### ISSUE TITLE
Proposal for decoupling module settings from core.

### ISSUE THREAD

**Issue by petsagouris** [pyrocms/pyrocms#1122]
I have been thinking that the current situation of module settings isn't really ideal. 
Addon modules should implement their own settings pages while core modules are attached to the `/admin/settings` page.

I propose that each module takes care of their settings on their own and that the `/admin/settings` area (from the `settings` module) actually becomes a "Site configuration" area. The functionality for form validation and submission found in the settings module can be migrated to a library or a controller (a basic `Module_Settings_Controller` class comes to mind) so that everything can use the same interface for saving and retrieving their settings. I believe that this will make the whole UX in the admin area more streamlined.

(Up next in the pyro queue... submodules?!)

**Comment by RyanThompson** [comment]
This is a thing in 3.0.
