### ISSUE TITLE
Inline Editing

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#1474]
Hi guis ( @ryun ), been thinking about the inline edit feature since working on my Newsletters module and was thinking..

If it is not tooo far along, I would suggest utilizing an editing type consistant to what I am using for email templates.

Here is a link to the post, I will be adding an updated video later today.

The reason being is CKEditor can get effed up in odd places and my editor method would allow tight spots as well as odds n ends to be edited very easily.

The end result, I would hope, would be to allow ANYTHING with database content storage to be edited with the inline editor. I think the editing method I use for the new module would be best.. more versatile and less likely to f up the websites structure while using it..

This is in regards to the front end logic / appearance only.

And it's sexy looking..

http://www.pyrocms.com/forums/topics/view/17877

I am willing to share with anyone interested.

**Comment by huglester** [comment]
@RyanThompson this is really going to happen in 3.0?

**Comment by RyanThompson** [comment]
3.1

**Comment by RyanThompson** [comment]
Thinking about the syntax for handling identifying these editable areas based on FT.

`{% editable page.title span.title %}`

Could generate: 

`<span class="title" data-editable="pages::pages.title">{{ page.title }}</span>`

Thoughts?

**Comment by philsturgeon** [comment]
That's pretty much what I was thinking :)
