### ISSUE TITLE
Versioning pages so changes can be reverted

### ISSUE THREAD

**Issue by kirillinfinite** [pyrocms/pyrocms#1611]
Pages need to have versioning, so users can roll back to previous changes.

**Comment by RyanThompson** [comment]
This is handled by a separate module in 3.0 - unreleased / premium add-on but this is handled.

**Comment by BenWoodford** [comment]
1 year later I cannot find anything about a module for handling page revisions. Did it just never release?

**Comment by RyanThompson** [comment]
@BenWoodford this is still on the docket for a v3 item but it's not high in the totem poll. I don't have a release point for nailed down for it - ecommerce is a big one standing in the way before I can start working on something like this.

**Comment by benrogmans** [comment]
+1 👍 
Would be a great feature. Clients are telling me they love Wordpress for this
