### ISSUE TITLE
Change page type on existing page

### ISSUE THREAD

**Issue by jaminday** [pyrocms/pyrocms#2244]
Any plans to implement an option to change page type on an existing page? Currently (as far as I can tell) the only way is to delete the page and re-create it with the desired page type. I can see this becoming an issue down the track once pages start getting populated with content.

**Comment by huglester** [comment]
@RyanThompson probably in 3.0 only?

**Comment by RyanThompson** [comment]
Yep - Im working on this now - you'll obviously lose data but.. it's a start.
