### ISSUE TITLE
Watermarking images

### ISSUE THREAD

**Issue by foreachlt** [pyrocms/pyrocms#2272]
Hey,

I've started extending the Files library to enable watermarking, however, I'm having a bit of a problem with handling transparent PNGs while using Codeigniter Image Library - it just completely messes it up and it's doing my nut!

So I believe I've got a couple of options:

1. Create an Image library extension to handle watermarking
2. Use a third-party composer package

Also, the watermarking options would be controlled through the setting module, which will allow you to:

1. Specify the watermark image
2. Set the default position + offsets
3. Set the opacity
4. Anything else???

Any thoughts on this are welcome :)

Kasparas.

**Comment by huglester** [comment]
@RyanThompson probably close. THink in Imagine (in PyroCMS 3) will be able to handle this easily?

**Comment by RyanThompson** [comment]
Yep - built into the image class.
