### ISSUE TITLE
Lex Parser & conditional problem 

### ISSUE THREAD

**Issue by jeroen-net** [pyrocms/pyrocms#2274]
I also posted this on the forum because I first thought it wasn't a bug. But now I believe it is.

In the head of the website I have this code:

    {{ if url:current == { pages:url id="24" } || url:current == { pages:url id="25" } }}
	...load some JavaScript
    {{ endif }}

'url:current' generates:
http://localhost/Websites/Atent/index.php/schade-melden 

'pages:url id="24"' generates
http://localhost/Websites/Atent/index.php/schade-melden 

Despite that both tags generate the same url, the conditional turns false.

When I compare 'url:current' with the above url, the result of the conditional is true.
When I compare 'pages:url id="24"' with the above url, the result of the conditional is false.

The fact that the last test turns false, makes me believe the problem is 'pages:url '.

(The code worked perfectly with PyroCMS 2.1)

**Comment by huglester** [comment]
Hello,

maybe some of you have tried using this lex parser? 

https://github.com/pyrocms/lex

**Comment by RyanThompson** [comment]
Lex has it's wonkiness and is often times better if you use a plugin for things like this.
