### ISSUE TITLE
Dashboard Menu - New Module Menu Display Problem

### ISSUE THREAD

**Issue by dollardad** [pyrocms/pyrocms#2359]
version 2.2beta

When adding a custom module the top level menu displays 0 instead of the menu name ( in this example is "autobase'") and then adds the menu item to the dropdown.

![pyrocms_error](https://f.cloud.github.com/assets/204340/122781/b30d5478-6e8e-11e2-9307-3606246c52d2.jpg)

details.php

class Module_Autobase extends Module
{
    public $version = '2.0';

```
public function info()
{
    return array(
        'name' => array(
            'en' => 'Autobase',
        ),
        'description' => array(
            'en' => 'Autobase Settings',
        ),
        'frontend' => true,
        'backend' => true,
        'menu' => 'autobase',
        'sections' => array(
            'settings' => array(
                'name' => 'Settings',
                'uri' => 'admin/autobase',
            ),
        ),
    );
}
```

**Comment by syamsudar** [comment]
can you show me how to show the menu name ?
it just shows '0'..

thanks
