### ISSUE TITLE
Error 500 under PRODUCTION evnironment

### ISSUE THREAD

**Issue by kdeng** [pyrocms/pyrocms#2366]
Hi,

I have cloned the latest PyroCMS 2.2 from Github, and setup a brand new website with the default installer. But, when I switch the environment from DEV to PROD, and get a 500 error page.

The error message is :

An Error Was Encountered [ 500 ]
Unable to load the requested language file: language//choice_lang.php

So. could someone help to have a look on this issue? and let me know if there is any solutions. Also, I am happy to contribute my works if someone can give me a direction. 

Many thanks
Kefeng

**Comment by huglester** [comment]
@RyanThompson please close this.
guys if you have more problems please create new issue. we will try to fix
