### ISSUE TITLE
Media embed plugin in CKEditor 4

### ISSUE THREAD

**Issue by rmwebs** [pyrocms/pyrocms#2458]
Any chance we can get a media embed plugin integrated into CKEditor 4 for a future release? I can see it being pretty handy for blog posts and such where you want to insert youtube videos. 

https://github.com/starfishmod/jquery-oembed-all

That one seems to work well on CKEditor 4 - been using it in a custom system for a few weeks and seems to work fine.

**Comment by huglester** [comment]
@RyanThompson this probably can be closed? This probably won't be included?

**Comment by RyanThompson** [comment]
Yep - I agree with @ryun here - this can be included on it's own very easily. On that note though after 3.0 release Ill be revisiting the CKeditor thing. Perhaps adding more core features (the kitchen sink).
