### ISSUE TITLE
Relationship field outputting numbers not page titles

### ISSUE THREAD

**Issue by semibad** [pyrocms/pyrocms#2483]
Setting up a relationship-type field pointing to a page outputs a dropdown of numbers rather than a page title (for instance, if there are three pages of the target type, the dropdown shows 1, 2 and 3). Using the field tags in the page template just outputs the selected number. Screengrab attached.

![relationship-issue](https://f.cloud.github.com/assets/1047073/190308/1d5f4910-7ee0-11e2-9f8b-1449dd6c23a5.png)

**Comment by AspireToCodeBetter** [comment]
@semibad Did you ever manage to get a solution to this? I've come across the same issue now!

**Comment by RyanThompson** [comment]
Try a new installation or updating he title column value in the DB for pages. It's been remedied a while ago ^_^

Sent from my iPhone

On Oct 6, 2015, at 8:35 AM, AspireToCodeBetter <notifications@github.com<mailto:notifications@github.com>> wrote:


@semibad<https://github.com/semibad> Did you ever manage to get a solution to this? I've come across the same issue now!

-

**Comment by RyanThompson** [comment]
Uh oh.. This is 2.2 so scratch that

Sent from my iPhone

On Oct 6, 2015, at 8:35 AM, AspireToCodeBetter <notifications@github.com<mailto:notifications@github.com>> wrote:


@semibad<https://github.com/semibad> Did you ever manage to get a solution to this? I've come across the same issue now!

-

**Comment by AspireToCodeBetter** [comment]
@RyanThompson so ... is there a way in 2.2 to  "update he title column value in the DB for pages" :-)

**Comment by RyanThompson** [comment]
ya it's the same table actually so that's a good idea - default_streams -> title_column

Change it to"title" I believe is the main page title field slug.

**Comment by amityweb** [comment]
I have this issue too... I added title as the title_column in the default_data_streams table for stream_name Default, but still shows numbers in the relationship field.

**Comment by amityweb** [comment]
Dont know if its the best way to do it but on line 70 of cms/modules/stream_core/field_types/relationship/field.relationship.php I changed the code inside the foreach to the following (in fact I created a new fieldtype from this so as not to mess with core, until this is fixed)

```
if($stream->stream_name == 'Default')
{
	$page = $this->CI->page_m->get($row->id);
	$choices[$row->id] = $page->title;
}
else
{
	// Need to replace with title column
	$choices[$row->id] = $row->$title_column;
}
```
