### ISSUE TITLE
2.2/develop - Streams Issue with Relationship and Multiple Relationship

### ISSUE THREAD

**Issue by jHoldroyd** [pyrocms/pyrocms#2508]
This one is a little hard to explain but when you attempt to get entries from a stream that has a relationship, when it queries the relationship if that contains another relationship or multiple relationship it causes a MySQL error. It doesn't seem to correctly identify them as a relationship and attempts to retrieve the data directly from the parent table rather than doing joins, etc.

For instance if you try to get data from A that references B and B has a reference of Item on C it will try to get B.Item rather than C.Item causing the unknown column error.

It seems to be an issue with the way query_build_hooks is building the sub-query in the relationship field, I took a quick look at it but really not sure where to start with fixing it.

**Comment by RyanThompson** [comment]
Vastly improved in 3.0
