### ISSUE TITLE
Simple wysiwyg not expanding to full size.

### ISSUE THREAD

**Issue by wernerwerks** [pyrocms/pyrocms#2575]
The simple wysiwyg textarea is not expanding to full height. It reads that it should be 30 rows, but it's only opening to about 10.

Occurring in Safari 5.1.7 and Mac Firefox 19.0.2. I haven't checked in Chrome, ie or others.

**Comment by huglester** [comment]
@RyanThompson  close?

CKeditor was updated to version 4.4.7 i 2.2/develop branch. Le'ts hope this is fixed :)
