### ISSUE TITLE
Standardize language codes.

### ISSUE THREAD

**Issue by mdentinho** [pyrocms/pyrocms#2584]
It seams like the **/system/cms/config/language.php** file have no standard for the language codes.

Here are some examples:
```php
'codes'        => array('en', 'english', 'en_US'),
'codes'        => array('csy', 'czech', 'cs_CZ'),
'codes'        => array('dutch', 'nld', 'nl-NL'),
```

Sometimes the code is using two words, sometimes it is using three. Sometimes it's exchanged with the english name for the language, like in the dutch example.

Also, the language-country code is using underscore instead of hyphen, which is the standard for the HTML 'lang' attribute and probably the best option for HTML document internationalization.

I've found in the history of commits that it was changed to underscore to better serve the Facebook API. So my suggestion is to separate the language code from the country code by using the first element of the array to the language code (as it seams to be the purpose now) and leave the third one only for the country code.

With this suggestion, if someone decide to create a British english translation, it would look like this:
```php
    'en' => array(
        'name'        => 'American English',
        'folder'    => 'english',
        'direction'    => 'ltr',
        'codes'        => array('en', 'english-american', 'US'),
        'ckeditor'    => null
    ),
    'gb' => array(
        'name'        => 'British English',
        'folder'    => 'british',
        'direction'    => 'ltr',
        'codes'        => array('en', 'english-british', 'GB'),
        'ckeditor'    => null
    ),
```

Don't know if the **'en'** and **'gb'** codes for PyroCMS are the best options, but I think that this change will make internationalization a lot easier and will work either with HTML or with Facebook API.

But I think the best way would be to include the countries variations of languages inside the language array, like this:

```php
    'en' => array(
        'us' => array(
            'name'        => 'American English',
            'folder'    => 'english',
            'direction'    => 'ltr',
            'codes'        => array('en', 'english-american', 'US'),
            'ckeditor'    => null
        ),
        'gb' => array(
            'name'        => 'British English',
            'folder'    => 'british',
            'direction'    => 'ltr',
            'codes'        => array('en', 'english-british', 'GB'),
            'ckeditor'    => null
        ),
    ),
```

But I know that this could cause a lot of changes in the core code of the framework, so it's just a suggestion for the future.

Thanks

**Comment by huglester** [comment]
@RyanThompson close :) 
guys if have mire info please open new issue.
