### ISSUE TITLE
Page CSS & JS editors loading Page Type CSS & JS when 'Save as Files' checked

### ISSUE THREAD

**Issue by toothydesign** [pyrocms/pyrocms#2656]
When a Page Type has 'Save as Files' checked, Pages based on it are loading the Page Type CSS & JS into the editor. 

When the Page Type has blank CSS or JS, the Page CSS & JS editors will also be blank.

This is causing accidental overwrites of Page CSS/JS when Page content is updated.

(Using v2.2.0 Professional in a multisite setup)

**Comment by huglester** [comment]
can you please be more specific, on what is going on?

**Comment by epicurius7** [comment]
Noticed this as well. If a page type has 'Save as files' ticked, it overrides the Page's css & js content when you open it for editing. Still saves and displays what you enter. Just editing after the fact is bugged.

Suggested fix: If the Page css/js is null, then it is OK to fill it with the Page Type css/jss:

/system/cms/modules/pages/models, lines 209-217:

            // CSS/JS
            foreach (array('css', 'js') as $ext)
            {
                $page->db_originals->$ext = $page->$ext;
                if ($page->$ext == null && file_exists($folder.$page->{$pt_slug_var}.'.'.$ext))
                {
                    $page->$ext = read_file($folder.$page->{$pt_slug_var}.'.'.$ext);
                }
            }

This way you get the Page Type's css as default, but you can override it on a page level.
