### ISSUE TITLE
Page Type with a conditional on a WYSIWYG Page Field breaks LEX - Parse error: syntax error, unexpected T_LNUMBER 

### ISSUE THREAD

**Issue by cheeseytoastie** [pyrocms/pyrocms#2680]
Pyro v 2.2
If I create a new page type with the template layout: 

{{ if heading1 }} 
<h1>{{ heading1 }}</h1>
{{ endif }}
{{ if heading2 }} 
<h2>{{ heading2 }}</h2>
{{ endif }}
{{ if content }} 
{{ content }}
{{ endif }}

And paste the content (not the heading) from here: http://duffa.org/constitution.php

Then I get 
A PHP Error was encountered

Severity: 4096

Message: Object of class stdClass could not be converted to string

Filename: Lex/Parser.php

Line Number: 351

A PHP Error was encountered

Severity: Notice

Message: Object of class stdClass to string conversion

Filename: Lex/Parser.php

Line Number: 351

I've a funny feeling it might be something "in" the content as I've tried really long strings and they looked fine. I've cleansed the content in notepad etc and it still does it?!  You'll note that the if else around the content field is not required in my simple example but I was cutting it back until I found the breaking point.  If I take the if else away and just output the content then it's fine.

**Comment by strandoo** [comment]
@caex: Your plugin worked perfectly. Thanks!

**Comment by huglester** [comment]
@RyanThompson close?

I think no-one gonna look at this Lex stuff atm, since it is absolete?

**Comment by RyanThompson** [comment]
Ya I don't care to open it up - it's a SHIT ton of regexp
