### ISSUE TITLE
Admin menu css helpers.

### ISSUE THREAD

**Issue by berbecki** [pyrocms/pyrocms#2694]
It would be good if the Administration Panel menu had more classes defining the statuses as:
current
has_current

The fact that the parent does not have the status of has_current impedes its modifications.

**Comment by huglester** [comment]
@RyanThompson probably can be closed. This, anyhow, will be easyli doable in 3.0 (if not yet done ;))

**Comment by RyanThompson** [comment]
Yap - way ahead of ya guys
