### ISSUE TITLE
Adding "unique id" to LEX tags for nested matching tags

### ISSUE THREAD

**Issue by chadwithuhc** [pyrocms/pyrocms#2698]
I've been seeing a lot of people having the need for nested tags in LEX which use the same name. For example:

```
{{ children }}
  ...
  {{ children }} ... {{ /children }}
{{ /children }}
```

Do you think we could add something like a unique ID to handle the correct open / closing of tags?

```
{{ children#id1 }}
  ...
  {{ children#id2 }} ... {{ /children#id2 }}
{{ /children#id1 }}
```

Or is it something as simple as fixing a Regex to properly nest tags?

**Comment by huglester** [comment]
this is good point. But PyroCMS3 is going to use Twig whichi should solve dozen of similar problems..

@RyanThompson close probably?

**Comment by RyanThompson** [comment]
Yep
