### ISSUE TITLE
Having some issues with CKeditor when i move from localhost to hosted

### ISSUE THREAD

**Issue by darylthornhill** [pyrocms/pyrocms#2699]
Hello,

Having some issues with CKeditor when i move from localhost to hosted.

Works fine locally, as soon as I move it to the server I am getting these issues in console and the editor doesnt appear. It also breaks the JS.

Uncaught SyntaxError: Unexpected identifier ckeditor.js:539
Uncaught ReferenceError: CKEDITOR is not defined jquery.js:6
Uncaught SyntaxError: Unexpected identifier ckeditor.js:539
Uncaught ReferenceError: CKEDITOR is not defined jquery.js:6
Uncaught TypeError: Object [object Object] has no method 'ckeditor' 8:96

**Comment by anthosey** [comment]
Hi, I'm having a similar experience with ckeditor, it works well on local machine but failed to load when moved to production server. 

I have recopied all the files to ensure no corrupt file is in there. 
I have gave full permission to Network Service user, yet it doesn't work,  please help.
