### ISSUE TITLE
Adding "static" data to LEX vars

### ISSUE THREAD

**Issue by chadwithuhc** [pyrocms/pyrocms#2719]
I think it'd be nice for LEX to be able to handle common information about variables or specifically arrays when parsing. Examples could be current item count, total, first, last, etc.

Code Example:

```
// run code if the final loop item
{{ looped_var }}
  {{ if this::count == this::total }}Last item{{ endif }}
{{ /looped_var }}

// same thing easier
{{ looped_var }}
  {{ if this::last }}Last item{{ endif }}
{{ /looped_var }}
```

Thoughts?

**Comment by huglester** [comment]
@RyanThompson I think you are not up to it? thank GOD pyro3 has twig so we will have less similar issues!!!

**Comment by RyanThompson** [comment]
Bleck
