### ISSUE TITLE
Copy/Paste Issue with CKeditor in Pyro 2.2.1

### ISSUE THREAD

**Issue by ikoniqoz** [pyrocms/pyrocms#2731]
I have a Page Type with a number of WYSIWYG/Simple fields. If I copy text from one field and paste it into another, the pasted content gets wrapped in a span tag which applies a font size of 13px.  This auto application of the span needs to be stopped/prevented if possible. 
This was discussed in the 2.2 forum https://forum.pyrocms.com/discussion/24132/page-type-fields-get-wrapped-in-a-span-with-stylefont-size-13px#latest

**Comment by huglester** [comment]
After playing for several hours with ckeditor today, I came up to the sollution: https://github.com/pyrocms/pyrocms/issues/3286#issuecomment-99073973 (well it actuallly has some more plugins packaged we use, but I will strip them off if everything is ok.)

I think all of you had the problem with pyroimage and pyrofiles plugins not working? if so, probably the  solution would be to add : 
`config.allowedContent = true;`

because ckeditor startig from some 4.x version has some filter enabled by default with strips whole bunch of html tags.

p.s. sorry for flooding, just wanna more people to test this stuf. because we were strugling with this problem for far too long.

**Comment by RyanThompson** [comment]
@ikoniqoz can you test out the suggested fix here? Seems like you are the most knowledgeable on it thus far ^_^

**Comment by ikoniqoz** [comment]
Thanks Ryan for the followup. 
Thanks also to @huglester for the work put in. Here is what I have experienced today.
My environment is Win7 SP1 and kept up to date with M$ updates.
1. I used a Pyro Comm 2.2.5 dev site I am working on for the following: Renamed default ckeditor.js file and added ckeditor.js from 4.1.3. Added the config setting as above.
Using Google Chrome Version 42.0.2311.135 m,  I opened up the Pyro2.2.5 site and  opened up Pages -> Page Content to access Page Body. I can confirm that I can add images and files which is a good start. I can copy/paste a para of text without it getting totally scrambled which is another big improvement. However, I still get a span wrapped around the pasted text with "font-size: 13px; line-height: 20.7999992370605px;" added. 
Firefox 37.0.2 shows a blank empty space where the editor should be displayed.
IE 11.0.9600.17728 is the same as FF above.

2. Replaced the 4.1.3 version of CKeditor with 4.2 - same as above.
3. Replaced the 4.2 version with 4.4.5 - same as above.

Keen to learn more from @huglester on what further  details he can provide..

**Comment by ikoniqoz** [comment]
I have now downloaded the full copy of CKeditor from Dropbox that @huglester provided in the other #3286 and can confirm that by replacing the full ckeditor directory (DUH!) as was noted in #3286  that in FF and IE CKeditor so far, appears to function as it should. However in Chrome, I am still getting the span with font-size and lineheight added.
So this is a major step forward. Thanks to @huglester  
One other point regarding the config settings is that the CKeditor team got the config.enterMode and config.shiftEnterModes reversed. They should be:
	config.enterMode = CKEDITOR.ENTER_P;
	config.shiftEnterMode = CKEDITOR.ENTER_BR;
which is how they had always been up til v4.

**Comment by RyanThompson** [comment]
Have you tried clearing your caches super good on Chrome just in case? Usually Chrome is the most forgiving.


On May 5, 2015, at 8:48 PM, John Ashton <notifications@github.com<mailto:notifications@github.com>> wrote:


I have now downloaded the full copy of CKeditor from Dropbox that @huglester<https://github.com/huglester> provided in the other #3286<https://github.com/pyrocms/pyrocms/issues/3286> and can confirm that by replacing the full ckeditor directory (DUH!) as was noted in #3286<https://github.com/pyrocms/pyrocms/issues/3286> that in FF and IE CKeditor so far, appears to function as it should. However in Chrome, I am still getting the span with font-size and lineheight added.
So this is a major step forward. Thanks to @huglester<https://github.com/huglester>

One other point regarding the config settings is that the CKeditor team got the config.enterMode and config.shiftEnterModes reversed. They should be:
config.enterMode = CKEDITOR.ENTER_P;
config.shiftEnterMode = CKEDITOR.ENTER_BR;
which is how they had always been up til v4.

**Comment by ikoniqoz** [comment]
OK - Good point. Thanks Ryan.
Did that. Diff is that I now get just "line-height: 20.7999992370605px;" added as an inline style inside the added span. The font-size has gone.

Remembered this:  https://dev.ckeditor.com/ticket/9998#comment:52 and cleared my cache again, edited the default contents.css file by changing line-height on line 24 from "1.6em" to "normal" which appears to have resolved the insertion of the span and the line height of 20.xxxpx.

Beauty! Maybe @huglester  has worked around this issue as well ??

Interested in what others may experience after applying the fix from @huglester and editing the contents.css file.  Me ? I'm excited!

**Comment by huglester** [comment]
@ikoniqoz thanks for the feedback. so you offer to only change this:
```
config.enterMode = CKEDITOR.ENTER_P;
config.shiftEnterMode = CKEDITOR.ENTER_BR;
```
and ` line-height` to `normal`?

We will be testing this on fresh projects this week, if I find issues, I will post back!

**Comment by huglester** [comment]
@ikoniqoz actually I don't have any more details. I must say I did not do too much, to make it work. But took around 3 hours make this stuff done. main problem which was not working, is the pyroimages or something like that. It appears it was just stripping the html I was trying to insert. And the fix actually was quite easy: `config.allowedContent = true;`

**Comment by RyanThompson** [comment]
PR PR PR!!

**Comment by ikoniqoz** [comment]
@huglester By installing your dropbox version and my additional edits  thats all I have done.  We have resolved a number of issues by installing the latest version and seem to have resolved a number of issues on Win7 with Chrome, FF and IE  !!

Your tip about config.allowedContent was the thing that resolved the pyrofiles and pyroimages issue. I will do another check on my browsers later just to be doubly sure.

**Comment by ikoniqoz** [comment]
Yes - need a PR on this - I want to do another check across the browsers I use for pyroimages and pyrofiles later tonight then report back.

**Comment by ikoniqoz** [comment]
OK - I have tested this again on a new install of Pyro 225 Community and can verify:
1. Can edit text OK including copying and pasting a para without junk span being added.
2. Can upload images using pyroimages.
3. Can upload files using pyrofiles.
4. A further benefit that comes from CKeditor 4.4.7 is that the entry of the initial text gets included within para tags. This was an annoyance that was recently mentioned in #3468.

All tests were done using: Win7 with IE11, FF 37.0.2 and GGL Chrome 42.0.2311.135 m.

So, if @huglester can do another PR that includes the line-height fix and changes to CKEDITOR.ENTER_P and CKEDITOR.ENTER_BR mentioned above we will have resolved some long standing issues. 
HOORAY!

**Comment by huglester** [comment]
Sure thing @ikoniqoz 

since you're so active, I also will be and will start preparing the PR now, I will try to keep plugins probably only ones, which are currently in the setup? 

I should probably use the ckeditor-builder for this

**Comment by ikoniqoz** [comment]
@huglester Many thanks for your excellent work on this. I have spent hours looking into these issues but never found a solution to the problems I was frustrated by til you came good with your work. Many thanks again!

**Comment by huglester** [comment]
@ikoniqoz I now try to build ckeditor, and then append changes. Strange thing is, that pyrocms install has 47folders inside

and ckeditor builder, building even FULL version, creates only 27 folders. maybe because it  is very optimized? 
Because if I am correct, we only need to copy pyrofiles, and pyroimages. with other modifications. so should I go with ckeditor standard as a base, or ckeditor full?:)

**Comment by RyanThompson** [comment]
Keep it consistent with what's there now.

**Comment by huglester** [comment]
@RyanThompson that's what I am trying to say.
for example, if you take it from here: https://github.com/ckeditor/ckeditor-releases/releases/tag/full%2F4.4.7 (releases) - it has 27 folders in plugins/ (I think they are compressed somehow into the main ckeditor.js file, because they don't have options or smth like that)

but if you take full, from here (DEV) - https://github.com/ckeditor/ckeditor-dev/releases/tag/4.4.7 - you got 97 folders :) 

so looking at this, I think, we need STANDARD ckeditor pack + pyrocms plugins (this page states: http://ckeditor.com/builder - that standard has 48 plugins (generated package will have ~27 folders in plugin/ ). but if download UN-OPTIMIZED - it has 51folders. 

So I will check that, and probably will go with it :) but I think optimized is better for us? or for probable less BC breaks - let's stick with unoptimized version but with 1:1 folder structure?

**Comment by marcogrueter** [comment]
You guys rock. That's probably the most annoying thing in PyroCMS right now ^^

@RyanThompson can you give some input on the upgrade process for your Newsletter module?
The editor there is also a bit icky. I'll certainly try to upgrade it with the files from this PR, but maybe you have some cavets in mind.

**Comment by huglester** [comment]
Hello guys,

can you test this PR please? https://github.com/pyrocms/pyrocms/pull/3480

Need some feedback :)

**Comment by ikoniqoz** [comment]
@huglester  I see that there are some issues with the PR.  Another option would be to use Dropbox again with a copy of the ckeditor directory for Pyro..

**Comment by huglester** [comment]
@ikoniqoz what are the issues? Yeah I can actually just replace it with dropbox content...

**Comment by ikoniqoz** [comment]
@huglester  The issues are related to the test failure.They may not be deal-breakers though.  In the meantime, if you can dropbox the ckeditor directory, I will try it out and report back.

**Comment by huglester** [comment]
strange that you have problems.. I have diffed the path with my olddropbox and the difference I see that I did not have images/spacer and themes/ in it...

please try this: https://www.dropbox.com/s/pqmv0fa03v0b85d/ckeditor-new.tar.gz?dl=0 (it is an archive from PR)

**Comment by ikoniqoz** [comment]
Thanks for the file. Will post back once I have loaded and tested.

**Comment by RyanThompson** [comment]
@marcogrueter - regarding the newsletters module - the only thing is I included it in a standalone file that was injected into an iframe (not the prettiest). I think you could likely copy / overwrite the library in the module with the PR one and it'll work just fine. Other than location it's no different. Simple usage as I recall.
