### ISSUE TITLE
Undefined variables error at index.php/blog

### ISSUE THREAD

**Issue by zxcqwe** [pyrocms/pyrocms#2734]
hi, i recently installed the v2.2.1 via cpanel and when i clicked on the Blog link on the main menu bar of the PyroCMS Theme, i got the following error msg...

A PHP Error was encountered
Severity: Notice
Message: Undefined variable: conifg
Filename: models/row_m.php
Line Number: 1721

A PHP Error was encountered
Severity: Notice
Message: Undefined variable: pag_method
Filename: models/row_m.php
Line Number: 1745

A PHP Error was encountered
Severity: Notice
Message: Undefined variable: pag_uri_method
Filename: models/row_m.php
Line Number: 1754

A PHP Error was encountered
Severity: Notice
Message: Undefined variable: pag_query_var
Filename: models/row_m.php
Line Number: 1766

**Comment by huglester** [comment]
@RyanThompson close
