### ISSUE TITLE
Theme Options (Feature)

### ISSUE THREAD

**Issue by snlbase** [pyrocms/pyrocms#2748]
Hello, 

currently developing a new theme i've run into an ordering issue with options. 
As it is right now, the theme options are just listed one after another. 
In this case i am making a theme with 20+ options, so this will result in epic scrolling. 

A solution here would be columns and tabs for the options. And i just wonder if this can be implemented in the next version. 

By tweaking the view in system/cms/modules/addons/views/admin/themes/options.php: 

![multicolumn](https://f.cloud.github.com/assets/526088/513745/02ec929a-be46-11e2-8183-8dee82460542.png)

Tweaking further (using the class tabs): 

![multicolumn with tabs](https://f.cloud.github.com/assets/526088/513750/306607d8-be46-11e2-9fc2-cb903a4bc848.jpg)

But of course this is just the layout, to give you guys an idea so the tabs don't work. 
Would be really a step forward for the organization, if one could tab the options (create tab categories). 

Can we have tabbed theme options please? :)
Details.php should include tabs for options so these can be grouped imho.

P.S.: If something is not posted correctly, sorry. I am new to github. 
Thank you in advance. If you need more information let me know.

Greetings,
snlbase

**Comment by huglester** [comment]
@snlbase if you are up for it?
But I think it is not worth it, since PyroCMS3 is almost there?

@RyanThompson probably close this. and if there is interest here, I don't see anything against it , if there will be well designed PR with migration if needed!

**Comment by RyanThompson** [comment]
This is in 3.0 and is so easy it's stupid. I wouldn't bother.

**Comment by RyanThompson** [comment]
And no need for dumb reindexing either..
