### ISSUE TITLE
Feature Request: Remember last image directory.

### ISSUE THREAD

**Issue by danrichards** [pyrocms/pyrocms#2752]
I have a guy doing design with a pages module and when he's adding images, it would be nice if it remember the last directory you were browsing (just like Windows or any modern OS does).

This feature would be pretty quick and easy to implement.

Thanks!

Dan

**Comment by huglester** [comment]
@RyanThompson I think it can be done with cookies. but I think it is not worth adding - 3.0 is on it's way. Probably close unless @danrichards wants to do a PR ?: )

**Comment by RyanThompson** [comment]
Eh.. this kinda steps on some toes too. Might be a good idea though.
