### ISSUE TITLE
Feature: Add the ability for nested pages:children tag

### ISSUE THREAD

**Issue by yckart** [pyrocms/pyrocms#2769]
In some cases it would really helpful get the ability to nest the `children`-tag. Currently you get just something like this: `nested_looped_tags_ba6277cad1a5528895d5013f3f84a6a5`.

```
{{ pages:children id="1" }}
    {{ pages:children id="[[ id ]]" }}
        <h2>{{ title }}</h2>
    {{ /pages:children }}
{{ /pages:children }}
```

**Comment by huglester** [comment]
@yckart hey. if you are up for a PR go on! @RyanThompson will accept. Otherwise we probably are closing this.

3.0 is our new friend which is very close

**Comment by RyanThompson** [comment]
Reopen if you're up for it.
