### ISSUE TITLE
Bug in Asset.php class. Does not handled remote files correctly.

### ISSUE THREAD

**Issue by lordemanonsr** [pyrocms/pyrocms#2774]
The ability to add_asset using a remote file URL is broken.

The following lines need corrected in the Asset.php file

Line 1114 
      $remote = (strpos($path, '//') !== false);

should read
      $remote = (strpos($file, '//') !== false);

It needs to check the provided file for any '//' characters to determine if it is a remote URL or not.

Line 1122
At this point it is determined to be remote so the return should only be returning the file.

     return array($path.$folder.$file);

should read
     return array($file);

**Comment by huglester** [comment]
@RyanThompson  close
