### ISSUE TITLE
Custom Navigation Level 3

### ISSUE THREAD

**Issue by abadiwidodo** [pyrocms/pyrocms#2792]
How to write custom navigation level 3 and so on?

		{{ navigation:links group="sidebar" }}
		<div class="{{class}}">
			<a href="{{ url }}">
			<div class="nav">
				{{ title }}
			</div> </a>
			{{ if children }}
			<div class="subnav">

				{{ children }}
				<div>
					<a href="{{ url }}">{{ title }}</a>
					[HOW TO SHOW THE CHILDREN OF THIS?]
				</div>
				{{ /children }}

			</div>
			{{ endif }}
		</div>
		{{ /navigation:links }}

**Comment by vacoo** [comment]
Thank you very much for your decision. Problem solved for a week)
