### ISSUE TITLE
Modules Files

### ISSUE THREAD

**Issue by matteocaccioni** [pyrocms/pyrocms#2793]
Hi, I have a problem with 'pyrocms'. When i insert an image in the form files the image charged doesn't display so the print review disappears. I tried to check the file access and it creates a folder named 'cloud_thumb' but this folder doesn't exist anywhere. What's happened?We aren't using cloud service. Thank you for your help!!

**Comment by huglester** [comment]
@RyanThompson close. no there was no feedback
