### ISSUE TITLE
Add favicon to Admin / Docs

### ISSUE THREAD

**Issue by danrichards** [pyrocms/pyrocms#2796]
I have the admin pinned 24/7, most of the time with multiple others pinned.

Can a favicon be setup for the pyro admin?

Can a favicon also be setup for pyro docs [perhaps slightly different than the pyro admin one]?

If the favicons were managed from the settings module (with defaults), that'd be even more neato.

Please excuse my OCD.

Thanks,
![favicon-pretty-please](https://f.cloud.github.com/assets/470255/624473/376bc292-cf86-11e2-882d-45445bdf50ed.png)

Dan

**Comment by huglester** [comment]
@RyanThompson maybe put something like this to backend ? https://www.pyrocms.com/favicon.ico

**Comment by RyanThompson** [comment]
Already have one - pry should polish it up a bit though.
