### ISSUE TITLE
SVG uploads "file type not allowed"

### ISSUE THREAD

**Issue by james2doyle** [pyrocms/pyrocms#2801]
I have not been able to allow SVG uploads despite adding the SVG mime type, adding the SVG to allowed files, and adding the SVG mime type to my .htaccess file.

Maybe I am missing a step but it doesn't seem to be the case.

Here is my "request payload" screenshot from chrome. As you can see it is treating the file properly...

![screen shot 2013-06-14 at 5 12 50 pm](https://f.cloud.github.com/assets/1425304/656810/6572f1a4-d537-11e2-9ea7-ea86992bd885.png)

**Comment by huglester** [comment]
@amityweb how did you solve this?

**Comment by RyanThompson** [comment]
This is a MIME issue BUT.. you MUST use your server CLI in some cases to see what mime it's being interpreted as.
