### ISSUE TITLE
Why do we need meta keywords and meta description?

### ISSUE THREAD

**Issue by webvitaly** [pyrocms/pyrocms#2802]
Google does not use meta data for years. Video - Matt Cutts about "Google does not use meta keywords and meta description" https://www.youtube.com/watch?v=jK7IPbnmvVU 

Google handles more than 92% of all search queries. Meta-keywords and meta-description are invisible for frontend users and mostly used to spam search engines. 

Meta data now is just a waste of time and space. 
Maybe it would be better to drop support for meta data in the admin section?

**Comment by huglester** [comment]
@RyanThompson close?

@webvitaly while I agree with you, many customers just "need" it. they just wnna change them.
Sometimes people use title for page title, and use meta title - with different text.

So I would say let's leave it as is.

**Comment by webvitaly** [comment]
@huglester our duty as web-developers not only to develop but also to educate customers. And sometime we should say "no".
Just imagine if customer will come to the developer of the car and ask him to add a microwave oven into every car just because he "need" sometime to heat the food inside of the car. The developer of the car will say "no" because this is useless and will explain why it is useless.
Same goes here.
If car developers will add every feature customers want - they will create a spaceship instead of the car.
If web-developers will add every feature into the CMS - it will be a feature monster.

**Comment by huglester** [comment]
I fully understand you.

But for example google often uses meta description to show in the results description, no?

What about other search engines?

For example we use keywords also in the search. So we search by body, keywords.

From my point of view I am for keeping it.

**Comment by webvitaly** [comment]
Just facts:
Meta keywords are totally useless for google.
Meta description used rarely.
Google handles about 90% of all search requests and dictate the rules on the market.

For example WordPress have no meta tags inside of the core. 
But if user will need it - he may extend it with the plugin. 
Pretty clever, because the majority will not need it and the core will be clean.

**Comment by RyanThompson** [comment]
I tend to agree here. When I was adding the meta_* fields to the V3 pages modules I couldn't help but wonder "Why is this even here..". As a developer I would typically take this from other input (substring / striptags of body for description, page title for meta title).

Let's see what @numerogeek about this one.

**Comment by numerogeek** [comment]
Meta keywords are indeed useless to Google. 
But meta description are not useless at all !
 Maybe Google don't use them with the bot, but the snippet you see in the search engine result page are the meta title (first line)  and the meta description (2 OR 3 lines). 

They serve to show the users a marketing headline to call the action. It shows the users that your website have the answer to their question. 

If meta seems cool, users click. 
If users click, Google knows it and the remember that "this page seems attractive to this particular request". And guess what Google gonna do then...? 

So metas does not help you ranking better. But if they are sexy enough for your users,  you 'll rank up.

**Comment by RyanThompson** [comment]
Case settled! Thanks ^_^
