### ISSUE TITLE
Allow custom Modules to register link types with Navigation Module

### ISSUE THREAD

**Issue by scottpledger** [pyrocms/pyrocms#2823]
I'm currently working on a simple wiki module and I would like users to be able to create navigation links to wiki pages more easily by creating a custom link type, but from what I see in system/cms/modules/navigation/views/admin/ajax/form.php, these are only hard-coded.

**Comment by huglester** [comment]
@scottpledger maybe you happen to create that and wanna share a PR ?:)

**Comment by RyanThompson** [comment]
This is a thing in 3.0
