### ISSUE TITLE
Bye jQueryUI

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#2825]
Who will miss it? In my current UI update - it's been removed and it's needs replaced already.

A lot of its components are replaced in parallel with Bootstrap and many that are not - I've replaced with HTML5 friendlier alternatives..

BUT.. This is pretty big. Sure it's got lots of cool stuff but IMO it's pretty invasive and they'll be obvious conflicts with methods.

Second, jQuery UI seems far less focused on mobile / HTML5-ness as well. Sortable for instance isn't even supported by mobiles.. Whereas a lot of the plugins developed around the bootstrap community take mobiles / HTML very seriously like a friggin religion.

Thoughts on this?

**Comment by huglester** [comment]
@RyanThompson close?

**Comment by RyanThompson** [comment]
For what it's worth we're using http://johnny.github.io/jquery-sortable/ and it's rad.
