### ISSUE TITLE
Cannot move page item UP in a long list of pages

### ISSUE THREAD

**Issue by amityweb** [pyrocms/pyrocms#2831]
I have a lot of pages on a site, several scrolls are needed to get to the bottom. When trying to move a page UP the list, to the top say (because new pages are added to the bottom), its quite difficult. I am on a Macbook Pro. What happens is you move it up to the top of your screen (the browser does not scroll up when you move it higher), then you manually scroll up, then when you go to move it up further again it magically moves itself back down (and the browser scrolls with it). 

Quite bizarre, I guess some JS issue, but quote annoying. 

To fix it I have zoom out to see most of the menu so I can move it up in two goes.

**Comment by huglester** [comment]
@RyanThompson close this. this will be addressed in 3.0 I think :)

**Comment by RyanThompson** [comment]
Fixed in 3.0

**Comment by flip3** [comment]
Great to hear that. Thanks so much for fixing the bug!
