### ISSUE TITLE
2.2 possible bug in files plugin :listing

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#2835]
sometimes (yes, sometimes. can't reproduce on demand) files:listing takes out all the images, even though i have spcified a folder.

https://gist.github.com/keevitaja/5892910

atm i have 3 folders and "sometimes" i get all the images from all folders. after refresh the problem goes away.

not sure, maybe it is my code.

**Comment by huglester** [comment]
@RyanThompson this is solved
