### ISSUE TITLE
CKEditor (WYSIWYG) not auto formatting to normal

### ISSUE THREAD

**Issue by alexborton** [pyrocms/pyrocms#2854]
Hi guys, 

Looks like the Advanced WYSIWYG CKEditor is not automatically wrapping text in P tags (Normal). 

I have checked through the CKEditor documentation and according to them, this is default functionality. 

I would not expect a user to select 'Normal' for all the paragraph text to create the P tags. 

Any advice would be appreciated!

Cheers

**Comment by huglester** [comment]
as stated here: https://github.com/pyrocms/pyrocms/pull/3480
this pr already fixes this. so @RyanThompson - close

thanks
