### ISSUE TITLE
Order navigation groups manually or alphabetically

### ISSUE THREAD

**Issue by flip3** [pyrocms/pyrocms#2859]
The navigation groups under website.com/admin/navigation are currently ordered by database ID or similar. If you have many navigation groups (e.g. for multiple languages), it becomes soon disorganized. It would be good to order them alphabetically (then you could also use 1, 2, 3, ... in the navigation group name for order) or manually similar as the drag'n'drop functionality for pages.

**Comment by huglester** [comment]
PR would be welcome to order them manually I think :) this would be best.
so most important are on the top. and others on the bottom

**Comment by RyanThompson** [comment]
3.0 uses a flat navigation that is sortable by setting / preference too. In some cases though it's best to simply override the view to set a client's specific ordered needs / display logic.

For 2.2.. Sortable would be cool but might be other things to focus on.
