### ISSUE TITLE
Template partials

### ISSUE THREAD

**Issue by jzmwebdevelopment** [pyrocms/pyrocms#2861]
Would be great if there was away that we could tell $template not to load variables like header footer via the custom module that extends the admin_controller.

**Comment by huglester** [comment]
probably we should close this. @RyanThompson

**Comment by gr8escapes** [comment]
Has it been resolved as I still have a system that is having the issue I opened?

**Comment by jzmwebdevelopment** [comment]
Has it been resolved as I still have a system that is having the issue I opened?

**Comment by RyanThompson** [comment]
You referring to frontend or backend? Either way you should be able to modify the template variable in due process.. Let me look around in 2.2 and see what's available.

**Comment by jzmwebdevelopment** [comment]
Backend I have a section thats been poorly built via an old developer so I am just trying to patch it - client on limited to no budget and it would work fine if I could kill the header and footer

**Comment by RyanThompson** [comment]
Somewhat hacky but you could include an asset that display: none'd them for starters / quickie patch.
