### ISSUE TITLE
Files modules when gzip compression is enabled

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#2864]
I ran across an interesting issue in the files module (admin) when gzip is enabled. The call to /admin/files/folder_contents fails when initially called and returns no response. I assumed that this was because something was being echoed before the actual response was being echoed. I was able to remedy this by adding

    ob_end_clean();

before

    echo json_encode(Files::folder_contents($parent));

in the folder_contents function of the files/controllers/admin.php file (around line 134).

I then noticed a similar issue with the cloud_thumb function. I was able to fix this by adding

    ob_end_clean();

before

    if ($file and $file->location !== 'local')

in the files_front.php file (around line 256).

I'm using pyro 2.2.1 Professional and was just wondering if you knew about this or if there was a better way to solve this issue.

**Comment by huglester** [comment]
@bloveless so it was  fixed in that pull request?:)

**Comment by RyanThompson** [comment]
Yep I remember this one.

**Comment by bloveless** [comment]
@huglester I haven't seen the issue again in a few years, so I'm going to assume that it is fixed.

**Comment by huglester** [comment]
nice! also did not ever met this problem. let's hope so!
