### ISSUE TITLE
Third-party modules : only first setting's title and description are loaded

### ISSUE THREAD

**Issue by tristanjahier** [pyrocms/pyrocms#2889]
Hi guys,

I recently discovered that I can localize settings, having a settings_lang.php file into my module.

But when I look at the settings, only the first setting has its title and description displayed. For the next ones, there is just the form input.

I tried to debug the index method of admin controller of Settings module, and I found out that other strings are properly loaded. The problem is that others settings aren't processed.

![settings](https://f.cloud.github.com/assets/1117304/868549/4ebcc1cc-f7ad-11e2-982d-fbe30a0a70e7.png)

**Comment by huglester** [comment]
Settings do not support multi language. so basicly you would need something like different settings key  for each language... 
or maybe choose type as checkboxes and posibility to (for example) enable some option in different language.

You can pass the 'options' to the settings as 'func::function_name' so you can pass dynamic params.

if need, I can give more examples.

**Comment by tristanjahier** [comment]
So how do you explain my first setting label is actually localized?

This is really weird but I actually gave up. I'm waiting for PyroCMS 3.
