### ISSUE TITLE
issue on editing fields for a page type

### ISSUE THREAD

**Issue by asecondwill** [pyrocms/pyrocms#2901]
I got this error on clicking edit for a relationship field on my page type. 

Fatal error: Call to undefined method Parameter_fields::link_uri() in /Users/willbarker/Sites/pyrodemo/system/cms/themes/pyrocms/views/admin/partials/streams/field_form.php on line 133

at url http://pyrodemo.r4/index.php/admin/pages/types/fields/2

i'm on php 5.4, mysql  using mamp on osx. 

I downloaded the cms to evaluate for a new client job.  Looks really good apart from a few visual issues.

**Comment by huglester** [comment]
@RyanThompson close
