### ISSUE TITLE
pyrocms wysiwyg insert image error

### ISSUE THREAD

**Issue by coatless** [pyrocms/pyrocms#2934]
Hello,

I'm using Chrome Version 28.0.1500.95 on OS X 10.8.4 with pyrocms v2.2.3.

When I try to insert an image via the built in image function with either the advanced or simple wysiwyg, I am unable to select the image. Here is what I see once I've navigated to the folder where the images are in:
![Loader](https://f.cloud.github.com/assets/833642/981931/cd8062c0-07a7-11e3-8d83-f4ff472b316e.png)

I pulled up console to receive the following debug:

Uncaught ReferenceError: config is not defined config.js?t=D3NA:14
26
Uncaught TypeError: Cannot read property 'isBlock' of undefined ckeditor.js:319
3
Uncaught TypeError: Cannot call method 'openDialog' of null plugin.js?t=D3NA:8
Uncaught TypeError: Cannot call method 'openDialog' of null plugin.js?t=D3NA:44
Uncaught TypeError: Cannot call method 'openDialog' of null plugin.js?t=D3NA:8
Uncaught TypeError: Cannot read property 'isBlock' of undefined ckeditor.js:319
20
Uncaught TypeError: Cannot read property 'isBlock' of undefined ckeditor.js:319
Uncaught TypeError: Cannot read property 'isBlock' of undefined ckeditor.js:319

**Comment by huglester** [comment]
If possible try this: https://github.com/pyrocms/pyrocms/issues/3286#issuecomment-99073973

it it will work, we will update ckeditor in PyroCMS 2.2.6 up to 4.4.7

**Comment by huglester** [comment]
@RyanThompson potentialy this can be closed?

**Comment by RyanThompson** [comment]
Reopen if problem continues on dev branch.
