### ISSUE TITLE
Problem with template parser

### ISSUE THREAD

**Issue by bsh** [pyrocms/pyrocms#2963]
Controller:

```php
class Test extends Public_Controller
{
    public function index()
    {
		$test_array = array(0 => array ('test' => 1));
		$this->template->set('test_array', $test_array)->build('index');
    }
}
```

View:

```
{{ test }}
{{test_array}}
	{{ test}}
	<br />
	{{ if test}} ok {{ else }} not working  {{ endif }}
	<br />
	{{ if test == 1 }} ok {{ else }} not working  {{ endif }}
{{/test_array}}
```

Output:
```
1
not working
not working 
```

Parsed as:
```
if (null): ok else: not working endif; 
```

Sample modul: https://dl.dropboxusercontent.com/u/4901980/test.zip

Linux, PHP 5.3.21, MySQL 5.1.70-cll, Apache/2.2.2.

**Comment by huglester** [comment]
@RyanThompson these are Lex issues? I am not able to fix those bizzare regexp :)

**Comment by RyanThompson** [comment]
Pull latest from Lex at best - going to close this for now. Reopen if this issue continues.

**Comment by huglester** [comment]
You mean from anomaly/lex repo?

**Comment by RyanThompson** [comment]
https://github.com/pyrocms/lex
