### ISSUE TITLE
Pagination on search results page is broken

### ISSUE THREAD

**Issue by philipschilling** [pyrocms/pyrocms#2975]
The pagination on the search results page is not working. It shows that the pages cannot be found:
https://www.pyrocms.com/search/results/2?q=pyro&lang=de
https://forum.pyrocms.com/discussion/24571/multilingual-search-results-page

**Comment by flip3** [comment]
Finally, I upgraded to 2.2.5, too. I removed the "Require an exact uri match?" checkmark on the "Options" tab. Now I don't get a "Page Missing" error when I click on the second page but it always shows the first 10 listings from the first page. I changed the URL for the search results page from /results/search to /search and in /system/cms/modules/search/plugin.php all strings from search/results to search. Maybe it's related with that if it's working for others like timtait.
