### ISSUE TITLE
2.3 Update field types with new features

### ISSUE THREAD

**Issue by obrignoni** [pyrocms/pyrocms#2983]
I am going through and updating field types with the new stuff. This is a list for me to keep track of my progress.

* Choice - Complete
* Country - Complete, untested
* DateTime - Needs work, should leverage Carbon class
* Email - Complete, untested
* Encrypt - Complete, untested
* File - In progress
* Field - In progress
* Image - Complete
* Keywords - Complete
* Merge Tags - Complete
* Pyro Lang - Complete
* Relationship - Complete, untested plugin use
* Slug - Complete
* Text - Complete
* Textarea - Complete
* URL - Complete, untested
* US State - Complete, untested
* User - Complete
* WYSIWYG - In progress
* Year - Complete

**Comment by huglester** [comment]
@RyanThompson or @obrignoni please close:)

**Comment by RyanThompson** [comment]
Yep - and Phil to provide a small FYI - getRelation can return any relation type class from Eloquent and uses the related config option for the model and any other configurable shiz: 

https://github.com/anomalylabs/relationship-field_type/blob/master/src/RelationshipFieldType.php#L37

https://github.com/anomalylabs/multiple-field_type/blob/master/src/MultipleFieldType.php#L70

All that method says is 1.) I am a relationship type field type and 2.) Here is the relation I am providing
