### ISSUE TITLE
template->append_js|css not working in frontend controllers

### ISSUE THREAD

**Issue by websmarts** [pyrocms/pyrocms#3008]
Pyrocms  2.2/develop branch

template->append_js and template->append_css work as expected from an admin controller but NOT from a frontend controller. They dont cause an error but nothing gets added to the html page.

**Comment by huglester** [comment]
can you please try it with current 2.2/develop please?

**Comment by RyanThompson** [comment]
Ima close this oldie for now - if they respond we'll catch up with them.

**Comment by wingdigby** [comment]
For anyone who find this, ref https://github.com/pyrocms/pyrocms/issues/1763.
Make sure in theme header file you have {{ template:metadata }} at end of header for any appends.
