### ISSUE TITLE
files module and IE10 problem

### ISSUE THREAD

**Issue by juliefull5** [pyrocms/pyrocms#3018]
Hi
noticed that after uploading files in IE10 into a folder it is impossible to upload further files without either refreshing the browser or going back into the folder tree and  starting again, the progress bar doesn't work and also the top navigation menu only shows arrows for where the drop down menus are ie missing the words "Content", "Profile" etc
Firefox & Chrome are fine but could do with a fix for IE please?

**Comment by huglester** [comment]
@RyanThompson probably close this? @juliefull5 PyroCMS 3 will be fully bootstrapped- so probably less of similar problems!
