### ISSUE TITLE
Adding Lex variable context to the plugin parameter parsing context

### ISSUE THREAD

**Issue by getu-lar** [pyrocms/pyrocms#3082]
This is somewhat related to the following forum post: https://forum.pyrocms.com/discussion/25026/bug-in-the-lex-parser

In short; I don't understand why inside a plugin parameter definition, it should not be possible to access the Lex context variables. Let's say we have in the current Lex context a variable "somevalue", why can't I use this variable as the value of a plugin parameter like so?

```
{{ somevalue }}
{{ my:plugin myparam="[[ somevalue ]]" }}
```

Of course, the technical reasoning behind this is clear: plugin parameters are not actually parsed by Lex like e.g. conditionals, instead this is done by the Plugin class' parse_parameter function where another completely separate Lex parser cycle is started - the necessary variable data is simply not available at this point.

I would argue that this is a design flaw and that it should in fact be possible to do that. Should you agree with that assessment, there are some potential solutions. I'll propose them in the order of "cleanest" to "least clean" solution:

1. I include this option just for completeness, since I've been wondering about that - completely replace the Lex parser with an (generated) LALR-Parser instead of relying on highly fiddly regular expressions for parsing of nested structures. I'm not familiar with parser generators in the PHP space, but I would hope that there is something similar to [Lex](http://en.wikipedia.org/wiki/Lex_programming_tool) and [Yacc](http://en.wikipedia.org/wiki/Yacc).

2. Update the Lex parser to allow it to process parameter values of callback tags (and probably also other parameters). Due to the regex-based nature of the Lex parser, this is probably going to be a bit difficult and have a high probability of introducing bugs.

3. Update the Lex parser to include the context variables in the callback parameter list. From there (MY_Parser), pass this data along to the plugin and through to the Plugin.parse_parameter function where the variables could then be included in the secondary Lex pass over the plugin parameters.

I've already spent some time looking into option three and as soon as I find the time I will create forks of the PyroCMS core and Lex parser to try this. Please let me know what you think about that and I'll be more than happy to invest some time into the solution.

**Comment by huglester** [comment]
@RyanThompson probably close? if we are not goign to fix that :(

**Comment by RyanThompson** [comment]
Bleck
