### ISSUE TITLE
Update to CKEditor 4.3 to allow inline widgets

### ISSUE THREAD

**Issue by FrediBach** [pyrocms/pyrocms#3090]
CKEditor 4.3 has a very useful feature that allows you to use widgets: http://ckeditor.com/addon/widget

I'm currently working on a module that would be a 100 times better if I could use this feature. If it doesn't brake anything, it would be super useful if we had this feature in a future version.

Here's some more information about it: http://ckeditor.com/blog/Widget-Tutorials-and-SDK-Published

**Comment by huglester** [comment]
@RyanThompson close probably. ckeditor updated
