### ISSUE TITLE
Admin theme - navigation.php - top menu bug

### ISSUE THREAD

**Issue by rarutu** [pyrocms/pyrocms#3091]
When u have a module and set in the details.php menu => 'hahaha' the top menu will display the index of the menu_items array instead of the correct label because of this error in logic in the navigation.php

if (is_array($menu_item))
{ ... }
elseif (is_array($menu_item) and count($menu_item) == 1)
{ ... }
elseif (is_string($menu_item))
{ ... }

the second if will never be executed because if the menu_Item is an array it will always validate the first if ... so switching the 2 ifs will be a fist step

One more thing .. the last if looks to me that it never gets trigger ... i think my module should have landed on the last if because menu is set to 'hahaha' ... so there are some logic conflicts in here u should take a look at

thanks,
Rares

**Comment by huglester** [comment]
@rarutu did you solve this?

@RyanThompson this seems a valid error for me. We could fix it for 2.2 I think

**Comment by RyanThompson** [comment]
PR
