### ISSUE TITLE
404 not loading, incorrect array merge

### ISSUE THREAD

**Issue by syosoft** [pyrocms/pyrocms#3093]
Not sure if this is due to the version of PHP I'm running vs when this was written, but the line located in  /system/cms/libraries/Template.php on line 963

return self::_load_view($theme_view, $this->_data + $data, $parse_view, $location);

causes $data['page'] to end up NULL when it's an object loaded with goodies before.

Simply reversing the order of the vars corrects the issue

return self::_load_view($theme_view, $data + $this->_data, $parse_view, $location);

I came across this issue when I was debugging why my 404 record was causing an error in my themes views/modules/pages/page.php template when looking for <?php echo $page->layout->body ?>

**Comment by huglester** [comment]
@RyanThompson close probably? no feedback.

And I can't remember having problems with 404 page?

**Comment by RyanThompson** [comment]
Might be specific to his install.. not sure what would be causing that. But ya 2.2 404's are A-OK for my sites right now.

**Comment by Sopico** [comment]
Hah, thanks for getting on this guys almost 2 years later. No worries thou, zero interest in continuing with pyro, was forced into it by a poorly thought out mgmt decision.

**Comment by syosoft** [comment]
Hah, thanks for getting on this guys almost 2 years later. No worries thou, zero interest in continuing with pyro, was forced into it by a poorly thought out mgmt decision.

**Comment by RyanThompson** [comment]
Hey thanks for taking the time out of your day to leave a comment like that - it's greatly appreciated.
