### ISSUE TITLE
email attachment double added to auto reply.

### ISSUE THREAD

**Issue by gotoplanfgoto** [pyrocms/pyrocms#3252]
When using the auto reply feature on the contact form, and an attachment field has been added, the attachment gets added to the auto reply, and will be added twice if an email is first sent to the site user. This was rectified by adding

$this -> ci -> email -> clear(TRUE);

on line 28 of cms/modules/templates/events.php

**Comment by huglester** [comment]
@RyanThompson you know something about it? I personally use swiftmailer to deliver emails :)

**Comment by RyanThompson** [comment]
Ya not sure - mind testing it real quick for the same behavior?

**Comment by huglester** [comment]
Not sure, really. I never used contact form plugin. I have some build some forms module, which work from this config: http://laravel.io/bin/9vbjR
and as I said, I am not using CI email :( had too many trouble with it...

**Comment by RyanThompson** [comment]
Closing this for now - pretty old. I've done attachments before and have never had duplicates.
