### ISSUE TITLE
Navigation plugin wrongly assigns has_current on menus 3+ levels deep

### ISSUE THREAD

**Issue by aidanwatt** [pyrocms/pyrocms#3265]
This line can match a url part rather than the whole url...

```
strpos($wrapper['children'], $current_link)
```

/system/cms/modules/navigation/plugin.php line 290

So if the user is on a parent page it is possible for a child of a child to match the current and the child will be assigned has_current.

**Comment by huglester** [comment]
@RyanThompson close probably. At least someone will PR ;)

**Comment by RyanThompson** [comment]
Id be surprised if this was still an issue with some small patches that have been made - reopen if so.
