### ISSUE TITLE
Pyro 2.2.3 Will Not Install 

### ISSUE THREAD

**Issue by vincej** [pyrocms/pyrocms#3269]
The install does not complete. If you go to your site ie localhost/mysite You get an error message that the default groups are missing from the sql. 

https://drive.google.com/file/d/0B5elaUk7GlRoVXJ6cHJMUEZvdjQ/edit?usp=sharing

The default .sql file in the installer does not contain an entry for the default groups. 

If you want more detailed explanation of the steps to replicate this go to: 

https://forum.pyrocms.com/discussion/25525/another-install-error-this-one-is-real#latest

**Comment by benawv** [comment]
hello guys, in my case change value on max_execution_time on php.ini solve this case. I hope it helps
