### ISSUE TITLE
PyroCMS 2.2.4 CKeditor prblem

### ISSUE THREAD

**Issue by ikoniqoz** [pyrocms/pyrocms#3286]
If you copy or cut some text and past it elsewhere in CKeditor (WYSIWYG mode), the pasted text gets a style with font-size: 13px applied to it.  

This issue was reported when we went from 2.2.2 to 2.2.3. I had hoped it would have been resolved with 2.2.4.

For those of us with large sites and large clients AND the Professional version, this is a show stopper for PyroCMS 2.2.x.

I for one would be happy to contribute $$ to anyone that can resolve this - especially since I only purchase PyroCMS Professional.

**Comment by mamarmite** [comment]
I found on CKeditor's forum a fix to the "span anarchy bug" (should I say): (http://ckeditor.com/forums/CKEditor/ckeditor-4.01-inserting-span-elements-everywhere-with-a-line-height-of-1.6em )

I tried fixed this directly in the css, but it work only if added on('instanceLoaded') event in the bottom of the config file of ckeditor (system/cms/themes/pyrocms/js/ckeditor/config.js )

```javascript
var isChrome = /Chrome/.test(navigator.userAgent) && /Google Inc/.test(navigator.vendor);
if (isChrome) {
	CKEDITOR.on( 'instanceLoaded', function( e ){
		this.addCss('.cke_editable { line-height: normal; font-size:12px; }');
	});
}
```

My not verified hypothesis is that if we alter the default value of ckeditor, Chrome tell you the hard way.
Tested on PyroCMS 2.2.5 and Chrome up to date.

The 12px font is not beautiful. this isn't a good fix, just a work arround fix.

**Comment by wollombiwombat** [comment]
@mamarmite  Thanks Andre for posting this. Unfortunately, this did not work in my case. I still got the spans inserted with a font size of 13px and also a line height of 20+ems.
The CKeditor saga continues to be a problem even if they can resolve this issue. I am seeing new problems emerging with IE  (unable to edit hyperlinks in the modal) and in FF the CKeditor is empty! For the record, I have Win7 SP1 IE 11.0960017728, FF 37.0.2 and Chrome 42.0.2311.90 
Just hope that with all the emerging problems associated with CKeditor, we have a better solution for PyroCMS v3.   Altho CKeditor 4.5 beta was released a few days ago, it still is carrying some baggage of un-resolved issues.

**Comment by RyanThompson** [comment]
We're not using CKEditor in v3 - we're using Redactor: http://redactorjs.com/

**Comment by ikoniqoz** [comment]
Looking forward to that! Thanks Ryan.

**Comment by huglester** [comment]
Hello,

Well I could not afford to upgrade all projects, so I have taken a try to update  ckeditor.

I have updated ckeditor to version 4.4.7.
Nothing too much was changed. Mainly the:
`config.js`
added: `skins/moono-dark`
and added `plugins/` from current ckeditor plugins/ folder.

Basically you can try it like so:

move old ckeditor:
from `system/cms/themes/pyrocms/js/ckeditor` to `system/cms/themes/pyrocms/js/ckeditor.old`

and download this one: https://www.dropbox.com/s/b4pt7hkts9yn9cd/ckeditor-62354ed96b800fc0ad248d65fc2e136fcc3cd8e1.zip?dl=0

And tell me how it works for you if you try!
