### ISSUE TITLE
2.3/Develop Migrations are broken

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#3337]
When trying to do a migration from 2.2.3 to 2.3 you get the following error.

![capture](https://cloud.githubusercontent.com/assets/656313/3360969/ffbee604-faf8-11e3-98ee-0def9165ddda.JPG)
![capture1](https://cloud.githubusercontent.com/assets/656313/3360972/08881472-faf9-11e3-9436-6b4fe5087961.JPG)

**Comment by huglester** [comment]
@RyanThompson close please. no more 2.3, 3.0 FTW! :)
