### ISSUE TITLE
New delete convention

### ISSUE THREAD

**Issue by james2doyle** [pyrocms/pyrocms#3345]
I had someone delete the navigation today, even after showing them exactly what happens. This common user mistake still haunts me even after I added the [red delete in the navigation](https://github.com/pyrocms/pyrocms/pull/2250) a million years ago. I still see the need for an extra level of dummy-proof on these delete functions. 

I've seen this convention in Github and MailChimp for a while. I am thinking this could apply nicely to pages, navigation, and modules.

![lists_listfieldsmerge_deleteconfirm](https://cloud.githubusercontent.com/assets/1425304/3457797/b7f2a2ca-01fb-11e4-9b53-3c08b5dd9c8a.jpg)

The idea is essentially the same as Github and MailChimp, make everyone think and read before deleting something that can't be undone.

**Comment by huglester** [comment]
@james2doyle are you up for this? :))) I like it :)!

**Comment by james2doyle** [comment]
It could be a while before I get around to this

**Comment by RyanThompson** [comment]
Confirm and prompt confirm (text matching) are built into 3.0 now soo...

**Comment by huglester** [comment]
@RyanThompson maybe let's give @james2doyle a month or so.

Or will close it when 3.0 will be at least beta1 or so.

**Comment by RyanThompson** [comment]
Ya won't be long!

**Comment by RyanThompson** [comment]
This is done now.
