### ISSUE TITLE
WYSIWYG broken in IE11

### ISSUE THREAD

**Issue by alexborton** [pyrocms/pyrocms#3347]
Hi guys, 

The WYSIWYG does not work in IE11. This has been recognised by CKEditor and seems to have been fixed in their latest version, but this is not the version included in PYRO.

We are using PYROCMS 2.2.4.

Please advise. Thanks

**Comment by huglester** [comment]
@alexborton if possible, please test this:
https://github.com/pyrocms/pyrocms/issues/3286#issuecomment-99073973

and see if it works for you
