### ISSUE TITLE
Make the online documentation keyword searchable

### ISSUE THREAD

**Issue by dutchman71** [pyrocms/pyrocms#3397]
Would be nice if the online documentation at http://docs.pyrocms.com/2.2/manual was keyword searchable. Thanks!

**Comment by huglester** [comment]
I saw, somewhere on the internet, example of the Elastic search powered search which crawls .md files or so. Was really nice. would be good to have smth like that!

**Comment by RyanThompson** [comment]
I was looking at that for search in general but .. idk.. Id like to have a DB fallback.

**Comment by huglester** [comment]
I personally like the docs being in markdown. Easier pull requests etc. And you later want them jus put in db and make serach using DB queries?
