### ISSUE TITLE
Keywords Field Type Error: Uncaught TypeError: undefined is not a function 

### ISSUE THREAD

**Issue by byybora** [pyrocms/pyrocms#3398]
I'm using PyroCMS 2.2.5 version and i created new custom module with enabled streams.

I assigned `Keywords` field type for `meta_keywords` input. And in backend it's working perfect! But in front-end, i'm getting following error:

**keywords.js on line 9**
Error: Uncaught TypeError: undefined is not a function
```
$(this).tagsInput({
```

And i noticed that two resources of field type not loaded.

```
public function event($field)
{
     $this->CI->template->append_css('jquery/jquery.tagsinput.css'); // Not Loaded
     $this->CI->template->append_js('jquery/jquery.tagsinput.js'); // Not Loaded
     $this->CI->type->add_js('keywords', 'keywords.js'); // Loaded
}
```
I tried to change default theme and copy these two files `jquery/jquery.tagsinput.css` and `jquery/jquery.tagsinput.js` to my frontend theme, but nothing happens.

Finally i tried `{{ streams:form_assets }}` but i got new error:
```
Uncaught ReferenceError: pyro is not defined
```

**Comment by huglester** [comment]
Hello,

I think those tagsiput would only work in backend?

cc @RyanThompson

**Comment by RyanThompson** [comment]
You would need to include the assets and they'd work - otherwise correct, they're made for backend use.
