### ISSUE TITLE
Bug in Search module (Its fixed here )

### ISSUE THREAD

**Issue by aruncnt** [pyrocms/pyrocms#3413]
In search module when we want to add some more fields in table like "keywords" then we pass it from "option" argument but its unable to store in search table when we add more fields in "option" argument. I have changed search module code which able to store all "options" data in search table. Pyrocms have to replace this code for fixed

system\cms\modules\search\models\search_index_m.php

Replace index method
public function index($module, $singular, $plural, $entry_id, $uri, $title, $description = null, array $options = array()) {

   $this->drop_index($module, $singular, $entry_id);

   /*@updated  BY Arun Kumar Yadav , aruncnt@gmail.com  */
    if (is_array($options) && count($options) > 0) {
        foreach ($options as $key => $value) {
            if ($key == 'keywords') {
                if (is_array($value)) {
                           $this->db->set('keywords', implode(',', $value));
                } elseif (is_string($value)) {
                    $this->db->set(array(
                         'keywords' => Keywords::get_string($value),
                        'keyword_hash' => $value,
                    ));
                }
            } else {
                $this->db->set($key, $value);
            }
        }
    }

 return $this->db->insert('search_index', array(
                'title' => $title,
                'description' => strip_tags($description),
                'module' => $module,
                'entry_key' => $singular,
                'entry_plural' => $plural,
                'entry_id' => $entry_id,
                'uri' => $uri,
    ));
}

**Comment by huglester** [comment]
@RyanThompson have you checked this 'code'? if so I could prep the PR

**Comment by RyanThompson** [comment]
I've not - I will review the PR though.

**Comment by huglester** [comment]
@RyanThompson I have added the PR here: https://github.com/huglester/pyrocms/commit/913c38ec52edb203ed6be8863a4c0371810c47c8

it just replaces the index() method. not sure if it works, because I do not use search module as is, have custom implementation.

**Comment by huglester** [comment]
@aruncnt hello. can you test my patch provided?

**Comment by RyanThompson** [comment]
Reopen if issue persists.
