### ISSUE TITLE
set_metadata() causing duplicate meta

### ISSUE THREAD

**Issue by byybora** [pyrocms/pyrocms#3428]
I tried this:

```
$this->template->set_metadata('canonical', 'test', 'link', 'header', true);
```

This causing duplicate canonical meta. 1. Default canonical (in Public_Controller) and 2. mine. Because of 528 and 530 line;

https://github.com/pyrocms/pyrocms/blob/2.2/develop/system/cms/libraries/Template.php#L528
https://github.com/pyrocms/pyrocms/blob/2.2/develop/system/cms/libraries/Template.php#L530

My meta content and default meta content are already different. So this cause to duplicate meta. Override codes should be use`$name` instead of `content` like following:

```
if ($override) 
{
   $this->_override_meta[$place][$name] = $link;
} else {
   $this->_metadata[$place][$name] = $link;
}
```

**Comment by huglester** [comment]
@RyanThompson close this. it's fixed now
