### ISSUE TITLE
Wildcard redirect in Redirect module not working

### ISSUE THREAD

**Issue by amityweb** [pyrocms/pyrocms#3432]
According to the changelog http://docs.pyrocms.com/2.2/manual/reference/changelog:
"Redirects will now have 301 or 302 dropdown in redirects. Redirects will now support * wildcard in from field and optionally $1,$2... in to field."

But I can't get wildcards to redirect at all. I cant see any code taking into account the star * in redirect_m.php's function get_from($from) or Public_controller.php.s __construct(). 

I am entering the redirect as follows:
From = oldpage/* 
To = newpage

But going to /oldpage/whatever does not redirect me to /newpage. I am using v 2.2.2

Thanks

**Comment by huglester** [comment]
@RyanThompson you know how to solve this? This probably needs some nasty regexp? Maybe we could look inside Laravel sources? I think it has something similar

**Comment by RyanThompson** [comment]
Can you try changing the % to an * in the line referenced below:

https://github.com/pyrocms/pyrocms/blob/2.2/develop/system/cms/core/Public_Controller.php#L38

I believe there was a mistake there.

**Comment by RyanThompson** [comment]
Hmm just tried this on my end - NVM.. Looks like there is a deeper issue in the model here.
