### ISSUE TITLE
Upgraded from 2.1.5 to 2.2.5 not getting into the admin

### ISSUE THREAD

**Issue by lordgema** [pyrocms/pyrocms#3433]
Saw this issue from two years ago but the methods used doesn't work. When I try and log into the admin, I see:"
A Database Error Occurred
Error Number: 1054

Unknown column 'c.user_name' in 'field list'

SELECT `c`.*, IF(c.user_id > 0, m.display_name, c.user_name) as user_name, IF(c.user_id > 0, u.email, c.user_email) as user_email, `u`.`username`, `m`.`display_name` FROM `default_comments` `c` LEFT JOIN `default_users` `u` ON `c`.`user_id` = `u`.`id` LEFT JOIN `default_profiles` `m` ON `m`.`user_id` = `u`.`id` WHERE `c`.`is_active` = 1 ORDER BY `c`.`created_on` desc LIMIT 5
"
On the DB and on, "system/cms/config/migration.php" the migration versions are the same which was the previous solution. Please advise.

**Comment by huglester** [comment]
@lordgema were you able to solve this?

**Comment by lordgema** [comment]
I eventually did a clean install and added the content back in by hand.

**Comment by huglester** [comment]
so you added a field manually?
