### ISSUE TITLE
2.2/No confirm before deleting an email template

### ISSUE THREAD

**Issue by james2doyle** [pyrocms/pyrocms#3436]
This just killed me.

I clicked delete by accident on an email template. Right away I figured, "oh I will just cancel at the prompt!".

But the prompt never came, it never came.

---

*I can add this in*, if it's worth adding in at this point. What do you think?

**Comment by huglester** [comment]
@james2doyle I think it is worth it :) Will flood @RyanThompson to accept the pull request:)

**Comment by RyanThompson** [comment]
PR?

**Comment by huglester** [comment]
@RyanThompson it it fixed. please close. not sure why it did not auto-close.

**Comment by james2doyle** [comment]
Thanks @huglester
