### ISSUE TITLE
Plugin blog:posts - not listen

### ISSUE THREAD

**Issue by globsecure** [pyrocms/pyrocms#3439]
Plugin Blog,

Not listen posts `default_blog`.`created_on` >= CURDATE()

SELECT `default_blog_categories`.`title` AS 'category_title', `default_blog_categories`.`slug` AS 'category_slug', `default_blog_categories`.`title` AS 'category||title', `default_blog_categories`.`slug` AS 'category||slug', `default_blog`.*, `cb_users`.`id` AS `created_by||user_id`, `cb_users`.`email` AS `created_by||email`, `cb_users`.`username` AS `created_by||username`, `profiles`.`display_name` AS `created_by||display_name` FROM `default_blog` LEFT JOIN `default_blog_categories` ON `default_blog_categories`.`id` = `default_blog`.`category_id` LEFT JOIN `default_users` AS `cb_users` ON `cb_users`.`id`=`default_blog`.`created_by` LEFT JOIN `default_profiles` AS `profiles` ON `profiles`.`user_id`=`default_blog`.`created_by` WHERE (`default_blog`.`status` = 'live') AND `default_blog`.`created_on` >= CURDATE() ORDER BY `default_blog`.`created_on` DESC LIMIT 2

SELECT CURDATE()

**Comment by huglester** [comment]
@globsecure @RyanThompson is this still the issue?

**Comment by RyanThompson** [comment]
Reopen if this is a thing that needs addressing still.
