### ISSUE TITLE
How to upload bulk images and save record in stream?

### ISSUE THREAD

**Issue by techsandeep** [pyrocms/pyrocms#3442]
Hi,

I have created a stream named "products" having 500 records and updated data from csv.
I want to upload images against all records from a folder. I am using Files::upload() method for same but unable to get image detail however i am able to upload using core but how to upload in pyrocms as there are virtual files and only image id saved in stream. Please help how to upload images using pyrocms methods?

Thanks

**Comment by RyanThompson** [comment]
There is no bulk upload in 2.2 - you need to handle them individually in a loop.

**Comment by techsandeep** [comment]
Ok I am doing in loop but what to pass at the place of field name in Files::upload() method as I am picking image from a folder...

**Comment by RyanThompson** [comment]
Sounds like you need to read the files rather than actually upload them? I may be missing what you are trying to do..


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is

t (877) 705-0806
m (309) 752-8581
