### ISSUE TITLE
2.2.5 parent class will be added to all navigation items if browsing home page

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3445]
Parent class will be added to all navigation items if browsing home page.

**Comment by RyanThompson** [comment]
I do not have this happening on any of my 2.2.5 sites. Can anyone else reproduce this?

**Comment by keevitaja** [comment]
http://bug.keevitaja.com/

fresh install and i do get parent classes on nav elements:

```
			<ul id="head-nav">
			<li class="first current parent"><a href="http://bug.keevitaja.com/home">Home</a></li><li class="parent"><a href="http://bug.keevitaja.com/blog">Blog</a></li><li class="last parent"><a href="http://bug.keevitaja.com/contact">Contact</a></li>
			</ul>
```

**Comment by keevitaja** [comment]
@RyanThompson i think it is confirmed, as other sites get parent class added as well. i looked at some examples from pryocms forum showcase:

- http://bulletproof.com.co/
- http://www.mountain-days.co.uk/
- http://rainferr.ee

**Comment by huglester** [comment]
@RyanThompson close. it should be fixed
