### ISSUE TITLE
3.0/develop -- composer install hits runtime exception

### ISSUE THREAD

**Issue by theTrip73** [pyrocms/pyrocms#3447]
I started a fresh checkout using:

    git clone git@github.com:pyrocms/pyrocms.git -b 3.0/develop newsite
    cd newsite
    composer install

It ran until this happened:

    -Installing anomaly/streams-platform (dev-master 1b4972b)
    Cloning 1b4972b8917e7d3001340493b93c51fa8354471b
    
    [RuntimeException]
    core/anomaly/users_module_blocked_check-extension does not exist and could
    not be created.

To this point, using git and composer, I have not been able to even get to the point where I can access /installer without error.

**Comment by RyanThompson** [comment]
Composer update in there do anything?

The package is at:
https://packagist.org/packages/anomaly/users_module_blocked_check-extension

Do you have anything at all in your core/ folder?

**Comment by philmartinez** [comment]
I'm having the same issue. I did try and run composer update and got an memory size exhausted error.

**Comment by theTrip73** [comment]
"composer update" gave me a conflict with trying to resolve streams-platform's twig/twig 1.16.* requirement.

I re-ran composer install and got this runtime exception during the clear-complied block:

    Error Output: PHP Fatal Error: Class 'Anomaly\Streams\Platform\Model\Users\UsersRolesEntryModel' not found in /var/www/newsite/core/anomaly/users-modules/src/Role/RoleModel.php on line 14

**Comment by RyanThompson** [comment]
I will check this out this afternoon and see what's going on. This is on fresh clones?

**Comment by theTrip73** [comment]
I pulled 3.0/develop into a basically empty but previously init-ed git repo. The existing repo had only two favicon files and a quickstart.html file.

I did try an actual clone and got similar results.

**Comment by RyanThompson** [comment]
Just checked and am running this fine.. What is your guys' environment like?

Can you up your PHP memory allowance? 

Perhaps try something like this: php -d memory_limit = 1024M composer.phar install / update

**Comment by theTrip73** [comment]
I'm not running into memory errors (at least not explicit ones). Is there any situation in which a memory allocation error would 'class not found' output instead of an allocation message?

**Comment by RyanThompson** [comment]
Oh sorry I was referring to the message higher up.

Does your version of this file look like this: https://github.com/anomalylabs/users-module/blob/master/src/UsersModuleServiceProvider.php#L25

**Comment by theTrip73** [comment]
I will have to check that when I get back home. I don't have my home server set up for SSH access.

I just realized that I never answered your previous question: "Do you have anything at all in your core/ folder?" I checked this morning, and there were definitely folders and files in there. I checked specifically for the "/users_module_blocked_check-extension" folder, but I was dealing with contractors this morning and honestly can't remember if that specific one was there.

I follow up tonight.

**Comment by RyanThompson** [comment]
Ok cool - and if those users_module extensions ARE in there then try deleting the and removing them from your composer file. Idk why it would be that way in your env and not mine though :-(


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is

t (877) 705-0806
m (309) 752-8581

**Comment by theTrip73** [comment]
Interesting. My UsersModuleServiceProvider doesn't have that if (INSTALLED) check in it. I guess this means my files are somehow still out of date... ?

On that checkout, I'm still getting these errors (https://github.com/pyrocms/pyrocms/issues/3447#issuecomment-70102462) even after pulling the latest updates from 3.0/develop.

I'm cloning a spanking new checkout right now -- which is incredibly slow (like it was last night) -- but I'm guessing that's because of the sheer number of packages included. 220,353 seems like a lot of objects. :-)

I will update again after cloning and running composer install.

**Comment by theTrip73** [comment]
Well, that did it. I can't explain it, but I'm up and running now off a fresh clone.

I am closing this, but I'd love to hear any potential explanations as to why a pull into an empty repo didn't work but a clone did.

**Comment by theTrip73** [comment]
I spoke too soon. I got past all of the composer stuff but I'm still just getting a blank screen when I visit the /installer page. Nothing is showing up in the /storage/logs folder.

**Comment by RyanThompson** [comment]
Ya there are more git packages now that Phil helped us out with preserving the existing repository. That will trim down as we delete 2.0 and so on going forward.

Can you make sure your storage/* and public/assets/* folders are writable?

**Comment by theTrip73** [comment]
Yep. That was the last bit. I was so focused on getting the composer stuff worked out that I forgot about the /storage folder, and I just worked my way through the /assets issue.

Given that /assets is in the web root, is there much of a difference between (1) going 775 and adding www-data to the group and (2) just going 777 on it?

My problem is solved on this, btw. So feel free to leave this open for others or close it, as you see fit.

**Comment by RyanThompson** [comment]
I would just say 775 is fine - all you need is to be able to write to it with the server. Laravel keeps business logic behind root so you're safe either way.

Ill close her down - working on a good remedy to holler / complain at users and fail FAST and in an informative way regarding folder permissions. So shouldn't be applicable for long.

Thanks for the feedback!

**Comment by umair2k3** [comment]
I am having installation error.

[Error Exception]
zipArchive::extractTo<>: No such file or directory

Can you please help ??

Help will be highly appreciated.

**Comment by RyanThompson** [comment]
This is what Google gave me - that's that PyroCMS I'm afraid:

https://github.com/composer/composer/issues/2824

**Comment by tejrajs** [comment]
This may be solution

Go to your php.ini file and search for "sqlite".

These are probably commented:

extension=php_pdo_sqlite.dll
extension=php_sqlite3.dll

Un-Comment them, and restart your web server. Try again via composer.
