### ISSUE TITLE
Related field is shown twice

### ISSUE THREAD

**Issue by pixeldesignstudio** [pyrocms/pyrocms#3450]
Hello,

if I choose the "related field", save the page/fieldcustom 
![image](https://cloud.githubusercontent.com/assets/9533914/5803733/ceb1c0ba-a000-11e4-9b22-f7b80cebd873.png)

Reenter the field (edit field), the "choose"-field is duplicated.
![image](https://cloud.githubusercontent.com/assets/9533914/5803758/fdb7a6cc-a000-11e4-879e-7c8388281f59.png)

If I try to print out the data from lex, it prints out "Array" instead of the data.

Version 2.2.5 Community

**Comment by RyanThompson** [comment]
if you submit the form does it work still or does it get confused?

**Comment by pixeldesignstudio** [comment]
It still works, no difference in administration

2015-01-24 20:09 GMT+01:00 Ryan Thompson <notifications@github.com>:

> if you submit the form does it work still or does it get confused?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyrocms/pyrocms/issues/3450#issuecomment-71332672>.
>



-- 


*Wichtiger Hinweis:* Diese E-Mail und etwaige Anlagen können Betriebs- oder
Geschäftsgeheimnisse, oder sonstige vertrauliche Informationen enthalten.
Sollten Sie diese E-Mail irrtümlich erhalten haben, ist Ihnen der Status
dieser E-Mail bekannt. Bitte benachrichtigen Sie uns in diesem Fall sofort
durch Antwort-Mail und löschen diese E-Mail nebst etwaigen Anlagen von
Ihrem System. Ebenso dürfen Sie diese E-Mail oder ihre Anlagen nicht
kopieren oder an Dritte weitergeben. Vielen Dank!

*Important Note:* This e-mail including any attachment is confidential and
may contain trade secrets or other confidential information. If you have
received it in error, you are aware of its status. Please notify us
immediately by reply e-mail and then delete this e-mail and any attachment
from your system. If you are not the intended recipient, you are not
allowed to copy this e-mail or any attachment or disclose the content to
any other person. Thank you for your cooperation.
