### ISSUE TITLE
Index.php overwritten

### ISSUE THREAD

**Issue by romeo-whiskey** [pyrocms/pyrocms#3451]
Hello people,
Whilst updating my website via FileZilla, I have accidently overwritten the main index file.
Shame on me, there is no backup to be found (since I only just got the webmaster job).

Because of the missing index.php, the entire website now no longer functions, including the PyroCMS admin page.
Since almost all the info is stored in the database (which is untouched), I thought it might be possible to simply replace the index file by the one from the "clean" PyroCMS download, but it does not work that easily. Next I tried to reinstal the website on a local machine (using XAMPP), with the settings from the database, but that did not work either.

For now, I am running a bit out of ideas, so is there anyone who can help me?

Kind regards
Rutger

**Comment by guillefd** [comment]
If you only deleted the index.php, it should work again by replacing it with the file of the same version.
What version are you running? Look in system/{cms|pyrocms|whatever}/config/constants.php there should be a version constant defined in there ("CMS_VERSION")

**Comment by romeo-whiskey** [comment]
Thanks a lot for the quick answer!
Indeed it works again with the right index version (I realy could not find it in the beginning, so I was copying the wrong version)..

Everything works again, thanks!
