### ISSUE TITLE
[3.0] composer install --no-dev

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#3452]
Hello,

when Installing with '--no-dev' directive, you will get this error: 
exception 'ReflectionException' with message 'Class Anomaly\PyrocmsDistribution\PyrocmsDistribution does not exist' in /var/www/vhosts/pyro23/vendor/laravel/framework/src/Illuminate/Container/Container.php:776

seems https://github.com/anomalylabs/streams-distribution is need in require and not require dev? 
but I did not find composer.json file with this requirement... or searched wrong:)

**Comment by RyanThompson** [comment]
The streams distribution IS needed as well: https://github.com/pyrocms/pyrocms/blob/3.0/develop/composer.json#L35

The PyroCMS distribution is an extension of the Streams one currently. 

Can you try just a straight composer install?

**Comment by huglester** [comment]
Yes it worked. But just wanted you to know. I think it would be good for be
installable with prod settings
