### ISSUE TITLE
[3.0] Admin user/permissions bug

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#3453]
Hello,

when accessing permissions (admin/users/permissions/2) you get:

Next exception 'ErrorException' with message 'The function "users_roles" does not exist in "module::admin/permissions/partials/roles" at line 9' in /var/www/vhosts/pyro23/core/anomaly/users-module/resources/views/admin/permissions/partials/roles.twig:9

**Comment by RyanThompson** [comment]
I know if :-(

Kicking this module out the door this week though. Look for a post on Alpha2 of the core platform. Core is close to code lock but addons need catching up..
