### ISSUE TITLE
Installer field validation : fields name with locale

### ISSUE THREAD

**Issue by remyma** [pyrocms/pyrocms#3455]
Installer doesn't works for me. Fields have a name with locale but validator expects name without locale.
I don't know wether this is a bug or if i have to do something like clearing cache ?
I've done a composer update just in case, but it's still boken.

Here is the name of the field in view :
`
database_username_en
`

And in Anomaly\StreamsDistribution\Ui\Form\InstallerFormValidator : 
`
'driver'    => $input['database_driver'],
`

I think this is relaated to this commit ?
 https://github.com/anomalylabs/streams-distribution/commit/8d1cc44aebf8ab16eb2c4f8890e7719fc71606e0

**Comment by RyanThompson** [comment]
Ah shoot - didn't mean to push that. I've got a load of commits I'm pushing later today. Thanks for the heads up!
