### ISSUE TITLE
Can't login on admin.

### ISSUE THREAD

**Issue by remyma** [pyrocms/pyrocms#3456]
When installation is done, I can't login.
I get this message :
``Your account has not been activated.``

And in my database :
default_users_users.activated is null for my user.

![pyro_login_fail](https://cloud.githubusercontent.com/assets/2292735/6136092/37958b4c-b16e-11e4-810a-9ee700d74e6b.png)

**Comment by RyanThompson** [comment]
Tick it to 1 - Im working on the users module later tonight to change that for the userManager class

**Comment by RyanThompson** [comment]
Someone should go over the colors in the PyroCMS theme.. That clashing red is enough to drive me insane.


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is

t (877) 705-0806
m (309) 752-8581

**Comment by remyma** [comment]
;-) Thanks, I now have access to admin
