### ISSUE TITLE
Able to delete main admin

### ISSUE THREAD

**Issue by j-hubb** [pyrocms/pyrocms#3458]
After install, I'm able to delete my own admin account which shouldn't be possible.

**Comment by RyanThompson** [comment]
Agreed - I will make sure this is protected in the Users module release!


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is

t (877) 705-0806
m (309) 752-8581

**Comment by RyanThompson** [comment]
Fixed
