### ISSUE TITLE
Googlebot Mobile is seen as a robot and not mobile

### ISSUE THREAD

**Issue by epicurius7** [pyrocms/pyrocms#3460]
PyroCMS 2.2.x and lower:

The mobile GoogleBot can't see mobile themes in PyroCMS sites. The User Agent detection prioritizes 'robot' over 'mobile'. Not good for ranking as a mobile-friendly site.

Suggested fix: separate robot detection from mobile/browser detection:
`/system/codeigniter/libraries/User_agent.php, line 225:`

    /**
     * Compile the User Agent Data
     *
     * @return	bool
     */
    protected function _compile_data()
    {
        $this->_set_platform();

        foreach (array('_set_mobile', '_set_browser') as $function)
        {
            if ($this->$function() === TRUE)
            {
                break;
            }
        }

        foreach (array('_set_robot') as $function)
        {
            if ($this->$function() === TRUE)
            {
                break;
            }
        }
    }

**Comment by ikoniqoz** [comment]
Awesome! - Many thanks for posting this proposal for the user-agent issue. I have tried it out and it has worked using Google's Mobile Friendly Test :  https://www.google.com/webmasters/tools/mobile-friendly/  on my own site.
Will implement it on a few client sites and report back.

**Comment by ikoniqoz** [comment]
Works great. Can I suggest that you put in a PR so that Ryan can merge it.

**Comment by epicurius7** [comment]
OK, think I did this correctly...
pyrocms/pyrocms#3470

**Comment by ikoniqoz** [comment]
Thanks for the fix and for the PR David. Dont know why it looks like it failed though.

**Comment by epicurius7** [comment]
PR processed now, so done. Thanks.

**Comment by RyanThompson** [comment]
Thank you!
