### ISSUE TITLE
Commit composer.lock

### ISSUE THREAD

**Issue by james2doyle** [pyrocms/pyrocms#3463]
Apparently committing the `composer.lock` file helps with `composer install`. This suggestion comes from the [composer project lead](https://twitter.com/seldaek/status/578687656910983168).

I have found it hard to install and update the dependencies because my composer exhausts the RAM.

Is the experience familiar to anyone else?

**Comment by RyanThompson** [comment]
I'd just assume leave it though, installing shouldn't be necessary for normal dev. Just updating as things change.

**Comment by james2doyle** [comment]
That's the thing, I have had trouble installing. My composer exhausts all the memory on my machine.

**Comment by RyanThompson** [comment]
Even now with Alpha2? Usually installer is much easier on the machine.

**Comment by RyanThompson** [comment]
try manually adding it: https://gist.github.com/RyanThompson/6f406521fa92179e159c

**Comment by james2doyle** [comment]
Well it did actually manage to install this time without crashing composer. So thats good! :smile:

**Comment by RyanThompson** [comment]
@obrignoni what do you think about committing lock file on master?

**Comment by obrignoni** [comment]
Committing the lock to the master branch makes sense.
