### ISSUE TITLE
Built in server broken

### ISSUE THREAD

**Issue by incraigulous** [pyrocms/pyrocms#3464]
server.php is requiring /bootstrap/paths.php in alpha 2. Taylor removed that file in Laravel 5. That means running "php artisan serve" does not work. The line of in question is:

$paths = require __DIR__.'/bootstrap/paths.php'

You might just need to pull in the newest version of server.php from the Laravel repo. I tried it, but I got stuck in a redirect loop. I haven't actually tried Alpha 2 on Apache yet, so I'm not sure if that is an issue with the built in server or not.

**Comment by remyma** [comment]
Hi, 

I think it is not a pyrocms issue but a laravel one, according to this post : 
http://laravel.io/forum/10-22-2014-dev-l5-bootstrappathsphp-file-missing

But I agree, it would be nice if fixed on laravel ;-)

**Comment by remyma** [comment]
Seems I havn't carrefuly read your post. Indeed server.php changed in laravel repo and it does not require paths.php anymore

**Comment by RyanThompson** [comment]
I will bring up to speed on the develop branch, thanks!

**Comment by incraigulous** [comment]
Thanks Ryan!

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/e99eaeb3e04ffcad65b6d5c0096fbdbe6f265f82
