### ISSUE TITLE
'Class composer does not exist' exception

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#3466]
Hello,

just tried to fresh install. Git cloned the repo, composer install, and get:

```php
intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
phpdocumentor/reflection-docblock suggests installing league/commonmark (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Writing lock file
Generating autoload files
                                
  [ReflectionException]          
  Class composer does not exist  

Script php artisan clear-compiled handling the post-install-cmd event returned with an error
                  
  [RuntimeException]  
  Error Output:       
                      
```

**Comment by ramon-villain** [comment]
same here.

**Comment by RyanThompson** [comment]
What do your error logs say about it?

**Comment by remyma** [comment]
I have same error on composer install after cloning repo. Here is the trace I have in my log file : 
```
[2015-04-09 21:07:47] local.ERROR: exception 'ReflectionException' with message 'Class composer does not exist' in /home/vagrant/sites/pyrocms/vendor/laravel/framework/src/Illuminate/Container/Container.php:776
Stack trace:
#0 /home/vagrant/sites/pyrocms/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): ReflectionClass->__construct('composer')
#1 /home/vagrant/sites/pyrocms/vendor/laravel/framework/src/Illuminate/Container/Container.php(656): Illuminate\Container\Container->build('composer', Array)
#2 /home/vagrant/sites/pyrocms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(644): Illuminate\Container\Container->make('composer', Array)
#3 /home/vagrant/sites/pyrocms/vendor/laravel/framework/src/Illuminate/Container/Container.php(1231): Illuminate\Foundation\Application->make('composer')
#4 /home/vagrant/sites/pyrocms/vendor/laravel/framework/src/Illuminate/Foundation/Providers/ArtisanServiceProvider.php(98): Illuminate\Container\Container->offsetGet('composer')
#5 /home/vagrant/sites/pyrocms/vendor/laravel/framework/src/Illuminate/Container/Container.php(773): Illuminate\Foundation\Providers\ArtisanServiceProvider->Illuminate\Foundation\Providers\{closure}(Object(Illuminate\Foundation\Application), Array)

```

**Comment by RyanThompson** [comment]
I get this too now - I think something in my outdated L5 dir is wrong but you can still proceed after this for now. Will fix soon.

**Comment by balu-lt** [comment]
Same thing here after cloning repo and running composer install...
![composer_install_cut](https://cloud.githubusercontent.com/assets/7798162/7085338/85595500-df7e-11e4-8387-39619ed5d273.png)

Then browser redirects to /install with Twig_Error_Loader,
and after page refresh in result:
![browser_cut](https://cloud.githubusercontent.com/assets/7798162/7085326/584b4028-df7e-11e4-86f4-b53147636c09.png)

I still have working version installed from april 1st (semantic),
and after trying composer update I get no errors in console,
however in browser /admin/login I get the same "not available".

Hope you will find a solution soon :)

**Comment by RyanThompson** [comment]
Open your .env file or delete it to let you "reinstall". The twig thing is SUPER annoying but Im not sure that I have a clean solution just yet. Usually a refresh works great.

**Comment by balu-lt** [comment]
Weird stuff is happening... can't get out of that "not available".
The only working version is that old one without updates.

And for now the only clue I get when hitting url is in Apache logs:
```
[Fri Apr 10 20:35:53.304782 2015] [mpm_winnt:notice] [pid 7164:tid 280] AH00428: Parent: child process 5172 exited with status 3221225725 -- Restarting.
[Fri Apr 10 20:35:53.948819 2015] [ssl:warn] [pid 7164:tid 280] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Apr 10 20:35:53.982821 2015] [mpm_winnt:notice] [pid 7164:tid 280] AH00455: Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.6.3 configured -- resuming normal operations
[Fri Apr 10 20:35:53.982821 2015] [mpm_winnt:notice] [pid 7164:tid 280] AH00456: Apache Lounge VC11 Server built: Jul 17 2014 11:50:08
[Fri Apr 10 20:35:53.982821 2015] [core:notice] [pid 7164:tid 280] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Fri Apr 10 20:35:53.985821 2015] [mpm_winnt:notice] [pid 7164:tid 280] AH00418: Parent: Created child process 6576
[Fri Apr 10 20:35:54.609856 2015] [ssl:warn] [pid 6576:tid 292] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Apr 10 20:35:54.922874 2015] [ssl:warn] [pid 6576:tid 292] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Apr 10 20:35:54.956876 2015] [mpm_winnt:notice] [pid 6576:tid 292] AH00354: Child: Starting 150 worker threads.
```

**Comment by RyanThompson** [comment]
Are you trying to reach it over SSL? Those are SSL warnings man.. No PHP.

On Apr 10, 2015, at 1:49 PM, Vytautas M. <notifications@github.com<mailto:notifications@github.com>> wrote:


Weird stuff is happening... can't get out of that "not available".
The only working version is that old one without updates.

And for now the only clue I get when hitting url is in Apache logs:

[Fri Apr 10 20:35:53.304782 2015] [mpm_winnt:notice] [pid 7164:tid 280] AH00428: Parent: child process 5172 exited with status 3221225725 -- Restarting.
[Fri Apr 10 20:35:53.948819 2015] [ssl:warn] [pid 7164:tid 280] AH01909: www.example.com<http://www.example.com>:443:0 server certificate does NOT include an ID which matches the server name
[Fri Apr 10 20:35:53.982821 2015] [mpm_winnt:notice] [pid 7164:tid 280] AH00455: Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.6.3 configured -- resuming normal operations
[Fri Apr 10 20:35:53.982821 2015] [mpm_winnt:notice] [pid 7164:tid 280] AH00456: Apache Lounge VC11 Server built: Jul 17 2014 11:50:08
[Fri Apr 10 20:35:53.982821 2015] [core:notice] [pid 7164:tid 280] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe<smb://xampp//apache//bin//httpd.exe> -d C:/xampp/apache'
[Fri Apr 10 20:35:53.985821 2015] [mpm_winnt:notice] [pid 7164:tid 280] AH00418: Parent: Created child process 6576
[Fri Apr 10 20:35:54.609856 2015] [ssl:warn] [pid 6576:tid 292] AH01909: www.example.com<http://www.example.com>:443:0 server certificate does NOT include an ID which matches the server name
[Fri Apr 10 20:35:54.922874 2015] [ssl:warn] [pid 6576:tid 292] AH01909: www.example.com<http://www.example.com>:443:0 server certificate does NOT include an ID which matches the server name
[Fri Apr 10 20:35:54.956876 2015] [mpm_winnt:notice] [pid 6576:tid 292] AH00354: Child: Starting 150 worker threads.

**Comment by balu-lt** [comment]
Made a short & fast video: https://youtu.be/AByRAexIFWI
- Installing old (git clone & composer install) archive
- Trying to  use composer update
- Deleting and trying fresh installation

**Comment by RyanThompson** [comment]
Ah, use the dev branch.

**Comment by gijsjanr** [comment]
I have te same problem, I'm using the dev branch.

**Comment by balu-lt** [comment]
Even tried manually download dev branch - no difference.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/e99eaeb3e04ffcad65b6d5c0096fbdbe6f265f82
