### ISSUE TITLE
Issue with lex parser error

### ISSUE THREAD

**Issue by tara-irvine** [pyrocms/pyrocms#3467]
Hi there

I'm experiencing issues with the lex parser regex and I'm not sure how to fix them.
The page is http://vue-us.com/artists/kerry-harrison/kerry-harrison-portfolio
It's happening with quite a few sections on the site now, any gallery with over 23 images isn't appearing - just this error.

Message: preg_replace() [function.preg-replace]: Compilation failed: regular expression is too large at offset 43589

Filename: Lex/Parser.php Line Number: 282

<code>
public function parse_callback_tags($text, $data, $callback){
		$this->setup_regex();
		$in_condition = $this->in_condition;

		if ($in_condition){
			$regex = '/\{\s*('.$this->variable_regex.')(\s+.*?)?\s*\}/ms';
		}else{
			$regex = '/\{\{\s*('.$this->variable_regex.')(\s+.*?)?\s*(\/)?\}\}/ms';
		}
while (preg_match($regex, $text, $match, PREG_OFFSET_CAPTURE))
		{
...
</code>

Anyone know what we need to do to get everything displaying again?

**Comment by RyanThompson** [comment]
Have you tried something like this?

http://stackoverflow.com/questions/8268624/php-preg-match-all-limit

**Comment by tara-irvine** [comment]
Hi there

Thanks so much for getting back to me, I'm not a PHP expert so that doesn't make a lot of sense to me, do you think this is the only way to fix it?

Have you come across this before?

T.

**Comment by RyanThompson** [comment]
I've had it happen once upon a time it seems, yes. Indeed the PHP config is the likely culprit as well. Memory issue! I am confident this will remedy the issue so I will close it for now. Get ahold of your php.ini or a your hosting's customer service if you can!

**Comment by tara-irvine** [comment]
Hi there

This is the phpinfo, any idea where to find the php.ini file for pyrocms? http://vue-us.com/phpinfo.php

T.

**Comment by tara-irvine** [comment]
Hi there

Thanks for that, I'll take a look now, doesn't seem to be any folders with those names on the server though.

T.
