### ISSUE TITLE
Issues cleanup

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#3478]
Hello @RyanThompson 

are these still a thing? https://github.com/pyrocms/pyrocms/milestones/v3.0.0

Just gathering some idea on PyroCMS. And trying to clean up issues list, at least by 1%!

Probably would be good idea to just start closing very old issues.
Probably no poin in issues 1+ year or without feedback...

**Comment by RyanThompson** [comment]
Let me look through those and if you want - start from the bottom and just kill anything older than necessary. I can give you access if you have a little bit of time - then we can evaluate what's left in regards to 2.2.x.

Thanks for the help so far!

**Comment by huglester** [comment]
Hello,

I went threw all 2.2.6 milestone issues, and fixed whose I understood/knew how to fix. Yeah I could close some issues for sure. leaving comments for people so they ran re-reopen if are ready to coloborate. 
Issues I will be affraid to touch I just won't close then
