### ISSUE TITLE
Why is blog and email templates core modules?

### ISSUE THREAD

**Issue by 4tron** [pyrocms/pyrocms#3484]
These modules do not seem dependent on core functionality.

**Comment by numerogeek** [comment]
Historical reason I think.

**Comment by RyanThompson** [comment]
While it's not core to Streams or the Streams Platform, it IS core to PyroCMS. The reason being is PyroCMS is an application for building and maintaining a "website". Very often, websites include some kind of press / blog / news section and the Blog module is there to provide a quality user experience for it.

The email templates is / will be used by many modules, core and not. It's a generic email template manager that your module can use but Users module will use at the very least.

**Comment by 4tron** [comment]
@RyanThompson Thanks for the reply. I have used a few content management system and was impressed with pyro because it was lighter then the others. I understand that it is a "content management" system for websites , but it does seem like it can be more of an application development system . There are many situations in a business environment where a blog would just be verbose for its use case.

**Comment by RyanThompson** [comment]
@4tron funny you mention, the underlying core (Streams Platform) in the case of PyroCMS 3 is indeed an application development platform, powerful enough to build PyroCMS. 

One major change from 2 to 3 is that you WILL be able to delete core modules. They're not bound to core in any way they just get installed by default. You can also fork and adjust your composer file to include more / less addons as you wish. AND we'll eventually have a build file you can use from our store so you can just deploy PyroCMS or any variation of it to your server.. 

I guess what I am trying to say is, core / not core / etc doesn't really matter anymore. The product is flexible enough to do without it if you choose.

**Comment by RyanThompson** [comment]
@4tron @numerogeek I wouldn't mind changing the module name to something more generic though.. 

Thoughts?

**Comment by 4tron** [comment]
@RyanThompson Rad. Really keen to use version 3.
