### ISSUE TITLE
Can not create user by Installer

### ISSUE THREAD

**Issue by dakshhmehta** [pyrocms/pyrocms#3486]
Hello,

Once again, I restarted everything to have a test drive on PyroCMS with pages module.

I cloned the 3.0/develop branch
Installed the composer
777ed public/assets and storage folder
666ed .env file

and I hit the installer in browser.
It went perfectly fine and looks awesome.
I put all the details, progress started.

But, got stuck in the step "Creating admin user..." step.
I looked the console and I see that It returns 500 Internal server error with No response

Hope this will help in debugging.

**Comment by RyanThompson** [comment]
You're .env file needs to be editable until installation is finished.
