### ISSUE TITLE
Download MIME type is set to octet stream regardless of file (2.x).

### ISSUE THREAD

**Issue by epicurius7** [pyrocms/pyrocms#3488]
Just noticed this when trying to open a PDF downloaded from a Pyro site on Android. It won't recognise it as a .pdf if the mime type is wrong (unless manually opened via a PDF reader app), leading users to think the download failed somehow.
iOS ignores the server provided type, so no issue there.

Looking into the download module, Pyro sets all downloads to 'application/octet-stream'.

Default is ignore type:
/system/codeigniter/helpers/download_helper.php, line 52:
`function force_download($filename = '', $data = '', $set_mime = FALSE)`

Passing the true MIME type appears to be just a case of passing the third argument of force_download:

/system/cms/modules/files/controllers/files_front.php, line 48:
`force_download($name , $data, TRUE);`

Any idea why this is the default behaviour? Maybe the third argument was added later in CI.

**Comment by RyanThompson** [comment]
Im honestly not sure - if you've fixed the issue though and feel confident would you please submit a pull request for the patch to 2.2/develop?

**Comment by epicurius7** [comment]
OK, PR is: https://github.com/pyrocms/pyrocms/pull/3498
