### ISSUE TITLE
Analytics dashboard in admin no access - ClientLogin shutdown

### ISSUE THREAD

**Issue by marcogrueter** [pyrocms/pyrocms#3489]
Looks like Google has shutdown the ClientLogin on their APIs. That means that the analytics dashboard in the admin can't display the graph anymore.

Would it be possible, to integrate the social module (https://www.pyrocms.com/store/details/social_integration) into the PyroCMS 2.2 core and go from there? Or just update the analytics library? Or drop the whole thing?

I'd be happy to give a PR a go, if you could guide me in the right direction.

**Comment by huglester** [comment]
@RyanThompson I think it is nice idea?

**Comment by RyanThompson** [comment]
That might work - Im somewhat concerned that the social module will not be free in 3.0 though. People might think that's shifty. But it would be a quick / decent fix for 2.2.

I say give it a go - PR it up and Ill handle explaining why the module is no longer free in 3.0..
