### ISSUE TITLE
Windows / XAMPP - PyroCSM installation fails

### ISSUE THREAD

**Issue by nunomira** [pyrocms/pyrocms#3490]
On Windows (8) using XAMPP the installation fails.
When you visit
http://localhost/pyrocms/
to start the installation, you're correctly redirected to
http://localhost/pyrocms/installer
where you get a "This webpage is not available" and "ERR_CONNECTION_RESET" error messages.

Adding

`<IfModule mpm_winnt_module>`
`ThreadStackSize 8888888`
`</IfModule>`

to the *httpd.conf* file solved the problem.
(Source http://goo.gl/WEKzs0)

**Comment by RyanThompson** [comment]
You rock! Thanks for sharing.
