### ISSUE TITLE
Check box  selection issue 

### ISSUE THREAD

**Issue by naeemshah** [pyrocms/pyrocms#3494]
i have check box field in stream 

array(
                'name' => 'Webinar Available To',
                'slug' => 'eba',
                'namespace' => 'webinar',
               'type' => 'choice',
                'assign' => 'webinar',
                 'extra' => array('choice_type'=>'checkboxes','choice_data'=> 'Different subscription types 
                   Men with "Testosterone Imbalance"
                   Women with "High Estrogen"
                   Women with "Low Estrogen"
                   Women with "Low Progesterone"
                   Women with "Low Testosterone"
                   Women with "High Testosterone"')
               
            )

only first choice remain checked after save. other field did not save even marked on creation time

**Comment by naeemshah** [comment]
'extra' => array('choice_type'=>'checkboxes','choice_data'=> '0 : Different subscription types 
                   1 : Men with "Testosterone Imbalance"
                   2 : Women with "High Estrogen"
                   3 : Women with "Low Estrogen"
                   4 : Women with "Low Progesterone"
                   5 : Women with "Low Testosterone"
                   6 : Women with "High Testosterone"


this solved my issue

**Comment by RyanThompson** [comment]
Ya 2.2 requires that syntax. 3.0 is where you'd define an array or something.
