### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by Vitell09** [pyrocms/pyrocms#3497]
www.moteldelamer.co.nz
Cannot access pyrocms via login
Have attempted to reset password, however have tried all known emails/accesses and the system says No account was found with these details.  Where to from here.?
How do I seek to resolve this issue? 
Is there someone who can look at this for me please.
relax@moteldelamer.co.nz or reservations@moteldelamer.co.nz.  
Appreciate your guidance. 
Thank you.
Tania

**Comment by RyanThompson** [comment]
Hi Tania,

See my emails to you regarding this. This is not really a system error. Have your developer contact me.
