### ISSUE TITLE
Pyrocms Website Throwing Error for Logged in Users

### ISSUE THREAD

**Issue by tapankumar** [pyrocms/pyrocms#3500]
Please check screen shot.
![error](https://cloud.githubusercontent.com/assets/734522/8389939/c12197fa-1c9b-11e5-8958-f03461753e98.jpg)

**Comment by RyanThompson** [comment]
Thank you (new server)! Fixed.

**Comment by tapankumar** [comment]
Still issue not fixed.
![error-1](https://cloud.githubusercontent.com/assets/734522/8390694/2ade0524-1cc0-11e5-9173-4cafb63dffa3.jpg)

**Comment by RyanThompson** [comment]
Arg.. there's a lot of these as it turns out. I think Ill suppress them for now X_X

**Comment by RyanThompson** [comment]
Should be ready to rock n roll now - thanks again!
