### ISSUE TITLE
Pyro2.2.5: View Preview of email templates yields a PHP Fatal Error.

### ISSUE THREAD

**Issue by ikoniqoz** [pyrocms/pyrocms#3505]
REFERS to the current 2.2 DEV branch!!
When I attempt to preview an Email Template I get a fatal error which is caused by a request for a missing file. Refer to line 12 of  /system/cms/themes/pyrocms/views/admin/layouts/modal.php  which is: Asset::css('webdujour.css');  
My solution was to comment out this line.

**Comment by RyanThompson** [comment]
Good catch, thank you: https://github.com/pyrocms/pyrocms/commit/5872f0bec886f81f15b7fa7a11366fd854c5c41b

**Comment by ikoniqoz** [comment]
Thanks Ryan. Interestingly, I see that the master branch version of modal.php is somewhat different to  the dev branch!
