### ISSUE TITLE
Pyrocms Multiple Relationship field doesn't remove all items, instead it will leave one item uncleared.

### ISSUE THREAD

**Issue by TshepoMokgoatjane** [pyrocms/pyrocms#3506]
Hi there,

I have a field of type "Multiselect" UI which holds items as per my request, now when I add items to the field, all work until max, however when I minus items, I cannot remove all of them completely.

I tried changing my field from a "Multiselect" UI to a "Drag/Drop" UI and it work in terms of adding and removing items.

Can somebody please advise on this?

Thanks.
Tshepo Mokgoatjane.

**Comment by RyanThompson** [comment]
Is there a javascript error or any more information you can share?
