### ISSUE TITLE
Installing module module

### ISSUE THREAD

**Issue by eoptimo** [pyrocms/pyrocms#3508]
When running the installer the text says "Installing ....... module module..."

Guess this is a minor thing but anyways :)

**Comment by RyanThompson** [comment]
Ya I'm aware of this one - I will be converting the installer to CLI based (with GUI wrapper) and fixing that for the final release tonight or in the morn. Thanks for the heads up!

**Comment by eoptimo** [comment]
I am getting an error when running the installer.. 
It cannot use forge username for db.
In the installer form in entered homestead/secret

**Comment by RyanThompson** [comment]
I don't use forge - is it a normal PDO password like you'd put in your config?

**Comment by RyanThompson** [comment]
Sorry read that wrong - the username eh? What's it saying?

**Comment by eoptimo** [comment]
the storrage/debugbar file says:

"exceptions": [{
			"type": "Exception",
			"message": "Cannot add listen to Queries for Laravel Debugbar: SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO)",
			"code": 1045,
			"file": "\/home\/vagrant\/Code\/pyrocms-v3\/pyrocms\/vendor\/barryvdh\/laravel-debugbar\/src\/LaravelDebugbar.php",
			"line": 316,
			"surrounding_lines": ["                );\n", "            } catch (\\Exception $e) {\n", "                $this->addException(\n", "                    new Exception(\n", "                        'Cannot add listen to Queries for Laravel Debugbar: ' . $e->getMessage(),\n", "                        $e->getCode(),\n", "                        $e\n"]
		}, {
			"type": "PDOException",
			"message": "SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO)",
			"code": 1045,
			"file": "\/home\/vagrant\/Code\/pyrocms-v3\/pyrocms\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connectors\/Connector.php",
			"line": 50,
			"surrounding_lines": ["\n", "        $password = Arr::get($config, 'password');\n", "\n", "        return new PDO($dsn, $username, $password, $options);\n", "    }\n", "\n", "    \/**\n"]
		}]

**Comment by eoptimo** [comment]
Ah..! Wasn't men to close it there

**Comment by RyanThompson** [comment]
"forge" is indeed the password and no password is set?

**Comment by eoptimo** [comment]
i didn't change in the config/database.php file if that is what you mean. I can see the .env file has been updated with the right credentials

**Comment by RyanThompson** [comment]
You've run the GUI installer?

https://github.com/pyrocms/pyrocms/blob/3.0/master/docs/getting-started/installation.md#installing-pyrocms

**Comment by RyanThompson** [comment]
You don't install it the same as Laravel JIC that's what you've done. There's a bit more to it.

**Comment by RyanThompson** [comment]
But if you've got an .env sounds like you have.. Can you try editing the database config directly?

**Comment by RyanThompson** [comment]
Ah.. Ill bet it's this:

Try using `127.0.0.1` instead of localhost.

**Comment by RyanThompson** [comment]
This is on the list of things fixed in Installer v1.1
