### ISSUE TITLE
Pages set to No-Index or in Draft mode are shown in XML sitemap

### ISSUE THREAD

**Issue by flip3** [pyrocms/pyrocms#3509]
When you set a page to draft mode or No-Index, it is included in the sitemap XML file:
http://www.domain.com/pages/sitemap/xml

**Comment by flip3** [comment]
Sorry, in draft mode it's ok and it isn't included but when you set it to No-Index. I'm not sure if that is intended. It doesn't make much sense for me.

**Comment by RyanThompson** [comment]
Hmm.. seems like a grey area. Perhaps another option is necessary to toggle sitemap visibility. From what I've ready already it seems like they are OK in there specially if they are only reachable via the sitemap.
