### ISSUE TITLE
Cloned pages produce binary string in Meta keywords field

### ISSUE THREAD

**Issue by flip3** [pyrocms/pyrocms#3510]
When you clone a page which has some meta keywords, a binary string like 1e7e4869146deba7e31db9fefdcafb24 is shown for the cloned page instead of the meta keywords.

**Comment by bloveless** [comment]
Sorry I didn't mean to close this! Reopened! But I think that is the ID of the keyword group. I agree it should show the actual keywords. I'll take a look as soon as I can, but if you want to look at it and submit a PR that would be awesome!

**Comment by flip3** [comment]
You don't want me to make a PR. I'm not a developer ;-)
