### ISSUE TITLE
Pyro2.2.5/Develop Show-stopper: Unable to create a new page. Ref: also PR 3487

### ISSUE THREAD

**Issue by ikoniqoz** [pyrocms/pyrocms#3511]
Following PR 3487, With a fresh install from the repo source I get the following error when attempting to create a new page:

A Database Error Occurred
Error Number: 1048
Column 'custom' cannot be null
INSERT INTO default_navigation_links (title, link_type, url, uri, module_name, page_id, custom, position, target, class, navigation_group_id, restricted_to) VALUES ('The New Page', 'page', '', '', '', 12, NULL, 4, '', '', 1, 0)

![225com-ceate-new-page-1](https://cloud.githubusercontent.com/assets/3609155/9075860/cdfbdf54-3b5d-11e5-8972-8e971ccdd00f.jpg)

Which makes me wonder why we need a custom nav type. Can anyone sell me on this?

**Comment by bloveless** [comment]
Custom types are useful for something like sms:// or tel://. I've been meaning to fix this. Sorry for the hassle. I'll fix this right now. But it will require a re-install. Or you can manually update the column in the database to allow nulls.

**Comment by bloveless** [comment]
It might not require a re-install. Let me look into it a little more.

**Comment by ikoniqoz** [comment]
@bloveless  Thanks for picking up on this. Wont the standard URL Link Type option handle these URL forms ?

**Comment by bloveless** [comment]
Fixed in PR #3512 the standard URL Link Types are prefixed automatically. That is why I had to create this custom field type. I think that most people will never need this, but it has been very hand for me in the past.

**Comment by bloveless** [comment]
Will you pull the latest version (or just replace your navigation_m file with the latest) and let me know if that works.

**Comment by ikoniqoz** [comment]
@bloveless  Thanks - I will try the nav module to start. - You have me wondering now about the prefix you mention. How can I replicate this. Very curious....

**Comment by ikoniqoz** [comment]
@bloveless - Didnt try just the model file.  However,  I can report that swapping the Navigation module solved the error. Still wondering about use cases. though. Would appreciate some examples.

**Comment by bloveless** [comment]
So all of the other types of navigation elements are formatted in some way. Either by adding a / or http://domain.com/ to the beginning of your url. If you wanted to add sms://18001234567 link to your navigation (less likely) but a tel://18001234567 to your navigation is more likely, especially with mobile devices browsing the web so much more than in the past. If you use the other types of navigation links you'll get /tel:// or http://domain.com/tel:// neither of which are valid. The custom type doesn't do any formatting for you and allows you to put whatever you'd like in the navigation link.

**Comment by ikoniqoz** [comment]
@bloveless - Thanks for the explanation.  In my case, with a site prior to your initial PR, I dont get the leading slash for a tel:// style URL.  / Cheers .

**Comment by bloveless** [comment]
Interesting. I put it in there because on a site prior to my PR I was seeing issues. Well thanks for helping me get this fixed anyway!

**Comment by ikoniqoz** [comment]
No Probs. Pleased I was able to contribute. / Cheers.

**Comment by ikoniqoz** [comment]
Just a thought: Because of the new custom feature it would be a good idea to crank up the version number from 1.1 to 1.2.
