### ISSUE TITLE
Pyro 3.0-beta1 won't install

### ISSUE THREAD

**Issue by markeilander** [pyrocms/pyrocms#3513]
When following on https://www.pyrocms.com/docs/pyrocms/setup/installation#installing-pyrocms, i get this error....

How to proceed??

````
  - Installing anomaly/dashboard-module (v1.0.0)
    Downloading: 100%



  [ErrorException]
  ZipArchive::extractTo(C:\wamp\www\projects\pyrocms/vendor/composer/c6a2e99d
  /anomalylabs-dashboard-module-2ded975\resources\js\highcharts\exporting-ser
  ver\java\highcharts-export\highcharts-export-convert\target\classes\com\hig
  hcharts\export\pool/ServerObjectFactory$PortStatus.class): failed to open s
  tream: Invalid argument
````

**Comment by RyanThompson** [comment]
We've been discussing this in the Facebook dev group if you'd like to join: https://m.facebook.com/groups/pyrocms/

Otherwise I think he'll post the fix here shortly

**Comment by wmiskib86** [comment]
In my case, on a windows machine, the error is appen beacause "the filepath was too long for windows"
I've tried to install the hotfix form microsoft support but dosen't work, so i decide to use a short name for the root folder.

**Comment by markeilander** [comment]
Thnx for the update!
I've stopped using facebook, i will wait for the fix.
Looks very promissing!!

 
Mark Eilander


Date: Thu, 6 Aug 2015 07:12:40 -0700

**Comment by RyanThompson** [comment]
Mark - perhaps join our dedicated chat: https://pyrocms.com/chat

Seems like this is an issue primarily with Windows, and then Composer relating to the length of directories.. Perhaps @wmiskib86 can expound a bit on his findings.

I am going to close this for now as all signs point to external services not playing nice.

**Comment by edster** [comment]
@markeilander You have 2 choices, move your site folder to just c:/ when doing the composer install.

Or do what I did and map a drive letter to the folder, navigate your cmd prompt using that drive mapping, then run composer install. You can do this by using \\localhost\C$\wamp\www\projects\pyrocms

**Comment by basv** [comment]
@markeilander I had the same issue on windows 8 and also after upgrading to windows 10. I got it fixed by using the following:

composer create-project pyrocms/pyrocms=3.0-beta1 --prefer-source

This makes composer use the source (it's slower) instead of a ZIPped package but doesn't need the unzip step which is triggering the error. Git should also be registered in your PATHs: http://blog.countableset.ch/2012/06/07/adding-git-to-windows-7-path/

**Comment by markeilander** [comment]
Hi there,

Thanks for all the reply's..

I've been on holiday the past week.

The ladt two post are promising, i will try to look into them today and post my findings.
