### ISSUE TITLE
Can't install beta 3

### ISSUE THREAD

**Issue by gavinfostered** [pyrocms/pyrocms#3514]
Just tried installing beta3. Composer went perfectly well, changed permissions on all directories as instructed by the installation instructions and get the following error:

ErrorException in metadata.twig line 25:
An exception has been thrown during the rendering of a template ("mkdir(): File exists") in "theme::partials/metadata" at line 25.

Any ideas? 

Using php 5.6/ubuntu(latest)/apache2. Screenshot also attached. 

![screen shot 2015-08-08 at 18 29 29](https://cloud.githubusercontent.com/assets/2064358/9151471/71d4f792-3dfb-11e5-975e-041a3e70dfec.png)

**Comment by RyanThompson** [comment]
What's your environment look like? I've seen this before but it should force the file put

Sent from my iPhone

On Aug 8, 2015, at 12:30 PM, Gavin Foster <notifications@github.com<mailto:notifications@github.com>> wrote:


Just tried installing beta3. Composer went perfectly well, changed permissions on all directories as instructed by the installation instructions and get the following error:

ErrorException in metadata.twig line 25:
An exception has been thrown during the rendering of a template ("mkdir(): File exists") in "theme::partials/metadata" at line 25.

Any ideas?

Using php 5.6/ubuntu(latest)/apache2. Screenshot also attached.

[screen shot 2015-08-08 at 18 29 29]<https://cloud.githubusercontent.com/assets/2064358/9151471/71d4f792-3dfb-11e5-975e-041a3e70dfec.png>

-

**Comment by RyanThompson** [comment]
Oh sorry didn't even see the environment there at the end. My bad. Try 777 your public/assets directory or clear them.

**Comment by gavinfostered** [comment]
Thanks for the reply Ryan! 

Propblem solved now... tried opening everything up to 777 but still same issue. So... Noticed you're using homestead so destroyed my default vm (after backing files and db's up of course), upgraded vagrant to 1.7.x and installed homestead. 

Got to the installation page. All goes well until we get to "Installing module module pages", installation hangs then says "There was an error. Please check your error logs."

Took a look in /var/log/nginx/pyrocms.app-error.log and found the following:

2015/08/09 13:16:23 [error] 1900#0: *45 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.10.1, server: pyrocms.app, request: "GET /installer/module/anomaly.module.pages HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock", host: "pyrocms.app", referrer: "http://pyrocms.app/installer/install"

To solve, added the following line to the http block in /etc/nginx/nginx.conf

fastcgi_read_timeout 300;

Tried it at 150, same error, doubled it, problem solved. Fricking LOVE this new interface! Oh, adding type: "nfs" to the folders mapping inside Homestead.yaml sped things up brilliantly :)


Time to play!

**Comment by RyanThompson** [comment]
Awesome! Unfortunately, due to the nature of the scaffolding and model relationship the installer is easily the heavies aspect of the system. 

I am super glad you got in and running though! I'll make some notes on the installation docs based on your experience here ^_^

**Comment by RyanThompson** [comment]
Also - composer update every now and then as Beta1 will hold some changes to all the modules as I doc them. Ill push a blog today with notes on Beta1 vs Beta2 and how to migrate in changes.

Thanks again!
