### ISSUE TITLE
PyroCMS3 Beta1 - Adding a partial returns error 500

### ISSUE THREAD

**Issue by gavinfostered** [pyrocms/pyrocms#3520]
Adding a partial returns the error 500 view. Error log here:

https://gist.github.com/gavinfostered/a22bfbac797a7f9ca372

Replicate:

1. CP > Partials > Add Fields
2. Add a text field
3. CP > Partials > Add Partial Type
4. CP > Partials > Add Partial of Partial Type
5. Fill in the fields

Results in the error. Least I got my theme all installed. Woooop!

**Comment by RyanThompson** [comment]
Odd.. Ill check it out asap.

Can you retry but change debug=true in your .env file?

Sent from my iPhone

On Aug 11, 2015, at 2:07 PM, Gavin Foster <notifications@github.com<mailto:notifications@github.com>> wrote:


Adding a partial returns the error 500 view. Error log here:

https://gist.github.com/gavinfostered/a22bfbac797a7f9ca372

Replicate:

  1.  CP > Partials > Add Fields
  2.  Add a text field
  3.  CP > Partials > Add Partial Type
  4.  CP > Partials > Add Partial of Partial Type
  5.  Fill in the fields

Results in the error. Least I got my theme all installed. Woooop!

-

**Comment by gavinfostered** [comment]
Here's a quick look at what I get with debug=true

![screen shot 2015-08-11 at 20 40 26](https://cloud.githubusercontent.com/assets/2064358/9208072/6339c3b4-4069-11e5-9a06-9b4b5bb9c249.png)

**Comment by gavinfostered** [comment]
Full debug error here :)

https://gist.github.com/gavinfostered/15fe46616e936251f82f

**Comment by gavinfostered** [comment]
Doesn't seem to matter what field types are added to the partial type either. Tried with text, markdown and wysiwyg

**Comment by RyanThompson** [comment]
I know what it is - fixing

**Comment by gavinfostered** [comment]
Awesome!

**Comment by RyanThompson** [comment]
The selector idea was dumb..

Fixed: https://github.com/anomalylabs/partials-module/commit/7d77966635c97e9ac864e1d50f0572ee62472e77

You will want to run:

    php artisan streams:destroy partials
    php artisan migrate:refresh --addon=anomaly.module.partials

**Comment by gavinfostered** [comment]
Worked! Cheers :D
