### ISSUE TITLE
PyroCMS3 Beta1 - Adding a file returns error 500, file still added successfully

### ISSUE THREAD

**Issue by gavinworks** [pyrocms/pyrocms#3521]
When uploading a file to a created disk the upload dialog box returns error 500. Browsing the disk however, the image is uploaded successfully. Replicate:

1. CP > Files > Disks > + New Disk > Local Storage (e.g. Images)
2. CP > Files > Browser > Images > Upload
3. Drag a file to upload to see error 500
4. CP > Files > Browser > Images
5. File was uploaded successfully

Error and stack trace here:
https://gist.github.com/gavinfostered/25a2bcf173f212ab3620

**Comment by RyanThompson** [comment]
Ya I still need to scour that module and doc it. What does you network activity say for the Ajax request?

**Comment by gavinfostered** [comment]
"Upload". Status 200. Response:
{"name":"logo.jpg","folder_id":null,"disk_id":2,"size":27307,"mime_type":"image\/jpeg","extension":"jpg","updated_at":null,"created_at":"2015-08-11 21:53:03","created_by":1,"sort_order":6,"id":6}

"Images" Status 500. Response:
BadMethodCallException in /home/vagrant/Projects/_dev/pyrocms/vendor/laravel/framework/src/Illuminate/Validation/Validator.php line 2596 Validator.php line 2596: Method [validateRules] does not exist.

**Comment by RyanThompson** [comment]
Awesome thanks - I'm on it

Sent from my iPhone

On Aug 11, 2015, at 5:10 PM, Gavin Foster <notifications@github.com<mailto:notifications@github.com>> wrote:


"Upload". Status 200. Response:
{"name":"logo.jpg","folder_id":null,"disk_id":2,"size":27307,"mime_type":"image\/jpeg","extension":"jpg","updated_at":null,"created_at":"2015-08-11 21:53:03","created_by":1,"sort_order":6,"id":6}

"Images" Status 500. Response:
BadMethodCallException in /home/vagrant/Projects/_dev/pyrocms/vendor/laravel/framework/src/Illuminate/Validation/Validator.php line 2596 Validator.php line 2596: Method [validateRules] does not exist.

-
