### ISSUE TITLE
No site, can't create pages

### ISSUE THREAD

**Issue by eddnav** [pyrocms/pyrocms#3522]
I just installed the latest version of PyroCMS through composer, ran the installer and logged into the dashboard. First time using it, can't seem to create any pages it just says "What type of page would you like to create? No results.", what am I doing wrong? also, going into the site just returns a 404 page...

**Comment by eddnav** [comment]
Closing this, my bad. Should've explored the docs further.

**Comment by RyanThompson** [comment]
Glad you got it going!

Unfortunately I've not got any seeded data just yet. I have to make some improvements to the installer and will add that in. Should help people get started with less reliance on the docs ^_^

**Comment by kdoichinov** [comment]
I'm having the exact same problem and I can't find anything in the docs related to it, @eddnav could you please point me in the right direction? Thanks!

**Comment by adewalegeorge** [comment]
I'm still very much lost here.. can't create pages

**Comment by whitnelson** [comment]
Please do tell us how you solved it. I'm combing the docs and I can't find it.

**Comment by RyanThompson** [comment]
@whitnelson all you need to do is create a page type first (and some fields too). Hope this helps!

**Comment by whitnelson** [comment]
Awesome, thanks!!
