### ISSUE TITLE
Pages Field Section losing switches

### ISSUE THREAD

**Issue by carsonsuite** [pyrocms/pyrocms#3523]
When hovering over the menu the switches seem to disappear partially.
Here is the exact structure to where I saw the error: /public/admin/pages/types/fields/4/assign/132
http://drops.thelifechurch.com/1iAyx

**Comment by carsonsuite** [comment]
I'm seeing this everywhere there is a switch... here is a video occurrence:
http://drops.thelifechurch.com/1kNEG

**Comment by RyanThompson** [comment]
Looks like when the menu covers it - it wipes it out. Odd, any idea? You're a CSS guy right?

**Comment by carsonsuite** [comment]
Yeah! It looks like a browser specific bug with and issue only in chrome. The switch is using "-webkit-mask-box-image" chrome is not rendering it properly. @RyanThompson
