### ISSUE TITLE
issue while creating page with translatable field

### ISSUE THREAD

**Issue by lckamal** [pyrocms/pyrocms#3528]
I was creating a translatable field named content and while adding content in 2 languages I get Undefined property..
screenshot: http://take.ms/bNsvK

**Comment by RyanThompson** [comment]
Do you get this with new installations?

**Comment by lckamal** [comment]
Yes! I had a field named content which was not translatable. I deleted that and added again with translatable checked.

**Comment by RyanThompson** [comment]
Did you not have it checked at first?

**Comment by lckamal** [comment]
well. I uninstalled the installation and grabbed new one and that solved the problem.
thanks.

**Comment by RyanThompson** [comment]
Sure thing! Things will slow down with Beta2 ^_^
