### ISSUE TITLE
documentation?

### ISSUE THREAD

**Issue by doespresso** [pyrocms/pyrocms#3529]
Is there any real reference for v3?
Templating fields for example... and so on

Thanx

**Comment by RyanThompson** [comment]
All documentation is being pushed to: https://www.pyrocms.com/docs/pyrocms/setup/installation

References and all that will come too. Most all str / request and auth helpers are available like str_camel_case() for example but I've lot's to add.. I was busy this last week but will be pushing docs daily and hollering about it on slack / facebook dev group and twitter so people can stay up to date on the progress.
