### ISSUE TITLE
Installing module?!

### ISSUE THREAD

**Issue by websemantics** [pyrocms/pyrocms#3533]
Don't see how to install a private Module, Extension etc?

![screencapture-localhost-pyro-public-admin-addons-extensions-1441924513040](https://cloud.githubusercontent.com/assets/2190455/9803025/1715468e-581f-11e5-98f0-f6aeaed5de37.jpg)

**Comment by RyanThompson** [comment]
Click on the "Uninstalled" view for the table - the table actions at the bottom will have contextual buttons.

Piss poor design I am afraid (which is being remedied).

**Comment by websemantics** [comment]
Thanks @RyanThompson, I can see it now.
