### ISSUE TITLE
Pagination for Stream's Entry Looping doesn't work

### ISSUE THREAD

**Issue by flip3** [pyrocms/pyrocms#3534]
When I display a stream using the standard code from http://docs.pyrocms.com/2.1/manual/plugins/streams/entry-looping, the pagination doesn't work. The paginated pages can't be found (Error 404). I'm using PyroCMS Pro 2.2.5 (almost same issue with the search which someone here marked as fixed but when clicking on paginated pages, it always shows the results from the first page).

{{ streams:cycle stream="mini_site_start_page" limit="5" paginate="yes" }}
 
    <p>{{ total }} entries returned.</p>
 
    {{ entries }}
 
        <h2>{{ language }}</h2>
 
    {{ /entries }}
 
    {{ pagination }}
 
{{ /streams:cycle }}

**Comment by bloveless** [comment]
What is the initial URL of the page you are displaying the streams on? And what is the URL that is generating the 404 page? Make sure that use exact URL checkbox is not checked on the page you are displaying the stream on.

**Comment by bloveless** [comment]
The checkbox is called "require an exact uri match" and is on the options tab of the page you are trying to display the stream on.

**Comment by flip3** [comment]
Hi, Yes, that's it for the streams page. Sorry, then it's working indeed. However for the search page I unchecked "require an exact uri match" but on any paginated page the results from the first page are shown, e.g. http://www.ailolaquito.com/search/3?q=spanish

**Comment by bloveless** [comment]
I'm a little less familiar with the search pagination. Do you have pagination="yes" in your results stream? http://docs.pyrocms.com/2.2/manual/plugins/streams/basic-search would you post the code you are using to show the search results?

**Comment by flip3** [comment]
I'm using the standard search tag (http://docs.pyrocms.com/2.2/manual/developers/tools/search) and the behavior isn't changing when adding pagination="yes".

**Comment by bloveless** [comment]
Remove pagination="yes" and change your search tag to look like this {{ search:results uri="search" }} see if that helps you.

**Comment by flip3** [comment]
It works ;-) That's really good because the search wasn't working for 2 years now. I just changed {{ search:results limit="10" uri="/search" }} to {{ search:results limit="10" uri="search" }}. Thanks a lot!

**Comment by bloveless** [comment]
Glad I can help!
