### ISSUE TITLE
Default installation fails: failed to open stream, no such file or directory

### ISSUE THREAD

**Issue by sebastiaanluca** [pyrocms/pyrocms#3536]
Running the installation command

```
composer create-project pyrocms/pyrocms=3.0-beta1 --prefer-dist
```

results in

```
[ErrorException]                                                                                                                                              
file_get_contents(/var/www/bitsoflove/pyro-cms-test-2/pyrocms/core/anomaly/variables-module/composer.json): failed to open stream: No such file or directory

Script php artisan clear-compiled handling the post-install-cmd event returned with an error
```

when it hits

```
php artisan clear-compiled
```

Browsing to my application also throws the same exception:

```
ErrorException in AddonLoader.php line 55: file_get_contents(/var/www/application/core/anomaly/variables-module/composer.json): failed to open stream: No such file or directory
```

Funny thing is I successfully installed it this morning the same way. Clean Homestead VM btw, but same error on my local machine and other VMs.

**Comment by RyanThompson** [comment]
Hey there - I am trying to figure out why it INSISTS on that being there but not sure at this point. I removed it AND updated the beta.. try composer clear-cache though

**Comment by sebastiaanluca** [comment]
Was trying to figure out the same thing, but I can't find `variables-module` anywhere 😕

**Comment by sebastiaanluca** [comment]
@RyanThompson Did a fresh install on a new VM, but that command still fails with the same error.

**Comment by ugrupp** [comment]
same problem here. is there any way to get pyrocms installed right now?

**Comment by RyanThompson** [comment]
Remove the variables directory from core/anomaly

Trying to figure out why composer is still trying to install that.

**Comment by RyanThompson** [comment]
It's not in composer anymore: https://packagist.org/packages/pyrocms/pyrocms

**Comment by droplab** [comment]
I'm having that same error too :(

**Comment by erikbelusic** [comment]
same issues as recent as 5 minutes ago =] works after removing directory

**Comment by jraack** [comment]
same error here :(

**Comment by jraack** [comment]
Just delete the directory variables-module. Then it will load.

**Comment by RyanThompson** [comment]
Thanks to @JoelESvensson for the fix!

https://github.com/pyrocms/pyrocms/pull/3540
