### ISSUE TITLE
Checkbox for TOS not blocking installation

### ISSUE THREAD

**Issue by youanden** [pyrocms/pyrocms#3541]
I just installed PyroCMS and it turns out that I forgot to tick that checkbox, but I did not see any validation errors, and the installer continued.

**Comment by RyanThompson** [comment]
Yaaa it's just for show :-)

Lol I've needed to button up the installer for some time - has a few oddities

**Comment by RyanThompson** [comment]
Closing this for now - on the docket for the installer rebuild tomorrow.
