### ISSUE TITLE
Getting system error while installing pyrocms 3.0

### ISSUE THREAD

**Issue by rgogulakrishnan** [pyrocms/pyrocms#3543]
Just cloned the 3.0 branch and installed. Got 500 and i see the below from logs.

```
[2015-09-27 14:16:56] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Mmanos\Search\SearchServiceProvider' not found' in /opt/lampp/htdocs/pyrocms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:575
```

Thanks

**Comment by tomcastleman** [comment]
@rgogulakrishnan yea I just updated by beta1 and also getting this error now. Trying to liaise with @RyanThompson on slack to get to the bottom of it.

**Comment by rgogulakrishnan** [comment]
@tomcastleman will you be able to send a slack invite (the username is same as github!). Thanks in advance.. @RyanThompson

**Comment by tomcastleman** [comment]
@rgogulakrishnan you can do that yourself [here](http://pyrocms.com/chat)

**Comment by RyanThompson** [comment]
Pull again - fixed: https://github.com/anomalylabs/streams-platform/commit/ab85c42637ce36cd350dbf42d0d18d0abbb1a62a
