### ISSUE TITLE
Unable to sign in into the forum at https://forum.pyrocms.com/

### ISSUE THREAD

**Issue by rtarasov** [pyrocms/pyrocms#3545]
Hi Guys!

I wold like to comment on your forum. The message says that I must sign in first. 
The problem is that I can NOT find a sign-in form on the page.

Could you please help with that?

Thanks in advance!

Roman.

**Comment by RyanThompson** [comment]
Try:

First logging in or registering if needed here: 
https://codeigniter.pyrocms.com/users/login

Then head over to the forum and click the sign in button again. Just make sure you're logged into PyroCMS.com first.

**Comment by rtarasov** [comment]
Hi Ryan!

Have logged into codeigniter.pyrocms.com

[image: Inline image 1]

The problem is that - still can not see he SignIn button in the forum:

[image: Inline image 2]

What is wrong? Could you please help?

Roman.
