### ISSUE TITLE
PyroCMS Pro Multi Site Configuration

### ISSUE THREAD

**Issue by alexgaspersz** [pyrocms/pyrocms#3546]
1. I've installed pyrocmspro in main domain http://bataminternational.tk/
2. Alreadey add subdomain CNAME in control panel
![screen shot 2015-10-09 at 2 24 55 pm](https://cloud.githubusercontent.com/assets/8047007/10388134/8f347968-6e91-11e5-8af0-1ae72d7d3a02.png)

3. Add domain and subdomain in cms domain module
![screen shot 2015-10-09 at 2 24 35 pm](https://cloud.githubusercontent.com/assets/8047007/10388138/989aef6e-6e91-11e5-8269-3c65446edeeb.png)

4. Create New Site in http://bataminternational.tk/sites
![screen shot 2015-10-09 at 2 21 05 pm](https://cloud.githubusercontent.com/assets/8047007/10388094/376dbdde-6e91-11e5-8a12-510274afa545.png)

But when open my subdomain in browser, it show an error pages 404

Do i missed some configuration?
Pls help

Regards,
Alex

**Comment by ChristianGiupponi** [comment]
Hi @alexgaspersz make sure that you created your subdomain in your cpanel and point the document root to the main domain
