### ISSUE TITLE
[ PyroCMS 3 ] - New Page Type and New Fields generate 500 error

### ISSUE THREAD

**Issue by ChristianGiupponi** [pyrocms/pyrocms#3548]
## Issue
When you create and click "save & exit" a new page type it shows 500 error page

## How to reproduce
1. Log in the Admin area
2. Go in "Pages" module
3. Click on "Types"
4. Click on "New Page Type"
5. Add a title
6. Click on "Save & Exit"

if you just click "save" everything works.

You can find the same issue in the "Fields" tab.

**Comment by RyanThompson** [comment]
Fixed

**Comment by j-hubb** [comment]
I'm seeing this as well on the latest pull update.

**Comment by RyanThompson** [comment]
On it!

**Comment by nickeblewis** [comment]
Yes, just saw this too
