### ISSUE TITLE
PyroCMS Store Active?

### ISSUE THREAD

**Issue by AspireToCodeBetter** [pyrocms/pyrocms#3549]
Hi Guys,

Is the PyroCMS store active? I seem to have stopped getting any sales from the Code Igniter themes. Can you please check?

Have you guys opened up a store for Laravel version? There isn't any link on the main home page for Laravel based products either.

Can you provide some stats around the Sales, Downloads and Future map for products based off PyroCMS? Themes and Addons will likely be very critical for further adoption of PyroCMS.

**Comment by AspireToCodeBetter** [comment]
@RyanThompson any guidance on this?

**Comment by RyanThompson** [comment]
It's active but very slow. Most people are waiting for the new release. Only the regulars on there buying for their projects mostly. Nothing adventurous.
