### ISSUE TITLE
PyroCMS 3 Beta 1 - Runtime dependencies are missing if composer --no-dev specified

### ISSUE THREAD

**Issue by PMLavigne** [pyrocms/pyrocms#3550]
As far as I can tell, the only "dev" dependency that PyroCMS 3 has is for unit testing (phpunit), so I attempted to install using --no-dev to skip that part since it seems unnecessary for my use case. Later, I wound up getting several random 500 errors around the site, and after checking the log I found the following:

```
[2015-10-13 20:45:12] local.ERROR: exception 'ReflectionException' with message 'Class Symfony\Component\Yaml\Yaml does not exist' in /srv/vendor/laravel/framework/src/Illuminate/Container/Container.php:790
Stack trace:
#0 /srv/vendor/laravel/framework/src/Illuminate/Container/Container.php(790): ReflectionParameter->getClass()
#1 /srv/vendor/laravel/framework/src/Illuminate/Container/Container.php(771): Illuminate\Container\Container->getDependencies(Array, Array)
#2 /srv/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build('Anomaly\\Textare...', Array)
#3 /srv/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Anomaly\\Textare...', Array)
#4 /srv/vendor/anomaly/streams-platform/src/Addon/FieldType/FieldType.php(816): Illuminate\Foundation\Application->make('Anomaly\\Textare...', Array)
#5 /srv/vendor/robclancy/presenter/src/Decorator.php(17): Anomaly\Streams\Platform\Addon\FieldType\FieldType->getPresenter()
#6 /srv/vendor/anomaly/streams-platform/src/View/Listener/DecorateData.php(45): Robbo\Presenter\Decorator->decorate(Object(Anomaly\TextareaFieldType\TextareaFieldType))
#7 [internal function]: Anomaly\Streams\Platform\View\Listener\DecorateData->handle(Object(Anomaly\Streams\Platform\View\Event\ViewComposed))
#8 /srv/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(348): call_user_func_array(Array, Array)
...
```

It turns out that the "symfony/yaml" dependency was not being pulled in by anything *but* the "phpunit/phpunit" dependency, and by not pulling in phpunit the project was missing this vital (yet unrelated) component. I fixed this case on my own site by just adding the dependency to PyroCMS itself, but it seems to me like it should actually be pulled in transitively by one of the "anomaly/" dependencies. I'd be happy to do a pull request for this but I'm not sure which anomaly/ dependency actually needs it.

**Comment by RyanThompson** [comment]
Ahh good catch - absolutely I'd love a PR. I assumed it was on Laravel but go ahead and add it to anomalylabs/streams-platform

**Comment by PMLavigne** [comment]
Okay, should be good to go. I used the same version string as phpunit was using and just tried it out on a test site and it seems to work fine.

**Comment by TisConsultores** [comment]
Error (500) - Please check your application error logs. 
log:
src/Illuminate/Container/Container.php:790 :(

**Comment by RyanThompson** [comment]
I'll check again but I thought a PR was already pulled in to include YAML. If not I'll add it and give er a try.
