### ISSUE TITLE
Upgrade from Pyro 2.1.x to 2.2.5 error in Navigation

### ISSUE THREAD

**Issue by ikoniqoz** [pyrocms/pyrocms#3551]
Following an upgrade from 2.1.5 to 2.2.5 I get an error in Admin -> Navigation. This appears to be associated with the recently added Custom Link Type. When the Custom the Custom Link Type is selected the following error is displayed: 
A PHP Error was encountered
Severity: Notice
Message: Undefined property: stdClass::$custom
Filename: ajax/form.php
Line Number: 77
" />
Note the " /> which appears below the Page file label in the view.
I was able to re-produce this error in 2 upgrades.

**Comment by bloveless** [comment]
When I wrote that change I didn't write a migration for upgrading. Give me a bit and I'll figure out how to do it.

**Comment by bloveless** [comment]
Can I ask if you pulled 2.2/develop or 2.2/master? My custom type doesn't exist in 2.2/master.

**Comment by ikoniqoz** [comment]
May have to consider upgrade from say 2.1.x as well as say upgrading from 2.2.x (eg: 2.2.1 -> 2.2.5)

**Comment by bloveless** [comment]
#3552 Should be fixed.

I just tested by creating a new 2.1 site and checking out 2.2/develop. It migrates the database correctly now.

**Comment by bloveless** [comment]
Also keep in mind that this 2.2/develop won't be made official until pyro 3 is released. Then it will be released as 2.2.6 if I remember correctly.

Will you try to upgrade again and let me know if the problem persists? Then close this issue if it is fixed.

Thanks

**Comment by ikoniqoz** [comment]
@bloveless Thanks for the quick response. Will try a few upgrades and report back - and yes - I am working off the 2.2.5/dev branch....

**Comment by ikoniqoz** [comment]
@bloveless Upgrade from 2.1.5 to 2.2.5 works fine. However, I see that the name of the Migration file needs to be changed to be 131_Add_custom_to_navigation.php - Note the uppercase "A" in 131_Add.

I will see if I can do an upgrade from a 2.2.1 site next. Will report back within 24hrs.

**Comment by bloveless** [comment]
I've updated the the migration file name. Thanks for the assist! I'm going to close this issue. Please re-open it if you continue to have issues.
