### ISSUE TITLE
"The installer module still exists!" message, yet appears as uninstalled/disabled in module list

### ISSUE THREAD

**Issue by snetty** [pyrocms/pyrocms#3553]
After a clean install, the message `The installer module still exists! Please delete it from your server! Leaving it online means control of this site could be granted to somebody else.` appears in the dashboard.  However, in Addons / Modules, the Installer module is marked as `uninstalled`

**Comment by RyanThompson** [comment]
Ya, but it needs to be deleted from the system as well. Otherwise it could potentially be installed and utilized again.

**Comment by snetty** [comment]
yeah, of course.  But you're asking for it to be removed, and when I go to the logical place to remove it, it looks like it has been.  I suppose ultimately this is a UX problem, but it's a pretty horrible one to experience as soon as you're done installing.  The message doesn't even tell you where it needs deleting from.

**Comment by RyanThompson** [comment]
I agree whole heartedly. The addons module needs its 1.1 tag I might tackle that this afternoon. Should be easy enough.
