### ISSUE TITLE
Twig cache not being cleared

### ISSUE THREAD

**Issue by daviesgeek** [pyrocms/pyrocms#3556]
The Twig cache isn't being cleared when necessary for the pages. When creating a page type and modifying the layout, the pages with that page type aren't updated. Running `php artisan twig:clean` fixes it and it works as expected after that.

**Comment by RyanThompson** [comment]
Fixed!

**Comment by daviesgeek** [comment]
I did a `composer update` and updated, but I don't see a difference. Neither editing a page type layout nor editing a page's fields clear the cache (a manual clean works as expected)

**Comment by RyanThompson** [comment]
Fixed!
