### ISSUE TITLE
Upgrading CodeIgniter 3.0.3 for security release on PyroCMS 2.x

### ISSUE THREAD

**Issue by afbora** [pyrocms/pyrocms#3559]
Will planned upgrading to CodeIgniter 3.0.3 for security release on PyroCMS 2.2.5?

Thanks

**Comment by afbora** [comment]
I tried to upgrade 3.0.3 self but i couldnt. Not compatible with MX, some functions, libraries, etc..

**Comment by RyanThompson** [comment]
Ya I am not sure how realistic jumping up the major version is.. I would be curious what security issues have been addressed and see about merging those in.

**Comment by afbora** [comment]
I upgraded to 3.0.3 self but modified so many files. Thanks @RyanThompson

**Comment by pdring** [comment]
Hi. Could you make your 3.0.3 version available please?

**Comment by afbora** [comment]
I have no files anymore, sorry.
