### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by Remo** [pyrocms/pyrocms#3564]
I've been trying to make PyroCMS3 faster, but so far I'm a bit lost in all the Laravel internals. I can see that most time is spent on the pipelines and their commands. I only get the impression that we simply handle too many things for each request.
However, I can't imagine that I'm not missing anything.

I'm just posting this here hoping to get some hints that push me in the right direction. I'd be happy to keep profiling it, but I feel like I'm stuck unless I find the time to completely analyse every line of PyroCMS.

A profile where you can see that we've got quite a few callers:
![image](https://cloud.githubusercontent.com/assets/129864/11313385/cacdfb68-8fdc-11e5-93d2-956fa5d28a0c.png)

**Comment by RyanThompson** [comment]
Hey @Remo - thanks for delving in! It's true there is a lot going on. The addon registration is my biggest concern as well as the multiple maps. There MUGHT be a recursion somewhere but overall .. I think the biggest issue is class auto loading. I've got a couple ideas following what Taylor did with Laravel but have yet to experiment. Basically optimize everything into a single psr0 directories per vendor with an optimize command or maybe ship it built like that..
