### ISSUE TITLE
[PyroCMS 3] Deleting a parent navigation link does not remove children, also does not show them

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#3565]
When you delete a parent navigation link, the children links do no get deleted, while this in itself isn't nessecarily bad, the backend gui no longer displays these child nav links.

The given effect is it looks like it is deleted, however it is not as it is in the DB, it also shows in the front end when using the nav_group twig macro.

To recreate, create a nav link, then create a child nav. Delete the parent.

**Comment by RyanThompson** [comment]
Needs an observer to fire on the deleted event. Will do.
