### ISSUE TITLE
Anomaly\FilesModule\Adapter\AdapterExtension not found

### ISSUE THREAD

**Issue by lsobral** [pyrocms/pyrocms#3567]
I found this error on install by composer

My server point to public directory

PHP Fatal error:  Class 'Anomaly\FilesModule\Adapter\AdapterExtension' not found in /Applications/MAMP/htdocs/pyrocms/pyrocms/core/anomaly/local_storage_adapter-extension/src/LocalStorageAdapterExtension.php on line 14

**Comment by RyanThompson** [comment]
Fixed this - re-composer install
