### ISSUE TITLE
Error on PyroCMS 3 installation

### ISSUE THREAD

**Issue by feuzeu** [pyrocms/pyrocms#3569]
Just tried installing PyroCMS 3 Beta 1.
I've started on CLI with the following command and all just went well.
composer create-project pyrocms/pyrocms=3.0-beta1 --prefer-dist

Then I started the install in the browser, and after a while I got the message "There was an error. Please check your error logs.".

According to the browser console logs, the error occurs on the page "installer/run/6", and the following message is written in the Laravel logs.
development.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function getPrefix() on a non-object' in /srv/sunrise/core/app/content/vendor/anomaly/streams-platform/src/Assignment/AssignmentModel.php:290.

What have I done wrong?

**Comment by RyanThompson** [comment]
Would you mind clearing your DB and trying a fresh install of Beta2?

**Comment by feuzeu** [comment]
I've tried a fresh install with Beta2, and it worked.
Thanks.
