### ISSUE TITLE
[feature] Generate migrations when creating/altering content tables

### ISSUE THREAD

**Issue by tobz-nz** [pyrocms/pyrocms#3573]
It would be awesome if a migration was generated each time a content table - e.g. pages - was created or altered.

This means you could create all your data structures locally then run the migrations as part of your deploy process - no need to manually redo all that work in all you're separate environments (which is a laborious process & very error prone).

**Comment by RyanThompson** [comment]
Hey @tobz-nz - this is something I have been thinking about for some time. How do you foresee this working? For example, when you edit a page that creates a new migration, yes?

And for the production environment. Do the same thing? So they "merge" the users doings and your own as the developer?

**Comment by tobz-nz** [comment]
yes, I guess if you were to change schema's in production It'd still generate a migration - you'd have to commit it from the production server back into source control though - I'd never recommend doing it that way.

Generally how I've always worked is the client never makes those sorts of changes - it usually requires design changes anyway....

I just think - If the database structure is ever changed, it should be done with(or at least create) a migration.

I'm glad to hear you've been thinking about this too. If this were to be implemented Pyro would have a big win over EE, Craft & others.

**Comment by edmeehan** [comment]
Sounds like an awesome feature, would love to follow progress.

**Comment by RyanThompson** [comment]
A good friend of mine has this right now - will be merging parts of it into core soon: http://websemantics.ca/build-laravel-applications-faster-with-pyrocms-and-entity-builder/

**Comment by tobz-nz** [comment]
Cool, looks interesting.
