### ISSUE TITLE
Creating a duplicate Variables group throws exception

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#3574]
validation should prevent the script from getting to this point.

https://www.evernote.com/l/ADJhGIc11P1HPKSsHBE0h8yVnFZStUHCUsc

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/47e4865ccd2491cd6845928eebf1e78bc783360d
