### ISSUE TITLE
Installer blank page

### ISSUE THREAD

**Issue by pdring** [pyrocms/pyrocms#3575]
Hi,

Having downloaded the latest files through **composer create-project pyrocms/pyrocms=3.0-beta2 --prefer-dist ff** and modified the permissions (777) for **storage**, **bootstrap > cache** and **public > assets**, I still have a blank page when I go to (URL)/installer

I am using MAMP, but I I'm not sure what I'm missing to get to the installer.

Thanks.

**Comment by RyanThompson** [comment]
Can you check your apache error logs and let me know what they say? Almost always permissions of some sort. Or a missing PHP extension. Your logs will let us know what's up though.

**Comment by YOMorales** [comment]
So, I did the same exact steps of:
1. composer create-project pyrocms/pyrocms=3.0-beta2 --prefer-dist
2. modified the permissions (777) for storage, bootstrap > cache and public > assets

Then I created a site configuration in nginx. My root is `/home/name/path/pyrocms/public`.
But when I accessed the url for my test site, I got:

2015/12/24 01:41:40 [error] 7916#0: *4 open() "/home/name/path/pyrocms/public/installer" failed (2: No such file or directory), client: 127.0.0.1, server: pyrocms.local, request: "GET /installer HTTP/1.1", host: "pyrocms.local"

I cannot find such "installer" file anywhere.

**Comment by RyanThompson** [comment]
Looks like your rewriting is not set up: https://laravel.com/docs/5.1/installation#configuration

See pretty urls

**Comment by YOMorales** [comment]
Oh ok, I'm now seeing the installer.
Didn't know that you also had to follow the configuration according to the Laravel docs (I thought that the PyroCMS instructions were all).

Thanks.

**Comment by YOMorales** [comment]
Actually, I now see that such pretty-urls instructions were in the PyroCMS docs.
Although they come after running the installer.
Maybe they should be placed on top, before running the installer.

**Comment by RyanThompson** [comment]
Ya docs will definitely need massaging. Glad you got it working!
