### ISSUE TITLE
File Field Type - Admin GUI bug - modal breaks on pagination selection

### ISSUE THREAD

**Issue by edmeehan** [pyrocms/pyrocms#3576]
Bug: clicking the pagination on the File field type modal pop-up returns blank white page, no errors

Reproduce: Go to the pages or posts module in Admin. Add the file field type to a page or post type. Make sure you have enough files in the files module to product pagination when selected. Create a new  page or post and switch to the "fileds" tab, then select the "select file" option from the file field type. A modal should apper in the admin UI. Scroll to the bottom of the modal and select page 2 in the pagination. This should produce the bug.

**Comment by RyanThompson** [comment]
Good catch - will address this tonight! Thank you.
