### ISSUE TITLE
[ PyroCMS 3 ] - Error 500 - Can't create disk or folder in files module

### ISSUE THREAD

**Issue by ChristianGiupponi** [pyrocms/pyrocms#3577]
This is the redirect url:
    
`http://pyrocms.app/admin/files/disks/edit/%7Brequest.route.parameters.id%7D`

Steps to reproduce the issue:

1. Log in as Admin
2. Go to the Files module
3. Click on new Disk
4. Click "Save & Exit"
5. See error 500

If you just go back to the main disk page you can see that the disk is actually create so this could be just a redirect error.

Same on Folders page.

**Comment by RyanThompson** [comment]
Eh this drat'd save and edit. Will address, thanks for reminding me! It's system wide for the most part..

**Comment by RyanThompson** [comment]
Should be good to go! `composer create-project pyrocms/pyrocms=3.0-beta3 --prefer-dist`
