### ISSUE TITLE
Composer dependency error: intervention/image wrong version

### ISSUE THREAD

**Issue by marijnhur** [pyrocms/pyrocms#3579]
When installing Beta2 on windows through Composer I get the following error message:

```
[RuntimeException]
  Could not load package intervention/image in http://packagist.org: [UnexpectedValueException] Could not parse version constraint 4.x.x: Invalid version string "4.x.x"
```

It seems that the latest version of this package is 2.3.4.

Is there any way to install PyroCMS Beta2 with the right dependency in the meantime?

**Comment by RyanThompson** [comment]
Not sure where that would be coming from: https://github.com/anomalylabs/streams-platform/blob/1.0/develop/composer.json#L15

**Comment by Remo** [comment]
I had the same message but it didn't happen the second time I tried. Maybe just a cache issue? Couldn't track it down as it disappeared..

**Comment by marijnhur** [comment]
Okay, I'm going to retry it.
