### ISSUE TITLE
where location of logs file ?

### ISSUE THREAD

**Issue by viyancs** [pyrocms/pyrocms#3588]
I was succefully install pyrocms/pyrocms=3.0-beta2, then i try to use this cms by generating page, type of page , category post , at that time little confuse what should i do first. is there any documentation for guide this case ?

also I got error when i want to delete my post, 500 internal server error, maybe if i know where the location of logs file it's will helpfull for me.

thanks

**Comment by RyanThompson** [comment]
The logs file is in the same location as laravel puts them - storage/logs/*

**Comment by RyanThompson** [comment]
Working on docs - none but those found at pyrocms.com right now.
