### ISSUE TITLE
error 404 at /public/ path 

### ISSUE THREAD

**Issue by viyancs** [pyrocms/pyrocms#3589]
hi i have error when fresh intsall pyrocms , the error is 404 in home path .

**Comment by RyanThompson** [comment]
Make a page first. 


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by RyanThompson** [comment]
There is no seeder for the installer / default pages just yet. So you need to login and make one.


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581
