### ISSUE TITLE
Conflict with images

### ISSUE THREAD

**Issue by weldygx** [pyrocms/pyrocms#3590]
At some point on or after Monday, December 21, a gap of random height has started displaying under images. At first, I thought it was a change in html code I made (that shouldn't have affected it) but then I noticed on a 2nd site that had no modifications, that it was on that site as well.

Was there some sort of code change done to Pyro that caused this? I have scoured through my code to figure it out and have come up with nothing.

The links to both sites are:

http://flhealthsource.gov (note the slider)
http://healthypromiseFL.com (click View Submitted Promises)

**Comment by RyanThompson** [comment]
https://github.com/pyrocms/pyrocms/tree/2.2/develop

Last commit - Oct 26th.
