### ISSUE TITLE
[Pyro 3 Beta 2] navigation links aren't being hidden when the roles say they should be

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#3591]
If you navigate to a page where you must be logged in, (my example is `gate_codes`) I get the url `/login` with `NotFoundHttpException in RouteCollection.php line 161:`
If you are logged in and go to a protected page `/about-byc/gate-codes` and logout I get `/about-byc/logout` with the same error as above
If I'm on the home page and logout, it works fine (same link)
Link rendered with `<a href="{{ logout_path() }}">`(edited)

Pages that are marked to be hidden for those not logged in etc are not being hidden from the navigation as well.

**Comment by RyanThompson** [comment]
This has been fixed
