### ISSUE TITLE
Brand new Install failing

### ISSUE THREAD

**Issue by ryanhungate** [pyrocms/pyrocms#3592]
Homestead.
composer create project.
go to install screen
fill out form elements
save
all sorts of errors in the javascript console that are preventing the install from completing.

Uncaught SyntaxError: Unexpected token <
install:240 Uncaught ReferenceError: PhpDebugBar is not defined(anonymous function) @ install:240
99f9f65e851f97143a5d814a258afd7b.js:58 Uncaught TypeError: $ is not a function

**Comment by RyanThompson** [comment]
Disable the debugger during installation - it ruins everything for some reason..

**Comment by ryanhungate** [comment]
Sorry this is like day 1 minute 1 for me looking at pyro... how do you disable that?

**Comment by ryanhungate** [comment]
Ok i just realized that something is off with the environment variables - because as soon as I disabled the debugbar in the config file manually, ( not based on the APP_DEBUG environment variable ) it's working.

**Comment by RyanThompson** [comment]
Hey no worries! Still pretty early for most people but I appreciate you digging in! Lot of docs / brand new site and launch in February so should get easier to make sense of everything real soon. Feel free to ping me in Slack with any questions until then though!
