### ISSUE TITLE
[3.0-beta2] some templates not rendering

### ISSUE THREAD

**Issue by pmall** [pyrocms/pyrocms#3594]
After installing pyrocms 3 beta 2 I have this errors on many pages, basically all the pages for adding things (for example admin/dashboard/create) :

~~~
An exception has been thrown during the rendering of a template ("variable @secondary is undefined in file anonymous-file-0.less in anonymous-file-0.less") in "theme::partials/metadata" at line 27.
~~~

I work on a VM with ubuntu 14.04 64bits, basic apache2 configuration. No idea what to do about it.

**Comment by RyanThompson** [comment]
Can you pull latest and composer update and check that this is persisting?


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by pmall** [comment]
I tried but now I cant even install pyro, I get this on the install page : 

~~~
Method Anomaly\Streams\Platform\Image\Image::__toString() must not throw an exception
~~~

**Comment by RyanThompson** [comment]
That is indicative of either:

1.) Your public/assets folder needs to be 777'd

or 

2.) The resources/core/config/addons directory is actually addon (singular).

I would double check the latter because I recently had to update the Beta2 release as it was a bit behind.. my bad :-(

**Comment by pmall** [comment]
Ok I'll try what you suggest and I'll report you this soon :-)

-----Message d'origine-----
De : "Ryan Thompson" <notifications@github.com>
Envoyé : ‎03/‎02/‎2016 18:38
À : "pyrocms/pyrocms" <pyrocms@noreply.github.com>
Cc : "pmall" <pierre.mallinjoud@gmail.com>
Objet : Re: [pyrocms] [3.0-beta2] some templates not rendering (#3594)

That is indicative of either:
1.) Your public/assets folder needs to be 777'd
or 
2.) The resources/core/config/addons directory is actually addon (singular).
I would double check the latter because I recently had to update the Beta2 release as it was a bit behind.. my bad :-(

**Comment by pmall** [comment]
Unfortunately the resources/core/config/addons is actually well named and I tried to 777 my public/assets folder, same error.

Here is my vagrantfile with provisioning so you can test it https://raw.githubusercontent.com/pmall/pyrocms/master/Vagrantfile hope it can help :)

**Comment by RyanThompson** [comment]
This was likely due to my fussing around with variables during this B3 push - can you try again in a fresh install on B3? `composer create-project pyrocms/pyrocms=3.0-beta3 --prefer-dist`

**Comment by pmall** [comment]
Thanks it's working now :)

2016-02-21 13:59 GMT+01:00 Ryan Thompson <notifications@github.com>:
