### ISSUE TITLE
Problem routing site

### ISSUE THREAD

**Issue by bahman2216** [pyrocms/pyrocms#3595]
I have installed fully, Login page is success but view site has problem:
NotFoundHttpException in RouteCollection.php line 161:

**Comment by RyanThompson** [comment]
You need to make a page now is all - Beta3 will come with seeders but until then your install comes completely empty.

**Comment by bahman2216** [comment]
So how can login to admin panel? It just login page /admin/login and users table is empty!

**Comment by RyanThompson** [comment]
Hmm.. sounds like your install might have broken?

admin/login is the correct login path.

Perhaps try running the installer again. That's odd. Sorry for the hassle!

**Comment by bahman2216** [comment]
admin/login route is correct. I mean How can I make user admin to login? users table is empty and admin panel not accessible.

**Comment by RyanThompson** [comment]
It should have created a user and roles for you when installing - you need to install again.

**Comment by RyanThompson** [comment]
Try this again with B3 `composer create-project pyrocms/pyrocms=3.0-beta3 --prefer-dist`

**Comment by bahman2216** [comment]
Thanks. it works perfect. Many changes from last.
