### ISSUE TITLE
OOB New User broken (Server Error 500)

### ISSUE THREAD

**Issue by uxinnuendo** [pyrocms/pyrocms#3596]
From /admin/users/ :
Click the "New User" Button

The page directs to : /admin/users/create 
With a Server 500 error.

Installed 13th Feb 2016:
composer create-project pyrocms/pyrocms=3.0-beta2 --prefer-dist

**Comment by RyanThompson** [comment]
Try composer update until you get the latest anomaly theme - just pushed it (working on B3 theme finalizations and this issue is caused from these missing variables).

https://github.com/anomalylabs/anomaly-theme/commit/24bece06e0062a4e54dfbd3f132e8f021f17de1b

**Comment by RyanThompson** [comment]
Also what's OOB?

**Comment by uxinnuendo** [comment]
Cheers Ryan, will do.
OOB - "Out of box", ie. fresh install with nothing touched by me as yet.

**Comment by RyanThompson** [comment]
Ahh learned something new - cheers!

**Comment by uxinnuendo** [comment]
Very welcome! And thanks for the fix :)
