### ISSUE TITLE
repository 'https://github.com/anomalylabs/partials-module.git/' not found  

### ISSUE THREAD

**Issue by anilkoeri** [pyrocms/pyrocms#3599]
I am new to pyrocms while installing i am getting below error.. Please help me to overcome this issue.  

[RuntimeException]                                                                                       
  Failed to clone git@github.com:anomalylabs/partials-module.git via git, https, ssh protocols, aborting.  
  - git://github.com/anomalylabs/partials-module.git                                                       
    Cloning into 'core/anomaly/partials-module'...                                                         
    fatal: remote error:                                                                                   
      Repository not found.                                                                                
  - https://github.com/anomalylabs/partials-module.git                                                     
    Cloning into 'core/anomaly/partials-module'...                                                         
    remote: Repository not found.                                                                          
    fatal: repository 'https://github.com/anomalylabs/partials-module.git/' not found                      
  - git@github.com:anomalylabs/partials-module.git                                                         
    Cloning into 'core/anomaly/partials-module'...                                                         
    ERROR: Repository not found.                                                                           
    fatal: Could not read from remote repository.                                                          
                                                                                                           
    Please make sure you have the correct access rights                                                    
    and the repository exists.

**Comment by broklyngagah** [comment]
me too..
@RyanThompson Looks like the repository doesn't exist.

**Comment by reypm** [comment]
@RyanThompson +1 agreed the repository does not exist

**Comment by RyanThompson** [comment]
I've remove partials from the free release - pre orderer holders already have access to it so you can include as you please.

The require has been dropped from the B3 / 3.0/develop branch as well.

**Comment by RyanThompson** [comment]
If you checkout the 3.0/develop branch it will install - I am working on finishing up for release now and will update the tag for pyro too.

**Comment by reypm** [comment]
@RyanThompson what's the proper command on this case for composer? 

    composer create-project pyrocms/pyrocms=3.0-beta2 --prefer-dist

**Comment by RyanThompson** [comment]
Just pull `pyrocms/pyrocms` and check out `3.0/develop` then composer install like normal.

**Comment by reypm** [comment]
@RyanThompson by pull you mean clone the whole repository then checkout `3.0/develop` branch and then install dependencies using composer?

**Comment by RyanThompson** [comment]
Yessir!
