### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by j-hubb** [pyrocms/pyrocms#3600]
When the viewport is 926-930 high, the top menu flickers between stuck and unstuck when scrolling to the bottom of the screen on some pages:

http://share.jhubb.io/lXQ2bgX

**Comment by RyanThompson** [comment]
Can you check this out in latest version. `php artisan asset:clear` to assure you've got freshly compiled assets.

**Comment by j-hubb** [comment]
Yes, it's still an issue. http://share.jhubb.io/7IXJAoI

**Comment by RyanThompson** [comment]
How realistic is it to fix this? Won’t this be an issue at whatever the affix trigger point is?

**Comment by j-hubb** [comment]
I think you're right. I've tested a few options and can't fix it. It's particular to this page and will happen very rarely.

**Comment by RyanThompson** [comment]
Word
