### ISSUE TITLE
Redirect Issue

### ISSUE THREAD

**Issue by j-hubb** [pyrocms/pyrocms#3604]
When a session has expired and an action is made (such as reordering pages) where login is needed, the admin user is redirected to http://localhost/admin/login which will usually be a 404 (not http://my.site.com/admin/login

**Comment by RyanThompson** [comment]
Fixed: https://github.com/pyrocms/pyrocms-theme/commit/5af578bea9c05a5d993fa15eb9a7c9a99198af03
