### ISSUE TITLE
500 Error on Page Reorder

### ISSUE THREAD

**Issue by j-hubb** [pyrocms/pyrocms#3605]
Getting the following error on page reorder

http://share.jhubb.io/hgLyR6b

**Comment by RyanThompson** [comment]
Can you consistently reproduce this? I assume this doesn't always happen - I've not seen it.

**Comment by RyanThompson** [comment]
That should be a page interface - see if you can dump some shit there by checking instance of that page when not page interface: https://github.com/anomalylabs/pages-module/blob/master/src/Page/Command/UpdatePaths.php#L45

**Comment by j-hubb** [comment]
I just tried this on a completely fresh install.

1. On a fresh install, create a new page as a child of the seeded home page.
2. Try to reorder the page.

Video here http://share.jhubb.io/3upt5qn

**Comment by RyanThompson** [comment]
Ok I will try that then. Thanks!

**Comment by j-hubb** [comment]
This "seems" to be resolved with the latest versions.

**Comment by RyanThompson** [comment]
Phew

**Comment by RyanThompson** [comment]
Keep and eye out and submit if you can reproduce.

**Comment by j-hubb** [comment]
Will do
