### ISSUE TITLE
Asset class debug flag should be tied to a different option.

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#3606]
Something like ASSET_DEBUG=(true / false / admin / public) and that will trigger debug assets to force re-compile.

Otherwise you are forced to recompile backend / fronted / everything. Need more granular control during development in order to keep load times from spiking with large asset recompilations.

**Comment by edmeehan** [comment]
+1 for feature

**Comment by RyanThompson** [comment]
Done
