### ISSUE TITLE
[Users Module] Any, Public tags feature request

### ISSUE THREAD

**Issue by edmeehan** [pyrocms/pyrocms#3611]
In Pyro 2 the access input had a default "Any" option that was a default.

Pyro 3 doesn't have a default, so empty value is equal to "Any". It would be good to add back "Any" and also maybe an additional "Public".

Any = equals all users, public and logged in (group)
Public = equals all users not logged in (no group)

Could be used to toggle links (ex. login vs logout) and used on any module that has user groups access control.

**Comment by RyanThompson** [comment]
I've added a guest role to the seeder for users and a couple logic points in the two add ons - navigation and pages. It will be up to developers to utilize the guest as / if they desire. Core add ons will have their behavior to lead the way there too.
