### ISSUE TITLE
[Pages Module] bug - slug route not working for homepage

### ISSUE THREAD

**Issue by edmeehan** [pyrocms/pyrocms#3612]
If you goto http://pyrohost/ you get the defined homepage as expected. The default homepage is the /welcome routed slug. If you try to use the slug route to hit this page you get a 500 error. If you then disable the welcome page as the home page, the /welcome route works as expected.

**Home page set: /welcome**

- http://host/ response:200

- http://host/welcome response:500

**Home page not set**

- http://host/ response:500

- http://host/welcome response:200

**Comment by bloveless** [comment]
I think this is working as expected. Otherwise one page will have two routes, and google may flag this a duplicate content and doc you SEO points. Especially the homepage. Thoughts?

**Comment by bloveless** [comment]
Although it should be a 404 and not a 500 error.

**Comment by edmeehan** [comment]
Or a temp redirect, but yes a 500 server error should not be the response from a slug in the system

**Comment by RyanThompson** [comment]
Ya if a page is marked at home it's slug is ignored.

**Comment by RyanThompson** [comment]
Whets the detail of the 500?

**Comment by edmeehan** [comment]
**nginx error log:**
2016/02/26 00:12:36 [error] 845#845: *142 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Twig_Error_Loader: Template "anomaly.theme.starter::layouts/error" is not defined () in "theme::errors/500" at line 1. in /home/vagrant/pyro-sandbox/pyrocms/vendor/twig/twig/lib/Twig/Loader/Chain.php:115
Stack trace:
#0 /home/vagrant/pyro-sandbox/pyrocms/vendor/twig/twig/lib/Twig/Environment.php(266): Twig_Loader_Chain->getCacheKey('anomaly.theme.s...')
#1 /home/vagrant/pyro-sandbox/pyrocms/vendor/twig/twig/lib/Twig/Environment.php(324): Twig_Environment->getTemplateClass('anomaly.theme.s...', NULL)
#2 /home/vagrant/pyro-sandbox/pyrocms/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig_Environment->loadTemplate('anomaly.theme.s...', NULL)
#3 /home/vagrant/pyro-sandbox/pyrocms/vendor/twig/twig/lib/Twig/Template.php(256): TwigBridge\Bridge->loadTemplate('anomaly.theme.s...', NULL)
#4 /home/vagrant/pyro-sandbox/pyrocms/storage/framework/views/twig/8/1/817a1a62172762b8b5221333107d907b5a0d244ce06bc6992cf6d3ddad780435.php(11): Twig_Template->loadTemplate('anomaly.theme.s....
PHP message: PHP Fatal error:  Uncaught Twig_Error_Loader: Template "anomaly.theme.starter::layouts/error" is not defined () in "theme::errors/500" at line 1. in /home/vagrant/pyro-sandbox/pyrocms/vendor/twig/twig/lib/Twig/Loader/Chain.php:115
Stack trace:
#0 /home/vagrant/pyro-sandbox/pyrocms/vendor/twig/twig/lib/Twig/Environment.php(266): Twig_Loader_Chain->getCacheKey('anomaly.theme.s...')
#1 /home/vagrant/pyro-sandbox/pyrocms/vendor/twig/twig/lib/Twig/Environment.php(324): Twig_Environment->getTemplateClass('anomaly.theme.s...', NULL)
#2 /home/vagrant/pyro-sandbox/pyrocms/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig_Environment->loadTemplate('anomaly.theme.s...', NULL)
#3 /home/vagrant/pyro-sandbox/pyrocms/vendor/twig/twig/lib/Twig/Template.php(256): TwigBridge\Bridge->loadTemplate('anomaly.theme.s...', NULL)
#4 /home/vagrant/pyro-sandbox/pyrocms/storage/framework/views/twig/8/1/817a1a62172762b8b5221333107d907b5a0d244ce06bc6992cf6d3d

**Comment by RyanThompson** [comment]
https://github.com/pyrocms/starter-theme/commit/24c29f3ca10fcb636fe4e82b8330bca78762fa4f
