### ISSUE TITLE
New content default locale is always english, .env and preferenses ignored

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3613]
Hello!

New content should be created as the default locale suggested in .env or the public language in the preferences. At the moment, it is always english

http://i.imgur.com/5BMROQM.png

in .env i have: LOCALE=et

resources/core/config/streams/locales.php : 

```
<?php

return [
    'enabled' => ['et', 'ru', 'en'],
];
```

And when i start creating a new page, English is the default:

http://i.imgur.com/zHxhKLJ.png

Note: The default locale should not be coupled to administration section locale.

**Comment by RyanThompson** [comment]
Try changing your fallback locale - I assume that will fix the default part - but your CP will not be translated at all..

**Comment by RyanThompson** [comment]
Need another config for locale sounds like.

**Comment by keevitaja** [comment]
I do not think, changing the fallback helps. Perhaps English is hardcoded?

And changing the CP locale, is not an option anyways.

**Comment by RyanThompson** [comment]
Not necessarily changing the fallback - but need a default site local - we have local (active) and fallback (default APP) but no site default.

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/5102e8d101f5d2894e86263c530e9b6f70c2ee50
