### ISSUE TITLE
Default locale shifts from user-defined to english

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3618]
I know, it sounds fishy at best... But : 

I have 3 locales - et, ru, en where et is the default. All is working, untill i get auto logged out from the cp. Then suddenly en becomes default. The moment i log into CP, et is default again.

It has happened thrice. 

Does it make any sense?

Btw i think the "remember me" option is not working.

**Comment by keevitaja** [comment]
Mhhh... Setting the locale from preferences management utility sets it only for the current user?

Settings does not have a locale option.

**Comment by keevitaja** [comment]
Another update!

It seems, that .env ships with incorrect locale configuration. Instead of LOCALE=et  there should be 

APP_LOCALE=et

Not sure, if anything uses LOCALE. Anyways if APP_LOCALE is not defined, fallback will be used. And yes, preferences are for the logged in user!

**Comment by RyanThompson** [comment]
I have removed the preferences hook for now - needs further discussion.
