### ISSUE TITLE
New navigation menu "creator" disregards "deleted_at" stamp

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3619]
When you delete a navigation menu, the database entry is stamped as deleted_at. 

Never the less this deleted slug cannot be reused. Example (footer and this_is_a_test cannot be used as navigation menu slug):

![control panel create 2016-02-28 13-06-39](https://cloud.githubusercontent.com/assets/158787/13378851/90208cb8-de1c-11e5-91c0-07957d06ad9f.png)
![screenshot_2016-02-28_13-05-53](https://cloud.githubusercontent.com/assets/158787/13378852/9036c834-de1c-11e5-9e18-301eb1b3330b.png)

When i "harddeleted" the row, problem went away!

**Comment by RyanThompson** [comment]
This is intended behavior. To adhere to DB schema requirements we need to make sure it's truly unique.. @bloveless what do you think about this? I would hate to end up needing to check this kinda thing on restore too - could be a mess.

**Comment by RyanThompson** [comment]
I think the best thing to do here is educate the user rather than complicate the innards of the system.

https://github.com/anomalylabs/streams-platform/commit/b56f645c2aed8814d88a53dd5781afd41bd0abf5
