### ISSUE TITLE
Redirection not working for the none-default locales?

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3620]
`some/path` is redirected to `some/path/sub/section`

`site/some/path` is working
`site/ru/some/path` is not working

**Comment by RyanThompson** [comment]
A redirect should only really occur for a default language - otherwise you will need to include the locale yourself in the from / to. As such, the default locale will not have a segment ID so this is n/a.

See progress on other issues regarding locale for where I am going with this.

**Comment by keevitaja** [comment]
This cannot be right! Remember that the framework cannot see the locale in the URI.

`http://site.com/products` gets redirected to `http://site.com/products/notebooks` as the `products` page contains no information. But now if  `http://site.com/ru/products` is not redirected, empty (without any useful information) page will be displayed to the user.

This cannot be right, as it is impossible to redirect localized URLs. Or am i missing the piont?

**Comment by RyanThompson** [comment]
Can you give me a real world example? I think in your case - ru/products will not likely be landed on? If it's part of your site build (not fixing old links) would you not handle that in your routing?

I think I know what you're referring to now but wanna make sure.

From: products
To: products/notebooks

Should work for both:

http://site.com/products -> http://site.com/products/notebooks
http://site.com/ru/products -> http://site.com/ru/products/notebooks

Is that correct?

**Comment by RyanThompson** [comment]
Also - this is for a new build or rebuilding an existing site?

**Comment by keevitaja** [comment]
http://site.com/products -> http://site.com/products/notebooks
http://site.com/ru/products -> http://site.com/ru/products/notebooks

Yes, this is correct. If default is redirected, then none-default locales should be redirected as well as in your example above. 

I do not see a case, where "mirroring" the none-default locales redirection is not needed. 

I do not understand this "new build" question ...

**Comment by RyanThompson** [comment]
Ok I can make this happen.

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/redirects-module/commit/b59f0f061b0a3f3a389abca89411b12a558f757e

**Comment by keevitaja** [comment]
@RyanThompson please reopen this. Now the redirection is not working at all.

**Comment by RyanThompson** [comment]
Composer update for redirects module and apply this to your base: https://github.com/pyrocms/pyrocms/commit/5ef8fe79bc65d3d0a882df3d583115e5144a7665

Looks good from here let me know what you find.

**Comment by RyanThompson** [comment]
Not needing the deferred change - I was wrong on that

**Comment by keevitaja** [comment]
old redirects working
new redirects working
localized redirect working

**Comment by RyanThompson** [comment]
"old redirects working" = what? Ill check em

**Comment by keevitaja** [comment]
oh sorry, it = that all is working :)

I had a situation, where after update for previously created items redirection was working for default locales. Now everything is working!

Close!

**Comment by RyanThompson** [comment]
Woot!
