### ISSUE TITLE
Files Field type controls pointing to wrong URL in pages module

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3623]
Hello!

both edit and remove point to `site/admin/pages...` , i think they should point to files module.

![screenshot_2016-02-29_09-58-48](https://cloud.githubusercontent.com/assets/158787/13388797/c90ff7d4-decb-11e5-9bfc-c55cbbec71f6.png)

and how can i access this field from the layout?

**Comment by RyanThompson** [comment]
{{ page.image }} returns the file interface / presenter

**Comment by RyanThompson** [comment]
[note] edit button on added value does not point correctly.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/files-field_type/commit/42709ac070b0bc34ed43de93240cb6aca22966ee
