### ISSUE TITLE
Parent slug not shown on new child page

### ISSUE THREAD

**Issue by j-hubb** [pyrocms/pyrocms#3624]
When creating a child page, the slug of the parent is not displayed in the slug field, suggesting that the slug of the child page is in the root.

http://share.jhubb.io/ySoxs2U

**Comment by keevitaja** [comment]
I confirm this and i am 99,9% certain, that it is a "new" bug. Wasn't there like a day or a two ago.

**Comment by j-hubb** [comment]
This is fixed, except when the parent page is the homepage.

**Comment by RyanThompson** [comment]
This is intended - the home page is / so the child will be /<slug input>

**Comment by j-hubb** [comment]
This isn't how the actual slugs behave. I have homepage with slug "welcome" at / and it's child is /welcome/another-page

**Comment by RyanThompson** [comment]
Changed: https://github.com/anomalylabs/pages-module/commit/65ff5430f87bb249edabad2be08a9e37f211aafb

It will preserve non-slugs now but not sure this is the proper way to do things?

@j-hubb do you think it SHOULD have the home page slug in the path of home page children? @bloveless  what's your opinion?

**Comment by bloveless** [comment]
Honestly I've never put a page underneath the homepage, but it doesn't make any sense to me to use the / namespace for the child page. It should inherit the slug of the homepage even though the homepage doesn't use it's own slug. If you want something to be /my-slug-here then you can just make that page as a sibling to the homepage rather than a child.

**Comment by RyanThompson** [comment]
Agreed - this will let you achieve either technically speaking: https://github.com/anomalylabs/pages-module/commit/110424bddcab24686f46fa6252d66c7b028ff6d7

**Comment by j-hubb** [comment]
I agree. I never have a child of the homepage, but the slug should still be
maintained.
