### ISSUE TITLE
Guest Role

### ISSUE THREAD

**Issue by j-hubb** [pyrocms/pyrocms#3625]
Should there be a guest role (not logged in)?

At the moment, the "login" page can be viewed by anyone, including logged in users.

**Comment by bloveless** [comment]
I like this idea! It would make it super easy to toggle things, say a "logged in as" and "login" button.

@RyanThompson what do you think about this? Any concerns?

**Comment by j-hubb** [comment]
OK, thanks for the explanation. I was just confused by the login page that's seeded.

**Comment by RyanThompson** [comment]
It's a shitty example is all ;-) 

Will improve seed data soon.

**Comment by j-hubb** [comment]
=)
