### ISSUE TITLE
Installer just redirects back to start on finish

### ISSUE THREAD

**Issue by carss06** [pyrocms/pyrocms#3626]
I am trying to install beta3, the installer runs fine, but is not writing to my database and is not setting the .env file to installed = true. No errors are thrown though, either by the installer or in my php logs. Setting debug to true in the .env file is causing the installer not to load. Once the installer finishes, it just reloads the installer setup page again to enter the .env details.

I am using a MAMP setup with the database name pyrocms on localhost. php version 5.6.

I was wondering if anyone else has had a similar issue?

Is there somewhere else I should be checking to find errors?

How do I run the CLI installer to see if it shows any errors the GUI doesn't?

**Comment by keevitaja** [comment]
use php artisan install , but i just installed B3 from gui and had zero errors/problems.

**Comment by carss06** [comment]
Thanks, turns out when trying the CLI installer that artisan wasn't working at all. I therefore ran 'composer install' which was throwing the following error:

[PDOException] SQLSTATE[HY000] [2002] Connection refused  

I had to click the 'allow network access to MySQL' in my MAMP settings, then everything worked just fine!

**Comment by keevitaja** [comment]
yeah, MAMP can be evil

**Comment by RyanThompson** [comment]
So this can be closed @carss06 ?

**Comment by carss06** [comment]
Yes please
