### ISSUE TITLE
Page type field assignment translatable option cannot be changed. 

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3629]
When you create assignment with translatable option set to no and then try to set it yes, it will break the page type. You can change to option from no to yes, but page cannot be saved anymore. It starts to complain, that there is no such field.

**Comment by RyanThompson** [comment]
Ill push a fix for this later tonight.

**Comment by schmidex** [comment]
I think I run in the same error.
Or was this fixed?

**Comment by RyanThompson** [comment]
Fixed: git@github.com:anomalylabs/documentation-module.git

Warning - this is a destructive process as it sits. It will need to be thought about and improved going forward.
