### ISSUE TITLE
Installer Not Working with subbed MAMP hosts

### ISSUE THREAD

**Issue by carss06** [pyrocms/pyrocms#3630]
I have configured pyros .env to connect to my MAMP mySQL database. When using the CLI installer, the installation process completes, and all of the tables are created in the pyrocms database, however the tables aren't populated, there is no admin user entry, no default pages etc. the .env file is changed to installed=true, but I cannot login to the admin (as there is no user) and the home page shows a 500 error page.

If I use the same .env file and use the browser installer it does not install, just goes back to the start of the installation process. It keeps the .env file as installed=false

mySQL and php error logs don't show anything.

Am I missing something? It seems strange 'php artisan install' can connect to the database to create the correct tables but cannot fill them in.

Thanks

**Comment by carss06** [comment]
im letting the installer create it, here is what it creates: 

APP_ENV=local
INSTALLED=true
APP_DEBUG=false
APP_KEY=usubRcaFxDfSYsumwqw1M0p0cd4SFs7A
ADMIN_THEME=pyrocms.theme.pyrocms
STANDARD_THEME=pyrocms.theme.starter
DB_DRIVER=mysql
DB_HOST=localhost
DB_DATABASE=pyrocms
DB_USERNAME=root
DB_PASSWORD=root
APPLICATION_NAME=Default
APPLICATION_REFERENCE=default
APPLICATION_DOMAIN=en.pyrocms:8888
ADMIN_USERNAME=admin
ADMIN_EMAIL=XXXXXXXX
ADMIN_PASSWORD=XXXXXXXX
LOCALE=en
TIMEZONE=UTC

**Comment by RyanThompson** [comment]
So fresh install - browser should work yes? I will double check the artisan installer it might not have been updated to hook the seeders properly. Im on it! But double check a fresh install through the browser if you would please ^_^

**Comment by carss06** [comment]
Just retried a fresh install in the browser, through the browser it doesn't even manage to create the tables in the database. It runs through the installer without errors then goes back to the first installer page. The .env file still has installed=false.

If I don't touch the .env file the browser installer creates and use it with the CLI installer instead, it creates the database tables and sets the .env file to installed=true. 

The following tables are populated with entries:

default_addons_extensions
default_addons_modules
default_migrations
default_streams_assignments
default_streams_assignments_translations
default_streams_fields
default_streams_fields_translations
default_streams_streams
default_streams_streams_translations

But everything else is empty.

Im guessing the database connection is dropped for some reason after installing the streams or something?

**Comment by RyanThompson** [comment]
Can you watch your network activity during install and keep it open so you can visit each ajax request manually as needed - and try hitting some of those install / seed URLs manually. Maybe enable debugging by that point. Maybe it will give us a clue.

**Comment by RyanThompson** [comment]
I suppose I should mention I am using MAMP lol I dev on it usually and Im not getting this. Ill try another fresh install for good measure though

**Comment by RyanThompson** [comment]
Ya @carss06 my install worked fine.. Can you try using a non-subbed domain? example.local::8888 for example.

**Comment by tom-commotion** [comment]
Thanks!

Confirmed working with just pyrocms:8888 as the domain, without a the sub (en.) part on the MAMP host.

Not sure if should close this or leave open as something you want to work on?

**Comment by carss06** [comment]
Thanks!

Confirmed working with just pyrocms:8888 as the domain, without a the sub (en.) part on the MAMP host.

Not sure if should close this or leave open as something you want to work on?

**Comment by RyanThompson** [comment]
I think it has to do with the en sub specifically cause it's a locale hint - Ill do some testing. Thank you!

**Comment by RyanThompson** [comment]
Fixed (kinda): https://github.com/anomalylabs/installer-module/commit/750e42d08cec8366da850bb09b40b6883ba7340c

It's a bad idea to have your primary site domain to include a locale hint so I validate against it!
