### ISSUE TITLE
QueryException when trying to create new field with a "name" slug

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3634]
Creating a field with "name" slog throws 

`QueryException in Connection.php line 651: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'pages-name' for key 'unique_streams' (SQL: insert into `keevitusseadmed_streams_fields` (`config`, `namespace`, `type`, `slug`) values (a:5:{s:4:"type";s:4:"text";s:3:"min";N;s:3:"max";N;s:9:"suggested";N;s:13:"default_value";N;}, pages, anomaly.field_type.text, name))`

Perhaps it could display that this slug is reserved or something?

**Comment by keevitaja** [comment]
I think "type" has the same issue!

**Comment by RyanThompson** [comment]
Ah yep - they’re taken by the base installation. Needs a good error message and to not shit it’s pants, agreed!

**Comment by keevitaja** [comment]
I do not do another issue, as it is similar:

Field type slug should not be "en" . You can create field and assign it, but it will not save any data!

**Comment by RyanThompson** [comment]
Fixed duplicates: https://github.com/anomalylabs/streams-platform/commit/45c4aae80bcc4526aff15e807763d5561aff0c14

Fixed protected names: https://github.com/anomalylabs/streams-platform/commit/5fde0b3589fccfdcf824dc7958e5b4ccdab5ae1f
