### ISSUE TITLE
Files field type cannot be multilingual

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3635]
Multilingual files field type should allow user to upload localized files for each locale? 

To have localized files as an option is important for multilingual workflow! Like usually product sheets, sometimes certificates, are localized.

But anyways, it allows you to create one, but not select any files. Also it breaks these cool yes/no slider-checkboxes in a page insert form by swapping them with the default html ones.

**Comment by keevitaja** [comment]
Just a small note, does not have anything directly to do with the issue:

When i discovered this bug, i did not realize i really do not need it. 

Imagine you have some product pages where customers can download user manuals. So my first though was swell, now i can have english manual for the english locale and russian manual for the russian locale. But what if the customers works in multilingual environment and he needs to download manuals both in english and russian languages?

So it is best to display all manuals and add the language hint:

For english locale we display:

 - Space manual (en)
 - Space manual (ru)

And for the russian locale we display:

 - инструкция по эксплуатации (en)
 - инструкция по эксплуатации (ru)

**Comment by RyanThompson** [comment]
I think I am going to close this and add an option to disable this type of feature for now where a pivot is involved.. Only because it's a mess and can be handled better with something like a Grid / Matrix FT

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/31750b7b7288dfa453cd192b00b1e885d16be10e
