### ISSUE TITLE
RoleRepositoryInterface is not instantiable, after fresh install!

### ISSUE THREAD

**Issue by websemantics** [pyrocms/pyrocms#3638]
![c1f614f9-bda4-48b4-8d1e-8726689671b1](https://cloud.githubusercontent.com/assets/2190455/13551640/dc51e93c-e30e-11e5-85cc-6ffb493994fc.png)

**Comment by nealstammers** [comment]
Hiya, I'm getting the same issue

**Comment by websemantics** [comment]
Possible cause,  https://github.com/anomalylabs/streams-platform/commit/cf4bf9e7374800ca02e49ff9be192f8b62a5d413
Reverting to old  constructer, without `RoleRepositoryInterface $roles` should solve the issue ..

**Comment by websemantics** [comment]
Related to new installs, .. when using `localhost` as value for Primary Domain this causes an error,
`The "Primary Domain" is invalid.`

I see a new Domain Validator, so I am guessing something there is causing it, 

https://github.com/anomalylabs/installer-module/commit/750e42d08cec8366da850bb09b40b6883ba7340c#diff-0b32e73a720cf8f7626b8561759c664bR1

**Comment by RyanThompson** [comment]
My bad - I suck! Fixed..

**Comment by websemantics** [comment]
It happens, .. the installer will always be tricky one .. 

Ok, ..  issue is still there unfortunatly, 

Source, Anomaly\UsersModule\Role\Command\SetGuestRole

**Comment by j-hubb** [comment]
I'm also getting this error on a fresh install

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/users-module/commit/fb8fd6774bca71252896197a5a57ad718d7475f9

**Comment by nealstammers** [comment]
Thanks for fixing it Ryan :)
