### ISSUE TITLE
The "Primary Domain" is invalid.

### ISSUE THREAD

**Issue by websemantics** [pyrocms/pyrocms#3640]
Going with the default installation settings, 

![d9a46bfd-da59-4989-b0bc-92305292cc56](https://cloud.githubusercontent.com/assets/2190455/13574306/87f5b488-e451-11e5-92b5-f81eb6342c22.png)

What is the value expected / validated against?

**Comment by RyanThompson** [comment]
it's expected to be a valid domain but I think I can change to just a path. I originally intended to catch sub domains that were a locale. en.example.local for example

**Comment by RyanThompson** [comment]
This should let you through: https://github.com/anomalylabs/installer-module/commit/637edd708038731ac6ede5b672b643380ceb918b

**Comment by websemantics** [comment]
Still developing on localhost here, .. time to grow up .. 
Thanks for the fix @RyanThompson

**Comment by RyanThompson** [comment]
Im just not as cool as you ;-)
