### ISSUE TITLE
500 Error After Page Move

### ISSUE THREAD

**Issue by j-hubb** [pyrocms/pyrocms#3643]
I'm getting an unstyled 500 error after the following:

1. Create a child page.
2. Reorder the child page, so it's no longer a child.
3. Visit the original link (when it was a child)

http://share.jhubb.io/ckBeWXH

It would be a great idea to create a 301 when the page's path changes to avoid this.

**Comment by RyanThompson** [comment]
Ya it should be regenerating the paths. I think this is related to another issue where the sort fails though.

**Comment by RyanThompson** [comment]
Can you wipe your log files, recreate this scenario and publish your log file?

**Comment by j-hubb** [comment]
Here is the error with debug true http://share.jhubb.io/k4Lu0AT

**Comment by j-hubb** [comment]
Logs are emtpy once debug is true

**Comment by RyanThompson** [comment]
So when you do the reordering portion. If you reload the page - it's order is saved?

**Comment by j-hubb** [comment]
Yeah it it, see this http://share.jhubb.io/BYGIjio

**Comment by RyanThompson** [comment]
Ah but it's 403ing your request.. weird.

**Comment by RyanThompson** [comment]
You’re logged in as admin?

**Comment by j-hubb** [comment]
Sorry, here http://share.jhubb.io/vWz3fsE

Yeah I'm logged in as admin

**Comment by RyanThompson** [comment]
Ahhh this is expected. 301s would be everywhere otherwise.

**Comment by RyanThompson** [comment]
If you click the view link from the pages module afterward - it'll resolve

**Comment by j-hubb** [comment]
Yeah, I get it, just if you're restructuring it's a lot more work. I'll deal with it.

**Comment by RyanThompson** [comment]
I don't think there's a clean way to 301 all the dead links otherwise Id be all for it - one thing you CAN do is keep it disabled so the link you're on is the static preview link.
