### ISSUE TITLE
php artisan install doesn't seed

### ISSUE THREAD

**Issue by websemantics** [pyrocms/pyrocms#3644]
Also generates this error occasionally 

```
  [ErrorException]
  Undefined index: HTTP_HOST
```

**Comment by RyanThompson** [comment]
Can you paste the full stack for this?

**Comment by websemantics** [comment]
Cause, https://github.com/anomalylabs/streams-platform/blob/1.0/develop/src/Http/Kernel.php#L58
So now I just set $_SERVER['HTTP_HOST'] to localhost to avoid the error, ..

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/d1af3058f94aae8d72905e02d079adc10b7dd534

And fixed: https://github.com/anomalylabs/streams-platform/commit/3ad1058af0821d6f8b443d305d66f75f979ac521

**Comment by websemantics** [comment]
That makes me happy .. thank you :+1:

**Comment by RyanThompson** [comment]
Not a prob brotha
