### ISSUE TITLE
[Posts Module] reorder assignment fields error

### ISSUE THREAD

**Issue by edmeehan** [pyrocms/pyrocms#3645]
Found a bug in the Posts module. Related to posts type assignments. When I try to reorder assignment fields I get this error.
1/2
PDOException in Connection.php line 390:
SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name '86f5493e37f5b22ba1ab89523d795846'
2/2
QueryException in Connection.php line 651:
SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name '86f5493e37f5b22ba1ab89523d795846' (SQL: alter table `refresh_posts_event_posts` add unique `86f5493e37f5b22ba1ab89523d795846`(`meetup_id`))

I did notice that if you only have two assigned fields you can move up without issue, but moving down throws this error too.

**Comment by RyanThompson** [comment]
Good catch! Fixed: https://github.com/anomalylabs/streams-platform/commit/b6c522c7341cf2c3a5cb7c2681b6f070f13603a7
