### ISSUE TITLE
[Posts Module] config feature

### ISSUE THREAD

**Issue by edmeehan** [pyrocms/pyrocms#3646]
Config settings for the posts module is not present in admin.

/admin/settings/modules/anomaly.module.posts

**Comment by RyanThompson** [comment]
This is intentional - the configuration (being setup by the developer) is a config value. Until I come up with a solid across-the-board method of handling developer duties / user settings and how they'll play together settings will be sparse.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/posts-module/blob/master/resources/config/paths.php#L54
