### ISSUE TITLE
Fields cannot be updated

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3650]
When i try to update a field, i get slug taken notice. This is what happens when i press update:

![screenshot_2016-03-10_12-27-52](https://cloud.githubusercontent.com/assets/158787/13666784/07b391ba-e6bc-11e5-8afc-c31b6b3cd214.png)

And when i deleted the field, i could recreate it with the same slug.

**Comment by RyanThompson** [comment]
Are you up to date? This has been fixed I thought. Let me know before I double check and dig in if you would please.

**Comment by keevitaja** [comment]
Yes, i am up to date according to `composer update`

I think i reported on a bug that displayed 404 or something instead of the slug taken message. But that happened on a create with a deleted matching slug.

Now it lets me to create new fields with matching slugs, but not update any field.

**Comment by RyanThompson** [comment]
Ok - Ill check it out.

**Comment by RyanThompson** [comment]
This should fix it! Please confirm: https://github.com/anomalylabs/streams-platform/commit/0122b90b3d1629e0797bd03d7a28f6d23cfbf50c

**Comment by keevitaja** [comment]
Fields can be updated!
