### ISSUE TITLE
Deleting a folder from the trash causes an error

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#3651]
Although the folder is deleted successfully from the db.

![screen shot 2016-03-11 at 3 31 29 pm](https://cloud.githubusercontent.com/assets/535135/13717386/609954a8-e79e-11e5-8c55-398a801ff200.png)

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/files-module/commit/29eb167a0cf91e268c48605a79d4d54460984746
