### ISSUE TITLE
Creating folder with seeder doesn't respect the allowed types

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#3652]
Creating folder with seeder has allowed_types array in it.

![screen shot 2016-03-11 at 3 33 48 pm](https://cloud.githubusercontent.com/assets/535135/13717442/c81a1bc6-e79e-11e5-9bc3-b6ecdc31c357.png)

I can see when editing the folder that the allowed types made it into the admin.

![screen shot 2016-03-11 at 3 33 41 pm](https://cloud.githubusercontent.com/assets/535135/13717446/cc5fca3c-e79e-11e5-9675-c8a0f8288851.png)

But when trying to upload the allowed file types aren't present.

![screen shot 2016-03-11 at 3 34 08 pm](https://cloud.githubusercontent.com/assets/535135/13717449/d152837c-e79e-11e5-9a16-73cc6a56d27a.png)

**Comment by bloveless** [comment]
I tried php artisan cache:clear, php artisan assets:clear, php artisan httpcache:clear, and php artisan streams:compile. Which didn't fix anything.

I created this folder with a seeder once before, but forgot to put the allowed_types in it. So I deleted the folder and uninstalled/reinstalled the module. Which is how the allowed_types made it into the edit folder area, but it isn't reflected in the actual field.

**Comment by bloveless** [comment]
Just noticed that the slug is missing. I assume there should be some validation when creating the folders.

**Comment by RyanThompson** [comment]
Im surprised it didn't complain? Did it not autoslug? Cause the column should be required by the DB

**Comment by bloveless** [comment]
Nope no autoslug no complaining. Just chugged on through lol! Won't make that mistake again.

**Comment by bloveless** [comment]
But... someone else might ;)

**Comment by RyanThompson** [comment]
This should fix it: https://github.com/anomalylabs/streams-platform/commit/eb305dc037316b92324a2531acb7579550224c15

Cause: https://github.com/anomalylabs/slug-field_type/blob/master/src/SlugFieldType.php#L58

Wanna give it a shot?
