### ISSUE TITLE
Feature: Missing way to hook into navigation to add items

### ISSUE THREAD

**Issue by markbratanov** [pyrocms/pyrocms#3653]
Migrating this feature request from streams-platform. 

Would be nice to have the option to hook into the admin navigation builder to add / modify / remove navigation elements.

**Comment by RyanThompson** [comment]
You can now use $cp->addNavigation(slug, link array) and docs will be coming on how to apply custuom sorting aside from the default alpha-num - which will be handled by preferences as well.

https://github.com/anomalylabs/streams-platform/commit/1f2440a2753c37d7f39e8c25c168530da0cee3ed

**Comment by RyanThompson** [comment]
This is for v3.2 btw ^_^
