### ISSUE TITLE
Changing translatable status on assignment (pages-module)

### ISSUE THREAD

**Issue by j-hubb** [pyrocms/pyrocms#3657]
When you change the translatable status of a field, then try to edit a page with that field assigned you get the following error.
![screencapture-pyrocms-dev-admin-pages-edit-4-1457951777361](https://cloud.githubusercontent.com/assets/6826637/13741918/d8a69788-e9d0-11e5-9b9c-29a4561058fa.png)

**Comment by keevitaja** [comment]
duplicate of https://github.com/pyrocms/pyrocms/issues/3629

**Comment by j-hubb** [comment]
Oops, searched but didn't see that.
