### ISSUE TITLE
Slugs are not translatable

### ISSUE THREAD

**Issue by crazko** [pyrocms/pyrocms#3658]
Page and post slugs cannot be translated as they take values from default language.

**Comment by RyanThompson** [comment]
That's correct - this is by design. The locale is entered into the URI like /<locale>/path

**Comment by crazko** [comment]
So there is no way how to make pages like:

example.com/contact
example.com/de/kontakt
example.com/it/contatto

pointing to the same page with different translation?

**Comment by RyanThompson** [comment]
Not right now no - You could open an issue suggesting the change. I would be curious as to what the community thinks about it.

**Comment by RyanThompson** [comment]
My problem with it is it starts exponentially complicating the routing for pages is all.

**Comment by fdeneux** [comment]
> I would be curious as to what the community thinks about it.

I'm sorry for comparing PyroCMS (which is awesome) to other platforms, but I believe it is a frequently requested feature for Laravel-based CMSs. I just think that PyroCMS users have been a bit shy about it. AsgardCMS has it built in and it was added to October's translate plugin after some [discussion](https://github.com/rainlab/translate-plugin/issues/25).

**Comment by Piterden** [comment]
AsgardCMS? Ha, ha, ha, ha! )))

PyroCMS and AsgardCMS is not comparable, I believe.

Maybe translatable slugs could be implemented inside an extension? @RyanThompson
