### ISSUE TITLE
public_path missing for file type

### ISSUE THREAD

**Issue by ilessy** [pyrocms/pyrocms#3659]
I use beta3 to test. I uploaded a file to my page. Then I wanted to output it on the website.
```
{{ page.file.public_path }}
```
But I checked the raw output and there is no 'public_path', I can only find 'path'.
What did I miss.

**Comment by ilessy** [comment]
I found out that those images are actually located at like:
```
http://localhost/app/pyrocms/files-module/local/images/myimage.jpg
```
So, i think public_path should give me that. But it doesn't work as said in the document.

**Comment by RyanThompson** [comment]
Sorry man - I am in the process of updating docs. For now, check out the presenter: https://github.com/anomalylabs/files-module/blob/master/src/File/FilePresenter.php#L191

```
{{ page.file.view_path }}
```
