### ISSUE TITLE
make:addon creates migration files in the "wrong" place

### ISSUE THREAD

**Issue by haeflimi** [pyrocms/pyrocms#3660]
A minor Issue:
When creating a module addon using `php artisan make:addon me.module.kickass-module` a migration file is automatically created in the /database/migrations folder.
Basically a convinient thing having the migrations file created in the first place, but i would expect it to be put in the /migrations folder of the addon i am creating.

**Comment by bloveless** [comment]
The migrations will be created in the correct module/migrations folder, but I think you've got your name wrong... it should be `php artisan make:addon me.module.kickass`

**Comment by bloveless** [comment]
I've had that same problem when I do `php artisan make:migration --addon=me.wrong-module.signature` if it can't find the correct module it will put it in the /database/migrations folder.

**Comment by haeflimi** [comment]
Sorry, poor example. I do have dashes in my module names... maybe that is wrong should be prevented by the make command in the first place then.
`php artisan make:module:kiackass-nr1 --shared`
ran without complaining and also, as expected, created the stub folder structure under 
`/addons/shaed/me/kickass-nr1-module`
however, the migrations where created at
`/database/migrations` outside of the generated folder structure. I can confirm that this is not the case when having no dash in the module name.

I'll change my module names to using underscores as word separators then and i guess all will be fine.

**Comment by RyanThompson** [comment]
Good find! This should help prevent this oopsie in the future: https://github.com/anomalylabs/streams-platform/commit/7635769baf46d2ffc4ebf99d49c789346de08d54
