### ISSUE TITLE
Been forced to Authorize when view a post.

### ISSUE THREAD

**Issue by ilessy** [pyrocms/pyrocms#3665]
I wrote some posts and trying to view them in the front end. After some minutes then a not found exception been thrown. I check the call stack and found this:
```
at Application->abort('404', '', array()) in helpers.php line 29
at abort('404') in PostAuthorizer.php line 56
at PostAuthorizer->authorize(object(PostModel)) in MakePostResponse.php line 52
```
So I realized that I have to login as a user to view those posts, but I can't find any place to disable this feature in the Admin Panel.  Just got a little confused.

**Comment by ilessy** [comment]
I checked that authorize function. It's logic is fine and my post is **enabled **for the post. 
So the problem could lead to that my post is actually considered **not enabled** by the system.

**Comment by ilessy** [comment]
how about this:
```
public function authorize(PostInterface $post)
    {
        if (!$post->isEnabled() && !$this->guard->user()) {
            abort(404);
        }

        if ($this->guard->user() && !$this->authorizer->authorize('anomaly.module.posts::view_drafts')) {
            abort(404);
        }
    }
```

**Comment by RyanThompson** [comment]
Composer update - this issue has been fixed prior (I noticed it myself a day ago or so): https://github.com/anomalylabs/posts-module/blob/master/src/Post/PostAuthorizer.php#L51
