### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by mrhhsg** [pyrocms/pyrocms#3666]
when I try to install pyrocms with the command below:
composer create-project pyrocms/pyrocms=3.0-beta3 --prefer-dist

I get errors:

hushengangdeMBP:pyrocms jerry$ composer update
> php artisan clear-compiled

Warning: require(/Users/jerry/Development/Source/laravel/pyrocms/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /Users/jerry/Development/Source/laravel/pyrocms/bootstrap/autoload.php on line 17

Fatal error: require(): Failed opening required '/Users/jerry/Development/Source/laravel/pyrocms/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /Users/jerry/Development/Source/laravel/pyrocms/bootstrap/autoload.php on line 17
Script php artisan clear-compiled handling the pre-update-cmd event returned with an error

                      
  [RuntimeException]  
  Error Output:       
                      

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

**Comment by RyanThompson** [comment]
Hi there! Are you on forge by chance?

**Comment by mrhhsg** [comment]
no, it seems always like this.
and my php version is:

PHP 7.0.4 (cli) (built: Mar 17 2016 16:35:36) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

**Comment by RyanThompson** [comment]
Can you composer install instead of update right away? There are post / pre scripts that run with update that assume you are installed already.


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by mrhhsg** [comment]
Compose install makes no difference, I think the "php artisan clear-compiled" command leads to error.

**Comment by RyanThompson** [comment]
So looking closer at this it's actually using the pre-update-command..

**Comment by ubilli** [comment]
i have the same issue too.
`> php artisan clear-compiled
PHP Warning:  require(/var/www/html/pyrocms/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/pyrocms/bootstrap/autoload.php on line 17
PHP Stack trace:
PHP   1. {main}() /var/www/html/pyrocms/artisan:0
PHP   2. require() /var/www/html/pyrocms/artisan:16
PHP Fatal error:  require(): Failed opening required '/var/www/html/pyrocms/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/pyrocms/bootstrap/autoload.php on line 17
PHP Stack trace:
PHP   1. {main}() /var/www/html/pyrocms/artisan:0
PHP   2. require() /var/www/html/pyrocms/artisan:16
Script php artisan clear-compiled handling the pre-update-cmd event returned with an error

                                                                          
  [RuntimeException]                                                      
  Error Output: PHP Warning:  require(/var/www/html/pyrocms/bootstrap/..  
  /vendor/autoload.php): failed to open stream: No such file or director  
  y in /var/www/html/pyrocms/bootstrap/autoload.php on line 17            
  PHP Stack trace:                                                        
  PHP   1. {main}() /var/www/html/pyrocms/artisan:0                       
  PHP   2. require() /var/www/html/pyrocms/artisan:16                     
  PHP Fatal error:  require(): Failed opening required '/var/www/html/py  
  rocms/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/ph  
  p:/usr/share/pear') in /var/www/html/pyrocms/bootstrap/autoload.php on  
   line 17                                                                
  PHP Stack trace:                                                        
  PHP   1. {main}() /var/www/html/pyrocms/artisan:0                       
  PHP   2. require() /var/www/html/pyrocms/artisan:16                     
                                                                          

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]
`

**Comment by schmidex** [comment]
A Change in composer is causing this. Other projects have the same issue. See here:
https://twitter.com/laravelphp/status/710154669704683520

Since the composer.lock file is missing, the first `composer install` is fact an` composer update`
Simply removing the `clear-compiled` command from the `composer.json` and running `composer install` (or `composer update`) in the install DIR manually will install pyrocms.
You can add it back after the inital install.

**Comment by RyanThompson** [comment]
Nice work, will remove now!

**Comment by RyanThompson** [comment]
https://github.com/pyrocms/pyrocms/commit/ad835d71d9c577b3be334cc12828f7f8f13b32d6
