### ISSUE TITLE
Incorrect lang or redirect behaviour when creating a field

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#3667]
When you create a field the button "Save and Edit" actually redirects to create a new field.

Should change to "Save and New", or change redirect.

If you change the redirect consider adding a Save and New as it is handy.

**Comment by edster** [comment]
As discussed in slack:

save / new for create and save / exit for edit

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/3274a82175ea6f3a17ed314a370e4933b9f86b02
