### ISSUE TITLE
Feature: have slugs translatable

### ISSUE THREAD

**Issue by crazko** [pyrocms/pyrocms#3669]
Would be really helpful to have ability to provide translations also for slugs, so the url structure could be like:

- example.com/contact
- example.com/de/kontakt
- example.com/it/contatto

Same for Pages and Posts module. This would make them not only more SEO-friendly, but help end users from different countries at first place.

**Comment by RyanThompson** [comment]
At that point wouldn’t you drop the language hint in the URI?

**Comment by crazko** [comment]
Sure, that's an option, why not. I think, it would make sense as well.

**Comment by RyanThompson** [comment]
Ima close this for now - I don't foresee this happening too soon :-/
