### ISSUE TITLE
Feature: Pages list expanded/collapsted state should be remembered

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3671]
Otherwise it will be a mess ...

**Comment by RyanThompson** [comment]
https://github.com/pyrocms/pyrocms-theme/commit/7d83cfca4d9fd2efe5d25d26f7a10552921c9286
https://github.com/anomalylabs/streams-platform/commit/4631d756d166d3a583c7c88f928a697e3c9c4e9d
