### ISSUE TITLE
Navigation link page targets should be tabbed and correctly ordered

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3674]
Otherwise it is a mess like on the image below. Impossible to know what is what

![screenshot_2016-03-25_13-36-16](https://cloud.githubusercontent.com/assets/158787/14043657/56ec4d4c-f28f-11e5-9257-1fc557a130fc.png)

**Comment by RyanThompson** [comment]
Changed this to use lookup mode until a good / clean method of hooking into this can be thought up.
