### ISSUE TITLE
[v3] Image selector appears below WYSIWYG when fullscreen enabled

### ISSUE THREAD

**Issue by AkibaTech** [pyrocms/pyrocms#3675]
An image tells more than words...
Note: I've manually reduced the WYSIWYG's opacity to reveal the problem.

<img width="1066" alt="capture d ecran 2016-03-25 a 17 13 25" src="https://cloud.githubusercontent.com/assets/1665333/14048233/403637e8-f2ad-11e5-8686-7ba6561ac64f.png">

Taken on OSX + Chrome 49

**Comment by RyanThompson** [comment]
Weird! Easy fix though ^_^

**Comment by RyanThompson** [comment]
https://github.com/pyrocms/pyrocms-theme/commit/5e622df97290ff937d6115c40a39ababc4607e09
