### ISSUE TITLE
Sitemap extension generates links only for the default locale!

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3679]
This is a serious bug in my opinion...

**Comment by RyanThompson** [comment]
Is this the accepted / standard way of signifying languages in a sitemap?

https://support.google.com/webmasters/answer/2620865?hl=en <https://support.google.com/webmasters/answer/2620865?hl=en>

**Comment by keevitaja** [comment]
I do not know. I actually figured there will be a <loc> for each locale, but ...

i uploaded this example xml to a server and tested this file with googles webmasters tools. It found 3 pages with no errors. So at least the syntax is correct ...

**Comment by keevitaja** [comment]
I also think, if you go with this setup, it should affect only sites which have multiple locale support.  Otherwise there could be a situation, where system locale is en, but the actual on is something different and google gets wrong indication.

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/pages-module/commit/bd3444ca737e891d5093905b94856375009f3f12
