### ISSUE TITLE
[wysiwyg-field_type]  bug when all plugins deselected

### ISSUE THREAD

**Issue by aidanwatt** [pyrocms/pyrocms#3682]
When creating a field with this field type if all the plugins for the WYSIWG are deselected it will cause an error as the plugin config is NULL rather than an array.

`in WysiwygFieldType.php line 82 at HandleExceptions->handleError('2', 'array_intersect(): Argument #1 is not an array', '/core/anomaly/wysiwyg-field_type/src/WysiwygFieldType.php', '82', array('config' => array('configuration' => 'default', 'line_breaks' => true, 'height' => '200', 'buttons' => array('bold', 'italic'), 'plugins' => null), 'configuration' => array('buttons' => array('bold', 'italic', 'deleted', 'lists', 'link', 'format', 'horizontalrule', 'underline'), 'plugins' => array('source', 'table', 'video', 'inlinestyle', 'filemanager', 'imagemanager', 'fullscreen', 'alignment')), 'buttons' => array('format', 'bold', 'italic', 'deleted', 'lists', 'link', 'horizontalrule', 'underline'), 'plugins' => array('alignment', 'inlinestyle', 'table', 'video', 'filemanager', 'imagemanager', 'source', 'fullscreen')))`

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/wysiwyg-field_type/commit/03e2d6db23fef883a8df8fee4b6521b282da2725
