### ISSUE TITLE
Favicon should not 500 even if it doesn't exist (Really 404 page 500's)

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#3683]
![screen shot 2016-03-29 at 3 30 51 pm](https://cloud.githubusercontent.com/assets/535135/14124545/54e63440-f5c3-11e5-821a-0e946bfcc46e.png)

**Comment by bloveless** [comment]
[2016-03-29 15:32:15] local.ERROR: Twig_Error_Loader: Template "anomaly.theme.starter::layouts/error" is not defined () in "theme::errors/404" at line 1. in /var/www/nu-meat.fritzandandre.com/vendor/twig/twig/lib/Twig/Loader/Chain.php:115
Stack trace:
#0 /var/www/nu-meat.fritzandandre.com/vendor/twig/twig/lib/Twig/Environment.php(266): Twig_Loader_Chain->getCacheKey('anomaly.theme.s...')
#1 /var/www/nu-meat.fritzandandre.com/vendor/twig/twig/lib/Twig/Environment.php(324): Twig_Environment->getTemplateClass('anomaly.theme.s...', NULL)
#2 /var/www/nu-meat.fritzandandre.com/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig_Environment->loadTemplate('anomaly.theme.s...', NULL)
#3 /var/www/nu-meat.fritzandandre.com/vendor/twig/twig/lib/Twig/Template.php(256): TwigBridge\Bridge->loadTemplate('anomaly.theme.s...', NULL)
#4 /var/www/nu-meat.fritzandandre.com/storage/framework/views/twig/c/f/cf4e731ae966a33b70ba5fb1adc6fb01069676bec5d393db3594391e8ef2182e.php(11): Twig_Template->loadTemplate('anomaly.theme.s...', 'theme::errors/4...', 1)
#5 /var/www/nu-meat.fritzandandre.com/vendor/twig/twig/lib/Twig/Environment.php(346): __TwigTemplate_cf4e731ae966a33b70ba5fb1adc6fb01069676bec5d393db3594391e8ef2182e->__construct(Object(TwigBridge\Bridge))
#6 /var/www/nu-meat.fritzandandre.com/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig_Environment->loadTemplate('theme::errors/4...', NULL)
#7 /var/www/nu-meat.fritzandandre.com/vendor/rcrowe/twigbridge/src/Engine/Compiler.php(99): TwigBridge\Bridge->loadTemplate('theme::errors/4...')
#8 /var/www/nu-meat.fritzandandre.com/vendor/rcrowe/twigbridge/src/Engine/Twig.php(90): TwigBridge\Engine\Compiler->load('theme::errors/4...')
#9 /var/www/nu-meat.fritzandandre.com/bootstrap/cache/compiled.php(14572): TwigBridge\Engine\Twig->get('theme::errors/4...', Array)
#10 /var/www/nu-meat.fritzandandre.com/bootstrap/cache/compiled.php(14560): Illuminate\View\View->getContents()
#11 /var/www/nu-meat.fritzandandre.com/bootstrap/cache/compiled.php(14544): Illuminate\View\View->renderContents()
#12 /var/www/nu-meat.fritzandandre.com/bootstrap/cache/compiled.php(15701): Illuminate\View\View->render()
#13 /var/www/nu-meat.fritzandandre.com/bootstrap/cache/compiled.php(15216): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#14 /var/www/nu-meat.fritzandandre.com/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 404, Array)
#15 /var/www/nu-meat.fritzandandre.com/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(71): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 404, Array)
#16 /var/www/nu-meat.fritzandandre.com/vendor/anomaly/streams-platform/src/Exception/ExceptionHandler.php(59): Illuminate\Routing\ResponseFactory->view('streams::errors...', Array, 404)
#17 /var/www/nu-meat.fritzandandre.com/vendor/anomaly/streams-platform/src/Exception/ExceptionHandler.php(40): Anomaly\Streams\Platform\Exception\ExceptionHandler->renderHttpException(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#18 /var/www/nu-meat.fritzandandre.com/bootstrap/cache/compiled.php(2324): Anomaly\Streams\Platform\Exception\ExceptionHandler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#19 /var/www/nu-meat.fritzandandre.com/bootstrap/cache/compiled.php(2240): Illuminate\Foundation\Http\Kernel->renderException(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#20 /var/www/nu-meat.fritzandandre.com/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#21 {main}

Next InvalidArgumentException: Error loading theme::errors/404: Template "anomaly.theme.starter::layouts/error" is not defined () in "theme::errors/404" at line 1. in /var/www/nu-meat.fritzandandre.com/vendor/rcrowe/twigbridge/src/Engine/Compiler.php:101
Stack trace:
#0 /var/www/nu-meat.fritzandandre.com/vendor/rcrowe/twigbridge/src/Engine/Twig.php(90): TwigBridge\Engine\Compiler->load('theme::errors/4...')
#1 /var/www/nu-meat.fritzandandre.com/bootstrap/cache/compiled.php(14572): TwigBridge\Engine\Twig->get('theme::errors/4...', Array)
#2 /var/www/nu-meat.fritzandandre.com/bootstrap/cache/compiled.php(14560): Illuminate\View\View->getContents()
#3 /var/www/nu-meat.fritzandandre.com/bootstrap/cache/compiled.php(14544): Illuminate\View\View->renderContents()
#4 /var/www/nu-meat.fritzandandre.com/bootstrap/cache/compiled.php(15701): Illuminate\View\View->render()
#5 /var/www/nu-meat.fritzandandre.com/bootstrap/cache/compiled.php(15216): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#6 /var/www/nu-meat.fritzandandre.com/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 404, Array)
#7 /var/www/nu-meat.fritzandandre.com/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(71): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 404, Array)
#8 /var/www/nu-meat.fritzandandre.com/vendor/anomaly/streams-platform/src/Exception/ExceptionHandler.php(59): Illuminate\Routing\ResponseFactory->view('streams::errors...', Array, 404)
#9 /var/www/nu-meat.fritzandandre.com/vendor/anomaly/streams-platform/src/Exception/ExceptionHandler.php(40): Anomaly\Streams\Platform\Exception\ExceptionHandler->renderHttpException(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#10 /var/www/nu-meat.fritzandandre.com/bootstrap/cache/compiled.php(2324): Anomaly\Streams\Platform\Exception\ExceptionHandler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#11 /var/www/nu-meat.fritzandandre.com/bootstrap/cache/compiled.php(2240): Illuminate\Foundation\Http\Kernel->renderException(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#12 /var/www/nu-meat.fritzandandre.com/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#13 {main}  
[2016-03-29 15:32:15] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught Twig_Error_Loader: Template "anomaly.theme.starter::layouts/error" is not defined () in "theme::errors/500" at line 1. in /var/www/nu-meat.fritzandandre.com/vendor/twig/twig/lib/Twig/Loader/Chain.php:115
Stack trace:
#0 /var/www/nu-meat.fritzandandre.com/vendor/twig/twig/lib/Twig/Environment.php(266): Twig_Loader_Chain->getCacheKey('anomaly.theme.s...')
#1 /var/www/nu-meat.fritzandandre.com/vendor/twig/twig/lib/Twig/Environment.php(324): Twig_Environment->getTemplateClass('anomaly.theme.s...', NULL)
#2 /var/www/nu-meat.fritzandandre.com/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig_Environment->loadTemplate('anomaly.theme.s...', NULL)
#3 /var/www/nu-meat.fritzandandre.com/vendor/twig/twig/lib/Twig/Template.php(256): TwigBridge\Bridge->loadTemplate('anomaly.theme.s...', NULL)
#4 /var/www/nu-meat.fritzandandre.com/storage/framework/views/twig/9/1/91c17802055398427024b52e2e2b418242140254e0efc2458675b7a05be7a410.php(11): Twig_Template->loadTemplate('anomaly.theme.s...', 'theme::errors/5...', 1)
#5 /v in /var/www/nu-meat.fritzandandre.com/vendor/rcrowe/twigbridge/src/Engine/Compiler.php:101
Stack trace:
#0 {main}

**Comment by bloveless** [comment]
This doesn't occur in development as it shows the laravel 404 page, but on production it seems like it doesn't work.

**Comment by RyanThompson** [comment]
Different issue - I think it's fixed in a previous commit just recently - or a pull - I can't recall. Ill reference it here when I find it - cause shipped themes throw 404 but your 404 is missing which _used_ to be an issue
