### ISSUE TITLE
Feature: custom image filenames in files plugin

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3685]
Currently `page.field.image.resize(x, y)` gives us a hash for a filename:

`http://site.app/app/<namespace>/assets/images/bfa97422938e208b51777d2f29216bfe.jpg`

I propose it would create a folder using the hash, and then take the user specified filename:

`http://site.app/app/<namespace>/assets/images/bfa97422938e208b51777d2f29216bfe/my_image.jpg`

Also the hash string could be shorter, as it has no cryptographic responsibilities. Perhaps CRC32?

And maybe you could overwrite the filename coming from the db with following:

`page.field.image.resize(x, y).filename('some_imagename.jpg')`

**Comment by huglester** [comment]
+1 for this. FIlenames with name like qwegashjdfgashdf.jpg is nonsense. In terms of SEO and other stuff. Often we need to download a file, and when it gets giberish filename... it quiet sux :(

**Comment by keevitaja** [comment]
@huglester ryan told me, that there is a feature `rename()` already what does this, but it is not working. He promised to close this issue as soon as he fixes it.

**Comment by RyanThompson** [comment]
rename('filename or path'): https://github.com/anomalylabs/streams-platform/commit/d54231e6470262fa4c0a7f3bec42e12be3656959
