### ISSUE TITLE
where to study Pyrocms 3 

### ISSUE THREAD

**Issue by ricardoriffs** [pyrocms/pyrocms#3687]
Hi. Sorry if it isn't a issue. But I don't know where to study the configuration, operation and administration of the new platform on Pyrocms V3. I couldn't open the documentation in the official site (https://pyrocms.com/docs/pyrocms/setup/installation). I wonder if I can buy a physical book in a library or if there is another web resource where I can learn (tutorial, manual, etc...). Thanks for your orientation and aid. I hope to use Pyrocms v3 on my clients proyects.

**Comment by RyanThompson** [comment]
Hi there!

The new website with updated docs manager will be up late tonight / tomorrow. It’s undergone a change that put me in a tough spot.

Until then - all repositories have a docs/ directory you can browse that holds the source for the docs. Also be sure to join our slack channel we;re always around to help out.

Cheers!
