### ISSUE TITLE
DO NOT upgrade to PHP 7.0.5

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3688]
Sorry for the caps...

PyroCMS cannot work with PHP 7.0.5 . See the error message here

[log.txt](https://github.com/pyrocms/pyrocms/files/200730/log.txt)

First i had this on my Arch machine. But as soon as i upgraded forge to PHP 7.0.5 , the same trouble started there. The error log is from forge.

Another weird thing is, that on Arch first the `site.app/admin` threw error, but `site.app` did not. Later got error everywhere. Same thing is happening in forge. 

This is my forge configuration : http://test.keevitaja.com/

this a fresh pyro beta3 installation on forge running PHP 7.0.5 http://pyro.keevitaja.com

**Comment by RyanThompson** [comment]
Interesting.. Ill check it out!

**Comment by keevitaja** [comment]
@RyanThompson 

Now i am 100% it is the PHP 7.0.5 version with PyroCMS. Just installed homestead which came with PHP 7.0.3 . PyroCMS installer was working. The moment i upgraded to PHP 7.0.5 , the same stupid Assetic error showed up.

Please try to fix this, i'll help if i can...

**Comment by keevitaja** [comment]
What if, these two are related:

https://bugs.php.net/bug.php?id=71948
https://github.com/anomalylabs/streams-platform/blob/1.0/develop/src/Asset/Asset.php#L478

**Comment by keevitaja** [comment]
It is solved!

```
        foreach ($filters as $k => &$filter) {
            if ($filter == 'min') {
                if ($hint == 'js') {
                    $filter = new JsMinFilter();
                } elseif ($hint == 'css') {
                    $filter = new CssMinFilter();
                }
            }
```

This is Asset.php from line 478. I commented out the switch statement and added this if!

**Comment by RyanThompson** [comment]
There are very few - I can think of 3 off hand. But, this can certainly be `switched` to a group of if statements.

**Comment by keevitaja** [comment]
Just a small note:

The `switch` in Asset.php was replaced by `if`

https://github.com/anomalylabs/streams-platform/commit/67a0c1a5354fec31f49abb056b315603d72279ba
