### ISSUE TITLE
Pages should be allowed to be viewed even if their parent is not

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#3694]
I like to have an "orphans" section on the site that contains one-off pages that don't have any hierarchy. Then pages like a map will be visible via /o/map although /o should never be accessed (I.E. page is not enabled)

**Comment by keevitaja** [comment]
I do not think that this is easily doable. I am like almost certain, it will cause some issues with the navigation items. Also when you try to iterate over the pages it will not work. You cannot get the children. 

@bloveless ,

I am not sure, if this is the case here, but this "orphan" setting could be easily addressed with the streams. Does your sites architecture need some content which do not act as a pages?

If yes, then create a module with a stream for this content. While ago Ryan walked me through the process and i saved the conversation to http://laravel.io/bin/PXam8

**Comment by bloveless** [comment]
They are pages. And they act as pages. But I don't want them to show up in the navigation. The orphan container is simply for organization purposes.

**Comment by bloveless** [comment]
They definitely don't warrant a new stream since they would be pages lol! Anyway I just didn't want the parent accessible, but I'll just use a redirect plugin or something to redirect /o to the home page.

**Comment by keevitaja** [comment]
There is a special checkbox in the pages setting to hide it from the navigation structure

http://i.imgur.com/qJinoxl.png

**Comment by bloveless** [comment]
Redirection module will work fine. Thank you

**Comment by bloveless** [comment]
Thanks again for your suggestion! That worked perfectly and somehow I had forgotten about the redirect module!
