### ISSUE TITLE
[pages-module] [files-fieldtype] Can't change slug of an assigned field

### ISSUE THREAD

**Issue by schmidex** [pyrocms/pyrocms#3698]
Steps to reproduce:
1. Create a files-field
2. assign it to a page type
3. edit the files-filed created previously (1) and try to change its name

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/files-field_type/commit/31169e92c488fe8325909eb3abaf5929b5e7333d

**Comment by RyanThompson** [comment]
Also did the same thing to multiple FT
