### ISSUE TITLE
[Pages Module] Can change name/slug of type

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#3700]
This causes issues when trying to use/assign to that type again. Probably don't allow renaming of types.

This is the URL that I get that error message on. I just rename the type before attempting to assign something to it.

http://fritzandandre.dev/admin/pages/types/assignments/1

![screen shot 2016-05-04 at 4 11 13 pm](https://cloud.githubusercontent.com/assets/535135/15030987/e0f69cc0-1212-11e6-9e1d-36fa07e24c05.png)

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/pages-module/commit/77f8dcc378d7ba045111c901a987e1cc73a7c731

**Comment by bloveless** [comment]
Kewl! I was thinking you were just going to disable the editing of the slug. But wow! Nicely done!

**Comment by RyanThompson** [comment]
Ya we have dah powah! Making the change to posts and files too


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581
