### ISSUE TITLE
[v2.2] - Unable to Save Pages with certain inline javascripts

### ISSUE THREAD

**Issue by garyweldy** [pyrocms/pyrocms#3703]
Hi, 

We have a few pages that have several different scripts on them. We don't call on a file, we usually just write the script into the page editor source code.

For the last year, things have been working splendidly, but last week, suddenly, we were unable to successfully save certain pages with certain script code in it. Scripts that have been working for months and would allow us to save previously.

One of the scripts, I was able to pinpoint and found an alternative. It saves fine with the new script, but then I discovered another page with a different script that was experiencing the same issue. 

This morning, I found a third using different scripts. What I did for that page, is take all the scripts (3 of them) and put them into a single .js file and called the js file and it allowed me to save it and the page works fine.

Anyone have any idea what might cause this?

**Comment by bloveless** [comment]
@garyweldy are you referring to Pyro 2.2 or Pyro 3? Also are you using the WYSIWYG editor? Or a plain text editor.

**Comment by bloveless** [comment]
Also did you run any updates on the site? There is no autoupdate mechanism on pyro, so it would be very strange that it stopped working on it's own.

**Comment by garyweldy** [comment]
Hey, thanks for the reply. We are running 2.2 and using the WYSIWYG editor.
We did not run any updates on the website. 

The behavior is very strange and erratic. I created a new page, dropped in all the HTML and CSS and saved and it saved without any issue. I tried added the script at the top of it and it just spins. I tried it again with the same result, except the page was created - even though it timed out. If I manually drop my code into the editor, it saves with no problem. If I edit the existing page manually or just go back into it and click save (without pasting in my code over the existing code) it spins and times out. I compared the code and aside from some break tags adding the forward slash after them and some ampersands changing to &amp;, there aren't any changes to the code. It's baffling.

I work for a state agency. At this point I'm wondering if perhaps something happened behind the scenes internally, but I don't see why that would effect a WYSIWYG editor.

**Comment by bloveless** [comment]
Is it possible for you to live without a WYSIWYG editor. I'm pretty sure that this is an error with the WYSIWYG editor and some protection happening on the php side of things.

I would try changing the WYSIWYG editor to a text area and repeating the same procedure to see if it is indeed the WYSIWYG editor, or if there is an error in the codebase somewhere.

**Comment by bloveless** [comment]
I just created a new site, changed the Page Body to a text area and saved the following code without an issue.

![screen shot 2016-05-16 at 1 23 02 pm](https://cloud.githubusercontent.com/assets/535135/15301124/57fad91c-1b69-11e6-8546-bdf95c9159cd.png)

**Comment by ikoniqoz** [comment]
I would have expected that any Js might be included in the Script section and not in the Page Body area. Or better still, to include it in a separate js file  in the theme's js folder.

Am I missing something here ?

**Comment by bloveless** [comment]
@ikoniqoz You are right. It should go in the scripts section. I'm just trying to figure out where this bug is coming from.

**Comment by bloveless** [comment]
And if it is an XSS issue or what it could be.

**Comment by ikoniqoz** [comment]
Maybe its not a bug. Having Js code in the CKeditor instance is probably going to mangle the Js code anyway.  How about moving the Js out of where its not meant to be and do more testing ?

**Comment by garyweldy** [comment]
Hey guys. 

Here's some more odd behavior or maybe I'm just simply missing something. When I add javascript code the script section of the page, it does nothing. The script code saves, but when I view the page, the functionality does not exist. When I pop it back into the editor, it functions like normal. This is why we have been placing it within the content editor.

**Comment by bloveless** [comment]
Make sure you have {{ template:metadata }} in your theme. I'm pretty sure the scripts are included inside the metadata tag.

**Comment by bloveless** [comment]
This is how it is used in the minimal theme. views/partials/metadata.html

![screen shot 2016-05-17 at 9 39 47 am](https://cloud.githubusercontent.com/assets/535135/15328774/4ea04604-1c13-11e6-97dd-8bbf4850a9f1.png)

**Comment by ikoniqoz** [comment]
{{ template:metadata }} is used for meta data items under the page's Meta Data tab ( Page Details, Page Content, Meta Data, etc when editing a page). The other option is to put any Js behaviour needed  into a theme js file which is placed in the theme's js folder.

**Comment by bloveless** [comment]
I checked to make sure that {{ template:metadata }} does indeed put the scripts on the page. If you include that tag you'll be able to add the scripts from the pages module js tab.

**Comment by ikoniqoz** [comment]
WOW - Thats a neat feature. Thanks for the extra info.

**Comment by garyweldy** [comment]
Thanks for the continued followed up. I took a look at the files and we do have {{ template:metadata }} included, however, that doesn't seem to function the way it's intended.

What stikes me as odd is why it has worked up until this point. I've been maintaining this site for over a year and just recently did we start having this issue.

**Comment by garyweldy** [comment]
Also note, that while it does not fix it every time, sometimes, if I move the scripts to the bottom of the page, (under the code) it allows me to save it.

**Comment by RyanThompson** [comment]
Is this safe to close?

**Comment by bloveless** [comment]
It has been almost a month since the last comment. I'll close it and re-open it if anyone comments on it again.

**Comment by garyweldy** [comment]
Unfortunately, nothing suggested in this thread resolved my issue.
You're welcome to keep it closed. I've just resolved myself to not using the script section.
