### ISSUE TITLE
Valid form field fallback when label is false

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#3713]
In order to hide a field label we use label = false, but the validator also uses label to generate the validation messages. Validation should fall back to field name if the label isn't present.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/blob/master/src/Ui/Form/Command/SetErrorMessages.php#L61

Am I missing something?

**Comment by bloveless** [comment]
https://github.com/anomalylabs/streams-platform/pull/207

It is fixed here.

**Comment by bloveless** [comment]
How it currently works when the label is set to false

<img width="1433" alt="screen shot 2016-05-29 at 10 53 46 am" src="https://cloud.githubusercontent.com/assets/535135/15634858/b084357a-258b-11e6-8274-aaf822e943d2.png">

**Comment by bloveless** [comment]
Also that line of code you submitted looks like it only goes for unique_trash. I might be misreading that though.

**Comment by bloveless** [comment]
I don't know if this matters or not, but this is a custom form that is not created by a stream.

**Comment by bloveless** [comment]
field_type => [ config => [ disable_label => true ] ]
