### ISSUE TITLE
.env Configuration should restrict / play nice with settings / preferences.

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#3715]
Here's my thought:

1.) Setting definitions can have an `env = > THE_ENV_KEY` in the definition. 
2.) If the env key is there - when pulling (config is used there to determine mutation of value) use env value as defined in the key instead of the setting value.
3.) In the GUI - add a warning saying it's override by environmental file.
4.) In the GUI - disable the field as well.

**Comment by edster** [comment]
I think this should be done the other way,

1.) Setting definitions can have an env = > THE_ENV_KEY in the definition. 
2.) Use the env key, have the value in setting module set as "Default" (Default will be the value in .env.) 3.) The setting then overrides the .env if changed from default.
4.) Have a setting in .env that can block access to the settings, this will disable the fields.

**Comment by Mattnmoore** [comment]
+1

**Comment by Mattnmoore** [comment]
I think it should be .env for override otherwise you'll end up having to declare all the settings in the .env file for defaults right?

**Comment by edster** [comment]
That doesn't work for all things though, if a developer wants to set defaults, it is better for them to be hardcoded in a .env.

Also for what Ryan was saying, just because you have set a default for a client you don't necessarily want to lock them out from changing things.

**Comment by Mattnmoore** [comment]
I need to look at it again but I thought you could declare defaults in the settings definition.

**Comment by RyanThompson** [comment]
Right - env will be considered the DB value for all intents and purposes. Because once you save settings 1 time. There is no default value _typically_ and if there is it's utilized when accessing the setting like `$settings->get('streams::foo', $default);`

It needs to cascade nicely otherwise it'll be too involved. Check this and it's default otherwise this has value too and if flag then this that and now it overrides it where as it was originally vice-versa is what I hear lol

**Comment by RyanThompson** [comment]
@edster defaults should live in config. Not env - and config can use env but that's for convenience and environmental differences - not a legitimate value store. 

Settings, when used with config n env - should pry set that config too just in case so I might need another key for the config value to set. 

THEN and only then it might make sense.. leaves less purpose for the default argument but that's ok. we're talking design principles for addons basically. If there is a setting that does NOT tie into config / env then the default param is helpful at least ^_^

**Comment by edster** [comment]
True dat.

**Comment by RyanThompson** [comment]
I am thinking something like this. Where the source is the config key it's meant to manipulate. And env is the env key to look for. 

Cause the gist is - build your addon to use CONFIG store. And the settings should overload it.

THIS WAY you don't have a hard dependency on the settings module.

```
'debug'           => [
        'type'   => 'anomaly.field_type.boolean',
        'source' => 'app.debug',
        'env' => 'APP_DEBUG'
        'config' => [
            'default_value' => function (Repository $config) {
                return $config->get('app.debug');
            },
            'on_text'       => 'ON',
            'off_text'      => 'OFF'
        ]
    ],
```

**Comment by bloveless** [comment]
I was thinking that .env would be the end all essentially. If it exists in the .env file then that is the value that would be used no matter what. If that key didn't exist then it would fall back to the other values. That way the developer has the POWA and nobody can overwrite his/her master control.

My thinking is exactly how @RyanThompson mentioned it in the first comment.

**Comment by RyanThompson** [comment]
Done deal!


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by RyanThompson** [comment]
@Mattnmoore just something worth noting here.. Settings are powered natively by field types so as such `config.default_value`, is supported.

**Comment by RyanThompson** [comment]
Done - bind / env keys do this now.
