### ISSUE TITLE
Pyro not respecting image driver setting

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#3720]
I noticed this on a server that only had imagick installed.  The images were failing to create even with imagick selected as the 'driver' value in config/image.php.  To reproduce:

* Set driver to imagick
* `php artisan tinker` `config('image');` - **this will show the correct value**
* On the next line after Intervention\Image\ImageManager line 103 add `echo $drivername;`.  For me it is still showing gd.

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/7995c4d3b1da7f443a38e44762a8e945c200beee
