### ISSUE TITLE
[pages-module] Feature: GUI should allow any twig template file to be associated via an open text field

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#3721]
It looks like currently Pyro is just parsing the "layouts" directory and offering these as options for a template to associate with a page.  For the most part I would prefer to create top level directories for each section of the site (see below).  So for a blog page i would like to just type in "blog.index" and for an about page "about.index" rather than being forced to put these templates in a layouts directory.

Additionally, it would be nice to have the option to assign a page to a controller rather than a route and have the entry passed in as an argument.
- layouts
  - default
  - error
- team
  - index
  - detail
- blog
  - index
    -detail
- about
  -index

**Comment by RyanThompson** [comment]
We've tried this route but users have a hard time with it. They don't understand what the path means. So a simple dropdown made more sense.

HOWEVER - I totally agree that it'd be nice and I do want to allow controller's to handle routes as well. I think this is something that PageHandler's can help with but haven't been able to flesh it out. I've got some changes slated for 3.1.

**Comment by mattcdavis1** [comment]
hmm - that's the way it is with craft (just type in path) and no one seems to be getting confused.  Maybe we just need instructions that make it clearer (possibly an example of what a path looks like).  Or pehaps provide both options (dropdown plus text input and take the text input if filled out).  

At minimum, IMO all template files should be available (not just templates in the layouts directory). 

https://www.dropbox.com/s/rmsqllvxqdzhpb4/2016-05-31_11-07-42.png?dl=0

**Comment by RyanThompson** [comment]
I would be open to making them all available and presenting them in an optgroup for the dropdown.

Who's managing your sites? How do they know what templates are available? 

In our case - we generally turn over a locked down / stripped version of the system to the end user(s) to manage themselves. Leaving us administrative power.

**Comment by RyanThompson** [comment]
Pyro and Craft also differ here - we don't rely on theme templates but for outter layout. Whereas Craft is closer to EE in the respect that everything relates back to a template. You can do that here - but I would pry do it a wee bit differently.

**Comment by mattcdavis1** [comment]
What do you meant by "we don't rely on theme templates but for outer layout," In the case of pages modules what other options are available?  Either way, templates are an option for pages and to that extent it is the same as Craft.

**Comment by RyanThompson** [comment]
Honestly, I might have Craft mis-understood but I think it comes down to how you use it! There are many different ways you can use something but generally we (my team) keep page / CMS specific information out of themes. BUT.. You 100% don’t have to considering (as far as my team goes) never distribute themes. It’s always for the project at hand.

But generally our layouts are default, index and sidebar. Then the page TYPE organizes how each page’s content is handled. Again, just how we use it. I suspect better / different patterns will emerge like you are referring to and we’ll need to make sure it’s accommodated or adapt to do so.

**Comment by RyanThompson** [comment]
@mattcdavis1 you wanna add optgroup support here: https://github.com/anomalylabs/select-field_type/blob/master/src/Handler/Layouts.php

Use a nested array and humanize the directory name for the key. PR it up!

**Comment by mattcdavis1** [comment]
yeah sure - I'll try and get this added over the weekend and then submit a PR

**Comment by mattcdavis1** [comment]
@RyanThompson i just realized that you have that theme dropdown at both a page type and a page level.  Really all i'm concerned about is the page type level.  I agree that it would be confusing for end users to have to choose from a list of templates when creating pages.  

I would actually prefer to have the page level dropdown removed entirely (or if not please allow a configuration option to hide it).  I don't want end users trying to design the site or choose it's look and feel.

Would you be ok adding a simple text field in place of a dropdown at a Page Type level since this should be purely targeted at developers?  Also, what roles does the page level theme option play?  Is that an override of the Page Type theme option or is that something in addition to the page option setting?

**Comment by ikoniqoz** [comment]
Cant Page Types be hidden from content editors by Permissions as in all previous versions ?

**Comment by RyanThompson** [comment]
Yes they can be hidden with permissions - no permission, you don’t see it.

Matt the page type layout designates the default layout to use. You can override that as desired and it’s not uncommon. We have a lot of clients that use it to create basically the same page but with different .. layouts lol. Sidebar is sometimes not desired so they will choose the default layout or one with a banner (then we use a partial to determine which banner they want to use). We’ve had 0 issues with it thus far.

**Comment by RyanThompson** [comment]
This has been implemented in a more simple manner but will be expounded upon in v2.2: https://github.com/anomalylabs/pages-module/commit/cd48fc56352d85f5d1ebd3423255e277fd2e2ae6

**Comment by RyanThompson** [comment]
You can now extend anything from the type layout - and soon will have similar potential with the pages/posts too (same pattern).
