### ISSUE TITLE
[Streams Module] Feature Request: Nested Stream Entries

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#3723]
Currently streams can be sorted and navigation / pages can be nested but there is no way that i'm aware of to nest streams entries.  For example, if i want to create a stream of "Categories" that have an image, a description and some other fields and are nested 3 levels deep i don't think there is currently a way to do this.

**Comment by ikoniqoz** [comment]
@RyanThompson Looks like the Ol' Master / Detail list thing from yonks ago... Remember ?

**Comment by RyanThompson** [comment]
I could make the TreeBuilder the UI component for Streams needing this kinda behavior. What would be a good way to "toggle" this do you think?

**Comment by bloveless** [comment]
What if when you are creating the stream you can select nestable. That would add a parent_id column to the stream as well as switch to the TreeBuilder instead of a TableBuilder.

**Comment by RyanThompson** [comment]
Could be part of building that streams config JSON

**Comment by bloveless** [comment]
I suppose as long as the DB has the parent_id column then it could go in the config JSON. Would that mean that you'd have to add the parent_id column to every stream no matter what? Or would that be configurable as well?

**Comment by RyanThompson** [comment]
@bloveless I would make that configurable as well - since it's technically configurable on the builder I think. If not it should be. Can't recall.
