### ISSUE TITLE
Font Awesome Not Display At PyroCMS 3 RC2

### ISSUE THREAD

**Issue by bluedragonID** [pyrocms/pyrocms#3724]
I Am Just Installed PyroCMS In Localhost. But The Icons In Dasboard Can't Display
This The Sreenshot :
![image4144](https://cloud.githubusercontent.com/assets/18642710/15641157/0b80cf78-2669-11e6-8271-d4be276a31ac.png)

**Comment by RyanThompson** [comment]
Can you let me know if they're 404 or not? And if so paste the URL it's attempting from your browser debugger!

**Comment by RyanThompson** [comment]
I can't do much about this one without more details but thinking it's either an issue with being installed in a path instead of a domain but not sure.. if you have more info lets open this back up.

**Comment by marcsoler** [comment]
Happend to me too running a local server like XAMPP:

`http://localhost/app/default/assets/core/pyrocms/pyrocms-theme/resources/fonts/font-awesome/fontawesome-webfont.woff2 `

Resolved by creating virtual hosts

**Comment by RyanThompson** [comment]
Ok - Ill take a look at spinning up a folder based install. Thanks for the heads up @marcsoler !

**Comment by RyanThompson** [comment]
Will merge into master shortly. 

Fixed: 

https://github.com/anomalylabs/streams-platform/pull/226/commits/00fae8aaab75a1da2c13480d7148971e30d54186

https://github.com/anomalylabs/streams-platform/pull/226/commits/b0234e311579464c122512c4211644c32098681c
