### ISSUE TITLE
Error with anomaly.field_type.datetime on required true

### ISSUE THREAD

**Issue by Philippe-Mange** [pyrocms/pyrocms#3725]
I got an error when i save a form with a field 'anomaly.field_type.datetime' with the option required true, when i forget to fill in the time part
DATA MISSING 
DatetimeFieldType->getPostValue(null) 

rgds

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/datetime-field_type/commit/be5fd2e1c374a25b06fa7ee650710a69b2c53df9
