### ISSUE TITLE
[UX] High fidelity improvements for control panel

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#3731]
We will start keeping track of some of the user improvements here.
- [ ] Hot Links / Shortcuts for quick navigation
- [x] CMD-S to save (windows and linux versions as well)
- [ ] CMD-N to open a new form when looking at a table view or a form (windows and linux also)
- [x] Support for sub-sections / more sections (possibly alternate / opt-in layout)
- [x] Support for module-categories in push menu (similar to 2.2 concept)
- [x] Allow image management from the Editor FT. Upload images and then select them to add the image path or include code at the cursor.
- [ ]  Module to upload directly from the admin side (theme, extension, plugin, modules)
- [x] Better image properties on Reactor editor (padding, floats, borders, css classes)

Anyone/everyone feel free to comment on this issue with things you'd like implemented/changed to make the admin UI perfect!

**Comment by jcastillotx** [comment]
- [ ]  Module to upload directly from the admin side (theme, extension, plugin, modules)
- [ ] Better image properties on Reactor editor

**Comment by RyanThompson** [comment]
Can you tell me more what you are looking for in redactor? Specifics ^_^

**Comment by jcastillotx** [comment]
We talked about it -- the ability to add padding, floats, borders, classes. I can do it with HTMl but my content writers not so much.

**Comment by RyanThompson** [comment]
Donzo - keeping the uploader out of the picture for a bit yet though. If there is significant demand for it we can revisit.
