### ISSUE TITLE
[Streams Platform] [FieldType] Add config for DB column

### ISSUE THREAD

**Issue by hotrdung** [pyrocms/pyrocms#3736]
**Suggestion:**
_File: /vendor/anomaly/streams-platform/src/Addon/FieldType/FieldType.php_

public function getColumnType()
{
   return array_get($this->getConfig(), 'column_type', $this->columnType);
}

⇒ then a field can be defined like this:
'status'   => [
   'type'   => 'anomaly.field_type.integer',
   'config' => [
       'column_type' => 'smallInteger',
   ],
],

**Comment by RyanThompson** [comment]
@bloveless what do you think? @hotrdung You can easily use a boolean FT as well (going off your field name)

**Comment by RyanThompson** [comment]
I am going to hold off on this one for now. Optimization for DB schema as a whole needs to be implemented as a service firstly. And some FTs have their own implementation of switching DB columns too. Perhaps this will be moved into the integer FT itself - hard saying right now.
