### ISSUE TITLE
[FormBuilder] "Update" and "Save & Exit" buttons have the same action when redirect option is set

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#3740]
```
protected $options => [
    'redirect' => '/admin/inbound_marketing/forms/fields/{entry.form_id}'
];
```

Will cause the Update button and the Save & Exit buttons to leave the page and go wherever the redirect option is set. Seems like the "Save & Exit" button shouldn't leave the page even if redirect is set.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/e7b79c2302ca0acdb2d04f2b613fb6a6eba6641b
