### ISSUE TITLE
[FormBuilder] Cancel button on forms does not respect the redirect option

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#3741]
```
protected $options => [
    'redirect' => '/admin/inbound_marketing/forms/fields/{entry.form_id}'
];
```

Cancel will still redirect to whatever it would have if there was no redirect option. Seems like it should redirect to the same place as the redirect options.

**Comment by RyanThompson** [comment]
Cancel is a button component - which doesn't use the redirect option. The intention of the redirect is to provide a simple directive for the default (first) action component for the form.

**Comment by bloveless** [comment]
I can accept that, but I still need to set the URL for the cancel button since it goes to the wrong place right now.

**Comment by RyanThompson** [comment]
Cancel uses href
