### ISSUE TITLE
[FormBuilder] When the form/handler route is used the error messages are not passed back to the view

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#3742]
@RyanThompson we were talking about this one. Something like the form should be able to determine if it is being posted from the admin (directly to the form) or from the front-end (using the form/handler route) and still pass the errors to the front-end version of the form.

**Comment by RyanThompson** [comment]
Need to move flashing logic to it's own $form->flash() and command to use on the controller..

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/a1618bad385aa41a6494a2bf1406b8e56a0e75c5
