### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#3746]
Notes on existing documentation below. Feel free to suggest new docs that are not already planned: https://github.com/anomalylabs/streams-platform/blob/develop/docs/roadmap.md

## Installation

- [ ] How to remove installer properly

**Comment by joannamroz** [comment]
suggestion for adding to documentation part about overriding partials from existing modules
for example overriding post.twig from posts-module 
\core\anomaly\posts-module\resources\views\posts\post.twig
is possible by creating post.twing in
\addons\{sitename}\anomaly\{theme_folder}\resources\views\addons\anomaly\posts-module\posts\post.twig
Thanks again for help!
