### ISSUE TITLE
Duplicate public folder

### ISSUE THREAD

**Issue by cphubs** [pyrocms/pyrocms#3749]
Hi

after i install pyrocms with composer in xampp/htdocs folder when i run installer in browser, pyrocms can not load css and java and other files.

I search and find that pyrocms make duplicate folder in Public folder like this:

xampp\htdocs\pyrocms\public\pyrocms\public\app\default

and now i have two app folder.
What is the problem?

**Comment by RyanThompson** [comment]
This is what is responsible for that:

https://github.com/anomalylabs/streams-platform/blob/develop/src/Asset/AssetPaths.php#L180 <https://github.com/anomalylabs/streams-platform/blob/develop/src/Asset/AssetPaths.php#L180> 

Is your request root also incorrect?

**Comment by cphubs** [comment]
I echo it and it seems that there is no problem here

/pyrocms/public/app/default/assets/public/theme.css
