### ISSUE TITLE
Files upload Page Not Found (404)

### ISSUE THREAD

**Issue by liuflowt** [pyrocms/pyrocms#3755]
![bug](https://cloud.githubusercontent.com/assets/20101964/16325479/22925286-39f1-11e6-8c0a-600305e1b8d3.png)

After I selecting the logo and refresh the page selected logo is empty again

**Comment by RyanThompson** [comment]
Try s composer update. I believe this has been patched.

**Comment by liuflowt** [comment]
![image](https://cloud.githubusercontent.com/assets/20101964/16326339/5079e694-39f8-11e6-9020-b32a201cd05b.png)

**Comment by RyanThompson** [comment]
composer update and clear assets
