### ISSUE TITLE
Automatic logout in Admin Dashboard

### ISSUE THREAD

**Issue by liuflowt** [pyrocms/pyrocms#3756]

**Comment by RyanThompson** [comment]
After 10 minutes of inactivity or whatever you mean? I used to have this actually..

**Comment by liuflowt** [comment]
Sometimes it is autologout even less than 10 minutes

**Comment by RyanThompson** [comment]
Ill add this but make it configurable.

**Comment by RyanThompson** [comment]
I think I am going to actually leave this one as it is for the time being. We've got some UI work to be done going forward and this can be revisited after that.
