### ISSUE TITLE
Issue Installing 

### ISSUE THREAD

**Issue by bdeacon** [pyrocms/pyrocms#3761]
I am new to Pyrocms and am evaluating for a large project.  I am trying to install on CENTOS and running into the below issue when running  php artisan optimize: 

[2016-06-27 21:12:06] production.ERROR: exception 'ErrorException' with message 'Undefined index: REQUEST_URI' in /var/www/vhosts/new2.livewiresolution.com/pyrocms/vendor/anomaly/streams-platform/src/Http/Kernel.php:44
Stack trace:
#0 /var/www/vhosts/new2.livewiresolution.com/pyrocms/vendor/anomaly/streams-platform/src/Http/Kernel.php(44): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/vhosts...', 44, Array)
#1 /var/www/vhosts/new2.livewiresolution.com/pyrocms/vendor/anomaly/streams-platform/src/Http/Kernel.php(25): Anomaly\Streams\Platform\Http\Kernel->defineLocale()
#2 [internal function]: Anomaly\Streams\Platform\Http\Kernel->__construct(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router))
#3 /var/www/vhosts/new2.livewiresolution.com/pyrocms/vendor/laravel/framework/src/Illuminate/Container/Container.php(780): ReflectionClass->newInstanceArgs(Array)
#4 /var/www/vhosts/new2.livewiresolution.com/pyrocms/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('Anomaly\\Streams...', Array)
#5 /var/www/vhosts/new2.livewiresolution.com/pyrocms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Anomaly\\Streams...', Array)
#6 /var/www/vhosts/new2.livewiresolution.com/pyrocms/vendor/laravel/framework/src/Illuminate/Container/Container.php(220): Illuminate\Foundation\Application->make('Anomaly\\Streams...', Array)
#7 /var/www/vhosts/new2.livewiresolution.com/pyrocms/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array)
#8 /var/www/vhosts/new2.livewiresolution.com/pyrocms/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build(Object(Closure), Array)
#9 /var/www/vhosts/new2.livewiresolution.com/pyrocms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#10 /var/www/vhosts/new2.livewiresolution.com/pyrocms/vendor/laravel/framework/src/Illuminate/Container/Container.php(1167): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#11 /var/www/vhosts/new2.livewiresolution.com/pyrocms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Container\Container->offsetGet('Illuminate\\Cont...')
#12 /var/www/vhosts/new2.livewiresolution.com/pyrocms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#13 /var/www/vhosts/new2.livewiresolution.com/pyrocms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#14 /var/www/vhosts/new2.livewiresolution.com/pyrocms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(208): Illuminate\Foundation\Application->bootstrapWith(Array)
#15 /var/www/vhosts/new2.livewiresolution.com/pyrocms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#16 /var/www/vhosts/new2.livewiresolution.com/pyrocms/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 {main}

**Comment by RyanThompson** [comment]
Hi! Well, that's an easy one.. weird that it's not set though: https://github.com/anomalylabs/streams-platform/blob/master/src/Http/Kernel.php#L44

Could you try using array_get($_SERVER, 'request_uri') instead?

**Comment by RyanThompson** [comment]
`$_SERVER['ORIGINAL_REQUEST_URI'] = array_get($_SERVER, 'REQUEST_URI');` Just to clarify

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/9bf72239e357a80c3cb66a15b7cc89cec90995a8
