### ISSUE TITLE
Settings should return default value if one has not been set

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#3762]
I.E. streams::name is null until you open the settings page and press save. Then it will get either the user entered value or the streams::distribution.name.

Would be nice if it could pull the default value before the user has pressed the save button. That is, if there is a default value set in the config/settings.php file.

**Comment by bloveless** [comment]
https://github.com/anomalylabs/settings-module/pull/11

**Comment by RyanThompson** [comment]
Merged
