### ISSUE TITLE
Lang button error

### ISSUE THREAD

**Issue by luisfer7192** [pyrocms/pyrocms#3763]
I create ES and EN button file to new_customer, and i use by default ES

When i create both files, only read EN button file, the text of the button is Create Customer, it should be Crear Cliente.

I change the name file of /lang/en/button.php because it is a problem.

**Comment by RyanThompson** [comment]
If the button is not translated then there is likely a problem with your key / file / folder or you're viewing the system in english.

`resources/lang/es/button.php` => create_customer => Translation 

would be the correct path

Also make sure your `.env` file does nat have LAZY_TRANSLATIONS defined in it or false

**Comment by luisfer7192** [comment]
i have 2 files:
customers-module/resources/lang/en/button.php
customers-module/resources/lang/es/button.php

both at the same structure

i have all page in spanish, but the only text is in english is the new_customer button

Look the images please
[http://i65.tinypic.com/23s9kaq.jpg](url)
[http://oi66.tinypic.com/5jzmms.jpg](url)

**Comment by RyanThompson** [comment]
What language does it say is active in the footer?

**Comment by luisfer7192** [comment]
i dont know how to preview a image. link:

http://oi66.tinypic.com/23rwyz4.jpg

**Comment by RyanThompson** [comment]
Also send me your module class $sections


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by RyanThompson** [comment]
Cause it shows new_customer in the lang file - but create_customer may be what you used (hence the naming). Both behave the same cause they are similar but sometimes one sounds better than the other; but they are going to use different keys.


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by luisfer7192** [comment]
i will check what happend but i have one question, at the start i try to create a module with out title, it show me error because the order by use title, so where can i change the order by of the DB select?

**Comment by RyanThompson** [comment]
Ahh - depending on where this is you can do it in $options for your table like order_by => [field => direction]

Or in your criteria the same thing can be done as in eloquent entries(foo).orderBy(foo, asc).get()
