### ISSUE TITLE
Can't upload gif file

### ISSUE THREAD

**Issue by liuflowt** [pyrocms/pyrocms#3764]
![image](https://cloud.githubusercontent.com/assets/20101964/16441051/8c7a7b0e-3df9-11e6-8bda-139db1e8b569.png)

**Comment by RyanThompson** [comment]
Your folder displays that it only allows png jpeg jpg to be uploaded - edit your folder to allow gif

**Comment by liuflowt** [comment]
I found allowing of file type in Admin Dashboard > Field edit.
