### ISSUE TITLE
Move core/.gitignore to main .gitignore

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#3768]
I don't think /core should be on the .gitignore at all.  The only thing that should be on .gitignore IMO is stuff that could differ by environment or user generated stuff. I don't want to have to run composer update / install every time i deploy that's a real pain.  It's much better to keep this sort of stuff in the repo - this also provides more assurance that your local environment matches prod. 

However, if all the .gitignore directories (excluding above mentioned) are at least placed in the main .gitignore (like laravel does with /vendor) i can remove all the unwanted gitignores in one place and also not have to worry about a core update adding the file back.

**Comment by RyanThompson** [comment]
I agree and disagree. I think this is more to do with how Pyro is distributed right now. By nature it's decoupled / modular. But, things will be changing just slightly with the advent of downloadable versions in the forthcoming store. 

That said, I wouldn't be against removing the folder .gitignore file in the core dir - it's already being ignored in the base. Then you can just remove it and be done.. At the time though and it looks like it's still like that - Laravel did a lot of the .gitignore stuff IN directories. I ended up doing both lol - doh!

**Comment by RyanThompson** [comment]
https://github.com/pyrocms/pyrocms/commit/bc03724aabce1d94efd5adb50d4ac0a10dfcc4ac
