### ISSUE TITLE
XML Feed Widget fails if curl is not installed

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#3769]
Error is posted below.  I'm guessing most servers will have curl installed - my suggestion would be to just add the requirement for curl [here](http://pyrocms.com/documentation/pyrocms/installation) since the xml feed widget is installed by default.  As soon as i installed curl the issue was resolved.  This may be related to [this ticket](https://github.com/pyrocms/pyrocms/issues/3748) - not sure.

Next Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("An exception has been thrown during the rendering of a template ("gzinflate(): data error") in "/var/www/investments.budget-app.com/core/anomaly/dashboard-module/resources/views/admin/dashboards/partials/columns.twig" at line 17.") in "/var/www/investments.budget-app.com/core/anomaly/dashboard-module/resources/views/admin/dashboards/dashboard.twig" at line 13. in /var/www/investments.budget-app.com/vendor/twig/twig/lib/Twig/Template.php:160
Stack trace:
#0 /var/www/investments.budget-app.com/storage/framework/views/twig/9/7/973aba517e48c1cd541e66e61b402020d550ec776b78a945beba6a108c3e0e83.php(73): Twig_Template->displayBlock('content', Array, Array)
#1 /var/www/investments.budget-app.com/vendor/twig/twig/lib/Twig/Template.php(322): __TwigTemplate_973aba517e48c1cd541e66e61b402020d550ec776b78a945beba6a108c3e0e83->doDisplay(Array, Array)
#2 /var/www/investments.budget-app.com/vendor/twig/twig/lib/Twig/Template.php(296): Twig_Template->displayWithErrorHandling(Array, Array)
#3 /var/www/investments.budget-app.com/vendor/rcrowe/twigbridge/src/Twig/Template.php(41): Twig_Template->display(Array, Array)
#4 /var/www/investments.budget-app.com/storage/framework/views/twig/6/c/6c3fd4b51cfde0bd24445bcabb6392980c857d2ea842b2f220ad8a33227244b7.php(23): TwigBridge\Twig\Template->display(Array, Array)
#5 /var/www/investments.budget-app.com/vendor/twig/twig/lib/Twig/Template.php(322): __TwigTemplate_6c3fd4b51cfde0bd24445bcabb6392980c857d2ea842b2f220ad8a33227244b7->doDisplay(Array, Array)
#6 /var/www/investments.budget-app.com/vendor/twig/twig/lib/Twig/Template.php(296): Twig_Template->displayWithErrorHandling(Array, Array)
#7 /var/www/investments.budget-app.com/vendor/rcrowe/twigbridge/src/Twig/Template.php(41): Twig_Template->display(Array, Array)
#8 /var/www/investments.budget-app.com/vendor/twig/twig/lib/Twig/Template.php(307): TwigBridge\Twig\Template->display(Array)
#9 /var/www/investments.budget-app.com/vendor/rcrowe/twigbridge/src/Engine/Twig.php(90): Twig_Template->render(Array)
#10 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/View/View.php(147): TwigBridge\Engine\Twig->get('/var/www/invest...', Array)
#11 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/View/View.php(118): Illuminate\View\View->getContents()
#12 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/View/View.php(83): Illuminate\View\View->renderContents()
#13 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Http/Response.php(51): Illuminate\View\View->render()
#14 /var/www/investments.budget-app.com/vendor/symfony/http-foundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#15 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1229): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#16 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#17 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 /var/www/investments.budget-app.com/vendor/barryvdh/laravel-stack-middleware/src/ClosureHttpKernel.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/investments.budget-app.com/vendor/symfony/http-kernel/HttpCache/HttpCache.php(487): Barryvdh\StackMiddleware\ClosureHttpKernel->handle(Object(Illuminate\Http\Request), 1, true)
#21 /var/www/investments.budget-app.com/vendor/symfony/http-kernel/HttpCache/HttpCache.php(444): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Illuminate\Http\Request), true)
#22 /var/www/investments.budget-app.com/vendor/symfony/http-kernel/HttpCache/HttpCache.php(344): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Illuminate\Http\Request), true)
#23 /var/www/investments.budget-app.com/vendor/symfony/http-kernel/HttpCache/HttpCache.php(210): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Illuminate\Http\Request), true)
#24 /var/www/investments.budget-app.com/vendor/barryvdh/laravel-stack-middleware/src/ClosureMiddleware.php(36): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Illuminate\Http\Request))
#25 [internal function]: Barryvdh\StackMiddleware\ClosureMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#27 /var/www/investments.budget-app.com/vendor/anomaly/streams-platform/src/Http/Middleware/PoweredBy.php(46): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Anomaly\Streams\Platform\Http\Middleware\PoweredBy->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#30 /var/www/investments.budget-app.com/vendor/anomaly/streams-platform/src/Http/Middleware/SetLocale.php(92): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Anomaly\Streams\Platform\Http\Middleware\SetLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#33 /var/www/investments.budget-app.com/vendor/anomaly/streams-platform/src/Http/Middleware/ApplicationReady.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Anomaly\Streams\Platform\Http\Middleware\ApplicationReady->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#36 /var/www/investments.budget-app.com/vendor/anomaly/streams-platform/src/Http/Middleware/VerifyCsrfToken.php(69): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Anomaly\Streams\Platform\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#39 /var/www/investments.budget-app.com/core/anomaly/users-module/src/Http/Middleware/AuthorizeRoutePermission.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Anomaly\UsersModule\Http\Middleware\AuthorizeRoutePermission->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#42 /var/www/investments.budget-app.com/core/anomaly/users-module/src/Http/Middleware/AuthorizeControlPanel.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Anomaly\UsersModule\Http\Middleware\AuthorizeControlPanel->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#45 /var/www/investments.budget-app.com/core/anomaly/users-module/src/Http/Middleware/AuthorizeModuleAccess.php(64): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Anomaly\UsersModule\Http\Middleware\AuthorizeModuleAccess->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#48 /var/www/investments.budget-app.com/core/anomaly/users-module/src/Http/Middleware/CheckSecurity.php(87): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: Anomaly\UsersModule\Http\Middleware\CheckSecurity->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#51 /var/www/investments.budget-app.com/core/anomaly/users-module/src/Http/Middleware/Authenticate.php(93): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Anomaly\UsersModule\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#54 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#57 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Anomaly\DashboardModule\Http\Controller\Admin\DashboardsController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'view')
#58 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Anomaly\\Dashboa...', 'view')
#59 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#60 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#61 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#63 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#65 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#66 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#67 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#68 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#69 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#70 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#71 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#74 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#77 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#78 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#79 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#80 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#81 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#82 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#83 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#84 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#85 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#86 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#87 /var/www/investments.budget-app.com/public/index.php(56): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#88 {main}

Next ErrorException: An exception has been thrown during the rendering of a template ("An exception has been thrown during the rendering of a template ("gzinflate(): data error") in "/var/www/investments.budget-app.com/core/anomaly/dashboard-module/resources/views/admin/dashboards/partials/columns.twig" at line 17.") in "/var/www/investments.budget-app.com/core/anomaly/dashboard-module/resources/views/admin/dashboards/dashboard.twig" at line 13. in /var/www/investments.budget-app.com/core/anomaly/dashboard-module/resources/views/admin/dashboards/dashboard.twig:13
Stack trace:
#0 /var/www/investments.budget-app.com/vendor/rcrowe/twigbridge/src/Engine/Twig.php(92): TwigBridge\Engine\Twig->handleTwigError(Object(Twig_Error_Runtime))
#1 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/View/View.php(147): TwigBridge\Engine\Twig->get('/var/www/invest...', Array)
#2 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/View/View.php(118): Illuminate\View\View->getContents()
#3 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/View/View.php(83): Illuminate\View\View->renderContents()
#4 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Http/Response.php(51): Illuminate\View\View->render()
#5 /var/www/investments.budget-app.com/vendor/symfony/http-foundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#6 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1229): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#7 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#8 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 /var/www/investments.budget-app.com/vendor/barryvdh/laravel-stack-middleware/src/ClosureHttpKernel.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /var/www/investments.budget-app.com/vendor/symfony/http-kernel/HttpCache/HttpCache.php(487): Barryvdh\StackMiddleware\ClosureHttpKernel->handle(Object(Illuminate\Http\Request), 1, true)
#12 /var/www/investments.budget-app.com/vendor/symfony/http-kernel/HttpCache/HttpCache.php(444): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Illuminate\Http\Request), true)
#13 /var/www/investments.budget-app.com/vendor/symfony/http-kernel/HttpCache/HttpCache.php(344): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Illuminate\Http\Request), true)
#14 /var/www/investments.budget-app.com/vendor/symfony/http-kernel/HttpCache/HttpCache.php(210): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Illuminate\Http\Request), true)
#15 /var/www/investments.budget-app.com/vendor/barryvdh/laravel-stack-middleware/src/ClosureMiddleware.php(36): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Illuminate\Http\Request))
#16 [internal function]: Barryvdh\StackMiddleware\ClosureMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#18 /var/www/investments.budget-app.com/vendor/anomaly/streams-platform/src/Http/Middleware/PoweredBy.php(46): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: Anomaly\Streams\Platform\Http\Middleware\PoweredBy->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#21 /var/www/investments.budget-app.com/vendor/anomaly/streams-platform/src/Http/Middleware/SetLocale.php(92): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: Anomaly\Streams\Platform\Http\Middleware\SetLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#24 /var/www/investments.budget-app.com/vendor/anomaly/streams-platform/src/Http/Middleware/ApplicationReady.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Anomaly\Streams\Platform\Http\Middleware\ApplicationReady->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#27 /var/www/investments.budget-app.com/vendor/anomaly/streams-platform/src/Http/Middleware/VerifyCsrfToken.php(69): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Anomaly\Streams\Platform\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#30 /var/www/investments.budget-app.com/core/anomaly/users-module/src/Http/Middleware/AuthorizeRoutePermission.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Anomaly\UsersModule\Http\Middleware\AuthorizeRoutePermission->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#33 /var/www/investments.budget-app.com/core/anomaly/users-module/src/Http/Middleware/AuthorizeControlPanel.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Anomaly\UsersModule\Http\Middleware\AuthorizeControlPanel->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#36 /var/www/investments.budget-app.com/core/anomaly/users-module/src/Http/Middleware/AuthorizeModuleAccess.php(64): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Anomaly\UsersModule\Http\Middleware\AuthorizeModuleAccess->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#39 /var/www/investments.budget-app.com/core/anomaly/users-module/src/Http/Middleware/CheckSecurity.php(87): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Anomaly\UsersModule\Http\Middleware\CheckSecurity->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#42 /var/www/investments.budget-app.com/core/anomaly/users-module/src/Http/Middleware/Authenticate.php(93): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Anomaly\UsersModule\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#45 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#47 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#48 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Anomaly\DashboardModule\Http\Controller\Admin\DashboardsController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'view')
#49 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Anomaly\\Dashboa...', 'view')
#50 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#51 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#52 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#54 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#57 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#58 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#59 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#60 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#61 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#62 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#65 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#68 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#71 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#74 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#76 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#77 /var/www/investments.budget-app.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#78 /var/www/investments.budget-app.com/public/index.php(56): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#79 {main}

**Comment by RyanThompson** [comment]
Done! https://github.com/pyrocms/pyrocms/commit/e618059b694a506209183399ed8993f9eb4f0387
