### ISSUE TITLE
Pyrocms 3.0 installation problem using composer

### ISSUE THREAD

**Issue by bakshisourabh** [pyrocms/pyrocms#3771]
Its showing 
500 There was an error.
503 Service Unavailabe

When trying to install pyrocms 3.0 using composer.
![pyrocms](https://cloud.githubusercontent.com/assets/20320898/16620124/ddfbce46-43ae-11e6-820b-35a6dbe1d851.png)

**Comment by RyanThompson** [comment]
What do your Laravel logs say about the error?

**Comment by bakshisourabh** [comment]
Getting the error as mentoined below


[Wed Jul 06 18:25:56 2016] [error] [client 192.168.1.2] File does not
exist: E:/websites/new_pyro.com/www/installer

On Wed, Jul 6, 2016 at 7:30 PM, Ryan Thompson <notifications@github.com>
wrote:

> What do your Laravel logs say about the error?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pyrocms/pyrocms/issues/3771#issuecomment-230779784>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATYSgq0XKmE3HlSzJoAF2zUENGMLK4MPks5qS7TrgaJpZM4JGGZw>
> .
>



-- 


*Sourabh Suresh BakshiMobile Number  : 9890638088*
*Email   Address  : *bakshisourabh@gmail.com

*Preserve our Environment , Print this e-mail if only necessary !*

**Comment by RyanThompson** [comment]
Looks like either your .htaccess needs tweaking but ore likely that you haven’t set the site’s web root properly. It should be the public folder not pyro root - just like Laravel.

**Comment by bakshisourabh** [comment]
Also showing the following errors in the logs

production.ERROR: exception
'Symfony\Component\Debug\Exception\FatalErrorException' with message
'Maximum execution time of 60 seconds exceeded' in E:\websites\new_pyro.com
\www\vendor\oyejorge\less.php\lib\Less\Parser.php:1565
Stack trace:
#0 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(2094):
Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(2089):
Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(0):
Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(720):
Less_Parser->parseEntity()
#4 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(2388):
Less_Parser->MatchFuncs()
#5 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(720):
Less_Parser->parseExpression()
#6 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(1048):
Less_Parser->MatchFuncs()
#7 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(1028):
Less_Parser->parseEntitiesArguments()
#8 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(720):
Less_Parser->parseEntitiesCall()
#9 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(2364):
Less_Parser->MatchFuncs()
#10 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(2224):
Less_Parser->parseOperand()
#11 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(2263):
Less_Parser->parseMultiplication()
#12 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(720):
Less_Parser->parseAddition()
#13 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(2388):
Less_Parser->MatchFuncs()
#14 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(2185):
Less_Parser->parseExpression()
#15 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(720):
Less_Parser->parseValue()
#16 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(1887):
Less_Parser->MatchFuncs()
#17 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(720):
Less_Parser->parseRule()
#18 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(870):
Less_Parser->MatchFuncs()
#19 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(1759):
Less_Parser->parsePrimary()
#20 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(1814):
Less_Parser->parseBlock()
#21 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(720):
Less_Parser->parseRuleset()
#22 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(870):
Less_Parser->MatchFuncs()
#23 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(1759):
Less_Parser->parsePrimary()
#24 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(1767):
Less_Parser->parseBlock()
#25 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(2161):
Less_Parser->parseBlockRuleset()
#26 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(720):
Less_Parser->parseDirective()
#27 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(870):
Less_Parser->MatchFuncs()
#28 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(542):
Less_Parser->parsePrimary()
#29 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(363):
Less_Parser->GetRules()
#30 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Tree\Import.php(282):
Less_Parser->parseFile()
#31 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Tree\Import.php(198):
Less_Tree_Import->ParseImport()
#32 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Tree\Ruleset.php(248):
Less_Tree_Import->compile()
#33 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Tree\Ruleset.php(235):
Less_Tree_Ruleset->evalImports()
#34 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Tree\Ruleset.php(70):
Less_Tree_Ruleset->PrepareRuleset()
#35 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lib\Less\Parser.php(198):
Less_Tree_Ruleset->compile()
#36 E:\websites\new_pyro.com\www\vendor\oyejorge\less.php\lessc.inc.php(89):
Less_Parser->getCss()
#37 E:\websites\new_pyro.com\www\vendor\anomaly\streams-platform\src\Asset\Filter\LessFilter.php(71):
lessc->parse()
#38 E:\websites\new_pyro.com\www\vendor\kriswallsmith\assetic\src\Assetic\Filter\FilterCollection.php(69):
Anomaly\Streams\Platform\Asset\Filter\LessFilter->filterDump()
#39 E:\websites\new_pyro.com\www\vendor\kriswallsmith\assetic\src\Assetic\Asset\BaseAsset.php(112):
Assetic\Filter\FilterCollection->filterDump()
#40 E:\websites\new_pyro.com\www\vendor\kriswallsmith\assetic\src\Assetic\Asset\AssetCollection.php(151):
Assetic\Asset\BaseAsset->dump()
#41 E:\websites\new_pyro.com\www\vendor\anomaly\streams-platform\src\Asset\Asset.php(475):
Assetic\Asset\AssetCollection->dump()
#42 E:\websites\new_pyro.com\www\vendor\anomaly\streams-platform\src\Asset\Asset.php(432):
Anomaly\Streams\Platform\Asset\Asset->publish()
#43 E:\websites\new_pyro.com\www\vendor\anomaly\streams-platform\src\Asset\Asset.php(283):
Anomaly\Streams\Platform\Asset\Asset->getPath()
#44 E:\websites\new_pyro.com\www\vendor\anomaly\streams-platform\src\Asset\Asset.php(315):
Anomaly\Streams\Platform\Asset\Asset->path()
#45 E:\websites\new_pyro.com\www\storage\framework\views\twig\8\a\8aaef2526fe143145e4c368c5990ed11683e83d5208cff06ff6344a9f88f42d3.php(78):
Anomaly\Streams\Platform\Asset\Asset->style()
#46 E:\websites\new_pyro.com\www\storage\framework\views\twig\8\a\8aaef2526fe143145e4c368c5990ed11683e83d5208cff06ff6344a9f88f42d3.php(78):
call_user_func_array:{E:\websites\new_pyro.com
\www\storage\framework\views\twig\8\a\8aaef2526fe143145e4c368c5990ed11683e83d5208cff06ff6344a9f88f42d3.php:78}()
#47 E:\websites\new_pyro.com\www\vendor\twig\twig\lib\Twig\Template.php(322):
__TwigTemplate_8aaef2526fe143145e4c368c5990ed11683e83d5208cff06ff6344a9f88f42d3->doDisplay()
#48 E:\websites\new_pyro.com\www\vendor\twig\twig\lib\Twig\Template.php(296):
Twig_Template->displayWithErrorHandling()
#49 E:\websites\new_pyro.com\www\vendor\rcrowe\twigbridge\src\Twig\Template.php(41):
Twig_Template->display()
#50 E:\websites\new_pyro.com\www\storage\framework\views\twig\2\8\28a1928c7b6ef06969eb3ff571c7591ac88ec9e280594a438d9282494f664949.php(36):
TwigBridge\Twig\Template->display()
#51 E:\websites\new_pyro.com\www\vendor\twig\twig\lib\Twig\Template.php(322):
__TwigTemplate_28a1928c7b6ef06969eb3ff571c7591ac88ec9e280594a438d9282494f664949->doDisplay()
#52 E:\websites\new_pyro.com\www\vendor\twig\twig\lib\Twig\Template.php(296):
Twig_Template->displayWithErrorHandling()
#53 E:\websites\new_pyro.com\www\vendor\rcrowe\twigbridge\src\Twig\Template.php(41):
Twig_Template->display()
#54 E:\websites\new_pyro.com\www\storage\framework\views\twig\6\2\624bfb33a403e538f338669b88e581c36c7c10bafdf4ce14980eb81beab2c7d5.php(23):
TwigBridge\Twig\Template->display()
#55 E:\websites\new_pyro.com\www\vendor\twig\twig\lib\Twig\Template.php(322):
__TwigTemplate_624bfb33a403e538f338669b88e581c36c7c10bafdf4ce14980eb81beab2c7d5->doDisplay()
#56 E:\websites\new_pyro.com\www\vendor\twig\twig\lib\Twig\Template.php(296):
Twig_Template->displayWithErrorHandling()
#57 E:\websites\new_pyro.com\www\vendor\rcrowe\twigbridge\src\Twig\Template.php(41):
Twig_Template->display()
#58 E:\websites\new_pyro.com\www\vendor\twig\twig\lib\Twig\Template.php(307):
TwigBridge\Twig\Template->display()
#59 E:\websites\new_pyro.com\www\vendor\rcrowe\twigbridge\src\Engine\Twig.php(90):
Twig_Template->render()
#60 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(14627):
TwigBridge\Engine\Twig->get()
#61 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(14615):
Illuminate\View\View->getContents()
#62 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(14599):
Illuminate\View\View->renderContents()
#63 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(15750):
Illuminate\View\View->render()
#64 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(15272):
Illuminate\Http\Response->setContent()
#65 E:\websites\new_pyro.com\www\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(57):
Symfony\Component\HttpFoundation\Response->__construct()
#66 E:\websites\new_pyro.com\www\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(71):
Illuminate\Routing\ResponseFactory->make()
#67 E:\websites\new_pyro.com\www\vendor\anomaly\streams-platform\src\Ui\Form\Command\SetFormResponse.php(49):
Illuminate\Routing\ResponseFactory->view()
#68 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(1187):
Anomaly\Streams\Platform\Ui\Form\Command\SetFormResponse->handle()
#69 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(1187):
call_user_func_array:{E:\websites\new_pyro.com
\www\bootstrap\cache\compiled.php:1187}()
#70 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9490):
Illuminate\Container\Container->call()
#71 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9642):
Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#72 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9642):
call_user_func:{E:\websites\new_pyro.com
\www\bootstrap\cache\compiled.php:9642}()
#73 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9624):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#74 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9624):
call_user_func:{E:\websites\new_pyro.com
\www\bootstrap\cache\compiled.php:9624}()
#75 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9497):
Illuminate\Pipeline\Pipeline->then()
#76 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9483):
Illuminate\Bus\Dispatcher->dispatchNow()
#77 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(5444):
Illuminate\Bus\Dispatcher->dispatch()
#78 E:\websites\new_pyro.com\www\vendor\anomaly\streams-platform\src\Ui\Form\FormBuilder.php(268):
Anomaly\Streams\Platform\Ui\Form\FormBuilder->dispatch()
#79 E:\websites\new_pyro.com\www\core\anomaly\installer-module\src\Http\Controller\InstallerController.php(41):
Anomaly\Streams\Platform\Ui\Form\FormBuilder->render()
#80 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(8922):
Anomaly\InstallerModule\Http\Controller\InstallerController->index()
#81 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(8922):
call_user_func_array:{E:\websites\new_pyro.com
\www\bootstrap\cache\compiled.php:8922}()
#82 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(8991):
Illuminate\Routing\Controller->callAction()
#83 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(8971):
Illuminate\Routing\ControllerDispatcher->call()
#84 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9642):
Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}()
#85 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9642):
call_user_func:{E:\websites\new_pyro.com
\www\bootstrap\cache\compiled.php:9642}()
#86 E:\websites\new_pyro.com\www\vendor\anomaly\streams-platform\src\Http\Middleware\CheckForMaintenanceMode.php(77):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#87 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9634):
Anomaly\Streams\Platform\Http\Middleware\CheckForMaintenanceMode->handle()
#88 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9634):
call_user_func_array:{E:\websites\new_pyro.com
\www\bootstrap\cache\compiled.php:9634}()
#89 E:\websites\new_pyro.com\www\vendor\barryvdh\laravel-stack-middleware\src\ClosureHttpKernel.php(30):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#90 E:\websites\new_pyro.com\www\vendor\symfony\http-kernel\HttpCache\HttpCache.php(487):
Barryvdh\StackMiddleware\ClosureHttpKernel->handle()
#91 E:\websites\new_pyro.com\www\vendor\symfony\http-kernel\HttpCache\HttpCache.php(444):
Symfony\Component\HttpKernel\HttpCache\HttpCache->forward()
#92 E:\websites\new_pyro.com\www\vendor\symfony\http-kernel\HttpCache\HttpCache.php(344):
Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch()
#93 E:\websites\new_pyro.com\www\vendor\symfony\http-kernel\HttpCache\HttpCache.php(210):
Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup()
#94 E:\websites\new_pyro.com\www\vendor\barryvdh\laravel-stack-middleware\src\ClosureMiddleware.php(36):
Symfony\Component\HttpKernel\HttpCache\HttpCache->handle()
#95 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9634):
Barryvdh\StackMiddleware\ClosureMiddleware->handle()
#96 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9634):
call_user_func_array:{E:\websites\new_pyro.com
\www\bootstrap\cache\compiled.php:9634}()
#97 E:\websites\new_pyro.com\www\vendor\anomaly\streams-platform\src\Http\Middleware\PoweredBy.php(46):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#98 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9634):
Anomaly\Streams\Platform\Http\Middleware\PoweredBy->handle()
#99 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9634):
call_user_func_array:{E:\websites\new_pyro.com
\www\bootstrap\cache\compiled.php:9634}()
#100 E:\websites\new_pyro.com\www\vendor\anomaly\streams-platform\src\Http\Middleware\SetLocale.php(92):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#101 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9634):
Anomaly\Streams\Platform\Http\Middleware\SetLocale->handle()
#102 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9634):
call_user_func_array:{E:\websites\new_pyro.com
\www\bootstrap\cache\compiled.php:9634}()
#103 E:\websites\new_pyro.com\www\vendor\anomaly\streams-platform\src\Http\Middleware\ApplicationReady.php(57):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#104 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9634):
Anomaly\Streams\Platform\Http\Middleware\ApplicationReady->handle()
#105 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9634):
call_user_func_array:{E:\websites\new_pyro.com
\www\bootstrap\cache\compiled.php:9634}()
#106 E:\websites\new_pyro.com\www\vendor\anomaly\streams-platform\src\Http\Middleware\VerifyCsrfToken.php(69):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#107 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9634):
Anomaly\Streams\Platform\Http\Middleware\VerifyCsrfToken->handle()
#108 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9634):
call_user_func_array:{E:\websites\new_pyro.com
\www\bootstrap\cache\compiled.php:9634}()
#109 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9624):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#110 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9624):
call_user_func:{E:\websites\new_pyro.com
\www\bootstrap\cache\compiled.php:9624}()
#111 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(8972):
Illuminate\Pipeline\Pipeline->then()
#112 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(8957):
Illuminate\Routing\ControllerDispatcher->callWithinStack()
#113 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(7906):
Illuminate\Routing\ControllerDispatcher->dispatch()
#114 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(7877):
Illuminate\Routing\Route->runWithCustomDispatcher()
#115 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(7530):
Illuminate\Routing\Route->run()
#116 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9642):
Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#117 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9642):
call_user_func:{E:\websites\new_pyro.com
\www\bootstrap\cache\compiled.php:9642}()
#118 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9624):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#119 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9624):
call_user_func:{E:\websites\new_pyro.com
\www\bootstrap\cache\compiled.php:9624}()
#120 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(7531):
Illuminate\Pipeline\Pipeline->then()
#121 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(7519):
Illuminate\Routing\Router->runRouteWithinStack()
#122 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(7504):
Illuminate\Routing\Router->dispatchToRoute()
#123 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(2310):
Illuminate\Routing\Router->dispatch()
#124 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9642):
Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#125 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9642):
call_user_func:{E:\websites\new_pyro.com
\www\bootstrap\cache\compiled.php:9642}()
#126 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(12993):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#127 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9634):
Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#128 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9634):
call_user_func_array:{E:\websites\new_pyro.com
\www\bootstrap\cache\compiled.php:9634}()
#129 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(11585):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#130 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9634):
Illuminate\Session\Middleware\StartSession->handle()
#131 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9634):
call_user_func_array:{E:\websites\new_pyro.com
\www\bootstrap\cache\compiled.php:9634}()
#132 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(12730):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#133 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9634):
Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#134 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9634):
call_user_func_array:{E:\websites\new_pyro.com
\www\bootstrap\cache\compiled.php:9634}()
#135 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(12667):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#136 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9634):
Illuminate\Cookie\Middleware\EncryptCookies->handle()
#137 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9634):
call_user_func_array:{E:\websites\new_pyro.com
\www\bootstrap\cache\compiled.php:9634}()
#138 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9624):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#139 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(9624):
call_user_func:{E:\websites\new_pyro.com
\www\bootstrap\cache\compiled.php:9624}()
#140 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(2257):
Illuminate\Pipeline\Pipeline->then()
#141 E:\websites\new_pyro.com\www\bootstrap\cache\compiled.php(2240):
Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#142 E:\websites\new_pyro.com\www\public\index.php(57):
Illuminate\Foundation\Http\Kernel->handle()
#143 E:\websites\new_pyro.com\www\server.php(21): ()
#144 E:\websites\new_pyro.com\www\server.php(0): {main}()
#145 {main}

On Wed, Jul 6, 2016 at 7:35 PM, Ryan Thompson <notifications@github.com>
wrote:

> Looks like either your .htaccess needs tweaking but ore likely that you
> haven’t set the site’s web root properly. It should be the public folder
> not pyro root - just like Laravel.
>
> > On Jul 6, 2016, at 9:04 AM, Sourabh Bakshi <notifications@github.com>
> wrote:
> >
> > Getting the error as mentoined below
> >
> >
> > [Wed Jul 06 18:25:56 2016] [error] [client 192.168.1.2] File does not
> > exist: E:/websites/new_pyro.com/www/installer
> >
> > On Wed, Jul 6, 2016 at 7:30 PM, Ryan Thompson <notifications@github.com>
> > wrote:
> >
> > > What do your Laravel logs say about the error?
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/pyrocms/pyrocms/issues/3771#issuecomment-230779784
> >,
> > > or mute the thread
> > > <
> https://github.com/notifications/unsubscribe/ATYSgq0XKmE3HlSzJoAF2zUENGMLK4MPks5qS7TrgaJpZM4JGGZw
> >
> > > .
> > >
> >
> >
> >
> > --
> >
> >
> > *Sourabh Suresh BakshiMobile Number : 9890638088*
> > *Email Address : *bakshisourabh@gmail.com
> >
> > *Preserve our Environment , Print this e-mail if only necessary !*
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub <
> https://github.com/pyrocms/pyrocms/issues/3771#issuecomment-230781025>,
> or mute the thread <
> https://github.com/notifications/unsubscribe/ABDIv07Q8uZMDH3kfibJDH3NsT5QXqDYks5qS7XggaJpZM4JGGZw
> >.
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pyrocms/pyrocms/issues/3771#issuecomment-230781445>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATYSgpfZgJULf2U9H8MI8p4aNZJY_1Xmks5qS7Y4gaJpZM4JGGZw>
> .
>



-- 


*Sourabh Suresh BakshiMobile Number  : 9890638088*
*Email   Address  : *bakshisourabh@gmail.com

*Preserve our Environment , Print this e-mail if only necessary !*

**Comment by RyanThompson** [comment]
A few reloads should clear this one up - might have to do with your box. Are you using vagrant or anything? Our slack  team has a lot of guys who can help you out based on your environment more-so than I can I’m afraid :-/

You can join here: http://pyrocms.com/slack

**Comment by bakshisourabh** [comment]
Thanks a lot for you quick reply

On Wed, Jul 6, 2016 at 7:43 PM, Ryan Thompson <notifications@github.com>
wrote:

> A few reloads should clear this one up - might have to do with your box.
> Are you using vagrant or anything? Our slack team has a lot of guys who can
> help you out based on your environment more-so than I can I’m afraid :-/
>
> You can join here: http://pyrocms.com/slack
>
> > On Jul 6, 2016, at 9:10 AM, Sourabh Bakshi <notifications@github.com>
> wrote:
> >
> > Also showing the following errors in the logs
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pyrocms/pyrocms/issues/3771#issuecomment-230784000>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATYSgjwKKz8Kx6SAQdPOUI7dYJ_gfNu9ks5qS7gIgaJpZM4JGGZw>
> .
>



-- 


*Sourabh Suresh BakshiMobile Number  : 9890638088*
*Email   Address  : *bakshisourabh@gmail.com

*Preserve our Environment , Print this e-mail if only necessary !*

**Comment by RyanThompson** [comment]
You are very welcome!

**Comment by infolinematrix** [comment]
I am getting the same error
http://localhost:8000/installer 

Please Help me to use PyroCms 3.0
http://www.scriptbazar.com
