### ISSUE TITLE
 [translator-module] untranslatable fields

### ISSUE THREAD

**Issue by kiger** [pyrocms/pyrocms#3773]
I've finished the whole translation, but there are several fields, that's missing, what I've found so far:
The right "View Site", and the whole Logout menu, the search field placeholder, the Help button at the bottom bar. 
![image](https://cloud.githubusercontent.com/assets/2277562/16653108/35f26286-444f-11e6-9af4-2c38e2b2aae5.png)

**Comment by RyanThompson** [comment]
Great! Can you start a markdown compilation list here so I can smash these all out at once?

Have you been submitting PRs for these translations? I've not seen any :-(

**Comment by kiger** [comment]
I'm new to this Github thing, I've sent a PR to the streams-platform with the new language. If it's correct I send the other modules. 

The untranslateble fileds:
-  The right "View Site"
-  Logout (Name Dropdown) 
- Preferences (Name Dropdown)
- Settings (Name Dropdown)
- Search field placeholder
- Help button (Bottom bar)
- The type 'yes' to delete (I think it's nicer to type yes in the current language).

**Comment by RyanThompson** [comment]
It's quite correct aside from the branch you submitted it to - submit to dev and we're good to go! Ill merge it in immediately.

**Comment by RyanThompson** [comment]
Ill also knock these untranslatable out of the way too

**Comment by RyanThompson** [comment]
Done deal - check the pyrocms/pyrocms-theme for these translations
