### ISSUE TITLE
[slug-field_type] Not slugifying when in alternate language

### ISSUE THREAD

**Issue by kiger** [pyrocms/pyrocms#3774]
If I add a new field (for example in the pages module) and I define the field's name in not english language after I save the Name is empty. The name is appear when I define it in english. So basicly the error is the table display's the english name variable, not the selected language.
![image](https://cloud.githubusercontent.com/assets/2277562/16653262/1093d5a0-4450-11e6-84fe-9a5db1eb7f8e.png)

**Comment by RyanThompson** [comment]
In settings try changing your default locale to match your preference and see if that fixes this behavior. It’s likely set as english right now.

**Comment by kiger** [comment]
The default language is the foreign language. If I switch to english it's working perfectly.  Another related issue is when I switch the default locale to foreign locale when I type the nem field the Slug wont generate itself. If I switch back to english Its working nicely.

**Comment by RyanThompson** [comment]
If the default language is set and there is no translation for it - it will not display a value (for example it won't show english if in hungarian and hungarian is default as well - but it WOULD show english if in hungarian and english was the default).

I believe this is all expected behavior but the slug is certainly not - it should translate the default locale - Ill check it out!

**Comment by kiger** [comment]
If I have for example the default language Hungarian and I fill out the name field the slug won't appear, in the other hand if I have English the default language and I fill out the name the slug appear. I think the expected behaviour is that whatever the default language the slug should appear in that language. (The visible field in the table too should the default language)

**Comment by RyanThompson** [comment]
Yep that one is certainly an issue.

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/slug-field_type/commit/14c3f2fcb41da4463652a28af845586ec137e74f
