### ISSUE TITLE
[installer module] Missing database error message in installer.

### ISSUE THREAD

**Issue by dantleech** [pyrocms/pyrocms#3775]
The installer says that the database configuration is invalid, it doesn't say why.

After debugging I found out that it was because the database didn't exist.

**Comment by dantleech** [comment]
Also the sqlite option doesn't work (error: database pyrocms doesn't exist)

**Comment by RyanThompson** [comment]
SQLite won’t work even if the database exists?

Ya it won’t create one for you yet.. Usually it does give you more detailed information in yellow for the database unless there is no exception message. Ill have to check it out - can you give me a step by step to reproduce this?

Thanks!

**Comment by dantleech** [comment]
From what I understand Sqlite shouldn't care if the database exists as it would just autocreate it?

The database error was swallowed here:

https://github.com/anomalylabs/installer-module/blob/master/src/Installer/Form/Validator/DatabaseValidator.php#L45

**Comment by RyanThompson** [comment]
Honestly I am not sure - I've left it to Laravel in that regard (testing connections). The error should be spit back into the flashed messages on screen.

If you create the database yourself and retry - success?

**Comment by RyanThompson** [comment]
Fixed: 

https://github.com/anomalylabs/installer-module/commit/61f523a9f7d3f85e379e42e5a712167a3bc49398

https://github.com/anomalylabs/streams-platform/commit/93fd8ebad69498371c4a74f769df12c4784c65e1
