### ISSUE TITLE
Post Tags

### ISSUE THREAD

**Issue by HiddenTesla123** [pyrocms/pyrocms#3776]
how can i seperate the post tags?
{% for tag in post.tags %}
    <a href="#">{{ tag }}
{% endfor %}

**Comment by RyanThompson** [comment]
Hi! `{{ posts.tags }}` returns the `TagsFieldTypePresenter` so you could do like `{{ posts.tags.labels|join }}` or loop the actual value which is an array with `{{ post.tags.value }}`.

`.value` off a field type presenter will always return the value that the API would normally return from a non-decorated entry.

**Comment by RyanThompson** [comment]
So: 

```
{% for tag in post.tags.value %}
{{ tag }}
{% endfor %}
```
