### ISSUE TITLE
Post Tags

### ISSUE THREAD

**Issue by HiddenTesla123** [pyrocms/pyrocms#3777]
How can I filter the posts when i clicked a certain tag? Only shows post that have the same tag.

**Comment by HiddenTesla123** [comment]
How can i view all of the tags that a certain category of post have? for example the category 'latest-news'. I would to get all of the tags that is used with that category. Then when I clicked a certain tag, the post with that tag will only show. like a filter

**Comment by EnricoVilloteBarandon** [comment]
How can I redirect from http://localhost/posts/2016/06/30/sleep-apnea to http://localhost/posts/tag/DentalNews in <a href="posts/tag/{{tag}}">{{ tag }}</a> ???

**Comment by RyanThompson** [comment]
Hey guys - let's keep non-issue stuff like this in our slack channel. It will help us focus on issues here at Github: http://pyrocms.com/slack

Via controller: posts/tag/translatable
Via plugin: entries('posts').whereLike(tags, foo).get()

Similar for category - also entries(posts).recent.get

@EnricoVilloteBarandon Not sure what you mean - redirects module handles redirects
