### ISSUE TITLE
[Streams Module] Title column missing from GUI

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#3778]
as far as i can tell there is nowhere in the GUI to set the stream title. By default the entry listing just shows "id" - and the id is not even the entry id, it is just the literal text "id".

[Screenshot](https://goo.gl/PO7NT0)

**Comment by RyanThompson** [comment]
Streams Module is pre-release and you are correct, there is no GUI for it just yet. I have some ideas brewing for it's beta that I am still mulling over. I haven't acted on them yet and that's usually because they're not quite fully matured.. Soon though.

**Comment by mattcdavis1** [comment]
ok cool - i'll hold-off on adding any more issues until things are further with development on this.

**Comment by RyanThompson** [comment]
Fair enough - I think the primary missing component is modifying the UI components here - not far away.

**Comment by RyanThompson** [comment]
Huge improvements coming down the pipe for this module. I think you'll like. Closing these for now since they're on my radar.
