### ISSUE TITLE
[Streams Module] No way to change field type in GUI

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#3779]
I don't see any way to change the field type in the GUI - this functionality should be available.  For example, changing a URL field type to a text field type.

**Comment by RyanThompson** [comment]
This isn't supported just yet but will be within a week. Two at the longest. 

Pyro doesn't use an EAV model so it's a little more involved changing field types _sometimes_. I think with recent changes made before 3.0 was released though it should be perfectly doable and clean. So Ill get on it ^_^
