### ISSUE TITLE
Form order by error (create view)

### ISSUE THREAD

**Issue by luisfer7192** [pyrocms/pyrocms#3780]
Hi,
I have a module with out title

TableBuilder
`/**
     * The table options.
     *
     * @var array
     */
    protected $options = [
        'order_by' => [
            'address'
        ]
    ];`

In the table view is all ok

but in the create view show me a error

`Column not found: 1054 Unknown column 'title' in 'order clause' (SQL: select * from `default_brands_contacts` where `default_brands_contacts`.`id` is null order by `title` asc limit 1)`

i put in the FormBuilder the same order by at the $options

`/**
     * The form options.
     *
     * @var array
     */
    protected $options = [
        'order_by' => [
            'address'
        ]
    ];`

Could you help me please.

**Comment by RyanThompson** [comment]
What does the migration look like for the stream?

Can you post the full stack trace as well please?


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by luisfer7192** [comment]
Look the gist, I dont have the title field, I need order this by another field in the create form. 

https://gist.github.com/luisfer7192/dbe8a2ca2969e8b7dfe35fa9f5b81e7f

I hope this show you the error. Thanks!

**Comment by bloveless** [comment]
Try changing the title column in your migration to a field that actually exists in your layout. Right now your title_column is set to "title".

**Comment by luisfer7192** [comment]
Thx, this work for me!

**Comment by bloveless** [comment]
Great! Glad to help!
