### ISSUE TITLE
Stream search rebuild message error

### ISSUE THREAD

**Issue by luisfer7192** [pyrocms/pyrocms#3781]
i build a module and its works perfect.
When i try to rebuild the search show me a error.

<img width="1072" alt="captura de pantalla 2016-07-11 a las 2 25 53 p m" src="https://cloud.githubusercontent.com/assets/13595748/16743852/f20e571e-4773-11e6-83d2-70612122a380.png">

i am doing something bad?.

**Comment by bloveless** [comment]
You'll want something like php ```artisan search:rebuild pages``` but in your case you'll use brands or whatever the name of your stream is.

**Comment by bloveless** [comment]
Just so you know if you use slack there is an active community there that will help you with these issues. http://pyrocms.com/slack

**Comment by bloveless** [comment]
Closing since this is not an "issue".

**Comment by RyanThompson** [comment]
`php artisan search:rebuild namespace.slug` for the record should do it - can’t remember if only namespace works as well for all streams in said namespace.
