### ISSUE TITLE
Time and Date format not working

### ISSUE THREAD

**Issue by kiger** [pyrocms/pyrocms#3782]
The time and date format in the settings wont affect the other inputs for example in the Blog module.

**Comment by RyanThompson** [comment]
Fixed! 

https://github.com/anomalylabs/streams-platform/commit/a6e7a2446e15d707eaa0367450021a95db67cec5

https://github.com/anomalylabs/streams-platform/commit/a6e7a2446e15d707eaa0367450021a95db67cec5
