### ISSUE TITLE
wysiwyg > Edit Link > Can't Save URL

### ISSUE THREAD

**Issue by liuflowt** [pyrocms/pyrocms#3784]
url is invalid but it is valid when URL is ending with .html or .etc...

![image](https://cloud.githubusercontent.com/assets/20101964/16787774/9299996a-48d1-11e6-8b33-7bdecd6a2de8.png)

**Comment by RyanThompson** [comment]
This is a functionality bound with Redactor - I don't see how to remedy it at the moment based on their configuration / API. Considering this is an issue in specific development only environments Ima go ahead and close er down. Hopefully they patch this - maybe submit a issue to them. Normal dev hosts like dev.local or something also work fine.
