### ISSUE TITLE
[Users Module] - View [message.reset] not found.

### ISSUE THREAD

**Issue by aidanwatt** [pyrocms/pyrocms#3786]
I think there is a problem when initialising a password reset via /users/password/forgot

Doesn't seem to find the view for the email:

>InvalidArgumentException in FileViewFinder.php line 137:
>View [message.reset] not found.

If I move message/en/reset.twig to message/reset.twig works okay.

Cheers

**Comment by RyanThompson** [comment]
Composer update - someone else pointed this out to me yesterday and I fixed it last night ^_^

**Comment by aidanwatt** [comment]
Hey Ryan

Yeah had updated, still got the same error though.

**Comment by RyanThompson** [comment]
You're up to date with this?

https://github.com/anomalylabs/streams-platform/commit/d6bf0cd8c37828f5df4b8ae1b1a3ee13df256423

**Comment by aidanwatt** [comment]
Yeah

**Comment by RyanThompson** [comment]
Can you plop dd(get_class(app(‘mailer’))); in any ole controller and tell me what you get?

**Comment by aidanwatt** [comment]
It's 'Illuminate\Mail\Mailer', that's me being dozy again, we have a custom module that's setup that's providing 'Illuminate\Mail\Mailer' so will be overriding yours! Sorry for the time wasting :$

**Comment by RyanThompson** [comment]
LOL no worries. Glad I can say it wasn’t me ^_^

Try extending mine in the core - I added translatable messages
