### ISSUE TITLE
Seed unlocked fields should allow null.

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#3787]
When seeing an unlocked field I.E.
```
        'name'    => [
            'type'   => 'anomaly.field_type.text',
            'locked' => 0,
            'en'     => [
                'name'         => 'Name',
                'placeholder'  => '',
                'instructions' => '',
                'warning'      => ''
            ]

        ],
```

placeholder, instructions, and warning have to be an empty string or they will get a translation string rather than an empty string. This should work with null also.

**Comment by RyanThompson** [comment]
Note to self: change tests to isset() instead of the null / ! value checks (migrations)

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/bfe68a37387b0d292bc147756dd0150632d6ad95
