### ISSUE TITLE
[Files Module] Overwriting and image does not update its attributes.

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#3789]
I.E. Overwriting an image with the same file name doesn't update it's size. It is still showing me the size of the original image though when I download the image it is the correct (new) size.

**Comment by RyanThompson** [comment]
What no PR? lol

**Comment by bloveless** [comment]
LOL! I just wanted to write it down so I wouldn't forget. I will certainly PR it later! Still have a job I don't want to lose lol!

**Comment by bloveless** [comment]
Beat me by a minute!
