### ISSUE TITLE
Too many files open on page type save... Sometimes.

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#3790]
I'm not sure if this is something that needs to be fixed, but sometimes when I try to update a page type (change the layout) I get this error

[Mon Jul 18 21:28:22.008063 2016] [:error] [pid 2628] [client ::1:53751] PHP Fatal error:  Uncaught ErrorException: include(/Users/brennon/Projects/php/verticalsolns.dev/vendor/symfony/debug/Exception/FatalErrorException.php): failed to open stream: Too many open files in /Users/brennon/Projects/php/verticalsolns.dev/vendor/composer/ClassLoader.php:412\nStack trace:\n#0 /Users/brennon/Projects/php/verticalsolns.dev/vendor/composer/ClassLoader.php(412): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'include(/Users/...', '/Users/brennon/...', 412, Array)\n#1 /Users/brennon/Projects/php/verticalsolns.dev/vendor/composer/ClassLoader.php(412): include()\n#2 /Users/brennon/Projects/php/verticalsolns.dev/vendor/composer/ClassLoader.php(301): Composer\\Autoload\\includeFile('/Users/brennon/...')\n#3 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Symfony\\\\Compone...')\n#4 /Users/brennon/Projects/php/verticalsolns.dev/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(131): spl_autoload_call('Symfony\\\\Compone...')\n#5 /Users/brennon/Projects/php/vertic in /Users/brennon/Projects/php/verticalsolns.dev/vendor/composer/ClassLoader.php on line 412, referer: http://verticalsolns.dev/admin/pages/types/edit/2

Too many files open.

**Comment by RyanThompson** [comment]
Open this up if you have anything more on this. If I recall we solved this outside of GitHub.
