### ISSUE TITLE
Header Sections

### ISSUE THREAD

**Issue by kiger** [pyrocms/pyrocms#3792]
I'm nearly finished building a left-menu Admin Theme based on AdminLTE, I have only one question, is there a way to get all section to generate the menu with the full structure?
I know, to get the current sections the code is {% for section in template.cp.sections.root() %}
but there is a method to get all the sections?

Thanks
![image](https://cloud.githubusercontent.com/assets/2277562/16952734/c1d2134e-4dca-11e6-8ae1-d574887c061c.png)

**Comment by RyanThompson** [comment]
Looks good! I really wish you would have simply contributed a left menu layout to Pyro lol.

You can get sections off each module like module.sections - but they will be unprocessed.. So in short, not really no. Not at this time.
