### ISSUE TITLE
[ Navigation module ] Missing field when creating menu

### ISSUE THREAD

**Issue by ChristianGiupponi** [pyrocms/pyrocms#3793]
I have used italian language as main language and I have remover the english from the **Enabled Languages** 

![schermata 2016-07-20 alle 10 58 48](https://cloud.githubusercontent.com/assets/1614796/16981014/fe7fdcb0-4e68-11e6-865d-1c70a4ca37d8.png)

Now if I visit the Navigation module and try to create a new menu I can't see the default fields:

![schermata 2016-07-20 alle 11 00 07](https://cloud.githubusercontent.com/assets/1614796/16981048/2a6d89b2-4e69-11e6-94df-c40bf52fdc93.png)

Anyone can confirm the issue?

EDIT:  
I have found out that if you do not set english in the enabled languages the fields do not shows up

**Comment by RyanThompson** [comment]
This has been resolved.
