### ISSUE TITLE
Created project via composer but unable to install

### ISSUE THREAD

**Issue by techsandeep** [pyrocms/pyrocms#3794]
Hi 

I created a pyrocms project(Laravel Version) via composer and its downloaded all dependencies but when i am running http://localhost/pyrocms/public/ url its redirected to http://localhost/pyrocms/public/installer with 500 error I checked public directory and that is missing installer directory.

Please help how to install.

**Comment by RyanThompson** [comment]
Hi! You won't see an install directory that's a slug used in pretty URLs. 

What do your server logs say about the errors?

**Comment by hermawan-fsi** [comment]
i have the same too. error 404 even i had chmod folder 
fyi, i used php7,nginx

**Comment by RyanThompson** [comment]
Sounds like pretty URLs (see Laravel docs) are not setup. 

Does /index.php/installer work?

**Comment by hermawan-fsi** [comment]
thanks for reply my comment. 
i have got in here http://docs.pyrocms.com/2.2/manual/guides/pyrocms-urls#404-page
but still can not figure it out what happen.

this articles mentions 
404 Page
All pages that are not found in PyroCMS are routed to the Pages module, where a special 404 page handles them. This page simply has to have a slug of 404, and PyroCMS will use it as the 404 and set the correct 404 headers accordingly.

**Comment by techsandeep** [comment]
My URL http://localhost/pyrocms/public/installer display 500 error then I tried localhost/pyrocms/public/index.php/installer but getting same error

**Comment by RyanThompson** [comment]
Those docs are 2.2 you're referencing the installation for 3.0. What do your Laravel logs say or maybe your server error logs?

**Comment by hermawan-fsi** [comment]
this is from /var/log/nginx/error.log

2016/07/26 12:31:03 [error] 4201#4201: *70 directory index of "/var/www/html/alpha/pyrocms/" is forbidden,

this is my nginx.conf
root /var/www/html/alpha/pyrocms;

when i am running laravel is work in here 
http://bataviaresources.com/laravel/public/

**Comment by techsandeep** [comment]
Hi Ryan I am trying to install pyrocms 3 and i checked my error_log flie in root its blank.

**Comment by RyanThompson** [comment]
@techsandeep then your error will be in your PHP / Apache / NGINX logs. Should be self explanatory from there but if it's something fishy let us know and we can get it sorted out for you ^_^

**Comment by techsandeep** [comment]
I am installing on localhost(wamp server) on window machine.

**Comment by techsandeep** [comment]
Following are my .htaccess file 
ROOT -> 
  <IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteBase /pyrocms/
</IfModule>

PUBLIC ->

<IfModule mod_rewrite.c>
	Options +FollowSymLinks
	RewriteEngine On
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteRule ^ index.php [L]
</IfModule>

**Comment by RyanThompson** [comment]
What does your server error log say?

**Comment by RyanThompson** [comment]
If there is still an outstanding issue here please open er back up!

**Comment by ghost** [comment]
Same problem here, tried everything without success. (personnally, I don't have index.php file in my root of pyrocms folder), so localhost/index.php/installer don't work
