### ISSUE TITLE
[Posts-Module] -- Breadcrumbs for posts arn't being passed through to the page within {{ template }}.

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#3798]
In the route of the posts module you get the breadcrumb `posts`. However, all child pages the breadcrumbs don't work.

From troubleshooting, breadcrumb calls are set in the postsController, if you DD template in here the breadcrumbs are set correctly, however they are not rendering on pages at all.

there is no breadcrumb logic set in MakePostResponse.

**Comment by RyanThompson** [comment]
Fixed
