### ISSUE TITLE
[settings-module] Should be multilingual

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#3800]
Explore this.. but should be totally doable.

**Comment by PMK** [comment]
Is this referring to the "content" field to be multilingual?

![example](https://cloud.githubusercontent.com/assets/355176/19348657/481ed4ba-914f-11e6-9d85-3a5f46ca5ee6.png)


On the other note, do you have maybe a clue how I can have multilingual uri for pages and posts?

**Comment by RyanThompson** [comment]
Content field CAN be multilingual but it’s not seeded in that way. Delete it / reassign if you want.
