### ISSUE TITLE
Admin Dashboard > Alert Message

### ISSUE THREAD

**Issue by liuflowt** [pyrocms/pyrocms#3803]
![image](https://cloud.githubusercontent.com/assets/20101964/17388758/c8cb024c-5a30-11e6-975a-abaa03bbb661.png)

I open two different tab. During saving the page type I switch the browser tab and notice that the message was combine.

**Comment by RyanThompson** [comment]
Sessions are shared across browser tabs. I wouldn't consider this is a bug ^_^
