### ISSUE TITLE
ErrorException in metadata.twig

### ISSUE THREAD

**Issue by tymon82** [pyrocms/pyrocms#3804]
Got this error after running installer:
ErrorException in metadata.twig line 24: An exception has been thrown during the rendering of a template ("fopen(php://stderr): failed to open stream: operation failed") in "theme::partials/metadata" at line 24.

**Comment by RyanThompson** [comment]
Does refreshing fix it? Sounds that that is a server config issue but probably caused by another error.. Not sure what it would be though that line is an asset function..

Any more information on server / Laravel logs?

**Comment by tymon82** [comment]
Nope, refreshing do noting
[laravel-2016-08-07.txt](https://github.com/pyrocms/pyrocms/files/405720/laravel-2016-08-07.txt)

**Comment by RyanThompson** [comment]
Is this still giving you problems? I think this is kinda more related to a PHP config / environment issue: https://www.google.com/search?q=php%3A%2F%2Fstderr&oq=php%3A%2F%2Fstderr&aqs=chrome..69i57j69i58.217j0j7&sourceid=chrome&ie=UTF-8#newwindow=1&q=php:%2F%2Fstderr+error
