### ISSUE TITLE
Getting There was an error. Please check your error logs while installing

### ISSUE THREAD

**Issue by rgogulakrishnan** [pyrocms/pyrocms#3805]
Hi, i guess this error already reported once but im unable to see any solution over there..

After composer create project, installation throws this error.. 

error log has the below

```
[Mon Aug 08 22:33:18.890258 2016] [:error] [pid 3864:tid 1872] [client 127.0.0.1:52603] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in C:\\Data\\xampp\\htdocs\\pyrocms\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php on line 390, referer: http://pyrocms.dev/installer/install
```

Using xampp in local..

**Comment by RyanThompson** [comment]
This is a pretty straight forward issue with your php timing out. Configuration might help. I'm assuming it's related to initia asset compilation since it's kinda heavy.

**Comment by RyanThompson** [comment]
This is a pretty straight forward issue with your php timing out. Configuration might help. I'm assuming it's related to initia asset compilation since it's kinda heavy.

**Comment by rgogulakrishnan** [comment]
increasing max_execution_time in php.ini resolved the issue.

**Comment by RyanThompson** [comment]
Excellent!
