### ISSUE TITLE
Resources generated with index.php

### ISSUE THREAD

**Issue by callum-jh** [pyrocms/pyrocms#3808]
When i login to the admin area some resources don't load

`http://example.com/index.php/app/company/assets/core/pyrocms/pyrocms-theme/resources/img/icon-dark-transparent.png 404 (Not Found)`

List of files that dont load are

- proximanova-regular-webfont.woff
- icon-dark-transparent.png
- fontawesome-webfont.woff2 
- proximanova-regular-webfont.ttf
- fontawesome-webfont.woff
- fontawesome-webfont.ttf  

If i request these urls without index.php the resources load correctly.

Im using Nginx and 3.0 master branch

**Comment by RyanThompson** [comment]
Looks like you need to remove index.php from your domain in `.env`

And configure pretty URLs per Laravel documentation as well if not already ^_^

**Comment by callum-jh** [comment]
My .env file shows 

APP_URL=http://example.com
APPLICATION_DOMAIN=example.com

In my Nginx conf i have

try_files $uri $uri/ /index.php?$query_string;

Is there any caching?

**Comment by RyanThompson** [comment]
Interesting.. What is the URL you are using to access the site? The Control Panel for example, what URL do you have for that?


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by callum-jh** [comment]
I just access it through http://jewelhost.co.uk/admin

**Comment by RyanThompson** [comment]
Ok.. the URL generator in Laravel is picking up index.php for some reason.

There is a cache though - try `php artisan asset:clear`

If it persists here are some places to sniff around: 

That file is located at: core/pyrocms/pyrocms-theme/resources/scss/theme/layout/_brand.scss

Does the image include look like this:

`background-image: url("{{ image_path('theme::img/icon-dark-transparent.png') }}");`

Which prefixes with: https://github.com/anomalylabs/streams-platform/blob/master/src/Asset/AssetPaths.php#L190

**Comment by RyanThompson** [comment]
The cache should clear with changes in request information like that but that might be it.

**Comment by RyanThompson** [comment]
Is this still an issue on updated Pyro?
