### ISSUE TITLE
[settings-module] and [preferences-module] do not respect permissions

### ISSUE THREAD

**Issue by haeflimi** [pyrocms/pyrocms#3809]
I've just set up a fresh installation of pyro to have a look at what's changed since i last checked in and did some playing around.

One thing i wanted to test is this:
Can i grant a user access to the control panel but make him unable to do any damage to the site by just using the permissions available?

So i did the following:
- created a new role
- stripped the new role of any permissions available only leaving "Can access the control panel?" and "Can access dashboards section." activated.
- created a new user and assigned the role, removing all others
- log in as the new user

At fist glance all seemed to be working as i expected:
- Navigation all neat and clean, only showing the dashboard
- Trying to access a few modules over the direct url -> getting a 403, Great!

But in the User dropdown in the far right corner i can still access "Prefferences" and "Settings" and even sidestep into other menues via the sub- navigation. Even changes to things like Site Name and Site Description are possible there.

There are Options for these things in the Permissions List (Can manage system settings? and Can create and edit preferences?) and i've tripple checked that i removed those, but they don't seem to have the intended effect.

I have the feeling that it's not supposed to be like that.

**Comment by RyanThompson** [comment]
Fixed. Leaving it as a module wide permission cause idk how I want to drill down just yet.

https://github.com/anomalylabs/settings-module/commit/b0fa7af2eb6c59d71d89ff418f962fb1a041caf8

https://github.com/anomalylabs/preferences-module/commit/6d96abfb5f02013a10c68368ae1e7b7e5c475a17
