### ISSUE TITLE
[forum-module] -- When you register it should redirect to forum not home

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#3817]
When you register or the forum module you should redirect back to the `/forum` page not the home page. Extra navigation is useless

**Comment by RyanThompson** [comment]
Hmm.. good call.

**Comment by RyanThompson** [comment]
Fixed out of the box behavior which is what the site uses: https://github.com/anomalylabs/users-module/commit/c81f35e4194dba79f78ccb94f77fa771ac6d84b8
