### ISSUE TITLE
v3.0 - 404 on Installer

### ISSUE THREAD

**Issue by jzalenski** [pyrocms/pyrocms#3821]
I'm trying to install Pyrocms, downloaded with composer. Currently running a LEMP stack with PHP7.0.9. Nginx *seems* to be working in this instance, but I am only seeing a server-level 404 when I attempt to navigate to the installer via my domain. 

I say it *seems* to because I'm at least being redirected to "http://domain/installer" when I receive the error, but I can't tell if there are additional parameters required for working with Pyrocms I'm missing in the conf. 

Laravel (alone) seems to work fine, at least at a base level ( I installed only to test against pyrocms to see if I could deduce the problem) with the same exact conf setup. Root is set to "install_directory/public" for both.

Adding */index.php/* does not change a thing. Please let me know if there is additional documentation somewhere about using v3.0 with Nginx, or something I'm missing.

**Comment by RyanThompson** [comment]
Can you 777 your storage/ and public/app folder for the sake of testing? Usually permissions is the culprit if the server rewriting is not.


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by jzalenski** [comment]
Hi Ryan,

All directories have already been set to 777 during this process. As I noted the Pyrocms installation instructions warnings about permissions, I did this the moment I noticed an issue. 

All directories were also set with correct permissions (owned by web server, 777) prior to installing with Composer.

Odd problem, hope there is an easier way to tease out the source of it. I was getting some Nginx errors early on, but not anymore after pointing everything to the correct location and clearing caches in artisan.

Again, I apologize if I'm missing something simple - I have yet to work much with Laravel.

**Comment by RyanThompson** [comment]
Unfortunately Im unsure of where your configuration went wrong but it sounds like rewriting. If your configuration is rewriting for Laravel correctly then PyroCMS will work just fine. 

It should be rewriting /index.php/installer to /installer for example. 

Your web root should be /your-pyro-site/public/ - can you confirm that as well?

**Comment by RyanThompson** [comment]
Did you get this sorted out?

**Comment by jzalenski** [comment]
Hello Ryan,

No, I haven't had time to address it. At last attempt, I made some changes
with NGINX, but it only resulted in the installer being downloaded via the
browser when I attempted to navigate to the page it was meant to be hosted
on.

Let me know if you receive any related or relevant complaints that were
successfully resolved. This is a personal project I may elect to put on
hold, or try another avenue with.

**Comment by RyanThompson** [comment]
This sounds increasingly like classic NGINX misconfiguration. Google hunting (Laravel has tons of references out there on it too) should get you set up. "How to configure NGINX for Laravel" for example should do the trick.

I am going to close this for now because it would appear to be unrelated. If the problems persist and especially if it's Pyro related I'll be obliged to reopen and dig in!

Cheers,


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581
