### ISSUE TITLE
[Form Builder] Ajax option

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#3822]
We talked about the protected $ajax = true option in the form builder.

I think it would be super helpful if the dev could set protected $ajax = true; and then form would return the response from a new public function toJson(FormBuilder $builder) method rather than the actual form response.

One think to keep in mind is the form needs to validate and return validation information if the form is in error.

I always prefer to have json responses in the form of
```
{
   status: 'success', // or error
   data: [] // or whatever. The data is
}
```
But really the response can just be anything json oriented, but I'd like to be able to return the data that was just created so I can append it or whatever.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/issues/290

**Comment by RyanThompson** [comment]
Can't say I never did anything for ya: https://github.com/anomalylabs/streams-platform/commit/bc8baf289c0fc916a8be26425767041effce138f
