### ISSUE TITLE
 [addons-module] --  Uninstall should have "Type module slug" or something to confirm the uninstall

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#3828]
Eg, when you delete something in modules you get a confirmation to type `yes` to confirm.

Case: You want to delete `settings` in the gui. you click uninstall `addons` instead, the confirmation would say type `addons` to confirm, then you will see, shit, I clicked the wrong one.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/addons-module/commit/12cf7428749b185c6e1734454dca1b30d3c8f5d5
