### ISSUE TITLE
Always error on migration

### ISSUE THREAD

**Issue by juanrhino** [pyrocms/pyrocms#3830]
Every time that I make the first migration is always sending a primary key error and sometimes when I tried again, it tells me that everything is fine but the main page sends this error:

Call to a member function uri() on null in /Users/juan/Documents/TypiCMS/test/storage/framework/views/abf063477cd91d8bd3e9316e6d011bf369b1ce3a.php on line 17

**Comment by RyanThompson** [comment]
Hmm your path there shows typicms? Are you in the right place?
