### ISSUE TITLE
Creating a new user in admin

### ISSUE THREAD

**Issue by websemantics** [pyrocms/pyrocms#3831]
That's odd behaviour, any idea why?!

![27458f60-2f3a-4d29-ab35-02d55fb846d1](https://cloud.githubusercontent.com/assets/2190455/18279213/c36df8c0-7422-11e6-922d-bb7e9fc3d2cd.png)

**Comment by RyanThompson** [comment]
Looks like it was the tags input mode: https://github.com/anomalylabs/multiple-field_type/commit/b2146b1df23da19e8c68371ec6ef9cdf6ebe404f
