### ISSUE TITLE
[pages-module] Identifier name is too long

### ISSUE THREAD

**Issue by HolyMarcell** [pyrocms/pyrocms#3843]
Hi,

I came across this lovely error-message today:

> QueryException in Connection.php line 761:
> SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'pages_mainpage_pages_leftblock_lower_teaser_entry_id_file_id_primary' is too long (SQL: alter table `pages_mainpage_pages_leftblock_lower_teaser` add primary key `pages_mainpage_pages_leftblock_lower_teaser_entry_id_file_id_primary`(`entry_id`, `file_id`))

This happened when I tried to assign a field to a pagetype. There seems to be a 64-Char-Limit to these ID's in MySQL which I easily broke with my second Field-Type ;) 

I guess it won't be practical to redo the whole database-id-naming-scheme but maybe you can add a limit/warning to the slug field when creating a Field that maybe 

"leftblock_lower_teaser" 

is too long? 

The whole key "pages_mainpage_pages_leftblock_lower_teaser_entry_id_file_id_primary" is 68 chars long and the part I can manipulate is 22 chars long that leaves me in this example to choose a slug that is maximum 18 characters long, but this might differ.

Regards, 
HolyMarcell

PS: Just food for thought:

A much longer wordspan might be needed for diffrent languages. You know how the germans have these neverending words ;)

**Comment by RyanThompson** [comment]
This has been fixed just recently - didn't see this as a duplicate issue.
