### ISSUE TITLE
[wysiwyg-field]

### ISSUE THREAD

**Issue by HolyMarcell** [pyrocms/pyrocms#3844]
Hi,

when editing a page and producing an error - maybe I didn't fill out a required field - the contents of a WYSIWYG-Field aren't preserved.

Regards,
HolyMarcell

**Comment by HolyMarcell** [comment]
Disregard that: Somehow after I fixed the "error" the contents of the WYSIWYG-Fields reappeared. Might be a glitch.

**Comment by RyanThompson** [comment]
Only time I've seen this happen is when the file system (virtual) and the database (on the original machine) have been on different TZs / machines technically. There is some time comparison going to to figure out whether the dump file or the database is "true" for those field types (editor, wysiwyg, and markdown). They all dump a file that's listed under the input as a full path. When you edit that file - your DB is synced automatically to keep your changes in the system. And vice versa of course.

Lesson for the day ^_^
