### ISSUE TITLE
[streams-platform] Automatic metadata / breadcrumb would be epic

### ISSUE THREAD

**Issue by daviesgeek** [pyrocms/pyrocms#3846]
Pretty simple, just like the way that module names are set in the lang files, do the same for page titles and metadata…

**Comment by RyanThompson** [comment]
This is so easy as it is - the collections are even available directly on the controller. On top of that builders automate this already cause they have the structure to support it. I could see this being a mess outside of something with as much structure / guidance as a UI builder. Closing er down! Sorry man.
