### ISSUE TITLE
[Bug Report] .env LOGIN=username not working

### ISSUE THREAD

**Issue by onyxg** [pyrocms/pyrocms#3849]
appears user-module setting LOGIN type email/username does not take effect.
**Compare:**

user-module / Login / LoginFormBuilder @ line 23
`$method = $config->get('anomaly.module.users::config.login');`
form correctly picks up username and validates login using a "username" however the form is displaying the email field type and requires a valid email... (HTML5 client side email validation)

user-module / view / login @ line 19 is not pulling the correct setting.
`{% if setting_value('anomaly.module.users::login') == 'username' %}`
returns email - have tried setting_value('anomaly.module.users::config.login') without any luck.

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/default_authenticator-extension/commit/412a285c19635c411ed400a6c97df6bee9ca66a7
