### ISSUE TITLE
Removing an asset that is referenced breaks the whole parsing.

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#3851]
If the parse can't find an asset it just stops parsing, instead of skipping over it and continuing on it just breaks and doesn't parse anymore.

**Comment by onyxg** [comment]
hay edster, 
I think the question we need to ask is - should it be a soft or hard fail?
Additionally I feel we need to factor in want type of asset and where is it being used, ie: theme/ stream/ page content etc.
like I would think a stream not having an image assigned to an image field type should fail softly, but the system not able to find an image/css/js file in the main theme should hard fail - as those assets must exist and are set/built by the developer (hard fail), whereas stream stuff is user maintained and we shouldn't break that (soft fail) - just thinking of the end user.

**Comment by bloveless** [comment]
I agree with this. I think that theme files are a developers responsibility and should fail hard, at least when debug mode is enabled. And since populating addon content is an end user responsibility they should fail softly.

**Comment by RyanThompson** [comment]
Soooo... good?

**Comment by RyanThompson** [comment]
I haven't noticed any oddities in missing assets (seems somewhat forgiving to me). Closing for now.
