### ISSUE TITLE
Upgrade excerpt to strip tags

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#3852]
As discussed on slack look at improving excerpt to strip tags.

**Comment by RyanThompson** [comment]
@edster looks like the presenter methods are indeed stripping tags where did you see this behavior?

**Comment by edster** [comment]
I was using
`{{ staff.bio.excerpt(200, '...') }}`
But that was giving me display issues because tags were not being stripped and breaking my layout.

Started using this `{{ staff.bio.excerpt(200, '...')|stiptags|raw }}` but shit like `&nbsp;` would show, but the layout tags wouldn't break for w.e. reason.

**Comment by RyanThompson** [comment]
What's `bio`? WYSIWYG?

**Comment by edster** [comment]
Excellent question!

Yes `'bio'   => 'anomaly.field_type.wysiwyg',`

**Comment by RyanThompson** [comment]
Hmmmm https://github.com/anomalylabs/wysiwyg-field_type/blob/master/src/WysiwygFieldTypePresenter.php#L138-L152

**Comment by RyanThompson** [comment]
Calling bull honky. Reopen if you have a better example Its working on this end :-/
