### ISSUE TITLE
[Posts / Pages] Lang switcher bug

### ISSUE THREAD

**Issue by AkibaTech** [pyrocms/pyrocms#3856]
Hi!

When creating (or editing) a page (or a post) on a fresh installation with 2 lang configured, once the lang switched, you can't switch back to the first language as you can see on the two screenshots.

![capture d ecran 2016-09-19 a 09 35 08](https://cloud.githubusercontent.com/assets/1665333/18625162/ef7c7962-7e4c-11e6-83a3-a383aa38f4a5.png)
![capture d ecran 2016-09-19 a 09 35 13](https://cloud.githubusercontent.com/assets/1665333/18625161/ef79f412-7e4c-11e6-8173-d701523b2da9.png)

**Comment by RyanThompson** [comment]
If you can get me a step by step to reproduce but I was not able to do so. Closing for now.
