### ISSUE TITLE
While Installing PyroCMS Error

### ISSUE THREAD

**Issue by krunaltasolglobal** [pyrocms/pyrocms#3858]
I am getting following error while installing pyroCMS

`local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Uncaught exception 'Twig_Error_Loader' with message 'Template "theme::errors/500" is not defined.' in /var/www/html/pyrocms/vendor/twig/twig/lib/Twig/Loader/Chain.php:115`

**Comment by RyanThompson** [comment]
Hmm.. what else is in your Laravel logs? `storage/logs/`

There will be something else in there that causes the error view to be required at all.

Is this during the process or after submit or when exactly is this?

**Comment by haeflimi** [comment]
I am having the same Issue.
It's during installation. After the progress Bar filled up for the first time a Popup appears and states: 
> There was an error. Please check your error logs.
The installation stops there and does not seem to be finished.

I've included my log file. Had it cleared beforehand, so it contains only the stuff that mathers for this Issue. Still pretty extensive though.

[laravel-2016-09-21.txt](https://github.com/pyrocms/pyrocms/files/483799/laravel-2016-09-21.txt)

**Comment by krunaltasolglobal** [comment]
@RyanThompson it's come during the installations process..

**Comment by haeflimi** [comment]
For me it works again since i've dumped my Homestead development Box in favour of a local Server Setup using [Laragon](laragon.org).

Since i'v also completly reinstalled all the dependencies it might be possible this didn't solve the issue but one of the, meanwhile updated packeges, did. Hard to tell.

**Comment by RyanThompson** [comment]
Closing this for now - if anyone has some error logs / details to share I can dig into it more.
