### ISSUE TITLE
Page-module

### ISSUE THREAD

**Issue by dummyusers** [pyrocms/pyrocms#3860]
When i view and delete the page, I've notice that the parameter id is incorrect. It gets the entry_id instead the page id. I'm about to move my website to production. Can someone help me.  Im using the latest version

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/pages-module/commit/73bae8f3e41052e1e6e6ac45ff24817aae6764fa

**Comment by RyanThompson** [comment]
Fixed for posts / documentation modules as well. Good catch!
