### ISSUE TITLE
[files-module] Assigning Field breaks "Edit" links

### ISSUE THREAD

**Issue by HolyMarcell** [pyrocms/pyrocms#3861]
Hi,

- working on Images folder in the files module

Assigning a Text-Field (caption for a slider) to the images folder yields strange results. After adding the text to an image the "Edit" and "View" links to the file sometimes get corrupted and point to other files e.g.

File ID 12:
[Edit] links to [..]/edit/7

This does happen to random images, sometimes not even the one that was edited. The images still get displayed correctly but the assigned caption sometimes is saved, sometimes not.

------

Possible other reason: Filename-length. My lovely coworker has uploaded some images named:

"stock-photo-cropped-image-of-a-doctor-working-on-his-digital-tablet-he-is-showing-digital-tablet-with-blank-355433666.jpg"

and others like it.

Regards,
HolyMarcell

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/files-module/commit/5d0099fed63fa9fac544fe1f13a552e600e4f4b7 <https://github.com/anomalylabs/files-module/commit/5d0099fed63fa9fac544fe1f13a552e600e4f4b7>

This is the same as what was recently found in pages / posts. Merged IDs were clashing.
