### ISSUE TITLE
Admin design font characterset

### ISSUE THREAD

**Issue by kiger** [pyrocms/pyrocms#3862]
The default Admin Theme font Proxima Nova won't have the latin extend characters (example őű) etc.

![image](https://cloud.githubusercontent.com/assets/2277562/18788149/1bc0929a-81a6-11e6-8d18-b5f9fc166799.png)

**Comment by RyanThompson** [comment]
Hmm.. thoughts? Seems there is a lot of movement towards native font sets.

**Comment by kiger** [comment]
I switched to Open Sans (https://github.com/FontFaceKit/open-sans), it has all the latin and latin extend characters, and  I think looks nice in this design.

**Comment by huglester** [comment]
GitHub does this: font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";

**Comment by RyanThompson** [comment]
I like that ^

**Comment by RyanThompson** [comment]
https://github.com/pyrocms/pyrocms-theme/commit/279c9902fed38360201c4515441bd12f475d3413
