### ISSUE TITLE
Problem re-creating post types (and posts) already deleted

### ISSUE THREAD

**Issue by kimse1** [pyrocms/pyrocms#3865]
When I delete a post type I can't create a new one with same slug. It says it's already taken.

Same goes for post if there were any using the post type.

1. Create a post type and slug it: "test-post-type"
2. Create a new post and slug it "my-post" with the "test-post-type"
3. Delete the "test-post-type" post type
4. Try create a post type with same slug: "test-post-type"
5. Try create a post type with same slug: "my-post" (doesn't matter which post type you choose)

**Comment by bloveless** [comment]
Do you get a message about something being in the trash? Make sure that after you delete a post or a page that you also delete it from the trash.

**Comment by kimse1** [comment]
Damn I feel stupid, didn't even notice that PyroCMS had trash feature now. Anyway, maybe the deleted message should be changed to something like "1 row(s) were trashed successfully." instead.
