### ISSUE TITLE
[installation] doesn't allow empty db password

### ISSUE THREAD

**Issue by chriscubos** [pyrocms/pyrocms#3867]
returns: [ERROR] A value is required.

**Comment by RyanThompson** [comment]
This error is coming from the database. Can you try commenting out this line and seeing if it works?

https://github.com/anomalylabs/installer-module/blob/master/src/Installer/Form/Validator/DatabaseValidator.php#L38

**Comment by huglester** [comment]
I tried empty password (it allowed it, saved the config) and I got 500 error (since on localhost I require password)
later I needed to edit .env file and set VALID DB_PASSWORD, to pass the '500' error

**Comment by RyanThompson** [comment]
I think this was a DB issue reporting back to you - I can install without password. Open back up it you have more information.
