### ISSUE TITLE
Wysiwyg form field is showing the twig path when outputting the form in the client.

### ISSUE THREAD

**Issue by ThinkGraphical** [pyrocms/pyrocms#3869]
When outputting a form in the client,
the twig path is showing at the bottom of the wysiwyg field.

This is handy when in development, but end-users don't need this information.

Possible solutions:
- Only show the field when APP_DEBUG=true
- Only show the field when the logged-in user is an Admin, SuperAdmin
- Adding a extra option 'show_path'

**Comment by huglester** [comment]
And probably best would be, if, for example we have field type 'text', but we could override 'frontend' with different views, as well as backend.

**Comment by RyanThompson** [comment]
@huglester that's already very possible. You can override any view.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/wysiwyg-field_type/commit/81309bf3c8b492d59c2bbc29bdf54b6ff0515abe

Also updated markdown and editor types.
