### ISSUE TITLE
V3: Assets not being precompiled in themes

### ISSUE THREAD

**Issue by mikey0000** [pyrocms/pyrocms#3872]
I've followed the documentation on creating a theme and my scss files are not being converted to css
```
{{ asset_add("theme.css", "theme::scss/app.scss") }}
```

the scss file has 
```
@import "bourbon";
@import "bourbon-bitters";
```
these are from node_modules

**Comment by mikey0000** [comment]
I ended up installing them in the directory which worked but node_modules should also work IMO. If you feel this isn't the case, close the issue. Of course I could have directly done a path to them but again I think its pretty standard that node_modules is within path.

**Comment by RyanThompson** [comment]
`node::` is a registered asset prefix:

    $asset->addPath('node', base_path('node_modules'));
