### ISSUE TITLE
[Feature Request] artisan installer command

### ISSUE THREAD

**Issue by theshaunwalker** [pyrocms/pyrocms#3874]
It would be great if there was an installer command we could run instead of navigating to `/installer` in the browser. Instead of using the web form we could pass command arguments or pre-populate the .env file with our desired settings.

This will help with automating deployments as currently it still requires the manual step of going to the browser to run all the installers.

Cheers!

**Comment by bloveless** [comment]
I believe you are looking for "php artisan install"

**Comment by theshaunwalker** [comment]
@bloveless ah didnt see that! Thanks!

**Comment by bloveless** [comment]
Not a problem!
