### ISSUE TITLE
[streams-platform] Foreign keys are not enforced

### ISSUE THREAD

**Issue by pepijnolivier** [pyrocms/pyrocms#3877]
When I create 2 streams, one with a relation to the other, I notice that foreign keys are not enforced on the database level.

**Ryan Thompson**:

> For exactly this reason:
> 
> **It should also be noted, that data, which serves as a foreign key in one record, cannot be removed if there is another record that assumes its existence.
> From MySQL docs.**
> 
> Relationships are not always a hard coupling. And should be loosely defined. Allowing another to be deleted without enforcement.
> That said. There could be a config option that causes this kind of key binding.

I understand that enforcing foreign keys on the database level can prevent certain data from being added, deleted or updated, and I am convinced that this is a good thing. Ghost records or invalid relations shouldn't ever exist, and by enforcing foreign keys, the database will be cleaner in the end.

By utilizing foreign keys, we could also implement clear error messages like

> Cannot delete this {model}, because a {differentModel} depends on it.

But also, because PyroCMS uses `SoftDeletes` on every stream, one could argue that there wouldn't be many (if any) problems with implementing foreign keys.

Can someone please point me in the right direction so I can send in a PR to add Foreign Keys to the migrations ? Would make this an optional setting, of course!

Via https://github.com/anomalylabs/streams-platform/issues/289#event-810321155

CC @RyanThompson

**Comment by RyanThompson** [comment]
I think this should be handled on a per-stream basis so it will need to implemented on Field Types. Relationship for one will be a good one to start with.

I feel like this needs more thought put into it though still. @bloveless what do you think? I feel like cascading deletions could be improved too instead of relying on observer hooks and manual deletion.

Let's get a clear vision of these things first cause I think they're related in ways. Then we can form a plan and implement.

**Comment by bloveless** [comment]
I can see this being hugely helpful! Especially cascading deletions. Do you know how cross database cascading deletions are?

I've used observers all over the place to attempt to keep the DB clean and speedy.

I can also see DB enforced relations being very helpful.

This absolutely needs to be on a per-stream basis and implemented on Field Types.

**Comment by RyanThompson** [comment]
This will be a new feature in 3.2: https://github.com/anomalylabs/streams-platform/commit/1c201c3b3451ce845242a45adbedc55be7aff521

**Comment by RyanThompson** [comment]
For example (pages model):

    /**
     * The relation cascades.
     *
     * @var array
     */
    protected $cascades = [
        'entry'    => [
            'delete',
            'restore',
        ],
        'children' => [
            'delete',
            'restore',
        ],
    ];
