### ISSUE TITLE
[forms-module] Admin UI/UX no reference to what detail page you are on

### ISSUE THREAD

**Issue by ThinkGraphical** [pyrocms/pyrocms#3879]
On detail pages for 'Assignments' or 'Entries', there's no reference to what page you're on.

Ex. When looking at the page, I can't see that I'm on the assignments page for 'Contact'.
The only reference is in the URL, but it's an ID.

![Screenshot 1](https://www.evernote.com/l/AAbqpYYARFdMPpEAdOhjVnBVR56w9nd_kb8B/image.png)

When detail pages don't have a 'title' field (like a page entry detail) there's a need for a page heading or something like that, to give the user a reference.

**Comment by RyanThompson** [comment]
This is something that is going to be improved on a very wide scale. But has to be implemented per module.

**Comment by RyanThompson** [comment]
This is going to be addressed globally soon enough.
