### ISSUE TITLE
[forms-module] Admin UI/UX 'new form' cta 

### ISSUE THREAD

**Issue by ThinkGraphical** [pyrocms/pyrocms#3880]
The cta 'new form' is shown almost everywhere, while it's not always the cta you'd expect in the context.

Ex. This is the 'entries' view from my 'Contact' form. (sidenote: looking at this screenshot, theirs no way of telling that, because there's no reference whatsoever) 

Here you'd expect the 'export' button to be the main cta in this context and not the 'new form' cta.
Even further, in this context, a user would not really be interested in creating a new form.

![Screenshot 1](https://www.evernote.com/l/AAbMitNMY99LaLJYG5pDE9Ae6StqnzCH2TMB/image.png)

**Comment by RyanThompson** [comment]
Separated forms from it's sub-section entries. Should do better now.
