### ISSUE TITLE
[Bug Report] Twig error after changing post type layout

### ISSUE THREAD

**Issue by theshaunwalker** [pyrocms/pyrocms#3881]
I edited the Default post type included in the install, and selected a different Theme Layout.
After this I got a twig error, and even switching it back to the default layout that it was originally the error is still there.

The error is
```
An exception has been thrown during the rendering of a template ("Illegal offset type in isset or empty") in "theme::posts/post" at line 1
```

With my theme post template extending thusly
```
{% extends post.type.theme_layout %}
```

I can manually change the extends to `'theme::layouts.default'` and the page will load fine using the default layout. And checking the value of `post.type.theme_layout` when the page loads this way, the value is the same as `'theme::layouts.default'`

So it seems changing the theme layout via the Edit Post Type admin page, has caused some corruption somewhere that's preventing `{% extends post.type.theme_layout %}` being parsed correctly.

Any ideas?

**Comment by ThinkGraphical** [comment]
I think i've filled the same issue, but mistakenly in the specific module.
https://github.com/anomalylabs/posts-module/issues/25#issuecomment-251134603
Please keep the thread here.

Haven't got to examine it further but maybe this will help you.

**Comment by theshaunwalker** [comment]
Thanks @ThinkGraphical I thought @RyanThompson wanted all issues submitted on this main repo. 

Is this the case @RyanThompson? Or do you want module issues on the module's individual repo?

I'll follow on in the existing issue on posts-module for now anyway.

**Comment by ThinkGraphical** [comment]
Indeed, all issues must be submitted here in this main repo.
Like i said, I've mistakenly added it in the specific module, that was wrong of me to do.

But Ryan probably answered so I wouldn't have to recreate the issue here.

**Comment by theshaunwalker** [comment]
Fix found at https://github.com/anomalylabs/posts-module/issues/25#issuecomment-251340471
