### ISSUE TITLE
[forms-module] Export entries cta issue

### ISSUE THREAD

**Issue by ThinkGraphical** [pyrocms/pyrocms#3882]
I've noticed that the 'Export' button on form entries. Is always trying to export the entries of the first created form. (Twig cache?)

Ex. Currently on the 'Test' form entries page, while hovering the export button you see that the link still refers to my first created form 'Contact'.

![Screenshot 1](https://www.evernote.com/l/AAYEoy6rsFZID7Sw1Bx1qTaGv0bOC_AW-0cB/image.png)

Also noticing: forms / pages / ... uses ID's in the url, while the export button uses the slug. Maybe better to use the ID there also.

**Comment by RyanThompson** [comment]
This is kinda funny.. was hard coded so it was a coincidence.. But has been fixed in 1.1.
