### ISSUE TITLE
User module permissions

### ISSUE THREAD

**Issue by michiel1995** [pyrocms/pyrocms#3885]
When you create an "customer admin" and you want that this admin have access to the user module. this Amdin can create super admins. But you expect that he only can make other "customer admins" and not super admins.

**Comment by RyanThompson** [comment]
Seems like this is very dependent on the client. Perhaps a permission is needed for this as well.

**Comment by RyanThompson** [comment]
Added permission for writing (create/edit) admin roles: https://github.com/anomalylabs/users-module/commit/d476bc272ef93614660fd2172264a90839645d10
