### ISSUE TITLE
[multiple-field_type] Changing slug of page type causes base table not found exception

### ISSUE THREAD

**Issue by joe642** [pyrocms/pyrocms#3889]
Create a new page type, go back in and change the slug, attempt to edit/create a page using this page type, or assign a field to it, and it will give an exception like:

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pyro_db.yagro_pages_about_page_template_pages' doesn't exist (SQL: alter table`website_pages_about_page_template_pages`add`content`text null) in /var/www/website/vendor/laravel/framework/src/Illuminate/Database/Connection.php:761`

**Comment by RyanThompson** [comment]
Can you investigate in here and see if the correct values are updating the stream appropriately? 

https://github.com/anomalylabs/pages-module/blob/master/src/Type/Command/UpdateStream.php#L46

The type will have an associated stream for it's page models.

**Comment by joe642** [comment]
They are updating upstream, I think something on the other side is looking for a page slug that no longer exists.

**Comment by joe642** [comment]
It updated the pages_slug and translations table for the page type, but not for tables such created with the files/repeater module attached to that page type.

**Comment by RyanThompson** [comment]
Aha - so we need a hook or something to handle that.

**Comment by RyanThompson** [comment]
Nice work catching that - Ill take er from here!

**Comment by RyanThompson** [comment]
I've disabled slug changes for now here.
