### ISSUE TITLE
file-field_type - upload popup not always working

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#3891]
Hello,

There are circumstances when the UPLOAD popup won't show up.

1. try opening the 'create' method of some module
2. upload a file (or select from the list)
3. press REMOVE icon to remove the item
4. now try pressing the SELECT or UPLOAD - and you would get a loading screen

thanks

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/file-field_type/commit/63a53d873a55e49592d5a61e9c417c3ae95fc9f9

Thanks for the report! Well done.
