### ISSUE TITLE
[Bug Report] migrate:rollback missing --addon option

### ISSUE THREAD

**Issue by theshaunwalker** [pyrocms/pyrocms#3892]
From our previous discussion.

The `artisan migrate:rollback` command is missing the `--addon` option so you can rollback a specific module's etc. migrations.

I'm on commit 01598acc6ea2f02d39c0dbfb0ed12fac23258dd5 for streams-platform which is from October 3rd and nothing significant has been added since then so its not an update issue.

**Comment by RyanThompson** [comment]
This should do it: https://github.com/anomalylabs/streams-platform/commit/33fa2f95a98703fbce265a66833818b0ac547399

**Comment by theshaunwalker** [comment]
@RyanThompson Bingo 👍
