### ISSUE TITLE
addons install: seeder error

### ISSUE THREAD

**Issue by nickstanko** [pyrocms/pyrocms#3893]
Getting the following error when trying to install addons in the admin and selecting "Yes, include seed data when installing." Errors come up with both core and custom modules. On PHP7 with Pyro 3.1.

BindingResolutionException in Container.php line 763:
Target [Anomaly\PostsModule\Type\Contract\TypeRepositoryInterface] is not instantiable while building [Anomaly\PostsModule\Type\TypeSeeder].

**Comment by RyanThompson** [comment]
Took a stab at this one tonight and it's tough! I made an adjustment in streams platform that will help (only the register() move on InstallModule) but there is still an issue where the "state" of the PHP load can't update correctly to allow normal entry processing like it could with a new request. So this might need to be handled differently in the addons module.. We'll see.

https://github.com/anomalylabs/streams-platform/commit/81501f8991c2db2246ebf0416607248f2ccac7cf

**Comment by RyanThompson** [comment]
Related: https://github.com/pyrocms/pyrocms/issues/3859

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/3c92d14d3d0b8dc688e216eaf3b3e22d90d76a2d
