### ISSUE TITLE
[boolean-field_type] boolean checkbox not updating properly

### ISSUE THREAD

**Issue by stijntilleman** [pyrocms/pyrocms#3894]
I've just created a setting for a custom module, in this i needed a boolean field. So I created this resources/config/settings.php

``` php
return [
    'show_extras' => [
        'required' => false,
        'bind' => 'stijn_tilleman.module.custom_module::config.show_extras',
        'type' => 'anomaly.field_type.boolean',
        'config' => [
            "default_value" => false,
            "mode" => "checkbox",
        ],
    ],
];
```

When I visit the /admin/settings/modules/stijn_tilleman.module.custom_module I get the checkbox (YaY).

When I check the checkbox It's being saved to the database. But if i try to uncheck it again, the input isn't being updated in the database.

I got a solution but I don't know if its clean enough

``` twig
# core/anomaly/boolean-field_type/resources/views/checkbox.twig:23

<div class="c-inputs-stacked">

    <label class="c-input c-checkbox">
        <input
                type="hidden"
                name="{{ field_type.input_name }}"
                value="0"
                >
        <input
                type="checkbox"
                name="{{ field_type.input_name }}"
                value="1"
                {{ field_type.value ? 'checked' }}
                {{ field_type.readonly ? 'readonly' }}
                {{ field_type.disabled ? 'disabled' }}>

        <span class="c-indicator"></span>

        {{ trans(field_type.config.label) }}
    </label>

</div>
```

So this piece of code defines a default value for the 'input_name' and only if the checkbox is checked the new value will be passed to the request.

**Comment by RyanThompson** [comment]
Ya cause it's the only field and no value.. I have another way to handle it I ran into this the other day. I'll push a fix after fartin around with it a bit. Thanks!

**Comment by ThinkGraphical** [comment]
Any news on this?

**Comment by huglester** [comment]
@RyanThompson ?

Actually I was using this method in the last year or so:
<input
                type="hidden"
                name="{{ field_type.input_name }}"
                value="0"
                >
and it did work WELL for me. What you don't like about this? Is there a better scenario for this?

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/boolean-field_type/commit/5375e55642068dc795e4c9fd69318931679c4cf0
