### ISSUE TITLE
[file(s)-field_type] Folder selection handler

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#3895]
Would be nice to have a documented / robust way to provide available folders.

**Comment by huglester** [comment]
Yes, very much!

so, for example, in moduleX you select available folders as: ['CatalogMovies'], and then if no such folder exists, it would even create such a folder?

That way, when uploading, since only one folder is available, it will be default for upload! which is nice :)

**Comment by RyanThompson** [comment]
That could be done in an options handler for sure yes!

**Comment by RyanThompson** [comment]
Added: https://github.com/anomalylabs/users-module/commit/d476bc272ef93614660fd2172264a90839645d10
