### ISSUE TITLE
Add ability to serve files from CloudFront via custom URL from S3 adapter

### ISSUE THREAD

**Issue by joe642** [pyrocms/pyrocms#3896]
Would be good to be able to serve files directly from a CDN via a preconfigured URL (e.g. AWS), so files are served directly from the real path (CDN URL) rather than through Pyro.

I was trying to find a way of doing this with the S3 adapter, but as it is an extension rather than a plugin, I'm unsure of how to retrieve this path with the files module/file presenter.

This can be achieved by registering a path and calling it with {{ image('foo::example/image.png') }} where foo is registered as a path, but could be cleaner to have it as part of the S3 adapter enabling the use of {{ entry.image.make  }}

**Comment by RyanThompson** [comment]
Done! https://github.com/anomalylabs/files-module/commit/7f8798ec686e7a5883e1b172911405cb6f0e9f8c

You will of course need anonymous read-only access for your bucket. But this works for public-local file storage all the same as well.
