### ISSUE TITLE
[pages-module] Add named routes

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#3897]
Add "name" to pages stream and use the field to name the route.

**Comment by RyanThompson** [comment]
I was going to add a slug type field called "name" to the pages and have them use that for a named route like "pages::$name".. would like route pattern option in there too but not sure about that (for naming segments n such)

**Comment by Piterden** [comment]
Why don't use existing slug for it?

**Comment by damian-pf** [comment]
@Piterden slugs can change.

 But I guess in the context of the WYSIWYG link, could update all the links, depends on how it's stored I guess. 

You could have a table that keeps track of everywhere the named route is being linked to, that way updating would be easy.

**Comment by damian-pf** [comment]
@RyanThompson what about a links module? You could create the "named route" there and it's db entry would just link the IDs so no issue if the slug changes. 

Does the WYSIWYG content go through the twig parser? Could you have a twig function to fetch the link?

**Comment by Piterden** [comment]
Why don't you try it

**Comment by Piterden** [comment]
> slugs can change.

And what?

**Comment by RyanThompson** [comment]
Note to self: Should force prefix with `pages::` to avoid route/path collision. 

Also on the slugs - slugs don't have to be unique. These will need to be unique.

**Comment by RyanThompson** [comment]
Done in 2.6
