### ISSUE TITLE
[url-field_type] always required

### ISSUE THREAD

**Issue by nickstanko** [pyrocms/pyrocms#3899]
Adding a url-field_type field to any form and NOT requiring it will cause Chrome to force you to enter a URL to save the form in the admin. Unfortunately seems like input type would have to be text and field validation must be done with JS to make this work correctly.

**Comment by RyanThompson** [comment]
Hmm.. thats super odd I haven't noticed that. 

It uses the URL input type but no required flag as it's done server side:

https://github.com/anomalylabs/url-field_type/blob/master/resources/views/input.twig

**Comment by nickstanko** [comment]
If I remove the input type (type="text") it bypasses Chrome's HTML5 validation. But then we hit the server side validation if value is only "http://" - The "Web Page Address" format is invalid. Agreed wacky behavior.

**Comment by nickstanko** [comment]
Sorry I didn't notice that data was being seeded with only http:// for some entries - mistook it for the placeholder. If field is blank validation works correctly.

**Comment by RyanThompson** [comment]
Can you open the controller and dump your $_POST values? Let's see what it's actually getting. Maybe it's an issue in the filter validation part of post is clean.

**Comment by RyanThompson** [comment]
I assume these were your seeders?
