### ISSUE TITLE
Multi site manager

### ISSUE THREAD

**Issue by maczdata** [pyrocms/pyrocms#3900]
Am unable to purchase pyrocms multi site manager from the site. Any one has and willing to sell?

**Comment by RyanThompson** [comment]
No one is allowed to sell it but us as we own it. Are you having an issue logging in to purchase or what exactly are you experiencing issues with?

**Comment by maczdata** [comment]
Yes I can't login after signup

**Comment by RyanThompson** [comment]
What is your username there - I will activate your account.

**Comment by maczdata** [comment]
I can remember, by my email address is Immensedan@yahoo.com

**Comment by RyanThompson** [comment]
Activated!


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by maczdata** [comment]
Ok
