### ISSUE TITLE
Minimum PHP version?

### ISSUE THREAD

**Issue by jordanlev** [pyrocms/pyrocms#3902]
New to PyroCMS, trying to install it via Composer. Your docs say that the minimum version of PHP is 5.5.9: https://pyrocms.com/documentation/pyrocms/v3.1#installation/server-requirements

...but when I run the `composer create-project pyrocms/pyrocms` command, I get an error ("Your requirements could not be resolved to an installable set of packages.")... I think because Laravel version 5.3 required PHP 5.6 or higher. (And I am running PHP 5.5.36 on my computer).

**Comment by RyanThompson** [comment]
Bah - so sorry about that. It got reverted during the update to docs on accident. It does need 5.6.4 (Laravel's requirement for 5.3).

**Comment by RyanThompson** [comment]
I fixed docs too btw - thank you for the heads up!
