### ISSUE TITLE
Pages module error, error thrown on editing assignments and page

### ISSUE THREAD

**Issue by joe642** [pyrocms/pyrocms#3903]
**When attempting to open assignments for page type:**

Type error: Argument 1 passed to Anomaly\Streams\Platform\Assignment\Table\AssignmentTableBuilder::setStream() must implement interface Anomaly\Streams\Platform\Stream\Contract\StreamInterface, null given, called in /Applications/MAMP/htdocs/pyrocms/core/anomaly/pages-module/src/Http/Controller/Admin/AssignmentsController.php on line 33

**When attempting to edit page:**

FatalThrowableError in TypeModel.php line 89:
Call to a member function getEntryModelName() on null

**When attempting to edit page type**

FatalThrowableError in UpdateStream.php line 54:
Call to a member function fill() on null

Not sure what has caused it, it has died since last used it on Friday.

**Comment by RyanThompson** [comment]
I don't have enough information here but it would appear you may need to compile. If you can dig up some steps to reproduce let me know and we can reopen.
