### ISSUE TITLE
[FieldTypes] Can't be in admin url.

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#3904]
Field types can have their own routes, but if you put a route for a field type in the /admin area. I.E. /admin/cool-field_type/list you'll get an error in the SectionNormalizer (https://github.com/anomalylabs/streams-platform/blob/master/src/Ui/ControlPanel/Component/Section/SectionNormalizer.php#L46) resulting in a foreach error because $sections is a string at that point and not an array.

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/2bc126d64a6e2ffe0464477e95ccfd2c17112e13
