### ISSUE TITLE
Pyrocms 3.1.1 Installation fail

### ISSUE THREAD

**Issue by W1ll-1-am** [pyrocms/pyrocms#3905]
Hi, I seem to be getting this error on install too.
It occurs just after the files module tries to install.

[2016-10-11 10:04:23] local.ERROR: ReflectionException: Method Anomaly\Streams\Platform\Stream\Event\StreamWasUpdating::handle() does not exist in /home/william/work/aptana/pyrocms/vendor/laravel/framework/src/Illuminate/Container/Container.php:553

Pyrocms Version - 3.1.1
PHP Version - 7.0
MySQL Version - 5.7.15
OS - Ubuntu 16.04

Any idead what may be causing this @RyanThompson ?

**Comment by marcsoler** [comment]
Did composer install run as expected?

**Comment by W1ll-1-am** [comment]
Yeah I did not have any issues regarding composer. I reinstalled it to test if that could've been the issue but with no success

**Comment by rudivdme** [comment]
I am getting the same error. Composer succeeded, and I can run php artisan without errors, but the installer fails at the File Module. I tried locally on Valet and on a DO droplet.

**Comment by shane-garelja** [comment]
I'm also getting this error and have tried both 3.1.0 and 3.1.1.

**Comment by skvorets** [comment]
I am getting the same error (Windows environment)

**Comment by RyanThompson** [comment]
This has been fixed - composer update. 

Had some commits from a feature branch accidentally get pulled in. Sorry!
