### ISSUE TITLE
Interface tweaks to pages module

### ISSUE THREAD

**Issue by SublymeRick** [pyrocms/pyrocms#3907]
When adding a field to a page type (may come up in other modules as well) - Add a header to say what field you are adding to what thing, sometimes I  get pulled away from my desk in the middle of assignments and  I come back to the screen and I have no idea what field I'm adding to what thing, would be nice if the page said what it was that I was doing.

Also, I noticed when assigning fields the "+ assignment" button persists on the right side, and sometimes my brain sees that before the save / update buttons and just "reacts" as I'm trying to work fast, I'll click that instead of the actual save button. I feel that the the  + assignment button should go away while actually doing the assignment.

Further more, even when you go into the assignments area of a page type, that page does not indicate anywhere what page type you are currently editing:
![image](https://cloud.githubusercontent.com/assets/3813238/19356699/517e08ac-9134-11e6-8842-48a3cd634e9f.png)

**Comment by RyanThompson** [comment]
I think this could / should be done everywhere really (the table header indicating the object assigning to).

**Comment by RyanThompson** [comment]
Duplicate: https://github.com/pyrocms/pyrocms/issues/3879
