### ISSUE TITLE
Filter does not work on asset selector when the target asset is not on page one

### ISSUE THREAD

**Issue by SublymeRick** [pyrocms/pyrocms#3908]
See:
![image](https://cloud.githubusercontent.com/assets/3813238/19357332/d01255f4-9136-11e6-858f-672d032746d0.png)

and filtered:
![image](https://cloud.githubusercontent.com/assets/3813238/19357350/dea2586c-9136-11e6-95c6-a88aa7b98c5f.png)

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/a3661ff50034f06324c61f4fe9950b2a6582a4ed
