### ISSUE TITLE
View route changes on child pages loop when child is set to disabled

### ISSUE THREAD

**Issue by SublymeRick** [pyrocms/pyrocms#3909]
As per your request (just pasting the convo due to lazyness)

rickkuk [10:04 AM]  
If i disable a page, will it still be in the parent pages children array or will it be removed?

rickkuk [10:28 AM]  
To answer my own question, it does still show up in the array, which is good, however what I found strange was the link changes to some "preview" url which still loads the page. Ideally the the slug would not change and just throw a 404... but as long as there is a way to detect the fact that the page is disabled in the loop I guess it doesnt really matter

ryanthompson [11:24 AM]  
If you visit the slug / path @rickkuk it does 404

rickkuk [11:25 AM]  
right

ryanthompson [11:25 AM]  
but the link could be changed to a preview rather than having `view` change.

[11:25]  
it’s a unique preview link to show outsiders / preview

rickkuk [11:25 AM]  
but if the "loop" on the parent page doesnt know that its disabled it will link to the preview instead of the live link...

ryanthompson [11:25 AM]  
You can use `enabled` off the collection I believe

rickkuk [11:25 AM]  
I would have to add logic to the loop to check for that, which isnt a problem, just good to know

new messages
ryanthompson [11:26 AM]  
`… pages.enabled() …` in your loop

[11:26]  
Add an issue if you would - view route should not change - and add a `preview` route name (edited)

[11:27]  
That’s a good point

**Comment by RyanThompson** [comment]
NOTE: route `view` and `preview` separately.

**Comment by RyanThompson** [comment]
This is addressed in 2.2
