### ISSUE TITLE
Fresh install doesn't include the .ENV file

### ISSUE THREAD

**Issue by CDOLago** [pyrocms/pyrocms#3913]
`composer create-project pyrocms/pyrocms`

Installs everything... go to browser and see `500 There was an error.`. Check project and there is no .env file to be found.

**Comment by RyanThompson** [comment]
What do your server logs say about the errors? Did you check logs?

Per docs you still have to run the installer so there is no .env file just yet.

**Comment by CDOLago** [comment]
I ran this composer command: `composer create-project pyrocms/pyrocms`

What's the next step? The documentation says run that and the next things it says is the following: 

> **Running the Installer**
> 
> After downloading and installing PyroCMS and it's dependencies, you will need to install the software in order to get started. By this time you should be able to visit your site's URL which will redirect you to the installer.

How do I do that?

**Comment by RyanThompson** [comment]
Hit the URL like yoursite.dev or something - but sounds like you’re running into 500’s so let’s figure out what those are. What do your laravel / server logs say?

**Comment by CDOLago** [comment]
Here´s the error:

```
ErrorException in BooleanFieldTypePresenter.php line 126:
Declaration of Anomaly\BooleanFieldType\BooleanFieldTypePresenter::label() should be compatible with Anomaly\Streams\Platform\Addon\FieldType\FieldTypePresenter::label($text = NULL, $context = NULL, $size = NULL)
```

**Comment by CDOLago** [comment]
I created another project (about the 4th) and it has magically started working.
