### ISSUE TITLE
[streams-platform] select database table type

### ISSUE THREAD

**Issue by mikey0000** [pyrocms/pyrocms#3914]
As a dev I would like to be able to select which table type to use per table.

**Comment by RyanThompson** [comment]
I think this can be stuffed into the streams.config value.

**Comment by RyanThompson** [comment]
Added: https://github.com/anomalylabs/streams-platform/commit/107828ee79b0abb049988fc50b58f4c410f7d043

Just added this to the streams definition in your migration.

```
'config' => ['database' => ['engine' => 'InnoDB']]
```
