### ISSUE TITLE
[feature] files-field_type - upload files by order?

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#3915]
Hello,
is there a way to upload files by order they were 'selected'? I tried:
```php
data-max-parallel="{{ setting_value('anomaly.module.files::max_parallel_uploads', 1) }}"
```

but this also does not help.
Thank you

**Comment by RyanThompson** [comment]
I think that's kinda how they do it now? It does top down in the loaded files to upload?

**Comment by RyanThompson** [comment]
Files are uploaded in the the way they appear in my finder.. but I don't think there is any way of changing this.

**Comment by huglester** [comment]
I will re-test this and post back
