### ISSUE TITLE
[feature] log module 

### ISSUE THREAD

**Issue by michiel1995** [pyrocms/pyrocms#3916]
It will be verry handy if there is a log module where you can see all the changes that has been done in the admin. Think about UserA created a Form, Page, UserB,...  and UserB edited the Form, Page,... I think this will be a feature that will be a great value for the cms!

**Comment by ThinkGraphical** [comment]
Possible reference: https://devot-ee.com/add-ons/audit-pro

**Comment by RyanThompson** [comment]
I have plans for a "Revisions" module using: https://github.com/VentureCraft/revisionable

Would be open to contract if anyone needs it faster ;-)
