### ISSUE TITLE
ErrorException, file_put_contents FilesFilesEntryModel.php, Permission denied Filesystem.php

### ISSUE THREAD

**Issue by CDOLago** [pyrocms/pyrocms#3917]
http://i.imgur.com/8ad1Sov.png

`[2016-10-18 12:47:39] local.ERROR: ErrorException: file_put_contents(C:\Users\Daniel\Dropbox\Work\Dev\Laragon\pyrocms\storage\streams/default/models/Files/FilesFilesEntryModel.php): failed to open stream: Permission denied in C:\Users\Daniel\Dropbox\Work\Dev\Laragon\pyrocms\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:111`

I've tried setting **everything** to `777` and using `php artisan serve` to no avail.

**Comment by RyanThompson** [comment]
Check ownership of the directory - also Pyro has not been thoroughly tested using the `serve`. Please use a vhost.

**Comment by DeeJaVu** [comment]
all you have to do is create an empty .env file and chmod 777 the file then run the installer
and is should work
