### ISSUE TITLE
Sorting pages (works) throws a 500 error after about 10 seconds

### ISSUE THREAD

**Issue by SublymeRick** [pyrocms/pyrocms#3918]
![image](https://cloud.githubusercontent.com/assets/3813238/19483363/aedb24ec-9519-11e6-9ecf-dd8b9d64c6cb.png)

[2016-10-18 14:59:21] local.ERROR: PDOException: SQLSTATE[HY000]: General error: 5 database is locked in C:\Projects\uptown\pyrocms\vendor\teamtnt\tntsearch\src\Indexer\TNTIndexer.php:383
Stack trace:
#0 C:\Projects\uptown\pyrocms\vendor\teamtnt\tntsearch\src\Indexer\TNTIndexer.php(383): PDOStatement->execute()
#1 C:\Projects\uptown\pyrocms\vendor\teamtnt\tntsearch\src\Indexer\TNTIndexer.php(340): TeamTNT\TNTSearch\Indexer\TNTIndexer->saveWordlist(Object(TeamTNT\TNTSearch\Support\Collection))
#2 C:\Projects\uptown\pyrocms\vendor\teamtnt\tntsearch\src\Indexer\TNTIndexer.php(269): TeamTNT\TNTSearch\Indexer\TNTIndexer->saveToIndex(Object(TeamTNT\TNTSearch\Support\Collection), 17)
#3 C:\Projects\uptown\pyrocms\vendor\teamtnt\tntsearch\src\Indexer\TNTIndexer.php(274): TeamTNT\TNTSearch\Indexer\TNTIndexer->processDocument(Object(TeamTNT\TNTSearch\Support\Collection))
#4 C:\Projects\uptown\pyrocms\vendor\teamtnt\tntsearch\src\Indexer\TNTIndexer.php(282): TeamTNT\TNTSearch\Indexer\TNTIndexer->insert(Array)
#5 C:\Projects\uptown\pyrocms\vendor\teamtnt\laravel-scout-tntsearch-driver\src\Engines\TNTSearchEngine.php(45): TeamTNT\TNTSearch\Indexer\TNTIndexer->update(17, Array)
#6 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Support\Collection.php(228): TeamTNT\Scout\Engines\TNTSearchEngine->TeamTNT\Scout\Engines\{closure}(Object(Anomaly\PagesModule\Page\PageModel), 0)
#7 C:\Projects\uptown\pyrocms\vendor\teamtnt\laravel-scout-tntsearch-driver\src\Engines\TNTSearchEngine.php(49): Illuminate\Support\Collection->each(Object(Closure))
#8 C:\Projects\uptown\pyrocms\vendor\laravel\scout\src\Searchable.php(52): TeamTNT\Scout\Engines\TNTSearchEngine->update(Object(Illuminate\Database\Eloquent\Collection))
#9 C:\Projects\uptown\pyrocms\vendor\laravel\scout\src\Searchable.php(35): Anomaly\Streams\Platform\Entry\EntryModel->queueMakeSearchable(Object(Illuminate\Database\Eloquent\Collection))
#10 [internal function]: Illuminate\Database\Eloquent\Collection->Laravel\Scout\{closure}()
#11 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Support\Traits\Macroable.php(78): call_user_func_array(Object(Closure), Array)
#12 C:\Projects\uptown\pyrocms\vendor\laravel\scout\src\Searchable.php(98): Illuminate\Support\Collection->__call('searchable', Array)
#13 C:\Projects\uptown\pyrocms\vendor\laravel\scout\src\ModelObserver.php(76): Anomaly\Streams\Platform\Entry\EntryModel->searchable()
#14 [internal function]: Laravel\Scout\ModelObserver->updated(Object(Anomaly\PagesModule\Page\PageModel))
#15 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(348): call_user_func_array(Array, Array)
#16 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(Anomaly\PagesModule\Page\PageModel))
#17 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#18 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1665): Illuminate\Events\Dispatcher->fire('eloquent.update...', Array)
#19 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1545): Illuminate\Database\Eloquent\Model->fireModelEvent('eloquent.update...', false)
#20 C:\Projects\uptown\pyrocms\vendor\anomaly\streams-platform\src\Model\EloquentModel.php(518): Illuminate\Database\Eloquent\Model->performUpdate(Object(Anomaly\Streams\Platform\Entry\EntryQueryBuilder), Array)
#21 C:\Projects\uptown\pyrocms\vendor\anomaly\streams-platform\src\Model\EloquentModel.php(471): Anomaly\Streams\Platform\Model\EloquentModel->saveModel(Array)
#22 C:\Projects\uptown\pyrocms\vendor\anomaly\streams-platform\src\Model\EloquentTreeRepository.php(108): Anomaly\Streams\Platform\Model\EloquentModel->save()
#23 C:\Projects\uptown\pyrocms\vendor\anomaly\streams-platform\src\Model\EloquentTreeRepository.php(111): Anomaly\Streams\Platform\Model\EloquentTreeRepository->save(Object(Anomaly\PagesModule\Page\Tree\PageTreeBuilder), Array, '16')
#24 C:\Projects\uptown\pyrocms\vendor\anomaly\streams-platform\src\Ui\Tree\Command\SaveTree.php(41): Anomaly\Streams\Platform\Model\EloquentTreeRepository->save(Object(Anomaly\PagesModule\Page\Tree\PageTreeBuilder))
#25 [internal function]: Anomaly\Streams\Platform\Ui\Tree\Command\SaveTree->handle()
#26 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Container\Container.php(508): call_user_func_array(Array, Array)
#27 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#28 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Anomaly\Streams\Platform\Ui\Tree\Command\SaveTree))
#29 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Anomaly\Streams\Platform\Ui\Tree\Command\SaveTree))
#30 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(75): Illuminate\Bus\Dispatcher->dispatchNow(Object(Anomaly\Streams\Platform\Ui\Tree\Command\SaveTree))
#32 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Foundation\Bus\DispatchesJobs.php(17): Illuminate\Bus\Dispatcher->dispatch(Object(Anomaly\Streams\Platform\Ui\Tree\Command\SaveTree))
#33 C:\Projects\uptown\pyrocms\vendor\anomaly\streams-platform\src\Ui\Tree\Command\PostTree.php(39): Anomaly\Streams\Platform\Ui\Tree\Command\PostTree->dispatch(Object(Anomaly\Streams\Platform\Ui\Tree\Command\SaveTree))
#34 [internal function]: Anomaly\Streams\Platform\Ui\Tree\Command\PostTree->handle()
#35 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Container\Container.php(508): call_user_func_array(Array, Array)
#36 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#37 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Anomaly\Streams\Platform\Ui\Tree\Command\PostTree))
#38 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Anomaly\Streams\Platform\Ui\Tree\Command\PostTree))
#39 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#40 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(75): Illuminate\Bus\Dispatcher->dispatchNow(Object(Anomaly\Streams\Platform\Ui\Tree\Command\PostTree))
#41 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Foundation\Bus\DispatchesJobs.php(17): Illuminate\Bus\Dispatcher->dispatch(Object(Anomaly\Streams\Platform\Ui\Tree\Command\PostTree))
#42 C:\Projects\uptown\pyrocms\vendor\anomaly\streams-platform\src\Ui\Tree\TreeBuilder.php(94): Anomaly\Streams\Platform\Ui\Tree\TreeBuilder->dispatch(Object(Anomaly\Streams\Platform\Ui\Tree\Command\PostTree))
#43 C:\Projects\uptown\pyrocms\vendor\anomaly\streams-platform\src\Ui\Tree\TreeBuilder.php(107): Anomaly\Streams\Platform\Ui\Tree\TreeBuilder->build()
#44 C:\Projects\uptown\pyrocms\vendor\anomaly\streams-platform\src\Ui\Tree\TreeBuilder.php(152): Anomaly\Streams\Platform\Ui\Tree\TreeBuilder->make()
#45 C:\Projects\uptown\pyrocms\core\anomaly\pages-module\src\Http\Controller\Admin\PagesController.php(34): Anomaly\Streams\Platform\Ui\Tree\TreeBuilder->render()
#46 [internal function]: Anomaly\PagesModule\Http\Controller\Admin\PagesController->index(Object(Anomaly\PagesModule\Page\Tree\PageTreeBuilder))
#47 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(55): call_user_func_array(Array, Array)
#48 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('index', Array)
#49 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Route.php(189): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Anomaly\PagesModule\Http\Controller\Admin\PagesController), 'index')
#50 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Route.php(144): Illuminate\Routing\Route->runController()
#51 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Router.php(642): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#52 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 C:\Projects\uptown\pyrocms\vendor\anomaly\streams-platform\src\Http\Middleware\PoweredBy.php(38): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Anomaly\Streams\Platform\Http\Middleware\PoweredBy->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 C:\Projects\uptown\pyrocms\vendor\anomaly\streams-platform\src\Http\Middleware\SetLocale.php(88): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Anomaly\Streams\Platform\Http\Middleware\SetLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 C:\Projects\uptown\pyrocms\vendor\anomaly\streams-platform\src\Http\Middleware\ApplicationReady.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Anomaly\Streams\Platform\Http\Middleware\ApplicationReady->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 C:\Projects\uptown\pyrocms\core\anomaly\users-module\src\Http\Middleware\AuthorizeRoutePermission.php(106): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\AuthorizeRoutePermission->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 C:\Projects\uptown\pyrocms\core\anomaly\users-module\src\Http\Middleware\AuthorizeControlPanel.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\AuthorizeControlPanel->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 C:\Projects\uptown\pyrocms\core\anomaly\users-module\src\Http\Middleware\AuthorizeModuleAccess.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#72 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\AuthorizeModuleAccess->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#74 C:\Projects\uptown\pyrocms\core\anomaly\users-module\src\Http\Middleware\AuthorizeRouteRoles.php(98): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#75 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\AuthorizeRouteRoles->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 C:\Projects\uptown\pyrocms\core\anomaly\users-module\src\Http\Middleware\CheckSecurity.php(86): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#78 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\CheckSecurity->handle(Object(Illuminate\Http\Request), Object(Closure))
#79 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#80 C:\Projects\uptown\pyrocms\core\anomaly\users-module\src\Http\Middleware\Authenticate.php(92): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#81 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#82 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#83 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#84 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Router.php(644): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#85 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Router.php(618): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#86 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Router.php(596): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#87 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(267): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#88 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#89 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#90 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#91 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#92 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#93 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#94 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#95 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#96 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#97 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#98 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#99 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#100 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#101 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#102 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#103 C:\Projects\uptown\pyrocms\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#104 C:\Projects\uptown\pyrocms\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#105 {main}

**Comment by RyanThompson** [comment]
Delete your search index as a quick fix: storage/streams/{ref}/search/*

**Comment by RyanThompson** [comment]
This is related to a recursion issue that I will be addressing.

**Comment by ultrono** [comment]
Still getting this issue on a fresh install of v3.5.
