### ISSUE TITLE
[localisation] translatable fields are gone when disable English language

### ISSUE THREAD

**Issue by michiel1995** [pyrocms/pyrocms#3923]
When you enable languages and disable English (the default) by example 2 languages dutch & french. You set the default language from your site to dutch. When you go to a custom module and set `translatable' => true` in your stream and to the field assignment. All the translatable fields are gone in the view

**Comment by aliselcuk** [comment]
try adding these to you .env file: 
`DEFAULT_LOCALE=fr`
`APP_FALLBACK_LOCALE=fr`

and see if it fixes

**Comment by RyanThompson** [comment]
i believe the is resolved.
