### ISSUE TITLE
slug ft fights with curosor

### ISSUE THREAD

**Issue by SublymeRick** [pyrocms/pyrocms#3924]
Cannot arrow back to edit slug in middle, must backspace. If you do click in the middle somewhere and add a character it immediately sends the carrot to the end of the string after keystroke. You cannot add a space, - or _ to the end of the page slug string, and I understand why, but if im manually typing my slug and I want to enter an underscore this basically wont let me do it. I have to type the whole thing with no spaces or underscores, then go back and add them in by clicking where I want the underscore.

**Comment by RyanThompson** [comment]
Fixed the jumpiness! https://github.com/anomalylabs/slug-field_type/commit/f2ec9a6d609c757618163a292ccc28b0cf4db218

And the other thing has been fixed too some time prior.
