### ISSUE TITLE
[streams-platform] new_* type buttons are not getting translated to languages other then default 

### ISSUE THREAD

**Issue by aliselcuk** [pyrocms/pyrocms#3926]
I've created a section button in the format of new_*:

```
    protected $sections = [
        'categories' => [
            'buttons' => [
                'new_category',
            ],
        ],
    ];
```

And in **resources/lang/en/button.php**:

```
return [
    'new_category' => 'New Category';
];
```

In **resources/lang/tr/button.php**:

```
return [
    'new_category' => 'Yeni Kategori';
];
```

and this never gets translated to Turkish.

It seems these buttons are compiled in `Anomaly\Streams\Platform\Ui\ControlPanel\Component\Button\Guesser\TypeGuesser` and Control Panel is loaded after `Anomaly\Streams\Platform\Application\Event\ApplicationHasLoaded` is fired

However in `Anomaly\Streams\Platform\Http\Controller\BaseController` this event if fired before setting the locale

```
        $this->middleware('Anomaly\Streams\Platform\Http\Middleware\ApplicationReady');
        $this->middleware('Anomaly\Streams\Platform\Http\Middleware\SetLocale');
```

Switching the middleware order: 

```
        $this->middleware('Anomaly\Streams\Platform\Http\Middleware\SetLocale');
        $this->middleware('Anomaly\Streams\Platform\Http\Middleware\ApplicationReady');
```

fixes this

**Comment by RyanThompson** [comment]
Fixed thanks! https://github.com/anomalylabs/streams-platform/blob/master/src/Http/Controller/BaseController.php#L145
