### ISSUE TITLE
[datetime-field_type] Validation of time type

### ISSUE THREAD

**Issue by stijntilleman** [pyrocms/pyrocms#3927]
Since an update of datetime-field_type (this morning) the time only type throws up a validation error "field must contain 1 items" when you fill it in

commit 872efec9e110b282c5bfa706498237021d6e308d seems to be the problem

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/datetime-field_type/commit/4d687a948fef3b9dc5b7cf68ba66024b1857bdb1
