### ISSUE TITLE
[pages-module] Slugs change when updating title/name

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3928]
Hello!

When i have created a page entry and start to modify its title, the slug changes automatically. This is a very bad thing. Like URL should not change just because its title changed.

Also when i modify a page type, there is identical behaviour with name and a slug. Are these slugs supposed to change at all?

Ryan would you consider removing the `slugify` option from the slug?

Like it is OK, if this option is on when creating, but for updating it is a pain!

**Comment by RyanThompson** [comment]
I won’t be removing it but have considered a little additional UI / behavior. Like if there is a value don’t auto-update (editing).

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/slug-field_type/commit/c3114c3a86448943386d51b7937e2df2e74437e9
