### ISSUE TITLE
[streams-platform] Field assignments should have searchable flag

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#3929]
Base `toSearchableArray` can default to all if no searchable fields and stream is searchable.

**Comment by edster** [comment]
Would be handy, nice that you don't have to scroll forever and a day to get to the field your looking for

**Comment by RyanThompson** [comment]
This would be for search indexing with Scout. Instead of indexing the entire model by default you can define which fields are searchable. This will be mostly for custom streams. So you add a custom content field - make it searchable so it's available in the search API. Add a boolean for whatever.. Not searchable skip it.

**Comment by aliselcuk** [comment]
Would be just great. I was already tackling this with overriding the toSearchableArray method.

thumbs up!

**Comment by RyanThompson** [comment]
This is done.
