### ISSUE TITLE
Need more Docs/Tutorials

### ISSUE THREAD

**Issue by EgorLetovsky** [pyrocms/pyrocms#3931]
i've just installed Pyro and... have no one idea how to create even the simplest Wordpress-like news site, write the simplest plugin and so on

add some video tutorials (there are only 2 of them on youtube now but they are really terrible)

**Comment by RyanThompson** [comment]
Hi Egor - I appreciate your criticism. You can probably imagine how hard and how much time it has taken to get this project back to the state it's in! Quite difficult. Docs take time too. And I don't know if you've been around to see but they've already grown TREMENDOUSLY and improved in design. So, that said - I am asking you to be patient ^_^ You've given me a couple ideas that are already on my radar for missing docs / videos that are already on my radar. And in the meanwhile - please join our Slack channel and register for the forum! There are plenty more people who have learned and are eager to share. I am often available to help personally as well - so don't hesitate to give me a shout. 

Cheers! ^_^
