### ISSUE TITLE
[anomoly] Twig errors on input.twig field_types.text randomly

### ISSUE THREAD

**Issue by mikey0000** [pyrocms/pyrocms#3934]
http://pastebin.com/1e73qxpr

I keep getting this issue, it only happens occasionally and if I refresh it goes away.

**Comment by RyanThompson** [comment]
What are the contents of `/home/vagrant/Code/storage/framework/views/twig/d4/d413d9f4f9f161c1ebd60a34d773c6a16a97bf7d52518cb3f250c1087560f30b.php`?


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by mikey0000** [comment]
http://pastebin.com/6pZrbVq2

here they are.

**Comment by RyanThompson** [comment]
The original file is no longer available - if you can cross reference the two files like I was about to you can get some more information to post if this continues. Closing for now - reopen as needed!
