### ISSUE TITLE
[streams-platform] Bind generators from Laravel and add options 

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#3936]

**Comment by Piterden** [comment]
Can you tell me, which exactly generators and what options do you want to bind together?
I could have a try to make it...

**Comment by RyanThompson** [comment]
Well... pretty much all of them really. But I've been thinking about this and not sure about it's cost / benefit ratio.. Since make:stream does all this anyways.

**Comment by RyanThompson** [comment]
Going to close for now.. might reopen. Meh ^_^
