### ISSUE TITLE
[streams-platform] Translatable field option not working

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3940]
Hello!

This is a major bug.

When text field has translatable option, it is not displayed by the form builder. Bug is present in pages module types section as well!

When translatable option is removed, the field is displayed:

```
    protected $assignments = [
        'name'         => [
            //'translatable' => true,
            'required'     => true,
            'unique'       => true,
        ],
```

**Comment by keevitaja** [comment]
This bug can be recreated when during installation you choose your primary locale something other than english and later do not enable it from the settings panel.

**Comment by RyanThompson** [comment]
When you say primary locale do you mean fallback?

I need more specific steps to recreate - sorry! But this kinda sounds like it might be misconfiguration - which may not be a bug - could definitely be explained / given a heads up better on my part ^_^

**Comment by keevitaja** [comment]
So, i installed with estonian default locale. And when i browse page in admin side, i get missing fields:

![screenshot_2016-11-02_22-38-29](https://cloud.githubusercontent.com/assets/158787/19946594/456fc8ce-a14d-11e6-9b84-bee677a62603.png)

And when i check the estonian locale in the settings, all is fine again:

![screenshot_2016-11-02_22-39-03](https://cloud.githubusercontent.com/assets/158787/19946610/512c4430-a14d-11e6-8234-5ec6aa4df19c.png)

**Comment by RyanThompson** [comment]
What was checked before? Nothing?


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by keevitaja** [comment]
Nothing!

**Comment by RyanThompson** [comment]
Ok so need to add to the enabled locales there.. 


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/settings-module/commit/a9ca8c53f335626b7780dada7c4553534479f16f
https://github.com/anomalylabs/streams-platform/commit/4ab3106507e9580644a8fd928c2b923cbb5008e7

Fixed!
