### ISSUE TITLE
[Forms SetJsonResponse] add extra data to json response

### ISSUE THREAD

**Issue by stijntilleman** [pyrocms/pyrocms#3941]
Out of the box we can use `{% set form = form('newsletter.form').actions(['submit']).ajax(true).get() %}` to load a form (in this case a newsletter form) and set the handling to ajax [great!], but by default you can only pass a couple of things to the response:
- success: boolean
- errors: array 
- redirect: string, only there if the response if of type RedirectResponse

Wouldn't it be useful to be able to pass extra data to the default Json response?

fe. I'm creating a remote resource, the service I use returns the full resource as Json after it's finished creating it, but after the default ajax handler finished it's job, it returns an ajax response 

``` json
{
  "success":true,
  "errors":[],
  "redirect":"http:\/\/www.my-site.com"
}
```

My proposal would be to be able to add extra response data via the form builder that's added to the json response under it's own key `data`

``` php
# in a custom handle method
# $builder->addResponseData($key, $value);
$builder->addResponseData("name", "Sylvester");
$builder->addResponseData("type", "cat");
$builder->addResponseData("enemy", "Tweety");
```

which would give you

``` json
{
  "success":true,
  "errors":[],
  "redirect":"http:\/\/www.my-site.com",
  "data":
     {
        "name":"Sylvester",
        "type":"cat",
        "enemy":"Tweety"
     }
}
```

**Comment by RyanThompson** [comment]
I think you can probably do this already by using `$builder->getFormResponse()` and working with the object directly. I don't have anything more offhand for this but check it out! Let me know if it's available there. If so - you can use `onPosted` builder callback to handle hooking into it without a custom handler.

**Comment by RyanThompson** [comment]
Ya so I just confirmed - you can `getData` and `setData` off the response object from `$builder->getFormResponse();`
