### ISSUE TITLE
Form validation and $_POSTed data

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#3949]
Hello,

so we have a form. and First name is required.
we have populated data, but for example we remove the 'First name' value;
and try to save;
we get 'First name required' validation error

but in the first_name field, we get old data, not $_POSTed one (empty).
We think that after saving the form, data in the forms should be $_POSTed not from the entity.

thanks

**Comment by RyanThompson** [comment]
You need to `skip` the field. `$builder->skipField(slug)` or include it in the `$skips` property.

**Comment by RyanThompson** [comment]
You can also remove the the field programmatically anytime before validation.

**Comment by huglester** [comment]
@RyanThompson maybe I described it wrong.

1. YOu try to edit for example Entity. It has first_name field with value Jaroslav
2. You remove this value and press SAVE
3. You get and ERROR - "First name is required" - which is OK
4. The value in the first_name field is again "Jaroslav" - but I deleted it! so it should be empty
