### ISSUE TITLE
[streams-platform] composer update complains of abandoned package

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#3950]
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

**Comment by huglester** [comment]
which package depends on it?

**Comment by RyanThompson** [comment]
Looks like core is good: https://github.com/anomalylabs/streams-platform/blob/master/composer.json#L23-L25 <https://github.com/anomalylabs/streams-platform/blob/master/composer.json#L23-L25>


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by RyanThompson** [comment]
`twig-markdown` and `string-template` both use it it looks like (from core) so it's inferred through those.


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by huglester** [comment]
@RyanThompson probably can be closed then
