### ISSUE TITLE
[wysiwyg-field_type] Option to persist to DB only

### ISSUE THREAD

**Issue by adrianfalleiro** [pyrocms/pyrocms#3951]
Thoughts on adding an option to the field type to make it only persist to the database and not the local filesystem. 

Would you accept a PR for this?

Example config might look like:
```
"example" => [
    "type"   => "anomaly.field_type.wysiwyg",
    "config" => [
        "default_value" => null,
        "configuration" => "default",
        "line_breaks"   => false,
        "height"        => 500,
        "buttons"       => [],
        "plugins"       => [],
        "persistence" => "db_only", // "db_only" or "default"
    ]
]
```

**Comment by RyanThompson** [comment]
What would be the reasoning behind this? In the end - it uses the view and runs it through the native view system for rendering which is quite nice when needed (extending views n such).

What use case do you have to avoid this file storage?

**Comment by adrianfalleiro** [comment]
I'm deploying across multiple application servers and and want to reduce the possibility of variation across nodes.

**Comment by RyanThompson** [comment]
The storage directory should be ignored - the DB value is used as truth. Are you lsyncing or something?

**Comment by adrianfalleiro** [comment]
Hmm, in our tests we found that manually updating the twig file in the storage folder changed what was displayed.

**Comment by RyanThompson** [comment]
IF it's newer than what the database has yes it will update the database.

**Comment by RyanThompson** [comment]
The intention is that it's only used for development - however I could use perhaps disabling this or forcing the DB output to sync to file IF the system is NOT in debug mode. That would essentially get you the same effect, yes?

**Comment by RyanThompson** [comment]
Ive already remove the storage path when not in debug mode - this would make sense along the same lines.

**Comment by adrianfalleiro** [comment]
So that's what I want to avoid. Yeah if there was a way to disable sync from filesystem to DB that would achieve what I'm after

**Comment by RyanThompson** [comment]
Ok - Ill work on that then. Should be very simple to do. Ill patch the three FTs that do this tonight. 


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by adrianfalleiro** [comment]
Legend. 💯

**Comment by RyanThompson** [comment]
Give er a shot: https://github.com/anomalylabs/wysiwyg-field_type/commit/e45e404df10243a64516eca0550bbfd358c70d06
