### ISSUE TITLE
[Feature] environment twig function

### ISSUE THREAD

**Issue by stijntilleman** [pyrocms/pyrocms#3953]
Atm the only way to check which environment you are on from twig is `env("APP_ENV") == "insert_env_here"` that will give you a boolean.

In Laravel if you use `app()->environment("production", "staging")` this checks if the current environment is in the list. Would it not be "better" to expose this function to twig so you can output environment specific items easier.

As an example the plugin im using atm to add this exact functionality

```php
# Plugins/EnvironmentPlugin.php

class EnvironmentPlugin extends Plugin
{
    /**
     * @var EnvironmentPluginFunctions
     */
    protected $functions;

    public function __construct(EnvironmentPluginFunctions $functions)
    {
        $this->functions = $functions;
    }

    public function getFunctions()
    {
        return [
            new \Twig_SimpleFunction(
                'environment', [$this->functions, 'isEnvironment']
            ),
        ];
    }
}
```

```php
# Plugins/Functions/EnvironmentPluginFunctions.php

class EnvironmentPluginFunctions
{
    use DispatchesJobs;

    /**
     * @var Application
     */
    protected $application;

    public function __construct(
        Application $application
    ) {
        $this->application = $application;
    }

    /**
     * Expose the app.environment() method to twig
     *
     * @return bool|string
     */
    public function isEnvironment()
    {
        $args = func_get_args();

        if (empty($args)) {
            return $this->application->environment();
        }

        return call_user_func([$this->application, "environment"], $args);
    }

}
```
ps: I would've created a pull request, but I couldn't decide where to put this.

**Comment by RyanThompson** [comment]
I really prefer to use the native functionality of existing code like Twig `in Array` and the `env` function. 

```
{% if env('APP_ENV') in ['local', 'development'] %}
    Phew.. we're ok.
{% endif %}
```

We have to be careful cause this kinda wrapping can be dangerous - more overhead and more code that does basically the same thing. Thanks for the suggestion! Keep em coming ^_^
