### ISSUE TITLE
[feature] [forum-module] Follow a channel

### ISSUE THREAD

**Issue by daviesgeek** [pyrocms/pyrocms#3955]
Just like you can follow a discussion, it'd be pretty awesome if you could follow a channel.

**Comment by RyanThompson** [comment]
I like it!

**Comment by RyanThompson** [comment]
Ill have to take a look and see about implementation - first concern is the notification system. These notifications will have to be moved to `ShouldQueue` if not already

**Comment by daviesgeek** [comment]
I haven't dug into it extensively, but when I do, I'll see if I can put up a PR.

**Comment by RyanThompson** [comment]
I appreciate the offer! Don't be offended if I mess with PRs quite a bit. It's still a pretty early addon and design patterns are still emerging.


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by daviesgeek** [comment]
Awesome. LOL. You know me…I won't be :joy: I'm still learning the design patterns, so I'm sure I'll mess stuff up 😆
