### ISSUE TITLE
[multiple-field_type] Sorting not working in lookup mode

### ISSUE THREAD

**Issue by aidanwatt** [pyrocms/pyrocms#3956]
Issue in lookup.js When rows are added for the first time sortable not firing.

wrapper.find('.selected table').sortable({.... Probs wants wrapping in a function and call, similar to the files field type.

Think there is a bit of old code in there as well.

**Comment by huglester** [comment]
confirmed

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/multiple-field_type/commit/e8ab9b22b10d5f0d2095971755fde7053a5483ad

Thanks guys - excellent report @aidanwatt

**Comment by aidanwatt** [comment]
No probs - cheers
