### ISSUE TITLE
[feature] [forum-module] Private channels

### ISSUE THREAD

**Issue by daviesgeek** [pyrocms/pyrocms#3957]
Pretty self-explanatory; private channels that allow a moderator or administrator to approve join requests.

**Comment by RyanThompson** [comment]
I almost added this in - an `allowed_roles` field for channels..

**Comment by daviesgeek** [comment]
Ahh okay. But that would require creation of roles for each individual group right? Let's say I have three "private" channels, wouldn't that mean three different roles? 

I currently am planning on adding a field to each channel that's a relationship to many users, then just filtering out the front end as necessary. That said, it would be pretty awesome if this functionality was baked in.

**Comment by daviesgeek** [comment]
From a conversation with Ryan. Should create a new stream called "subscriptions" that allows for subscribing to an individual channel and get email notifications.
