### ISSUE TITLE
Pages module - multilang

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#3960]
So I try: 

1. Enable LT locale
2. Create a default page
3. Fill title, Content
4. Switch to LT locale
5. Fill in 'Title' but 'Content' has the value from EN, I change it to 'LT content'
6. Switch back to EN locale, and see 'LT Content' there

thank you

**Comment by RyanThompson** [comment]
Glad we figured this out! FYI: https://github.com/anomalylabs/pages-module/commit/97d7cbb80e4d97cc8ad3db617cdfcee3faa85076
