### ISSUE TITLE
Theme blade instead of twig

### ISSUE THREAD

**Issue by NeiChan** [pyrocms/pyrocms#3961]
I followed this tutorial https://pyrocms.com/videos/series/theme-development/introduction-to-working-with-theme-assets. 

In the documentation of PyroCMS it's said that the order of finding files is twig then blade.php and it does. But when i change the {% block content %} into @section('content'). I only see raw text on the front page.

**Comment by huglester** [comment]
maybe because the parent template you were extending is still twig?

**Comment by NeiChan** [comment]
I found where I went wrong. Had to do {{ content }} in order to retrieve the content data.
Thanks for the advice!
