### ISSUE TITLE
[bug] [forms-module] Email layout not respected in notification setting 

### ISSUE THREAD

**Issue by daviesgeek** [pyrocms/pyrocms#3964]
When the email to the user is sent [here](https://github.com/anomalylabs/forms-module/blob/68ac8808339866a4b3aea1744d448a30eb1dfd44/src/Form/FormAutoresponder.php#L83), the email layout setting ([field definition](https://github.com/anomalylabs/forms-module/blob/68ac8808339866a4b3aea1744d448a30eb1dfd44/migrations/2015_09_21_200616_anomaly.module.forms__create_forms_fields.php#L52)) isn't respected; it just sends the email content as is, without wrapping it in the layout.

**Comment by RyanThompson** [comment]
This will probably be removed.. but I don't know just yet. Removing this for now cause it's on my internal list of todos
