### ISSUE TITLE
[datetime-field_type] Dates assigned to stream are being CREATED into the DB with the wrong time.

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#3969]
So doing a shit ton of digging.

`vendor/anomaly/streams-platform/src/Model/EloquentModel.php::saveModel` line 525. When $query hits this spot the `$query->model->attributes` have the correct UTC timestamps.

However,

in `vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php::performInsert(Builder $query)`

if you dump `$query` at the top of the function, it has the wrong timestamps.

**Comment by edster** [comment]
Did more digging, I was off a bit

in `vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php::performInsert(Builder $query)`

Line 1559 `$this->fireModelEvent('creating')` is changing the dates in the `$query` variable to the wrong format.

**Comment by edster** [comment]
FIXED

`vendor/anomaly/streams-platform/src/Entry/EntryModel.php` line 674

Change
$fieldType->setValue($this->getFieldValue($assignment->getFieldSlug()));
to
$fieldType->setValue($this->getRawAttribute($assignment->getFieldSlug()));

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/eb3e35c0156aa7ef0035cd4ad7c8c30078eeef2f

Thanks for your help! Killer job man.
