### ISSUE TITLE
[feature] [forum-module] Reaction/quick responses

### ISSUE THREAD

**Issue by daviesgeek** [pyrocms/pyrocms#3970]
A quick response feature à la GitHub style reactions would be pretty nice!

![image](https://cloud.githubusercontent.com/assets/2348508/20194874/0a8e6948-a749-11e6-89dd-20939939862b.png)

**Comment by RyanThompson** [comment]
https://github.com/AltThree/Emoji

**Comment by daviesgeek** [comment]
https://github.com/daviesgeek/emoji-plugin
