### ISSUE TITLE
[Multiple FT] -- When I set a multiple to a variable min number in lookup mode it doesn't care

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#3971]
If you assign a multiple ft to a variable and set the `min` required items under lookup to 3, then assign 2 to the entry, it will save.

If you set the `required` flag on the field, it enforces the 3 min rule.

**Comment by RyanThompson** [comment]
So tricky: https://github.com/anomalylabs/multiple-field_type/commit/7bff834f8aad2eb55757a4cfeb3f77a1be9bb8a2
