### ISSUE TITLE
Setting custom class to action buttons

### ISSUE THREAD

**Issue by angelbc123** [pyrocms/pyrocms#3974]
How i can overwrite action button classes in formBuilder?
protected $actions = [
       'my_button' => [
           'text' => 'Register',
           'class' => 'my class',
       ],
   ]; 
this code only adds 'my class' next to other classes on the action button but i want to overwrite them

**Comment by RyanThompson** [comment]
You can override the `type` property to be 'success' or whatever you like.

**Comment by angelbc123** [comment]
Thanks, it works but it produce this class
class = "btn btn-sm btn-advisor  my-class"
but i want to have only
class = "my-class" //in my case "btn btn-primary"
