### ISSUE TITLE
Robbo presenter CLI error when installed set to true

### ISSUE THREAD

**Issue by designbywilliam** [pyrocms/pyrocms#3975]
I have not really figured this one out. So i am logging my experience.

I am using Valet. And it has started to happen after an update. 

It's while i create an addon. It has happened while i use php artisan make:addon as well as when i use php artisan addon:install.

The error i receive:
```
[Illuminate\Contracts\Container\BindingResolutionException]
  Unresolvable dependency resolving [Parameter #0 [ <required> $object ]] in class Robbo\Presenter\Presenter
```

If i set installed to false, and then run php artisan addon:install, it works without errors. But if i then turn it back to true, i get the error message again.

Ill update with more info if possible.

**Comment by designbywilliam** [comment]
Reinstalled everything on homestead. Getting the same issue. Also getting this error when trying to do addon:install on previously installed and working modules.

**Comment by RyanThompson** [comment]
Is this with any addon? For example a core addon (redirects for example) does the same?

**Comment by designbywilliam** [comment]
Tried with that one, and yes.

```
vagrant@homestead:~/Code/xxx.dev$ php artisan addon:install redirects


  [Illuminate\Contracts\Container\BindingResolutionException]
  Unresolvable dependency resolving [Parameter #0 [ <required> $object ]] in class Robbo\Presenter\Presenter
```

**Comment by designbywilliam** [comment]
Reinstalled again, running the installer. Now it seems to work. At least i was able to create my module. Ill work on it and lets see what happens.

**Comment by designbywilliam** [comment]
I imported the old database. And the issue arise again. So its some crap somewhere in my old DB. Just cant figure it, so ill just use the new one.

**Comment by RyanThompson** [comment]
We settled this in slack but was due to custom theme registry or something if I recall ;-)
