### ISSUE TITLE
[feature] How about SPA & PyroCMS?

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#3978]
**Laravel** framework since 5.3 version have **vue.js** available out of the box.
**vue.js** framework is among other things allows you, as you might know, to scaffold a single page applications (SPA) and some kind of progressive web applications (PWA).

I can use **vue.js** with Pyro's back only instead of **Pages Module** for now, because for **vue** we need only one template. If I want to use **vue.js** I'll have lost all powerful of **Pages Module** template system. Also, for using **vue** we should generate correct Laravel's routing which structure should be clone of **vue-router** routes list, otherwise we'd not have correct working SPA. With **Vue** and **Vue Router** major update to 2 version, it makes a bit more difficult, if you wants to use nested routes in your app.
_I mean using of official **Vue Router** with `html5` (without `#`) history mode_

I want to ask, have anybody tried to scaffold SPA based on **Vue** with **PyroCMS**?

Also which is the best way to implement functionality like this? Maybe update some **Pages Module** code for it or better construct new module?

**Comment by RyanThompson** [comment]
I am all for moving Vue support in but alas - Im a little new to it. Im sure there will need to be some updates. 

Being as Vue is helpful in consuming an API for content that's why I've been pushing the finishing of the API module (tonight I suspect for alpha) so that I can test this kinda stuff better.

**Comment by Piterden** [comment]
I start to scaffold a module for Vue integration but I don't know, maybe I am on the wrong way.

Module will be used for add and edit `.vue` files which are separately (js from style from html) stored in database. If we'll listen for the `saved` eloquent event then we could write through twig template (its simple version is present) `.vue` file.
There are 2 sections in module for now. Partials (vue-components) using for store files which representing HTML-elements only, and Pages section also will be used to generate Laravel routing and its Vue Router frontend clone. This is finish for present time. 

I don't know how I going to realize nested routing. Also it will be little problem with showing prompt and real-time console output in panel or maybe it's better to make action buttons (to run compiler tasks and install packages).

Please [take a look at it](https://github.com/Piterden/vue_manager-module).
Your opinion is very important for me, because I don't like useless work.
Maybe you've made much smarter and cleaner solution...

**Comment by RyanThompson** [comment]
One thing I was thinking - you can actually route to a simple view and loop over pages doing something like `{{ page.content()|raw }}` in loop. Just a thought.

**Comment by Piterden** [comment]
Sorry, I suppose, my English is too bad to explain this correctly or maybe to understand your message. about the loop.

I don't need any loops over pages. Module's main purpose is to render `.vue` files and possibilities to start `npm i` (`yarn`) and `gulp watch` etc. commands from CMS control panel.
I want to write `.vue` files to FS on after save event entries of stream. If gulp will be launched in watch mode in moment of saving file, it will force file (that is currently being saved) (re)compilation in ES5.

Here is an example of listing of  **VueJS** application's sources files:
```yaml
pages/
    BlogPage.vue
    ContactsPage.vue
    Error404Page.vue
    IndexPage.vue
    OfficePage.vue
    PasswordResetPage.vue
    PostPage.vue
    ProfilePage.vue
    ProjectPage.vue
    ProjectsPage.vue
    SchedulePage.vue
    StationPage.vue
    StationsPage.vue
partials/
    Breadcrumbs.vue
    FooterArea.vue
    LoginForm.vue
    Messages.vue
    Modal.vue
    Navigation.vue
    PlayerElement.vue
    Preloader.vue
    SideMenu.vue
    StreamPlayer.vue
    UserMenu.vue
App.vue
directives.coffee
idbstore.coffee
main.coffee
mixins.coffee
router.coffee
routes.coffee
vendor.coffee
vuexstore/
    modules/
        equalizer.coffee
        menus.coffee
        posts.coffee
        projects.coffee
        stations.coffee
    actions.coffee
    getters.coffee
    index.coffee
    mutations.coffee
    mutation-types.coffee
```
We can divide all this files by 4 groups. From up to down:
- pages
- partials
- main
- vuexstore
If we will able to create this files with right code content (_don't forget about gulp_), we could create VueJS MVVM webapp, and VueResource module could have nice interaction with your `anomaly.module.api`'s controllers. 

Each of `.vue` component(file) can contents:
- **1** tag `<script>` _(JS|ES6|Coffee)_ 
- **1** tag `<template>` _(HTML|Jade|Pug|anything even Twig with NodeJS compiler)_
- **Ꝏ** tags `<script>` _(CSS|SASS|LESS|scoped)_

Because I'm a little bit newer in PHP, I have some problems:

1. I want user to have ability to edit `.vue` files separately for each language available inside `.vue` components, because this will allow us to use snippets inside the editor 
Could you please tell me is there any for storing information about files in streams besides database? Can I parse files directly in the file-system without using eloquent and receive this data in Pyro backend?

2. Also I will need to control `npm` and `gulp` with Pyro. This utilities have continuous cli output, so it should be very nice to see this output in real-time right inside the backend.
Don't you know is there any way to implement this real-time functionality?

So far, I can handle other tasks related to this module by myself except the problems mentioned above, so I would appreciate your help to deal with them.

**Comment by RyanThompson** [comment]
You can generate these files with event listeners - EntryWasSaved for example.

You can also register a new observer on the respective models and hook into it that way to dump your files. I hope this helps. You're talking over my head a little with the front end stuff. But if its files you need to generate - I can help with that!

**Comment by RyanThompson** [comment]
You can use the templates module as well (it's paid - if you're not presale let me know). It will generate template files tied into the view layer and asset service to use.. You can also route them - Seems like it would be very helpful for this kinda stuff.

Closing for now not sure there is an actionable item in here anywhere!

**Comment by websemantics** [comment]
Mixing in Vue.js with core PyroCMS is problematic from an architectural perspective first, as it's the case with Laravel for that matter (despite the fact Vue.js is shipped in by default). 

Both Pyro and Laravel are described as MVC frameworks, .. Laravel uses Blade and Pyro uses Twig. To change that, a great deal of work must be invested into loosening that dependency. 

To do that, you'll inevitably have to remove the `MV` from the `MVC`, which leaves you essentially with an equivalent of the API Module as Ryan mentioned. I wrote something along these lines long time ago, http://websemantics.ca/php-mvc-frameworks-vs-javascript-frameworks.

Essentially you'll need to build everything from scratch for whatever feature Pyro currently offers out-of-the-box. Having said that, one can see great advantages of using Vue.js to enhance user experience in some scenarios that local to Modules (not core) including an SPA Pages Module. 

I thought I  share my thoughts on the subject, I hope it was helpful :)

**Comment by websemantics** [comment]
Just learned about this, https://nuxtjs.org, server-side Vue.js, ... well, that's interesting.
