### ISSUE TITLE
[feature] Entry layout

### ISSUE THREAD

**Issue by ThinkGraphical** [pyrocms/pyrocms#3980]
I would love something like this: https://devot-ee.com/add-ons/entry-layout for the entry views.

So you can easily reorder the fields, float multiple fields next to each other (instead of each fieldtype on a new line), create different views for each role, etc...

Maybe we could discuss this a bit further here?

**Comment by RyanThompson** [comment]
I will be adding column support back again very soon.

**Comment by RyanThompson** [comment]
Added: https://github.com/anomalylabs/streams-platform/commit/a22c50278a7dc58a96b15f524b7f0d218c07b07e
