### ISSUE TITLE
Table filter of relationship field type using LIKE?

### ISSUE THREAD

**Issue by ndlinh** [pyrocms/pyrocms#3981]
In Posts module, I have 2 categories with ID is 1 and 11.
I has some posts in both categories. When I filter by category with id = 1, all posts of category 11 also showing in table.

I'm using PyroCMS 3.1.3

**Comment by RyanThompson** [comment]
This might expand into a different test but the relation but I think this should be a good starting fix: https://github.com/anomalylabs/streams-platform/commit/6f3cf6ed6fc06c2b2f007ddf78e6d1242d68b7e5

Good catch!

**Comment by ndlinh** [comment]
@RyanThompson Thanks for this fix. Work perfect.
