### ISSUE TITLE
Validate database input on install

### ISSUE THREAD

**Issue by lenvanessen** [pyrocms/pyrocms#3985]
Hi,

I was installing Pyro on my machine, serving trough MAMP.
But when i misspelled the databasename it proceeded with the installation generating this 500 error, instead of giving me feedback what was wrong.

Would be great if there was validation inside the installer about these problems, instead of a 500 error after submitting.

Stack trace below:

[01-Dec-2016 20:44:07 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: No hint path defined for [streams]. in /Users/USERACCOUNT/Sites/pyrocms/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:112
Stack trace:
#0 /Users/USERACCOUNT/Sites/pyrocms/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(90): Illuminate\View\FileViewFinder->getNamespaceSegments('streams::errors...')
#1 /Users/USERACCOUNT/Sites/pyrocms/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(76): Illuminate\View\FileViewFinder->findNamedPathView('streams::errors...')
#2 /Users/USERACCOUNT/Sites/pyrocms/vendor/laravel/framework/src/Illuminate/View/Factory.php(174): Illuminate\View\FileViewFinder->find('streams::errors...')
#3 /Users/USERACCOUNT/Sites/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\View\Factory->make('streams::errors...', Array)
#4 /Users/USERACCOUNT/Sites/pyrocms/vendor/anomaly/streams-platform/src/Exception/ExceptionHandler.php(69): Illuminate\Routing\ResponseFactory->view('str in /Users/USERACCOUNT/Sites/pyrocms/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 112
[01-Dec-2016 20:45:44 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: No hint path defined for [streams]. in /Users/USERACCOUNT/Sites/pyrocms/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:112

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/installer-module/commit/53988fba5bf258cc866ccc483561bb4dcce2e5c8
