### ISSUE TITLE
[BUG?] Table builder returning duplicated rows

### ISSUE THREAD

**Issue by agustindidiego** [pyrocms/pyrocms#3987]
This happens when searching if slug field is appended on search fields filters.
I believe this happens because of the way the translations table is joined. Currently it makes a left join and filters the current locale as a WHERE statement; when it probably should be doing an inner join with the locale filter within the join.
You can reproduce this by adding 'slug' to the PostTableBuilder filters under 'search'->'fields'.
Example generated sql query:
```sql
select `default_posts_posts`.* from `default_posts_posts` left join `default_posts_posts_translations` on `default_posts_posts`.`id` = `default_posts_posts_translations`.`entry_id` where ((`default_posts_posts`.`slug` LIKE '%Test%') or (`default_posts_posts`.`tags` LIKE '%Test%') or (`default_posts_posts_translations`.`locale` = 'es' and `default_posts_posts_translations`.`title` LIKE '%Test%') or (`default_posts_posts_translations`.`locale` = 'es' and `default_posts_posts_translations`.`summary` LIKE '%Test%') or (`default_posts_posts_translations`.`locale` = 'es' and `default_posts_posts_translations`.`meta_title` LIKE '%Test%') or (`default_posts_posts_translations`.`locale` = 'es' and `default_posts_posts_translations`.`meta_keywords` LIKE '%Test%') or (`default_posts_posts_translations`.`locale` = 'es' and `default_posts_posts_translations`.`meta_description` LIKE '%Test%')) and `default_posts_posts`.`deleted_at` is null order by `publish_at` desc limit 15 offset 0
```

**Comment by RyanThompson** [comment]
The only problem with an inner join would be that the entry would not get returned at all if the locale needed didn’t exist.

**Comment by RyanThompson** [comment]
The search filter likely needs a distinct addition

**Comment by RyanThompson** [comment]
Can you try adding $query->distinct();

 to the \Anomaly\Streams\Platform\Ui\Table\Component\Filter\FilterQuery near the top so its done for ALL filtering?

**Comment by agustindidiego** [comment]
Perfect, adding "distinct" to the query did the trick.
I'll make a PR

**Comment by agustindidiego** [comment]
Ok, sorry. I cannot create a PR :P
But I tested adding the distinct call, and it works.

**Comment by RyanThompson** [comment]
Perfect! Ill make sure it get's in for ya ^_^

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/8d713f7c621e53ea232d4ec1d905a53cae92733a
