### ISSUE TITLE
[streams-platform] ValidationException throws 500

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3992]
If validation is done in custom controller, and it does not pass, error 500 is thrown but only if debug mode is off.

https://github.com/anomalylabs/streams-platform/blob/master/src/Exception/ExceptionHandler.php#L69

**Comment by huglester** [comment]
we probably need to handle FormValidation here too? 
You use form requests?
@RyanThompson

**Comment by keevitaja** [comment]
Yes, i use form request validation.

**Comment by RyanThompson** [comment]
This has been fixed
