### ISSUE TITLE
Settings and .env problems

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#3993]
Steps to reproduce

1. I create for example enabled locales in settings via ADMIN (en + lt) - OK
2. I LOCK them in the .env ENABLED_LOCALES="lt,en"
3. I go to the settings - I see those 'LOCALES' options as 'disabled'
4. but when I save the options, DB options are get overriden with 'empty' data
(if you have disabled data, this is posted ALWAYS as empty, we need to skip those 'ENV' fields when saving I think)
5. setting_value('streams::enabled_locales', []) - returns [] now
6. If I remove from .env ENABLED_LOCALES="lt,en"
7. I go to settings, I see NONE enabled lcoales

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/settings-module/commit/92bf5c1e007a19bb0371377fbd201e0bdd52c8d6

**Comment by RyanThompson** [comment]
Also fixed preferences though rare cases
