### ISSUE TITLE
Access form object from form wrapper.twig?

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#3994]
So there is a file in streams platform:
./vendor/anomaly/streams-platform/resources/views/form/partials/wrapper.twig

but form is not there?

{{ var_dump(form) }} gives null

**Comment by RyanThompson** [comment]
It's because it's too big to dump in the view. Use something like `{{ get_class(form) }}` to get clues instead. It's a `FormPresenter` though.
