### ISSUE TITLE
Validator and $_POSTed data

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#3995]
Hello

so we have a validator, OK.

1. And we try to edit the 'First name' (object already had first name, 'John Doe')
2. I remove the first_name
3. press save
4. Have validation - that name is required, but value I see the 'Jogn Doe'
5. but it should contain $_POSTed data - no name.

Thanks

**Comment by RyanThompson** [comment]
Can you give me a step by step on how to replicate this? I am unable to produce the same results :-(

**Comment by RyanThompson** [comment]
Is this an issue?

**Comment by huglester** [comment]
I will leave feedback soon

**Comment by huglester** [comment]
Hello,
1. this somehow WORKS OK on backend.
2. Let's say we want to modify Entity Customer (via frontend)

I have in twig:

```
{% set form = form('form_customer').redirect(url_current()).get() %}

{{ form.renderFIelds()|raw }}
```
Here - everything work. It loads data from entity and shows values. 
This entity ALREADY HAS FIRST NAME specified.
so it loads, for example: Jaroslav

Now I remove first name value, press SAVE
it sais - FIRST NAME IS REQUIRED (this is OK.)
But value in FIRST NAME shown is again "Jaroslav", not empty one.

cant you reproduce this?

thanks

**Comment by RyanThompson** [comment]
You need to `skip` the field by using `skipField(slug)` or `skips(fields)`.

**Comment by RyanThompson** [comment]
Just because the field doesn't display doesnt mean it's processing is skipped basically is what I think you're running into.
