### ISSUE TITLE
[select-field_type] Select field type has wrong options for theme layouts

### ISSUE THREAD

**Issue by samharrison7** [pyrocms/pyrocms#3996]
The theme layout field for post and page type entries has incorrect keys that use a dot instead of a slash as a separator, e.g. `theme::/layouts.default` instead of `theme::/layouts/default`. This causes templates to break, e.g. when trying to extend the theme_layout using Twig (`{% extends post.type.theme_layout.key %}`).

The source of the error is in `Anomaly\SelectFieldType\Handler\Layouts` (line 48) and replacing this with the following fixes the error, but I didn't want to submit a PR in case it causes errors elsewhere:

![image](https://cloud.githubusercontent.com/assets/3359948/20967401/31f25b0a-bc77-11e6-90cc-e44714eb7e60.png)

**Comment by RyanThompson** [comment]
This would be a super widespread issue I think if this were the case. I do see a wonky leading slash in your example. Does your option dropdown indeed have that leading slash? `theme::/layouts.default`

The dots are used in Laravel to provide ambiguity for DIRECTORY_SEPARATOR stuff. Because your fix - would break windows for example which uses back slashes.

I think the issue might be the leading slash. The trim should be taking care of that though..

Maybe try `trim($path, ['/', '\\']);` instead?

**Comment by samharrison7** [comment]
Thought there might be something more going on then I could see! The leading slash is there in my option dropdown and using your suggested trim seems to do the trick (though the second param has to be a string).

**Comment by RyanThompson** [comment]
Can you tell me - is this consistent across all your installations? Are you on windows on one and linux on the other? The reason being is the directory separator should catch that. This fix suggests that your environment has both \ and / in the path?

**Comment by samharrison7** [comment]
I'm just on Windows (WAMP), so it should be backslashes all the way, but `$theme->getPath('resources/views')` is actually returning `C:\wamp\www\pyrotest\core/pyrocms/starter-theme/resources/views`, which is odd.. Same for addon themes except the backwards slashes become forwards after the addons dir.

It's consistent across all my installations (four of them, one completely fresh) but as I say I'm only using WAMP.

**Comment by RyanThompson** [comment]
Ill patch the fix. Might as well edge case as it may be ^_^

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/select-field_type/commit/01894c35eb635a72cdad42d578742147eed77b65
