### ISSUE TITLE
country-field_type FORM display issue 

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#3997]
Hello,

So now the country field has this display: http://pic.webas.lt/webas.lt-7937180165.png
Maybe it would be good to have a dropdown? (even better select2 dropdown or so - but this can be separate feature request :))

usage example in migration:
`'country' => 'anomaly.field_type.country',`

Thank you

**Comment by RyanThompson** [comment]
Use the country and state both default to TEXT mode by default because it’s just so much simpler. It validates against existing state / country options. 

I would love to see select2 make it in but the theme has been a chore to work with and it’s not super high on my priorities :-(
