### ISSUE TITLE
[docs] [field-type] Datetime field type is missing docs for min and max

### ISSUE THREAD

**Issue by daviesgeek** [pyrocms/pyrocms#3998]
Min and max are supported config options for the date/time picker, yet they aren't documented!!

https://github.com/anomalylabs/datetime-field_type/blob/master/resources/js/input.js#L15
![image](https://cloud.githubusercontent.com/assets/2348508/20996441/7cbd83cc-bcb2-11e6-9824-9cf5e290af8f.png)

**Comment by RyanThompson** [comment]
Added
