### ISSUE TITLE
[Relationship field] non title_column doesn't use entry.getTitle() but takes id for dropdown

### ISSUE THREAD

**Issue by stijntilleman** [pyrocms/pyrocms#4000]
I wanted to create a relationship field to an entry with a `first_name` and `last_name`, but no real column I could use as `title_column`.

```php
  //  ContactUserModel.php
  public function getTitle()
  {
      return "{$this->first_name} {$this->last_name}";
  }
```

If I use this entry in a relationship the dropdown is filled with `id` instead of the expected `title`

ps: this is the same thing for the default table overview. Instead of using the title it always uses id as default `title_column`

**Comment by RyanThompson** [comment]
Fastest way to do something like this now is just use your own options handler:

http://pyrocms.com/documentation/relationship-field-type/v2.1#introduction/configuration/option-handlers

I have plans to make this more versatile but nothing concrete yet - small change but needs testing & thought ^_^
