### ISSUE TITLE
[relationship-field_type] Default value with disabled on true

### ISSUE THREAD

**Issue by michiel1995** [pyrocms/pyrocms#4001]
When you want do something like:
```
$fields['company'] = [
                    'disabled'=> true,
                    "type" => "anomaly.field_type.relationship",
                    "config" => [
                        "related" => CompanyModel::class,
                        "default_value" => $company,
                        "mode" => "dropdown",
                    ],

                ];
$builder->setFields($fields);
```
The disabled prevents it from processing all together since value could be snuck in.

**Comment by RyanThompson** [comment]
I think this should be left alone. If you wanna set that value you can do so with a callback handler on the builder - using onSaving -> set the value on  the entry. 

$entry = $this->getFormEntry() // where $this is the builder
