### ISSUE TITLE
[forms] Fail gracefully when forms are not found in the cache.

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#4004]
Right now (or very soon) the forms will only expire in the cache after 24 hours. I think that will really help with this issue, but just in case I think it might be a good idea to have the form fail gracefully when they are not found in the cache, and just let the user know that the page needed to be refreshed before they could submit a specific form.

So far I've only found this on Contact Us forms when I leave the browser open for a long time, but still something I'd like to visit soon.

I'm pretty sure it is in the GetFormCriteria when it calls $factory->make and the parameters haven't been populated by the cache.

Something like that.

**Comment by RyanThompson** [comment]
Merged in! We can increase as needed in the future.
