### ISSUE TITLE
Exception when using checkboxes as a field in contact-form

### ISSUE THREAD

**Issue by andreasotto** [pyrocms/pyrocms#4006]
When using a checkbox (with using checkboxes field type) in a contact-form, there occurs an "Array to string" Exception with http error 500 upon POSTing the form. That looks like pyrocms expects a string, but checkboxes is of type array of course.

That means it is currently not possible to use a checkbox within a contact-form (btw, i'm expecting the same error with a select field, too).

**Comment by RyanThompson** [comment]
Hey thanks for the catch! I updated checkboxes and select to override the __toString to use values (select was returning key by default) and also updated the contact plugin.

Should be good to go!
