### ISSUE TITLE
Exception when field name starts with a digit

### ISSUE THREAD

**Issue by andreasotto** [pyrocms/pyrocms#4007]
There is an exception when you create a field name starting with a digit.

To reproduce just create a field with for example `5images` as a name / slug and multiple upload as file type.
Then assign it to a page and try to (re)load that page in the frontend => exception.

Renaming that field to something like `images5` fixes the problem. That looks like field names (or table names?) are not allowed to start with a digit.

**Comment by RyanThompson** [comment]
I am able to use fields starting with numbers just fine. What's the detail of the error? And what's your DB version / type?

**Comment by RyanThompson** [comment]
If you have any more information on this let me know ^_^
