### ISSUE TITLE
[streams-platform] Adding to asset collection by string

### ISSUE THREAD

**Issue by samharrison7** [pyrocms/pyrocms#4008]
It'd be nice to have a method to be able to add to asset collections by inputting a string of inline styles/scripts, instead of from a file path. For example, something like this:

```
{{ asset_add('styles.css', '$bg-color: #fff; body { background-color: $bg-color; }' }}
```

Or more realistically, inputting some custom styles from a field:

```
{{ asset_add('styles.css', post.custom_styles) }}
```

**Comment by RyanThompson** [comment]
Try something like this (after updating): 

    {{ asset_add('styles.css', parse(your_var or string).getPath()) }}
