### ISSUE TITLE
[pyrocms] Addons dependencies. Install/uninstall.

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4009]
I have collided with some strange behavior of system, when I tried to uninstall `anomaly.module.pages`.

First - I knew it only in that time - I can't just uninstall `anomaly.module.pages` through composer, with editing `composer.json`. Before this I need to uninstall module with `php artisan module:uninstall` command.
It would be much better if composer, before removing module, initialising this uninstall command from within itself. Otherwise, I get an exception even calling clear artisan without any parameters.

But, you definitely should have known it, there is another one problem with `anomaly.module.pages`. More specifically, it is dependency of `anomaly.extension.default_page_handler` from pages module.
And then there was the same situation - artisan was lying, etc.

So, I suppose it would be much-much better, if composer had making a prompt about removing additional packages have become unmeeted dependencies to the administrator. And with the success of its consent did all the boring operations with dependencies automatically...

**Comment by RyanThompson** [comment]
I think what you've done with adding dependencies (even though pages to default_page_handler is not a dependency - just needs any handler) will suffice. Let's revisit this as needed once we get those worked in.

**Comment by Piterden** [comment]
Yes, looks like a little mistake.

Maybe would be better if I'll make a list of dependencies and then you'll add it to configs?

I reasoned it like this: if you have `use` of `Aclass` in at least one of classes of `Bclass`, then when this code (of `Bclass`) runs - it'll throw an exception, and so then `Bclass` have dependency. This dependency is `Aclass`.

**Comment by RyanThompson** [comment]
Ya but composer dependecies being filled out will prevent this and its already done - just need to fill it out

**Comment by Piterden** [comment]
If it's routine, than I can help find an executor without your PHP skills, if you wish))
