### ISSUE TITLE
[navigation-module] link target is set to what ever the text is

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#4010]
Hello!

Something has been messed up bigtime.

`menu('mymenuslug')` will generate anchors link that:

```        <a
                href="http://horses.app/a"
                class=""
                target="Open in the current window."
                
                        >
```

**Comment by RyanThompson** [comment]
Resolved - reverted my "fix": https://github.com/anomalylabs/select-field_type/commit/18ffa08f1b2a0d80e8e8dea9da14c285c30422b5
