### ISSUE TITLE
[editor-field_type] Repeater causing issues after subsequent rows

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4014]

**Comment by RyanThompson** [comment]
@bloveless what did you come up with for repeating editor fts in ajax load?

**Comment by bloveless** [comment]
I cheated hard on this one lol! I do the Ajax request, and before the load the results on the page I remove the ace.js script if(ace) is true. Check your texts where we were talking about pros/cons of grid being free. I linked to a line of code in bitbucket. That is the exact code of how I did it.

**Comment by RyanThompson** [comment]
Mother of pearl..

**Comment by bloveless** [comment]
Lol yeah it's hard because it has to happen on the client side since that is the only way to check if ace has been loaded already.

**Comment by RyanThompson** [comment]
I was trying to do the same with the input.js for Editor and writing the script but.. no worky. I believe it’s cause it’s firing in `load` before it can detect form the main body that ace is indeed loaded already.

F
