### ISSUE TITLE
Feature: horizontal ruler in Pages section for layouting

### ISSUE THREAD

**Issue by andreasotto** [pyrocms/pyrocms#4015]
I'd like to suggest a very simple thing:

To have a horizontal ruler as a layout element in the Admin `Pages` section, just for styling reasons. This would help me / the users to seperate groups of pages. For example i have some landing pages in the Pages list, and i'd love to optically seperate them from the regular site's pages.

That ruler should be drag'n'dropable just like a Page item.

**Comment by RyanThompson** [comment]
What about collapsable trees? Thats something that's in the next release already!

<img width="287" alt="screen shot 2016-12-20 at 3 34 11 pm" src="https://cloud.githubusercontent.com/assets/1099967/21368825/cb386848-c6c9-11e6-9762-e298ff90f341.png">

**Comment by RyanThompson** [comment]
Cookie persistent too

**Comment by RyanThompson** [comment]
Closing this for now - the collapse in 3.2 is a big improvement.
