### ISSUE TITLE
[multiple-field_type]

### ISSUE THREAD

**Issue by sandor93** [pyrocms/pyrocms#4016]
When editing stream entries, the multiple field type's value table will contain the related models multiple times, when using custom ValueTableBuilder.  
composer: "anomaly/multiple-field_type": "2.0.*",

![Alt text](https://monosnap.com/file/nAcuoRxE5QuMTJBiwqDLzI5NAp2eI3.png)

My current solution for this is to add :
$query->distinct($table . 'related_id');
to OnQuerying function of the ValueTable builder

![Alt text](https://monosnap.com/file/CSWtWxZckdXCGkkqAylOcBY0gJAEts.png)

**Comment by RyanThompson** [comment]
Hmm That can definitely be added in the FT too. Ill check it out thanks!

PS that's one heck of a table column you have there ;-)

**Comment by sandor93** [comment]
My original intention was to extend the multiple relation with an extra price column. Unfortunately I did't find a clean solution for this so I am storing the prices in a separate column as a json sting. I think it would be beneficial to add a possibility to add custom columns to multiple field types.

Thanks for your response :-)

**Comment by RyanThompson** [comment]
I would handle this as a migration after the fact ^_^
