### ISSUE TITLE
[feature] [streams-platform] No hard limit on available Image manipulation functions

### ISSUE THREAD

**Issue by pepijnolivier** [pyrocms/pyrocms#4019]
The Image class relies on the awesome Intervention package to do any image manipulation.
However, PyroCMS allows only a subset of the functionality available in this Intervention package.

The list of 'allowed methods' is hardcoded [here](https://github.com/anomalylabs/streams-platform/blob/master/src/Image/Image.php#L105)

The problem I'm currently having, is that I need to call the [resizeCanvas](http://image.intervention.io/api/resizeCanvas) method, which is not in the list of allowed methods.. When I add it to this list, I can successfully call the method, and my code works as expected.

However, I just touched the core code, and whenever I'll run `composer update`, my changes might get overwritten.

---

Proposed solution: this list of 'allowed methods' could be moved to a config file (`image.php`), or better yet, removed. (Why are we limiting the available functionality?) :-)

**Comment by RyanThompson** [comment]
Resize canvas has been added recently. The issue I was originally having that the allowed array fixed was the magic methods. It's easier to determine what non-defined function is intended for intervention and what isn't so we can work with the `Image` class more predictably. Feel free to add any others necessary for now!
