### ISSUE TITLE
[repeater-field_type] Issue with file field type

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#4020]
File does not work with the field type. If you have it in there, and have a row saved, the next time you load the page no assets will load and you will get a 500 error if you look at page source. No logs are thrown.

**Comment by RyanThompson** [comment]
What's the output with debug enabled?

**Comment by edster** [comment]
nothing =/

**Comment by edster** [comment]
I will also note that file was not required, tested when a file was not assigned, but the rest of the row had values.
