### ISSUE TITLE
[repeater-field_type]: streams::models/filter does not exsist.

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#4022]
On `http://www.martello.group/admin/repeaters/assignments/`, when you click add field you get a 500 error, logs show

```[2016-12-22 19:16:29] local.ERROR: Twig_Error_Loader: Template "streams::modals/filter" is not defined in "C:\Sites\martello_group\addons\shared\anomaly\repeater-field_type\src/../addons/anomaly/repeaters-module//resources/views/admin/assignments/choose.twig" at line 10. in C:\Sites\martello_group\vendor\twig\twig\lib\Twig\Loader\Chain.php:115```

**Comment by RyanThompson** [comment]
Use the older version - this is for 3.2
