### ISSUE TITLE
[streams-platform] Recursion issue with ajax loaded scripts

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4023]
I have tables in 3.2 loading with this at the top: 

```
$(function () {

    // Focus on the first filter input.
    $('#filters').find('input:visible').first().focus();
});
```

Which is super nice. Less clicking. But when ajax tables are filtered this content / script is loaded over and over and it ends up taking over the focus a bit. How can I make sure it loads / fires only once?

**Comment by RyanThompson** [comment]
I have also tried: 

```
$(document).on('ready ajaxComplete', function () {

    // Focus on the first filter input.
    $('#filters').find('input:visible').first().focus();
});
```

With stopPropagation and no go.

**Comment by pepijnolivier** [comment]
> when ajax tables are filtered this content / script is loaded over and over
Is this script being fetched and executed every time ? Maybe this is the issue (script should only be fetched on initial page load, but not on ajax calls).

**Comment by RyanThompson** [comment]
It's being included in the return yes. Question is - how would that look? How can I keep things simple / tight and prevent duplication?

Here is how ajax returns are usually loaded (this is the layout): https://github.com/anomalylabs/streams-platform/blob/master/resources/views/ajax.twig

As you can see it loops over scripts.. problem is we need this on the first but not subsequent times. 

One of my first thoughts would be to mark all inputs / code with "is-initialized" (class, data attr, whatever) and only process those not initialized..
