### ISSUE TITLE
insert chart.js content into pages

### ISSUE THREAD

**Issue by solasoli** [pyrocms/pyrocms#4025]
Hi, 

i've been updating websites recently, and i found the website CMS are pyro. Im new at this so enlighten me please.

i wanted to change some content into animated chart with chart.js and included js files withing the themes folder so does the footer.php

> `<script type="text/javascript" src="../js/chart.js"></script>` -----> script included'

and i already insert chart.js into themes js folder too, but when i go into post modules and insert the js code to display the chart, it turns to nothing. Is there anything i can do to make this happen? sorry for my broken english.

Thanks

**Comment by RyanThompson** [comment]
You can add this in your footer or elsewhere. Code in the post JS field needs to be inline. It strips `code` blocks.
