### ISSUE TITLE
[streams-platform] Install bower and npm packages on addon install

### ISSUE THREAD

**Issue by daviesgeek** [pyrocms/pyrocms#4027]
I really don't like committing third-party code to my addon's repository, as there's no need when package managers like bower and npm exist.

It would be nice to have the addon installer run `bower install` and `npm install` (`yarn` if available) inside the addon's directory after installation. It would probably need to check first to make sure that the `bower.json`/`package.json` file(s) exist, and then run the appropriate command.

It would also be pretty great to use yarn instead of npm if it's installed _and_ there's a `yarn.lock` file.

**Comment by daviesgeek** [comment]
I'm going to test this out on my own branch and see how it works. I'll track progress on this issue.

**Comment by RyanThompson** [comment]
We need to get more people involved in this discussion!

**Comment by daviesgeek** [comment]
I agree! This is something I definitely want to see added!

How's the best way to get eyeballs on this?

**Comment by RyanThompson** [comment]
Blast people about it lol

**Comment by edster** [comment]
composer needs to run to, I've run into it where I tried to use composer for the addons, but I don't add it to composer.json in core.

**Comment by daviesgeek** [comment]
@edster that's just if you drop the folder into `addons/ref`? And you're not installing it via composer?

**Comment by edster** [comment]
correct

**Comment by RyanThompson** [comment]
@edster composer can not handle dependencies for anything outside of the root composer.json file. That's documented and he's not budging on it.

**Comment by edster** [comment]
bastard lol. Ok well just wanted to throw that in there.

**Comment by RyanThompson** [comment]
addons is for drop in support only - you can ship with it's own dependencies included but that's generally not good cause others might conflict.

**Comment by edster** [comment]
Well we won't really have a choice. The store works by drop in so.

**Comment by RyanThompson** [comment]
The vast majority do yes

**Comment by RyanThompson** [comment]
In fact API is all I can think of right now that does not.
