### ISSUE TITLE
[streams-platform] over zealous runtime caching

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#4033]
If I create a new element after getting the elements then try and get the elements again then I don't get the new elements. Even if I flush the cache between the two gets.

I.E.

GetFormSubmissions (contains 2 elements)
CreateFormSubmission
FormSubmissions->getModel()->flushCache()
GetFormSubmissions (contains 2 elements, but should be 3)

We talked about this via SMS and this is what @RyanThompson said:

```
Ya the flush cache needs to remove its keys from runtime too
So I need a mutator and to make sure they are keyed with collection keys if not already
```

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/e251aa4e3dba905bd7cf5914c9e6bde20f17bc9c
