### ISSUE TITLE
Documentation: field type integer

### ISSUE THREAD

**Issue by rabol** [pyrocms/pyrocms#4037]
The documentation for field type integer is not correct: https://pyrocms.com/documentation/integer-field-type/v2.1

Integer cannot have decimals

**Comment by rabol** [comment]
There is is actually also something wrong with the implementation

The presenter tries to get decimal points from the config, but the config does not have a 'point' configuration.

The presenter tries to get decimals from the config, but the config does not have a 'decimals' configuration.

**Comment by RyanThompson** [comment]
Fixed and patched the field type!
