### ISSUE TITLE
[documentation] Finish #the-basics/routing

### ISSUE THREAD

**Issue by rabol** [pyrocms/pyrocms#4038]
The link on page: https://pyrocms.com/documentation/streams-platform/v1.1#core-concepts/service-providers to get more information on routing https://pyrocms.com/documentation/streams-platform/v1.1#the-basics/routing does not give more information

**Comment by RyanThompson** [comment]
Oh my - need to finish that section!

**Comment by RyanThompson** [comment]
Publishing momentarily

**Comment by RyanThompson** [comment]
https://pyrocms.com/documentation/streams-platform/latest#the-basics/routing
