### ISSUE TITLE
Documentation: FiresCallbacks::on() 

### ISSUE THREAD

**Issue by rabol** [pyrocms/pyrocms#4039]
This make sense as a callback is created 'before_starting' then on the call the 'beforeStarting()

// Example of using a callable string
$callable->on('before_starting', 'App\Example@test');

$callable->beforeStarting();

This does NOT make sense

// Example of using a Closure
$callable->on('querying', function(Builder $query) {
    $query->where('modifier_id', $this->example->getId());
});

$callable->sayHello('Ryan!'); // Hello Ryan!

what is the sayHello() ???

**Comment by RyanThompson** [comment]
Fixed! Cache should bust soon. Makes much more sense now ^_^
