### ISSUE TITLE
[Feature request][Streams platform] module:install should fail if already installed.

### ISSUE THREAD

**Issue by stijntilleman** [pyrocms/pyrocms#4040]
As is it now the `module:install` doesn't check if a module is already installed, it just re-installs the module and cleans the database. 

Wouldn't it be "better" to ignore already installed modules, or have an extra flag `--force`.

### Proposal

Add a check in `module:install` to ensure modules that are installed already aren't re-installed.  

### Real world example:

We use continuous deployment/integration. We have 3 environments: development, staging and production. When we have tested a module on development and staging the module is deployed to production via a script. This script should automatically install the new module. First time deploy/install this gives no problem. When we deploy a second time the module defined in the install script loses all data, because it is re-installed.
Changing the script after every deploy could be an option, but very illogical imo. This would mean you have to comment out every `module:install` call in the script or the actual script (historical) data is lost. This script could be handy to replicate a full clean environment in the future for testing purposes.

**Comment by RyanThompson** [comment]
Consider it done!

**Comment by RyanThompson** [comment]
I think this should throw an exception if already installed / return error message to the command prompt.. 

Thoughts?

Failing quietly is too sneaky.

**Comment by stijntilleman** [comment]
Throwing an exception should do the trick.

I'm personally not a fan of failing silently, it should at least show an already installed message.

**Comment by RyanThompson** [comment]
This should do it: https://github.com/anomalylabs/streams-platform/commit/c300d4079744e09d7601459e41013f0313360954
