### ISSUE TITLE
Settings: Debug mode does not work

### ISSUE THREAD

**Issue by rabol** [pyrocms/pyrocms#4043]
The UI settings for Debug does not work as expected.

if the APP_DEBUG is set in .env, then one get the debugbar, but then the setting is 'locked in the UI and there is a messages:  This setting is currently locked.

If you removed the APP_DEBUG from the .env file, then the settings become available in the UI, but setting debug to on, does not have any effect.

**Comment by RyanThompson** [comment]
Closing this as there is a duplicate that's newer.
