### ISSUE TITLE
[feature] [streams-platform] Add JSON-serialization of UI objects

### ISSUE THREAD

**Issue by daviesgeek** [pyrocms/pyrocms#4049]
Add JSON serialization of the UI objects in the `Anomaly\Streams\Platform\Ui` namespace to allow access to the UI stuff via a frontend SPA.

Ultimately, I'd love to see _everything_ be API accessible, so that I can, in theory, build my own control panel.

**Comment by Piterden** [comment]
Can't we do it self?

**Comment by stefanpkc** [comment]
You can of course, @Piterden, but if it's in the official release and with the blessing of @RyanThompson. It would be better I think. A discussion is helpful to determine if there's a standardized way for it that can work almost everytime for 80% of the people.

We have to distinguish between the cp and what happens on the site. What will we tackle and what won't we do? And what has the highest priority?

**Comment by RyanThompson** [comment]
I am going to JSONify everything but will pry use the __toString method instead of the package we talked about.

**Comment by daviesgeek** [comment]
@RyanThompson Sounds good to me!

**Comment by sergey-koretsky** [comment]
well may be after this i'll move back to Pyro
but for now simple wordpress is more friendly for SPA-based modules in admin area

**Comment by stefanpkc** [comment]
@RyanThompson what package was that?

**Comment by RyanThompson** [comment]
@stefanpkc I honestly can't remember - but I will be implementing http://php.net/manual/en/class.jsonserializable.php instead.

@sergey-koretsky I highly doubt that :-/ But consider what you might be losing as a result of using wordpress.. a whole lot of would think :-/

**Comment by RyanThompson** [comment]
Heh.. those smilies line up perfectly on top of each other :-P
