### ISSUE TITLE
Unable To Login

### ISSUE THREAD

**Issue by psaunders** [pyrocms/pyrocms#4050]
Went to login today and am getting this error.

![image](https://cloud.githubusercontent.com/assets/424956/21964625/a86e1a98-db1d-11e6-83b4-cccd5eb10a0c.png)

Have granted full permissions to write on the storage directory. These folders and subfolders don't appear to exist.

**Comment by RyanThompson** [comment]
Look like you’ve got a permissions issue there. Make your storage folder writable. 

Also check the user your CLI is running as. It’s usually from running a CLI command that alters files and does so as root or whoever is running it.

**Comment by psaunders** [comment]
Yeah I figured out it's another example of the CLI vs www-data permissions issue that you get with logs. It's so common I kind of wish it was in the install docs for laravel.

I've found the easiest way to fix this is to go into your project root and:

Add your own user to the www-data group
```
usermod -a -G www-data yourusername
```

Set the group for storage to use www-data
```
sudo chgrp www-data storage/ -R
```

Set the new content in the directory to inherit these group permissions
```
sudo chmod g+s storage/ -R
```

Turn on file access control
```
setfacl -d -m g::rwx storage/
```

You can repeat that on any other folders that may be getting written to by both the CLI and the webserver (bootstrap/cache)

**Comment by RyanThompson** [comment]
Good stuff! I've set that aside and will add it to our own docs. Thanks ^_^
