### ISSUE TITLE
[files-module] invalid csrf-token on upload

### ISSUE THREAD

**Issue by stevemo** [pyrocms/pyrocms#4052]
In upload.js line 20 the token is fetch from meta tag but no meta tag is set in the admin accelerant-theme
'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')

But in the file-module upload.js line 20 the csrf-token is taken this way 'X-CSRF-TOKEN': CSRF_TOKEN and it is working.

p.s. I would have done a pull request but not sure on how to do this ;-)

**Comment by RyanThompson** [comment]
Hey Steve thanks for the bug report! Fixed: https://github.com/anomalylabs/files-module/commit/f8bfe62d19f3f40927bbbfaf35bb1a4997e53653

**Comment by stevemo** [comment]
same problem exist in the files-field_type and file-field_type module, 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/files-field_type/commit/1e95bd1e47a8ae1c079913110c1456a6aee0c50f
