### ISSUE TITLE
php artisan make:addon does not check type before proceding

### ISSUE THREAD

**Issue by rabol** [pyrocms/pyrocms#4054]
example: php artisan make:addon test.addon.test

this command starts creating directories and files and at the end and exception is thrown:
[Illuminate\Contracts\Filesystem\FileNotFoundException]
File does not exist at path /Users/<username_removed>/Sites/pyrocms/vendor/anomaly/streams-platform/resources/stubs/addons/addon.stub

**Comment by RyanThompson** [comment]
Fixed! https://github.com/anomalylabs/streams-platform/commit/609be012a7a2e0edab1e9c5069a1654dddaaf931

Thanks ^_^
