### ISSUE TITLE
[Repeater-FT] Cannot use Files ft within a repeater

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#4055]
Tried to add files to a repeater, it crapped out and was unable to save the record. No errors presented.

Page did not load properly either. Just showed repeater text on the page without any CS/Js/theme layout

![image](https://cloud.githubusercontent.com/assets/656313/22040193/e4e5a69a-dcb6-11e6-9dc6-64b5997d80ae.png)

If you remove the files ft, with the rest of the content the same. It works fine.

**Comment by RyanThompson** [comment]
No errors whatsoever?

**Comment by edster** [comment]
Nope, nothing rendered on screen or in the logs

**Comment by RyanThompson** [comment]
xDebug WOES
