### ISSUE TITLE
[repeater-field_type] Nested repeaters js issues

### ISSUE THREAD

**Issue by samharrison7** [pyrocms/pyrocms#4057]
When using nested repeaters (a repeater in a repeater), clicking the "Add row" button fires the add row click event twice so you get two new rows added instead of one. I can't figure out why this is happening. Changing line 148 of input.js from `wrapper.find('.add-row').click(function (e) {` to `wrapper.find('.add-row').off('click').click(function (e) {` stops it being fired twice for the nested repeater, but it's still fired twice if the top level "Add row" is clicked (one new row appears inside the nested repeater, and one where it should in the parent repeater).

Also, the drag and drop doesn't work for the nested repeater as you can only place them in the top level repeater (i.e., on the display, the nested repeater ends up displaying as the top level repeater).

![repeater](https://cloud.githubusercontent.com/assets/3359948/22098787/1cb6d0b6-de20-11e6-9196-070ae32b8a91.gif)

**Comment by RyanThompson** [comment]
That's a feature. It doubles your productivity :trollface:
