### ISSUE TITLE
[streams-platform] Automate image alt tags.

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4060]
At the very worst - these can be automated to a "humanized" version of the file name minus the extension:

`my_cool_image.jpg` would fallback to `My Cool Image`

**Comment by edster** [comment]
yes please

**Comment by minioak** [comment]
This would need to be a fallback default - and differentiate between “not set” and “purposely empty”

**Comment by RyanThompson** [comment]
Done: https://github.com/anomalylabs/streams-platform/commit/56f06c9e2d3b813c7110dddd706b2a6ff9952da0
