### ISSUE TITLE
[installer-module] Feature request: parse Heroku $DATABASE_URL and pre-fill database config fields

### ISSUE THREAD

**Issue by barbeque** [pyrocms/pyrocms#4061]
The Heroku `DATABASE_URL` environment variable contains some of the parameters that the installer asks for (host, db username, pass, database).

I am not sure if it is possible or practical to fingerprint which kind of database it is from the URL alone but it could save the user from entering four fields on install in this environment:

```
$url = parse_url(getenv("DATABASE_URL"));
$host = $url['host'];
...
```

**Comment by RyanThompson** [comment]
I think I would like to avoid environment specific implementations like this for now. It's a good idea. But probably something I would dump into my `.env` file in a fork or something..
