### ISSUE TITLE
Version all assets?

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4062]
Should images and style/script assets all be versioned by default?

I.e. my_file.css?v=TIME

Right now it's opt-in only.

**Comment by RienMoeyaert** [comment]
I don't mind it being optional, though I can't think of a reason you'd not want it to be versioned :)

Next to css, and js, you'd want image paths to be versioned as well.

**Comment by keevitaja** [comment]
It would not hurt unless you cannot opt out. Who knows what kind of weird things people need.

**Comment by lachieh** [comment]
oooh yes please

I can't think of a reason not to version assets

**Comment by RyanThompson** [comment]
@lachieh yes as is assets (usually) but the problem is getting the browser to respect it.

**Comment by RyanThompson** [comment]
Yup - version'n all teh assets
