### ISSUE TITLE
"A non-numeric value encountered" error

### ISSUE THREAD

**Issue by michaelGregoire** [pyrocms/pyrocms#4063]
I'm currently following your Module Development video "Module Sections and Basic CRUD" and when I get to the part where you add a search feature to VideoTableBuilder:

`protected $filters = [
    	'search' => [
    		'fields' => [
    			'title',
			    'description',
		    ]
	    ]
    ];`

…I get the error "A non-numeric value encountered" due to the fact that the hidden "page" input lacks a value, however is added as a get parameter.

When EloquentTableRepository tries to set the offset, it throws an Exception because "page" is found, but lacks a value and the default of 1 is not used.

`$page   = app('request')->get($builder->getTableOption('prefix') . 'page', 1);
$offset = $limit * ($page - 1);`

**Comment by RyanThompson** [comment]
Can you modify that code there to make a proof of the bug? Not quite following.. What is the name of the module / stream?

**Comment by michaelGregoire** [comment]
I followed your tutorial here: https://pyrocms.com/videos/series/module-development/module-sections-and-basic-crud

At about 12:12, you add search functionality. That's the top code I pasted up above.

The module is "Videos" and the file that the search is added to is the "VideoTableBuilder".

The generated search form has a hidden "page" input that lacks a value, which causes EloquentTableRepository to throw an exception.

I'm using the latest version of PyroCMS.

**Comment by michaelGregoire** [comment]
<img width="1433" alt="screen shot 2017-01-20 at 3 21 16 pm" src="https://cloud.githubusercontent.com/assets/1930152/22164259/7d186f5a-df24-11e6-90d5-dcd665d33674.png">

**Comment by wernerwerks** [comment]
I get this error when I use any of the filter buttons in the admin (fresh install). Doesn't matter if I leave the field blank or populate it. I'm assuming these are connected.

**Comment by RyanThompson** [comment]
Fixed! Thanks: https://github.com/anomalylabs/streams-platform/commit/378795baf229a31fc16530ca5bddcbc044594830
