### ISSUE TITLE
[files-field-type] Does not allow empty Selection

### ISSUE THREAD

**Issue by HolyMarcell** [pyrocms/pyrocms#4064]
Hey,

the Filesmodule doesn't allow "no file" selection.

Reproduce:

Pages - Field -> Create Field "Files" -> name it and use 
"Minimum Selection": 1 (-- it somehow doesnt allow "0" but this might not be part of the issue)
"Maximum Selection": 1

-> Assign The File-Field to a Pagetype with Option "Field required": no (rough translation from german here) 

-> Create/Edit a page, but leave the file selector empty.

This creates the error that the file-field may not be empty.

Regards,
Tristan

**Comment by HolyMarcell** [comment]
Quick workaround for now: There is a difference between the "files-field_type" and the "file-field_type". The (single) file-field_type does the trick for now and doesn't seem to have the bug.

**Comment by RyanThompson** [comment]
Im not sure if this would be considered a bug. Here are the rules that are compiled:

```
array [
  0 => "array"
  1 => "nullable"
  2 => "min:1"
  3 => "max:1"
]
```

Despite the nullable it's overriden by your desire to force 1 entry. Basically, the way I read this, is that this field is required. You must have 1 and only 1 file.

Also the file field type is far more appropriate for single files! Ill try and get some other input in on this ^_^

**Comment by edster** [comment]
I'm not sure how this is a issue, if you want to allow 0, then you don't set the field to be required, and you leave the min blank.

**Comment by carsonsuite** [comment]
I have run into this error too with a site once memphisdreamcenter.com a long time ago. I just worked around it.... in use I had an optional files FT for the background image of interior pages. I don't think it's a problem though as long as the error is caught with a explanation for the user. I should have been using the image FT anyways :)

**Comment by HolyMarcell** [comment]
@edster the "Minimum Selection" is mandatory and only allows integers >= 1

**Comment by RyanThompson** [comment]
@HolyMarcell the configuration is **optional** .. I think what should be done is leave off the config - and only use max in this case. Closing this out for now cause I really think it's correct the way it is. Unless I've misunderstood something.
