### ISSUE TITLE
[bug][streams-platform] search module issue

### ISSUE THREAD

**Issue by turakvlad** [pyrocms/pyrocms#4066]
In this [file](https://github.com/anomalylabs/streams-platform/blob/master/resources/views/table/partials/filters.twig) there is a hidden input with no value:
```
<input type="hidden" name="{{ table.options.prefix }}page" value="">
```

I always get the error below when I am trying to use search. After submitting the form I am redirected to this link - `http://pyrocms.app/admin/posts?view=all&page=&filter_search=test`. I think the problem is in empty `page` parameter. If I put 1 there, I have no error and everything works perfect.
![screenshot from 2017-01-22 19-47-32](https://cloud.githubusercontent.com/assets/7996184/22184934/10c2640a-e0dc-11e6-9626-291618beefff.png)

It looks like we should add some proper value to that peace of code above.

**Comment by RyanThompson** [comment]
This works fine in my install. The resulting query:

```
select distinct `default_posts_posts`.* from `default_posts_posts` left join `default_posts_posts_translations` on `default_posts_posts`.`id` = `default_posts_posts_translations`.`entry_id` where ((`default_posts_posts`.`tags` LIKE '%test%') or (`default_posts_posts_translations`.`locale` = 'en' and `default_posts_posts_translations`.`title` LIKE '%test%') or (`default_posts_posts_translations`.`locale` = 'en' and `default_posts_posts_translations`.`summary` LIKE '%test%') or (`default_posts_posts_translations`.`locale` = 'en' and `default_posts_posts_translations`.`meta_title` LIKE '%test%') or (`default_posts_posts_translations`.`locale` = 'en' and `default_posts_posts_translations`.`meta_keywords` LIKE '%test%') or (`default_posts_posts_translations`.`locale` = 'en' and `default_posts_posts_translations`.`meta_description` LIKE '%test%')) and `default_posts_posts`.`deleted_at` is null order by `publish_at` desc limit 15 offset 0
2.2ms
```

What is your environment? PHP / MySQL versions

**Comment by RyanThompson** [comment]
Eh doesn't matter.. Needs to be fixed either way! This should clean things up ^_^

Thanks for the report! https://github.com/anomalylabs/streams-platform/commit/378795baf229a31fc16530ca5bddcbc044594830
