### ISSUE TITLE
[bug][settings-module] maintenance mode issue

### ISSUE THREAD

**Issue by turakvlad** [pyrocms/pyrocms#4067]
I change `Maintenance Mode` option to `true` in the settings, but it doesn't take my site down. My site is still available. Maybe I wrongly understand this feature?

**Comment by RyanThompson** [comment]
No this and the debug setting stopped working when I moved the settings binding down the boot cycle. Ill get it worked out thanks!

**Comment by RyanThompson** [comment]
Fixed

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/settings-module/commit/9ff71c0cbe4755ff9a37777a6674ed50a187bb86#diff-3ef327dba58aa03968a0b60d7c940178L52
