### ISSUE TITLE
[fix?] [.htaccess] Rewrite Base for additional provider compatibility

### ISSUE THREAD

**Issue by HolyMarcell** [pyrocms/pyrocms#4072]
Hey,

I've just spent quite some time debugging the current .htaccess file for some asshat provider:

Can you just add a Rewrite Base like so:

```
    RewriteEngine On

++RewriteBase /

    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]
```

to public/.htaccess

so maybe other devs don't have to guesswork their way out of 500 Errors.

Regards,
Tristan

**Comment by RyanThompson** [comment]
Done deal - sorry for your frustrations :-/

**Comment by RyanThompson** [comment]
https://github.com/pyrocms/pyrocms/releases/tag/v3.2.2
