### ISSUE TITLE
[streams-module] How I can add New URL in Dashboard

### ISSUE THREAD

**Issue by aroon9002ahmed** [pyrocms/pyrocms#4073]
Hello
How I can add New URL in Dashboard for my new Streams [ Travel Styles]?

![cc](https://cloud.githubusercontent.com/assets/7735634/22230007/f3a22f28-e1e3-11e6-9f61-c67c603e90c5.jpeg)

**Comment by RyanThompson** [comment]
This is a feature coming soon to the Streams Module ^_^

I will announce updates over the various social venues!
