### ISSUE TITLE
[country-field-type] Documentation fix

### ISSUE THREAD

**Issue by sandor93** [pyrocms/pyrocms#4079]
The mode config for country field type is innacurate as it can not be **text**. 
In the table it is mentioned that **mode** accepts **input** or **dropdown**
![country_field_type_config](https://cloud.githubusercontent.com/assets/9431885/22294207/145e858a-e31b-11e6-85da-46c478027892.png)

**Comment by RyanThompson** [comment]
Fixed - thank you! This one kinda dropped off my radar :-P
