### ISSUE TITLE
[streams-platform] Disabled field type config fields save incorrectly

### ISSUE THREAD

**Issue by samharrison7** [pyrocms/pyrocms#4080]
Encountered this issue using a select field as a config option for a custom field type. Upon saving the field type's form (i.e. fields/edit/{field-id}), any config fields that are disabled don't get saved. I think this is because [this](https://github.com/anomalylabs/streams-platform/blob/master/src/Model/EloquentFormRepository.php#L84) removes the disabled fields (as expected), but as field type config fields are all stored in one database column, this means it unsets the config fields that are disabled, isn't of leaving them as is (as a serialised version of the other config field still gets saved to the database, just without the disabled field). Hope that makes sense?

**Comment by RyanThompson** [comment]
I've been playing around with this and I believe it is unavoidable. 

A workaround would be adding a callback to the FieldFormBuilder that sets the value on saving or on posting or something.

You can register something like this in the controller like `$builder->on('saving', function() {});`

**Comment by RyanThompson** [comment]
The only thing I can think of is if the select is disabled - add a hidden value with the same name. Thoughts on this?

**Comment by RyanThompson** [comment]
Still doesn't fix the issue for text field types though.
