### ISSUE TITLE
[streams-platform] Problem hosting when there are multiple languages (locale in url)

### ISSUE THREAD

**Issue by lckamal** [pyrocms/pyrocms#4086]
If locale is added on url then locale is not detected. which leads to 404 page.
When I checked on Anomaly\Streams\Platform\Http\Kernel.php
this was not returning locale from url:
```$uri = filter_input(INPUT_SERVER, 'REQUEST_URI', FILTER_SANITIZE_URL);``` line 131 and 147
Simply changing this to ```$uri = $_SERVER['REQUEST_URI'];```
works

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/bc3e636fef9c619c6b92283ef7282dbfc5d65dc0
