### ISSUE TITLE
[files-field_type] & [file-field_type] Frontend Uploader

### ISSUE THREAD

**Issue by jcastillotx** [pyrocms/pyrocms#4088]
If possible to allow config of uploader for frontend use. No select and hide the folder that the files are being uploaded to. This will allow personnel to use uploader for front and maintain form integrity.

**Comment by Piterden** [comment]
Don't know about front-end, but inside the seeder I had successfully used uploader:
```php
<?php namespace Bla\Bla\Bla;

use Illuminate\Http\UploadedFile;
use Anomaly\FilesModule\File\FileUploader;
use Anomaly\FilesModule\Folder\Contract\FolderRepositoryInterface;

class Seeder
{

    public function __construct(FileUploader $uploader, FolderRepositoryInterface $folders)
    {
        parent::__construct();

        $this->uploader = $uploader;
        $this->folders  = $folders;
    }

    public function run()
    {
        $uploaded = new UploadedFile(
            $file,
            array_get($image, 'image_name'),
            array_get($image, 'mime_type'),
            filesize($file),
            null,
            true
        );

        $processedFile = $this->uploader->upload($uploaded, $folder);
    }
}
```
I think that you can use technique like this for frontend too. Why not?

**Comment by RyanThompson** [comment]
You can also use the simple laravel integrations too: https://pyrocms.com/documentation/files-module/v2.1#integration

If you use PHP league's flysystem / laravel's filesystem with folders / disks integrations it will sync automatically to the files module.

**Comment by RyanThompson** [comment]
I will add a config for button control but you will want to config to only 1 folder - then the options won't be seen

**Comment by RyanThompson** [comment]
Added: 'mode'

https://pyrocms.com/documentation/file-field-type/v2.1#introduction/configuration
https://pyrocms.com/documentation/files-field-type/v2.1#introduction/configuration
