### ISSUE TITLE
[Pyrocms-core] Public .htaccess rules collide

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#4090]
Issue: If you turn on `Force SSL` or `Force WWW` you break the `Handle Front Controller` index.php handling.

To fix, move 
```
# Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
```

To the last rule in the file.

**Comment by RyanThompson** [comment]
Done: https://github.com/pyrocms/pyrocms/commit/4d3d0fcd5ca81166875e2e5571b0830d8ad2a275
