### ISSUE TITLE
[grid-field_type/repeater-field_type] Assign Text FT to Row Title In A Grid

### ISSUE THREAD

**Issue by carsonsuite** [pyrocms/pyrocms#4095]
It would be awesome to change the row's title to a value within the row itself. It would help the end user see what they are collapsing exactly and bring more clarity to what is being edited. Check out this video to help get a visual :) http://go.web901.io/30Oj

**Comment by RyanThompson** [comment]
There we go ^_^

**Comment by carsonsuite** [comment]
Ba da bing

**Comment by RyanThompson** [comment]
I think I will add this to the next major version of those fields.

**Comment by RyanThompson** [comment]
This is moot with blocks FT
