### ISSUE TITLE
Post Validation Issue on date

### ISSUE THREAD

**Issue by atdiehm** [pyrocms/pyrocms#4096]
If the date of a post is typed/pasted in, vs choosing from the date picker, and not in the same format as what the date-picker uses, submission throws a Server 500 error, versus a validation notification as I would expect.

This is when creating a new post in the admin area.

**Comment by RyanThompson** [comment]
This has been fixed in the 3.0 of the datepicker - give er a shot!

**Comment by atdiehm** [comment]
It better be! :-p
