### ISSUE TITLE
State / Province only allows 2 letters.

### ISSUE THREAD

**Issue by NickRT91** [pyrocms/pyrocms#4098]
I'm sure this applies to many other people from around the globe, that their 'state' or as we call them in the UK counties just have full names and do not have a 2 letter identifier code. Because of this that part of the address has to be left out.

Cheers,
Nick.

**Comment by RyanThompson** [comment]
Hmm.. The state field type you're referring to? I can certainly lift the length restriction. 

Honestly I've thought for some time if this field type was even necessary. It's left over from 2.2. It's got a dropdown mode which is nice but defaults to text.

Thoughts? My ideology is limited to the States :-P

**Comment by Piterden** [comment]
There is [RFC 3066](http://www.i18nguy.com/unicode/language-identifiers.html).
2 and 5 letters.

**Comment by RyanThompson** [comment]
I need more information on this - industry standards ideas.. Maybe will call for a field type.
