### ISSUE TITLE
[relationship-fieldtype] [CRITICAL] Can not use relationship field type multiple times in single stream

### ISSUE THREAD

**Issue by dakshhmehta** [pyrocms/pyrocms#4099]
Hello,

This is the frustrating issue and makes PyroCMS un-usable. Right now, when using relationship field types multiple times in a stream, than both the dropdown will have same options.

Stream Fields Migrations:
```
    /**
     * The addon fields.
     *
     * @var array
     */
    protected $fields = [
    	'name' => 'text',
    	'description' => 'textarea',
    	'email' => 'text',
        'raw_material' => [
            'type' => 'relationship',
            'config' => [
                'related' => RawMaterialModel::class,
            ],
        ],
        'supplier' => [
            'type' => 'relationship',
            'config' => [
                'related' => SupplierModel::class,
            ],
        ],
];
```

Stream field assignment migration
```
    /**
     * The stream definition.
     *
     * @var array
     */
    protected $stream = [
        'slug' => 'purchasing'
    ];

    /**
     * The stream assignments.
     *
     * @var array
     */
    protected $assignments = [
        'raw_material',
        'supplier',
        'name',
        'description',
    ];
```

Now, when a module is installed, and assuming Raw material and supplier are two different stream. When a data is added to both the module, The new module's form will get populated with Supplier's options in both the relationship field type.

Now, that's very irritative.

PS:
I have done some research and there might be two reason;
1. it looks like setOptions is setting the value and both the dropdown is using same thing
2. Based on, It looks like both the key are having same thing.

This should be fixed ASAP!

**Comment by dakshhmehta** [comment]
Also, both has provided with handlers explicitly and there is no change in output same issue. 

However, a new observation has been made with the code that no matter what, It is using the handler of last field type. That means, config are being shared with single stream and shouldn't get shared.

**Comment by Piterden** [comment]
That's interesting.
Try to set `lookup` mode.
I have many fields together in `lookup` and don't have any problems.
```php
    protected $fields = [
        'brand'            => [
            'type'   => 'anomaly.field_type.relationship',
            'config' => [
                'mode'    => 'lookup',
                'related' => BrandModel::class,
            ],
        ],
        'type'             => [
            'type'   => 'anomaly.field_type.relationship',
            'config' => [
                'related' => ProductTypeModel::class,
            ],
        ],
        'product_usage'    => [
            'type'   => 'anomaly.field_type.relationship',
            'config' => [
                'mode'    => 'lookup',
                'related' => ProductUsageModel::class,
            ],
        ],
        'product_usages'   => [
            'type'   => 'anomaly.field_type.multiple',
            'config' => [
                'mode'    => 'lookup',
                'related' => ProductUsageModel::class,
            ],
        ],
        'author'           => [
            'type'   => 'anomaly.field_type.relationship',
            'config' => [
                'mode'          => 'lookup',
                'related'       => UserModel::class,
                'default_value' => 1,
            ],
        ],
        'colors'           => [
            'type'   => 'anomaly.field_type.multiple',
            'config' => [
                'related' => ColorModel::class,
                'mode'    => 'lookup',
                'columns' => [
                    'name',
                    'slug',
                    'color',
                ],
            ],
        ],
    ];
```

**Comment by RyanThompson** [comment]
@Piterden are you able to replicate this? I am not: 

<img width="2553" alt="screen shot 2017-01-31 at 11 35 15 pm" src="https://cloud.githubusercontent.com/assets/1099967/22496292/21588996-e80e-11e6-98be-f70b0ec86a54.png">

**Comment by RyanThompson** [comment]
@dakshhmehta if you add `$type = clone($type);` on this line:

https://github.com/anomalylabs/streams-platform/blob/1.2/src/Addon/FieldType/FieldTypeBuilder.php#L98

Does it solve your problem?

**Comment by RyanThompson** [comment]
Ah.. nevermind I think I found it. Interesting you have this issue and I can't seem to replicate but I recall you saying something in Slack about the shorthand of the type.. That's important lol.

Fixed (I assume - test): https://github.com/anomalylabs/streams-platform/commit/4241f5c3bf02c4b4a75ccd4b332fbda844f3be60

**Comment by dakshhmehta** [comment]
Sorry for being inactive on this. But, the problem was that when I use full namespace type than it works properly, and when I just use slug as 'relationship'

Correct type: anomaly.field_type.relatioship
Invalid type: relationship
