### ISSUE TITLE
[field_types] Adding Class

### ISSUE THREAD

**Issue by jcastillotx** [pyrocms/pyrocms#4100]
It would be to be able to add a class to the field type so we can use bootstrap columns.

**Comment by Piterden** [comment]
1. Which field type exactly?
2. I suppose you mean HTML-class? If so, you need to accurate to which element you need to add class.

**Comment by RyanThompson** [comment]
This is something that is going into the `sections` definition.

**Comment by RyanThompson** [comment]
Technically duplicate of: https://github.com/pyrocms/pyrocms/issues/3980

**Comment by RyanThompson** [comment]
Check this out: https://github.com/anomalylabs/streams-platform/commit/a22c50278a7dc58a96b15f524b7f0d218c07b07e
