### ISSUE TITLE
[feature] Standardization of seeding process

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4104]
I like how migrations represented in Streams Platform, and it could be nice if seeding process will have similar representation.
Exactly I mean, that seeder's data store in config folder, `seeders.php` for example and inside it we have data in simple php arrays, like this:
```php
<?php

return [
   'products'   => [
    [
        'en'         => [
            'title'   => 'Filler Body 205 l.p.plus-soft',
            'summary' => 'This is an example product to demonstrate the products module.',
        ],
        'ru'         => [
            'title'   => 'Шпатлевка Body 205 l.p.plus-soft',
            'summary' => 'This is an example product to demonstrate the products module.',
        ],
        'slug'       => 'shpatlevka-body-205-l-p-plus-soft',
        'publish_at' => time(),
        'enabled'    => true,
        'author_id'  => 1,
    ], [
        'en'         => [
            'title'   => 'Filler Body 206 l.p.plus-soft',
            'summary' => 'This is an example product to demonstrate the products module.',
        ],
        'ru'         => [
            'title'   => 'Шпатлевка 206 l.p.plus-soft',
            'summary' => 'This is an example product to demonstrate the products module.',
        ],
        'slug'       => 'shpatlevka-body-206-l-p-plus-soft',
        'publish_at' => time(),
        'enabled'    => true,
        'author_id'  => 1,
    ], [
        'en'         => [
            'title'   => 'Filler Body 207 l.p.plus-soft',
            'summary' => 'This is an example product to demonstrate the products module.',
        ],
        'ru'         => [
            'title'   => 'Шпатлевка Body 207 l.p.plus-soft',
            'summary' => 'This is an example product to demonstrate the products module.',
        ],
        'slug'       => 'shpatlevka-body-207-l-p-plus-soft',
        'publish_at' => time(),
        'enabled'    => true,
        'author_id'  => 1,
    ]],
];
```
Also, of course, we have a parser of this data which have to called in seeder class of the Streams Platform. 

I can help with this, because I have some experience of coding seeders for the Steams, but I don't have such experience in creating structures like migrations inside Streams. That's why, I afraid to make a mistake and do my work for nothing.
But if we discussed this and together make a decision about rules for write data for seeders in config `seeders.php` file, (or maybe it would be better to create `resources/seeders` folder to store this data, I don't know) then I think that my knowledge would be enough to write this classes for seeding.

**Comment by RyanThompson** [comment]
This isn't a bad idea. Honestly though I would like to start from the reverse. I have high hopes of the system _generating_ seeders like this. Which can be moved around as needed and used to migrate / seed changes from local into the remote environment.

They could easily be used to do what you're suggesting as well.

I would like to version data though. I think that's the top top level need here. And we can do what you suggest and many other things with a proper system in place to do this.

**Comment by RyanThompson** [comment]
I am gonna close this for now - as I am working on an idea to generate stuff like this. A ways off but Ill keep you in the loop of course ^_^
