### ISSUE TITLE
[feature] New front-end theme \w VueJS SPA implementation.

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4106]
That'd be very nice - and this is most important thing in this post - to give to developers, using Pyro, ability to create SPA in front-end of site. Which will brings almost only good effects to the Pyro Project at all.
Looks like a front-end theme could be the most obliviously decision. Inside theme - thanks to God(I mean Ryan))) - we can put theoretically any classes. So we can to put Api classes if it have to present or any other stuff.
Also creating theme with new principal advantages probably could engage some more people to Pyro.

Original message
https://pyrocms.slack.com/archives/vue/p1486167792000355

**Comment by RyanThompson** [comment]
I am starting an initiative for making Pyro more JS / API consumable from a control panel standpoint. 

https://github.com/pyrocms/pyrocms/issues/4112
