### ISSUE TITLE
[feature][Control Panel] Adding Webpack builder & improving of JavaScript code

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4107]
I want to make offer to use Node and Webpack as builder of assets for Control Panel.

Also it'll be a pleasure for me to refactor some of JS attached to the CP. I agreed that excluding of jQuery at all is not possible, because it is a critical dependency of some other stuff, which is necessary for correct work.
But I want to offer rewrite some parts of JS, replacing jQuery functions which can be easily replaced its native JS analogs.
Exactly, I mean that `$('.header')` is slower than `$(document.querySelector('.header'))`, because there is difference between native JS and jQuery-wrapped DOM-select methods.
Also it'd be nice to replace `$.ajax` with some more modern lib, based on Promises or async/await techniques of asynchronous calls.

Pyro doesn't really have a lot of JS, and I don't think, that it is very much to work for.
I can realize this, if I'll receive a resolution to do so.

**Comment by RyanThompson** [comment]
I would be happy to clean up the JS involved. The end goal should be:

- Cleanly organized code (let asset class concat them together). 
- Fast / efficient execution. You're probably better than me in this area.
- Minimal footprint.

Sounds like your cleaning up is a great idea. I would love to see what you can do!

----

One thing I would love to do is make the JS a little more OOP too.. but that might be best saved for a later goal. But keep it in mind.

**Comment by RyanThompson** [comment]
so yes - start doing what you do and send in smaller / concise pull requests! 

Thanks ^_^
