### ISSUE TITLE
[installer-module] Streams models compiled to wrong folder

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4110]
![image](https://cloud.githubusercontent.com/assets/5930429/22623407/1fa2bab2-eb6b-11e6-8723-f169c624a3b6.png)

Have this when trying to enter first command just after fresh install Pyro 3.3 through console.
And again I have streams generated models in wrong folder.

![image](https://cloud.githubusercontent.com/assets/5930429/22622705/42d7e6f0-eb53-11e6-94db-2e31e7a59f25.png)

These values I had used in install prompt:
```dotenv
APPLICATION_NAME=DeloZvuka                                                                                                                   
APPLICATION_REFERENCE=delozvuka
```
Simple copying of models solves the problem.
I tried to find possible solution, but I have a little bit confused with it.

I can write code, that can move compiled models to correct folder. But this code will be placed in separate command class at run in the end of install process.
But I sure that this is not right way.

**Comment by RyanThompson** [comment]
You said this was no longer an issue if I recall? If I am mistaken please open er back up ^_^

**Comment by Piterden** [comment]
You are right, thank you)
