### ISSUE TITLE
stop developing this crap

### ISSUE THREAD

**Issue by DeeJaVu** [pyrocms/pyrocms#4111]
every time i save or do someting i get 500 server error bla bla bla

what is this shit

**Comment by RyanThompson** [comment]
I can't tell you how incredibly productive and helpful this bug report is.

If you can't be a productive member of the community and even give me a stack trace from your logs - in a civilized manner. Go away.

That said, if you'd kindly provide the error log (the whole thing if you like) I would love to look into what's causing this issue.

I feel like referring to Pyro (I assume) as "crap" is pretty naive on your part. And again "what is this shit" hardly prompts anyone to give two shits about the issue you're having. 

I'll happily chalk this up to frustration if you'd like to provide more information.

**Comment by DeeJaVu** [comment]
fuck the stack trace its every time i install pyro i get bunch of errors and all that shit

way back usin codeigniter was the same.. i will never come back to this shit

**Comment by RyanThompson** [comment]
See ya!

I _genuinely_ feel sorry for whatever community you happen to land in.
