### ISSUE TITLE
[streams-platform] Make CP components more JS consumable

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4112]
Allow JSONifying everything..

**Comment by Piterden** [comment]
Maybe this is not it, but why we can't do just like `response()->json($collection, 200);`

**Comment by RyanThompson** [comment]
We need actual object JSON mutations - including mutable properties for UI objects.

**Comment by Piterden** [comment]
Excuse me, Ryan, but does increasing consumption of JS includes integrating PyroCMS with Node.js based build-system, which Laravel has out of the box?

Either, this has to be a new issue title.
