### ISSUE TITLE
Admin icon/label positions

### ISSUE THREAD

**Issue by atdiehm** [pyrocms/pyrocms#4113]
The icons in the admin area seem to have a varying width, but a fixed distance to their label from when they stop.  

This lends to a vertically misaligned stack of labels when expanded.

It's about the least serious bug ever, but I notice it every time I look in there :)

Setting  .fa, and .glyphicons in #sidebar to width:1.25em; cleans it up for me via inspector, but would have likely other ramifications, so I don't want to suggest that as a broad fix.

This is on current macOS and current chrome, also a fresh update to 3.3.0

With other screen for guide | Without guide
---------- | ----------
![screen shot 2017-02-06 at 1 40 03 am](https://cloud.githubusercontent.com/assets/323884/22637081/d8e9912e-ec0d-11e6-8476-b7b7b059acf7.png) | ![screen shot 2017-02-06 at 1 40 20 am](https://cloud.githubusercontent.com/assets/323884/22637080/d8e97d9c-ec0d-11e6-836b-2b814b533276.png)

**Comment by RyanThompson** [comment]
Fixed! https://github.com/pyrocms/accelerant-theme/commit/3235cbe71a25ff0c2ba9acc1349cfe7ff4eb7996
