### ISSUE TITLE
Bug in CLI installer. admin password is incorrect.

### ISSUE THREAD

**Issue by oimken** [pyrocms/pyrocms#4114]
I am using the  CLI Installer automating install pyro,  
admin and password is already set in `.env` just like the doc guide:
```
...
ADMIN_EMAIL=ryan@pyrocms.com
ADMIN_USERNAME=admin
ADMIN_PASSWORD=password
...
```
and run 
```
php artisan install --ready
```
install is successful but login failure.   password was incorrect.

please check it out.

BTW:
If there is a artisan command to reset/rehash a password will be great.

**Comment by RyanThompson** [comment]
In the admin login you can click "Forgot your password?" to initiate a reset.

**Comment by RyanThompson** [comment]
Can't reproduce :-(
