### ISSUE TITLE
[markdown-field_type] duplicate comma in translations file

### ISSUE THREAD

**Issue by pepijnolivier** [pyrocms/pyrocms#4115]
- Please see: [Armenian language file](https://github.com/anomalylabs/markdown-field_type/blob/v2.1.10/resources/lang/ar/addon.php)
- Use CTRL+F or CMD+F and search for a comma `,`
- notice that the last entry in this translation file has a duplicate comma

---

Easy fix; remove the last comma

**Comment by RyanThompson** [comment]
Thanks for the heads up! https://github.com/anomalylabs/markdown-field_type/commit/39145cf02fdf26c22a40567d9a9572393f0d5cc4
