### ISSUE TITLE
Need DEMO .env flag for locking out certain aspects of the system.

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4116]
Need suggestions / thoughts on this.

**Comment by RyanThompson** [comment]
- [ ] Install / uninstall addons
- [ ] Modify the admin user or group in any way.

**Comment by fryiee** [comment]
I think it's fine as long as there is a config fallback. I would say it defaults to false. in the config.

**Comment by RyanThompson** [comment]
Lol ya but what would / should I start with for limiting on demos? Installer is pry another one..

**Comment by fryiee** [comment]
Installer, modifying any admins for sure. Potentially editing Streams / Repeaters ?
