### ISSUE TITLE
500 Error when adding a new row of grid field type.

### ISSUE THREAD

**Issue by designbywilliam** [pyrocms/pyrocms#4117]
I have a grid, with a code editor and a markdown field type. Works ok locally. But on digital ocean when i click add row, i get a 500 error. And the log shows the below.

Next Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("variable @brand-danger is undefined in file anonymous-file-0.less in anonymous-file-0.less") in "/var/www/williamastrom.se/core/anomaly/grid-field_type/resources/views/wrapper.twig" at line 3. in /var/www/williamastrom.se/vendor/twig/twig/lib/Twig/Template.php:182

**Comment by RyanThompson** [comment]
Fixed
