### ISSUE TITLE
Failed When Installing

### ISSUE THREAD

**Issue by endytc** [pyrocms/pyrocms#4119]
When after run this command  
> php artisan install

I'm got error:

> file_put_contents(/var/www/html/pyrocms/pyrocms/storage/streams/default/mod  
  els/Configuration/ConfigurationConfigurationEntryModel.php): failed to open  
   stream: No such file or directory
![image](https://cloud.githubusercontent.com/assets/1209684/22722855/55b132b8-edec-11e6-9741-f04cf249e2e0.png)

**Comment by RyanThompson** [comment]
Can you make sure the system has the required write permissions per docs?

**Comment by endytc** [comment]
yes I have changed storage folder to 777,

> chmod 777 -Rf storage

**Comment by RyanThompson** [comment]
Check ownership and everything this is definitely a permissions issue ^_^
