### ISSUE TITLE
Small layout issue when dividing form sections into rows/colums

### ISSUE THREAD

**Issue by ThinkGraphical** [pyrocms/pyrocms#4120]
When dividing the form sections into rows/columns, i'm noticing that the margin of `.form-group`is being set to 0, which results in a layout that looks squeezed together.

<img width="1169" alt="screen shot 2017-02-08 at 10 22 22" src="https://cloud.githubusercontent.com/assets/1651789/22730969/5b7a3d82-ede9-11e6-8512-19d9284d688c.png">
Versus:

<img width="1167" alt="screen shot 2017-02-08 at 10 22 59" src="https://cloud.githubusercontent.com/assets/1651789/22730979/6584a9e8-ede9-11e6-85f7-6c4a61baee85.png">

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/3d1ae9c5f45b2821a86636c134410b014fa164cf
