### ISSUE TITLE
[streams-platform] Watching and clearing assets only partially.

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4121]
![image](https://cloud.githubusercontent.com/assets/5930429/22733047/776cb688-ee01-11e6-9749-3c84584206a3.png)

When I'd edited `translations.js` I don't needed even to clear assets. But when I'd edited `keyboard.js` - even clearing assets with command line does not work.

This is not actually problem for me, because I use `mc` for deleting it)

**Comment by RyanThompson** [comment]
I am unable to reproduce this - the only known issue that we've found is files including files (SCSS importing others). Which.. I am working on a fix.
