### ISSUE TITLE
[file-field_type] No options when file is removed from file FT 

### ISSUE THREAD

**Issue by carsonsuite** [pyrocms/pyrocms#4122]
I have a header image as a required file field type on a default page layout. When replacing the file in the CMS, it fails to prompt options to upload or select a new file.

Video gives extra clarity: http://go.web901.io/sQeZ

Workarounds for me right now:
- Mark as NOT required and save the page after removed. Then the options come back when you reload the page.

- Replacing the image on the server with a new file with same file name.

**Comment by RyanThompson** [comment]
Is this resolved now that the button issue was resolved on the FT right?

**Comment by RyanThompson** [comment]
Ya looks like that was the case - fixed!
