### ISSUE TITLE
show that error - class not exist

### ISSUE THREAD

**Issue by Zakrota** [pyrocms/pyrocms#4123]
how can fixed this problem  ,that when I Created series and category as normal but finally shown this problem ,

![2](https://cloud.githubusercontent.com/assets/24638537/22852986/07a1f51c-f017-11e6-98ed-3c9b4d7d18ce.jpg)

![1](https://cloud.githubusercontent.com/assets/24638537/22852987/07a8128a-f017-11e6-9764-6e3c4c5884b1.jpg)

![3](https://cloud.githubusercontent.com/assets/24638537/22853283/28293486-f020-11e6-9b1f-015001e85c71.jpg)

**Comment by RyanThompson** [comment]
Ya we would really benefit from some exceptions in there wouldn't we!

This is from a field filter being defined where the field doesn't exist in the stream.

**Comment by Zakrota** [comment]
Thank you , but I'v main problem , When i want to create a video on the admin panel i get ReflectionException Class SeriesModel and CategoryModel does not exist. The model exists in the addon.
I feel freeze completely  in this code on pic1 for this problem,What I do ,please solve my problem on pic2 ???
pic1 :   
![4](https://cloud.githubusercontent.com/assets/24638537/22857284/810876b6-f070-11e6-99b1-5f5bbf66a964.jpg)
pic2: 
![2](https://cloud.githubusercontent.com/assets/24638537/22857289/96ca0dc0-f070-11e6-8e64-f9760b39d113.jpg)
