### ISSUE TITLE
problem creating second new Video on panel 

### ISSUE THREAD

**Issue by Zakrota** [pyrocms/pyrocms#4128]
Hi , Mr @RyanThompson  , Firstly  field_type for slug and text area on Videos not exist what is problem ??? 
![5](https://cloud.githubusercontent.com/assets/24638537/22858266/d25e217c-f085-11e6-87d2-718c5e5757f9.jpg)

I've problem when create new video is show to me this problem.Who can I fix that ???
![6](https://cloud.githubusercontent.com/assets/24638537/22858269/e5b864a8-f085-11e6-8c63-89c73da704c4.jpg)

Thank you .

**Comment by Zakrota** [comment]
@RyanThompson  Can you help me please ???

**Comment by RyanThompson** [comment]
That’s pretty self explanatory - but we’d need to see your migrations to point out anything specifically.

**Comment by Zakrota** [comment]
This is code , some tags not appear on my website it is like disable on pic1 and pic2 (above on the Top comment issue ), Fix my problem  please??,Thank you @RyanThompson  .
pic3:
![1](https://cloud.githubusercontent.com/assets/24638537/23070313/63685fb4-f533-11e6-8a6e-601ebbfeda89.jpg)
pic4:
![2](https://cloud.githubusercontent.com/assets/24638537/23070314/636cd576-f533-11e6-8bcb-58ac6382b93b.jpg)
pic5:
![3](https://cloud.githubusercontent.com/assets/24638537/23070315/637230f2-f533-11e6-8b25-c77c3c69c83e.jpg)
pic6:
![4](https://cloud.githubusercontent.com/assets/24638537/23070316/63e6e578-f533-11e6-9eca-4c95c892985f.jpg)
pic7:
![5](https://cloud.githubusercontent.com/assets/24638537/23070327/71d0442c-f533-11e6-8de8-bec248c9efa1.jpg)
pic8:
![6](https://cloud.githubusercontent.com/assets/24638537/23070328/72189d1c-f533-11e6-80ee-720025fa733e.jpg)
pic9:
![7](https://cloud.githubusercontent.com/assets/24638537/23070311/635bcf2e-f533-11e6-9616-53c0f578dc36.jpg)
pic10:
![8](https://cloud.githubusercontent.com/assets/24638537/23070408/b8305146-f533-11e6-980b-0fb0098d67b8.jpg)

**Comment by Zakrota** [comment]
@RyanThompson ???
