### ISSUE TITLE
[Feature Request] Add CDN support for Files Module

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4129]
Unless i'm missing this (checked both disks and folders) i don't see anywhere to put a base url for CDNs in the files module.  Here is an example of how this is handled in Craft CMS (just one extra field that defaults to the bucket url [in the case of S3] but can be replaced with a CDN url). 

[Screenshot](https://goo.gl/x5RuCV)

**Comment by RyanThompson** [comment]
You can use the `{{ file.url() }}` to get the real URL for them. In the case of S3 it will be the S3 URL for example.

**Comment by mattcdavis1** [comment]
@ryanthompson you're not understanding my request.  I don't want the S3 URL.  I want the CDN URL.  currently there is no place to entera CDN URL.  S3 is not a CDN

**Comment by RyanThompson** [comment]
LOL oh gotcha sorry - I don't know that you need the files module to do this?

You can add this prefix anywhere - even set it as a Twig constant. And use it along with the name of the file to do what you need yes?

Perhaps more explanation of the implementation will help me better answer. Seems to me like this is something done on the implementation end not the provisioning end.

**Comment by mattcdavis1** [comment]
Well - it's convenient to have a GUI for the base url and also more convenient on the front end so that i can do {{ file.url }} to get something like https://d1y5an0wsv0wfg.cloudfront.net/my/s3/asset.  Otherwise, i have to either do {{ mySpecialFunction(file.url) }} or {{ file.myCdnUrl }} which means (in the case of the latter) that every project i have to extend the file model or in the case of the former i need to add a special function that parses out the base domain.  It just makes more sense to have the base domain as a configurable path with a sensible default (for example, S3 would default to https://s3.amazonaws.com/)

**Comment by RyanThompson** [comment]
Ok cool - Ill check it out and see what it looks like ^_^
