### ISSUE TITLE
[Feature Request] Files Module: Remove slug from storage location

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4130]
The only reason i can think of as to why this is currently happening is to avoid collisions but this could be handled through unique validation.  It's awkward when i create an "S3" disk and the first segment of the path is "s3".  This is just redundant and unnecessary.  I think there should be an optional subpath but not a forced slug-as-first-segment.  Here's an example of what this looks like in Craft:

[Screenshot](https://goo.gl/4ltgFV)

**Comment by RyanThompson** [comment]
I could definitely see it being optional like that. I can get onboard with that for sure. Seems like I'd still want to force it though.. would that be less obtrusive if you could define the folder separate the slug?

**Comment by mattcdavis1** [comment]
Why force it?  People should be in control of their own URLs.

**Comment by RyanThompson** [comment]
I believe there is an argument for best practice there but also because you won't easily be able to change it later.

**Comment by RyanThompson** [comment]
This is no longer forced in the files module.
