### ISSUE TITLE
[files-module] Make files movable.

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4131]
Disk sources should be editable - for moving from one cloud to another or local to cloud or any number of other scenarios.  

As far as moving existing content, the way Craft handles this is that it just leaves existing content in place until an entry that references that field is re-saved (at which time the files are moved to their new location).  And of course any new files moving forward are saved to the new destination.

Alternately, there could be some sort of migration process.  Perhaps an artisan command that copies all files over.  Then, the old files could optionally be deleted.  I suppose at this point you could leave the source un-editable and the migration script would handle moving between 2 sources.  Only problem would be that you would likely want the new target to maintain the same slug.

**Comment by RyanThompson** [comment]
Ya I feel like this is a good place for a migration command. From one folder to another - one folder on X disk and the other on Y disk. Leaving the stuff behind seems kinda dangerous?

**Comment by RyanThompson** [comment]
This is done in Files Module 2.6

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/files-module/commit/c6be441961e669bb9070d057e0bf9c24b3b5e627
