### ISSUE TITLE
[3.1] User module custom field name validation errors are untranslatable

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#4132]
This should affect all modules

Field names in validation errors that come from the stream field names are always in default locale.

I tracked the problem to

https://github.com/anomalylabs/streams-platform/blob/4aee784d83e79790602d664d40b1cbb9a4ae99be/src/Ui/Form/Component/Field/FieldTranslator.php#L32

`$builder->getFields()` already has the label in default locale. Imho it has nothing directly to do translating. More of a stream issue.

More explanation in forums https://pyrocms.com/forum/channels/everything/31-user-module-custom-field-name-validation-errors-are-untranslatable

**Comment by keevitaja** [comment]
@RyanThompson any news on this?

**Comment by RyanThompson** [comment]
Can you check on this if it's still a thing? I swear I've fixed it before.

**Comment by RyanThompson** [comment]
I believe this is good to go:

<img width="1280" alt="screen shot 2017-07-08 at 1 05 16 am" src="https://user-images.githubusercontent.com/1099967/27983064-8cc1d908-6379-11e7-975b-e49f571d424f.png">
