### ISSUE TITLE
FormBuilder does not respect working locale

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#4133]
FormBuilder generated post url does not contain the locale slug. 

So when it redirects back, it always gets non localized url. 
Also the validation error messages will not be in correct locale.

The very hackish workaround i made is

```
            {% set host = request_getHost() %}
            {% set register = form('register').redirect(url('/')).get() %}

            {{ str_replace(host, host ~ '/' ~ config_get('app.locale'), register.open({'class': 'form'}))|raw }}
```

Logout also redirects to non-localized url. No clue how to hack this

**Comment by RyanThompson** [comment]
I think the `LOCALE` can help - Ill take a look thanks!

**Comment by RyanThompson** [comment]
This should do it: https://github.com/anomalylabs/streams-platform/commit/58904fd565536280ca93f14d21d6090e4fb87bfb
