### ISSUE TITLE
[tutorials] Ideas for help articles

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4138]
### Theme stuffs

- [x] How to build the nav ( sample theme generates 2 uls so things break oddly in various responsive breakpoints. I see structure() but cannot find documentation on how to modify )
- [ ] How to get other blog navigations for a typical right-column nav section ( categories, tags, recent posts, search, etc.. typical blog things )
- [ ] How to add non-page blocks, editable in the admin, assuming this is doable. I.e. if I wanted to make a right column, have that contain the blog items from my previous bullet, then some content.. but have that content in a block that can be edited from the admin 
- [ ] Documentation, even at a very high level, of what theme/display-specific helper functions are available, with their options
- [ ] typical / useful code snippets that a developer would find useful in building/theming a brochure-site/blog ( as a starting point )

### Other

- [x] artisan cheat-sheet with some non-code keywords ( for searching ) for both laravel and pyro-specific comments, as appropriate for starting up a site .. upgrading pyro, cache clear, various make comments, etc.
- [ ] initial tips on locations of various important things ( again, with respect to what might be relevant in a brochure/blog type site ) ..
- [ ] quick install tips ( then links to docs for more in depth )
- [ ] other quick highlights of common questions that maybe already exist in docs, but are not necessarily obvious ( i.e., I had no idea that initially I needed to look in the "Streams" section of the docs to find out how to create a new theme, stuff like that )
- [ ] really anything obvious to frequent PyroCMS devs, that might be missing, or not easy to find in the docs ( or searchers may not know what to search for ) or just undocumented in general.

**Comment by Piterden** [comment]
![image](https://cloud.githubusercontent.com/assets/5930429/23090266/fc4fcab0-f5aa-11e6-9704-a38acca2ba68.png)
that's what I'm waiting for

**Comment by RyanThompson** [comment]
- Form builders help
- Laravel principles help
- Form Builders (UI category?)

**Comment by damian-pf** [comment]
I think I written version of the basics of building an addon would be great. The videos are awesome but a little hard if you need a reference point to go back to. You have docs for things like migrations but as mentioned above it can be hard to navigate around the docs and also to piece it all together.

I thought that the Tutorials in the Laravel 5.2 documentation were great idea for beginners, something similar to that for Pyro would be cool.

**Comment by fryiee** [comment]
I know you've mentioned Laravel principles, but a basic article describing how you would do common tasks in Laravel and where you should be doing them in Pyro would be helpful (obviously prefaced by whether its in a module / extension).

**Comment by RyanThompson** [comment]
Anything in particular you have in mind Craig?

**Comment by Piterden** [comment]
Builders life-cycles for UI! Could you write them?

**Comment by RyanThompson** [comment]
Noted these internally
