### ISSUE TITLE
[feature] Disable reloading pages

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4146]
It's terrible, it's so annoying - my mind is just exploding when I seeing it next time.

I'm about that bad habit of any Pyro theme, to reload any page you want to go to.
Can we do something?

One time I had implemented such like not-reloading pages web-site (NOT SPA).
The principle is in different responses depending on request type, and dividing page on 3 parts:

- head
- content
- foot

By XHR server puts only content part. On standard GET - all.
So, if in controller or somewhere else we could globally program such behavior, then we can tell to JS make XHR requests on every internal link. 

I had make such web-sites a few times, and, even on slowly Modx, I had page change timing about 150-300ms!

**Comment by RyanThompson** [comment]
This is part of the robust and simple nature of Pyro. It reflects it's simplicity and boasts what it can do with such simple tools. I am not interested in changing that mindset in the core application. Developers can of course do it and I encourage it! Tasteful amounts of JS UI is great. But not in core.
