### ISSUE TITLE
Navigation module issues (pyro 3.3, nav: ~2.2.0)

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#4147]
Hello,

after upgrating to 3.3, I spotted (in two projects) that somethign is wrong with navigation.
In one project it did not even happen immediately - only after some time.

1. So while in development - I tried to reinstall module NAVIGATION (I have two locales);
2. Now I have no menus
3. I created one menu (and it created two!)

screenshot: http://pic.webas.lt/webas.lt-ee66bfd077.png

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/d5282b0fad20ed5f1d4539b33fc7ac6384ea1a20

**Comment by RyanThompson** [comment]
Fixed
