### ISSUE TITLE
[feature][navigation-module] More informative grid in navigation-module

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4149]
Could we have some more information in this grid? For example `url`.
Actions would be nice here too. Just like in table.

![image](https://cloud.githubusercontent.com/assets/5930429/23166134/635fcbc2-f850-11e6-9774-6f70e46d1ee2.png)

**Comment by RyanThompson** [comment]
I feel like URL is basically like clicking on "view" IMO

**Comment by Piterden** [comment]
URL is much important here. I have a situation when my client set some URLs wrong.
For example above it is not a big trouble, but for example below, how do you think?
![image](https://cloud.githubusercontent.com/assets/5930429/23166764/edd3b7da-f852-11e6-8097-4852ad416592.png)

**Comment by RyanThompson** [comment]
You can easily deduce what link is wrong by it’s title right? The “Help” link is wrong - find the “Help” link in the list of links.

**Comment by Piterden** [comment]
I have SPA on the front so that links is actually not broken for it. But `blog` link from the first image is really broken. Everything other is alright.

**Comment by RyanThompson** [comment]
I would automate your URLs in that case more since they are not exposed (use page links or product like you do and no URL link types since that can be very confusing for the client). But they can still see what’s being used by editing it for example.

**Comment by Piterden** [comment]
I don't have `pages-module`, `pages_link_type-extension` and `default_page_handler`

So `url_link_type` is only way to do it for me, but for other link types we need to show route instead of URL.

**Comment by RyanThompson** [comment]
Sorry man - I just don't see making URLs available. Perhaps I can add it as a configurable in the future or something but I don't feel like it's a good idea right now.
