### ISSUE TITLE
[store-module] (ecommerce) - Ideas

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#4150]
Hello,

I would like to just share some points, so we remember them, and try implement:

1. Example, we have a product, product variants (different variants can have different in_stock qty, price, photos)
 - or different prices, like X - 50 eur, XL- 60 eur
 - or white color 10 EUR, black 12 EUR;

// added
You can also have:
different prices, for different attributes like:
X, Blue = 50 eur,
X, Red = 60 eur
XL, Blue = 55 eur
- not sure here, how this would have difference with variants? Maybe variants are mo suitable when 
price changes; while attributes are the same price? but again - SKU/in_stock are different...
so probably these somehow should be interchangeable?

but again - for example we have items like this?: 
1. X Blue SKU001 - 50 EUR
2. X Red SKU002 - 60 EUR
3. XL Blue SKU003 - 60 EUR
4. XL Red SKU004 - 70 EUR

But how then the customer chooses: 
1st - color;
2nd - size?
- this is really common and needs to be solved in some way. maybe X Red could have not a price - but price 'modifier' - like "+10" EUR; - and these prices would have starting point of the main product.

2. Customers...
so basically users who register at the site, or sometimes there is no registration required (like guests);
but Customer would be created anyway - all data could be bound there.

2. Steps/submodules needed:
- cart...( adding to cart, modify + params (variants) etc);
- checkout process;
- after checkout - order is created (probably no need to create order earlier); - or even create an order when the payment option is selected;
- then payment set up as COMPLETED; - ORDER should go to state StoreStatuses::PAYMENT_RECEIVED

- Also after order is beein confirmed - probably customer data should be 'persisted', because later if customer changes his address - we don't want that old invoices would 'auto change' their address, last name or something like that;

- now probably some customer emails should go - depending on product (like it will be shipped)
- now there should be an option to change order to like 'shipped' -> email notification

3) Discount handling? (for example fixed discounts, or grouped discounts on different order items etc)

4) What about shipping and shipping zones; different zones pricing)

5) will it have posibility to make shipping calculations? like I buy two items:
5kg each, 100x200x500 sizes. 

6) what about invoicing? Probably invoice should be also created together after payment is initiated (or order created). so basicly user can pay OFFLINE somewhere, so he should pay for 'Invoice-001 or ORDER-001.

---
that's it for now - for start. we could combine it more

**Comment by RyanThompson** [comment]
Let's push this to the forum - trying to keep er cleaned up here and wanna point to the forum more-so than here :-P

Ive got these noted internally though too
