### ISSUE TITLE
[repeaters-module] Missing Permissions for the Repeaters Section in Dashboard

### ISSUE THREAD

**Issue by haeflimi** [pyrocms/pyrocms#4153]
There seems to be no Permissions for the Repeaters Section in the Backend.

This would be handy to hide away the Section from Users/ User Roles who shouldn't be bothered with it.

**Comment by RyanThompson** [comment]
You could implement this yourself with a multiple relation to roles - and check against the user during your loop. 

I don’t want to clutter up tangent implementations like this when it can be done on an implementation basis :-/

`user().hasAnyRole(row.allowed_roles)` for example where allowed roles is the repeater field

**Comment by haeflimi** [comment]
I get what you mean by not wanting to clutter up things.

But while working with different CMS over the years i found it to be of vital importance to hide away advanced features on the admin dashboard from users that only need to perform certain tasks. - People get confused too easily when there are to many options. (even if they dont have to concern them)

Besides:
I've been able to hide away all the other Sections but this one by using just the Module permissions on the User Roles that are already in place. Without writing even a line of code. - I think that's great and how it should be.
Why should this specific module be any different?

**Comment by RyanThompson** [comment]
Sorry I think I totally missed what you were saying lol. 

You want to add permissions for the module portion of Repeaters. Not for the repeater rows themselves.

Agreed!

**Comment by haeflimi** [comment]
Haha, ok. I am glad!
And I agree that adding permissions for repeater rows would be cluttering things.

**Comment by RyanThompson** [comment]
Done! Test em out if you would - grid / repeater both have them now.

**Comment by haeflimi** [comment]
Thanks! Hiding away all Core Modules from the Control Panel using permissions works like a charm now.

This leads me to a Question, or even a suggestion. But this is not the right place for it i think. - I'll outline it in a [Feature Request](https://github.com/pyrocms/pyrocms/issues/4239)
