### ISSUE TITLE
[feature] - [select-field_type]  - mode select2

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#4155]
Hello,

I suggest that select2 'mode' is added to the select field type (and probably to multiple-fiield_type also)

There was initial PR, but not ready  -  https://github.com/anomalylabs/multiple-field_type/pull/20 - just for a reference/help.

**Comment by RyanThompson** [comment]
Ya, I've been thinking of this too. Ill get it on my schedule to nail down that styling which is all there really is to it.

**Comment by RyanThompson** [comment]
Done
