### ISSUE TITLE
[grid-field_type] Bug : Nested repeater issue

### ISSUE THREAD

**Issue by designbywilliam** [pyrocms/pyrocms#4156]
Posted this in slack. But ill try to repeat it here!

I have a grid called callout assigned to a page.

I have a field type repeater assigned to the grid.

The repeater has a relationship fieldtype (translatable) with slug. Its related to pages and using lookup. I also had a text field to this repeater.

When adding new rows to the callout grid in the page. It worked to select page. But when saving it did not store the link.  But it did store the text link. However, there were duplicate entries in the database.

I then deleted everything and created it again. However, i did not do any translatable and did not add a text field to the repeater. I also selected dropdown and not lookup.

That works. Also changing dropdown to lookup works.

Attaching some images here. You also have a video in the feature slack group.
![screen shot 2017-02-25 at 16 06 28](https://cloud.githubusercontent.com/assets/1510338/23332377/012fbfd0-fb79-11e6-9296-83a1c51c730d.png)
![screen shot 2017-02-25 at 16 06 24](https://cloud.githubusercontent.com/assets/1510338/23332379/01323396-fb79-11e6-9e3c-8c3be0d0d2f6.png)
![screen shot 2017-02-25 at 16 00 50](https://cloud.githubusercontent.com/assets/1510338/23332378/01315052-fb79-11e6-9391-5dc2b68c22cf.png)

**Comment by designbywilliam** [comment]
![bug-grid-field-type-relation-repeater 1](https://cloud.githubusercontent.com/assets/1510338/23333284/737562ce-fb89-11e6-9462-88f2682e5c8d.gif)

**Comment by RyanThompson** [comment]
What if the relationship is not translatable?

**Comment by RyanThompson** [comment]
Update and try this out - I think it's fixed. Had issues with colliding instances

**Comment by RyanThompson** [comment]
Reopen if not
