### ISSUE TITLE
[image-field_type ] Image downsizes and disappear on browser resize

### ISSUE THREAD

**Issue by designbywilliam** [pyrocms/pyrocms#4157]
When you resize the browser window (using chrome). The image resizes to become very very small. 

![screen shot 2017-02-25 at 16 59 13](https://cloud.githubusercontent.com/assets/1510338/23332552/e0b14730-fb7b-11e6-8bae-2e884eca13ff.png)

![screen shot 2017-02-25 at 17 00 21](https://cloud.githubusercontent.com/assets/1510338/23332557/f118f564-fb7b-11e6-9274-bd194fd2a819.png)

**Comment by designbywilliam** [comment]
![cropper bug](https://cloud.githubusercontent.com/assets/1510338/23333263/f8ec6f84-fb88-11e6-8ab2-5ac64277a198.gif)

**Comment by RyanThompson** [comment]
lol... I know what that is. But that is kinda funny you have to admit.

**Comment by RyanThompson** [comment]
This will have to do for now: https://github.com/anomalylabs/image-field_type/commit/0a874eb04c6d67d2fad900f51191c686c565e015

I am unable to find a way around the responsive issue.
