### ISSUE TITLE
Feature Request: Namespaces for Tag Field Type

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4160]
For the "Free Input" component of tags, there ought to be namespaces at a field level so the autocomplete doesn't end up showing irrelevant results (from other fields).

**Comment by RyanThompson** [comment]
Hey can you explain a little more what you're referring to here? Maybe a couple screens? Im trying to figure it out with free input and assigned to pages but not seeing any results from other entries

**Comment by mattcdavis1** [comment]
Maybe this is baked in by default at a field level?  I just assumed the absence of a namespace implied global.  If that is the case (tags are namespaced to their field), what if you wanted to share the same tags across two fields?  How would you accomplish this?

**Comment by RyanThompson** [comment]
Tags are not stored in a shared space. Only configured options populate the field. Free input is free input so if you wanted the same tag in two fields either freely input it there or add it to configured options of both.

**Comment by mattcdavis1** [comment]
ok cool thanks. there's probably minimal scenarios where you would want shared free-input options so i'll cross that bridge when i get there.  definitely better to default to field-level scope since that will be that majority use-case.
