### ISSUE TITLE
Tags Field Type Errors on Create

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4161]
Here is a screenshot of the error i get when trying to create an entry with a tags field type: https://goo.gl/H4cpAA

Here is a screenshot showing the configuration for that field type:
https://goo.gl/AT0BLm

**Comment by mattcdavis1** [comment]
Looks like this is caused when there is not at least one option in the tags area.  If i add an item it works.  However, in most cases the tags will be all user defined.

**Comment by RyanThompson** [comment]
Fixed, thanks! https://github.com/anomalylabs/tags-field_type/commit/39a6da4ec38300cef96ca6ffbefb6abb11a2e209
