### ISSUE TITLE
Streams Module: Relationship Field Types Show ID 

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4162]
Screenshot: https://goo.gl/2DHMlU
There needs to be a place to choose the title field when setting up a relationship field or multiple relationship field

**Comment by RyanThompson** [comment]
Agreed - workin on it

**Comment by RyanThompson** [comment]
Been in API for a while but just pushed it to users control via UI now: https://github.com/anomalylabs/relationship-field_type/commit/39b85b4c0a061445f298fc2ac8487ebdaf9c2d69
