### ISSUE TITLE
Streams Module: Parameters Not Being Used in GetConfiguredTableBuilder

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4163]
I'm not sure if i'm understanding this correctly but in `GetConfiguredTableBuilder` there is code that fetches params and never uses them:

```
if (!$parameters = $config->get("anomaly.module.streams::table.{$namespace}.{$stream}")) {
    return null;
}
```

^^ If there are no parameters, return null - make sense ^^

```
if ($builder = array_pull($parameters, 'builder')) {
    try {
        $builder = $container->make("anomaly.module.streams::{$namespace}.{$stream}.table");
    } catch (\Exception $e) {
        $builder = $this->dispatch(new GetDefaultTableBuilder($this->stream));
    }
}
```

^^ if there is a `builder` key in parameters, remove this key but do nothing with it.  Then, run the same code as `GetEntryTableBuilder`.  If there is no `builder` key, `GetEntryTableBuilder` runs.  In either case, the following code executes:

```
try {
    $builder = $container->make("anomaly.module.streams::{$namespace}.{$stream}.table");
} catch (\Exception $e) {
    $builder = $this->dispatch(new GetDefaultTableBuilder($this->stream));
}
```

Unless i'm missing something the `GetConfiguredTableBuilder` isn't adding anything to the process except for removing a config key.  Is this the intended functionality for this class?  My guess is that the parameters should be used to override table builder class properties.

The thing i'm trying to accomplish is to choose the stream columns and the streams sort order for a given stream.  It appears as though the 2 ways to do this are to bind a class to `"anomaly.module.streams::{$namespace}.{$stream}.table"` or to override config.  I'm having trouble figuring out how to do either of these. 

I'm able to bind the class, but getting the TableBuilder configured correctly is something having having trouble with.  And going with the config override approach i'm running into the issue mentioned above.

**Comment by RyanThompson** [comment]
This should be resolved with the last fix but let me know if I am mistaken!

**Comment by mattcdavis1** [comment]
i don't think this is resolved.  The params are still not being used. 

On [this line](https://github.com/anomalylabs/streams-module/blob/1.1/src/Entry/Command/GetConfiguredTableBuilder.php#L58) `$builder` is an array of params.  This evaluates to true which takes us to [this line](https://github.com/anomalylabs/streams-module/blob/1.1/src/Entry/Command/GetConfiguredTableBuilder.php#L60).  

There are two problems with [this line](https://github.com/anomalylabs/streams-module/blob/1.1/src/Entry/Command/GetConfiguredTableBuilder.php#L60):
1. It is not using the params from the line above.
2. It does not call `setModel` like you're doing [here](https://github.com/anomalylabs/streams-module/blob/1.1/src/Entry/Command/GetEntryTableBuilder.php#L56)

My understanding is that the configured builder should use params to configure the table but it is not doing this.  It is functioning exactly the same as GetDefaultTableBuilder

**Comment by RyanThompson** [comment]
It should set the model for sure - however params would simply extend the existing table builder used by the addon - if you provide your own builder then params should be ignored cause you're BYOT :-P

Does that make sense?

**Comment by mattcdavis1** [comment]
If i am using my own builder then yes, i can set my own params.  However, the issue now is that if i do not want to use my own builder but instead would rather just override settings via a config file this is not working.  The config values from [here](https://github.com/anomalylabs/streams-module/blob/1.1/src/Entry/Command/GetConfiguredTableBuilder.php#L58) are never used. 

You can confirm that this is not working by trying to set a param in `resources/default/addons/anomaly/streams-module/config/table.php` and see if it works.  I had the following in this file:

```
<?php

return [
    'ratiochristi' => [
        'apologeti_ticker' => [
            'builder' => [
                'columns' => [
                    'title' => 'Title',
                    'created_at' => 'Date',
                ],
                'options' => [
                    'heading' => 'module::admin/groups/heading',
                ],
            ],
        ],
    ],
];

```

My config was not used (i commented out my builder override to test this)

**Comment by RyanThompson** [comment]
Gotcha - on it! Sorry Im a little slow today. SELinux issue has fried me.

**Comment by RyanThompson** [comment]
Ok this should behave correctly now - thanks!

**Comment by mattcdavis1** [comment]
great - thanks!
