### ISSUE TITLE
Gravatar Broken in Default Theme (accelerant)

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4164]
Looks like the recent change [here](https://github.com/anomalylabs/users-module/blob/2.2/src/User/UserPresenter.php#L46) is causing a break [here](https://github.com/pyrocms/accelerant-theme/blob/1.0/resources/views/partials/topbar.twig#L30) since the gravatar now returns the image tag and url instead of just the image tag.

**Comment by RyanThompson** [comment]
Arg - thanks! https://github.com/pyrocms/accelerant-theme/commit/5b456e7d82649e231d1c90596068827f4404eb58
