### ISSUE TITLE
[grid-field_type] [BUG] Translation problems.

### ISSUE THREAD

**Issue by designbywilliam** [pyrocms/pyrocms#4165]
## Based on a forum post 
https://pyrocms.com/forum/channels/general/translation-translatable-grid-or-field-assigned-to-pagetype

## My setup:
Created a markdown field : homepage_project_description
Created a image field: homepage_project_image
Created a grid : homepage_project **Translatable**

Created a (pages) grid field type: homepage_project
Assigned the field type to my default page type setting it as **translatable**

## Issue
When adding a row of this grid, populating with info and then hit save i get this error:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'homepage_project_image_data' in 'field list' (SQL: update `xxxx_grid_homepage_project_translations` set `homepage_project_image_id` = , `homepage_project_image_data` = , `updated_at` = 2017-02-26 20:47:53 where `id` = 3)
```

**Comment by designbywilliam** [comment]
Now, as i wrote in the other task:
"I deleted the old grid. Did a new one but didnt set it as translatable. Did a new page field of grid field type and assigned it to home. Set it to translatable."

Now i always get the mb_strtolower() error. And not seeing this one. So no clue if this works now when not setting the grid itself as translatable.

**Comment by designbywilliam** [comment]
Finally,

NOT setting the grid translatable
and NOT setting the assigned field to the pagetype translatable threw NO errors.

So there is a bug there..

**Comment by RyanThompson** [comment]
Fields that have a pivot table can NOT be translatable period. Like grid / repeater for example. If that helps. They really shouldn't even let you do it via GUI but not entirely sure about that as of right this very moment.

**Comment by RyanThompson** [comment]
This will help prevent this in the future - `null` was accounted for but not `false`: https://github.com/anomalylabs/streams-platform/commit/671ac8aee12767b0e5058b169a5f0b321beffb80
