### ISSUE TITLE
[ISSUE]  Saving page : mb_strtolower() expects parameter 1 to be string

### ISSUE THREAD

**Issue by designbywilliam** [pyrocms/pyrocms#4166]
## This is probably connected to my other filed issue:
https://github.com/pyrocms/pyrocms/issues/4165

##When saving the page i get this error:
```
mb_strtolower() expects parameter 1 to be string, object given
```

Refering to line 8 in:
/home/vagrant/Code/pixney.dev/vendor/teamtnt/tntsearch/src/Support/Tokenizer.php

**My post data:**
_token	
"4S1JMkulS2dSqtd9wZkci6piNjYPzLQvBANfZDrL"
page_title_en	
"Welcome"
page_slug	
"welcome"
entry_content_en	
"<p>Welcome to PyroCMS!</p>"
page_meta_title_en	
""
page_meta_keywords_en	
""
page_meta_description_en	
""
page_theme_layout	
"theme::layouts.homepage"
page_enabled	
"on"
page_home	
"on"
page_visible	
"on"
page_exact	
"on"
action	
"update"

**Comment by designbywilliam** [comment]
Deleting the grid field type assigned to the page type (referred to in the other issue) removed this problem.

**Comment by designbywilliam** [comment]
Assigning the same grid field type, but not setting it to translatable. Worked.

**Comment by designbywilliam** [comment]
Again assigning the grid field type to the page type but setting it to translatable. Same error appeared!

**Comment by designbywilliam** [comment]
I deleted the old grid. Did a new one but didnt set it as translatable. Did a new page field of grid field type and assigned it to home. Set it to translatable.

Same error.

But it seems like this might have solved the other issues issue.

**Comment by designbywilliam** [comment]
Finally,

NOT setting the grid translatable
and NOT setting the assigned field to the pagetype translatable threw NO errors.

So there is a bug there..

**Comment by RyanThompson** [comment]
This will help prevent this in the future - `null` was accounted for but not `false`: https://github.com/anomalylabs/streams-platform/commit/671ac8aee12767b0e5058b169a5f0b321beffb80
