### ISSUE TITLE
[grid-field_type] [Bug] - Duplicate text fields appear on page

### ISSUE THREAD

**Issue by designbywilliam** [pyrocms/pyrocms#4168]
Created a text field, set it to translatable, assigned it to a grid, created a grid field type and assigned it to a page.

The text field shows up twice on the page.

![screen shot 2017-02-27 at 08 05 19](https://cloud.githubusercontent.com/assets/1510338/23351806/b3d92522-fcc3-11e6-816f-debac6de26e3.png)

**Comment by huglester** [comment]
are you on the newest streams? 
I had something problematic with navigations module which was fixed

**Comment by designbywilliam** [comment]
How new? I updated an hour ago...

**Comment by RyanThompson** [comment]
I know what this is - grid uses a little used field view one sec..

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/526038e3bc939bcc7a9e87648aafce6b31c60bf8
