### ISSUE TITLE
Pyro is not PHP7.1 compatible

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#4169]
PHP7.1 cannot handle some automatic type castings anymore.

http://php.net/manual/en/migration71.other-changes.php

https://github.com/anomalylabs/streams-platform/blob/7ef25f9528dcd9a37dca4c006d2f29c12f64895e/src/Model/EloquentTableRepository.php#L97

And this will "fix" it:

`$offset = $limit * ((int)app('request')->get($builder->getTableOption('prefix') . 'page', 1) - 1);`

The actual problem is, that you cannot do math with strings anymore.

**Comment by RyanThompson** [comment]
This was fixed a while ago - what commit are you at there?

https://github.com/anomalylabs/streams-platform/blob/1.2/src/Model/EloquentTableRepository.php#L84-L86

**Comment by RyanThompson** [comment]
This is fixed in the 1.1 branch too
