### ISSUE TITLE
[files-field_type] Sorting is not reflected correctly in admin.

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#4170]
When I reorder the files in a field_field-type then save the sort order seems to always be in the order that I added them to the files field type. Although the order is saved correctly and when I iterate through the list of files on the front end they are also in the correct order.

I added the files in ascending order, but the are actually sorted in the order 3, 2, 1, 4, 5, 6, 7, 8. The admin shows them in the order that I added them (1, 2, 3, 4, 5, 6, 7, 8), but the front end updates correctly.

![screen shot 2017-02-27 at 10 15 08 am](https://cloud.githubusercontent.com/assets/535135/23371546/a3d1721c-fcd5-11e6-9921-679e6af336c9.png)

I'm pretty sure that I'm traced it do the setTableEntries of the ValueTableBuilder in the files field type, but when the entries are set they are set to FilesModels which don't contain the correct sort order.

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/39cd938687d74af53715a59aa89ad08ce7ad0b42
