### ISSUE TITLE
Feature Request: File(s) Field Type - Add Allowed Types / Validation

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4174]
File field type should allow folder creation and file validation should be moved to the field type as well.  It's cumbersome to have to go back and forth between field type and files when creating new file field.  Additionally, one shouldn't be forced to create a new folder just to accommodate field validation.  

This is what file field creation looks like in Craft: [https://goo.gl/TZT5Vy](https://goo.gl/TZT5Vy). I think the Craft approach makes more sense and easier to use.

**Comment by RyanThompson** [comment]
Creation within modals is something that's on the back burner and I'll have to kick it around a bit. But I 100% agree on the restricting file types!

**Comment by RyanThompson** [comment]
This is done. Files FT 2.3 and File FT 2.2
