### ISSUE TITLE
Feature Request: Folders Should Support Hiearchy

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4175]
It's difficult to organize files without a folder hierarchy.  It's also conventional to have this strucutre and most people will expect it.  Also, the lack of a folder hierarchy limits control of file urls which can provide useful information to people navigating to these files.

**Comment by RyanThompson** [comment]
We've had great feedback without it - I don't see this happening sorry! 

PS I went through about 4 files module versions 2 including hierarchy and the current version was by far the best from API and user standpoint. Simplicity wins again!

That said a custom / alternate module would be cool!

**Comment by mattcdavis1** [comment]
Yeah - looks like i'll have to build my own at some point.  Thanks for considering it.

**Comment by RyanThompson** [comment]
Of course! You've got plenty of experience and good ideas ^_^
