### ISSUE TITLE
Feature Request: File Field Types Need More Granular Control of Sources

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4176]
Let's say i have a blog stream and that stream has a multiple file field type (like for an image gallery).  I want to limit the images that show up in a given entry to only images that have been uploaded previously for that entry (instead of having to see all images in that folder.

Craft CMS supports this functionality via path variables.  For example, i can use {id} when defining the path for a file field which means the user will only see files for that entry when they are browsing the file viewer for that entry.

https://goo.gl/kXzpNk

**Comment by RyanThompson** [comment]
Ill have to think about this one.. We have a more rigid path than Craft does as we _only_ support disk://folder/file.ext

Perhaps some kind of meta information could be used in the database to achieve this and other tasks. Similar to tags but it'd be hidden from forms / API use only.

**Comment by mattcdavis1** [comment]
@RyanThompson - or we could change to a less restrictive file system which i've requested elsewhere.  It's really not ideal the way it is now (no nested folders).

**Comment by RyanThompson** [comment]
This would require a major rewrite and I've been down this path before. The simplistic principles of the way I made it has worked very well for even the largest sites handling 100's of new files a week that need to be organized in some way. I think there is enough alternative / extensible approaches that this just does not make sense :-/
