### ISSUE TITLE
Pages Module Forces Slug

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4177]
The home page does not have a slug therefore the slug should not be required.

**Comment by stefanpkc** [comment]
I don't think that's true. Because you can also create a menu where you add that page and maybe you would want a slug then.

There's an argument that it's duplicate content. Is this correct?

**Comment by mattcdavis1** [comment]
I'm not advocating that we remove unique contstraint, just the required restraint. Either that or just use "/" for home but that just seems weird currently since there is a "/" at the end of the grayed out portion of the field (which implies the url would be a double slash - i.e. mydomain.com//).  I suppose removing that slash and using "/" as value would be an option also

**Comment by RyanThompson** [comment]
I can't think of a reason to remove it. But there are a few reasons for it to stay (and it's automated by default):

- Consistency
- If you change home pages it'll all of a sudden be necessary / required
- What about finding a page by slug? 

Sorry man, I don't see this happening :-/
