### ISSUE TITLE
Pages Module Allows Multiple Home Pages

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4178]
Setting "Is this the Home Page" to yes should remove this setting from any other page that may already have this value set to "yes" since there can only be one home page

**Comment by RyanThompson** [comment]
Done! Thanks for pointing this out :-P

https://github.com/anomalylabs/pages-module/commit/f687644ab7879d15b79b38c83e363ff9db19a7d0

**Comment by mattcdavis1** [comment]
great - thanks!
