### ISSUE TITLE
Feature Request: Pages Module - use tabs

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4179]
I think the pages module would look much nicer and be more usable as a tabbed layout.  This may be possible already but it didn't see anywhere in the config where could override this.  ideally, meta data should be it's own tab and the section below it should be it's own tab.

**Comment by designbywilliam** [comment]
Yes! I 100% Totally agree with you @mattcdavis1 !

I know it is on it's way. But the sooner this could be implemented, the better! Currently developing a site right now where we make use of grids both for main content and sidebar. I would like to be able to specify tabs for Main content, Sidebar, SEO and general settings to start with. And then decide what fields to be placed where.

This is one of those fundamental design improvements that can make this cms even more outstanding. I think this feature together with putting the action buttons back to the top, making sure the client see them are my  biggest requests i personally have right now.

**Comment by RyanThompson** [comment]
Related to https://github.com/pyrocms/pyrocms/issues/4190
