### ISSUE TITLE
Feature Request: Form layout builder API

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4180]
Users should have the same control via streams module that they do via coded config.  Tabs can be a very helpful tool for organizing fieldsets and eliminating alot of extra scrolling

**Comment by RyanThompson** [comment]
I was thinking of laying this out like "sections" and you'd have GUI to manage sections (which contains/can contain rows/columns/tabs). 

How does Craft store their layout information? Serialized?

**Comment by mattcdavis1** [comment]
No - it's stored via relational tables.  An stream has many tabs (Name, Order) and each tab has a single layout, and each layout has many fields.

**Comment by RyanThompson** [comment]
I'd really like to support entire section design.. thought? It would default simple but allow for more complicated design.

**Comment by RyanThompson** [comment]
Also I feel like relational tables here would be a waste. Since builder are based in array definitions basically I was considering YAML to begin with as a beta of he feature and test that out. Then introduce a builder a little later.

**Comment by mattcdavis1** [comment]
yeah - i think whatever is easiest as far as persisting the layout.  I guess the only value to using tables here would be if portions of the layout were re-used since you would be able to reference a tab layout by id.  

As for entire section design - i'm not sure what this implies.  What else is there to a section beyond tabs and fields?  Are you referring to buttons / filters?  In any case, i'm all for anything that add more layout control via the GUI.

**Comment by RyanThompson** [comment]
@mattcdavis1 any ideas on how this should look? I'd like to make it a core component.. building layouts in general. Ideas?

**Comment by Piterden** [comment]
Drag&Drop and resizable

**Comment by Piterden** [comment]
List of fieldTypes at the right side
You could take one and put on the layout. Resizing should be stickable to the 24 rows grid. I suppose only width should be resizable.

**Comment by mattcdavis1** [comment]
Craft's UI would be a good reference: https://goo.gl/Thd3Jv

The tabs in the below area of the screen shot are field groups (which Pyro doesn't have but would be helpful).   If you didn't want to display all the fields by group as Craft does, each tab could have a dropdown at the bottom for adding new items (or a plus button that triggers the modal).  

Pyro does have more advanced capability than Craft when it comes to sub-tab layout though.  That would be a bit more challenging to do in the UI.  I'd have to give that some more thought.

**Comment by RyanThompson** [comment]
Could easily start with something like this though and add more granular control IF NEEDED later.. Start simple. My thought is a JSON object in the database for layout?

**Comment by RyanThompson** [comment]
Gonna work on this tonight - shouldn’t be too terribly difficult - all our structure is there just gotta write a little Vue app to handle the visual composing of it.
