### ISSUE TITLE
Errors thrown during the application boot cycle are not caught

### ISSUE THREAD

**Issue by damian-pf** [pyrocms/pyrocms#4183]
## Problem
I discovered when upgrading a site, that you can no longer have a space in `.env` values without quoting them. This used to fail silently in older versions of Laravel. Now there is an error thrown.

```
// bootstrap/app.php
$this->app->singleton(
    \Illuminate\Contracts\Debug\ExceptionHandler::class,
    'Anomaly\Streams\Platform\Exception\ExceptionHandler'
);
```

We are using our own ExceptionHandler to try catch this. However as it extends `GrahamCampbell\Exceptions\NewExceptionHandler` we have an issue due to this line:

```
// vendor/graham-campbell/exceptions/src/NewExceptionHandler.php

$this->config = $container->config->get('exceptions', []);

```

At the point in the application that the `.env` file is parsed, we have not loaded the config. Therefore the application breaks with `PHP Fatal error:  Uncaught ReflectionException: Class config does not exist` not the `.env` error; making it very hard for the user to track down the issue.

## Replication
You can easily replicate this with a fresh install by setting an unquoted `.env` value with a space. You don't have to run the installer, you can replicate straight after composer is finished.
```
TEST_VALUE=This will break
```

## Potential solution
I am unsure how to best test that this solution works or if this is where you want to place the code.

You can move the above code snippet from `bootstrap/app.php` to `vendor/anomaly/streams-platform/src/StreamsServiceProvider.php`

I am not sure if you want this to be a part of the Streams Platform or if you would rather add it elsewhere. I thought if we put it in `app/Providers/AppServiceProvider.php` then there is the potential for users to accidently delete it.

Also how do you propose I test this? Is there a particular error that is noticeably Pyro?

**Comment by damian-pf** [comment]
### Note on replication:
Run `php artisan` to test

**Comment by RyanThompson** [comment]
Lots of improvements on that front, thanks for the help man!

https://github.com/pyrocms/pyrocms/commit/26309c9c9a5006612d7c11dbc01a90ec61d9d0ab

https://github.com/anomalylabs/streams-platform/commit/357cbe024fad43e21cbb4287e6a9eaa0992bdcf9
