### ISSUE TITLE
[Feature] Move actionbuttons to the top. I dont want to scroll down to save/update a page

### ISSUE THREAD

**Issue by designbywilliam** [pyrocms/pyrocms#4184]
Could we add "update" and "save to exit" buttons to the top, next to "+ new page" ?

When you go in to just enter title and slug you don't want to have to scroll down to the bottom to update/save.

**Argument by by Stefanpkc:**
@RyanThompson, the argument of a cleaner look is not valid. It means someone needs to come up with a better design or a solution so it looks clean, but that you still have the controls add the top. Those controls are missing. I will throw it in the slack chat. Perhaps the hive mind has an answer.

Yes... shortcuts are handy. But actions/controls give people also a visual cue of "what's next?"...

**Argument by me:**
Im with @stefanpkc . This is a question about usability. Even though i know about and am using hotkeys now. I still find myself sometimes wondering where the actionbuttons are. And if i am, then i am 100% positive my clients will as well.

I can't defend this one saying it's under development or someone thinks it look nicer when they explain they feel this is slowing them down.

**Comment by Piterden** [comment]
Agreed. But duplicate to the top. Best would be to show buttons/actions from bottom at the top when you are at the top.

**Comment by RyanThompson** [comment]
@designbywilliam what if I made the hot keys more visually obvious?

**Comment by RyanThompson** [comment]
@Piterden Are you saying make them fixed to bottom of screen when not at the bottom of the form? Cause I agree that _could_ be nice and fix this issue.
