### ISSUE TITLE
[Spam-Module] -- convert fopen to curl

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#4189]
More and more hosting companies are shutting down access to `fopen` due to security concerns. Would like to have `fopen` converted to curl in this module as it is currently unusable and 500's whenever `fopen` is triggered.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/spam-module/commit/cd5074452f7db1575530ba6a362109a92ec95ca0
