### ISSUE TITLE
Feature Request: Remove height restriction from WYSIWYG Field Type

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4193]
Why is there a [200px min height restriction](https://goo.gl/P0IOsF) on the WYSIWYG field type?  It adds too much vertical space and is unnecessary.  [Here is what redactor looks like in Craft](https://goo.gl/zfOCBf) with 75px height (much better).  Can we please remove this restriction (or if there is a place to override this please point me to it)?

**Comment by mattcdavis1** [comment]
figured out how to override this `php artisan addon:publish anomaly.field_type.wysiwyg`.  I think 75 would be a better default minimum.

**Comment by RyanThompson** [comment]
Done: https://github.com/anomalylabs/wysiwyg-field_type/commit/5895e7b20a2db778e287d3a7e975a7164de2ada1
