### ISSUE TITLE
Feature Request (Repeater / Grid Field): Add checkbox to each row for mass updates

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4195]
When multiple repeater / grid rows are checked, the action taken from the dropdown on the right (Delete / Expand / Contract) would affect all checked rows.

**Comment by RyanThompson** [comment]
Can you send a quick screen to demonstrate what you're seeing?

**Comment by mattcdavis1** [comment]
Well - this isn't something i'm "seeing" so much as something i would like to see.  But here's an example of what i'm talking about from Craft: https://goo.gl/wsaQzW

**Comment by RyanThompson** [comment]
When you select multiple and apply the action I assume they uncheck all right?

**Comment by mattcdavis1** [comment]
No - they stay checked.  If you accidentally did an incorrect action it might be a pain to reverse if they auto-unchecked after the action.  My preference would be to keep the checkboxes checked.

**Comment by Piterden** [comment]
The checkbox, which toggles all, should works in 3 modes, if there are selected, at least one of other checkboxes.
- part is selected
- no one selected
- all selected
Also, it should return the selected state back to begin. To the same selected collection.

**Comment by RyanThompson** [comment]
Done: https://github.com/anomalylabs/grid-field_type/commit/b7933706e34212ae8e1cf6b1fd07bcaa9d65cb80

Also the following two commits.

**Comment by mattcdavis1** [comment]
great - thanks!
