### ISSUE TITLE
Feature Request (Repeater / Grid Field): Add "Disable" to actions on right

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4196]
Sometimes, people may want to temporarily disable a repeater / grid row rather than delete it.  Adding a "disable" option (where "Delete" and "Expand/Contract" currently are) would allow for this.

**Comment by mattcdavis1** [comment]
Actually, i guess this is more of a global request that relates to all streams generally.  There should be a "enabled" column for all streams tables (and a corresponding GUI control)

**Comment by RyanThompson** [comment]
Im right in line with you on the grid / repeater. I have editable row titles and enabled toggle coming (along with some other cool stuff for them).

On the global thing.. I feel like maybe even a status column. Cause I could see draft, pending, enabled for example. But perhaps keep it simple.. I've been thinking about this one a while and I think it could be nice.
