### ISSUE TITLE
Feature Request: Add "Entries in this stream have their own page" option

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4197]
When creating or updating a stream there should be a configuration option to indicate whether or not the entries in a given stream have their own pages / urls.  This data could be used to generate a link from the listing area, automated routing, or to generate a live preview of the page (preview functionality would be new feature also - clicking on preview could reveal an iframe view of the page).  

Clicking the checkbox for "Entries in this stream have their own page" would add additional fields to the form to collect the necessary information (url format and template)

Here is what this looks like in craft:

[Configuration screenshot](https://goo.gl/5lak7o) 
[Preview screenshot](https://goo.gl/93bkhC)

**Comment by RyanThompson** [comment]
Let me think on this for a bit.. I kinda like that idea. It would be specific to the streams module.

**Comment by stefanpkc** [comment]
+1 for the preview idea. I wanted to look into that when I have more experience with pyro. I was thinking about vuejs. But an iframe works too. 
I know we all hate joomla. But here's something YOOtheme did for live preview:
![news_yootheme_pro11](https://cloud.githubusercontent.com/assets/6933041/23658115/8b13271c-0341-11e7-9ee1-38c6f27a4338.gif)

Honestly, I think if live preview is going to be implemented, it will be difficult and a nice-to-have feature. But not highest priority.

**Comment by RyanThompson** [comment]
This is something I am REALLY to do for Pyro and I have a lot of ideas. Will definitely start with iframe since it's the most straight forward and simple approach but will only apply when a larger form context is needed. I really want straight up inline editing.

**Comment by stefanpkc** [comment]
I think that should become a side project. Maybe someone can do some research first on iframe vs Vuejs. What issues will arise and what limitations there are.

**Comment by RyanThompson** [comment]
I think Laravel's `ResponseTrait` might help make this more of a streamlined thing.. Still kicking this around though ^_^

**Comment by Pixney-William** [comment]
This seems like a good feature request to catch up on @RyanThompson

**Comment by RyanThompson** [comment]
This has been completed in streams-module v1.4 that will be released soon.
