### ISSUE TITLE
[datetime-field_type] Having overlay issue when using form builder in modal

### ISSUE THREAD

**Issue by dakshhmehta** [pyrocms/pyrocms#4199]
I am calling a FormBuilder, setting ajax = true. When using the ajax form builder, The following issue can be seen.

Looks like this can be fixed with CSS z-index but I failed. If anyone can tweak the CSS in realtime, please update here.

Attached preview of the issue.
![pyrocms_error](https://cloud.githubusercontent.com/assets/1838017/23589017/2afff478-01ec-11e7-99f0-d6108a96795b.png)

**Comment by dakshhmehta** [comment]
I managed to solve it by doing

.modal {
z-index: 101;
}
and 
.modal-backdrop {
z-index: 100;
}

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/datetime-field_type/commit/6a9d2fd6123929dcdfa596575224229d422a6fc2

**Comment by RyanThompson** [comment]
Thanks for the bug report!
