### ISSUE TITLE
[feature] As an admin i want to be able to select language for admin

### ISSUE THREAD

**Issue by designbywilliam** [pyrocms/pyrocms#4200]
I am developing a website which public default version should be Swedish.
I still want the admin to be in the english language though.

Is this possible? To me it seems as i have to set the default language to Swedish to show the swedish site to public users per default. But doing so, also changes the admin language to swedish.

**Comment by designbywilliam** [comment]
I think this might not be necessary, if i (as a user) am able to select my language? not sure though. Let's see once that issue is fixed.

**Comment by RyanThompson** [comment]
Users can choose their locale in the dropdown in the footer - but keep in mind there is no local definition for front / backend separately. Laravel uses a single locale value. It's the ABSENCE of a locale selection we can control with defaults.

I think having this separated could be confusing.. but you can also force the locale at runtime for example in the front end - if your locale (set from control panel maybe) is EN but you visit /de/example the page will be in de but NOT ALTER your session locale.
