### ISSUE TITLE
[php 7.1 compatibility] EloquentTableRepository.php:102

### ISSUE THREAD

**Issue by designbywilliam** [pyrocms/pyrocms#4202]
Line 102, should be : 
$offset = $limit * ((int)app('request')->get($builder->getTableOption('prefix') . 'page', 1) - 1);

To work with php 7.1..

**Comment by RyanThompson** [comment]
This is already being forced to an integer in 3.3 ^_^

Tested and working in my 7.1 environment:

```
$limit  = (int)$builder->getTableOption('limit', config('streams::system.per_page', 15));
$page   = (int)app('request')->get($builder->getTableOption('prefix') . 'page', 1);
$offset = $limit * (($page ?: 1) - 1);
```

**Comment by designbywilliam** [comment]
But now i have this issue on line 110 instead @RyanThompson 

[2017-03-20 10:44:51] local.ERROR: ErrorException: A non-numeric value encountered in /home/vagrant/Code/sr.dev/vendor/anomaly/streams-platform/src/Model/EloquentTableRepository.php:110

**Comment by RyanThompson** [comment]
Fixed in Slack :-P
