### ISSUE TITLE
[streams-platform] Pyro giving back duplicate stream entries

### ISSUE THREAD

**Issue by ddnetters** [pyrocms/pyrocms#4203]
Making a new stream entry with multiple locales enabled but without filling in all translatable fields results in pyro showing the same stream twice.

Backend:
![](https://i.gyazo.com/0d0f02785416798dd0a9efd5e54f4963.png)

Database:
![](https://i.gyazo.com/b6e085deca66de16b4a3cab782351a52.png)

Frontend using `{{ entries('vacancies').get() }}`:

![](https://i.gyazo.com/565313a34d64906365897f724fb9d9ce.png)

Deleting one results in both getting deleted. Same goes for editing one.

The only way to remove the duplicate is by editing the entry, switching the fields to another locale using the little switch next to the labels. And then pressing `update`.

![](https://i.gyazo.com/fc096dd99a8f9b90cafa5611d6d2cdf9.png)

**Comment by RyanThompson** [comment]
Can you double check this? I have recently made a patch for pgsql that likely fixed this too. I just tested latest and have an example stream with a translated name and non-translated field too - values for both EN / DE of the name.. Only getting one result on the front.

If you are still getting duplicate results send your query as shown in your debugbar too. 

Closing this for now but if it persists please let me know and Ill reopen!
