### ISSUE TITLE
[feature] Tracy debug bar

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4208]
I think [tracy](https://tracy.nette.org/en/#toc-debugger-bar) debug bar is nicely and more convenient than our old debug bar, don't remember how it calls. Also, it has not bad XHR debug system inside.
Is it possible to integrate it?

**Comment by RyanThompson** [comment]
I really like the Laravel specific debug bar we have now ^_^

Maybe submit a feature request to them for XHR support - seems like it tracks Ajax calls though?

**Comment by Piterden** [comment]
How about moving of debug bar? I don't want it to placed in that corner.

**Comment by Piterden** [comment]
![image](https://cloud.githubusercontent.com/assets/5930429/23640423/acc46a58-02fe-11e7-8fd3-900c4338bc12.png)
![54f791bd11b9c538717430](https://cloud.githubusercontent.com/assets/5930429/23640435/bf9f7b0e-02fe-11e7-837b-81b1f2bc9d5c.png)

**Comment by RyanThompson** [comment]
Its only in the corner while you have it collapsed.

**Comment by Piterden** [comment]
If I need this corner, what I have to do?

**Comment by RyanThompson** [comment]
You click on it to expand it - if you don’t want it there just disable it.

**Comment by Piterden** [comment]
But I need information from debug bar, and at the same time, I need a corner for my app. I have to disable it you are right, and I did so. It is the reason of this feature request.

**Comment by RyanThompson** [comment]
I don’t think this edge case justifies swapping out debug bars, sorry :-(

**Comment by Piterden** [comment]
Please add polling app to the Slack
