### ISSUE TITLE
Feature Request [anomaly.module.posts] & [anomaly.module.users]

### ISSUE THREAD

**Issue by lildiablo** [pyrocms/pyrocms#4209]
I would like to have the ability to create a Role: "Writer",
This role would have the ability to Create/Edit posts but not "enable",
Role: "Editor" Will be able to read and edit the post & enable the post
perhaps the administrator & editor would be notified about the new Posts, 
The Administrator will be able to read/edit and enable the post

**Comment by RyanThompson** [comment]
Do you see the need for a global status system that would be pluggable? Kinda like searchable. It would be has_status or something.. 
Then drafts n such could be controlled tighter.

**Comment by RyanThompson** [comment]
Got this elsewhere and is on my radar - closing for now.

Thanks!
