### ISSUE TITLE
[streams-platform] Force SSL

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4210]
```
if FORCE_SSL 
    $this->app['request']->server->set('HTTPS', true);
```

**Comment by DuckThom** [comment]
Heh, I have been looking all over the place on how to force https links if the webserver is behind an SSL terminating load balancer as doing `\URL::forceSchema('https');` in the AppServiceProvider's boot method does not seem to do anything.
However, doing `$this->app['request']->server->set('HTTPS', true);` in the boot method, does work! 😄

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/3bb277927b5b597f8ab8c1e8ffdf13b52e5d0f1a

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/blob/1.3/resources/config/system.php#L14
