### ISSUE TITLE
[streams-platform] runtime cache does not get updated in EloquentQueryBuilder

### ISSUE THREAD

**Issue by aliselcuk** [pyrocms/pyrocms#4211]
```
        if (
            env('INSTALLED')
            && env('DB_CACHE') !== false
            && $this->model instanceof EntryModel
            && isset(self::$cache[$this->model->getCacheCollectionKey()][$key])
        ) {
            return self::$cache[$this->model->getCacheCollectionKey()][$key];
        }
```

this code block prevents non-cached models (ttl=0) getting updating in queue jobs. 

I am using algolia search engine, and if model is not cached, it is always sending the same data (in the runtime cache) to algolia.

when the model is updated, this runtime cache should be flushed

**Comment by RyanThompson** [comment]
This should be happening already?

https://github.com/anomalylabs/streams-platform/blob/1.2/src/Model/EloquentModel.php#L294

**Comment by aliselcuk** [comment]
Yes, but think of "php artisan queue:work" daemon.. In this single continous thread, once the model is statically cached, no matter how you flush it or update it in another thread, the data is stale here.

there's a flaw with the general concept.

**Comment by RyanThompson** [comment]
Do you suggest simply disabling during artisan use? I think the value stands in normal usage though so I would prefer not get rid of it.

**Comment by aliselcuk** [comment]
Yes, off course.. with artisan it is a problem because we cant flush the static data in this thread.

in normal usage there's no problem

**Comment by RyanThompson** [comment]
This should do it: https://github.com/anomalylabs/streams-platform/commit/03b3f0c78a7337b4a4c150a2b3233c308f41d9b2

Thanks!
