### ISSUE TITLE
Streams Utilities

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4214]
- [ ] Migration generators (for fields / stream)
- [ ] Convert native table to stream data
- [ ] Seeder generators (for stream entries / entry by id)

**Comment by dakshhmehta** [comment]
I vote for task 2 as high priorty, We have lot of non-Pyro projects and everyone will be happy if we can somehow manage to port it to Pyro project.

**Comment by RyanThompson** [comment]
Technically you can btw.. 

All UI is compatible with non-streams models too. Just define your fields in the form builder.

**Comment by RyanThompson** [comment]
Back burner for a while now..
