### ISSUE TITLE
Feature Request (Users Module / Streams Core): Add Streams Permissions

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4217]
I'm not sure if permissions are just missing from the GUI or if they just aren't built into the backend yet.  What i'd like to see is [something like this](https://goo.gl/cOcWjp).  Currently, the only permissions i see for streams are whether the streams modules is accessible as  opposed to permissions for individual streams. 

In addition to what is shown in the screenshot it would be really helpful to have user group based permissions as well.  This is useful in instances where, for example, you have an organization with a number of different chapters and you want each chapter to only be able to edit entries in a stream created by other users in their group.  Here's what i would like to see:

* Edit Own entries
* Create entries
* Publish Own live changes (would require streams status discussed earlier)
* Delete Own entries
* Edit User Group entries
    - Publish live changes for user group entries
    - Deleted user group entries
* Edit User Group drafts
    - Publish user group drafts
    - Deleted user group drafts
* Edit Any entries
    - Publish live changes for Any entries
    - Delete Any entries
* Edit Any drafts
    - Publish Any drafts
    - Delete Any drafts

**Comment by mattcdavis1** [comment]
Actually - i guess what i'm looking for with respect to the user group functionality is similar to the functionality that already exists in the pages module via "Allowed Roles" except at a stream entry level - and only applicable to backend editing rather than front end viewing.  

It is a bit more complicated than i initially thought though because for my purposes i wouldn't want a user from one chapter to be able to create an entry and allow someone from another chapter access to it.  

It's almost like i want to create stream segments (groups of entries within a stream) and assign permissions at sub-stream level.  Definitely more complicated than i initially thought.

**Comment by RyanThompson** [comment]
You could do this within a custom module which .. might make the most sense considering you've got some specific business logic tied to the permissions. All in all there are basic permissions coming to the streams module but nothing that would allow conditional stuff like this. However you might be able to use the new extension system for building streams module UI to do this. Closing for now - we'll have to get feedback from ya after the new versions release.

**Comment by mattcdavis1** [comment]
Ok cool - yeah after thinking about it more it is a bit more complicated than i initially though.  I do have a question though - are there currently hooks for the following?

1. Modifying query builder for a stream listing
2. Custom permissions hooks for view / edit / delete (like maybe an event that fires and if i return false based on custom logic the attempt to view / delete / edit the stream entry is denied)

**Comment by RyanThompson** [comment]
1.) If you have a FooModel it will automatically pick up a FooQueryBuilder next to it.
2.) You can publish addons and modify the permission.php config file effectively adding new permissions to check for in your code.

Hope this helps!

**Comment by mattcdavis1** [comment]
great - thanks!
