### ISSUE TITLE
[grid-field_type] & [repeater-field_type] Feature request: Make it easier to close rows

### ISSUE THREAD

**Issue by designbywilliam** [pyrocms/pyrocms#4220]
We discussed this somewhere. You suggested a double click on the row to close it. I suggested an extra icon.

Whatever goes, but this would definitely help working with grids and repeaters as i am sure many of us do.

**Comment by Piterden** [comment]
https://github.com/anomalylabs/repeater-field_type/pull/5

**Comment by ghost** [comment]
Is this also on its way?

**Comment by RyanThompson** [comment]
Double click on control bar and added select all / checkboxes with mass actions.
