### ISSUE TITLE
Index.php included on baseUrl when pyrocms was installed on subdirectory

### ISSUE THREAD

**Issue by masardee** [pyrocms/pyrocms#4221]
I tried to install pyrocms on my local which is located in a subdirectory, but `index.php` always appears on asset's URL.
e.g : `http://localhost/pyrocms/public/index.php/app/default/assets/public/theme.css?v=1489212935`

However, when I installed it in root directory, everything was fine.

**Comment by stefanpkc** [comment]
Are you on windows?

**Comment by masardee** [comment]
No, I'm on Osx.
I never get this issue in my other laravel projects.
Right now, I just create a `vhost` and point it to public directory to solve the problem.
Any other suggestion?

**Comment by dakshhmehta** [comment]
Just remove that line from .htaccess. Nothing much we can do here I suppose!

**Comment by stefanpkc** [comment]
Just wondering what you're using to host it on your local system.

**Comment by RyanThompson** [comment]
Yes, you have to set your host's web root to the public directory.
