### ISSUE TITLE
[Streams-Platform v1.3.0] Remove SeedServiceProvider dependency

### ISSUE THREAD

**Issue by pepijnolivier** [pyrocms/pyrocms#4222]
`Streams-Platform v1.3.0` [depends on Laravel 5.4](https://github.com/anomalylabs/streams-platform/blob/v1.3.0/composer.json#L11) 

`Streams-Platform v1.3.0` also still depends on the [SeedServiceProvider](https://github.com/anomalylabs/streams-platform/blob/v1.3.0/src/Database/Seeder/SeederServiceProvider.php#L4) that was [present in Laravel 5.3](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/SeedServiceProvider.php) but [removed in Laravel 5.4](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/)

This yields errors like:
```
  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Illuminate\Database\SeedServiceProvider' not found
```

So to me it seems like upgrading to `Streams-Platform v1.3.0` will always break your pyrocms install.
We should probably remove this SeedServiceProvider dependency

**Comment by RyanThompson** [comment]
Ya 1.3 is under dev though - we've been waiting for 5.4 to get make parameters back in there - that was the first issue. This branch is known to break though and not being required by anything at the moment. Seeders I am aware of and will adjust as needed!

Thanks ^_^
