### ISSUE TITLE
Feature Request [streams-core] - Create Dedicated Area for Settings-Focused Modules / Sections

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4224]
It would great to have a dedicated area for settings-focused modules and sections to reduce clutter in the main nav.  IMO the main nav items should be focused on content.  Perhaps this area could be a module called "Configuration" or "Manage."  This new area would include the current "Settings" module as one of many child items.

Ideally, the sections for each module could have a configuration option indicating whether the section should be assigned to either settings or content navigation areas (so potentially the same module might show in both areas but the subnav would be different).  [Here is a screenshot](https://goo.gl/3Zih2O) of what i'm thinking.  In cases where all sub nav items are assigned to a given area, the module would only show in that area.  

Pages would be an example of a module that might show in both areas.  If you clicked on "Pages" from the content area, you'd go to pages/pages.  If you clicked on "Pages" from the new settings area, you'd go right to "Types" or "Fields" and those would be the only items visible in the sub-nav.

Also, it would be nice to not show the sub nav if there is only one link in it (this is pretty easy to override at a theme level but it think it's a sensible default).

**Comment by RyanThompson** [comment]
I've got some ideas to help alleviate some of what you're talking about but in general.. it's tough because as an out of the box approach I am generic. Switzerland on some things. I would suggest maintaining a theme of your own like William has to accommodate your needs - but please do make sure to let me know if something is technically impossible for you to do based on core limitations for example!

**Comment by mattcdavis1** [comment]
a better module api would definitely be helpful here.  It's a real pain to loop through all the modules and get the information associated with each module.  Currently, system is geared towards just providing info related to current module.

https://pyrocms.com/forum/channels/streams-platform/get-hyrdrated-list-of-modules-sections
