### ISSUE TITLE
[tabs-field_type] Enter tries to save. Not possible to use free input

### ISSUE THREAD

**Issue by designbywilliam** [pyrocms/pyrocms#4226]
I have my own module with the following migration:
```
'course_type' => [
    'type' => 'anomaly.field_type.tags',
    'config' => [
        'min' => 0,
        "max"           => 2,
        "options" => ['Grundkurs','Fortsättningskurs'],
    ]
],
```

I am able to select a pre-defined option and save.

If i try writing something myself and hit enter, it tries saving the document.
If i write something and tries separating with comma. Nothing happen.

**Comment by RyanThompson** [comment]
This should be resolved

**Comment by RyanThompson** [comment]
If not check for console errors in your browser and gimme
