### ISSUE TITLE
[streams-module] with Pyro3.3.3

### ISSUE THREAD

**Issue by ikoniqoz** [pyrocms/pyrocms#4227]
With add-on Streams Module on PyroCMS 3.3.3, attempts to edit a field assignment produces a 404 page with debug off.  With debug on - the top most notice in the list offers the following:

/Users/Mac/Sites/pyrocms333.dev/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php
 
        // First, we will see if we can find a matching route for this current request
        // method. If we can, great, we can just return it so that it can be called
        // by the consumer. Otherwise we will check for routes with another verb.
        $route = $this->check($routes, $request);
 
        if (! is_null($route)) {
            return $route->bind($request);
        }
 
        // If no route was found we will now check if a matching route is specified by
        // another HTTP verb. If it is we will need to throw a MethodNotAllowed and
        // inform the user agent of which HTTP verb it should use for this route.
        $others = $this->checkForAlternateVerbs($request);
 
        if (count($others) > 0) {
            return $this->getRouteForMethods($request, $others);
        }
 
        throw new NotFoundHttpException;
    }
 
    /**
     * Determine if any routes match on another HTTP verb.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    protected function checkForAlternateVerbs($request)
    {
        $methods = array_diff(Router::$verbs, [$request->getMethod()]);
 
        // Here we will spin through all verbs except for the current request verb and
        // check to see if any routes respond to them. If they do, we will return a
        // proper error response with the correct headers on the response string.
        $others = [];
 
        foreach ($methods as $method) {
            if (! is_null($this->check($this->get($method), $request, false))) {
                $others[] = $method;
Arguments
1. ""  
=========================================

On PyroCMS 3.3.1 - I dont get this error and I can edit the assignment OK.

**Comment by RyanThompson** [comment]
Fixed! Thanks for the heads up.

**Comment by ikoniqoz** [comment]
Hey Ryan, whats the fix and how do I get it ?  - FWIW: I am now seeing this error on my 3.3.1 site - which I didn't get last week....

**Comment by RyanThompson** [comment]
Looks like you might be out of date on this. Make sure you're requiring the latest version!
