### ISSUE TITLE
[streams-module] File FT and Image FT do not upload files

### ISSUE THREAD

**Issue by ikoniqoz** [pyrocms/pyrocms#4228]
Have experienced this on both pyrocms 3.3.1 and 3.3.3.

Error log sample:
2017-03-17 02:05:19] local.ERROR: Exception: The file must be a file of type: png, jpg. in /Users/Mac/Sites/pyrocms333.dev/core/anomaly/files-module/src/File/FileUploader.php:98
Stack trace:
#0 /Users/Mac/Sites/pyrocms333.dev/core/anomaly/file-field_type/src/Http/Controller/UploadController.php(50): Anomaly\FilesModule\File\FileUploader->upload(Object(Illuminate\Http\UploadedFile), Object(Anomaly\FilesModule\Folder\FolderModel))
#1 [internal function]: Anomaly\FileFieldType\Http\Controller\UploadController->upload(Object(Anomaly\FilesModule\File\FileUploader), Object(Anomaly\FilesModule\Folder\FolderRepository))
#2 /Users/Mac/Sites/pyrocms333.dev/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)

SAMPLE SCREENSHOT:
This example was taken from an attempt to upload  an image file with the Image FT:
![image-ft-select](https://cloud.githubusercontent.com/assets/3609155/24030019/76ada262-0b2e-11e7-811e-46e83d719c2b.png)
 
I had made sure that I created a new folder for the uploads and had made png and jpg files allowed for the folder.

**Comment by RyanThompson** [comment]
I don't see an error in the screenshot but the exception is saying that you uploaded the wrong file type. Can you try not dragging into the uploader but instead clicking and selecting what's allowed? Also send a screen of your upload screen with a failed upload. Alert should display the error on upload

**Comment by RyanThompson** [comment]
Closing this for now cause I think it's config issue - but will stay with it until you get it sorted! Cleaning house a bit :-P

**Comment by ikoniqoz** [comment]
My Bad ! I should have provided more detail. The screenshot is what I observed when I attempted to upload a file. Cant recall now which field type was used in that example. However, I have just now tried again and in this case I was using pyro3.3.1 with the FILE FT which is shown in the included screenshot. You will see that I have a field named "Photo". which is using the FILE FT. All I have done here is clicked on the blue Select File button and this is the result. I dont see any way I can upload a file here. What am I missing ?

![screen shot 2017-03-20 at 11 22 01 am](https://cloud.githubusercontent.com/assets/3609155/24086264/6db9334a-0d60-11e7-8937-07ca1b19056d.png)

**Comment by ikoniqoz** [comment]
And, following on from the above. In this next example, I selected the Upload button, then in the upload modal I selected the Select option, then chose a jpg file as you can see. 

![screen shot 2017-03-20 at 11 42 05 am](https://cloud.githubusercontent.com/assets/3609155/24086391/c7e28950-0d62-11e7-8e58-2257100f2b6d.png)

The target folder has both jpg and png files allowed and I can upload png and jpg files to the folder from within the Files module.

The same issue was observed in PyroCMS 3.3.3

Hope that all this helps.

**Comment by ikoniqoz** [comment]
Forgot the log: Here is a sample from the log.

2017-03-20 00:41:53] local.ERROR: Exception: The file must be a file of type: jpg. in /Users/Mac/Sites/pyrocms331.dev/core/anomaly/files-module/src/File/FileUploader.php:98
Stack trace:
#0 /Users/Mac/Sites/pyrocms331.dev/core/anomaly/file-field_type/src/Http/Controller/UploadController.php(50): Anomaly\FilesModule\File\FileUploader->upload(Object(Illuminate\Http\UploadedFile), Object(Anomaly\FilesModule\Folder\FolderModel))
#1 [internal function]: Anomaly\FileFieldType\Http\Controller\UploadController->upload(Object(Anomaly\FilesModule\File\FileUploader), Object(Anomaly\FilesModule\Folder\FolderRepository))
#2 /Users/Mac/Sites/pyrocms331.dev/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
