### ISSUE TITLE
[Repeater field] nested repeaters saved multiple times

### ISSUE THREAD

**Issue by stijntilleman** [pyrocms/pyrocms#4229]
I created a test setup to figure something out and hit this little issue:

### setup
- PHP 7.0.6
- PyroCms 3.3

### structure
- YearModel
  - repeater field `months` with related entity to `MonthModel`
- MonthModel
  - repeater field `weeks` with related entity to `WeekModel`
- WeekModel
  - repeater field `days` with related entity to `DayModel`
- DayModel
  - repeater field `hours` with related entity to `HourModel`
- HourModel

### issue
when I create a WeekModel with multiple days which have multiple hours the hours are created multiple times.

When I try to create 1 year with 1 month which has 1 week which has 1 day which has 1 hour
- 1 year
  - 1 month
    - 1 week
      - 1 day
        - 1 hour

but I get
- 1 year
  - 1 month
    - 2 week
      - 4 day
        - 8 hour

I know it's a stupid example but it makes a point 😄 

[my little toybox with the example code](https://github.com/stijntilleman/toybox-module)

**Comment by RyanThompson** [comment]
Are records duplicating or are you just finding that the events are firing multiples times

**Comment by stijntilleman** [comment]
Records are being duplicated, but I think the events being fired multiple times could be the issue.

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/repeater-field_type/commit/23cbae4c9e5ca8dc4a7658c7c0e533ca3e636cb9

Same fix was applied to grid as well.
