### ISSUE TITLE
 problem in  online 

### ISSUE THREAD

**Issue by Zakrota** [pyrocms/pyrocms#4231]
The icons and some images inside css on my theme not worked in online but in local worked very well how can I fixed that.. ???

**Comment by RyanThompson** [comment]
Clear your assets for good measure but probably browser cache. Fixed an issue where icons where not centering and pushin text around so wrapped them in span which was previously hidden. The above steps should get things ironed out! Sorry for geninconvenience :-/

**Comment by Zakrota** [comment]
sorry but in addition  The icons and glyphicon not access even stater theme and accelerant theme . where is should be the problem??? this  actually explanation my problem Mr. @RyanThompson .
