### ISSUE TITLE
glyphicon  problem on pyrocms 

### ISSUE THREAD

**Issue by Zakrota** [pyrocms/pyrocms#4233]
sorry but in addition The icons and glyphicon not access even stater theme and accelerant theme . where is should be the problem??? this actually explanation my problem Mr. @RyanThompson . online not locally ???

**Comment by RyanThompson** [comment]
Does your browser console show any 404s / more information?

**Comment by Zakrota** [comment]
Yes sir ,how can i fix that ??? and there is note : it is too slow work in server ,where is the problem also???
![untitled1](https://cloud.githubusercontent.com/assets/24638537/24079645/23b7379a-0c95-11e7-8f93-dc83a6df0747.jpg) 

![untitled](https://cloud.githubusercontent.com/assets/24638537/24079630/d72f5916-0c94-11e7-9c54-5ed68ea1dc0b.jpg)

**Comment by Zakrota** [comment]
Is that about security Vulnerabilities I don't know that my estimated   ???

**Comment by RyanThompson** [comment]
I need to see the URL you're installed under. I am guessing that the web root is incorrect.

**Comment by RyanThompson** [comment]
Blur out any private aspects of it.

**Comment by RyanThompson** [comment]
Going to close this for now - I think this is a setup problem but need more information.
