### ISSUE TITLE
[feature-request] Add in-place-edit mode for forms

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4235]
It is a very nice feature - to change the order of navigation menu right in place.

I think it would be much useful, to have the similar mode for forms.
In this mode, users should be allowed to change the order of fields in a form and also, to move fields between sections.

**Comment by RyanThompson** [comment]
Related to https://github.com/pyrocms/pyrocms/issues/4180

I would like to create a builder for custom "areas" like this in the control panel. So you could fetch a layout definition and insert it into your forms to give people control.

Do you know if any nice bootstrap grid builder plugins exist? Checkout the screen Matt posted in the other issue.
