### ISSUE TITLE
[ API-module ] module not being marked as active when checking for permission

### ISSUE THREAD

**Issue by lenssoft** [pyrocms/pyrocms#4236]
When using password based oauth the modules are not marked as active 
ie when accessing  /api/entries/users/users <-> anomaly.module.users module is not marked as active. This causes the missing of "anomaly.module.users::users.read" permission which should be automatically added.
Anomaly\ApiModule\Resource\ResourceAuthorizer::class

**Comment by RyanThompson** [comment]
Forgot to update - this should be fixed now.
