### ISSUE TITLE
[Users Module] Default admin role

### ISSUE THREAD

**Issue by RienMoeyaert** [pyrocms/pyrocms#4237]
The default admin role is called '**Admin**', with the description 'The **super admin** role.'
In my opinion this role should be called '**Super admin**', so we can still have a 'admin' role with restrictions.

We now end up making a 'Client admin' for this.

**Comment by RyanThompson** [comment]
Ya.. hindsight is 20/20 lol. I think I was looking for simplicity in the naming but.. eh. To be honest there is too little cost / vs reward here to consider changing it now. I don't feel like it's a big deal. We use "Owner" a lot ourselves.
