### ISSUE TITLE
[wysiwyg-field_type] Use Froala for v3

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4242]
https://www.froala.com/wysiwyg-editor

**Comment by stefanpkc** [comment]
@RyanThompson, it should be in v3. But I think as a priority it’s not at the top. we can wait a while for Froala.

**Comment by ghost** [comment]
Yes i like it too. Especially because of vue :) But also agree with @stefanpkc , there are other more pressing tasks to take care of before that are more important.

**Comment by Piterden** [comment]
There is another one https://quilljs.com/

**Comment by RyanThompson** [comment]
As awesome as it is - literally 0 need for it right now.
