### ISSUE TITLE
[Streams Core] Add error class to tab parent when tab child-field fails validation

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4244]
For example, if tab "B" has 3 fields - title, slug, and description - and the required "title" field is left empty, a css error class would be added to the html element with the tab title.  I would think default styling would just be to color the text red, but people could theme it however they wanted once the css class was there.

Here is what this looks like in Craft: https://goo.gl/bB3AMI

**Comment by RyanThompson** [comment]
Agreed!

**Comment by Piterden** [comment]
Also, it would be nice to have an ability, of disabling active class in any parent menus.
The `exact` option, which should disable all active classes, excepting highest by the depth, most nested item.

**Comment by RyanThompson** [comment]
@Piterden can you open another issue and try and illustrate your point a bit more?

@mattcdavis1 done!

**Comment by mattcdavis1** [comment]
@RyanThompson Great - thanks!

**Comment by Piterden** [comment]
There is also would be nice to display red star directly on tab, if this tab has required fields inside.
![image](https://cloud.githubusercontent.com/assets/5930429/25116358/ed68c658-2414-11e7-8549-dfb1c5c658c2.png)
