### ISSUE TITLE
[repeater-field_type] Nested Repeater fields return white page or break the form page after save

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#4245]
As title. If I create a new record with nested repeater fields, on save I'm returned a white screen. If I go back and view, the record is saved but none of the repeaters are (parent or child).

If I create a new record with just the top level repeater field, it saves as in intended. If I then go back and add a new row to the repeater and save, it breaks the form page from then on:
![](https://cloud.githubusercontent.com/assets/5254791/24230653/4a6e589a-0fd4-11e7-915c-c85a6bd9c699.png)

**Comment by fryiee** [comment]
I believe this is related to #4288

**Comment by Piterden** [comment]
Btw, if you would nest repeater in grid, you might avoid that issue. At least I can do it.

**Comment by RyanThompson** [comment]
See answer to other - can't repeat without image FT and even still I can't but have seen this elsewhere. Up local memory for starters.
