### ISSUE TITLE
[Streams Core] Allow option to store WYSIWYG content in database only

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4251]
See title - also reference slack discussion.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/wysiwyg-field_type/commit/4b31f38ee51849fec1bfbc962f45fb920bd1e42c

Updating docs now

**Comment by RyanThompson** [comment]
override `storage.php` config for default behavior changes

**Comment by mattcdavis1** [comment]
great - thanks!
