### ISSUE TITLE
[Files Field Type] (Feature Request) Paginate when more than "X" entries

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4253]
When there are more than X files, add pagination and possibly search filter.  [This entry](https://goo.gl/NYrwj2), for example, has 103 photos associated with it.  This functionality (pagination / search filter) would be nice for grid / repeater also (again, only if there is more than X relationships)

**Comment by RyanThompson** [comment]
I think this is a must - but I'd like to see it added as a table feature in general. Something like "Load more entries" for an ajax behavior in tables.

**Comment by mattcdavis1** [comment]
Well - the only think that i don't like about load more is that you can't go directly to a certain page.  I think pagination would be preferable to load more for this reason.

**Comment by bloveless** [comment]
Just keep in mind that the reason that we disabled pagination when a table or whatever is sortable is that is is quite difficult to move items from one page to another page when pagination exists.

It might be possible if you can adjust the number of items that are visible including an option to show all. Imagine moving an item from position 1 to position 100 when you can only see a few rows at a time. Currently without adjusting the pagination limit you wouldn't be able to move an item outside of the rows that are visible when that entry is visible.

**Comment by mattcdavis1** [comment]
Sortable + pagination is definitely a challenge but that's a problem that really needs to be solved regardless of how this particular issue is handled (sortable streams module streams also would have this issue).  One way would to handle this would be to have a modal dropdown where you could choose the parent (in addition to drag).  I'd be interested to see how other systems are handling this challenge as well/

**Comment by bloveless** [comment]
I think one way other systems get around this is by allowing the user to select the number of entries that show up on the page, including the ability to list all on the page at once. Then it can default to 10 entries (or whatever) and if you need to move it to the next page then you select "Show All", or 20 entries, or whatever allows you to see enough of the list that you can put the item where you want to.

Not sure how the modal would work since you would be selecting the sibling to move the entry before or after. Sounds a little clunky/foreign in my opinion.

**Comment by mattcdavis1** [comment]
I don't think the per-page option is a good one.  i hacked that into old pyro but ideally you want a system that can handle any number of entries.

**Comment by Pixney-William** [comment]
Another great idea @mattcdavis1

**Comment by RyanThompson** [comment]
Just as a note to self; we need to improve the table ajax functionality possibly in best suit this requirement.
