### ISSUE TITLE
[Repeater Field Type] New repeater rows include duplicate scripts / css

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4254]
Screenshot: https://goo.gl/he8lTg

Ideally, it would be nice to just include one empty row on the page and then just clone it with javascript and avoid the ajax call altogether.  That would be quicker and would also solve the issue of duplicate scripts.

**Comment by RyanThompson** [comment]
I've got this on my radar and am working on a cleaner approach involving a core app JS variable and API.. but it's gonna be a bit to handle this. By and large FTs need to be standalone and this is how I accomplished it thus far. Will fix later as it becomes more appropriate.

Thanks!
