### ISSUE TITLE
[Streams Module] (Feature Request) Add Core Fields

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4255]
Currently, all streams have the following core fields: id, sort_order, created_at, created_by_id, updated_at, updated_by_id, [deleted_at (if trashable)].

In addition to these, i would like to see the following columns added as core fields:

title, title_slug, published_date, expiration_date, enable / status (think we discussed this one elsewhere)

The advantages of adding these fields would be:

* You always need some field to show in the listing view.  If you know you can count on a "title" field you have a more sensible default than "id"
* It's a a fairly common use case to schedule  a date for when a given entry is first available and no longer available.  adding published_at / expired_at would accommodate this.
* As discussed elsewhere statuses can be useful for enabling / disabling post (and possibly additional states beyond this).

If this causes issue with people who do not want these fields , they could be optional and enable-able via a toggle on streams indicating that a given stream is the type of stream that makes use of these fields.  

I realize that, obviously i can just add these fields myself now.  However, the advantage of adding these to the core is that other areas of the core can then rely on these fields to add new functionality.  Plus, it saves the repetition of adding these fields to every stream.

**Comment by RyanThompson** [comment]
There's a lot to think about on these ones but I feel like more than a few of these are a good idea.

Regarding the title though that's already in the streams table as `title_column`. Is that what you're looking for there?

I could see though like expirable and status_group but I have to think a little more on the others. Particularly the scheduling.

**Comment by mattcdavis1** [comment]
Regarding the title_column - i realize that there is an option to select the title_column when creating a stream but it defaults to id.  By adding `title` as a core field you could default that to `title` since you could rely on that field being there.

Also - just something to think about from a UI perspective. If you added the above suggested fields, the create / edit form could have something like this: https://goo.gl/tawwUC

**Comment by bloveless** [comment]
I just wanted to throw my $0.02 in here. title, title_slug, published_date, expiration_date I've got quite a few data streams that store pure data and I would not like any of these fields in here. You'll notice that I've omitted the enabled/status field because I do feel like that can be used for more than most of the streams.

I do use title and slug for many of my streams, but I don't think it is a good idea to force these columns on every stream. One of my largest data streams keeps track of page visits and form submissions. Neither of these would benefit from any of the fields listed here. And a table with approx a million rows that is forced to have those fields seems very wasteful.

**Comment by mattcdavis1** [comment]
@bloveless - as i mentioned:

> If this causes issue with people who do not want these fields , they could be optional and enable-able via a toggle on streams indicating that a given stream is the type of stream that makes use of these fields.

I think including these fields could be a configuration option either at a stream level or a namespace level.   I think that for the majority of use cases these fields would be helpful though (and this functionality is frequently expected by clients based on experience with other CMSs).

**Comment by RyanThompson** [comment]
Some if not all of these less title and title_slug are on the roadmap.
