### ISSUE TITLE
[Streams Core] (Feature Request) Add Twig "Cache" Tag

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4257]
It's possible that this functionality exists and i'm just missing it (looks like there is already an issue for documenting the view system #4198).  

The way this would work is that you wrap your content inside a cache tag and the next time the page is request, generated html from cache is displayed.  For example:

``` twig
{% cache %}
    {% for post in posts %}
       {{ post.title }}
    {% endfor %}
{% endcache %}
```

The first time this code runs, the generated html would be saved to the database.  The next request would display the generated content rather than processing the twig logic.  The default cache key would be the url but the cache tag could accept custom keys.  For example, you might want to cache the main nav globally rather than per page.  So you would do something like:

``` twig
{% cache globally using key 'site-header' %}
    {{ include('_partials/header', {pageNav: block('pageNav')}) }}
{% endcache %}
``` 
As for clearing the cache, Craft has logic that tries to have an awareness of the content in a given cache block and intelligently clear the cache on stream save.  This works to a point but there are times when it doesn't.  I typically just clear the entire template cache on any save or deploy.

The cache tag is particularly helpful on more complex pages where there is a large number of queries and relationships.

**Comment by RyanThompson** [comment]
Wrote this up for ya ^_^ https://pyrocms.com/help/developer-tools/cache/caching-in-twig

**Comment by RyanThompson** [comment]
Let me know if it's needing any more detail!

**Comment by mattcdavis1** [comment]
great - thanks! A couple of questions:

* Is there an option to globally disable cache?  For example - when in development i typically don't want any caching.  Craft has an enableTemplateCache config variable which i typically use an ENV value to set.  I realize that there is some auto invalidation offered but for more complex scenarios i'd prefer to be able to just globally enable / disable template caching.

* The article reference how to clear the cache on a stream but is there a way to just wipe out the whole template cache?  Craft has a GUI button for this.  Does artisan cache:clear remove template caching?  Is there a way to clear the template cache without clearing the entire cache?
