### ISSUE TITLE
[Streams Core] Document functionality when deleting storage directory

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4261]
Currently, if you delete all files in the storage directory (or do a clean clone of the database), there's no way to get them back because you can't even run artisan commands at that point.  there should be a way to generate all needed files via composer + artisan + database.

Maybe the solution is just to add some storage files to git - if so would be nice to know which are required.  Or maybe just store these files in a separate directory.  Actually, that probably wouldn't be a great solution since the models would likely be generated on a remote server.  Ideally, i think it'd be best if artisan could run without depending on those models being there (user model, roles, settings, etc).  That way streams:compile could regenerate the needed models.

**Comment by Piterden** [comment]
The solution when you delete all streams generated models is:
- in the `.env` file, change flag INSTALLED to `false`
- run `php artisan streams:compile`
- toggle the flag back to `true`

You should guess about it self, it's so intuitive)))

https://github.com/anomalylabs/streams-platform/pull/365

**Comment by mattcdavis1** [comment]
@Piterden - this does not work if you delete all the files in the storage directory.  The `php artisan streams:compile` does not work when the entire storage directory is wiped out.

**Comment by Piterden** [comment]
I know thnx))

**Comment by Eighke** [comment]
@Pixney-William 

Piterden solution is working currently, even if you delete completly `/storage`. But it should be documented somewhere I think.

> i think it'd be best if artisan could run without depending on those models being there
Would be great, but I don't think it is posible currently (the problem is the binding of Model... that are in storage).

**Comment by Pixney-William** [comment]
Yes, need doc. I will tag it as document instead and see to it being done.
