### ISSUE TITLE
[Users Module] (Feature Request) Add Role Based Field Assignments / Validation

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4264]
It would be great to be able to assign user fields by role rather than just applying all fields to all users.  One common example would be front end only users.  These will likely have varying and different requirements from admin user / control panel users.

This could just be a mask - but not sure if `skips` would work because different roles would have different required fields (not sure if skips just hides field or also skips validation).

Additionally, since there is no assignments area in the users module, there is currently no way to set validation (required, etc).  It would be nice to have the assignments functionality as the streams module.

**Comment by mattcdavis1** [comment]
Actually - i guess assigning to roles doesn't work since that's a one to many.  Maybe when creating a user there is a "Profile" dropdown.  Field sets could then be associated with a profile.

**Comment by RyanThompson** [comment]
This has been asked before but logistically it's a mess. Roles having different fields / the same fields / validation overlapping and so on.. Sorry no go here!

What I've done in the past is used multi-form builders in my addons where I needed this kind of functionality which is / has only been for a shop.

**Comment by mattcdavis1** [comment]
@RyanThompson - what about my second suggestion?  We could associate fields with profiles instead of roles.  You would just create a user_profiles namespace and then a dropdown in the users form showing streams in the user_profiles namespace which could be associated with the user.
