### ISSUE TITLE
[Steams Core] (bug) Deleting a field from the Users Module only deletes assignment

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4266]
Deleting a field from the Users Module only deletes the assignment.  I noticed this when i deleted a field and then tried to add it back and was unable because the slug already existed.  Since there is no assignment interface in the users module, the field needs to be deleted as well.

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/users-module/commit/0d8219a97d29b23c290492a24270e13905078c60

Thanks!

**Comment by mattcdavis1** [comment]
thanks!
