### ISSUE TITLE
[Streams Core] Keep hash in tabbed Form sections for URL

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#4267]
Would be useful for multiple reasons, direct links as well as pagination within tabbed views, for example:

![image](https://cloud.githubusercontent.com/assets/5254791/24394790/155427d4-13e9-11e7-8a41-30e8849f4b03.png)

**Comment by Piterden** [comment]
https://github.com/pyrocms/pyrocms/issues/4312

**Comment by RyanThompson** [comment]
You mean hashing opens up active tabs?

**Comment by RyanThompson** [comment]
I just can't do sticky/cookie tabs

**Comment by Piterden** [comment]
And what here?
![image](https://cloud.githubusercontent.com/assets/5930429/25137790/7154b1c4-2461-11e7-9edf-839135005273.png)
