### ISSUE TITLE
[Streams core?] duplicate entries when translatable

### ISSUE THREAD

**Issue by ddnetters** [pyrocms/pyrocms#4268]
The table builder and `entries()` method show duplicate entries for some reason.

**Steps to replicate**
1. `composer require wirelab/locations-module` 
_The same bug appears in multiple other modules but this one was the easiest for duplicating it_
2. Enable multiple languages
_I used EN and NL_
3. Make a new location where the translations contain different values.
For example:
```
en name = 'example location'
nl name = 'example location 2' 
```

**Comment by ddnetters** [comment]
Temp fix: _(Breaks postgres)_

In the EloquentTableRepository you can change line 49 to `$query = $query->select($this->model->getTable() . '.*')->distinct();`

and in the EloquentQueryBuilder change line 234 `)->distinct();`

**Comment by RyanThompson** [comment]
Fixed! This was a doozy: https://github.com/anomalylabs/streams-platform/commit/938bccdf631122b74a1803e4c325abb6787e1a06
