### ISSUE TITLE
[navigation-module][bug] Links with Allowed Roles set not working properly

### ISSUE THREAD

**Issue by agustindidiego** [pyrocms/pyrocms#4269]
![screen shot 2017-03-20 at 5 31 45 pm](https://cloud.githubusercontent.com/assets/4682822/24120618/00bc8a2e-0d94-11e7-90aa-37e54aa08971.png)
In the screenshot "My Account" has "User" Role set as Allowed Roles.

Steps to reproduce:
1. Create a new Menu.
2. Add a link with "User" set as Allowed Role and save. Link shows the lock icon.
3. Add another link also with "User" set as Allowed Role and save. Previous created link doesn't show the lock icon.

If the menu is rendered in the frontend, the first created link is shown for Guests when it shouldn't since it has "User" set as the only Allowed Role.

**Comment by agustindidiego** [comment]
I found the issue. Not sure if it is correct or not, but...:
On class Anomaly\NavigationModule\Link\LinkModel.php line 50.
Removing 'allowedRoles' from $with protected property fix the issue.
@RyanThompson

**Comment by RyanThompson** [comment]
This was fixed elsewhere - make sure you are up to date and try again. We can’t remove these from $with as optimization here is critical.

**Comment by RyanThompson** [comment]
This should have fixed it: https://github.com/anomalylabs/users-module/commit/e8025aa1554d1bed0f5a6a1697e1bdab51b1e25c

**Comment by agustindidiego** [comment]
Confirmed. Fixed.
Thanks!
