### ISSUE TITLE
[Streams Core] (Bug) Updating "Is this field unique?" does not update DB constraint

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4270]
If you create an assignment and set the "Is this field unique?" value to "Yes", then save, and then update the value to "No" the database constraint is not removed.  This causes an error when one attempts to save a duplicate value for the given field.

**Comment by RyanThompson** [comment]
This has been fixed: https://github.com/anomalylabs/streams-platform/commit/6774b393498bd521b688a9fe864aa8d4d1d4b494
