### ISSUE TITLE
[Pages Module] (feature request) Allow changing of page type

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4271]
Typically, when i start developing a site i want to create a CMS page for every site map page but i'm not always sure at that point what the fieldsets will be.  Also, even when I think I have all the info, things often change and areas of shared fields sets are identified as the site progresses.  It would be nice to be able to change the page type and transfer any data for fields that are the same between page types.  The existing entry (in the old stream) would not be deleted until the page was deleted (so if you changed back, all your data would be there).  

This would mean that on page delete, you would need to loop through all page types to delete data for a given page.

**Comment by RyanThompson** [comment]
A garbage collection query could do this too - I have had something like this planned for a while and have been thinking about. It would only transfer matching files mind you..

**Comment by RyanThompson** [comment]
Bout to tag in pages v1.5 and will do the same in posts: https://github.com/anomalylabs/pages-module/commit/b62d16177747704702bfb36b2874609b9fa7db7f
