### ISSUE TITLE
[Streams Module] (bug) Latest composer update breaks table headings

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4272]
See screenshot: https://goo.gl/gWZyQl

**Comment by mattcdavis1** [comment]
Looks like this is only occurring in instances that i have manually set field headings.  here is an example of my settings for one of the streams with missing headings:

```php
'package_offerings' => [
    'columns' => [
        'Title' => 'title',
        'Acres' => 'acres',
        'Featured' => 'featured',
        'Active' => 'active',
    ],
    'options' => [
        'heading' => 'module::admin/groups/heading',
        'order_by' => ['title' => 'asc'],
    ],
],

**Comment by mattcdavis1** [comment]
Ok - resolved the problem.  looks like the key / values were switched.  Slug is now the key (makes more sense this way).

**Comment by mattcdavis1** [comment]
Hmm - maybe not.  reversing things fixed the header but then all the fields got messed up:

https://goo.gl/jG4MaA

**Comment by RyanThompson** [comment]
I'll take a look - it was technically incorrect and was fixed but might need a little more push

**Comment by mattcdavis1** [comment]
I was able to get it working with keys only but not sure what the proper way is for a custom title now.  This works:

```php
'package_offerings' => [
    'columns' => [
        'title',
        'acres',
        'featured',
        'active',
    ],
    'options' => [
        'heading' => 'module::admin/groups/heading',
        'order_by' => ['title' => 'asc'],
    ],
],
```

I just don't know how to assign custom titles now.

**Comment by RyanThompson** [comment]
The shorthand method SHOULD be `'title' => 'Title'` which I am fixing now but a sure fire way would be:

`'title' => ['heading' => 'Title']`

**Comment by RyanThompson** [comment]
This should cover it: https://github.com/anomalylabs/streams-platform/commit/df7683835b30ef9dce76314185b546045d0cbefc

**Comment by mattcdavis1** [comment]
great - thanks!
