### ISSUE TITLE
[Pages Module] Resolve URL to Page in single query

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4274]
In the current site that i'm building (just getting started), PyroCMS is generating 60 queries just to load a blank page.  The majority of this come from running separate queries for each page  (I have 42 pages) via `$pages = $pages->sorted();` in `PagesModuleServiceProvider`.  

There should only be one query to retrieve the page that matches the path in the url.  Even if you did want to query all the pages (which i don't think should be the approach) - this could be done in a single query.  

https://goo.gl/JKksI4

**Comment by RyanThompson** [comment]
Agreed - Ill get er patched.

**Comment by mmodler** [comment]
I think the issue is still open? I also see tons of queries on simple pages :(

**Comment by Pixney-William** [comment]
@RyanThompson This has to do with performance, and since its still open. Please have a look at it. I have also been worried about the queries:)

**Comment by Eighke** [comment]
@Pixney-William, already done I think, currently `$pages->sorted()` will create only a single query. Even with 100 pages

**Comment by Pixney-William** [comment]
Great! Thanks!
