### ISSUE TITLE
[Streams Core] Possibly Generate Multiple Models Per Streams for Performance

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4275]
I'm starting to build out the front end of a site now, and i'm once again running into severe performance issues that i think are unnecessary.  Here is what I'm doing:

Retrieve all listings from a stream (1162 records in this case).  Loop through each one and display 5 non-relational entry attributes (text fields).  Here are the results:

With Pyro Entry Model: Average of 675ms - 725ms
With Eloquent-Only Model: 235ms - 275ms

Pyro is almost 3 times slower than just eloquent.  And what's worse - it get slower for each attribute that is outputted due to all the stuff that Pyro does with Field Types.  

What's so frustrating to me is that all i want is my data - i don't want all the additional field type functionality, but i'm paying for it (in performance) anyway, whether i want it or not.  This (extra functionality) might be nice to have as opt-in functionality but not as forced functionality accompanied with a severe performance penalty.

I realize that i can just create my own models, it just sucks having to do that extra work for each stream.  It's really nice to have these auto-generated (especially the relationships).  I'm wondering if potentially 2 models could be auto-generated when saving a stream.  One that is feature focused and another that is performance focused.  Ideally, the performance-focused one would have access to as much of the non-performance-model functionality as possible, but it would be all opt-in.

For example, instead of running field events and such via a magic method when i attempt to access a property, this functionality could be accessible via a `getFieldValue('property)'` method.  This still provides the functionality without forcing it (and the accompanying performance hit).

Ideally it would be nice if this was the way the default entry model was constructed but i'm guessing it's too far down the road to change that.  That's why i'm thinking maybe generating a second model might be a good solution.

I realize that 1162 models is alot to retrieve (i won't actually be displaying that many for the page i'm building - it was just helpful for a quick performance check to retrieve all) but:

1. Even with a smaller set, by the time i've queried everything else i need on the page (dropdowns, options, etc) it will be still be a significant number.
2. The fact that i'm paying (in performance) for something i don't need is frustrating whether it's 1ms or 1000 ms.
3. Even with alot less models, i'll be displaying alot more than 4 properties so the savings in the reduced number of models will be somewhat offset by the cost of displaying additional fields.
4. There are legitimate use cases for that many models such as a DataTables table that you fully-populate and filter via javascript.

There's alot to like about Pyro and i think overall it's got alot of potential but these continued performance issues have been a major disappointment for me.  I really hope that solutions can be found that meet both performance and functionality goals.  For now i suppose i'll just create my own models.

**Comment by fryiee** [comment]
I'm going to work on a patch for this. What would you ideally want to be generated by `make:stream` ?

**Comment by mattcdavis1** [comment]
@fryiee - i've been creating my streams via the Streams Module - i'm not sure if it calls `make:stream` behind the scenes or not.  Typically, i'll create the streams on the remote server via the streams module, then download the database and run `streams:compile` locally to generate the models for my dev environment.

**Comment by fryiee** [comment]
@mattcdavis1 Sorry, I more meant what would you like to see in a `BasicEntryModel` in terms of functionality that is removed/kept from the existing `EntryModel`? From my understanding just having direct access to the relationships and the model attributes without any field information is the preferred route?

**Comment by fryiee** [comment]
It seems that a lot of this would be solved simply by defaulting the EntryModel's `getAttribute()` with the functionality in `getRawAttribute()` - i.e. removing the call to `getFieldValue()` in any sort of BasicEntryModel implementation.

**Comment by mattcdavis1** [comment]
@fryiee - main think i'm looking for is the relationships and attributes yeah.  As far as just removing the`getAttribute` method from the current model - my recollection is that that's not enough.  The performance was still subpar even after removing that I believe.  There's just too much stuff going on generally with those models (at least for simply displaying data - some of the stuff makes more sense for read/write/delete).  I'd like to see something that matches raw Eloquent performance.

**Comment by fryiee** [comment]
I'm not sure what else could possibly be running when you hit an attribute that is causing the slowdown - or is it the initial retrieval? I'm guessing that retrieving translation etc adds to the overhead. I just added a really basic method set on the base EntryModel and added to the conditional in getAttribute() and I saw greater than 3 fold speed increases.

![image](https://cloud.githubusercontent.com/assets/5254791/24505970/a6ba4450-15a7-11e7-8bee-af3898acf996.png)

**Comment by fryiee** [comment]
Can't you also just call `getRawAttribute('attribute')` / `setRawAttribute('attribute')` as well? What does your speed test look like when using that instead of the getter?

**Comment by fryiee** [comment]
@RyanThompson may have more insight into what we can already do / what we need to add in terms of improving the performance of the model. I would say that creating another model when generating streams is probably unnecessary, but potentially constructor flags or method-set flags to disable additional retrieval of non-essential things could be used to squeeze out better performance.

**Comment by fryiee** [comment]
I've put up a PR for something that will possibly help (or at least prevent the need to call `getRawAttribute()` on everything): https://github.com/anomalylabs/streams-platform/pull/371

**Comment by RyanThompson** [comment]
@mattcdavis1 can you give us some numbers using `getRawAttribute`? Out of curiosity. The functionality is there I think we can achieve this without a separate model. 

Also have you tried simply using the `query` function? I will return basic models: https://pyrocms.com/documentation/streams-plugin/latest#usage/entries/introduction/query

**Comment by RyanThompson** [comment]
Also have you peeked at what it might be that is causing it in FTs? I am interested in reducing that overhead / optimizing it too.

**Comment by mattcdavis1** [comment]
@fryiee @RyanThompson yes - i can definitely do more testing with getRawAttribute.  Probably will be this evening before i get to this.  I'll post back after i've looked into this a bit more.  Oops.  Accidentally clicked the closed button.  Reopened.

**Comment by mattcdavis1** [comment]
@RyanThompson @fryiee 

Here are the results on retrieving 1168 models using $model->all() and outputting 5 text properties:

**Laravel Only** - using standard property access syntax ($model->property): `248.2ms` (Average of 10 requests)

**Pyro Entry Model** using getRawAttribute: `285.4ms` (Average of 10 requests)

So definitely huge improvement.  I think if we just swapped the default to raw and made a method call for getting field type generated values that would be great.  On a side note, it was interesting to note that getRawAttribute actually runs significantly slower on a normal Eloquent model.

As far as the `query` method i tried below and it failed to find the class (looks like it was stripping backslashes):
`{% set properties = query('Anomaly\Streams\Platform\Model\Afm\AfmPropertyListingsEntryModel').get() %}`


So i tried the below which failed on 

> "Target [Anomaly\Streams\Platform\Stream\Contract\StreamInterface] is not instantiable while building [Anomaly\Streams\Platform\Entry\EntryCriteria]." 

`{% set properties = query('Anomaly\\Streams\\Platform\\Model\\Afm\\AfmPropertyListingsEntryModel').get() %}`

As for peeking into the fieldtypes, i did step through and there's just so much going on there i didn't dig into deep i just assumed it was all that it was related to the below.  That 's alot of stuff going on just to access a property:

```
if (!$locale) {
    $locale = config('app.locale');
}

$assignment = $this->getAssignment($fieldSlug);

$type = $assignment->getFieldType();

$accessor = $type->getAccessor();
$modifier = $type->getModifier();

if ($assignment->isTranslatable()) {
    $entry = $this->translateOrDefault($locale);

    $type->setLocale($locale);
} else {
    $entry = $this;
}

$type->setEntry($entry);

$value = $modifier->restore($accessor->get());

if (
    $value === null &&
    $assignment->isTranslatable() &&
    $assignment->isRequired() &&
    $translation = $this->translate()
) {
    $type->setEntry($translation);

    $value = $modifier->restore($accessor->get());
}

return $value;`
```

**Comment by RyanThompson** [comment]
Ya just accessing a property is a little loaded of a process that's taken for granted lol. But, I see some opportunity here to improve simple access needs. Something like entry.raw.attribute where raw set's a flag on the model to force all attributes to raw access.

Will continue looking into this. Thanks for the leg work!
