### ISSUE TITLE
[feature] Add view options to fieldable modules

### ISSUE THREAD

**Issue by ThinkGraphical** [pyrocms/pyrocms#4276]
I would like to be able to choose which fields are shown in the table view for fieldable modules (like posts).

I know you can achieve this by binding your own table builder to override the defaults,
for any other you can adjust the table builder. But i would love to be able to do that in the Pyro backend.

Why? The strength of a fieldable module is that you can add which ever field you like, from the backend, without touching any code. If you have to update the table builder code, that beats the purpose of a fieldable module, in my opinion.

Suggestion:

Introduce in preferences -> modules -> [the fieldable module]
a view options field just like in forms:

![screen shot 2017-03-30 at 11 21 48](https://cloud.githubusercontent.com/assets/1651789/24497718/a4274de8-153c-11e7-804e-8a6533d98f6d.png)

Maybe even extend that with search / filter options, etc...

Really nice would be if you would have view options for the form itself:
divide the fields into form sections, rows and columns, etc... from the Pyro backend.

**Comment by RyanThompson** [comment]
I've got other plans that will allow something like this ^_^
