### ISSUE TITLE
$sections not working on front end form builder(s)

### ISSUE THREAD

**Issue by davestar057** [pyrocms/pyrocms#4277]
It would appear there is an issue when using $sections on the front end theme.

It passes along the section info and fields if you dd($form) element - yet it does nothing with

**Comment by fryiee** [comment]
Have confirmed this issue in both default starter theme and custom theme.

**Comment by agustindidiego** [comment]
sections doesn't work with standard.twig form template, which is the default template if none is provided. You can switch form template and use form.twig, or override standard.twig template on your custom theme.
To change the form template, you need to change the "form_view" option in your FormBuilder.
```
protected $options = [
		'form_view' => 'streams::form/form'
	];
```

**Comment by fryiee** [comment]
This has been fixed in https://github.com/anomalylabs/streams-platform/pull/370
