### ISSUE TITLE
Markdown fieldtype is not rendering twig

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#4278]
If i use any twig inside a markdown fieldtype, it will not be rendered.

`{{ post.content.render|raw }}`

```
non proident, sunt in culpa qui officia deserunt mollit anim id est laborum

{{ snippet('first') }}

Lorem ipsum dolor sit amet
```

The above text is what gets printed to the screen. The problem does not exist with wysiwyg fieldtype.

**Comment by RyanThompson** [comment]
Try using "parse" since rendering is a little different for markdown.

**Comment by keevitaja** [comment]
Yes, it is working.
