### ISSUE TITLE
[Streams Module] Issue with Templates overrides

### ISSUE THREAD

**Issue by agustindidiego** [pyrocms/pyrocms#4279]
It seems that templates overrides only works for templates being loaded with view() function.

Test Cases:
1. Posts partial.
Way to reproduce:
- On Custom Theme, copy template _anomaly.module.posts::posts/partials/posts_ into _views/addons/anomaly/posts-module/posts/partials/_ folder and add some text to it to make it different from the original.
- Navigate to /posts page.

Current behaviour: Custom template is not being used.
Expected behaviour: Custom template should be rendered instead of original one.

2. With a template include in Page Type/Page Layout field.
Way to reproduce:
- On 'Default' Page Type/Page Layout field add the code:
```twig
<div id="posts">
{% set posts = entries('posts').recent().paginate() %}

{% include "anomaly.module.posts::posts/partials/posts" with {"posts": posts} %}

{{ posts.links|raw }}
</div>
```
- On Custom Theme, copy template _anomaly.module.posts::posts/partials/posts_ into _views/addons/anomaly/posts-module/posts/partials/_ folder and add some text to it to make it different from the original.

Current behaviour: Custom template is not being used.
Expected behaviour: Custom template should be rendered instead of original one.

Note: The same happens if the override is added into the Theme Service Provider.

**Comment by agustindidiego** [comment]
https://github.com/anomalylabs/streams-platform/pull/372

**Comment by RyanThompson** [comment]
Thanks again for the PR - working flawlessly.
