### ISSUE TITLE
[Navigation Module] Duplicate entries 

### ISSUE THREAD

**Issue by cewlbird** [pyrocms/pyrocms#4280]
Hi,

first of all thank you for this cewl CMS.
I encountered the following error and wanted to share this information with you.

When I create a new menu it gets displayed twice in the table builder list.
Deleting one of them removes both entries, so it seems to be the same entry just getting displayed twice.

I have activated the following translatable languages: German, Italian, English

<img width="1446" alt="pyrocms_bug" src="https://cloud.githubusercontent.com/assets/25002272/24581450/ff9f9078-171b-11e7-911b-c4eb1844ba43.png">

Thank you in advance for any kind of help.

Best Regards,

CEWLBIRD

**Comment by ddnetters** [comment]
Same issue as https://github.com/pyrocms/pyrocms/issues/4268 @RyanThompson

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/938bccdf631122b74a1803e4c325abb6787e1a06
