### ISSUE TITLE
[Streams Core] (bug) Deleting Model with "Cascades" fails if not trashable

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4285]
I'm building an admin navigation module using the navigation module as a starting point.  For my module i did not want to make use of the "trashable" option for the streams.  I noticed that this causes an issue when trying to delete models.  Deleting fails with: `Call to undefined method Illuminate\Database\Query\Builder::withTrashed()`.  

The specific lines of code are in `Anomaly\Streams\Platform\Model\Command\CascadeDelete`:

```php
$relation = $this->model->{$relation}();

if ($action == 'forceDelete') {
    $relation = $relation->withTrashed();
}
```

To reproduce the issue:

1. Temporarily update the migrations in the navigation module to not be trashable
2. `php artisan module:reinstall anomaly.module.navigation`
3. Create a menu
4. Create a link
5. Attempt to delete the link.  It fails with the error above.

**Comment by RyanThompson** [comment]
This has been since fixed
