### ISSUE TITLE
[repeater-field_type] Repeaters on front-end forms

### ISSUE THREAD

**Issue by sporkandrew** [pyrocms/pyrocms#4287]
Using a repeater on a front-end form doesn't work as the links generated by the 'add' action point to /admin/

**Comment by fryiee** [comment]
There's a PR in for this currently: https://github.com/anomalylabs/repeater-field_type/pull/10

**Comment by sporkandrew** [comment]
Just so anyone else knows - the associated PR is now merged and this Field Type now works in the front end.  Thanks, @fryiee!
