### ISSUE TITLE
[grid-field_type] does not render, when adding files-field_type

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#4288]
Hello,

so in general GRID works with no problems.
When I add a files-field_type - my product edit page, with added grid relations - stops rendering.

Rendered backend page looks similar to: http://pic.webas.lt/webas.lt-bbbc8d5455.png
It looks like it just 'exit()' somewhere.

There are NO LOGS LOGGED, console logs are also empty.

Removing the 'files_field-type' from grid - solves the problem.

( I have also confirmations from Slack, that people with repeater-field_type have identical issue)

Thanks

**Comment by fryiee** [comment]
This issue is also present when you place a file/s field type in a repeater field.

**Comment by RyanThompson** [comment]
This is from GD exhausting memory in thumbnail generation.
