### ISSUE TITLE
[streams-module] Renaming a namespace loses association with streams, fields, and entries

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#4293]
I created a stream and later decided to rename the namespace. So I did that, also renaming the slug, and now there are no fields or streams associated with that namespace. I can see in the database streams table that the old namespace is still in there associated with the stream.

For now, I suppose that the namespace slug should not be editable.

**Comment by Piterden** [comment]
That's interesting. How do you renamed it?

**Comment by bloveless** [comment]
I clicked edit next to the namespace, then typed in a new title and slug.

**Comment by Piterden** [comment]
Oh, there is `streams-module`. I confused with streams-platform again.

**Comment by RyanThompson** [comment]
Disabled it for now - there's a lot of moving parts we'd need to update and I don't think the pipeline for managing Streams is ready to handle that much yet without potential timeouts as it updates schema. 

https://github.com/anomalylabs/streams-module/commit/06d1312f59a31c9a4000ca390e1d7d0f128d3d8a
