### ISSUE TITLE
[form-module] view options breaks the entries table view

### ISSUE THREAD

**Issue by ThinkGraphical** [pyrocms/pyrocms#4295]
While i was looking for a way to display info from a related entry in the entries table,
for ex. when you add a relationship field type 'event' as a form field & add 'entry.event.id' to the view options.

I got following error:
`Call to a member function getType() on null` in `anomaly/streams-platform/src/Ui/Table/Component/Filter/Type/FieldFilter.php` on `line 33`

I noticed when 'disabling' the filters, it works like expected.
(in `\Anomaly\FormsModule\Http\Controller\Admin\EntriesController` commenting `line 75`)

**Comment by RyanThompson** [comment]
This is to be expected when erroneous fields are requested in config.
