### ISSUE TITLE
[Streams Core] (bug) php artisan cache:table throws an exception

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4296]
`Anomaly\Streams\Platform\Database\Migration@getStub` 
and
`Anomaly\Streams\Platform\Database\Migration@populateStub` 

both fail when running `php artisan cache:table` because `$this->input` is null

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/cd2b9074cc68f2695a54e395dc829a16805d6471
