### ISSUE TITLE
[Streams Core] Twig Cache fails when cache driver is set to database

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4297]
I ran the migration and the table exists.  also, other items are successfully being cached in the database.  However, when i add a twig cache tags an exception is thrown:

https://goo.gl/OT5t4h

Also, the twig cache tags work fine with the file based driver.

**Comment by Piterden** [comment]
I had a similar cache error with clean Laravel and without twig. It was about half year ago.

**Comment by mattcdavis1** [comment]
Looks like this is the issue: https://laracasts.com/discuss/channels/general-discussion/daeling-with-decryptexceptioninvalid-data

Solved by changing cache database field to LONGTEXT.
