### ISSUE TITLE
[streams-platform] saving of form not always working with 1.2.238

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#4298]
Hello,

I have products module, and FORM updating for products form stopped working starting from 1.2.238

1.2.237 - saving works.
In some forms saving still works with 1.2.238, but I have products form which is quite bigger - it says save success - but nothing is updated.. how we debug this? :)

Thanks

**Comment by Piterden** [comment]
it's because https://github.com/anomalylabs/streams-platform/pull/377 , I suppose

**Comment by huglester** [comment]
Solved in v1.2.251
