### ISSUE TITLE
[Streams Core] Fire Reliable "Saved" event for entries that includes field type saves

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4300]
Currently, the self handling fields are run after the entry is saved so the eloquent saved / saving methods occur too early.  Adding an event after the self-handling loop would help but would still not be adequate since updates made directly on a model would not trigger this event.

For example:

```php
$model = EloquentModel::find(1);
$model->multiple_field_type = [1,2,3];
```
Currently, as soon as multiple_field_type is assigned the accessor updates the database (same with repeater).  This occurs without any save event happening on the parent model.  This in and of itself is an issue in my opinion.  The set accessor should just cache the value and only executed on parent save.  Additionally, all of this should be wrapped in a database transaction so everything can be rolled back if needed if any save is prevented or errors.

One way or another though, there needs to be a single event that notifies me any time an entry or any of it's child relationships are update.  To accommodate this currently i'm having to bind to the field type accessors of the files / repeater field types to hook into attaching / detaching of relationships.

**Comment by mattcdavis1** [comment]
Actually the solution here might be fairly simple.  

1. Provide functionality for setting repeater / multiple fields types without triggering db update (possibly in place already, but ideally via normal assignment).

2. Route all entry saves through `$entryRepository->save($entry)` and handle DB transaction plus child field saving in this repo then fire events on saved / saving etc.  
'entry.saved \Some\Model\Name'

**Comment by Pixney-William** [comment]
@RyanThompson ?

**Comment by RyanThompson** [comment]
This goes against fundamental operations of Laravel. I don't really think going out of our way here is a good idea. There are likely far better alternatives to handle any situations that might warrant this change.
