### ISSUE TITLE
[files-module] Fields in File Not Saving

### ISSUE THREAD

**Issue by jhubb-io** [pyrocms/pyrocms#4301]
When fields are assigned to a folder, the fields are available to edit in the individual files but the values do not save.

http://share.jhubb.io/VhW9mSZDtVo7Ct9g

**Comment by Piterden** [comment]
Show please what you have on 54,55,56 lines of `/vendor/anomaly/streams-platform/src/Ui/Form/Command/SetRepository.php`.
