### ISSUE TITLE
[forms-module] Cannot create a new form.

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#4302]
I've installed the standard form extension and when I try to create a new form I get an error.

![screen shot 2017-04-07 at 4 28 25 pm](https://cloud.githubusercontent.com/assets/535135/24821998/4199391a-1baf-11e7-8e44-a5c45c6736aa.png)

If I bypass this error by checking that $this->getFormEntriesStream() is not null then the form can be created and edited, but I cannot assign fields to the form because the stream doesn't exist....

Anyway I tried to fix it, but alas...

**Comment by RyanThompson** [comment]
Been fixed
