### ISSUE TITLE
Solved - Was using an older version

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4303]
Trying to go to Grid->Assignments it links to the following
`admin/grids/assignments/%7Brequest.route.parameters.stream%7D`

Error Message:
```
Type error: Argument 1 passed to Anomaly\Streams\Platform\Assignment\Table\AssignmentTableBuilder::setStream() must implement interface Anomaly\Streams\Platform\Stream\Contract\StreamInterface, null given, called in /home/vagrant/Code/myfc.dev/core/anomaly/grid-field_type/addons/anomaly/grids-module/src/Http/Controller/Admin/AssignmentsController.php on line 34
```

**Comment by Piterden** [comment]
I have everything alright.

**Comment by ghost** [comment]
Are you sure? @Piterden ?

If you go to : admin/grids

And then you click on assignments (see pic) directly.

![screen shot 2017-04-10 at 15 56 39](https://cloud.githubusercontent.com/assets/1510338/24865062/61433726-1e06-11e7-9ec0-bc13d3d94943.png)
