### ISSUE TITLE
[Navigation Module] Roles functionality not working correctly

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4307]
In some cases, a navigation links' roles are not retrieved correctly.  For example, when i view the navigation tree the lock does not show, but when i go to the options tabs there are roles selected.

Navigation List View: https://goo.gl/rzp69L
Navigation Link Detail View: https://goo.gl/j3dIJB

The same issue occurs on the front end (restricted links show that shouldn't).

The way i've been able to reproduce this is to remove and add back roles multiple times.  Eventually, it registers incorrectly.  

The issue is resolved when i change `$roles = $entry->getAllowedRoles();` to `$roles = $entry->allowedRoles()->get();` in `Anomaly\NavigationModule\Link\Tree\LinkTreeSegments`

Haven't had time to dig further than this, for now i've just commented out the line that doesn't work and replaced it with the one that does.

**Comment by mattcdavis1** [comment]
Also - it appears that somehow roles associated with one model are affecting others.  For example, when i removed a role from one of the links, the "Restricted" icon showed correctly on another of the links.  When i added the role back to the second link, the "Restricted" icon was again removed from the other link.

**Comment by RyanThompson** [comment]
On it.

**Comment by RyanThompson** [comment]
Regarding restricted rows that show and should not - careful of being logged in as an admin cause they are allowed to see everything. I've thought about removing this though.. Cause it's confusing. Thoughts on that?

**Comment by mattcdavis1** [comment]
Yeah - i definitely wasn't logged in as an admin when i was testing.  As far as whether an admin should be able to see everything - i was thinking about that too.  The only use case i can think of where you might *not* want an admin to see everything is in cases where you had a large number of items and admin didn't want to see everything because it cluttered things up.

I could go either way on this though.  I can see a good argument for both approaches.

**Comment by RyanThompson** [comment]
I found the issue and am verifying the fix isn’t breaking anything (simple fix / old code). Funny it’s not in the nav module. 

Will push shortly and leave the admin aspect as is for now - need to get in the habit of not using admin so much probably (in our case anyways).

Thanks!

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/users-module/commit/e8025aa1554d1bed0f5a6a1697e1bdab51b1e25c
