### ISSUE TITLE
[forms-module] After saving a new assignment, redirects to wrong page

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#4308]
Click Add Field

<img width="847" alt="screen shot 2017-04-10 at 12 31 37 pm" src="https://cloud.githubusercontent.com/assets/535135/24876644/a97d689e-1de9-11e7-963e-9364e977c218.png">

Fill out form

<img width="847" alt="screen shot 2017-04-10 at 12 32 01 pm" src="https://cloud.githubusercontent.com/assets/535135/24876662/c2c660bc-1de9-11e7-9af6-192f55a7753e.png">

Receive 404, I get redirected to /admin/forms/assignments without the ID of the form.

<img width="805" alt="screen shot 2017-04-10 at 12 32 34 pm" src="https://cloud.githubusercontent.com/assets/535135/24876667/c9ee28d4-1de9-11e7-8031-eec9ba73ddc6.png">

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/forms-module/commit/5c9920b17a33dcd6e24654ccdc4d8d8479915376
