### ISSUE TITLE
Issue with Config Repository class

### ISSUE THREAD

**Issue by agustindidiego** [pyrocms/pyrocms#4310]
On several **core** packages and on **streams-platform** class **Illuminate\Config\Repository** is being used instead of it Contract **Illuminate\Contracts\Config\Repository.** Because of this, binding the class is not possible.

All usages of **Illuminate\Config\Repository** should be replaced by its Contract **Illuminate\Contracts\Config\Repository**.

**Comment by RyanThompson** [comment]
I've done core and have the rest replaced - will push up tonight, thanks!
