### ISSUE TITLE
[streams-platform] Placeholder in the filter of table-builder not works properly

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4311]
I set filter with that way:
```php
        'sku'    => [
            'filter'      => 'search',
            'query'       => SkuFilterQuery::class,
            'placeholder' => 'Поиск по артикулу',
        ],
```
Placeholder not works for me
![image](https://cloud.githubusercontent.com/assets/5930429/24943633/29571b60-1f60-11e7-8cef-724c92b05086.png)
Filter displays standard placeholder.

**Comment by RyanThompson** [comment]
Fixed! https://github.com/anomalylabs/streams-platform/commit/853fd48e71e6838ba47cce171ef381425f3dfd4dc

Good find.

**Comment by RyanThompson** [comment]
Thanks!
