### ISSUE TITLE
[Files,Repeater,Grid] (Feature Request) Provide Option to Make Entries Trashable

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4315]
UI for grid / repeater would be new but files could use same UI as streams module.

**Comment by RyanThompson** [comment]
I was going to add a disabled / enabled toggle which could do the same thing? Along with the inclusion of editable titles and UI update. Does that sounds like it'd do?

**Comment by mattcdavis1** [comment]
yeah - think disabled / enabled would do the trick.  What are your thoughts on UI treatment for disabled in listing view?  Would be nice to have some special styling for disabled elements to easily see that they are disabled from the listing view.

**Comment by RyanThompson** [comment]
I was going to lighten the gray and mute the text

**Comment by mattcdavis1** [comment]
cool - sounds good.

**Comment by Pixney-William** [comment]
Did you do this @RyanThompson, otherwise lets add it to a milestone please!
