### ISSUE TITLE
[forms-module] Exported entries csv with json string breaks document in MS Excel

### ISSUE THREAD

**Issue by ThinkGraphical** [pyrocms/pyrocms#4316]
When there's  json string in the csv, it breaks the document in MS Excel,
seems ok in Numbers or even Google Drive.

This can be fixed by forcing the seperator to `,`
you can force this by setting this on the first line of the csv: `sep=,`

**Comment by stijntilleman** [comment]
Looks like this issue can be fixed by adding the line 
```php
fputcsv($output, ["sep=,"]);
```
to the following classes:
### \Anomaly\Streams\Platform\Http\Controller\EntryController
```php
# public function export($addon, $namespace, $stream)
$output = fopen('php://output', 'w');
fputcsv($output, ["sep=,"]);
```

### \Anomaly\Streams\Platform\Ui\Table\Component\Action\Handler\ExportAll
```php
# public function handle(TableBuilder $builder, ResponseFactory $response, array $selected)
$output = fopen('php://output', 'w');
fputcsv($output, ["sep=,"]);
```
### \Anomaly\Streams\Platform\Ui\Table\Component\Action\Handler\Export
```php
# public function handle(TableBuilder $builder, ResponseFactory $response, array $selected)
$output = fopen('php://output', 'w');
fputcsv($output, ["sep=,"]);
```

This isn't the best solution, maybe a better one would be to implemented the [laravel-excel](http://www.maatwebsite.nl/laravel-excel/) package

**Comment by stijntilleman** [comment]
Just something I threw together for ourself to quickly fix this issue after deploy was done
```sh
#!/usr/bin/env bash

if [ $# -eq 0 ]
  then
    echo "You didn't provide a project root" 1>&2
	exit 1
fi

PROJECT_ROOT=$1;

echo "Replacing in Export.php"
sed -i "/\$output = fopen('php:\/\/output', 'w');/a fputcsv(\$output, [\"sep=,\"]);" ${PROJECT_ROOT}/vendor/anomaly/streams-platform/src/Ui/Table/Component/Action/Handler/Export.php
echo "Replacing in ExportAll.php"
sed -i "/\$output = fopen('php:\/\/output', 'w');/a fputcsv(\$output, [\"sep=,\"]);" ${PROJECT_ROOT}/vendor/anomaly/streams-platform/src/Ui/Table/Component/Action/Handler/ExportAll.php
echo "Replacing in EntryController.php"
sed -i "/\$output = fopen('php:\/\/output', 'w');/a fputcsv(\$output, [\"sep=,\"]);" ${PROJECT_ROOT}/vendor/anomaly/streams-platform/src/Http/Controller/EntryController.php

exit 0
```

usage
```sh
# make sure the file is executable (chmod +x whateveryoucalledyourfile.sh)
which(bash) whateveryoucalledyourfile.sh .
```
> Because there is a difference in the usage of the `sed` command between Mac and other unix based operation systems, I can't guarantee this will work on a Mac

**Comment by Piterden** [comment]
@stijntilleman Don't forget that it should be added into `composer.json` after update script to works properly with updates.

Actually, would be better you to make PR with that changes.

**Comment by huglester** [comment]
maybe we should just use: https://github.com/thephpleague/csv ?
