### ISSUE TITLE
[pages-module] truncate doesn't delete stream entry

### ISSUE THREAD

**Issue by ddnetters** [pyrocms/pyrocms#4317]
`truncate()` on `Anomaly\PagesModule\Type\Contract\TypeRepositoryInterface`  doesn't delete the stream entries in `streams_streams` resulting in an integrity constraint violation.

**Comment by Piterden** [comment]
Could you test it, @ddnetters ?
https://github.com/anomalylabs/pages-module/pull/47

UPD: Fixed a little.

**Comment by RyanThompson** [comment]
You would need to loop through page type's and truncate their streams tables first OR use $page->delete() on them all which will cascade delete things automatically.
