### ISSUE TITLE
[Streams Core] (Feature Request) Revert Saved Tab Functionality

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4318]
Making the last stream tab for a given entry stick on reload is really annoying and unwanted functionality for me. As discussed elsewhere, tabs should be setup so that the primary content is on the first tab.  This is what users should see when they edit an entry - not the last tab they viewed.

Please roll back this functionality or at least make it opt-in.

**Comment by bloveless** [comment]
I have also noticed some strange functionality with the tabs. Sometimes it will load up with no content at all. Sometimes the name and slug field will become decoupled and I have to type in the slug manually. I'd be in favor of removing the tab cookie functionality as well.

**Comment by RyanThompson** [comment]
Removed - I hate it too.
