### ISSUE TITLE
[streams-platform] Add table title to field create and assignment

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#4321]
Whenever I'm creating a field it would be very helpful to know what type of field I'm creating (I.E. put a table header in there that shows what field type I'm creating)

When I'm assigning a field I'd like to know what I'm assigning a field to. If I walk away from my computer without finishing an assignment I should be able to come back to it and learn everything I need to know to continue. Right now the assignment forms are extremely bare.

For example. Creating a new field for pages. This should show me what field type I'm creating.

<img width="1372" alt="screen shot 2017-04-19 at 9 26 28 am" src="https://cloud.githubusercontent.com/assets/535135/25188160/5d032df0-24e2-11e7-92f3-36778f802460.png">

Example 2. Listing assignments for a page type should show the breadcrumb link for the page type, and a table title telling me which page type I'm editing.

<img width="1372" alt="screen shot 2017-04-19 at 9 27 44 am" src="https://cloud.githubusercontent.com/assets/535135/25188215/8de0ec00-24e2-11e7-884e-91f4bccf1b9f.png">

Last example. When I click assign field and select a field. The CMS should show me which field I selected and which type I'm assigning it to.

<img width="1373" alt="screen shot 2017-04-19 at 9 28 45 am" src="https://cloud.githubusercontent.com/assets/535135/25188244/a3ca6c62-24e2-11e7-8aa2-330a2c061c71.png">

I've only used pages as an example but I feel like table headers and breadcrumbs need to be used every where that fields and assignments are happening.

**Comment by Piterden** [comment]
![image](https://cloud.githubusercontent.com/assets/5930429/25188639/6b290d3a-252f-11e7-8d40-f1ff4780020c.png)

**Comment by Piterden** [comment]
![image4144](https://cloud.githubusercontent.com/assets/5930429/25189468/e87d19be-2531-11e7-8c23-903d0a9158bb.png)

**Comment by Piterden** [comment]
![image](https://cloud.githubusercontent.com/assets/5930429/25189930/60fdd5ee-2533-11e7-8d4d-9ac2830c3cbc.png)

**Comment by Piterden** [comment]
How are you about slugs showing?
![image](https://cloud.githubusercontent.com/assets/5930429/25190578/56abf7c2-2535-11e7-8c48-dbd4aefcb576.png)

**Comment by bloveless** [comment]
Absolutely against showing slugs. These need to be user friendly, not developer friendly. Also styles for table titles already exist. They just need to be added in these areas.

For example, streams-module already implements these table titles.

<img width="1372" alt="screen shot 2017-04-19 at 10 22 59 am" src="https://cloud.githubusercontent.com/assets/535135/25190678/39c2c4ec-24ea-11e7-82cd-cc60b49f180e.png">

**Comment by Piterden** [comment]
Got it.

And what about showing URI here:
![image](https://cloud.githubusercontent.com/assets/5930429/25190880/517f9c94-2536-11e7-89c8-7b7959de0aac.png)

**Comment by RyanThompson** [comment]
Nay - doesn't really offer anything that's missing. If that makes sense. 

The way I look at it is this (someone french and historically important said this):

> Perfection is Achieved Not When There Is Nothing More to Add, But When There Is Nothing Left to Take Away

**Comment by mattcdavis1** [comment]
agree with @bloveless about showing the title for fields / pages (and probably some other areas as well) i've noticed this issue too. 

Also, in some cases the breadcrumbs are missing a link in the chain.  For example, when you're on any stream detail page instead of `Streams > Module > Entries > Edit` it should be `Streams > Module > Entries > Some Stream > Edit`

**Comment by RyanThompson** [comment]
We had a discussion outside of this too - but I preemptively closed this based on initial discussion. Globally I am working on adding titles / contextual help for the user.

**Comment by bloveless** [comment]
Yes! Thank Ryan!

**Comment by Piterden** [comment]
Do not forget about this quote is from fairy tail.

The same guy sad:
> True happiness comes from the joy of deeds well done, the zest of creating things new.

Also this:
> Prison is not a mere physical horror. It is using a pickaxe to no purpose that makes a prison.

And this:
> When we work merely for material gain, we build our own prison.

Think about it a little.
