### ISSUE TITLE
[Streams Module] (Feature Request) Add Stream Level Permissions

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4323]
Standard permissions would be: 

* View Own Entries
* Create Entries
* Delete Entries
* View Other's Entries
* Edit Other's Entries
* Delete Other's Entries

Ideally, there would be an event corresponding to each of these permissions that modules could hook into for more complicated / customized permissions (Event should allow rejecting/allowing permissions).  

Also, if we move forward with entry statuses (published, unpublished) - permissions for these would make sense as well.

**Comment by mattcdavis1** [comment]
Well, i guess "View Own Entries" is implicit in create so that wouldn't be needed.  If you can't create / edit / delete (own or others) then you would just be denied access to the stream completely.

**Comment by RyanThompson** [comment]
This has been added to Streams Module v1.3
