### ISSUE TITLE
[help-module] Subsection not parse string template, or parse it incorrect

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4324]
![image](https://cloud.githubusercontent.com/assets/5930429/25261041/bf35fe4a-2658-11e7-86e8-8c02b2549fa1.png)
As you can see that href renders with not parsed value maybe it should be some check about it?

**Comment by Piterden** [comment]
Maximum what I can propose now is not much like PR
```php
        $streamId = $this->route->parameter('stream');

        if (starts_with($streamId, '{') || ends_with($streamId, '}'))
        {
            return redirect()->back();
        }
```

**Comment by bloveless** [comment]
The assignments should have hidden set in sections. It is likely chosen from a modal or something else.

**Comment by bloveless** [comment]
Check out assignments in the section array of pages and posts. They are set to hidden.

**Comment by Piterden** [comment]
Ya, my custom modules set to hidden, too.
But don't know why, I though about, what if we would show Ajax form for that case, when parameter not received?

**Comment by Piterden** [comment]
```js
if (href.match(/\{[\w\.]*\}/)) 
```
Something like this ^

**Comment by Piterden** [comment]
https://github.com/anomalylabs/help-module/pull/2

**Comment by RyanThompson** [comment]
Merged - thanks!
