### ISSUE TITLE
[streams core] deleting entries of a `belongsToMany` relationship doesn't delete entries in the junction table

### ISSUE THREAD

**Issue by ddnetters** [pyrocms/pyrocms#4328]
When deleting entries of a `belongsToMany` relationship it doesn't delete the entries in the junction table.

Steps to replicate
1. Create a repeater called `homepage_blocks`
2. Assign a repeater field type to the default page type which relates to `homepage_blocks`
3. Make a new homepage and add some  `homepage_blocks` entries
4. Call `$this->pages->findByPath('/')->getEntry()->homepageBlocks()->delete()` somewhere

The repeater entries are now removed from the `repeater_homepage_blocks` table but the relationships in the junction table `pages_homepage_pages_homepage_blocks` remain resulting in foreign key relationships pointing to non existing entries in `repeater_homepage_blocks`.

**Comment by Piterden** [comment]
What if you would try to delete those entries from CP?

**Comment by RyanThompson** [comment]
This is something that's fixed on the newer version (not released yet).
