### ISSUE TITLE
[wysiwyg-field_type] Saving with ctrl+s shortcut from fullscreen mode is erasing content of field

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4330]
Fullscreen mode creates new HTML element for editor and place it at the end of body tag.
When we are saving entry with `ctrl+s` shortcut, form is submitting, but value of fullscreen editor element, not synchronized with actual form element. So we have an empty WYSIWYG field after page have reloaded.

**Comment by RyanThompson** [comment]
Sounds like we need to capture saving / submitting the form and make sure the WYSIWYG  updates itself before continuing.

**Comment by Piterden** [comment]
Maybe it would be better to synchronize value with `[name="{field}"]` element each `keyup` event. It seems, it would be not so easy, to implement proposed by you, unfortunately.

**Comment by RyanThompson** [comment]
Agreed - wanna see if you can get er done? Their API documentation is great.

**Comment by Piterden** [comment]
https://github.com/anomalylabs/wysiwyg-field_type/pull/30

**Comment by ghost** [comment]
Is piterdens solution OK, and will it be merged? @RyanThompson

**Comment by ghost** [comment]
@Piterden did you solve this?

**Comment by RyanThompson** [comment]
Fixed - thanks for the PR! Also updated Redactor
