### ISSUE TITLE
[Streams Core] Don't Escape Field Attribute Values

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4331]
Field attributes are coming from a trusted source (the CMS) so i don't see the need for this.  The specific issue i'm having is that i want to add a link to the instructions field:

```html
<a href="/assets/pdf/adding-a-property-boundary.pdf">Click here for detailed instructions on how to create and upload a KML/KMZ file</a>
```

but the quotes are getting escaped causing the link to not work.

**Comment by RyanThompson** [comment]
Agreed - would you PR?

**Comment by mattcdavis1** [comment]
sure - probably be the weekend before i get to this.

**Comment by mattcdavis1** [comment]
@RyanThompson  - here you go: https://github.com/anomalylabs/streams-platform/pull/386
