### ISSUE TITLE
[Files Module] Use Non-Guessable Unique ID for forms

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4332]
For front end uploads, if i do a dropzone ajax file upload and then add the ID of the newly created file model to my form (which contains other fields in addition to the file upload field) that ID can easily be swapped out with another one before the form is submitted, allowing access to files that may be private since incremental ids are easily guessable.  

For example, a user is able to manage a photo gallery stream which has a title, file, and description.  The user uploads the image, and then edits the resulting file ID hidden input field with a different value that corresponds to my super secret file.  Then, when that user goes to the listing page which shows all their photos, they could click on the one that has my super secret file and access it.

Old pyro used a hash as an ID which was much harder to guess.  I would suggest adding a fairly long identifier in addition to the auto-increment ID that can be used in forms as a reference in place of the file ID.

**Comment by RyanThompson** [comment]
For frontend access I would like to store permissions per file as needed and per folder rather than use hash trickery if possible. 

But sounds like you're referring to control panel access eh? Being dropzone and all. That particular interaction should/can be hashed though like some other things in the system are to obscure identifiers. Make sense? Like hashing the config array cache key of the FT so that if can be pulled out in the controller like multiple / relationship FT does. Would that work and make sense?

**Comment by mattcdavis1** [comment]
I'm actually referring to a non-cpanel scenario (front end form).  This would be specific to the editing context only. Here's an example of an edit form:

```html
<input type="hidden" name="files_field[]" value="5567" />
```

Where `5567` represents the file ID of an existing file that the user has previously uploaded and is associated with them.

The user could then edit the hidden input, swapping out "5567" with "6678" (where 6678 represents some other file belonging to another user) and re-save the form.  Then, when the page reloads the other person's file will now be associated with them.

This can be handled via something like the code below (not tested - just rough pseudo code) but ideally there would be an extra layer of protection in the form of difficult to guess identifiers.

```php
public function onPosting()
{
    $uploadedFileIds = request('files_field');
    $allowedFiles = FileModel::whereIn('id', $uploadedFileIds)
        ->where('created_by_id', '=', Auth::user()->id)
        ->pluck('id')
        ->toArray();
   
    // ensure that we are only associating files with the user that the user has uploaded themselves
    $_POST['files_field'] = array_only($allowedFiles, request('files_field'));
}
```

**Comment by RyanThompson** [comment]
This is done in in Files 2.6 where they are handled better/more secure and will get updated in the FTs accordingly in their next versions.
