### ISSUE TITLE
[Streams Core] Add app to views as global rather than function

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4333]
It appears as though the app() functionality is available in most twig views as a function, however it is not available in macros.  It would helpful to move app() to a global object rather than a simple function so it would be accessible in twig macros as well.

```php
$environment->addGlobal('app', app());
```

**Comment by RyanThompson** [comment]
Do you think this is safe?

**Comment by RyanThompson** [comment]
On that note - Im not entirely sure where the app is being loaded that you're referring to. Idk how it's in there lol

**Comment by RyanThompson** [comment]
Blade allows it - and you should know the consequences of parsing user input if you're gonna so I say it's fine: https://github.com/anomalylabs/streams-platform/commit/9f1d3b0203483d037294965015b56dfc35f04c94
