### ISSUE TITLE
[Streams Core / Repeater / Grid] Use nested html inputs rather than concatenated strings for prefixes / repeaters

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4334]
I don't understand why adding a form prefix has the effect of prepending a string rather than creating a nested array in the html.  For example, when a form has a prefix of "myFormPrefix" i would expect the following:

`<input name="myFormPrefix[myfield]" />`

Likewise for a repeater / grid field i would expect:
`<input name="myFormPrefix[myRepeaterField][MyRepeaterSubField]"`

This makes it easy to retrieve all values for a form or repeater.  Also, i can easily access nested values via dot syntax.  The current approach is difficult to work and i can't see any advantages for this approach over the nested approach.

**Comment by RyanThompson** [comment]
The way it is now piggy-backs of the existing field naming system which is much more stable then coming up with something custom for this use case. 

Can you share with me what you're trying to do? You should be able to get the values you need super easily since they all work the same (it's just nested form builders).

**Comment by mattcdavis1** [comment]
Well a couple of things here.  HTML has a built in structure for handling nested content - why not use it? That's what it was created for.  I'm suggesting changing the whole pyro form system, not just the grid / repeater (although that's the biggest pain point atm). 

When you want to manipulate the request (i.e. merge, remove, modify items) it's much more difficult than it should be with the current setup.  As i mentioned above, the native laravel array dot syntax is a great way to access nested request data but with the way repeater / prefixed forms are now this is not a viable option.  As a side, there are a number of location where $_POST is accessed directly which i think need to be changed.

Getting back to repeater though.  It is really painful to work with because there is actually an array of hidden inputs and then this hidden input array is somehow mapped to the naming convention inputs.  It's overly and unnecessarily complicated. 

In my particular use case i'm building a front end form with a repeater.  To handle adding a new fieldset i'm generating an empty fieldset as hidden html and then cloning / adding it to the DOM on "new item" link click.  I've had a number of issues with indexing of the hidden inputs getting out of sync with the named fields on page reload with errors and not saving correctly.  I still haven't figured out fully what's going on but it's just been much more difficult than i think it should be to work with the repeater in particular (both from a debugging perspective and a processing / manipulation perspective).

**Comment by RyanThompson** [comment]
Because array posts (nested) are interpreted entirely different than regular field names. 

Adding a form prefix shouldn’t change the format of input entirely - it should only prefix post keys with the form key. Otherwise you basically have to maintain the standard way of getting the value (no prefix / nesting) and an array version for nested forms. 

The way it is now - field values are always harvested from post data the exact same way - period. Much more stable than checking if prefix - then check the nested array / etc. Just more complicated.

**Comment by mattcdavis1** [comment]
> Because array posts (nested) are interpreted entirely different than regular field names.

By Pyro?  Not sure what you mean by this. If you're saying that Pyro currently handles nested array input different that may be the case i'm just saying the best way moving forward is to change this functionality so that nested arrays are used for prefixed forms and repeating field types.  The approach to accessing data would always be the same:

`$fields = request($prefix)`
`$field = request($prefix . '.myfield')`

simple.

There doesn't need to be two ways of accessing the value - just one (above).  I don't understand how nested fields represent a "non-standard" way of accessing $_POST values (unless you're saying non-standard as of the way Pyro is now - in which case i acknowledge that and propose that we change the standard) or why there would need to be an alternate way of accessing the values (I do understand that as things stand now there would need to be an alternate way but i'm proposing making this change across the board so that all forms everywhere expect that a prefixed form will be prefixed via an array and that repeating fields will be treated the same way).
