### ISSUE TITLE
[page-module] Add toggle-able table view for pages for filtering.

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4336]
When building larger sites. It would be great to be able to have a search field on the "admin/pages" to be able to find the page you are looking for.

**Comment by RyanThompson** [comment]
I've thought about a search for tree UI but it doesn't lend itself to good UI/UX

I've decided a while ago I will add a table of pages view that can be toggled and will use filters n jazz. It'll have a UI toggle on the admin page and be preferences based for persistence.

**Comment by RyanThompson** [comment]
This is in 2.4 that's included in Pyro 3.5
