### ISSUE TITLE
Database locked - Often happens when uploading images including this one

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4337]
![bill-williams-1806](https://cloud.githubusercontent.com/assets/1510338/25562773/f14428f2-2d8e-11e7-86d4-ebf7659b510c.jpg)

**Comment by RyanThompson** [comment]
Is there any pattern you can distinguish with this issue or is it happening randomly?

**Comment by ghost** [comment]
So far , it feels like it doesn't happen when you upload single files. It only happen when uploading multiple ones.

**Comment by keevitaja** [comment]
This has actually been present since the beginning of v3. When you upload bunch of files, some of them do not get uploaded. I couldn't figure out why... seems to be random "sometimes"

**Comment by huglester** [comment]
this is probably due to 'indexing' of tntsearch.
it indexes into sqlite table and gets locked.

and when you upload many files, two files finish at the same time. you get a lock.
I think we should decrease 'concurent uploads' to 1, maybe it will help?

related (probably) #4401

**Comment by RyanThompson** [comment]
I think this merged PR should help - for different indexes down the road we can change it back as needed.
