### ISSUE TITLE
[File / Files Field Type] Provide easier way to save entry model fields with file model

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4339]
There's another github-issue related to being able to save file entry content in the same context as the file itself within the CMS.  Depending on how that it is implemented, it may or may not resolve this issue.  On the front end of the website i am using form builder for a large multi-step form.  In one area of the form i am wanting to save file entry content along with the file (https://goo.gl/0gcWsU).

Right now, the only way to do this with form builder is to generate multiple forms (one for each of the multiple files) and somehow merge the two together when looping through files (file 1 gets associated with form indexed to zero).  Then i have to be sure to process all the forms associated with each file in addition to the main form.

The ideal scenario would be something like this.

```html
<input type="hidden" name="[myformPrefix][mymultiplefilesfield][17437][id]" value="17437"/>
<input type="text" name="[myformPrefix][mymultiplefilesfield][17437][entry][title]" value="My Entry Title"/>
<input type="text" name="[myformPrefix][mymultiplefilesfield][17437][entry][category_id]" value="66"/>
```

When saving content the files field type would handle re-displaying post content for file entry data, validation, saving etc. in addition to saving the files themselves.

**Comment by RyanThompson** [comment]
I've made file management more congruent through the FTs but it's still not within the context like you're showing - I think that needs to remain a custom implementation on your end. Could also rely on repeater logic too.
