### ISSUE TITLE
confusing 'tmp' folder in project root with autoloaded code

### ISSUE THREAD

**Issue by mjrider** [pyrocms/pyrocms#4341]
Pyrocms ships default with an `tmp/` folder in the projectroot, and code in the folder is autoloaded by composer

The name of the folder suggest that it should not be there, and it being in an autoloader is even worse.

Possible fixes:
- Delete the code
  If it is already no longer needed, just throw it away

- Rename folder to 'legacy' or 'compat'
  This makes it clear that it should be refactored away

From the file in the tmp folder
`@deprecated Since 1.0; Remove immediately. @handle is assumed per Laravel 5.3`

**Comment by RyanThompson** [comment]
Ya this will be removed in the next version of release Pyro(3.4) which will use streams platform 1.3

I try and deprecate for two minor versions. This was a fix to bc issues Laravel had which I try to avoid at all costs.
