### ISSUE TITLE
Moving pages threw "database is locked - TNTIndexer.php" error

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4342]
**In:** /admin/pages

**Moving children from one parent to another / reorganisation threw the following**

[2017-05-07 11:19:14] local.ERROR: PDOException: SQLSTATE[HY000]: General error: 5 database is locked in /home/vagrant/Code/myprojectfolder.dev/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php:306
Stack trace:
#0 /home/vagrant/Code/myprojectfolder.dev/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php(306): PDOStatement->execute()
#1 /home/vagrant/Code/myprojectfolder.dev/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php(291): TeamTNT\TNTSearch\Indexer\TNTIndexer->delete(39)
#2 /home/vagrant/Code/myprojectfolder.dev/vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php(50): TeamTNT\TNTSearch\Indexer\TNTIndexer->update(39, Array)
#3 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Support/Collection.php(228): TeamTNT\Scout\Engines\TNTSearchEngine->TeamTNT\Scout\Engines\{closure}(Object(Anomaly\PagesModule\Page\PageModel), 0)
#4 /home/vagrant/Code/myprojectfolder.dev/vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php(54): Illuminate\Support\Collection->each(Object(Closure))
#5 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/scout/src/Searchable.php(56): TeamTNT\Scout\Engines\TNTSearchEngine->update(Object(Illuminate\Database\Eloquent\Collection))
#6 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/scout/src/Searchable.php(35): Anomaly\Streams\Platform\Entry\EntryModel->queueMakeSearchable(Object(Illuminate\Database\Eloquent\Collection))
#7 [internal function]: Illuminate\Database\Eloquent\Collection->Laravel\Scout\{closure}()
#8 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php(78): call_user_func_array(Object(Closure), Array)
#9 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/scout/src/Searchable.php(112): Illuminate\Support\Collection->__call('searchable', Array)
#10 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/scout/src/ModelObserver.php(61): Anomaly\Streams\Platform\Entry\EntryModel->searchable()
#11 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/scout/src/ModelObserver.php(72): Laravel\Scout\ModelObserver->created(Object(Anomaly\PagesModule\Page\PageModel))
#12 [internal function]: Laravel\Scout\ModelObserver->updated(Object(Anomaly\PagesModule\Page\PageModel))
#13 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(354): call_user_func_array(Array, Array)
#14 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(Anomaly\PagesModule\Page\PageModel))
#15 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#16 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1667): Illuminate\Events\Dispatcher->fire('eloquent.update...', Array)
#17 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1543): Illuminate\Database\Eloquent\Model->fireModelEvent('eloquent.update...', false)
#18 /home/vagrant/Code/myprojectfolder.dev/vendor/anomaly/streams-platform/src/Model/EloquentModel.php(575): Illuminate\Database\Eloquent\Model->performUpdate(Object(Anomaly\Streams\Platform\Entry\EntryQueryBuilder), Array)
#19 /home/vagrant/Code/myprojectfolder.dev/vendor/anomaly/streams-platform/src/Model/EloquentModel.php(528): Anomaly\Streams\Platform\Model\EloquentModel->saveModel(Array)
#20 /home/vagrant/Code/myprojectfolder.dev/vendor/anomaly/streams-platform/src/Model/EloquentTreeRepository.php(108): Anomaly\Streams\Platform\Model\EloquentModel->save()
#21 /home/vagrant/Code/myprojectfolder.dev/vendor/anomaly/streams-platform/src/Ui/Tree/Command/SaveTree.php(41): Anomaly\Streams\Platform\Model\EloquentTreeRepository->save(Object(Anomaly\PagesModule\Page\Tree\PageTreeBuilder))
#22 [internal function]: Anomaly\Streams\Platform\Ui\Tree\Command\SaveTree->handle()
#23 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#24 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#25 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Anomaly\Streams\Platform\Ui\Tree\Command\SaveTree))
#26 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Anomaly\Streams\Platform\Ui\Tree\Command\SaveTree))
#27 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#28 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(75): Illuminate\Bus\Dispatcher->dispatchNow(Object(Anomaly\Streams\Platform\Ui\Tree\Command\SaveTree))
#29 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesJobs.php(17): Illuminate\Bus\Dispatcher->dispatch(Object(Anomaly\Streams\Platform\Ui\Tree\Command\SaveTree))
#30 /home/vagrant/Code/myprojectfolder.dev/vendor/anomaly/streams-platform/src/Ui/Tree/Command/PostTree.php(39): Anomaly\Streams\Platform\Ui\Tree\Command\PostTree->dispatch(Object(Anomaly\Streams\Platform\Ui\Tree\Command\SaveTree))
#31 [internal function]: Anomaly\Streams\Platform\Ui\Tree\Command\PostTree->handle()
#32 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#33 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#34 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Anomaly\Streams\Platform\Ui\Tree\Command\PostTree))
#35 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Anomaly\Streams\Platform\Ui\Tree\Command\PostTree))
#36 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#37 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(75): Illuminate\Bus\Dispatcher->dispatchNow(Object(Anomaly\Streams\Platform\Ui\Tree\Command\PostTree))
#38 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesJobs.php(17): Illuminate\Bus\Dispatcher->dispatch(Object(Anomaly\Streams\Platform\Ui\Tree\Command\PostTree))
#39 /home/vagrant/Code/myprojectfolder.dev/vendor/anomaly/streams-platform/src/Ui/Tree/TreeBuilder.php(94): Anomaly\Streams\Platform\Ui\Tree\TreeBuilder->dispatch(Object(Anomaly\Streams\Platform\Ui\Tree\Command\PostTree))
#40 /home/vagrant/Code/myprojectfolder.dev/vendor/anomaly/streams-platform/src/Ui/Tree/TreeBuilder.php(107): Anomaly\Streams\Platform\Ui\Tree\TreeBuilder->build()
#41 /home/vagrant/Code/myprojectfolder.dev/vendor/anomaly/streams-platform/src/Ui/Tree/TreeBuilder.php(152): Anomaly\Streams\Platform\Ui\Tree\TreeBuilder->make()
#42 /home/vagrant/Code/myprojectfolder.dev/core/anomaly/pages-module/src/Http/Controller/Admin/PagesController.php(34): Anomaly\Streams\Platform\Ui\Tree\TreeBuilder->render()
#43 [internal function]: Anomaly\PagesModule\Http\Controller\Admin\PagesController->index(Object(Anomaly\PagesModule\Page\Tree\PageTreeBuilder))
#44 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#45 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('index', Array)
#46 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(189): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Anomaly\PagesModule\Http\Controller\Admin\PagesController), 'index')
#47 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController()
#48 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(653): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#49 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /home/vagrant/Code/myprojectfolder.dev/vendor/anomaly/streams-platform/src/Http/Middleware/ApplicationReady.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\Streams\Platform\Http\Middleware\ApplicationReady->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /home/vagrant/Code/myprojectfolder.dev/vendor/anomaly/streams-platform/src/Http/Middleware/SetLocale.php(88): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\Streams\Platform\Http\Middleware\SetLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /home/vagrant/Code/myprojectfolder.dev/vendor/anomaly/streams-platform/src/Http/Middleware/PoweredBy.php(38): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\Streams\Platform\Http\Middleware\PoweredBy->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /home/vagrant/Code/myprojectfolder.dev/core/anomaly/users-module/src/Http/Middleware/AuthorizeRoutePermission.php(107): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\AuthorizeRoutePermission->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /home/vagrant/Code/myprojectfolder.dev/core/anomaly/users-module/src/Http/Middleware/AuthorizeControlPanel.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\AuthorizeControlPanel->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /home/vagrant/Code/myprojectfolder.dev/core/anomaly/users-module/src/Http/Middleware/AuthorizeModuleAccess.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\AuthorizeModuleAccess->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 /home/vagrant/Code/myprojectfolder.dev/core/anomaly/users-module/src/Http/Middleware/AuthorizeRouteRoles.php(106): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#72 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\AuthorizeRouteRoles->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#74 /home/vagrant/Code/myprojectfolder.dev/core/anomaly/users-module/src/Http/Middleware/CheckSecurity.php(86): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#75 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\CheckSecurity->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#78 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#79 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#80 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#81 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#82 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#83 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(607): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#84 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(268): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#85 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#86 /home/vagrant/Code/myprojectfolder.dev/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#87 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#88 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#89 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#90 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#91 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#92 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#93 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#94 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#95 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#96 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#97 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#98 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#99 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#100 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#101 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#102 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(150): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#103 /home/vagrant/Code/myprojectfolder.dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#104 /home/vagrant/Code/myprojectfolder.dev/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#105 {main} {"identification":{"id":"4c527b1d-d9b9-4a09-8de8-0cf1f48a3d78"}}

**Comment by RyanThompson** [comment]
You on a trash host by chance? Seems like I see this with crap HDs but might be coincidence.

**Comment by mattcdavis1** [comment]
@RyanThompson - i'm seeing this also on my Macbook with SSD.  Try this to reproduce: create a large tree (say 75 entries) in pages module.  Drag an entry back and forth about 10-15 times in quick succession.  In the screenshots below you'll see it took about 6 changes to trigger this error.

https://goo.gl/mvV7N1
https://goo.gl/ya6TQ6

I was able to resolve this error by wrapping TNT indexing queries in try / catch.  I checked the TNT github issues and didn't see any issues related to this so not sure if this is Pyro specific or not.

Here's a modified version of the file that seems to deal with the issue:

https://gist.github.com/mattcdavis1/bb83aba2d3b0a89237744366d0245769

**Comment by mattcdavis1** [comment]
On a related note - do we really want to trigger a save on every entry in the tree every time a tree item position changes?  This seems inefficient and unnecessary.  We should just need to change the parent ID of the item that changed position.

**Comment by RyanThompson** [comment]
I think a mass update could be much better yes.

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/pull/429
