### ISSUE TITLE
[grid/repeater-field_type] a few issues when nesting repeaters inside of a grid.

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#4344]
When creating a repeater nested within a grid and the repeater contains an image FT or a file FT (there might be others, but I'm not sure) the page stops rendering as soon as it gets to the repeater-list. There don't seem to be any errors logged. It just stops rendering.

<img width="1404" alt="screen shot 2017-05-09 at 3 04 05 pm" src="https://cloud.githubusercontent.com/assets/535135/25966157/6de22010-3647-11e7-991c-e1487e9caa99.png">

After removing the Image/File FT I was able to get the repeater working inside of the grid, but whenever I saved with a new row then two rows were created for each entry.

<img width="969" alt="screen shot 2017-05-09 at 3 18 25 pm" src="https://cloud.githubusercontent.com/assets/535135/25966190/8d3730c2-3647-11e7-8f0d-0b897dca0092.png">

Not sure if this is by design, but when I delete a repeater row (inside the grid) then only the pivot table has a row that is deleted. Both of the rows stay in the repeater table.

**Comment by bloveless** [comment]
I was able to trace it down to the FieldPopulator. It tries to set the slide_image relationship and shits its pants.

![screen shot 2017-05-11 at 3 47 38 pm](https://cloud.githubusercontent.com/assets/535135/25973499/99275c62-3661-11e7-8bed-e074c73c06e6.png)

It's trying to set $field['value'] = $entry->{$field['field']} ($field['value'] = $entry->slide_image)

And thats as far as I've made it.

**Comment by RyanThompson** [comment]
I can't replicate this (gonna text you)

**Comment by RyanThompson** [comment]
Mem issue on GD!

**Comment by bloveless** [comment]
LOL years into this and still a n00b feeling here and there.
