### ISSUE TITLE
[grid-field_type] Adding a row with an editor throws a JS error.

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#4345]
Adding a row with an editor throws a JS error if there is already an editor on the page.

![screen shot 2017-05-11 at 12 45 49 pm](https://cloud.githubusercontent.com/assets/535135/25966306/e0ec085a-3647-11e7-95eb-ec2a8dbf1ad9.png)

<img width="721" alt="screen shot 2017-05-11 at 12 46 46 pm" src="https://cloud.githubusercontent.com/assets/535135/25966328/ee6be1f8-3647-11e7-95c0-4082a407a470.png">

This happens because the script for ace is loaded into the page again and causes an issue. I have a fix for this, but it isn't elegant. https://github.com/anomalylabs/grid-field_type/pull/10

**Comment by RyanThompson** [comment]
Thanks for the PR!

**Comment by bloveless** [comment]
NP!
