### ISSUE TITLE
[Streams Core] (Feature Request) Add Versioning Functionality

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4346]
Example from Craft CMS: https://goo.gl/RvAYkb

This is a fairly standard feature across most modern / popular CMS's

**Comment by RyanThompson** [comment]
Ya this is in my roadmap using https://github.com/VentureCraft/revisionable

**Comment by mattcdavis1** [comment]
Yeah - i'm using revisionable to store history for the current Pyro project i'm working on but i wonder if that's the best option for providing restore to previous revision functionality.  Seems like a single record with data stored as json might work better for this. Especially when considering relationships (you'd have to find a way to connect a parent model's revisionable id with the relationship model's revisionable id for a given revision).  

If it get's the job done though - just whatever works.  I think issue #4300 is really going to need to be resolved to handle revisions for models and relationships effectively.

**Comment by girvydas** [comment]
What about this package integration: https://github.com/spatie/laravel-activitylog ?

**Comment by RyanThompson** [comment]
This is in PyroCMS v3.5
