### ISSUE TITLE
Twig_Error_Runtime 500 error

### ISSUE THREAD

**Issue by hcweb** [pyrocms/pyrocms#4347]
Visit / admin / dashboard / view / welcome 500 error when asked how to handle Thank you

![qq 20170512103023](https://cloud.githubusercontent.com/assets/12317944/25979935/0edf7902-36fe-11e7-9af6-457a4ccfbb02.png)

**Comment by RyanThompson** [comment]
This is a system issue. I unfortunately have never owned a PC (I think this is unique to Windows) so I can't help ya much on it but I've seen it around. Search old issues / Google and the answer should reveal itself ^_^

http://stackoverflow.com/questions/13830285/writing-to-php-stderr
