### ISSUE TITLE
[files-module] Importing images after being uploaded with ftp

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4348]
We need some improvements to the files. I am thinking about the following scenarios:

- User uploads files through ftp and want them in the system.
- User moves the files using ftp
- User want to move files from one folder to the other, pyrocms gui does currently not allow that (i think?).

/w

**Comment by huglester** [comment]
1. this can be done via some command.
like scanning directory and adding them to Files module.

2. moving files - this is not possible right. 
syncing then those files would be pain in the ....

so I think 1st can be done locally using command. 
something like (not tested):
```php
$files = ['file1.jpg', 'file2.jpg'];
foreach ($files as $file) {
    Storage::disk('local')->put('images/'.basename($file), file_get_contents($file)));
}
```

I think none of these will be implemented for now.
What do you think @RyanThompson  ?

**Comment by Piterden** [comment]
Maybe you look for this? @huglester 
```php
$uploaded = new UploadedFile(
    $nameSource,
    $nameDestination,
    $mime,
    filesize($nameSource),
    null,
    true
);
```

**Comment by RyanThompson** [comment]
We'll use `files:sync` I think here.

**Comment by RyanThompson** [comment]
This has been fixed via the `files:sync` command.
