### ISSUE TITLE
[Translator Module] html tags error

### ISSUE THREAD

**Issue by kiger** [pyrocms/pyrocms#4350]
In the translation module if I use html tags every " becomes &quot; and because of that the strings are broken.

For example a href tag becomes like this:
![image](https://cloud.githubusercontent.com/assets/2277562/26002988/b7328846-3731-11e7-9ab9-9b3ee1ed78be.png)

**Comment by RyanThompson** [comment]
Fixed! https://github.com/anomalylabs/translator-module/commit/7547244d57789bb333270e54cd27ef1062b81b10
