### ISSUE TITLE
[Translator Module] Related Streams Name  

### ISSUE THREAD

**Issue by kiger** [pyrocms/pyrocms#4351]
If I browse the Related Streams the stream name is not the translated name

For example:
![image](https://cloud.githubusercontent.com/assets/2277562/26003293/93ca1a26-3732-11e7-8112-b6008b2f28c5.png)

**Comment by RyanThompson** [comment]
Fixing now!

**Comment by RyanThompson** [comment]
Got all the core ones - will keep an eye on others.
