### ISSUE TITLE
[grid/repeater-field_type] Nested repeater is saving duplicate rows.

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#4353]
For example I have a hero slider (grid) that contains a single repeater ft (slides).

In the image below I've created a single slide in the repeater.

![screen shot 2017-05-12 at 2 26 20 pm](https://cloud.githubusercontent.com/assets/535135/26015624/feb9c566-371e-11e7-98ea-3e5d8ade01bf.png)

And I get two rows in the DB.

<img width="1079" alt="screen shot 2017-05-12 at 2 27 06 pm" src="https://cloud.githubusercontent.com/assets/535135/26015669/1b61a15c-371f-11e7-9a60-27fb7d067152.png">

And the repeater relationship only relates to the second row (id/related_id: 2)

<img width="1078" alt="screen shot 2017-05-12 at 2 27 39 pm" src="https://cloud.githubusercontent.com/assets/535135/26015696/3dc6f634-371f-11e7-9e32-a96a84602b12.png">

Editing the repeater row works correctly, only editing the second row.

<img width="1079" alt="screen shot 2017-05-12 at 2 29 32 pm" src="https://cloud.githubusercontent.com/assets/535135/26015748/71d20388-371f-11e7-8269-8abdd4390123.png">

**Comment by RyanThompson** [comment]
If you add another row do you get another empty?

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/repeater-field_type/commit/23cbae4c9e5ca8dc4a7658c7c0e533ca3e636cb9

Same fix was applied to grid as well.
