### ISSUE TITLE
Files Module: Length of slug affecting display of file

### ISSUE THREAD

**Issue by callum-baillie** [pyrocms/pyrocms#4354]
When I have a field with the slug

`"centre_feature_what_to_expect_homepage"` 

and then try outputting the image 

`{{ page.centre_feature_what_to_expect_homepage.url }}`

it will not display, however with identical settings, if I choose the slug "image" it works fine.

**Comment by Piterden** [comment]
Check SQL logs, it could be key length limitation.

**Comment by RyanThompson** [comment]
I would highly suggest picking a better field slug. We might need more validation in there to limit it? But yes I would expect it's a key length restriction but check slug in fields_fields table and column name.

**Comment by RyanThompson** [comment]
Going to close this for now and examine a better way to protect against this.
