### ISSUE TITLE
sources() and picture() to generate html5 picture element

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#4355]
There seems to be some tomfoolery going on with different queries.

`block.background.image` is 4905 x 3270 for reference.

Lets take the below example.

```
          {{ block.background.image
            .sources({
                "(max-width: 600px)": {
                    "resize": 600,
                    "quality": 60
                },
                "(max-width: 1600px)": {
                    "resize": 1800,
                    "quality": 90
                },
                "fallback": {
                }
            })
            .picture()|raw }}
```

Before when I was getting a bunch of weird sizes, nothing was resizing correctly Now with more playing around it seems to be doing the resizes ALMOST correctly, everything is half of what I want it to be, even the fall back.

The source code if you follow the links reports the right image sizes
600x400
1800x1200
4905x3270

highlighting the source in chrome reports the following image sizes
600x400
1800x1200
2452x1635

Browser is rendering 
300x200
900x600
2452x1635

**Comment by RyanThompson** [comment]
That's weird.. Is this like a thing with double density?

**Comment by edster** [comment]
I think so

Sent from my Windows 10 phone

**Comment by RyanThompson** [comment]
Can you paste your generated code here please? The HTML output.

**Comment by RyanThompson** [comment]
Is this still a thing?

**Comment by edster** [comment]
I haven't tested it in awhile as I couldn't fix it. It was on my surface so is almost definitly a density issue. I'll try to test it this week.

**Comment by RyanThompson** [comment]
This is done - srcset too
