### ISSUE TITLE
[Streams Module] (Feature Request) Add GUI for setting any field as hidden

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4356]
This (hidden) flag already exists in the FieldType class, there's just no way to set this via the streams GUI.  Main use case is if i want to handle setting the value programatically.

**Comment by RyanThompson** [comment]
Good call! I'll get er done.

**Comment by RyanThompson** [comment]
I was thinking - if you're setting the value programmatically - would you not make the field hidden programmatically as well?

**Comment by mattcdavis1** [comment]
In my scenario i'm setting the value programmatically on the front end form (which i have a dedicated form builder for) but in the streams module / admin area i'm not doing anything with the value.  So i have a form builder on the front end which could handle setting the field to hidden (although in that context it's not even needed because i can just omit the field from the form html) but in the admin area / streams module that would be extra work that i would prefer not to have to do.  

Since streams module doesn't have per-form builders i'd have to bind to the base form builder and run logic based on the current stream to see if this is the stream i want to modify.  Unless there's a simpler way that i'm missing?

**Comment by Pixney-William** [comment]
Did you get this done @RyanThompson

**Comment by RyanThompson** [comment]
Ya .. not sure what I was thinking here but by the time you need hidden fields in streams module you are programming and can bind something or configure the form builder as doc'd with array definitions. Closing this.
