### ISSUE TITLE
[Streams Module](Relevance of Namespace being displayed)

### ISSUE THREAD

**Issue by ikoniqoz** [pyrocms/pyrocms#4357]
When a user/client selects a Stream to add/edit items, they are presented with the Namespace of the Stream.  I feel that for our clients, this has little - if any - relevance. What would have more value would be to have the name of the Stream.
Perhaps the Change Namespace button also comes into this as well as I see no point in this for clients.

**Comment by RyanThompson** [comment]
What are you referring to here? Streams module? Maybe attach a screenshot of what you're referring to so I can make sure I am on the same page ^_^

**Comment by ikoniqoz** [comment]
Sorry I was not clear enough...  I was referring to the Streams Module add-on.
Below is a screenshot of a Stream that has been selected for editing entries - it happens to be photo gallery. Note the reference to the Namespace (ikoniq) - and the Namespace description -  which the Stream belongs to. I feel that instead of displaying the Namespace and Namespace description, it would be preferable to display the name (and possibly a description) of the Stream whose entries appear below the title box.
Refer: addons/shared/anomaly/streams-module/resources/views/admin/groups/heading.twig line 8
Hope this helps.

![screen shot 2017-05-17 at 5 22 12 pm](https://cloud.githubusercontent.com/assets/3609155/26143013/6dbd15b6-3b26-11e7-82f1-768e88f514e1.png)

**Comment by mattcdavis1** [comment]
+1 for this.  Could have sworn i created an identical issue but can't find it.  I think that "Change Namespace" button does not belong in this context.

**Comment by RyanThompson** [comment]
I think you’re right Matt - and honestly I am probably going to leave that in there in lieu for adding the namespace to the sidebar where it’ll be cleaned up and appear like a normal module would. This will be the more utilitarian section for savvy users / devs. 

Make sense?

**Comment by mattcdavis1** [comment]
cool sounds good.   I do think that button makes sense on the top level streams listing page (listing of streams as opposed to stream entries).  It's just on listing / detail pages of a specific stream that i don't think it make sense.  

I'm not sure how "Change Namespace" would work in the sidebar. I think the top area (as it is now) is fine.  IMO it just needs to be removed from all pages except `admin/streams`.

**Comment by ikoniqoz** [comment]
Thanks @mattcdavis1 for supporting my point. -  re the Change Namespace button. +1 from me on that as well.

**Comment by mattcdavis1** [comment]
Along these same lines - i don't think the "New Entry" button should be showing up when you're editing an entry.  That makes sense in the list view (of stream entries) but not when you're editing a stream entry.  I think a better use of the (button area) space when editing an entry would be to show the title of the entry you are editing.

**Comment by RyanThompson** [comment]
Bout done with this features rough-out prototype now and works well! I'll be bumping the streams module cause it's gonna require streams-platform 1.3 which is in Pyro 3.4 lol

Cause of schema changes but it's pretty sick and will be worth it. 

Also changing binding overrides to a format like `anomaly.module.streams::{group}.{stream}.{object}` where object could be admin_controller, table_builder, etc.

**Comment by RyanThompson** [comment]
No reason to wait for sidebar stuff - though it's right around the corner with the release of 3.4 being baaaaasically done..

https://github.com/anomalylabs/streams-module/commit/f5f68e2b3a61e026500f270c337b95c8f2ad9d76
