### ISSUE TITLE
[Image Field Type]

### ISSUE THREAD

**Issue by ikoniqoz** [pyrocms/pyrocms#4358]
If a user changes the width of the browser window while they are editing an entry for an image, then the crop selection area changes and could cause unexpected results for the user/client.

**Comment by RyanThompson** [comment]
This is a limitation to the field type's plugin. I've disabled the responsiveness as it does mess with the crop area. This will have to do for now :-(

As far as resizing the screen the cropper is still usable now and retains integrity. Just if you cut your screen size in half you might see it start spilling off the input group.
