### ISSUE TITLE
[files-module](feature request) Nesting folders

### ISSUE THREAD

**Issue by ddnetters** [pyrocms/pyrocms#4361]
The ability to nest folders for neater organisation of files.

Use case:
```
Images
    Posts
        Marathon 2017 - team photos
    Vacancies
    Pages
```

**Comment by RyanThompson** [comment]
Newp. Makes a mess! Have tried it before and most systems that do this maintain a flat structure which I don't care for. Also makes maintaining remote / adapter type directories a mess. What works for one MUST work for the others.
