### ISSUE TITLE
[wysiwyg-field_type] Impossible workflow in some cases with images.

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4366]
Let's imagine I have a long content text inside wysiwyg editor.

When I need to insert an image into this text, if image are placing at the bottom part, I always need to scroll down, put cursor to the place I want to insert image, then scroll up and up to the top, for pressing that button on editor bar.

Also, why CTRL+X not works with pasted images? If I insert some of em in wrong place, I even couldn't move it somewhere else.

**Comment by Piterden** [comment]
Another weird thing is impossibility of change the source of image after pasting.

**Comment by RyanThompson** [comment]
Just insert or copy in a different image URL from files?

**Comment by RyanThompson** [comment]
Also can you send a quick video of what you’re seeing? The image is not placing where you put the cursor?

**Comment by Piterden** [comment]
No, image placing in the right place.
I just need to insert 7 images at the bottom of content, and I must scroll so much to achieve this.

**Comment by Piterden** [comment]
Why editor bar couldn't stay always visible at the top of window?

**Comment by RyanThompson** [comment]
I think scrolling down to insert more long content is an acceptable demand lol

**Comment by RyanThompson** [comment]
Like sticky? Cause there’s often more than one with things like repeater / grid floating about.
