### ISSUE TITLE
[editor-field_type] FONT SIZE, THEME in config

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4367]
Do you really think, changing size of font by user is not necessary?

I just don't see anything inside editor FT area.

The same about theme. I can't use that dark theme.

**Comment by RyanThompson** [comment]
I think the font size is unnecessary correct. If it needs to be bigger let’s investigate that. 

The theme could be configurable in the addon config maybe. Tie it to env perhaps? Can’t remember how the old one handled changing themes (2.1). Working on something else or I’d check :-P

**Comment by Piterden** [comment]
In 2.2 there is everything OK with size of font.

But Twig syntax highlight should extend HTML (XML) highlight scheme. Either, it is even less useful than it was in 2.1.

**Comment by RyanThompson** [comment]
Can you PR that? Or tell me what to do there.

**Comment by Piterden** [comment]
Don't worry, I'm going to make it today some later.

**Comment by RyanThompson** [comment]
Thanks Denis

**Comment by RyanThompson** [comment]
Can you see about making ESC unselect multi cursor too? I can’t seem to figure that one out. LOVE multi cursor but not escaping out of it sucks lol

**Comment by huglester** [comment]
Denis, did you forgot about this?:)

**Comment by Piterden** [comment]
Ya. And no.
Because you could override anything inside the `resources` folder of your app.
