### ISSUE TITLE
[editor-field_type] [feature-request] Emmet editing.

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4368]
Now I don't see much differences between editor-FT and simple textarea (if we would talk about code-writing flow).

Emmet is must-have for any editor in any environment, and editor-FT is not the exception.

**Comment by RyanThompson** [comment]
I didn’t know what it was so I removed it. What is it?

**Comment by Piterden** [comment]
https://emmet.io/

**Comment by Piterden** [comment]
Allows you to save about half time during code writing routines.

**Comment by RyanThompson** [comment]
Done deal - was already in there it looks like but rearranged a bit knowing what it was.

Could you look over the existing modes and make sure they’re as feature packed as they could be? You know far more about this than I do I think. 

For example the twig mode kinda sucks. {{ doesn’t auto space inside }} / autocompletion for HTML is nowhere to be found.

Just keep your PRs specific and small please ^_^ I’ll be happy to improve but maybe ask me first if you’re unsure about features? I don’t want you to waste time on something I don’t jive with ya dig? :-P

Ryan

**Comment by RyanThompson** [comment]
Ooooh Emmet is pretty bad ass.

**Comment by RyanThompson** [comment]
Done

**Comment by Piterden** [comment]
Okay, I will look at it and will try to divide changes as much as it possible.
