### ISSUE TITLE
[repeater-field_type] AND [grid-field_type] together with file-field_type

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#4369]
Hello,

so long repeaters and grids are working good. 
But I met some problems when using it with file-field_type or image_field-type.

When entering the Form in backend, it just stops rendering and I have screen similar to:  http://pic.webas.lt/webas.lt-b8edfdcbb7.png

if I remove from this file:
core/anomaly/file-field_type/resources/views/input.twig 
these lines:
<div class="selected">
    {{ field_type.value_table|raw }}
</div>

the form starts to render. also if I remove 'file' or 'image' field types from grid, it starts working also.

I could not find a problem, somewhere too deep.

Thanks

**Comment by RyanThompson** [comment]
Keep reloading - and what is your PHP memory allotment? Chances are you are running into a memory exhaustion issue with rendering the thumbnails.

**Comment by Piterden** [comment]
For correct saving this repeater I was need to increase MySQL memory in config. From 64 to 128 M of buffer.
![image](https://cloud.githubusercontent.com/assets/5930429/26389783/48dd0916-4064-11e7-89da-d6282ce9a508.png)

**Comment by huglester** [comment]
@RyanThompson well refresh does not work :(

@Piterden about what specific options do you speak?
Can you share your my.cnf?

I've added with no luck:
[mysqld]
table_open_cache=1024
sort_buffer_size=2M
read_buffer_size=2M
read_rnd_buffer_size=2M
myisam_sort_buffer_size=64M
thread_cache_size=128
query_cache_limit=1M
query_cache_size=64M
query_cache_type=1

innodb_buffer_pool_size = 256M
innodb_log_file_size = 64M
innodb_log_buffer_size = 8M

**Comment by Piterden** [comment]
I had reinstalled mysql 2 times after that))
Now it works fine.

```conf
[mysqld]
user            = mysql
pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
port            = 3306
basedir         = /usr
datadir         = /var/lib/mysql
tmpdir          = /tmp
lc-messages-dir = /usr/share/mysql
key_buffer_size         = 16M
max_allowed_packet      = 16M
thread_stack            = 192K
thread_cache_size       = 8
myisam-recover-options  = BACKUP
query_cache_limit       = 1M
query_cache_size        = 16M
skip-external-locking
```

**Comment by RyanThompson** [comment]
Is this resolved then? Server configuration? Close if so please.

**Comment by huglester** [comment]
Not yet. Still trying to figure out

**Comment by Piterden** [comment]
Maybe, you would try Percona? It had resque me not so much time ago.

**Comment by huglester** [comment]
Well, unfortunately it won't help...
I've added these: 
key_buffer_size         = 16M
thread_stack            = 192K

I've even increased other params. no luck. I don't think it's to be dealt with mysql...

There is a loop: https://pastebin.com/bHKNiFAX

Something is not 'there'. And this is strange. I meet this error for the 2nd time.
I tried to dig more information and run php artisan serve - but baiscly the erorr is the same. some loop happens...

question is WHERE

**Comment by huglester** [comment]
PHP limits  - 1gb of memory, so this is not the issue for sure... 
MySQL 5.7

I don't believe it can be mysql issue. Not everybody has percona etc... the the issue is somewhere.
I must say, that I even copier dthe 'assets' folder from the server, where this is 'working', so baiscly there is no need to resize anything? but the problem stays the same

**Comment by RyanThompson** [comment]
What are the sizes in megabytes of all the files involved? This screams GD issue to me.

**Comment by huglester** [comment]
well what I tried - the problem isn't even in GD... (I earlier tried switching to imagick).
But the problem itself is whenver my 'repeater', 'grid' has FILE filed type - it stops working...
I mean, I can:
- create a repeater
- ad text and file field types
- create one repeater with NO file at all - only title
- it stops rendering

- I go to repeater later,
- remove FILE field type
- it starts rendering....

I was trying to go via all this table builders, value tables and so on.. no luck so far :D

**Comment by huglester** [comment]
I may upload reproducible code + sql db..
so you could check. Think it would be best and easiest to see! :)

**Comment by huglester** [comment]
Actual fix is here, in the comments:
https://github.com/pyrocms/pyrocms/issues/4456
