### ISSUE TITLE
[Repeater field] custom repeater relationship ignores related model on update

### ISSUE THREAD

**Issue by stijntilleman** [pyrocms/pyrocms#4370]
If you define a repeater field via a migration (as shown below), and you use the field assignment update form in the backend to change field options (instructions, ...) the relationship is overwritten by the first repeater field you've defined via the backend.

## the migration
```php
     "sessions" => [
            "type" => "anomaly.field_type.repeater",
            "locked" => false,
            "config" => [
                "related" => \Acme\Module\Session\SessionModel::class,
            ]
        ],
```
## before update
```
"a:4:{s:7:"related";s:32:"Acme\Module\Session\SessionModel";}"
```

## after update

```'a:4:{s:7:"related";s:62:"Anomaly\Streams\Platform\Model\Repeater\RepeaterTeamEntryModel";s:7:"add_row";N;s:3:"min";N;s:3:"max";N;}```

**Comment by Piterden** [comment]
Have you tried to set `with` or `cascade` on parent model?
