### ISSUE TITLE
StreamModel config data corrupted by Builder and EntryStreamParser

### ISSUE THREAD

**Issue by RichardMBS** [pyrocms/pyrocms#4373]
I have extended `StreamStreamBuilder` functionality to store additional data to `StreamModel::$config`. From the CMS the config data loads/saves as expected in the CMS.

When I attempt to access the data from an instance of `StreamModel` which was made via `StreamModel::make()` the serialized config data is re-serialized resulting in a serialized object being serialized as a string making the data unreadable.

Additionally, when the `GenerateEntryModel` Command is dispatched the serialized data has unnecessary slashed added to it making it impossible to unserialize.

**Comment by RichardMBS** [comment]
I have fixed this issue and made a [pull request](https://github.com/anomalylabs/streams-platform/pull/403).

**Comment by RyanThompson** [comment]
Fantastic - thank you!
