### ISSUE TITLE
Grid / Repeater / Image Field Type bug

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4376]
@RyanThompson  

I have a grid with a field repeater.

The repeater has an image field type and text.

- You add image and text.

If you double click on the repeater row to minimize it and save. The image lose data. And it looks as the first image attached. As you can see it is much smaller.
![screen shot 2017-05-25 at 18 10 19](https://cloud.githubusercontent.com/assets/1510338/26459050/7ac9713c-4175-11e7-9269-35c64dfabb3b.png)

If you instead double click on the grid row to minimize it and save. The image lose its data again but the thumbnail this time is only a couple of pixels. See second image.

![screen shot 2017-05-25 at 18 09 45](https://cloud.githubusercontent.com/assets/1510338/26459047/795218e0-4175-11e7-955a-0de35950d5b0.png)

**Comment by huglester** [comment]
is this still an issue?
