### ISSUE TITLE
[3.3.3][users-module][email-field_type] Admin - reloading form while type @ - AZERTY keyboard

### ISSUE THREAD

**Issue by FlickTheManual** [pyrocms/pyrocms#4380]
Hi everybody,

Glad to use pyroCMS,
Anyway I've a problematic issue:

While i want to input a mail, I want to insert ```@``` inside, and it reloading the form.

if anybody have the same issue, and who to fix it?

Thanks for regards

**Comment by Piterden** [comment]
Where did you meet that behaviour? Please, tell more detailed about your environment, such like OS, browser, etc...

**Comment by FlickTheManual** [comment]
While you're on the "email" input,
in AZERTY keyboard, when you type @ (alltGr+0)
it reload the user form in admin control panel,

environment:

- OS: WIN 10, WIN 7
- browser: chrome, firefox (not tested on  edge or ie)
- System,: i7 7th gen, 16 Go, lot of dd...

Best regards


2017-06-02 15:10 GMT+04:00 Denis Efremov <notifications@github.com>:

**Comment by Piterden** [comment]
Hope you mean in Control Panel.

If so, then it seems JavaScript has wrong triggering of some hotkey. Could you check why your page is reloading? Is it a reload by submitting a form, or something else?

**Comment by FlickTheManual** [comment]
Thanks,

It seems to reload the form, without submit or else, simple hard reload
no error in network panel dev mode,
then i've tested it in another page (youtube,google "lalalal" search), and
there is no reload

2017-06-02 16:14 GMT+04:00 Denis Efremov <notifications@github.com>:

**Comment by Piterden** [comment]
Could we talk in Slack?

**Comment by FlickTheManual** [comment]
ok, I'm on the pyrocms slack

2017-06-02 16:28 GMT+04:00 Denis Efremov <notifications@github.com>:

**Comment by FlickTheManual** [comment]
fix in accelerant theme, thanks to piterden.

Good luck to the team!!!
