### ISSUE TITLE
[Streams Core] (Bug) Fix Issue where modules are partially visible even when no permissions are selected

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4381]
Examples of this are the grid module and variables module.

**Comment by mattcdavis1** [comment]
I think part of the issue is that in `Anomaly\UsersModule\Http\Middleware\AuthorizeModuleAccess` the active module is not yet set so `$module = $this->modules->active();` is always null.  Either the active module needs to get set earlier or the check needs to happen later.  

For now, i just added an ApplicationLoaded listener with the following code:

```php
if (is_admin()) {
    $user = Auth::user();

    if (!$user->isAdmin()) {
        $modules = app(ModuleCollection::class);
        $activeModuleId = $modules->active()->getId();
        $permissions = $user->getPermissions();
        $hasPermission = false;

        foreach ($permissions as $permission) {
            $permissionModuleId = explode('::', $permission)[0] ?? null;

            if ($permissionModuleId == $activeModuleId) {
                $hasPermission = true;
            }
        }

        if (!$hasPermission) {
            app()->abort(403);
        }
    }
}
```

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/4aba86464e4e7b0635c2549608f37ce8727c0e3c

**Comment by RyanThompson** [comment]
Good find!
