### ISSUE TITLE
[pages-module] Accidentally moving of page when you want to open it.

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4383]
When I want to open one of parents, I have excessed moving of all this group.
Maybe we should make a division of element which is responsible for moving from element which is responsible for opening?

**Comment by Piterden** [comment]
I had done separation of functionality between elements:

![plus](https://cloud.githubusercontent.com/assets/5930429/26758024/5a1e2970-48da-11e7-9393-b2daf7f10ac4.gif)

With that way not happens any things, which I don't want to happens...

There are 2 PR's to streams-platform and accelerant-theme.
You could check here https://github.com/Piterden/streams-platform/tree/separated-tree-toggles and here https://github.com/Piterden/accelerant-theme/tree/expandable-menu.

PS Hoverable menu I just forget to disable, xcuse me ))

**Comment by RyanThompson** [comment]
I've not had any issues with this nor heard any reports from clients / my team. I am going to leave it clean / minimal as it is now. I don't think it's as important enough of a feature to take up UI/UX room. Perhaps on screen guides when users first see a list might help or something. Or a keyboard/shortcuts/tips toggle for control panel areas..
