### ISSUE TITLE
[users-module] Support automatically assigning a username based on email or other strategy.

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4384]
What is the point of the username field?  You login with your email - having a required username field is pointless IMO and adds confusion (people attempting to login with username and it doesn't work).  I say let's get rid of it.

**Comment by ghost** [comment]
I think it's used in the forum-module. Or am i mistaken?

**Comment by ikoniqoz** [comment]
I vote to retain the Username. Its part of Pyro's DNA since version one and before. We just need to get the login with username fixed. For me, i am taken to a white screen.

**Comment by RyanThompson** [comment]
It's "standard" user information. Github has it. Facebook technically has it. Twitter has it. Etc. It's not always used in a system like Pyro but I would assume automate it / hide it during registration before lopping it off completely. 

PyroCMS.com uses it for one (yes in the forum). But it's definitely needed for projects that Pyro handles outside of the normal website. 

I say add option for automating it. Thoughts?

**Comment by mattcdavis1** [comment]
I think that would help.  Maybe consider renaming the "username" field to "handle" which separates it from the association with login / credentials and better reflects its purpose.

**Comment by ikoniqoz** [comment]
Lets just leave it - it is a widely accepted norm and has been in Pyro since before the Dawn.
