### ISSUE TITLE
Feature Request - Locking a page preventing multiple users to edit at the same time

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4387]

**Comment by Piterden** [comment]
And tree, too )

**Comment by ghost** [comment]
Agree Mr @Piterden

**Comment by huglester** [comment]
+1 from me. Often needed feature

**Comment by RyanThompson** [comment]
Maybe some socket/polling action to let others know the item you are editing is being edited by another.. Seems higher level than where we're at right this moment. But I'll take ideas all day long!?

**Comment by Piterden** [comment]
![image](https://user-images.githubusercontent.com/5930429/27436378-b98cd88e-5767-11e7-8f89-aa005653a2f3.png)
Not this?

**Comment by ghost** [comment]
Might be higher level... But at the same time, if you want pyrocms to be used in large corporations then this is a must. And an important one. With staff members editing the site, you could end up ruin and having to redo a lot of stuff. So i definitely see this as something we should have a think about. Must be possible to achieve this rather simply. I will check and see how modx has solved it. Or do you already know @Piterden

**Comment by Pixney-William** [comment]
@RyanThompson What is the status on this issue? I am beginning to have issues with clients who report that they need this feature since they are a couple working on the website and things get messed up.

We need something here, otherwise it will not be possible to use the cms for larger organisations...

**Comment by Pixney-William** [comment]
Form locks is being introduced in version 3.5

https://pyrocms.com/posts/pyrocms-3-5-beta1

**Comment by girvydas** [comment]
Need option whether it's on or off per each formbuilder.

**Comment by RyanThompson** [comment]
This is in Pyro 3.5
