### ISSUE TITLE
FormBuilder Redirect Option does not work

### ISSUE THREAD

**Issue by christrumbull** [pyrocms/pyrocms#4389]
@RyanThompson  as discussed on slack:

When using FormBuilder and setting a custom redirect in the options array, the redirect is skipped, overlooked or ignored for some reason. I have tried this from a custom extension and stream with a plugin and creating a twig function to display the form on a page.

I have also tried to create the form using the artisan commands to create a separate module and stream in the event that I had missed a step in using the formbuilder (even though most skipped definitions are guessed from the builder).

I had also tried to force the redirect using on save callback, setting the option after the form was built using the builder and setting the option on the handler.

I also tried to do a redirect on the action as described as a possible solution in the documentation.

It still only redirects to the page that the form is on and then hides the form output. The form being hidden on redirect was also not the expected result, perhaps after we figure out why this is not redirecting youcan guide me as to how to not hide the form? 

Thanks!

Example Code:
`namespace Shared\DataDumpExtension\Data\Form;

use Anomaly\Streams\Platform\Ui\Form\FormBuilder;

class DataFormBuilder extends FormBuilder {

  protected $fields = [
      'name' => [
        'label' => 'Name'
      ],
      'email' => [
        'label' => 'Email'
      ]
  ];

  protected $actions = [
      'submit' => [
        'text' => 'Submit The Form Now!'
      ]
  ];

  protected $options = [
      'redirect' => '/',
      'success_message' => true
  ];

}`

**Comment by Piterden** [comment]
```php
namespace Shared\DataDumpExtension\Data\Form;

use Anomaly\Streams\Platform\Ui\Form\FormBuilder;

class DataFormBuilder extends FormBuilder
{

    /**
     * @var array
     */
    protected $fields = [
        'name'  => [
            'label' => 'Name',
        ],
        'email' => [
            'label' => 'Email',
        ],
    ];

    /**
     * @var array
     */
    protected $actions = [
        'submit' => [
            'text' => 'Submit The Form Now!',
        ],
    ];

    /**
     * @var array
     */
    protected $options = [
        'redirect'        => '/',
        'success_message' => true,
    ];

}
```

**Comment by RyanThompson** [comment]
This has been since resolved!
