### ISSUE TITLE
Editing Posts: Less Error

### ISSUE THREAD

**Issue by psaunders** [pyrocms/pyrocms#4392]
I see the editor double save got fixed, but after doing a composer update and clearing whatever caches I could find I get this:

Symfony\Component\Debug\Exception\FatalErrorException: Object of class Anomaly\Streams\Platform\Asset\Filter\LessFilter could not be converted to string in /Users/admin/www/sailingonsound/vendor/anomaly/streams-platform/src/Asset/Asset.php:839

PS: https://help.github.com/articles/disabling-issues/ and a readme entry would save you a lot of time

**Comment by psaunders** [comment]
Issue is on the streams-platform, I'm guessing some of the theme changes

**Comment by RyanThompson** [comment]
This should be resolved ^_^

And thanks for the tip! I had no idea I could disable issues lol 🤔
