### ISSUE TITLE
[feature] Make clear caches buttons in CP

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4393]
Separately for twig, views, assets, and clear-compiled. And one button for clear all.

**Comment by ikoniqoz** [comment]
+1 Awesome idea. Assumption being that we can access the CP.

**Comment by RyanThompson** [comment]
I think that on a system / diagnostic type page would be cool.

**Comment by RyanThompson** [comment]
Putting this on the back burner for now.
