### ISSUE TITLE
anomaly.field_type.boolean  toggle - does not fire events.

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#4394]
Hello,

so we have this: anomaly.field_type.boolean
We use it in the table builder, like entry.enabled.toggle

The problem is, when we trigger this 'toggle' button, no 'saved' events are fired on a model.
I am not sure if saved is a proper event, but probably yes :)

Can this be fixed?

Thanks

**Comment by Piterden** [comment]
Toggle in table builder. Does it caused reload?

**Comment by huglester** [comment]
yes, in table builder. 
Not toggles does not reload the page. it's an ajax request

**Comment by Piterden** [comment]
Look here https://github.com/Piterden/boolean-field_type/blob/2.2/src/Http/Controller/Admin/BooleanController.php
Seems it's a problem with your parent model

**Comment by Piterden** [comment]
Could you check with dd, which exactly model and repository has that controller when you toggle?

**Comment by huglester** [comment]
not sure. maybe it's on my end...
I'll reopen when get more info. Thanks @Piterden

**Comment by Piterden** [comment]
NP )
