### ISSUE TITLE
[video-field_type] Add matcher validation and youtu.be to youtube matching.

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4396]

**Comment by Piterden** [comment]
https://github.com/anomalylabs/video-field_type/pull/4

**Comment by Piterden** [comment]
@RyanThompson is there any problems with ^ that RegEx matching?

**Comment by RyanThompson** [comment]
Nope it was perfect! Just had some conflicts from  changes I had made prior. 

Is there anything for vimeo we need to do like that? To help match more formats?

**Comment by Piterden** [comment]
Have you the list of possible vimeo URIs?
