### ISSUE TITLE
[feature] Ability of import/export stream

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4398]
I propose to add two buttons import and export of stream data. Export of empty stream gives to user a file with field names. JSON and CSV formats.

**Comment by Piterden** [comment]
And XLS!

**Comment by fatihalp** [comment]
It would be nice @Piterden 👍

**Comment by Piterden** [comment]
@fatihalp Check out my unfinished extension for export https://gitlab.com/pyro-plus/exporter-extension

**Comment by RyanThompson** [comment]
This is all inherent in LS with the JSON and what not
