### ISSUE TITLE
[feature] Possibility of change default CP route

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4400]
`admin` I mean. It would be good to be able to change it.

**Comment by RyanThompson** [comment]
Once upon a time - but I don't think this is really needed any more. The cost vs benefit ratio is also WAY not in our favor.

**Comment by Piterden** [comment]
Excuse me, needed any more for what?
If I need to move some site from some CMS to Pyro, I think, it is more than necessary!!!

**Comment by RyanThompson** [comment]
What’s the benefit? To obscure the admin login? That’s the only thing I can think of it would benefit.

And my question is, with all other modern security measures in place, why do you need to obscure the admin login?

**Comment by Piterden** [comment]
Benefit is stayed unchanged routing
`https://pyrocms.com/wp-admin`
:smiley:

**Comment by RyanThompson** [comment]
Oh Lordy..
