### ISSUE TITLE
files_field-type

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#4401]
Hello,

sometimes when I upload multiple files, I get error. that file is not uploading.
I debuged to this JS error:
```js
detail:"An error has occurred and this resource cannot be displayed."
id:"895d04ea-0f18-48a3-92d7-bdb5f48bce84"
status:500
title:"Internal Server Error"
```

In laravel logs I see this: 
```php
[2017-06-09 09:04:31] local.ERROR: PDOException: SQLSTATE[HY000]: General error: 5 database is locked in /home/huglester/Projects/app-pinigai/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php:546
Stack trace:'
```

As I understand, this is more of the 'tntsearch' issue... but maybe we can somehow overcome this?
For example:
Upload files ONE-BY-ONE, not many at the time? because now files are being uploaded in random order.

**Comment by RyanThompson** [comment]
Not entirely sure how to fix this one just yet.. Like it’s trying to index things too fast.

**Comment by RyanThompson** [comment]
I think this merged PR should help - for different indexes down the road we can change it back as needed.
