### ISSUE TITLE
demo@pyrocms.com user in clean install?

### ISSUE THREAD

**Issue by AlexanderOMara** [pyrocms/pyrocms#4403]
I just made a clean install for testing and noticed something odd in the database. Apparently a "demo" account is created automatically on install.

![screenshot](https://user-images.githubusercontent.com/1740229/27000937-d8fade96-4d8a-11e7-973b-deff03fb744d.png)

This seems very strange and unpleasant. Is this a bug or a feature?

**Comment by Piterden** [comment]
There should be 2 accounts created during installation. Your admin account with credentials you entered, and demo account.
So, this is the feature, not a bug.

**Comment by RyanThompson** [comment]
Yep this is normal - the demo user can be deleted - it has ZERO permissions by default so it’s just there to let people experiment if they want. Dummy seed data :-P
