### ISSUE TITLE
[feature] Option to duplicate pages with 1 click on a button by @dwainscheeren

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4405]
https://github.com/anomalylabs/pages-module/issues/50

And my proposing to make not a duplicate, but just open create form with fields already filled with values of defined by you existed model.

I think it could be not only for pages module, but as a streams core feature.

**Comment by ghost** [comment]
I agree with @Piterden . Its better to just open a new form with filled fields, forcing the user to make a second decision if they really want to duplicate, and the possibility to change the fields directly. Its also quicker, compared to copy the page, and then click into it to change values.

This way the slug field could be cleared making sure it's not duplicated as well.

**Comment by RyanThompson** [comment]
I have a super clean way to allow duplicating I can get worked in (core thing).

$builder->duplicate($entry/$id)->render();

Basically fills from the entry but is a "create" mode form.

**Comment by RyanThompson** [comment]
Pretty sure I have this on another issue if not in my own task list. Closing for now.
