### ISSUE TITLE
[feature][architecture] Move Registry to Support namespace

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4408]
I have found 7 repeats of using Registry abstraction in streams-platform + core addons:
```
core/anomaly/api-module/src/Entity/Component/Action/ActionRegistry.php:
vendor/anomaly/streams-platform/src/Ui/Button/ButtonRegistry.php:
vendor/anomaly/streams-platform/src/Ui/Form/Component/Action/ActionRegistry.php:
vendor/anomaly/streams-platform/src/Ui/Icon/IconRegistry.php:
vendor/anomaly/streams-platform/src/Ui/Table/Component/Action/ActionRegistry.php:
vendor/anomaly/streams-platform/src/Ui/Table/Component/Filter/FilterRegistry.php:
vendor/anomaly/streams-platform/src/Ui/Table/Component/View/ViewRegistry.php:
```
They all ^ have repeated methods.

Maybe it would makes sense, to move Registry abstraction to the separate class? And, listed above registries, could extend that class...

**Comment by RyanThompson** [comment]
In time - a lot of the stuff in UI will be abstracted.

**Comment by RyanThompson** [comment]
Ill close for now though - since it's kinda a background task I don't want this open for months and months :-P
