### ISSUE TITLE
Streams / Files Module [Bug] In some cases the folder is not pre-selected

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4409]
When clicking "Select a File" from a files field type the file filter for the appropriate file folder(s) should already be applied.  However, in some cases it is not.  1 way to reproduce this error is:

1. Click "Create" on a stream entry
2. Upload a file and close the upload modal
3. Click the "Select a File" button.  The folder dropdown will show and the pre-selected file filter will not be applied.

**Comment by mattcdavis1** [comment]
Also, the folders in the "Select Folder" dropdown are not alphabetical and i think a select2 dropdown would be better here.

**Comment by RyanThompson** [comment]
I’ll check this out! Thanks

Also though folders are manually sorted in files module. I ran into a lot of cases where the alpha order didn’t reflect how often the user needed to use that folder so mouse travel all the time was annoying. Does that make sense?

**Comment by mattcdavis1** [comment]
For folder dropdowns non-alpha doesn't make sense to me and moving to select2 would eliminate mouse travel because you could quickly search for what you need.  Same thing with selecting a stream in relationship field type (alpha + select2 would be better)

**Comment by RyanThompson** [comment]
Lemme see what I can do ^_^

**Comment by Piterden** [comment]
https://joshuajohnson.co.uk/Choices/

**Comment by RyanThompson** [comment]
Mmm I like.

**Comment by Pixney-William** [comment]
What do you wanna do here @RyanThompson
