### ISSUE TITLE
[Documentation] - Sitemap Extension

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4410]

**Comment by Piterden** [comment]
Agreed, it is necessary to have it.

I have some links in sitemap like `https://mysite.ru/articles/{category}/rezultatyi-oprosa-nuzhna-li-privivka-protiv-grippa`. And even don't know what to start with.

**Comment by ghost** [comment]
@RyanThompson ?

**Comment by RyanThompson** [comment]
Like the sitemap-extension? 

Like what powers https://pyrocms.com/sitemap.xml

**Comment by ghost** [comment]
Yes. What i am missing, and probably others is how it all works and is connected. 

One example: When someone adds it's own module which has some of its own routes/pages. How do you add it to the sitemap.

**Comment by Pixney-William** [comment]
Work it man. We need it :) @RyanThompson

**Comment by Pixney-William** [comment]
Just had a look at that was easy.. so no rush from my side..

**Comment by andriamasy** [comment]
The problem with this sitemap extension is that if any html tags in the base are in xhtml format instead of xml format, if that person is caught then just do it: 

> `$sitemap = preg_replace("/<xhtml:link[^>]+\>/i", ' ', $sitemap);`
