### ISSUE TITLE
[Relationship Field Type] Fix issue where table name is too long

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4411]
It's really frustrating when i have to worry about field assignments causing issues with table length and it's totally unnecessary.  Just allow selection of the relationship table name in the assignment GUI for streams (and via API) with the current settings as the default.

**Comment by Pixney-William** [comment]
Is this still an issue @RyanThompson ? I know i ran into it at some point earlier. Very annoying.

**Comment by RyanThompson** [comment]
Could certainly add more validation and room for improvement here. I'll look into this ASAP.
