### ISSUE TITLE
[documentation] Views sucka

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4414]

**Comment by Piterden** [comment]
What `sucka` means?

**Comment by RyanThompson** [comment]
http://www.urbandictionary.com/define.php?term=Sucka&utm_source=search-action <http://www.urbandictionary.com/define.php?term=Sucka&utm_source=search-action>

**Comment by Piterden** [comment]
The same in Russian))

**Comment by cyrildewit** [comment]
Haha, love the title of this issue

**Comment by RyanThompson** [comment]
All the information I need :-P

**Comment by RyanThompson** [comment]
https://pyrocms.com/documentation/streams-platform/latest#the-basics/views

**Comment by Piterden** [comment]
`anomaly.module.products::admin/products/index`
why no one time there not?
`anomaly.module.products::admin.products.index`

**Comment by RyanThompson** [comment]
It’s either or - slashes are converted to dots within the view factory but IMO it’s more relatable to act like it’s a path not a dot notation for the directory/file.

**Comment by Piterden** [comment]
Ya, more relatable. But couldn't you write about possibility of using dots in that your new section?
