### ISSUE TITLE
[ streams-platform ] Dates don't get localised on MacOS and Linux

### ISSUE THREAD

**Issue by ddnetters** [pyrocms/pyrocms#4416]
Dates don't get localised on MacOS and Linux. Pyro sets the locale to something like `nl` while the system only know `nl_NL` resulting in dates reverting to english as fallback.

One potential fix is adding something like`setlocale(LC_ALL, config("locale.".LOCALE, LOCALE));` in the `SetLocale` middleware. You could then fill a config file called `locale` with an array which would look a bit like this:
```php
return [
    'nl' => ['nl_NL', 'Dutch_Netherlands', 'Dutch','nl', 'nl_NL.ISO8859-1', 'nld_NLD','nl-NL'],
    'en' => ['en_GB','en_US','English']
];
```

### Steps to reproduce

1. Enable dutch and english
2. Have the posts-module index view show the dates in some format like `Friday, 23 June 2017`
3. Go to `<site>/nl/posts`
4. Dates are still english

**Comment by huglester** [comment]
Same here.
@RyanThompson any idea on how to 'best' fix this?

**Comment by ddnetters** [comment]
I have a temporary fix while we sort this out.

**Temporary fix**
Replace all namespaces with your own, obv
1. Add [this](https://gist.github.com/ddnetters/fc066954eff5f6b928990895c3cce60f) file in your theme in the following folder: `<theme>/src/http/Middleware`
2. Add the following code to your themes service provider:
```php
    protected $middleware = [
        \Wirelab\DealerdirectTheme\http\Middleware\SetLocale::class
    ];
```
3. Create the file `config/locale.php` with the structure:
```php
<?php

return [
    'nl' => 'nl_NL',
    'de' => 'de_DE',
    'en' => 'en_EN',
];
```
4. Format your dates using `formatLocalized` in views.
```twig
{{ post.date().formatLocalized('%A %d %B %Y') }}
```
I think you can turn it into a multidimensional array for fallbacks but haven't tested it. (` 'nl' => ['nl_NL','nl','Dutch']`)
