### ISSUE TITLE
Allow for separate cache store for twig

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4420]
Here is the initial issue - i'm getting exceptions on production for form such as [this](https://goo.gl/kKT5od) from a url like this `streams/multiple-field_type/index/1ad449ff1084a09a35249767ec012f83`.  I think that what is happening here is the the following:

1. User has a form opened.  
2. I deploy code and clear cache (part of deployment process) or another user saves and entry (saving an entry also clears the cache).  
3. User saves form or triggers an action similar to the above.
4. Error

This could be avoided if i had a way to clear only the template cache which is all i really need to clear on deploy / save entry.  One way to handle this would be to just use the database for all caching because then i could target specific keys.  However, in my testing the db cache is slower than file cache.  If i could use db cache only for template caching and file caching for other stuff that would alleviate the issue. This would require a consistent db prefix (or flag for queue drivers that support this) for all the twig template cache entries.  Even if it was all file based if there were some way to target twig cache only (maybe a folder or something) that would help.

On a related noted - something seems off with caching.  I'm seeing 14 database deletes / inserts on every page load.  this may be why the database cache option is slower. I'll create a separate issue for this.

**Comment by RyanThompson** [comment]
Going to research this

**Comment by Pixney-William** [comment]
What was the result of your resaerch @RyanThompson

**Comment by RyanThompson** [comment]
Caching has been improved in general where the inserts/deletes were concerned. I can't break apart cache per service though I am going to make it so that this fails more gracefully right now.
