### ISSUE TITLE
[Streams Core - Caching] (Bug) Cache is deleting / inserting on every page load

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4421]
Here is what i'm seeing: https://goo.gl/Wq66XH (14 inserts / deletes on every page load).  [Here is a screenshot](https://goo.gl/whfzFh) of a clean install.  With the clean install i'm only see 6 inserts / deletes.  There should be zero though (after the initial cache).  I mean, what's the point of caching if your going to delete/re-write on every page load.  At that point caching is only adding time not saving time.

I'm not sure if this issue is database-cache specific only or not since it's harder to see when file stuff is getting cached.

**Comment by RyanThompson** [comment]
Good catch @mattcdavis1  -  on it.

**Comment by Pixney-William** [comment]
Is this sorted @RyanThompson

**Comment by RyanThompson** [comment]
Fixed in 3.6: https://github.com/anomalylabs/streams-platform/commit/652884da3cbe1ce4ed468e90870886850a7889a5
