### ISSUE TITLE
[documentation] Many-to-many documentation has no examples

### ISSUE THREAD

**Issue by Jameron** [pyrocms/pyrocms#4423]
I recently got started on a Pyro CMS application and found that the documentation was not sufficient for me as a newb to get started with a Belongs-to many relationship.

I would like to contribute some documentation updates with examples.

**Comment by Piterden** [comment]
Does multiple and polymorphic FTs, not enough for your needs?

Examples could be found in pages, posts and users modules.

**Comment by RyanThompson** [comment]
@Jameron a fellow metalhead I see! Welcome ^_^

Can you tell me - what's your experience with Laravel in general?

Agreed though it's not very obvious that the FT will generate the relationship for you.

**Comment by Jameron** [comment]
Hey Ryan, thanks! I've been chatting in the Pyro Slack chat as Cameron you might know me from there. I've been developing with Laravel since 4.1. I've built a handful of medium sized applications ranging from concert finding apps, budgeting apps, Wix clones, to social learning management systems. I have handled the deployment as well on load balanced AWS setups.

I'm working at a development agency that needs something in between a CMS and Laravel. Pyro looks like it is going to fit our needs. 

Our only issue is the initial learning curve is heavy and development has been slow as a newb with no Pyro experience.

Once I work through a feature with the help of Pyro Slack channel I realize how easy it is to accomplish my needs, but find the documentation just was not enough without getting some tips from the community.

I would be into helping out with getting some brief examples into the docs.

**Comment by RyanThompson** [comment]
This will have to do for now - FTs will get updated too: https://pyrocms.com/documentation/streams-platform/v1.1#models/relationships

**Comment by Piterden** [comment]
Had you checked the time of that page load?

**Comment by Piterden** [comment]
Google crawler will not eat all that would be more than 2.5Mb

**Comment by RyanThompson** [comment]
Ya docs are getting split up soon
