### ISSUE TITLE
[ installer-module ] Move the installer module to require-dev

### ISSUE THREAD

**Issue by ddnetters** [pyrocms/pyrocms#4425]
You don't really need the installer module on a production environment. I reckon a cleaner way of dealing with the 'error' that the installer module is still present is by:

1. Moving the installer module to require-dev
2. Installing pyro in development mode
3. Switch to production
4. Run composer update

**Comment by RyanThompson** [comment]
I dig it: https://github.com/pyrocms/pyrocms/commit/9ba6d6129a46b284fd3adee7d3656840f6022ab2
