### ISSUE TITLE
[feature] Keep the history of changes in form fields after save.

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4431]
When I used Modx, there was one awesome feature. The history of editing not erases after saving a document. I mean, for example WYSIWYG - lets imagine you writing something, then press ctrl+s, after that you could easily press ctrl+z in focused editor to return some state which was before saving.

Could we have something similar with PyroCMS?

**Comment by ghost** [comment]
Yeah.. good idea!

**Comment by RyanThompson** [comment]
This is something that will be soon baked in.

**Comment by RyanThompson** [comment]
Based on this: https://github.com/VentureCraft/revisionable

**Comment by Piterden** [comment]
No, it's not about it. I mean history inside each of field. Undo and redo with ctrl+z/ctrl+y

**Comment by RyanThompson** [comment]
Eh.. not that crazy about that. Browser will likely handle most of that for us.

For revisionable: https://github.com/pyrocms/pyrocms/issues/4346

**Comment by Piterden** [comment]
Browser not handle history after reload page. It's necessary to make AJAX saving of a FormBuilder.
