### ISSUE TITLE
[accelerant-theme][bug] Move footer and modals inside app

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4432]
![image](https://user-images.githubusercontent.com/5930429/27839716-2752f7a2-60fc-11e7-9f40-154a18fea1f0.png)
What is the reason of placing footer and modals outside of the app? I'm sure they should be inside.

**Comment by RyanThompson** [comment]
Why? And in my defense - why not? :-P

**Comment by Piterden** [comment]
What why not? You have the app, and all other things, should be inside. This is the question, why it is outside of the app? If there is some reason that's one deal, but if not, it should be placed inside the app.

I'm truly surprised about you don't think so! It's strange.
