### ISSUE TITLE
[bug][wysiwyg-field_type] Replacing <b> <i> and <strike> tags with others

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4433]
Redactor has default setting:
```javascript
replaceTags:{b:"strong",i:"em",strike:"del"},
```
I think not superfluous would be allow users to control all available options of JavaScript libraries.

**Comment by dwainscheeren** [comment]
Yes @RyanThompson add             replaceTags: {}, online 66 in input.js

**Comment by Piterden** [comment]
No, add all settings of the redactor, to the config array of the field type.

**Comment by huglester** [comment]
as far as I know, this is new style with strong, em.
If I remeber correct, even some HTML validators, complain about <i>

**Comment by RyanThompson** [comment]
These tags are deprecated and will fail most modern validators including ADA which is something I would like to keep. If you really want them removed you can modify the input.js in your overloaded addon resources.

**Comment by Piterden** [comment]
`<i class="fa fa-times"></i>` deprecated? Are you normal?
