### ISSUE TITLE
[installation] Setup build to push daily downloadable install.

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4434]

**Comment by edster** [comment]
This is something I have thought about a couple times since beta1.

The biggest problem is keeping everything in sync, but for a flat, this is the release your on have fun. i think it is a great idea.

Composer is great, but there are situations where it doesn't work out the way we hope.

**Comment by RyanThompson** [comment]
I figure I could trigger daily builds and push it to S3 - then redirect like pyrocms.com/downloads/latest to that S3 URL

**Comment by RyanThompson** [comment]
@edster can you tell me more about the latter part of this?

> Composer is great, but there are situations where it doesn't work out the way we hope.

**Comment by edster** [comment]
I think the s3 idea with pyrocms.com/downloads/latest is a great idea.

Issue is syncing it with production, installatron is a oneclick install, looks like it is for production.

We don't really have a good way of keeping production code up to date for something like that for users who would use it.

Most devs at this point would use local, test, staging, production. Meaning they are already using composer, or are composering on local, and uploading via git or something.

Just mentioning that, without a clean way of keeping source up to date, we run into problems with one click installers, as there is no way to update.

Just a note ^.^

**Comment by Piterden** [comment]
I think, we shouldn't spend our time on such of things. It's really not necessary!

**Comment by huglester** [comment]
I think the best would be:
1. script just git clones
2. composer installs via cli
3. zip folder...
then this folder can be extracted and used

**Comment by Piterden** [comment]
How do you like this. It has improved bash with git info in prompt, also tmux and all soft installed.
```bash
vagrant init Piterden/pyrocms
vagrant up
```
@RyanThompson you asked about it!
