### ISSUE TITLE
Make all settings of each JS library possible to manage by user!

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4435]
I feel, like somebody cut my hands, when I have powerfull high-weight lib and can't use it fully, just because you think that I don't need it ever.
Could user get all settings for manage?

**Comment by RyanThompson** [comment]
You can 100% do this yourself. Publish the addon - change config as needed - include your own deps / etc.. You can 100% override FT functionality in every way as a developer if you so choose.

**Comment by Piterden** [comment]
Look, now you understand about docs? You could open RyanThompson's school, be a teacher..

**Comment by Piterden** [comment]
I mean, last time I asked you told me you not supposed user need it.
Also you specially not pay to slack for destroy the history of speeches.
