### ISSUE TITLE
[feature] changing admin url 

### ISSUE THREAD

**Issue by stefanpkc** [pyrocms/pyrocms#4437]
It should be possible to change the admin URL. This way people can't reach the admin login screen. When people can easily reach an admin login screen it looks unprofessional I think.

**Comment by Youhan** [comment]
I don't see any other problem than being unprofessional which is relatively hard to define!

**Comment by RyanThompson** [comment]
We've released maybe 50 sites and not one complaint :-P

I think this is a little paranoia but should be easy to do if I can do what I wanna do where I wanna do it.. does that make sense? lol

**Comment by RyanThompson** [comment]
Almost there: https://github.com/anomalylabs/streams-platform/commit/b768e413ddf806eb61eb8a4e02668ea1275ccf0c

If you wanna play with it - change that segment variable.

Only problem now how to handle rewriting everything.. buttons / redirects / etc.

**Comment by Piterden** [comment]
:trollface:

**Comment by Pixney-William** [comment]
Seems like you tagged this @RyanThompson , is it done?

**Comment by RyanThompson** [comment]
Not worth it IMO. It can be secured in so many other ways. The router is the issue here - recognizing different admins is one thing but rewriting routes/url generator is not a good idea.
