### ISSUE TITLE
[streams-platform] Add the --addon option to make:command

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4438]
And have it parse into the service provider.

**Comment by Piterden** [comment]
`artisan make:command RenameSlug anomaly.module.pages` -> /core/pages-module/src/Command/RenameSlug.php

`artisan make:command RenameSlug anomaly.module.pages::type` -> /core/pages-module/src/Type/Command/RenameSlug.php

`artisan make:command RenameSlug anomaly.module.pages::type.form` -> /core/pages-module/src/Type/Form/Command/RenameSlug.php

**Comment by dwainscheeren** [comment]
Reminder, this would be help full.

**Comment by finnito** [comment]
👍 Would love this.
