### ISSUE TITLE
[grid-field_type] Changing slug of a grid cause errors

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4440]
If you have used a grid on your page with the slug **yyan**, and then you rename the slug to **ryan**. This is causing an error trying to access the page both in public and in admin.

**Comment by Piterden** [comment]
Actually it should rename column https://github.com/anomalylabs/grid-field_type/blob/1.1/src/GridFieldTypeSchema.php
Have you tried once more time?

**Comment by ghost** [comment]
No i havent but i am pretty sure this is an issue. However, ill try it ... soon. Hopefully.
