### ISSUE TITLE
[file-field_type] Relationships don't populate in twig when the field is translatable

### ISSUE THREAD

**Issue by squatto** [pyrocms/pyrocms#4441]
I have a field `case_study` on a `markets` stream that is used for uploading case study PDF files to the entry. I need this field to be translatable, so that the user can upload translated PDFs to go along with the translated entry. However, when I set the field as translatable, the twig accessors don't work anymore.

`$assignments` is very simple:

```php
'case_study'  => [
    'translatable' => true,
],
```

To access it in twig I use `{{ market.case_study.url }}`. If I set `translatable` to `false`, I see the URL. However, if I set it to `true`, no URL is returned. I'm able to upload the file, I just can't access it.

**Comment by Piterden** [comment]
**files-field_type**
**image-field_type**
**relationship-field_type**
**multiple-field_type**
Does it make a sense to give to the user ability to set translatable assignment of these field types?

**Comment by squatto** [comment]
I believe so. My use case is the perfect example. On the English version, the user will read an English PDF. On the French version, the user will want to read a French PDF, not the English PDF.

The same concept would apply if you were, for example, showing an image for the entry, and the image had words on it. You would want French users to see French words on the image.

**Comment by Piterden** [comment]
I understand what you what to say. But I suppose, it would be too much, to have another one join (file is essentially - join) everytime. If you need translatable pdf, you could create stream **Documents** where all additional information (price and so on, if you wish...) could be stored.

In most of cases you would need it.

But this is only my opinion and finally Ryan will tell you about how it would be.
