### ISSUE TITLE
Make stream in CLI doesn't recognize addons with underscores

### ISSUE THREAD

**Issue by calebsmithdev** [pyrocms/pyrocms#4442]
I have an addon called `default.module.content_blocks`. When I create a stream inside this module, I receive an error similar to the following.

 `File does not exist at path /default/content_blocks-module/src/Content_blocksModuleServic
  eProvider.php`

Everything seems to work as expected, but the provider should be `ContentBlocksModuleServiceProvider.php`

**Comment by Piterden** [comment]
Have you updated composer? It was fixed yesterday.
https://github.com/anomalylabs/streams-platform/pull/424

**Comment by RyanThompson** [comment]
Yep should be good to go
