### ISSUE TITLE
[documentation] Guide about basic usage of model and repository. Examples how NOT to do.

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4444]

**Comment by RyanThompson** [comment]
Can you provide some examples of what you'd like to see?

**Comment by Piterden** [comment]
I have a stack of it:
## EntryRepository
- about naming of functions (findBy findMany findAll)
- about short and clear methods 
- about creation/deletion (how to do it right, why not to use model)
- when to use EntryCollection
## EntryModel
- when to use model and not use repository
- what is the similar between all methods of the model
- getting criteria, presenter, and so on
## Both
- What is interface and why we should use it
- how don't catch exception when mapping interfaces
- methods of overriding standard models (this I could write )))))

**Comment by Piterden** [comment]
4444 rocks

**Comment by RyanThompson** [comment]
On it's way
