### ISSUE TITLE
[files-module] too long translation table name

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4445]
I have pages and there are 108 from there 98 are of event type. I need to seed events with galleries which are files-FT, and logos, which are file-FT.
So what I do - putting files to folders, named exactly like pages slugs, then try to seed it.

Translation table name is too long???!!!

Why do I need translation on folder? I want just it would works, please, how to disable that translation model?

**Comment by RyanThompson** [comment]
There's an obvious problem with your approach there I think. But Pyro translates everything that could be exposed to the front end. We have a project where files and folders are displayed to users of potentially 3 different languages and folders are translated for their convenience.

**Comment by RyanThompson** [comment]
Sometimes it's a case not of "Why do you _________?" but actually "How can I _________?". Does that make sense?

**Comment by Piterden** [comment]
Okay, let it be translatable, but
![image](https://user-images.githubusercontent.com/5930429/27955775-17f06022-631f-11e7-8b64-7b1ec45a0105.png)
Let it works ^

**Comment by mattcdavis1** [comment]
yeah - the too long table name issue is really annoying and unnecessary.  Happens in other contexts also.  Would like to see an across the board fix for this.  I have ticket elsewhere regarding the same thing.  All you need to do is allow people to choose the table name with a sensible default (or apply some logic that keeps trying different names until one is short enough based on some algorithm.

**Comment by ghost** [comment]
Agreeing with @mattcdavis1 , this is an issue i think. Ran into it today: https://github.com/pyrocms/pyrocms/issues/4445
