### ISSUE TITLE
[Localisation] Being able to make fields translatable at a later stage.

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4447]
If you have chosen to first not make a field translatable. But later decide it should be, we need to be able to edit this.

I know you are planning for this. When do you think it will arrive?

**Comment by Piterden** [comment]
You understand that we should create/remove table in DB to achieve this?

**Comment by RyanThompson** [comment]
If I recall the code is there but needs a little testing and it would not change the fact that if the stream is not translatable you can't translate the field (and the stream can not be changed in that manner).

**Comment by RyanThompson** [comment]
Just as a heads up.. ^

**Comment by RyanThompson** [comment]
This is certainly on it's way - but is tricky.
