### ISSUE TITLE
[streams-platform][form-plugin-function] Need rules on formbuilder object.. to merge in

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4448]
Also fields() method sucks with * on front end

**Comment by Piterden** [comment]
But works with `'*': '*'`

**Comment by RyanThompson** [comment]
Which is good to know! But Kinda tedious to append rules I think ya?

**Comment by Piterden** [comment]
Unquestionably.

**Comment by RyanThompson** [comment]
Donezo - updated form builder docs
