### ISSUE TITLE
[CP Theme] Updates breaking assets

### ISSUE THREAD

**Issue by calebsmithdev** [pyrocms/pyrocms#4449]
`pyrocms/accelerant-theme (v1.0.54 => v1.0.55)` causing some issues with admin assets. Had to run a `php artisan assets:clear` to regain assets again in the backend. No errors were logged.

**Comment by RyanThompson** [comment]
This should do it! https://github.com/anomalylabs/streams-platform/commit/d8c4816cacdeeb4abe12d2e1034d2bd13da136c3

Really the `&$filters` was the issue.. the rest was cleaning up to expose it :-P
