### ISSUE TITLE
login errors show in the dashboard

### ISSUE THREAD

**Issue by MohamedHar0un** [pyrocms/pyrocms#4451]
i was testing the applications and one of our test cases was:
- trying to login several times with wrong credentials till you got the (too many requests) page 
- press the back button on your browser 
- login with the correct credentials 
the action:
- it logs you in but it shows an error message with (login credentials errors ).
the screenshot below will clarify more.

also, how can i inherit a module so i can work with it's tables like if i want to create a new module to show all the users and assign a team leader or a manager for each user. i know how to do it with laravel but since i'll be using the cms, it will be great if it support this.

Many Thanks ,
![error](https://user-images.githubusercontent.com/18091140/27992240-a130d47c-648f-11e7-9502-e124fc0e8357.png)

**Comment by RyanThompson** [comment]
I think this is probably a case of refreshing or something odd causing a session message to store and not be flashed out - edge case I would say.. 

As far as Pyro - you can do anything in Pyro that you can do in Laravel - and the same way too - it IS laravel ^_^
