### ISSUE TITLE
[users-module] Users table should show email/username pending what's in preferences for being used.

### ISSUE THREAD

**Issue by emergingdzns** [pyrocms/pyrocms#4452]
I would like to request that you add a way for the admin user to select which of the columns to show in the Users table. Right now it is essentially hard set in the UserTableBuilder file to show display name, username, email and status. In my case, I never use the username field for anything so I'd love to be able to remove that column and maybe choose a different column. But I'd rather not have to fork and replace the users module.

In fact the ability to customize the columns through the admin for all modules that use the table builder functionality would be kind of nice. Just a thought.

**Comment by Piterden** [comment]
++

**Comment by calebsmithdev** [comment]
Username field is dependent on a few variables for login (if I remember right). I don't use usernames as well, so there may be a better option of allowing a toggle trigger in admin settings for either email and/or username login.

**Comment by Youhan** [comment]
There is already a setting to choose which field to use for login:
![screen shot 2017-07-10 at 8 11 32 pm](https://user-images.githubusercontent.com/2191898/28026711-2417d346-65ac-11e7-9978-4c40a2ed9795.png)

**Comment by calebsmithdev** [comment]
Perfect (how have I missed that). So now the perfect opportunity would be to trim down the GUI excess based on that preference.

**Comment by RyanThompson** [comment]
I agree! I'll have the column modified to reflect that.

**Comment by calebsmithdev** [comment]
@RyanThompson - Could I entertain the idea of having an option for "Both"? I have two projects (none currently Pyro) that do use both as an option, so that would be a nice to have for future projects.

**Comment by emergingdzns** [comment]
Thanks @RyanThompson! I think that at the very least showing one or the other would be good, but if someone is using "username" as their login they may want to see both. My thought was making it possible to modify the columns that appear from within the application. Kind of like the old Pyro. You could have the builder file determine the default and then have it able to override. Just a thought.

**Comment by RyanThompson** [comment]
I think I am going to close this in lieu of being able to make views in the future.. The possibilities could go on and on as to why to include it / leave it / show both / show something different / etc.
