### ISSUE TITLE
[Streams Platform] extendRules() error

### ISSUE THREAD

**Issue by calebsmithdev** [pyrocms/pyrocms#4454]
Saving a page is giving me this error

`"Type error: Argument 1 passed to Anomaly\Streams\Platform\Addon\FieldType\FieldType::extendRules() must be of the type array, string given, called in /vendor/anomaly/streams-platform/src/Ui/Form/FormRules.php on line 61"`

I am saving a page with a custom page type using a single grid block field type. Error is happening consistently no matter which grid block I add to the page. Saves fine as long as I don't add a grid row.

**Comment by ghost** [comment]
Confirmed @RyanThompson i also have this problem on two local sites!

**Comment by RyanThompson** [comment]
Fixed - sorry guys :-(

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/f6973ddc2137c309efe991b5fdc055b9336da255

**Comment by calebsmithdev** [comment]
No problem - thanks for the quick fix!

Confirmed that it does work on my sites now. I will go ahead and close out the issue.
