### ISSUE TITLE
[streams-platform] double JSmin lib?

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#4455]
Hello

in recent versions of streams-platform, I get this: 
Warning: Ambiguous class resolution, "JSMin" was found in both "/home/huglester/Projects/app-ebaldai/vendor/lmammino/jsmin4assetic/src/JSMin.php" and "/home/huglester/Projects/app-ebaldai/vendor/linkorb/jsmin-php/src/jsmin-1.1.1.php", the first will be used.

probably one should be removed? or both are needed?

**Comment by machii28** [comment]
Does it has an answer to this thread.

**Comment by Piterden** [comment]
JSmin.php ??? WTF???
