### ISSUE TITLE
[repeater-field_type] - does not work with file-field_type

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#4456]
Hello,

I am getting similar "white" screen (http://pic.webas.lt/webas.lt-d76bd47ecf.png) , when I have a repeater field type, WHEN  repeatrer has anomaly.field_type.file (files) attached to it (While testing, spot that other relations field types, also break this, but not tested enought)

How to reproduce?

1. I cloned the pyrocms/pyrocms (installed etc.)

2. Took this module (private) https://github.com/anomalylabs/products-module

3. 2017_04_28_061131_anomaly.module.products__create_variants_stream.php  to this : https://paste.laravel.io/8NPBe

(note that I also commented, downloads, properties etc, since those also affect this bug).

4. uncommented in addons/default/anomaly/products-module/migrations/2017_02_22_175704_anomaly.module.products__create_products_fields.php  migration 'VARIANTS'  (and named test):
```php
'test'         => [
            'type'   => 'anomaly.field_type.repeater',
            'config' => [
                'manage'  => false,
                'add_row' => 'anomaly.module.products::button.add_variant',
                'related' => 'Anomaly\ProductsModule\Variant\VariantModel',
            ],
        ],
```

5. in addons/default/anomaly/products-module/src/Product/Form/ProductFormSections.php
added 'test' to fields list, so we see it in the FORM:
```php
'fields' => [
                                'name',
                                'slug',
                                'description',
                                'test',
                            ],
```

- now installing the module. ie creating a product (without variants) - saves it.
- now try EDIT, and add a variant (slug: test)
- save changes;
- try pressing edit on the product, and you wont see the form - only white screen with half of text.

# 
- Now edit this: 2017_04_28_061131_anomaly.module.products__create_variants_stream.php
- remove images migration;
- reinstall module ( php artisan module:reinstall products )
- create product, try attaching variant (slug: test)
- no error! 

Thank you

**Comment by calebsmithdev** [comment]
Similar issue that I am having: #4453 - I thought it was a grid issue, but it must be a repeater issue.

**Comment by calebsmithdev** [comment]
@RyanThompson any feedback on this issue? Anything that I can look into?

**Comment by huglester** [comment]
not yet @Failcookie 
But hopefully something today will happen!

**Comment by calebsmithdev** [comment]
Copying this over from Slack for reference: Xdebug was causing the white screen with Files/File/Image FT added to a repeater. Uninstalling Xdebug fixed the issue, but I am guessing that isn’t a solid fix.

**Comment by calebsmithdev** [comment]
Possibly driven by this: https://stackoverflow.com/questions/4293775/increasing-nesting-function-calls-limit.


Server setup issue.

**Comment by huglester** [comment]
Okay, so the problem is with XDEBUG nesting level.
No need to disable xdebug.
In my setup I changed it to 500.

current xdebug.ini is:
```
$ cat /etc/php/7.0/mods-available/xdebug.ini
zend_extension=xdebug.so
xdebug.max_nesting_level = 500
```
after changes, make sure you restart php-fpm.
