### ISSUE TITLE
[SEO - Feature Request] Counter or meta description and page title

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4457]
How about adding a counter to meta description and page title? Just to show how many characters you have written. It would be very helpful and should be simple to add since we already have counters for text and input fields.

**Comment by RyanThompson** [comment]
There is support for count and "suggested" length as well as "too long" length without failing validation too. What's best practices for these numbers?

**Comment by ghost** [comment]
I think recommendations made by these guys are a good rule of thumb:

Title: Max 50-60 Chars
Meta Description: Max 60-160

https://moz.com/learn/seo/title-tag
https://moz.com/learn/seo/meta-description

**Comment by ghost** [comment]
@RyanThompson Is this something you are planning to add in? Or should i do it manually where needed?

**Comment by Piterden** [comment]
Fix you

**Comment by Pixney-William** [comment]
Description is now up to 320 characters sometimes @RyanThompson .. fyi

**Comment by Pixney-William** [comment]
Closing this. If we need it we could just write a migration for it. And a better solution would be to develop a SEO extension for pyro with this information.
