### ISSUE TITLE
[streams-platform] SetLocale Middleware overriding locale setting even if alread set

### ISSUE THREAD

**Issue by lachieh** [pyrocms/pyrocms#4458]
The new(ish) `Anomaly\Streams\Platform\Http\Middleware\SetLocale` middleware overrides the locale for anything else that may have already set it. For example, the https://github.com/mcamara/laravel-localization package will set the locale from the 'Accept-Language' Header. This new middleware will override this setting.

One option would be to include [the logic from the laravel-localization package](https://github.com/mcamara/laravel-localization/blob/master/src/Mcamara/LaravelLocalization/LanguageNegotiator.php#L75). The other would be to set the config locale from the default stream elsewhere earlier in the process and never override the locale in the middleware unless it matches those rules.

Hope I'm making sense. I can give examples if necessary.

**Comment by RyanThompson** [comment]
Hmmm.. We just need this section then? https://github.com/mcamara/laravel-localization/blob/master/src/Mcamara/LaravelLocalization/LanguageNegotiator.php#L75-L81 <https://github.com/mcamara/laravel-localization/blob/master/src/Mcamara/LaravelLocalization/LanguageNegotiator.php#L75-L81>

**Comment by lachieh** [comment]
I reckon that'd do it! Looks like it's checking for a `Locale` class which I think is defined in that package.

Pyro already supports the locale prefix on all routes, yes?
