### ISSUE TITLE
[translator-module] System translation not working

### ISSUE THREAD

**Issue by kiger** [pyrocms/pyrocms#4459]
If I open the System translation page this is the error message:
![image](https://user-images.githubusercontent.com/2277562/28033689-588275fc-65af-11e7-9ec3-4ec2d3c2cdc5.png)

Workaround:
```
if(is_string($value)){
$translations[$file][$key][$locale] = html_entity_decode($value, ENT_QUOTES);
}
```

**Comment by RyanThompson** [comment]
This has been fixed

**Comment by Piterden** [comment]
Could you please show how and where?
