### ISSUE TITLE
[streams-module] Illegal string offset

### ISSUE THREAD

**Issue by kiger** [pyrocms/pyrocms#4461]
After i cerated the namespace some field (in the example only string), the stream and i try to add an entry this error message is "Illegal string offset and whatever is the slug to the field.
![image](https://user-images.githubusercontent.com/2277562/28036790-9e2cbe00-65b9-11e7-9f93-b9e62642f0ce.png)

**Comment by RyanThompson** [comment]
Can you check your namespaces in the service provider? And see if there is any malformed classes in there? There was briefly an issue where the generator was not parsing 100%. Maybe show some codez?

**Comment by kiger** [comment]
After the streams-platform  v1.2.345 update it works without modificating anything so i think its solved.
