### ISSUE TITLE
[Localization] Problem with paths / urls

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4465]
I have this image on my server. It shows without the local in the url. But throws a 404 with the local in it. This is a problem when i use grids, and file-field_type. Since it generates different urls and the ones with the local in em doesn't work.

https://pixney.com/sv/ms-icon-310x310.png
https://pixney.com/ms-icon-310x310.png

I am using file.. with grids.. and i am getting the file url by : `<img src="{{section.file.url}}" alt="">` (edited)

[12:03] 
Works fine with the default language.. but with the seondary languge the urls fucks up
[12:04] 
**Works** `https://pixney.com/app/pixney/files-module/local/news/summer2017meetup_large.gif`

**Does not work** `https://pixney.com/sv/app/pixney/files-module/local/news/summer2017meetup_large.gif`

**Comment by RyanThompson** [comment]
This has been fixed it looks like.
