### ISSUE TITLE
[videos] New video tutorials!

### ISSUE THREAD

**Issue by myshoeshurt** [pyrocms/pyrocms#4466]
To start off, I had considerable difficulties creating a custom ajax contact form with captcha (yes, i guess this is beginners :) ). 

Please add your suggestions for new videos here!

**Comment by huglester** [comment]
1. Overwriting some concept of core would be nice to see (like adding icon to navigation (if project requires it))

2. Maybe altering the pages module

3. Overriding login/registration process on frontend "best way" 

something along these lines would be nice to see :) 

I've done that personally but there is always a better  way :D

**Comment by calebsmithdev** [comment]
I would agree with @huglester. I would honestly prefer small short videos of how to do lesser known things than anything else. Like the topics mentioned above. From a beginning perspective - it would be even better to show some examples of how you manipulate Twig for core modules. Let's take the Posts module - how can I change the pagination by publishing the core files?

**Comment by myshoeshurt** [comment]
@huglester great idea - i would love to see that as well. @Failcookie or all of those tips can be combined in a big video. also a great idea!

**Comment by Piterden** [comment]
@myshoeshurt Just interesting, do you have some problems with captcha of AJAX form outside of PyroCMS?

**Comment by huglester** [comment]
overriding pagination is good question;)))
I currently override from thme service provider:
if (\Request::segment(1) !== 'admin') {
            AbstractPaginator::$defaultView = 'theme::partials/pagination';
        }
btw, pagination should be: pagination.blade.php :) 

---

short videos are good:
1. more chance to find probably? more topics and so on;
Pyro is really getting very good. just need to show it to people.

probably would be nice to see:
a) Middware setup?
currently overriding it via streams.php file:
```php
'Illuminate\Foundation\Http\Middleware\VerifyCsrfToken' => '\App\Http\Middleware\VerifyCsrfToken',
```

b) some example of HOW EASY it is to integrate/use some laravel lib. and use pyrocms only for backend/fronend stuff if needed. I think some people may get lost, that they can bind lots of laravel packages and attach backend to them in no time. (on of those packages I connected something like https://github.com/owen-it/laravel-auditing )

**Comment by myshoeshurt** [comment]
@Piterden - no. also inside of pyrocms already sorted. just suggesting what could be explained better :) and as @huglester suggested - there's always a better way :)

**Comment by calebsmithdev** [comment]
@myshoeshurt My only thing with long videos is just how "exhausting" they can be. Sometimes I use the videos for visual reference in projects and it can be pretty tiring to have to scrobble through a Vimeo video to find the right spot. I like the format of videos like Laracasts, where you have a series of videos that are in smaller snippet chunks. Easier to take in and less intimidating.

**Comment by myshoeshurt** [comment]
@Failcookie I am ok with any format, it is up to @RyanThompson to decide the length :)

**Comment by ghost** [comment]
Adding svg icons (inline ones) to the navigation

**Comment by ghost** [comment]
Sitemap tutorial for your own modules and stuff

**Comment by myshoeshurt** [comment]
quick and painless way to add a blog

**Comment by RyanThompson** [comment]
@myshoeshurt did you use the field type from the store by  chance? It should work fine with ajax forms. That’s such a solid plugin I use it often - and it’s cheap enough that it makes sense like.. no brainer  :-P

That would be my official suggestion though haha

**Comment by stijntilleman** [comment]
A video about overall performance tweaks would be much appreciated

**Comment by myshoeshurt** [comment]
@RyanThompson that's how I solved my problems. But it was sort of a tweaky hacky solution to make it work with an ajax form.

@stijntilleman great idea!

**Comment by calebsmithdev** [comment]
Mailables could be awesome. I know it will change in Laravel 5.5 (if we upgrade), but it would be nice to see some visuals on creating email notifications and email templates within Pyro. Maybe use some of the Pyro specific techniques that may not be common knowledge.

**Comment by myshoeshurt** [comment]
comment section / message board in pyro / log in area

**Comment by calebsmithdev** [comment]
Another good one! Widgets - Some basic walkthroughs and creating them and the how the system interacts with them.

**Comment by RyanThompson** [comment]
See articles for video links: https://pyrocms.com/help/developer-tools/extending-pyrocms

**Comment by RyanThompson** [comment]
- [ ] Overriding JS for inputs like WYSIWYG

**Comment by calebsmithdev** [comment]
Text or video tutorial - How $schedule works and how it can be utilized in projects. Basic sample would be best for now

**Comment by myshoeshurt** [comment]
text or video tutorial on the forum module

**Comment by Piterden** [comment]
Please, the only one porno would be cute :trollface:

**Comment by Piterden** [comment]
@Failcookie schedule is the array `cron => ::class`
