### ISSUE TITLE
[RFC] CLI addon status

### ISSUE THREAD

**Issue by lenvanessen** [pyrocms/pyrocms#4470]
Hi Ryan,

I was playing around with Pyro today, and I noticed that there is no way to check the status of the addons from the CLI. 

Ik would be great if we can have like a
`php artisan addon:status`

That returns a list with addon names, and whether they are installed or not. Great for looking up names or taking a quick peek without visiting the CMS.

**Comment by Piterden** [comment]
You could see it in the `addons-module` GUI

**Comment by lenvanessen** [comment]
@Piterden I know:) 

"Great for looking up names or taking a quick peek **without** visiting the CMS."

**Comment by Piterden** [comment]
Ya, that would be nice, I agreed.

**Comment by RyanThompson** [comment]
I like this - can just show all the same stuff the addon does

**Comment by Piterden** [comment]
Add-on's CLI GUI sounds good

**Comment by RyanThompson** [comment]
Addons module now supports this as of Pyro 3.7: https://github.com/anomalylabs/addons-module/commit/4df31ff513206c02e1351a6117c2537141f1a09f
