### ISSUE TITLE
[s3_adapter-extension] Wysiwyg editor should return remote URL.

### ISSUE THREAD

**Issue by abfadel** [pyrocms/pyrocms#4473]
When selecting a file from s3 storage in wysiwyg editor it should return the s3 url. Currently it returns local url on frontend.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/wysiwyg-field_type/commit/678357201f9154ca5ecdc6c4acfc7a872c710e4d

https://github.com/anomalylabs/wysiwyg-field_type/commit/07deec21e714c98e45ca372e8da36e5a05ae8e0d
