### ISSUE TITLE
Edit assignment URL is all jacked up!

### ISSUE THREAD

**Issue by Jameron** [pyrocms/pyrocms#4474]
When I click edit assignment I get a not found. Also after I delete one, it is showing back up later, something to do with soft-deletes maybe.

http://proofer.dev/admin/files/folders/assignments/admin/files/folders/assignments/4/assignment/1901
Maybe related:
When I click Add Row to my repeater I'm getting:
local.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getNamespace() on null in /Library/WebServer/Documents/daylight/proofer/vendor/anomaly/streams-platform/src/View/Twig/Loader.php:164

**Comment by Piterden** [comment]
Clean up your streams

**Comment by Jameron** [comment]
whats the command? this is after running artisan addon:reinstall

**Comment by Piterden** [comment]
`artisan sreams:refresh`

**Comment by Jameron** [comment]
thx!

**Comment by Jameron** [comment]
edit link still broken

**Comment by RyanThompson** [comment]
@jameron you all up to date? Both of these should be resolved.

**Comment by huglester** [comment]
ping @jameron
