### ISSUE TITLE
SVG Uploads

### ISSUE THREAD

**Issue by psaunders** [pyrocms/pyrocms#4477]
The uploader seems to be having trouble with SVG mime types.

![image](https://user-images.githubusercontent.com/424956/28239176-a46cea9c-6933-11e7-820f-d738e19572a6.png)

Won't upload:

```
<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48">
    <path d="M0 0h48v48h-48z" fill="none"/>
    <path d="M10 26.36v8l14 7.64 14-7.64v-8l-14 7.64-14-7.64zm14-20.36l-22 12 22 12 18-9.82v13.82h4v-16l-22-12z"/>
</svg>
```

Will upload:
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 21.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 48 48" style="enable-background:new 0 0 48 48;" xml:space="preserve">
<style type="text/css">
	.st0{fill:none;}
</style>
<path class="st0" d="M0,0h48v48H0V0z"/>
<path d="M10,26.4v8L24,42l14-7.6v-8L24,34L10,26.4z M24,6L2,18l22,12l18-9.8V34h4V18L24,6z"/>
</svg>
```

**Comment by Piterden** [comment]
Maybe its because SVG is XML?

**Comment by calebsmithdev** [comment]
The main concern is probably just security, right? I feel like I remember seeing a lot of discussion around SVG uploads in the community and doing some upfront scanning to keep out the harmful code.

**Comment by psaunders** [comment]
Yeah, public uploading is such a common source of hacks. And SVGS make it pretty easy to write whatever you want into them, you could pretty easily get developers into trouble.

The first step here though would be getting the error message to actually tell you what is up. It seems to me that it's an issue with the compressed SVG format not having a prolog, if the error said that at least users could fix it.
