### ISSUE TITLE
Error Number: 1146  Table 'pyrocms.default_permissions' doesn't exist

### ISSUE THREAD

**Issue by gabgitt** [pyrocms/pyrocms#4479]
i just installed pyro cms on my machine. The installation went well but i couldn't login afterwards. I got this as the message  
A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: models/ion_auth_model.php

Line Number: 86

A Database Error Occurred
Error Number: 1146

Table 'pyrocms.default_permissions' doesn't exist

SELECT * FROM `default_permissions` WHERE `group_id` = '1'.

I am very new to pyro. I will appreciate any guidance. Thanks

**Comment by stockhausen** [comment]
please which version of pyroCMS ?

**Comment by ikoniqoz** [comment]
This looks like Pyro 2.x  If so, you need to use the 2.2 Develop version - https://github.com/pyrocms/pyrocms/tree/2.2/develop

**Comment by gabgitt** [comment]
@stockhausen , The version is 2.2.5

**Comment by ikoniqoz** [comment]
@gabgitt  OK - PyroCMS 2.2.5 was the last of the 2.x line and is very stable. Please make sure you have a fresh copy from the 2.2 Develop repo as mentioned above and try a fresh install again.

**Comment by gabgitt** [comment]
I encountered the same problem with the cloned 2.2 dev version.
This is what i got when i tried to login to the admin panel
A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: models/ion_auth_model.php

Line Number: 86

A Database Error Occurred
Error Number: 1146

Table 'pyrocms.default_permissions' doesn't exist

SELECT * FROM `default_permissions` WHERE `group_id` = '1'

Does this has to do with my system configuration or what? Please help. Thanks

**Comment by ikoniqoz** [comment]
@gabgitt ::  OK - I have downloaded a fresh copy of the PyroCMS 2.2.5 Dev and installed it and it all works correctly.
Can I suggest that there is no issue concerning the installation of PyroCMS 2.2.5 and ask you to try the Forums / General  ( https://pyrocms.com/forum/channels/general ) section and we can take it up there. Your problem may be related to your development environment. 
@RyanThompson  may close this Issue shortly.

**Comment by gabgitt** [comment]
All right. Thanks @ikoniqoz

**Comment by gabgitt** [comment]
I uncomment    extension=php_sqlite3.dll    in my php.ini, then did a fresh installation via composer. The installation went through successfully but the view is very different from what i was expecting. When i accessed it through my browser, i could see the directory listing of pyroCMS application instead of an installation page which i was expecting. I tried visiting the admin page as well but error 404 was thrown.

**Comment by ikoniqoz** [comment]
@gabgitt  Can I suggest again that you post to the Forum as suggested above.   The problem you are encountering is not an issue with PyroCMS.  Please include all details of your development environment and which version of PyroCMS you wish to explore. From your last post it may be that you have attempted to install PyroCMS v3 - not v2.2.5 as initially discussed.
