### ISSUE TITLE
[Documentation] [Ajax-Forms] Errors in documentation write up

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4484]
On this page:
https://pyrocms.com/help/developer-tools/form-builders/defining-custom-ajax-forms-in-twig

You are not setting the form `{% set form =... %}`

and you are not closing it with `%}`

**Comment by Piterden** [comment]
Fixed. Thanx)

**Comment by ghost** [comment]
Also...

This works : `{{ form.open({'class':'ajax'})|raw }}` but not the example: `{{ form.open({'class': 'ajax'}).get() }}`

**Comment by ghost** [comment]
Wrong video id here : 
https://pyrocms.com/videos/series/form-builders/defining-custom-ajax-forms-in-twig-part-2

**Comment by Piterden** [comment]
There is the mistake in the matcher:
https://github.com/anomalylabs/video-field_type/pull/7

**Comment by Piterden** [comment]
Also... fixed too
