### ISSUE TITLE
[Documentation] We need to split up the documentation

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4486]
Especially this page of the documentation takes far too long to load. I think we need to look into splitting it up to make it more effective.

https://pyrocms.com/documentation/streams-platform/v1.1#services/asset/basic-usage/asset-add

**Comment by Piterden** [comment]
Excuse me github.

F**k, we need docs in a normal doc system!!!

**Comment by Youhan** [comment]
How are the docs maintained already?

**Comment by Piterden** [comment]
There are 2 Pyro modules: the Help module and the Documentation module.

**Comment by RyanThompson** [comment]
Docs are being overhauled right now. Splitting up is definitely one of the steps being taken. Overall better organization.
