### ISSUE TITLE
[Forms-Module] Add ability to do something with a form request

### ISSUE THREAD

**Issue by lachieh** [pyrocms/pyrocms#4488]
This is a feature request.

I've got a situation where I need to handle the cookies from a form request and do something extra (send the form details to a CRM via an API) whenever a form is submitted.

It'd be great to be able to hook into a form submission, while still having access to the original request, so that we can create extensions that handle extra completion actions like create jobs, 3rd party notifications, etc

**Comment by Piterden** [comment]
But there is something, I am sure. Don't know, how it interacts with the forms module, but there should be 'saving' and 'saved' events on each formbuilder.

**Comment by lachieh** [comment]
That's pretty close to what I'd be looking for. Like a `Event::listen('forms_module.saving', func...` or something? Or would it need to be attached to a specific form?

Would I be able to access the original request?

**Comment by Piterden** [comment]
request();

No?

**Comment by RyanThompson** [comment]
There are form handlers you could use to do this (extensions) - which is what we tend to do when we need such a thing.

But I agree some lighter solutions like an event would be nice.
