### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4490]

**Comment by Youhan** [comment]
Besides RTL, I think it is a good idea to have a **font-face field type**. It could handle some free and paid font embedding services like below and include the font style to the page.

- [Google Fonts](https://fonts.google.com/)
- [Typekit](https://typekit.com/)
- [Edge Web fonts](https://edgewebfonts.adobe.com/)

**Comment by mustafa-online** [comment]
@RyanThompson .. are we going to see this in **PyroCMS v4** ?? 
Bootstrap 5 is already supports RTL.
