### ISSUE TITLE
[Video Field Type] Issue with YouTube video IDs

### ISSUE THREAD

**Issue by Cleancookie** [pyrocms/pyrocms#4492]
Videos with non alpha-numeric IDs such as `https://www.youtube.com/watch?v=YE7VzlLtp-4` seem to incorrectly get `YE7VzlLtp` as the video ID as opposed to `YE7VzlLtp-4`

Links with only alpha-numeric IDs seem to work fine: `https://www.youtube.com/watch?v=katIJ9Oabb8`.

**Comment by Piterden** [comment]
Are there the official rules of video naming?

**Comment by Cleancookie** [comment]
Not that I can find, closest I found was `https://developers.google.com/youtube/v3/docs/videos` where it just says it's a string but I've only ever seen alphanumeric characters (upper and lower case) with - or _

**Comment by Piterden** [comment]
https://stackoverflow.com/questions/44801861/regex-for-youtube-and-vimoe-url

**Comment by Cleancookie** [comment]
A promising looking fix here [anomalylabs/video-field_type](https://github.com/anomalylabs/video-field_type/pull/6)

**Comment by RyanThompson** [comment]
This has been resolved.
