### ISSUE TITLE
[users-module] search field gets focus on create/edit user

### ISSUE THREAD

**Issue by squatto** [pyrocms/pyrocms#4493]
Every time I create a new user or edit an existing user, the focus jumps to the search bar and the nav list drops down. I checked in form.js and I can't see any reason for it. It only happens on the user create/edit (that I've seen so far).

Here's a video of it happening: https://www.dropbox.com/s/xta5pc6o9q1qv6l/search%20glitch.mov?dl=0

**Comment by RyanThompson** [comment]
I believe this was fixed.
