### ISSUE TITLE
[ALARMA] Error after install

### ISSUE THREAD

**Issue by web812** [pyrocms/pyrocms#4494]
Can not launch after install

Symfony\Component\Debug\Exception\FatalErrorException thrown with message "Method Anomaly\Streams\Platform\Image\Image::__toString() must not throw an exception, caught ErrorException: filemtime(): stat failed for /home/smkmn/github/pyro.dev/public/app/default/assets//187057d83e4ff51f25cba86bd0afdaad."

Stacktrace:
#0 Symfony\Component\Debug\Exception\FatalErrorException in /home/smkmn/github/pyro.dev/vendor/twig/twig/lib/Twig/Extension/Core.php:0

![screenshot from 2017-07-27 17-51-14](https://user-images.githubusercontent.com/15962774/28676785-412c2b94-72f4-11e7-90a0-631d84c0ce3a.png)

[terminal.txt](https://github.com/pyrocms/pyrocms/files/1180344/terminal.txt)

**Comment by mfairch** [comment]
Fresh install, I get this as well.

**Comment by Piterden** [comment]
me too

**Comment by RyanThompson** [comment]
This has been resolved - sorry! Stupid issue with Favicons..

**Comment by Piterden** [comment]
You have lost one client causing of that err
