### ISSUE TITLE
[core] Scout indexes not updating on model update

### ISSUE THREAD

**Issue by squatto** [pyrocms/pyrocms#4495]
I have Scout connected to Algolia, and when I update a model, the Algolia index isn't updated for the model:

<img width="252" alt="screen shot 2017-07-27 at 1 46 29 pm" src="https://user-images.githubusercontent.com/748444/28689215-172c084a-72d2-11e7-8632-0eec0518c384.png">

After saving that change, this is my Algolia index value:

<img width="322" alt="screen shot 2017-07-27 at 1 49 03 pm" src="https://user-images.githubusercontent.com/748444/28689296-647ab0b0-72d2-11e7-8830-132a16f6143f.png">

Scout is configured correctly - I can run `artisan scout:import` and the models update correctly.

**Comment by RyanThompson** [comment]
Is your stream marked as searchable?

**Comment by squatto** [comment]
I assumed that the fact that they all `use Searchable`, that they would be. Is there a `searchable` attribute that needs to be flagged on the stream?

**Comment by RyanThompson** [comment]
@squatto so the base EntryModel uses that trait inherently - so just do this on your entry model (or flag the stream definition):

`protected $searchable = true;`

**Comment by RyanThompson** [comment]
That should resolve your issue - open er back up if not ^_^

**Comment by vargvinter** [comment]
I have connected Elasticsearch with Scout but indexes for my models are not updated. 
As @squatto said `artisan scout:import {model}` works fine for me as well but when I update the model index in Elasticsearch is not updated.
Moreover core Pyro models (like Post, Page, User) work great - index in ES is updated. 
My models have flag `searchable` set to `true`.
I am not sure what I am doing wrong. 

Pyro 3.6
Elasticsearch 5.6.15
Package for scout: tamayo/laravel-scout-elastic:~3

@squatto - did you solve your problem?

EDIT: I was doing some unit tests and when I do something like this:
```php
$model = factory(MyModel::class)->make();

$model->save();
```
index is updated.

But on saving the form (via browser) it does not work.

**Comment by RyanThompson** [comment]
Are you leveraging observers at all? Make sure that observers continue the call to the `parent::` so that deeper parts of automation in streams can work.

**Comment by vargvinter** [comment]
You mean `{ModelName}Observer` class created after scaffolding  the stream?
I have got something like this:

```php
<?php 

namespace Acme\CatalogsModule\Folder;

use Anomaly\Streams\Platform\Entry\Contract\EntryInterface;
use Anomaly\Streams\Platform\Entry\EntryObserver;
use Acme\CatalogsModule\Folder\Command\DeleteDirectory;
use Acme\CatalogsModule\Folder\Command\SetIdPath;
use Acme\CatalogsModule\Folder\Command\SetPath;
use Acme\CatalogsModule\Folder\Command\UpdatePaths;

class FolderObserver extends EntryObserver
{
    /**
     * @param EntryInterface $entry
     */
    public function saving(EntryInterface $entry)
    {
        $this->dispatch(new SetPath($entry));

        parent::saving($entry);
    }

    /**
     * @param EntryInterface $entry
     */
    public function saved(EntryInterface $entry)
    {
        $this->dispatch(new UpdatePaths($entry));

        // Fired after save, because we need folder id.
        $this->dispatch(new SetIdPath($entry));

        parent::saved($entry);
    }

    /**
     * @param EntryInterface $entry
     */
    public function deleted(EntryInterface $entry)
    {
        $this->dispatch(new DeleteDirectory($entry));

        parent::deleted($entry);
    }
}
```

Is something wrong here?

As I said firing `$myModelFromMyModule->save()` **works**.
Updating/creating some core module model via form in browser (Page, Post, User, etc) **works**.
Updating/creating my module model via form in browser **does not work**.

Maybe in `FormBuilder` is something wrong?

```php
<?php 

namespace Acme\CatalogsModule\Folder\Form;

use Anomaly\Streams\Platform\Ui\Form\FormBuilder;
use Exception;
use Acme\CatalogsModule\Folder\Command\CreateDirectory;
use Acme\CatalogsModule\Folder\Contract\FolderInterface;

class FolderFormBuilder extends FormBuilder
{
    /**
     * The parent folder.
     *
     * @var null|FolderInterface
     */
    protected $parent = null;

    /**
     * The form fields.
     *
     * @var array|string
     */
    protected $fields = [];

    /**
     * Additional validation rules.
     *
     * @var array|string
     */
    protected $rules = [];

    /**
     * Fields to skip.
     *
     * @var array|string
     */
    protected $skips = [
        'parent',
        'path'
    ];

    /**
     * The form actions.
     *
     * @var array|string
     */
    protected $actions = [];

    /**
     * The form buttons.
     *
     * @var array|string
     */
    protected $buttons = [
        'cancel',
    ];

    /**
     * The form options.
     *
     * @var array
     */
    protected $options = [];

    /**
     * The form sections.
     *
     * @var array
     */
    protected $sections = [
        'folder' => [
            'tabs' => [
                'general' => [
                    'title'  => 'acme.module.catalogs::tab.general',
                    'fields' => [
                        'folder_name',
                        'folder_slug',
                        'security',
                    ],
                ],
                'additional' => [
                    'title'  => 'acme.module.catalogs::tab.additional',
                    'fields' => [
                        'expand_on_click',
                        'countries'
                    ],
                ],
            ],
        ],
    ];

    /**
     * The form assets.
     *
     * @var array
     */
    protected $assets = [];

    /**
     * Fired just before saving the form.
     * @throws Exception
     */
    public function onSaving()
    {
        $entry = $this->getFormEntry();
        $parent = $this->getParent();

        $folderSlug = $this->getFormField('folder_slug')->getValue();

        if ($this->getFormMode() === 'create') {
            $result = $this->dispatch(new CreateDirectory($folderSlug, $parent));

            if (!$result) {
                throw new Exception('Create directory error');
            }
        }

        if ($parent) {
            $entry->parent_id = $parent->getId();
        }
    }

    /**
     * @param FolderInterface $folder
     * @return FolderFormBuilder
     */
    public function setParent(FolderInterface $folder): self
    {
        $this->parent = $folder;

        return $this;
    }

    /**
     * @return FolderInterface|null
     */
    public function getParent(): ?FolderInterface
    {
        return $this->parent;
    }
}
```

**Comment by RyanThompson** [comment]
You mention unit testing - is that the context in which you are experiencing this issue? Or just normal usage in your addon? Can you try flagging it as searchable in the DB and recompiling?

**Comment by vargvinter** [comment]
Normal usage.
Anyway, I have reinstalled module locally and it started indexing. Strange behaviour...
What should I do on production? I just can't reinstall module because of all the data I have.

EDIT: 
Issue still occurs.
Here is the scenario:
When I import models via `php artisan scout:import 'Model'` and then I update one of the imported models changes are not reflected in Elasticsearch.

When I create record via browser (normal usage in Admin Panel) the model is imported to the Elasticsearch and updates are reflected in Elasticsearch as well.
