### ISSUE TITLE
[ accelerant-theme ] includes the Bootstrap twice

### ISSUE THREAD

**Issue by Youhan** [pyrocms/pyrocms#4497]
Hi, 
I noticed that the accelerant theme is including the Bootstrap twice. One at the theme.css file and another time at the build.css file

![screen shot 2017-07-29 at 2 19 25 pm](https://user-images.githubusercontent.com/2191898/28743834-096191d8-7469-11e7-99fa-d895c48252d2.png)

![screen shot 2017-07-29 at 2 19 40 pm](https://user-images.githubusercontent.com/2191898/28743835-0962bd9c-7469-11e7-9b5c-0fe49118abde.png)

### The Fix:

The fix would be to remove the call from `metadata.twig` partial view.  since the `theme.scss` is including it.

**Comment by RyanThompson** [comment]
Good find! Fixed: https://github.com/pyrocms/accelerant-theme/commit/ac35d678147dd09d5a8c0f174773b838f5293fe4

**Comment by Piterden** [comment]
JAVASCRIPT should do that job
