### ISSUE TITLE
[streams-platform] Make the same behaviours of save hotkeys

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4498]
In the create mode of a form, pressing of the CTRL+s hotkey would reload the page to table. But in the edit mode it would just reload page on the same form.

It is wrong behaviour, there should be a consistency in hotkeys actions on different pages.

**Comment by RyanThompson** [comment]
There is a consistency - Ctrl + S saves using FIRST save action - adding shift uses second save action. Save actions are different per create/edit forms.

**Comment by Piterden** [comment]
Okay, so change places of that buttons.

**Comment by Piterden** [comment]
It was the amazing excuse
