### ISSUE TITLE
Override a theme by another theme

### ISSUE THREAD

**Issue by Youhan** [pyrocms/pyrocms#4499]
There is a situation that you like a theme and you want to use it. But you just want to do a little tweak on it. For example, I really like the accelerant theme for admin but I would like to change some CSS or JS or maybe add a font-face. What can I do?

- Clone the repo, do my edits, and have my own loaded with composer
- Make a new theme that basically inherits everything from the accelerant theme and then also extends it.
- Or maybe we can already make a theme extension, that I am not aware of?

**Comment by RyanThompson** [comment]
Any of those are viable options.

For example your extension could add a stylesheet to styles.css on every admin load and override that way.. You can also load variables into the compilers

**Comment by RyanThompson** [comment]
More of a forum discussion :-P
