### ISSUE TITLE
[streams-platform] streams plugin trans() should return rendered html

### ISSUE THREAD

**Issue by benrogmans** [pyrocms/pyrocms#4503]
Considering that translation lines should be stored escaped (https://github.com/pyrocms/pyrocms/issues/4502),

I think translated lines can be trusted by default and we shouldn't have to use the twig |raw filter for every translation.

Basically what I'm proposing is:

```
  new \Twig_SimpleFunction(
      'trans',
      function ($key, array $parameters = [], $locale = 'en') {
          return $this->dispatch(new GetTranslatedString($key, $parameters, $locale));
      },
      array('is_safe' => array('html'))
 ),
```

I'll create a PR for it to be forthcoming but I'd like to know your thoughts, @RyanThompson :)

**Comment by RyanThompson** [comment]
This won't work because it's possible to `trans($nasty)` and `$nasty` will be trusted since the key can't be found.
