### ISSUE TITLE
[all-addons] Remove meta_keywords

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4505]
- [x] Posts
- [x] Pages
- [x] Videos
- [x] Products

**Comment by Piterden** [comment]
Wait, the five years have not yet passed!!!

**Comment by huglester** [comment]
You want to remote from migration/streams
or you want to write UP migration which would remove them? (I don't see this nescessary), simply changing migrations probably would be enought.

Leave keywords for people who already have them?

**Comment by Piterden** [comment]
But keywords not working anymore. Searching engines, just not read em. You could remove all.

**Comment by RyanThompson** [comment]
And they're used within the API which would break - which is why I've bumped versions for everything removing them.
