### ISSUE TITLE
PostgreSQL install error

### ISSUE THREAD

**Issue by ngscheurich** [pyrocms/pyrocms#4506]
I’m running into an error while trying to install PyroCMS with PostgreSQL. The error I’m getting from the installer web interface is:

> Error (500) - Please check your application error logs.

Checking my log at `storage/logs/laravel-*.log` reveals the following:

> `[2017-07-31 12:54:57] local.ERROR: PDOException: SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "unique-relations" already exists in /home/vagrant/pyrocms-heroku/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105`

I’m currently trying to install PyroCMS on v6.0.0 of the [Laravel Homestead](https://laravel.com/docs/5.4/homestead) Vagrant box, with the intention of eventually deploying to Heroku.

**Comment by Piterden** [comment]
You need to rename so of them

**Comment by ngscheurich** [comment]
Thanks for chiming in, @Piterden! I'm not sure I completely follow, though. Do I need to go in and manually rename some database columns? If so, in the PHP app or in the database?

**Comment by Piterden** [comment]
https://github.com/anomalylabs/multiple-field_type/pull/26
https://github.com/anomalylabs/files-field_type/pull/15

All these changes have already done

**Comment by Piterden** [comment]
But @RyanThompson ...

**Comment by ngscheurich** [comment]
Cheers, @Piterden; your patches worked like a charm.

**Comment by Piterden** [comment]
Of course ))

Don't forget about pg has lesser max allowed length of table names. So don't use too long names of your models slugs

**Comment by RyanThompson** [comment]
Merged and closing
