### ISSUE TITLE
[Accelerant Theme] Toggle switches are going above the thead

### ISSUE THREAD

**Issue by calebsmithdev** [pyrocms/pyrocms#4507]
Toggle switches have a z-index and are going above the <thead> on the tables in the admin. Need to assign a z-index to the <thead>.

**Comment by Piterden** [comment]
It's accelerant related issue

**Comment by calebsmithdev** [comment]
Addressed this in the theme field: https://github.com/pyrocms/accelerant-theme/pull/35
