### ISSUE TITLE
How to change the post status

### ISSUE THREAD

**Issue by CMJaefarsadikh** [pyrocms/pyrocms#4508]
![error](https://user-images.githubusercontent.com/24778052/28824618-731987c4-76e0-11e7-8ee4-f71d31358d6f.jpg)

**Comment by RyanThompson** [comment]
Enable the post in the options tab while editing it. If the post_at time is future it will be `scheduled` - and finally live when both status are enabled and post_at time is met (so you can schedule out posts).

**Comment by CMJaefarsadikh** [comment]
thank you sir. i have another question .How to create CRUD Module in the
Dash board

**Comment by Piterden** [comment]
https://gitlab.com/snippets/1666857

**Comment by CMJaefarsadikh** [comment]
error

**Comment by CMJaefarsadikh** [comment]
Error
![untitled-2](https://user-images.githubusercontent.com/24778052/28862247-f92dcd06-7781-11e7-80a0-0fda22b21579.jpg)

**Comment by Piterden** [comment]
You need to set migrations and install module before.

**Comment by Piterden** [comment]
Also to read the docs will not be bad
