### ISSUE TITLE
[wysiwyg-field_type] Updated Redactor to fix image resizing issue

### ISSUE THREAD

**Issue by calebsmithdev** [pyrocms/pyrocms#4512]
We are currently using version 2.5.

In version 2.7, Redactor updated their plugin to fix some weird image resizing issues that happen in the content editor. Most notable around shrinking images that are over 800px and breaking the original ratio. This should also fix some issues with moving images around for proper placement.

Latest release is 2.8.1

**Comment by RyanThompson** [comment]
Done
