### ISSUE TITLE
exception template ("Expected ')' got '.' in anonymous-file-412.less

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#4515]
Hello,

so I can navigate everywhere in backend (where I tried).
But when trying to edit a user:
/admin/users/edit/1
I get this:
```php
An exception has been thrown during the rendering of a template ("Expected ')' got '.' in anonymous-file-412.less") in "theme::partials/assets" at line 1.
```

Any ideas?

accelerant-theme version: v1.0.68

tried clearing caches:
```php
php artisan view:clear && php artisan route:clear && php artisan cache:clear && php artisan clear-compiled && php artisan optimize && php artisan assets:clear
```

Thanks

**Comment by Piterden** [comment]
We need the song of the brave warrior about Assetic))))

**Comment by huglester** [comment]
I believe it is connected to comilation of assets...I went to core/ folder and run:

```bash
$ sass-lint '**/**/*.scss'

/usr/lib/node_modules/sass-lint/index.js:313
    throw new exceptions.SassLintFailureError(errorCount.count + ' errors were detected in \n- ' + errorCount.files.join('\n- '));
    ^
SassLintFailureError: 2 errors were detected in 
- pyrocms/accelerant-theme/resources/scss/bootstrap/mixins/_forms.scss
- pyrocms/pyrocms-theme/resources/scss/bootstrap/mixins/_forms.scss
    at Function.sassLint.failOnError (/usr/lib/node_modules/sass-lint/index.js:313:11)
    at detectPattern (/usr/lib/node_modules/sass-lint/bin/sass-lint.js:31:10)
    at /usr/lib/node_modules/sass-lint/bin/sass-lint.js:83:5
    at Array.forEach (native)
    at Object.<anonymous> (/usr/lib/node_modules/sass-lint/bin/sass-lint.js:82:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```
as you can see thow files are complaining

**Comment by robinvoor** [comment]
I had something similar with my pages module.

Have you tried the following:
Switch in the .env file 'installed' to 'false' and execute: `php artisan stream:compile`. After that, switch in .env 'installed' to 'true' again.

**Comment by huglester** [comment]
Just tried this, no luck :(

**Comment by huglester** [comment]
@RyanThompson maybe you have ideas, what to clean? whom to remove? :D

**Comment by jfchaput** [comment]
I got the same issue. I added a File field into a Post Type and after I got this issue when I try to Add or Edit a Post

**Comment by huglester** [comment]
What field type was it? Does removing the field type solves the issue?

**Comment by jfchaput** [comment]
It was a File field. I tried to remove it but the issue still there.

**Comment by huglester** [comment]
@jfchaput maybe you happen to solve this?

**Comment by huglester** [comment]
Hello,

so with big help from @RyanThompson I've tracked this down.
So the problem was with the .less file in the multiple-field_type.

But in the end, it was not the problem with the field type, but the 'streams-platform' version and field type version.

Since this project was an upgrade, probably some pages were missed upgrading in composer.json.
so now I have updated them:
```php
"anomaly/relationship-field_type": "~2.2.0",
"anomaly/checkboxes-field_type": "~2.2.0",
"anomaly/language-field_type": "~2.2.0",
"anomaly/multiple-field_type": "~2.2.0",
"anomaly/editor-field_type": "~2.2.0",
"anomaly/select-field_type": "~2.2.0",
```

cleared caches etc, and problem is gone.
Please try your luck @jfchaput 

A 'good' example of composer file is located here (for version 3.3.) 
https://github.com/pyrocms/pyrocms/blob/3.3/composer.json
