### ISSUE TITLE
[Bug] As a guest i am able to view the preview posts.

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4518]
The role Guest should not be able to view the post preview url. This has caused preview urls to be indexed by Google.

**Comment by ghost** [comment]
Im on posts module 2.2.27

**Comment by Piterden** [comment]
I think you need to update

**Comment by huglester** [comment]
I think we need some option to pass the 'noIndex' parameter from the controller.
so if the URL is the preview one, those wont' be indexed.

As i know preview url is not 'protected' by auth users in any way, they are protected by HASHed url.

**Comment by Piterden** [comment]
Previewed shouldn't be accessible.
`noIndex` option you could easily create like a field for the page

**Comment by RyanThompson** [comment]
Also check that your config is not published which powers permissions - could be overridden.

Closing this for now - I've not been able to replicate.
