### ISSUE TITLE
[streams-platform] Do we need Assetic AutoprefixerFilter?

### ISSUE THREAD

**Issue by Youhan** [pyrocms/pyrocms#4519]
I was using SCSS in my theme and came to this issue of auto-prefixing. I thought it would be nice if we could leverage the [AutoprefixerFilter](https://github.com/kriswallsmith/assetic/blob/master/src/Assetic/Filter/AutoprefixerFilter.php) provided by Assetic.

Also, I noticed that the Accelerant Theme is also compiling the Bootstrap from SCSS files without prefixing them.

**Comment by RyanThompson** [comment]
PR me! Bootstrap should only be compiled once now since your last issue posted / was fixed.

**Comment by Youhan** [comment]
@RyanThompson I am sorry, I could not understand your reply :(

What I tried to explain is that:
The Problem:
The compiler of the SCSS at Pyro does not auto-prefix the CSS. Does it?

Evidence: 
Look at the compiled Bootstrap CSS. There is no `-moz` or `-ms`

**Comment by RyanThompson** [comment]
Can you spin up a copy of 3.4 and test this out? https://github.com/anomalylabs/streams-platform/commit/19abfb41deb36312e2707551515a30288d74a427

**Comment by RyanThompson** [comment]
`autoprefix` is the filter flag - I think it requires a node dependency or something so I can't enable it by default.

**Comment by Youhan** [comment]
Yes, I did a research and it needs Node and to include the autoprefixer binary file which it seems that the autoprefixer itself has removed the binary from the repo. 
 
At the moment the only option for the binary I found is to install the [autoprefixer-cli](https://github.com/ai/autoprefixer-cli) which is not an official version I guess. I haven't tried it yet to see if that binary actually works.

Have you found the right binary file for this?

**Comment by Youhan** [comment]
> Can you spin up a copy of 3.4 and test this out? anomalylabs/streams-platform@19abfb4

@RyanThompson 
I tested that and here are my results.

### For me at least it didn't work until I made this change:
in `Assetic\Filter\AutoprefixerFilter@filterLoad` I had to add Environment Variable like so to get it work otherwise it throws exemption telling that the node directory could not be found:
```
$proc->setEnv(array(
      'PATH' => '/usr/local/bin' //Path to node bin dir
));
```

### Using [autoprefixer](https://github.com/postcss/autoprefixer) binary: 
Since the last binary has been published with v2.2.0 I had to install that version using:
```
npm install autoprefixer@2.2.0 --save
```
and so the `.env` file will have this: 
```
AUTOPREFIXER="/{base_path}/node_modules/autoprefixer/bin/autoprefixer"
```
Here is the source scss:
```
.example {
  display: flex;
  transition: all .5s;
  user-select: none;
  background: linear-gradient(to bottom, white, black);
}
```
and the compiled result:
```
.example {
  display: -ms-flexbox;
  display: flex;
  transition: all 0.5s;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  background: linear-gradient(to bottom, white, black); }
```
### Using [autoprefixer-cli](https://github.com/ai/autoprefixer-cli) binary: 
I had it globally installed using
```
npm install --global autoprefixer-cli
```
and so the `.env` file will have this: 
```
AUTOPREFIXER="/usr/local/bin/autoprefixer-cli"
```
and the compiled result:
```
.example {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  transition: all 0.5s;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  background: linear-gradient(to bottom, white, black); }
```

**Comment by RyanThompson** [comment]
Which would be easier to deploy do you think? Do you have a preference?

**Comment by Youhan** [comment]
I am not sure actually. The autoprefixer is at v7.1.2 and the autoprefixer-cli was last updated 2 years ago and says: 

> CLI tool for Autoprefixer. The official way to use Autoprefixer is postcss-cli, this tool is for legacy code.

Seems that people don't use this approach anymore. After all, this is also using Node and why not use webpack/gulp/grunt then? except it wouldn't do on the fly CSS compiling.

**Comment by RyanThompson** [comment]
I think we'll leave these to webpack type tools.

**Comment by Piterden** [comment]
Bravo!
