### ISSUE TITLE
[Datepicker][Bug] Showing datepicker when the input type is time

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4520]
When i have selected input mode time. You get both a datepicker in combination with a timepicker. This confuses my client a lot so a fix would be appreciated.

If you choose date+time = Date/time picker
If you choose date =Only datepicker
if you choose time = Only timepicker

If it can't be done, i would suggest reverting this back to the old stuff until it can be done and tested.

**Comment by Piterden** [comment]
https://github.com/anomalylabs/datetime-field_type/pull/20

**Comment by Pixney-William** [comment]
@RyanThompson merge?

**Comment by RyanThompson** [comment]
Merged
