### ISSUE TITLE
[posts-module] SEO fields for auto-pages (posts, archive, etc)

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4521]
To be an easy cms to use for users directly. We need to give the the possibility to set pagetitles and meta descriptions on posts page. For newcomers it seems very strange that you are not able to control this from the admin control panel!

**Comment by myshoeshurt** [comment]
+1

**Comment by Piterden** [comment]
https://github.com/anomalylabs/posts-module/pull/40
Actually posts page is the standard page, which has meta fields, but categories and types could have routes too.

**Comment by RyanThompson** [comment]
@designbywilliam you mean post categories?

**Comment by Pixney-William** [comment]
### What i mean is:
If you access `admin/posts` you should have a title and description field here. Or access to a page where you are able to set it. Because this is the place where it's most logical to set the title and description for the "index page of blogs".

**Comment by RyanThompson** [comment]
I am going to postpone this one just slightly because I am unsure how I want to do it. 

I'd love to just use settings but settings are not multilingual yet. 

I'd also be keen on using SEO block but it's not ready yet either and also not super obvious of a place to look.
