### ISSUE TITLE
[page_link_type-extension] Exception thrown in other languages

### ISSUE THREAD

**Issue by ddnetters** [pyrocms/pyrocms#4523]
page_link_type-extension throws an exception when checking whether a page is enabled in an different language than the system default: `Call to a member function getPage() on null`.

**Steps to reproduce**
1. Enable more than one language
2. Create a few pages
3. Create a navigation with some links to pages
4. Call `{{ links('navslug').get() }}` in some view
5. View a page in any language other than the system default
for example: `http://pyrocms.com/nl/about-us`

Code which tries to find the page can be found in PageLinkTypeExtension.php at line 89

**Comment by Piterden** [comment]
Hope it helps...
https://github.com/anomalylabs/page_link_type-extension/pull/6
