### ISSUE TITLE
Strange migrate button

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4524]
So, we have one new button in the addons-module table. It's name is **migrate**.
I suppose, it should rerun the migrations of the addon.

I have a few questions about it:
1. What is the example case of this button?
2. I suppose, it should erase all what I had created, if there would be any accidentally press (drunk, cat, etc.) of that button. Am I right? (there should be, at least a prompt)
3. Why I don't see migration button in themes table? Many of my themes have some migrations.
4. Where is seeding?
5. Why it is proposing me to migrate, already migrated addons?
6. I want to migrate/rollback only one migration file. What should I do for achieving it?

**Comment by ddnetters** [comment]
as for point one and two, I reckon the button runs any migrations not ran yet. A usecase is having to add or a change a stream when a website is already deployed / filled with content. Optional seeding would be nice.

**Comment by huglester** [comment]
Hello
so I've added this button
1. example: site in production, and we do not  have CLI option.
so we write only UP migrations (in production we do not write down migrations anyway)
if up migration did not do something, or we need to rollback - we write UP migration anyway.)

upload files, and run command via UI.

2. NO. migrate -is migrate not migrated tables yet (already migrated are not touched). for better management more options should be added. maybe 'migrate' button which would allow MORE options. but anyway if you want to 'erase all' you can uninstall?

3. probably missed :) never thought abotu this. it was FAST solution. you are free to add

4. yeah should be an option in the popup probably. like installing.

5. probably only way would be to 'scan for all migration/* files', and compare to the table, if they were migrated. I could not think of 'better' approach.

6. not via UI for now. 
we do MIGRATE UP, if we wanna roollback something.

If you have powers, I think you can offer more robust approach. 

Like 'Manage migrations', 
it opens new windows with...:
a. Migrate addon
b. Rollback (it rolls back one step at a time)
c. Reinstall
d. seed 
e. whatever

**Comment by RyanThompson** [comment]
It's just an UP only for convenience - in the future I see this going away and being replaced with a "check" or "update" button when the store and versions are included in the addons module. For now though this was scratching an itch that @huglester and a couple others have had and brought to my attention.

**Comment by RyanThompson** [comment]
PS this might be better placed in the forum as it's general discussion and not an issue or feature request ^_^

**Comment by Piterden** [comment]
Please, not one more forum
