### ISSUE TITLE
[streams-platform] Make the same behaviours of save hotkeys

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4526]
https://github.com/pyrocms/pyrocms/issues/4498

I understand about FIRST and SECOND buttons. But the position of those buttons in the form is MUCH LESS IMPORTANT than the user workflow inside our CP.
It is really annoying when the same hotkeys are doing different actions.

What about to change those buttons places?

**Comment by RyanThompson** [comment]
The user workflow is dictated by the buttons not the hot keys - the hot keys are position based and will stay that way.

**Comment by RyanThompson** [comment]
If anything the buttons would change - but they seem to work really well currently.

**Comment by Piterden** [comment]
Why are you so hard?
