### ISSUE TITLE
[text-field_type] Limited to 255 chars in DB but no limit on entry

### ISSUE THREAD

**Issue by lachieh** [pyrocms/pyrocms#4527]
The Text field type will accept an unlimited character count, but the DB column type is VARCHAR(255).

Suggest either adding a maxlength attribute on the field markup, or changing the database structure to TEXT instead of VARCHAR(255)

**Comment by Piterden** [comment]
I afraid, changing the structure wouldn't be good in this place.
https://github.com/anomalylabs/text-field_type/pull/8

**Comment by RyanThompson** [comment]
Merged and fixed
