### ISSUE TITLE
[Geocoder-PRO-FT] Allow for bad addresses

### ISSUE THREAD

**Issue by calebsmithdev** [pyrocms/pyrocms#4528]
Issue being thrown when the Geocoder can't convert the address into something usable - or a bad address. Here is an example of a "bad address" `Hwy 166 & 5300 Road Coffeyville, KS 67337`. Issue is failing at the `storage()` line specifically in the block below.

```
public function modify($value)
    {
        if (is_string($value)) {
 
            return $this->fieldType
                ->newGeocoder()
                ->convert($value)
                ->storage();
        }
 
        return parent::modify($value);
    }
```

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/geocoder-field_type/commit/e818caa2fb075cc2d7d1e1c525d52712ac1dcc49
