### ISSUE TITLE
[Geocoder-FT] Add options for quickly getting geocode elements

### ISSUE THREAD

**Issue by calebsmithdev** [pyrocms/pyrocms#4530]
Add decorators for quickly grabbing geocode information.

For example - `{{ entry.location.geocode.state() }}`

**Comment by RyanThompson** [comment]
Done: https://github.com/anomalylabs/geocoder-field_type/commit/80b6c0d5893ca52ca6f72d443d8214bb4880ff7f

**Comment by calebsmithdev** [comment]
This is gorgeous. Thank you!
