### ISSUE TITLE
[Files-FieldType] Make .url in Twig return null if resource cannot be found

### ISSUE THREAD

**Issue by biggins** [pyrocms/pyrocms#4531]
If using a file field type in a view the following code throws the following error if the file isn't in the resource system. 
```
Call to a member function getFilesystem() on null
```
Instead of having to check the resource first like: 
```{{ page.video_banner.resource ? page.video_banner.url }}```

it would be better if the .url function gracefully failed by returning null or false.

**Comment by RyanThompson** [comment]
This should do it: https://github.com/anomalylabs/files-module/commit/cbb9b34c984f022b92e0432f2a0fa3df7d68f105

Thanks!
