### ISSUE TITLE
[video-fieldtype] : regex youtube

### ISSUE THREAD

**Issue by stockhausen** [pyrocms/pyrocms#4533]
Hello, 

for this : https://www.youtube.com/watch?v=z3q-B3i3vkI
with this regex 
`/^(?:(?:https?:\/\/)?(?:www\.)?youtu\.?be(?:\.com)?\/)(?:watch\?v=|v\/)?([a-zA-Z0-9_]*)/`

the result is : z3q

the correct regex is 
`/^(?:(?:https?:\/\/)?(?:www\.)?youtu\.?be(?:\.com)?\/)(?:watch\?v=|v\/)?([a-zA-Z0-9_-]*)/`

**Comment by Piterden** [comment]
Check PRs on videoFT

**Comment by stockhausen** [comment]
i saw @RyanThompson can you push ?

**Comment by Piterden** [comment]
Pushed

**Comment by stockhausen** [comment]
Thx
