### ISSUE TITLE
[streams-platform] Hold shift to select checkmarks between clicks for selecting rows

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4535]

**Comment by Piterden** [comment]
https://github.com/anomalylabs/streams-platform/pull/439

**Comment by RyanThompson** [comment]
Looks good! I am showing ES6 errors - what's that all about? What's it written in? Is ES6 better? I am stupid.

**Comment by RyanThompson** [comment]
There's a bug with selecting 1 at a time though - they don't stay checked.

**Comment by Piterden** [comment]
It's the feature, not bug. It seems you better to write there in pr?

**Comment by Piterden** [comment]
ES6 needs to be compiled. ES6 is more functional, but browsers don't understand ES6. Validator, which I showed to you is written with ES6

**Comment by Piterden** [comment]
https://gist.github.com/Piterden/e4bf8802115866998b1620c0c6e3c99c
ES6 class

**Comment by Pixney-William** [comment]
So, a year later @Piterden do you have a status on this? is it completed and implemented or are there any issues?
