### ISSUE TITLE
WYSIWYG - and twig

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#4538]
Hello,
so for example we have this source:
http://pic.webas.lt/webas.lt-9667213b23.png

as you can see the contact form is automatically wrapped in <p> tag.
How do you solve this?

**Comment by Piterden** [comment]
Kill it

**Comment by huglester** [comment]
kill what? :)

**Comment by Piterden** [comment]
https://github.com/anomalylabs/wysiwyg-field_type/pull/27

**Comment by RyanThompson** [comment]
Use grid

**Comment by RyanThompson** [comment]
The WYSIWYG is not meant for this purpose.
