### ISSUE TITLE
[url-field_type] -- Throwing exceptions on null

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#4539]
After newest update getting the below using `{{ page.url }}`
```
An exception has been thrown during the rendering of a template ("Method Anomaly\UrlFieldType\UrlFieldTypePresenter::__toString() must return a string value") in "C:\Sites\martello_group\storage\streams/martello_group/pages/types/3/layout.twig" at line 119.
```
Expected: a blank string
`{{ page.url.to }}` doesn't throw an exception, but returns `://` instead of a blank string

**Comment by edster** [comment]
Fix for to string is 

replace `core/anomaly/url-field_type/src/UrlFieldTypePresenter.php` line 131 with 
`return $this->object->normalize() == NULL ? '' : $this->object->normalize();`

**Comment by Piterden** [comment]
Why don't you make the PR?

**Comment by edster** [comment]
Busy patching other things that slipped through to production

**Comment by fryiee** [comment]
@edster fixed in https://github.com/anomalylabs/url-field_type/pull/11
