### ISSUE TITLE
[Decimal Field Type] A value of "0" renders the field empty.

### ISSUE THREAD

**Issue by RichardMBS** [pyrocms/pyrocms#4541]
If the field has a value of "0" the lose comparison determines it is equal to NULL and should be left blank.

When a value of "0" is loaded from the DB the the fields value attribute isn't set. When re-submitting the form 0 must be manually entered into the field for it to pass validation (numeric). This can become annoying when there are multiple fields on a page.

I have fixed the issue here: https://github.com/anomalylabs/decimal-field_type/pull/17

**Comment by RichardMBS** [comment]
@RyanThompson I believe this is a bug but don't know how to add the label. Thanks.

**Comment by RyanThompson** [comment]
Merged - thank you!
