### ISSUE TITLE
[comments-module] Features List

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4546]
You told me to think of a feature list for comments and here is my list: 
- [x] Enable/Disable comments globally
- [x] Enable/Disable comments for each post/page or maybe for post/page type
- [x] Accept comments only from registered users or specific role ( this can be done at view level )
- [x] Show comments only to registered users or specific role ( this can be done at view level )
- [x] Automatically close comments on old entries ( old posts )
- [x] Email notification to admin and creator of the post/page
- [x] Either enable automatic spam check or reCaptcha
- [x] Ordering of Comments
- [x] Checkbox for the commenter to subscribe to comment updates
- [x] Slack notification?
- [x] Enable/Disable Mentions

---

- [x] Channel (for same stream / multiple channels)

**Comment by Piterden** [comment]
Commentable stream?

**Comment by RyanThompson** [comment]
Comments have a poly on them so just add it wherever.

**Comment by RyanThompson** [comment]
I could see needing an optional "channel" though.. for multiple channels on the same subject.

**Comment by Piterden** [comment]
Leave the Channel for broadcasting

**Comment by Youhan** [comment]
- batch approve/reject action in admin
