### ISSUE TITLE
[streams-platform] findAll() does not work on models with translations

### ISSUE THREAD

**Issue by squatto** [pyrocms/pyrocms#4547]
I have a `category` stream, and when I do this:

```php
$this->categoryRepository->findAll([1,2,3])
```

I get the following error:

> SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous (SQL: select `default_products_categories`.* from `default_products_categories` left join `default_products_categories_translations` on `default_products_categories`.`id` = `default_products_categories_translations`.`entry_id` where `id` in (1,2,3) and (`default_products_categories_translations`.`locale` = en or `default_products_categories_translations`.`locale` = en or `default_products_categories_translations`.`locale` is null) and `default_products_categories`.`deleted_at` is null group by `default_products_categories`.`id` order by `default_products_categories_translations`.`name` asc)

The problem is specifically with ```where `id` in (1,2,3)```

**Comment by Piterden** [comment]
As I see, you have the `ProductsModule`, which includes `products` and `categories` streams.

```sql
select `default_products_categories`.*
from `default_products_categories`
left join `default_products_categories_translations`
    on `default_products_categories`.`id` = `default_products_categories_translations`.`entry_id`
where
    `default_products_categories`.`id` in (1,2,3)
and (
    `default_products_categories_translations`.`locale` = "en" or
    `default_products_categories_translations`.`locale` = "en" or
    `default_products_categories_translations`.`locale` is null
)
and (
   `default_products_categories`.`deleted_at` is null
)
group by `default_products_categories`.`id`
order by `default_products_categories_translations`.`name` asc
```
Btw, this is working query ^

**Comment by squatto** [comment]
@Piterden Thanks for the response. I can definitely write my own query, but the `findAll()` method should do it correctly too.

**Comment by Piterden** [comment]
I am sure you can. Just wanted to show you the problem was not only with `where id in (1,2,3)`, but also with `en` without quotes.

**Comment by Piterden** [comment]
```mysql
SELECT 
    default_posts_categories.*
FROM
    default_posts_categories
        LEFT JOIN
    default_posts_categories_translations ON default_posts_categories.id = default_posts_categories_translations.entry_id
WHERE
    default_posts_categories.id IN (1 , 2, 3)
        AND (default_posts_categories_translations.locale = 'en'
        OR default_posts_categories_translations.locale = 'en'
        OR default_posts_categories_translations.locale IS NULL)
        AND (default_posts_categories.deleted_at IS NULL)
GROUP BY default_posts_categories.id
ORDER BY default_posts_categories_translations.name ASC
```
^ works fine for me

**Comment by RyanThompson** [comment]
Works these days.
