### ISSUE TITLE
HTTP 500 on install

### ISSUE THREAD

**Issue by cip8** [pyrocms/pyrocms#4548]
Hi! I installed PyroCMS it via composer and serve it with valet (pyrocms.dev), but for some reason it won't load. 

![pyro500](https://user-images.githubusercontent.com/11821612/29736425-34168f84-8a01-11e7-8b01-de1daac7fd72.jpg)

I tried it with different versions of php, reinstalled the package, checked the permissions, etc.

I get this warning, which may be connected with the issue:
![pyroerror](https://user-images.githubusercontent.com/11821612/29736387-c7d5cc86-8a00-11e7-9725-1a0275f82a9c.jpg)

All advice is highly appreciated... I would really like to try Pyro and see what it can do.

Thanks!

**Comment by huglester** [comment]
hello,
show show .env file if it was generated?

**Comment by Piterden** [comment]
Did you launch `php artisan install` ?

**Comment by cip8** [comment]
@ Denis, yes I ran it but it still doesn't work. 

No worries, I chose something else _(Spark)_ to build this project and maybe I'll give it another shot later on. Closing the issue, thanks for your help!

**Comment by Piterden** [comment]
Good luck!
If be honest I hate Apache )
About Pyro - you need to:
- double-check all dependencies
- do not use Valet for testing (use `php artisan serve` instead)
- use MySQL DB for testing
- turn on debug, to see exactly what error do you have
