### ISSUE TITLE
[files-module][files-field_type] order by date by default 

### ISSUE THREAD

**Issue by Youhan** [pyrocms/pyrocms#4549]
When I want to add a post which has some photos, I sometimes drag and drop all photos at once and then using the Editor or the select button of the field type I select the photo/image.

It would be great to see the latest uploaded files first when the modal appears. Saves some clicks and navigations.

**Comment by RyanThompson** [comment]
I think it's time for more views.. 

- [x] Recently Uploaded

**Comment by Pixney-William** [comment]
@Piterden seems like this has been in progress for a while. What is the status? Implemented?

**Comment by RyanThompson** [comment]
Added a view: https://github.com/anomalylabs/files-module/commit/0b831a399465c9e16ad61e83b771dd737b11e30e
