### ISSUE TITLE
[3.1.3] Variables module tags fieldtype error on save

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#4552]
After running composer update on older 3.1 project, i get following error if variable has a tags field-type in it:

```
Type error: Argument 1 passed to Anomaly\TagsFieldType\TagsFieldType::setOptions() must be of the type array, null given, called in /var/www/html/horses/core/anomaly/tags-field_type/src/TagsFieldTypeOptions.php on line 51
```

`$fieldType->setOptions($options ?? []);` hack seems to fix maybe. `$options` is null

**Comment by Piterden** [comment]
Maybe `$options ?: []`?

**Comment by keevitaja** [comment]
That is what i wrote

**Comment by Piterden** [comment]
Wrote ya go ya bat'. Could you show your ft class?

**Comment by RyanThompson** [comment]
This has since been accommodated for
