### ISSUE TITLE
Modify the data method in Anomaly\Streams\Platform\Image 

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4554]
To take into account if i have cropped the image. Today, data returns the raw data of the original image. But if you do crop(..)->data() it don't pay attention to the cropping.

**Comment by RyanThompson** [comment]
Related.. encoded: https://github.com/anomalylabs/streams-platform/commit/f2c9747c46862d5bd19c10079f76072018e4477d

Data: https://github.com/anomalylabs/streams-platform/commit/a634038d4bce83714ae6ac68798551f7492af7c2
