### ISSUE TITLE
[image-field_type] Data is not changed when outputting it in the saved event

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4556]
To replicate:
1) Add a image field type and assign it to post.
2) Add the code below to the PostObserver

When you update/save the post. First time the correct image name will display. If you go back and change the image, the same image name that you had earlier will show. Go back and change image again, and now you will the the image name of the earlier image.

If you do a page refresh however when the wrong image is displayed, it corrects itself.

[Archive.zip](https://github.com/pyrocms/pyrocms/files/1264844/Archive.zip)

```
public function saved(EntryInterface $entry)
    {
        echo 'core/anomaly/posts-module/src/Post/PostObserver.php';
        $post = $entry->getEntry();

        $image = $post->campaign_image;

        dd($image->name);
        
    }
```

**Comment by Piterden** [comment]
`parent::saved($entry)`

**Comment by RyanThompson** [comment]
We resolved this, no?

**Comment by Pixney-William** [comment]
yeah, create an issue for me to finish the guide
