### ISSUE TITLE
Weird scripts at the bottom of the starter theme page

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4557]

**Comment by RyanThompson** [comment]
Watchoo talking about sucka

**Comment by Piterden** [comment]
![image](https://user-images.githubusercontent.com/5930429/30244832-416b0a32-95cf-11e7-8e56-e1aaf8b15ded.png)

**Comment by RyanThompson** [comment]
Not able to see it here - maybe you've got a virus O_O

**Comment by Piterden** [comment]
I have linux
