### ISSUE TITLE
[repeater-field_type] Validation fails with multiple repeaters

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4560]
When there are more than 2 repeaters in a form, validation and repopulate fail unless the last repeater on the page has a validation error.  

In [this scenario](https://goo.gl/Kk521d), for example, when you click "update" (with no value in the required "Some Text Field" field) [this is what i see](https://goo.gl/BkpdC8) - the error shows up top but the form saves successfully and does not repopulate invalid repeater.  

When you click "Save & Exit" the error shows on the next page and does not reload the form with errors.

It seams as though the problem may be at `$fieldType->getValidators()` in  `Anomaly\Streams\Platform\Ui\Form\FormExtender@registerValidators`.  

All repeater field types return 'repeater' as the name of the rule so the rules just get overwritten in `Illuminate\Validation\Factory@extend` (`$this->extensions[$rule] = $extension;`)

**Comment by RyanThompson** [comment]
This has been fixed.
