### ISSUE TITLE
[settings-module] If default value includes `@`, it will attempt to be resolved

### ISSUE THREAD

**Issue by lachieh** [pyrocms/pyrocms#4561]
`Anomaly\SettingsModule\Setting\Command\GetDefaultValue::handle` will try to resolve the default_value if it includes the `@` symbol.

Example Settings file `./addons/default/example/config/settings.php`:
```php
return [
    'email_delivery' => [
        'label'       => 'Email Delivery Address',
        'required'    => false,
        'placeholder' => false,
        'type'        => 'anomaly.field_type.email',
        'config'      => [
            'default_value' => "lachlan@morrisonagency.com",
        ],
    ],
];
```

**Comment by Piterden** [comment]
![image](https://user-images.githubusercontent.com/5930429/30084129-d42de18e-9299-11e7-9523-c474ba8eee05.png)
![image](https://user-images.githubusercontent.com/5930429/30084150-e1f774b0-9299-11e7-9ce8-e3f47da7f71d.png)
Everything is fine for me.

**Comment by lachieh** [comment]
Try using it via `$settings->value()`. @ryanthompson can confirm.

**Comment by Piterden** [comment]
https://github.com/anomalylabs/streams-platform/pull/468

**Comment by RyanThompson** [comment]
Merged and fixed
