### ISSUE TITLE
[streams-platform] Extend other console commands to support addons 

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4562]
Here is the list of some of them:

- [ ] make:notification
- [ ] make:middleware
- [ ] make:controller
- [ ] make:provider
- [ ] make:listener
- [ ] make:command
- [ ] make:seeder
- [ ] make:model
- [ ] make:event
- [ ] make:job

Need to think about it...
Suggestions? @RyanThompson

**Comment by RyanThompson** [comment]
Basically the same path variable can likely be added just like migrate / seed commands. Will have to check though.

**Comment by Piterden** [comment]
The `--addon` should be more useful. Not any user knows about the filesystem ))

**Comment by Pixney-William** [comment]
Completed and implemented yet @Piterden ?
