### ISSUE TITLE
[users-module] - UserWasDeleted Event is fired in both Delete and ForceDelete

### ISSUE THREAD

**Issue by lckamal** [pyrocms/pyrocms#4563]
I wanted to clear data from my Profiles module if user is force deleted (record is deleted from table) but while using Anomaly\UsersModule\User\Event\UserWasDeleted, This event fires on both case delete/force delete. how to know if user is deleted or force deleted?

**Comment by Piterden** [comment]
Kamal, are you trolling me?
![image](https://user-images.githubusercontent.com/5930429/30095227-ec6192c4-92d9-11e7-91e6-44b7433ff7b7.png)
https://github.com/anomalylabs/streams-platform/blob/1.2/src/Model/EloquentModel.php#L287

**Comment by lckamal** [comment]
Because Ryan wanted to make an issue of it. For me isForceDeleting() was sufficient.
http://take.ms/YxzN7

**Comment by RyanThompson** [comment]
Done
