### ISSUE TITLE
DEPRECATE/abandon plugin repositories that were merged into the core one

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4566]

**Comment by Piterden** [comment]
Saying `core` what do you mean?

**Comment by RyanThompson** [comment]
Core being the plugin within Streams Platform (`StreamsPlugin`)

We used to have a session-plugin for example but now it's just all in the one larger core addon.

**Comment by Piterden** [comment]
What is `session-plugin`? Hear first time
