### ISSUE TITLE
Feature request : base64_encode images

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4570]
$cropped  = $this->image->make()->crop($this->width, $this->height, $this->x, $this->y);
$base64Encoded = base64_encode(file_get_contents($cropped->url()));

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/04f31c9aa63d91bc7dfe4e230cd303d7d0f802ed

Done princess
