### ISSUE TITLE
PyroCMS 3.4.0 still include Installer module version 2.2.0

### ISSUE THREAD

**Issue by azraai** [pyrocms/pyrocms#4571]
Hi,

I tried a fresh install for version 3.4.0. There is a 500 error page prompted once you access /admin since the Installer module is still version 2.2.0.

File that is affected is the CheckIfInstallerExists middleware in the installer module where version 2.2.0 is still using`$this->session->set()` to store session data.

**Comment by Piterden** [comment]
Do you want to say all other add-ons have 3.4.0 version?

Add `APP_DEBUG=true` to your `.env` file. Then share here an error, it throws to you.

**Comment by azraai** [comment]
Refer #4572.

**Comment by Piterden** [comment]
It's strange why for me it installs normal

**Comment by Piterden** [comment]
Hey, I got why. I always install Pyro with `php artisan install` ))

**Comment by RyanThompson** [comment]
This has since been fixed but thanks for the heads up!
