### ISSUE TITLE
Updating to 3.4 causes errors

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4574]
So, if you try updating to 3.4, coming from 3.2, to 3.3 and then 3.4 we have some issues. Logged the earlier ones in a previous issue. But once you get that working you now have an issue of an error saying: "Class php not found" on line 53 in AssetFilter.php.

This means, no css is compiled. And the error comes on the admin->settings view.

You have information in slack @RyanThompson

**Comment by RyanThompson** [comment]
We've got this settled - thanks for the heads up!
