### ISSUE TITLE
[forms-module] View not found when setting custom email template.

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#4575]
As title. 
These line of code (present in 1.2 and 1.3) is responsible:

`$layout ?: 'anomaly.module.forms::email',`

This is because the field value of notification_email_layout returns the twig template without namespace and with extension.

**Comment by fryiee** [comment]
https://github.com/anomalylabs/forms-module/pull/20

**Comment by RyanThompson** [comment]
This has since been fixed - thanks for your help!
