### ISSUE TITLE
[streams-platform] Handle missing stream models and compile if necessary

### ISSUE THREAD

**Issue by lachieh** [pyrocms/pyrocms#4576]
One of the most common problems that comes up with new Pyro users is the missing Stream Models and the necessity to run `php artisan streams:compile` most commonly when importing the database.

This may not even be possible because of the way Laravel runs, but it would be heaps good if Pyro would handle the missing stream before throwing an exception and compile the missing stream model.

**Comment by Piterden** [comment]
```bash
den:~/projects/pyro-pg [j2] [!1] $ artis 
PHP Fatal error:  Class 'Anomaly\Streams\Platform\Model\Pages\PagesPagesEntryModel' not found in /home/den/projects/pyro-pg/core/anomaly/pages-module/src/Page/PageModel.php on line 20

                                                                               
  [Symfony\Component\Debug\Exception\FatalErrorException]                      
  Class 'Anomaly\Streams\Platform\Model\Pages\PagesPagesEntryModel' not found                                                                             
```
![image](https://user-images.githubusercontent.com/5930429/31280989-d4d7f306-aab6-11e7-98de-9c1c013554a0.png)
How do you imagine it?

**Comment by RyanThompson** [comment]
I'll keep an eye on things like this in general but speaking to this point - it's too late by the time we know it's missing :-/
