### ISSUE TITLE
Getting error model does not exist.

### ISSUE THREAD

**Issue by ManrajParmarSipl** [pyrocms/pyrocms#4577]
I have seen yours video (4. Module Controllers and Views) but i am getting an error at a time of add Series and Category field on add video form.

Below it the error:
[2017-09-13 08:59:10] local.ERROR: ReflectionException: Class SeriesModel does not exist in E:\xamppinstallation\htdocs\pyrocms6\pyrocms\vendor\laravel\framework\src\Illuminate\Container\Container.php:749
Stack trace:
#0 E:\xamppinstallation\htdocs\pyrocms6\pyrocms\vendor\laravel\framework\src\Illuminate\Container\Container.php(749): ReflectionClass->__construct('SeriesModel')

Please let me know, where I am missing.

**Comment by Piterden** [comment]
First of all you should check files permissions
https://pyrocms.com/help/developer-tools/cheatsheets/installation

Then, requirements
https://pyrocms.com/documentation/pyrocms/latest#installation/server-requirements

PS Also you have the opposite slashes ))

**Comment by ManrajParmarSipl** [comment]
I have given 777 permissions but i think, I am missing to add SeriesModel  in a code.

 protected $assignments = [
    'poster',
    'video' => [
    'required' => true,
    ],
    'title' => [
    'translatable' => true,
    'required' => true,
    ],
    'slug' => [
    'unique' => true,
    'required' => true,
    ],
    'description' => [
    'translatable' => true,
    'required' => true,
    ],
   /* 'series' => [
    'required' => true,
    ],
    'categories',*/
    ];

When I add last two field of other tables that is series and categories then i am getting this error, Do i need to add model also in this migration file and if yes then how i can add ?

Actually here is relation ship of video->series
video->category.

**Comment by Piterden** [comment]
\`\`\`php

Read this
https://guides.github.com/features/mastering-markdown/

**Comment by Piterden** [comment]
Categories are also not added

Is it Pro module or your?

**Comment by ManrajParmarSipl** [comment]
Yes, Can you please let me know, How I can add category and series model and resolve this error.

**Comment by Piterden** [comment]
Make `cat *` in your `/migrations` folder and put here

Also I don't understand this is your module or Pro

**Comment by ManrajParmarSipl** [comment]
I have already setup migration for category inside a migration folder but problem is when i am adding categories in video stream file:

<?php

use Anomaly\Streams\Platform\Database\Migration\Migration;

class AnomalyModuleVideosCreateCategoriesStream extends Migration
{

    /**
     * The stream definition.
     *
     * @var array
     */
    protected $stream = [
    'slug' => 'categories',
    'translatable' => true,
         /*'title_column' => 'name',
         'trashable' => false,
         'searchable' => false,
         'sortable' => false,*/
         ];

    /**
     * The stream assignments.
     *
     * @var array
     */
    protected $assignments = [
    'title' => [
    'translatable' => true,
    'required' => true,
    ],
    'slug' => [
    'unique' => true,
    'required' => true,
    ],
    'description' => [
    'translatable' => true,
    'required' => true,
    ],
    ];

}

**Comment by Piterden** [comment]
https://pyrocms.com/documentation/streams-platform/latest#database/migrations

I wouldn't read code in that styling!

Also, if you wouldn't answer my questions, I can't help you.

**Comment by ManrajParmarSipl** [comment]
[videos-module.zip](https://github.com/pyrocms/pyrocms/files/1299012/videos-module.zip)
This is module which i am creating by following video and exploration but i am unable to resolve this issue, I need to add category and series also in add video form.

Can you please check or can share any addon of pyrocms with 2 tables CRUD .

**Comment by Piterden** [comment]
[catalog-module.zip](https://github.com/pyrocms/pyrocms/files/1299072/catalog-module.zip)

**Comment by ManrajParmarSipl** [comment]
Can you please let me know, How I can install this module: https://www.screencast.com/t/cH25I4lfY
I am getting some errors.

**Comment by Piterden** [comment]
Something with your environment. I don't have such of namespaces there.

**Comment by ManrajParmarSipl** [comment]
Thanks Piterden !!

Actually, I missed to add 2 lines in video stream.
After adding models (below lines) in videos fields file everything is working fine.

use Anomaly\VideosModule\Series\SeriesModel;
use Anomaly\VideosModule\Category\CategoryModel;
