### ISSUE TITLE
[multiple-field-type] Inversed Relationship

### ISSUE THREAD

**Issue by pepijnolivier** [pyrocms/pyrocms#4582]
# The problem

When defining a "multiple relationship" on a stream, the field is only added one-way.
For example:
> In a project with an `Artists` stream and an `Events` stream, adding the multiple-relationship field to the Events stream correctly ensures that, when editing an Event via the FormBuilder, multiple artists can be coupled to the Event.
> By default, a "reverse field" is not added to the Artists stream; eg. I won't be able to edit the events when editing an artist. 

---

The above is fine as a default setting. However, there are some cases in which you want to manage this relationship 2-way. (manage artists by event; but also manage events by artist).
Allowing this behaviour will solve a few of our problems (like eager loading EntryModels in an API, managing related stream entries in both formbuilders, etc.), and we wouldn't have to define these inversed relationships on the Models ourselves anymore.

The way it is now, when adding the "reversed relationship field" manually to the other stream, PyroCMS will create a different pivot table. In most cases, this is undesirable, it would be better to allow extra field configuration so that an existing table can be used.

### I'm willing to prepare a PR for this, if you can tell me which implementation you prefer

**Solution 1**
Add the following extra, optional config settings to the Multiple Field Type:
```
[
    "table" => 'events_artists' // rather than the generated default: artists_events,
    "entry_model" => ArtistModel::class,
    "related_model" => EventModel::class,
]
```

With the above solution, a developer will have to create the "inversed relationship" manually, but can configure the field so that an existing database pivot table can be used. (with id_column and related_id_column reversed). This solution is probably easiest to implement, and does not touch other streams when migrating a stream.

**Solution 2**
As mentioned by @Piterden, @RyanThompson  might prefer to make this process a little more automatic.
We could add the following config setting to the Multiple Field Type.
```
[
    "two_way" => true, // there's probably a better name for this though
]
```

If we would go this way, PyroCMS would also create the inversed relationship for us on the other stream. I'm not sure if that's a good idea though (editing a different stream from within one stream), but I get why some people would still prefer this.

**Other solutions**
? (open to suggestions)

---

I personally think the first approach will yield the least issues, but the developer does have to do a little bit extra work. The most important thing for me is that we can use an inversed multiple relationship though, no matter how it's implemented.

@RyanThompson 
Please tell me what you prefer and I will send a PR somewhere in the near future.

---

As a reference, here's [The related slack discussion](https://pyrocms.slack.com/archives/C12KPUV7U/p1505297130000366) where I mentioned this issue first.

**Comment by pepijnolivier** [comment]
@RyanThompson thoughts on this?

**Comment by RyanThompson** [comment]
I've been playing around with this recently and I've found that hooks were a good solution. No changes needed and it's BC but I haven't fleshed anything out as it's been waaaay back on the back burner. If you are still interested in doing something here I've been on a feature binge and can help you with getting a PR put together.

**Comment by slackernrrd** [comment]
Has there been any more work on this? I would love to see some version of this, not having inverse relationships is causing problems for me in my current project.

Do you have an example of a solution using hooks, @RyanThompson?

**Comment by slackernrrd** [comment]
I guess that’s a ”No”, then.
