### ISSUE TITLE
[multiple-field_type] Lookup table shows already selected

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4585]
![multift](https://user-images.githubusercontent.com/5930429/30469959-7ec4ec6a-99fb-11e7-8bc2-ade2dd3beafa.gif)

**Comment by RyanThompson** [comment]
Ya this is known - I don't see a huge problem with it and I had the damndest time trying to sort out the query prior. Might take another whack at it with the FT update though removing jQuery and cleaning it up.
