### ISSUE TITLE
Unable to show image on list

### ISSUE THREAD

**Issue by ManrajParmarSipl** [pyrocms/pyrocms#4586]
I am using poster filed type for uploading image but I am unable to show image.
https://www.screencast.com/t/0IE3fU9RoFx
Image is storing on the folder path : regina\public\app\default\assets\images

**Comment by Piterden** [comment]
What the field type you use?

**Comment by ManrajParmarSipl** [comment]
I have used 'poster' field type.

Below are my stream array:
 /**
     * The stream assignments.
     *
     * @var array
     */
    protected $assignments = [
        'poster',
        'name' => [
            'translatable' => true,
            'required' => true,
        ],
        'slug' => [
            'unique' => true,
            'required' => true,
        ],
    ];

And i am displaying two column on list.

protected $columns = ['entry.poster.preview','name'];

**Comment by Piterden** [comment]
I need your fields array also. But better, you would show full migrations.
And there is not any poster FT. Had you done it self?

PS You are already making to much wrong things. Pyro is not much similar to other CMS's. Maybe we better discuss it in the Slack?

**Comment by Piterden** [comment]
And wat's with your code?
How have you done it? Where have you lost all indentation from your code?

**Comment by ManrajParmarSipl** [comment]
Thanks, Piterden !
I have added htaccess then it's working fine.
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php?/$1 [L]
