### ISSUE TITLE
[geocoder-field_type] Allow reverse geocodig

### ISSUE THREAD

**Issue by lenssoft** [pyrocms/pyrocms#4588]
It would be nice if the geocoder field type would accept an array as input ( latitude and longitude ) in order to reverse geocode.

I think the field type is prepared for reverse geocoding. 
I have achieved the needed reverse geocoding behavior by modifying the file below:
```php
namespace Anomaly\GeocoderFieldType;

class GeocoderFieldTypeModifier{
...
public function modify($value){
..
// added code
if (is_array($value)) {
    $geocoder = $this->fieldType->newGeocoder();
            if (!$point = $geocoder->reverse($value[0], $value[1])) {
                return null;
            }
            return $point->storage();
        }
...
}
...
}
```

**Comment by RyanThompson** [comment]
Check it out!

https://github.com/anomalylabs/geocoder-field_type/blob/1.1/src/GeocoderFieldTypeGeocoder.php#L85

You can also feed this plugin a [lat, lng]

https://github.com/anomalylabs/geocoder-field_type/blob/1.1/src/GeocoderFieldTypePlugin.php#L28

**Comment by RyanThompson** [comment]
Also: https://pyrocms.com/documentation/geocoder-field-type/latest#usage/geocoder/geocoderfieldtypegeocoder-reverse
