### ISSUE TITLE
[pages-module] PG Can't create no one page

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4590]
Look like there is a little recursion
![image](https://user-images.githubusercontent.com/5930429/30570494-455de7be-9cea-11e7-84a9-6c7a75769a0d.png)
![image](https://user-images.githubusercontent.com/5930429/30570500-4d1834e6-9cea-11e7-97bf-fc3efc7408e9.png)

There are assignments
![image](https://user-images.githubusercontent.com/5930429/30570557-9513b496-9cea-11e7-98f2-6a03a1f9a351.png)

**Comment by RyanThompson** [comment]
How to recreate?? The title is a little confusing :-/
