### ISSUE TITLE
[redirects-module] Invalid expression

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4591]
![image](https://user-images.githubusercontent.com/5930429/30575264-49d62658-9d08-11e7-8ab6-21ab3de28c5a.png)

![image](https://user-images.githubusercontent.com/5930429/30575289-6b6cf800-9d08-11e7-9d4c-407ac5fa6a85.png)

https://github.com/laravel/framework/blob/5.5/src/Illuminate/Routing/Route.php#L412

Actually, `{(.*?)}` should be enough, but I'd prefer `{(\w+?)}`

**Comment by Piterden** [comment]
https://github.com/anomalylabs/redirects-module/pull/12

**Comment by Piterden** [comment]
Redirects module not working properly. Propose you to except it from default addons list, till it'd be fixed, @RyanThompson

**Comment by RyanThompson** [comment]
Merged - thanks!
