### ISSUE TITLE
Getting an error during pyroCMS 2.2 installation 

### ISSUE THREAD

**Issue by ManrajParmarSipl** [pyrocms/pyrocms#4593]
I am getting an error: The MySQL database driver for PHP were not found, installation cannot continue. Ask your host or server administrator to install it.

Can anyone help please .

Please have a look on this screen shot: https://www.screencast.com/t/qX506cbd8

**Comment by ikoniqoz** [comment]
This looks like a PHP installation issue.
Are you sure that you have MySQL support for PHP set up? What does phpinfo.php tell you?  
Also review https://dev.mysql.com/downloads/connector/php-mysqlnd/

**Comment by ManrajParmarSipl** [comment]
Thanks, Actually on my system installed PHP 7 and PHP 7 is not compatible with PyaroCMS 2.2 that's way i was facing issue, Now, it's working fine with PHP 5.6.
