### ISSUE TITLE
Forum: Need to prevent posting several times.

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4594]
Right now it's possible to click the reply button in our forum several times and it creates duplicated of you comment. We need to disable the button once clicked. @RyanThompson

**Comment by Piterden** [comment]
Why? It is nice! Leave it like now.

**Comment by RyanThompson** [comment]
I feel like this is something that's needed in general in the CP too.

How do you feel about a global loading state plugin that let's you change, say, the Update (with save icon) and on click it goes to "Updating" (with loading spinner) and disabled state?

data-loading-icon and data-loading-text we could use as options 

Pry trigger disable on all form actions when one is clicked and there are more than one.

**Comment by edster** [comment]
Thats a great way to go about it@RyanThompson

**Comment by Pixney-William** [comment]
Has this been completed @RyanThompson so that we can close the issue?

**Comment by RyanThompson** [comment]
This has been completed in the CP and will trickle out to others as I come across them.
