### ISSUE TITLE
PHP Fatal error:  Class 'Anomaly\Streams\Platform\Model\Users\UsersRolesEntryModel' not found

### ISSUE THREAD

**Issue by rocandante** [pyrocms/pyrocms#4595]
Hello, I have tried installing Pyro 3.4.1 on ubuntu 16.04 using php artisan install and I get the following error:

1/51 Running core migrations.
2/51 Running application migrations.
3/51 Installing: Addons Module
4/51 Installing: Configuration Module
5/51 Installing: Dashboard Module
6/51 Installing: Files Module
7/51 Installing: Navigation Module
8/51 Installing: Pages Module
9/51 Installing: Posts Module
10/51 Installing: Preferences Module
11/51 Installing: Redirects Module
12/51 Installing: Repeaters Module
13/51 Installing: Settings Module
14/51 Installing: Users Module
15/51 Installing: Variables Module
16/51 Installing: Default Authenticator Extension
17/51 Installing: Default Page Handler Extension
18/51 Installing: Local Storage Adapter Extension
19/51 Installing: Page Link Type
20/51 Installing: Robots Extension
21/51 Installing: Sitemap Extension
22/51 Installing: Throttle Security Check Extension
23/51 Installing: URL Link Type Extension
24/51 Installing: User Security Check Extension
25/51 Installing: XML Feed Dashboard Widget
26/51 Reloading application.

PHP Fatal error:  Class 'Anomaly\Streams\Platform\Model\Users\UsersRolesEntryModel' not found in /var/www/festiccbog/core/anomaly/users-module/src/Role/RoleModel.php on line 14

                                                                               
  [Symfony\Component\Debug\Exception\FatalErrorException]                      
  Class 'Anomaly\Streams\Platform\Model\Users\UsersRolesEntryModel' not found

Any idea how I can solve this issue?

**Comment by Piterden** [comment]
First of all check your permissions on the `storage` folder.
https://pyrocms.com/help/developer-tools/cheatsheets/installation

**Comment by rocandante** [comment]
thank you for replying. 

I set the permissions to the instructions and follow out the same error. Also try to do web installation and the same error occurs. Try running with sudo php artisan install which is not the usual but to discard any permissions problem and the same error. Change the owners of the storage, public/app and bootstrap/cache folders to www-data and the same thing.

The installation process correctly executes 26 of the 51 tasks, so I'm not sure that it's a permissions problem.

**Comment by Piterden** [comment]
What is in logs?

**Comment by RyanThompson** [comment]
Clean install?? Did you make the .env file ahead of time by chance or did you do just like what’s on the docs?

**Comment by rocandante** [comment]
this is the log of the last attempt to install:

[2017-09-20 19:32:11] production.ERROR:Class 'Anomaly\Streams\Platform\Model\Users\UsersRolesEntryModel' not found {"exception":"[object] ((Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Class Anomaly\\Streams\\Platform\\Model\\Users\\UsersRolesEntryModel' not found at /var/www/bogota/core/anomaly/users-module/src/Role/RoleModel.php:14)
[stacktrace]
#0 {main}
"}

I did a clean install according to the documentation. On the same server a couple of months ago I had installed version 3.3.3 and it was successful (https://new.ciudadred.co), so I do not understand that it went wrong.

**Comment by rocandante** [comment]
Hi, I'm not sure that caused the error but I started the whole installation process from scratch, I deleted the database, I cleaned the composer cache, I deleted the installation directory, even restart the server. Then I did the installation step by step and everything was satisfactory. Thank you very much for your replies.

**Comment by stickeegreg** [comment]
In case anyone else has this problem, try this (from [here](https://pyrocms.com/forum/channels/streams-platform/error-when-migrating-to-production-class-anomalystreamsplatformmodelusersusersrolesentrymodel-not-found) and [here](https://pyrocms.com/forum/channels/everything/class-anomalystreamsplatformmodelusersusersrolesentrymodel-not-found)):

1. Edit your .env to set `INSTALLED=false`
2. Run `php artisan streams:compile`
3. Set `INSTALLED=true` in your .env
