### ISSUE TITLE
[streams-platform] Twig_SimpleFunction 'trans' not working after update

### ISSUE THREAD

**Issue by girvydas** [pyrocms/pyrocms#4596]
after update to PyroCMS 3.4 trans function in twig not working correctly by locale:
{{ trans(‘anomaly.module.users::field.remember_me.name’) }} always return "Remeber me"

but in PHP ex. controller "trans" function works fine and returns correct translated string.

.env content:
APP_LOCALE=lt
LOCALE=lt
DEFAULT_LOCALE=lt
ENABLED_LOCALES=“lt,en”
APP_FALLBACK_LOCALE=lt

Fresh PyroCMS install works correct, this happens only after update from 3.3, 3.2

**Comment by Piterden** [comment]
`APP_FALLBACK_LOCALE=en` maybe?

**Comment by girvydas** [comment]
I think my problem with twig {{ trans() }} caused by removing ‘rcrowe/twigbridge’ from streams-platform 1.3
Also could you check fresh pyrocms 3.4 install with ENV set LOCALE=fa  (any not english) and open browser /admin/login  you will see not translated strings

**Comment by girvydas** [comment]
Fixed at https://github.com/anomalylabs/streams-platform/commit/701fbf37633cf87e5b2d0ac7d7b8f09cb2b0862d
streams-platform 1.3.2

**Comment by Piterden** [comment]
https://laravel.com/docs/5.5/localization @RyanThompson

**Comment by RyanThompson** [comment]
We ended up fixing this
