### ISSUE TITLE
[streams-platform - table] Sorting custom integer columns is not correct

### ISSUE THREAD

**Issue by michvh-dev** [pyrocms/pyrocms#4599]
I think there is a problem with the sorting table columns on integers. I created a custom column but the column is here not sorting correct. 
```
builder->setColumns(
[
      'custom_column' => [
                'heading' => trans('test.module.blarp::columns.volumn'),
                'sort_column' => 'custom_column',
                'value' => function (EventModel $entry) {
                    $res = $entry->relation->count();
                    return $res === 0 ? null : $res;
              },
       ],
]);
``` 
this is resulting not correct at the sort of this custom column. The first rows are correct but suddenly it is random by example: 40, 33, 22, 23, 23, 21, 19,....

**Comment by RyanThompson** [comment]
Just so we're on the same page - the `sort_column` parameter will cause it to sort on that column in the DB - regardless of the `value` there. Are you saying it's not sorting by the DB value correctly? If so, mind pasting the resulting query here from your debugger?

**Comment by michvh-dev** [comment]
This is not a Db column, i just want to sort on that custom_column. So not an a column that is in the DB. I want to sort on the count of a has many relation on a entryModel

**Comment by RyanThompson** [comment]
Ok - you will need to do this a little differently:

Use the `querying` callback to join / otherwise calculate this custom value in as an additional `select` in the query for the table (name it `custom_column` for example). Then your sort_column will work cause it's a select field now - then you can remove your `value` parameter.

**Comment by RyanThompson** [comment]
$query->addSelect('SUM(foo) as custom_column`) or something along those lines for example

**Comment by michvh-dev** [comment]
Is this not better to do this on an other way? i think this is really "dirty' because you know the value from the value property and when you want that it is sortable. You need to inject this value in the query with a turnaround. We had already several project where we have problem with these custom columns.

**Comment by michvh-dev** [comment]
Because the logic to calculate the exact value can not be injected in the query. So than is this also not the solution?

**Comment by RyanThompson** [comment]
The problem with what you're suggesting though is that you could only sort the returned page set from the DB. If you have smaller data sets you could do your custom value on the column - then use the builder's `onBuilt` callback to get the rows - sort them by your custom value (computer in PHP not DB) and then `$builder->setTableRows($rows)` back on the builder when you've sorted them.
