### ISSUE TITLE
url_secure and url_to generates wrong urls

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4604]
@RyanThompson  url_secure and url_to generates correct link when you browse default locale. 

When you then switch to the sv locale for example, it generates links like this: `http://william.dev/william.dev/sv/my-story`

**Comment by ghost** [comment]
Ping me on slack when it's sorted, soon heading to sleep so wanna be able to update as soon as poss so the seo isnt screwed

**Comment by RyanThompson** [comment]
Fixed! https://github.com/anomalylabs/streams-platform/commit/65a771f6081e8d0c1b1eba86b4139c66f379d01c

Thanks ^_^
