### ISSUE TITLE
[Documentation] https://pyrocms.com/posts/users-module-v2-4

### ISSUE THREAD

**Issue by ikoniqoz** [pyrocms/pyrocms#4605]
Grammar/Structure: "You can now login as other **_uses through via_** the control panel. Admins can not be impersonated and the action is again permission based"

Should this be: "You can now login as other users via the control panel. Admins can not be impersonated and the action is again permission based" - ??

**Comment by Piterden** [comment]
> You can now login as other users via the control panel, using the admin role as base login role.

**Comment by RyanThompson** [comment]
Thanks! Cleaned up a little
