### ISSUE TITLE
[streams-platform] - Table builder add row class, attributes

### ISSUE THREAD

**Issue by girvydas** [pyrocms/pyrocms#4607]
Need some functions or callback to add classes to table rows.
Now it just sets table row ID by loop.index

**Comment by RyanThompson** [comment]
Agreed - I feel like an option would still be nice too - so you could set it outside of the API if needed.


[9:43] 
But there is no builder definition for rows -


[9:43] 
So it’d have to be an option or something


[9:44] 
Which.. could just be put into the view and be done


[9:44] 
`{{ table.options.row_class }} {{ row.class }}` and have both.

**Comment by Piterden** [comment]
So, do column and cell right away.

**Comment by girvydas** [comment]
Any solution how to hack this temporary?

**Comment by Piterden** [comment]
Override this `vendor/anomaly/streams-platform/resources/views/table/partials/body.twig` in your addon.

**Comment by girvydas** [comment]
There is no reason to do so, because Row object has no class or other option. And there is no way to set it dynamically

**Comment by Piterden** [comment]
I have edited 2 files. 

`vendor/anomaly/streams-platform/resources/views/table/partials/body.twig`:
```twig
    <tr id="{{ loop.index }}"
        {% if table.options.row_class %}
            class="{{ table.options.row_class }}"
        {% endif %}
    >
```
and my formbuilder:
```php
    /**
     * The table options.
     *
     * @var array
     */
    protected $options = [
        'row_class' => 'black',
    ];
```
The result is
![image](https://user-images.githubusercontent.com/5930429/31269921-f6d91380-aa8a-11e7-940f-e3a3720f617c.png)

**Comment by girvydas** [comment]
This works if all rows need same class. 
In my situation and why I created issue, every row needs different class/attribute. Which could be set dinamically over hook or listener.
This will be useful for JS plugins or custom rows CSS (my case - row color).

**Comment by Piterden** [comment]
You could write any classes changing with JS, for now.

On what classes of a row would be depended?

**Comment by RyanThompson** [comment]
Alrighty - this has been added to streams platform 1.3 (in Pyro 3.4)

```
protected $options = [
    'row_class' => 'entry.id'
];
```

You can use a closure too but will need to leverage a `FooTableOptions` handler of course. 

https://github.com/anomalylabs/streams-platform/commit/608c6745c5248d43d7e0b243cb8107b4aa23f71f
