### ISSUE TITLE
[markdown-field_type] Update breaks, 2.2 using old markdown.

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4610]
**Not working:** 

https://github.com/anomalylabs/markdown-field_type/blob/2.2/src/MarkdownFieldTypePresenter.php#L7

**Working :** 

https://github.com/anomalylabs/markdown-field_type/blob/2.1/src/MarkdownFieldTypePresenter.php#L7

**2.2 is the recommended version :** 
https://github.com/pyrocms/pyrocms/blob/3.4/composer.json#L45

**Comment by RyanThompson** [comment]
These quirks have all been resolved. Reopen if I am missing something!
