### ISSUE TITLE
[ files-module ][ feature request ] SEO options for files

### ISSUE THREAD

**Issue by ddnetters** [pyrocms/pyrocms#4611]
When editing a file you have the ability to enter tags to help with searching. Maybe it'd be a good idea to also add the SEO fields of an image like `alt` and `title`.

**Comment by RyanThompson** [comment]
I 100% agree and had this in mind myself

**Comment by RyanThompson** [comment]
Alt, Description and/or Caption, Title are some of the ones Assets for EE used (which was top dog back in the day).

ALT, DESCRIPTION, TITLE are all 3 super important if you ask me. Caption would be cool but could use description in those cases as a caption too. 

Then we have custom fields of course per folder.

**Comment by RyanThompson** [comment]
Done! https://github.com/anomalylabs/files-module/commits/2.4

REquire 2.4.x-dev for now and I'll release a 2.4 version soon after some other updates I have planned.
