### ISSUE TITLE
Error during 3.4.2 installation

### ISSUE THREAD

**Issue by kiltedup** [pyrocms/pyrocms#4612]
Just tried a new install. 

Following error occurs:

`[2017-09-27 13:15:21] production.ERROR: Class 'Michelf\Markdown' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Michelf\\Markdown' not found`

**Comment by ghost** [comment]
Ryan will be sending out a fix soon. For now though, you can get it working by changing:
`"anomaly/markdown-field_type": "~2.2.0",`

to:
`"anomaly/markdown-field_type": "~2.1.0",`

in your **composer.json** file

**Comment by RyanThompson** [comment]
Thanks for looking out guys - this was silly on my part - had un pushed commits. 

This was fixed this morning.

**Comment by kiltedup** [comment]
Is this fixed? Still getting the issues. I can see that 'michelf/php-markdown' has gone from the stream-platform composer, but it is still referenced in the installer:

`installer-module/src/Installer/Form/InstallerFormFields.php:39`

```
'license'               => [
    'label'        => 'anomaly.module.installer::field.license.label',
    'instructions' => 'anomaly.module.installer::field.license.instructions',
    'wrapper_view' => 'anomaly.module.installer::field_type/license/wrapper',
    'type'         => 'anomaly.field_type.boolean',
    'required'     => true,
    'config'       => [
        'label'   => 'anomaly.module.installer::field.license.agree',
        'mode'    => 'checkbox',
        'license' => function () {
            return (new \Michelf\Markdown())->transform(
                file_get_contents(app('streams.path') . '/LICENSE.md')
            );
        },
    ],
],
```
