### ISSUE TITLE
[streams-platform] getFunctions no longer getting called in plugins

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4614]
When i upgraded to Pyro 3.4 i noticed that my twig functions / globals were no longer available in my views.  It looks like `getFunctions` and a couple of other methods are no longer getting called in plugins.

**Comment by Piterden** [comment]
3.4

**Comment by mattcdavis1** [comment]
@Piterden updated - thanks!

**Comment by RyanThompson** [comment]
Im not finding this behavior at all - how are you registering your plugins? Are they plugin addons or loaded by another addon?

**Comment by mattcdavis1** [comment]
My plugin is definitely loading - it's just that certain functions are no longer being called.  [Here's a gist](https://gist.github.com/mattcdavis1/63fcee87330132387b4c3c551062b8b0) with my plugin.

If you're not seeing this on your end, will re-test with clean install but this definitely stopped working for me when i attempted an upgrade from 3.3

**Comment by Piterden** [comment]
Maybe it should be `stdClass` on the line 31, @mattcdavis1 ?

**Comment by mattcdavis1** [comment]
This is related to the Twig upgrade not Pyro.  Just need to switch to `getGlobals` for my twig globals.
