### ISSUE TITLE
[checkboxes-field_type] Save Fails w/Front End Form when field is skipped

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4615]
I have a FE form with a checkbox field type that is in the skips array.  When saving, the value passed to `CheckboxesFieldTypeModifier@modify` is a serialized string.  This serialized string then gets re-serialized.

**Comment by Piterden** [comment]
https://github.com/anomalylabs/checkboxes-field_type/pull/15
