### ISSUE TITLE
[files-module] Images aren't translatable

### ISSUE THREAD

**Issue by ddnetters** [pyrocms/pyrocms#4622]
It's not too uncommon to have translatable image when dealing with multilingual sites. Currently when you make a file ft translatable, select a different language and try to pick a different image the modal for picking an image doesn't show up.

_Steps to reproduce_
1. Create a translatable file field
2. Try to select two different images in two different languages

**Comment by lachieh** [comment]
Related issue: If you enable the 'translatable' option on a File FT (even without enabling a second language), the field will not display on the frontend.

If you add a file field to a page, dumping the raw data will display the `file_id` property from the translations table column but when accessing the convenience method on the generated model, it returns `null`.

Outputs array of fields (including file_id):
```twig
{{ page|raw }}
```

Outputs nothing:
```twig
{{ page.file|raw }}
```

My use case is translated instruction manuals. We have a different PDF for each language and currently have to display two separate fields.

**Comment by ddnetters** [comment]
Another use case is images with text in them, including logos. @RyanThompson

**Comment by keevitaja** [comment]
https://github.com/pyrocms/pyrocms/issues/3635

**Comment by ddnetters** [comment]
@keevitaja way different use case from images with text. You can't display every version of an image on a page.

**Comment by Pixney-William** [comment]
I do see the use case here. And down the road i would like to see this too.

**Comment by RyanThompson** [comment]
Images/Files are translatable.

**Comment by bahl-marketing** [comment]
> Images/Files are translatable.

How to access the translatable Images/Files ?

**Comment by tasaduqh** [comment]
> Images/Files are translatable.

@RyanThompson How to access translatable Images/Files ?
