### ISSUE TITLE
[streams-platform] StreamCollection can't be grouped

### ISSUE THREAD

**Issue by schmidex** [pyrocms/pyrocms#4625]
Example:
`entries('namespace', 'slug').get().groupBy('field')`

results in the following error: 
`An exception has been thrown during the rendering of a template ("An exception has been thrown during the rendering of a template ("array_key_exists(): The first argument should be either a string or an integer").").`

i think grouping results is a very common case.... Hopefully there is a solution for this.

**Comment by Piterden** [comment]
`dd(entries('namespace', 'slug'))` - EloquentCriteria
`dd(entries('namespace', 'slug').get())` - EloquentCollection
Collection do not have the `groupBy` method, I believe.

**Comment by schmidex** [comment]
of course they have. The EloquentCollection is inherited from the original Laravel Collection.
The Problem seems to be here:
https://github.com/laravel/framework/blob/d610151d9baeb8ca090fa2405a86d619f842d7a9/src/Illuminate/Support/Collection.php#L664

The FieldTypePresenter isn't converted to string so a valid groupKey can't be created.

**Comment by schmidex** [comment]
simple fix:
https://github.com/anomalylabs/streams-platform/pull/503

**Comment by Piterden** [comment]
Anyway, try to entries().orderBy().get()

**Comment by schmidex** [comment]
orderBy <> groupBy ;-)

https://laravel.com/docs/5.5/collections#method-groupby
grouping can't by done this way on sql level :-(

**Comment by Piterden** [comment]
Doesn't matter
https://laravel.com/docs/5.5/queries#ordering-grouping-limit-and-offset

**Comment by schmidex** [comment]
grouping in sql is totaly different from what a laravel collection does when grouping

**Comment by Piterden** [comment]
Of course. The grouping of SQL query is much cheaper than grouping of L5 collection.
- *SQL* - cheapest
- *PHP arrays* - middle
- *L5 collection* - most expensive from them

**Comment by schmidex** [comment]
I know that it is much more performant.
But I can't get the result I want when grouping in SQL.

entries('events').groupBy('day').get()
vs.
entries('events').get().groupBy('day')

**Comment by Piterden** [comment]
Could you explain which result do you need?

**Comment by schmidex** [comment]
Sure. I will try by giving a very simple example:

table:
```
['id' => 1, 'name' => 'test1', 'day' => monday]
['id' => 2, 'name' => 'test2', 'day' => tuesday]
['id' => 3, 'name' => 'test3', 'day' => monday]
...
```


entries('...').get().groupBy('day'):
```
    [
        'monday' => [
            ['id' => 1, 'name' => 'test1', 'day' => monday],
            ['id' => 3, 'name' => 'test3', 'day' => monday],
        ],
        'tuesday' => [
            ['id' => 2, 'name' => 'test2', 'day' => tuesday],
        ],
    ]
...
```

**Comment by Piterden** [comment]
The most funny thing is: the query builder's groupBy not works too... :trollface:

**Comment by RyanThompson** [comment]
Merged
