### ISSUE TITLE
Installing Pyro issue

### ISSUE THREAD

**Issue by cedricvr** [pyrocms/pyrocms#4626]
When trying to install pyrocms it wokrs fine until trying to actualy visit the page I get this error. What can I do to resolve this issue ?
![capture](https://user-images.githubusercontent.com/9087667/31238321-e9ff1f2e-a9f9-11e7-8df1-b6c4d9118265.PNG)

**Comment by Piterden** [comment]
The webroot must be inside your public folder. Try to stop your XAMPP, then type `php artisan serve --host=pyrocms.dev --port=8888 &`. You would have running developer server on port you have set.

**Comment by cedricvr** [comment]
Thank you for the response. The command didn't work and I get the same error shown in the terminal as I do in chrome.

**Comment by Piterden** [comment]
It is your environment issue. Check all dependencies and also permissions.

**Comment by cedricvr** [comment]
Thank you for the very fast response.
The issue still exists, as well as with homestead, wamp, xampp, mamp pro and using artisan.
How can I check dependencies. The permissions are all set correctly.

**Comment by Piterden** [comment]
Read the docs. Dependencies are on the first page.

**Comment by RyanThompson** [comment]
@cedricvr this is probably the host name is confusing the app. Try just mapping `pyrotest.dev` to your `public` folder. Rather than localhost and a host name and then a public path. That's undoubtedly causing issues. 

Feel free to reopen if you find that's not the case!
