### ISSUE TITLE
[datetime-field_type] Comparison not possible

### ISSUE THREAD

**Issue by schmidex** [pyrocms/pyrocms#4627]
When comparing two `datetime-field_type`-fields you get wrong results

**Comment by schmidex** [comment]
fix: https://github.com/anomalylabs/datetime-field_type/pull/23

**Comment by Piterden** [comment]
I don't believe you.

**Comment by schmidex** [comment]
Steps to reproduce:

Create a stream with a `datetime-field_type` (called time in my example) and set it to time only. Add the following items to the stream:
`1: 20:30:00`
`2: 19:00:00`

try this:

```
{% set test = entries(...).get() %}

{{ dump(test.0.time > test.1.time) }}
```

will return `false`.

**Comment by schmidex** [comment]
Of course this is a very bad example because you can simply do this:
`{{ dump(test.0.time.getValue() > test.1.time.getValue()) }}`

I came across this when trying to get the `EloquentCollection::min()` method to work with a `datetime-field_type`

**Comment by Piterden** [comment]
I don't find the Twig `dump()` function. Where did you get it?

`core/anomaly/helper-plugin/src/HelperPlugin.php#L31-34`
