### ISSUE TITLE
error 500 in "localhost:8000/installer/install"

### ISSUE THREAD

**Issue by iamammiin** [pyrocms/pyrocms#4629]
error 500 in "localhost:8000/installer/install"
## preview Error:

exception
:
"Illuminate\Contracts\Container\BindingResolutionException"
file
:
"/media/amin/96E484F5E484D8BF1/MyProject/BackEnd/cmsTest/vendor/laravel/framework/src/Illuminate/Container/Container.php"
line
:
918
message
:
"Target [Anomaly\DashboardModule\Dashboard\Contract\DashboardRepositoryInterface] is not instantiable while building [Anomaly\DashboardModule\Dashboard\DashboardSeeder]."

**Comment by RyanThompson** [comment]
What environment information can you provide?

**Comment by Piterden** [comment]
Why dashboard? Is it edge?

**Comment by iamammiin** [comment]
@RyanThompson  @Piterden   thanks . now worked
