### ISSUE TITLE
Search in my post

### ISSUE THREAD

**Issue by iamammiin** [pyrocms/pyrocms#4630]
hi . 
i want search in  post title and content  . but  now just search in post title

**Comment by Piterden** [comment]
Hi

**Comment by Piterden** [comment]
We have the Slack chat for greetings )

**Comment by iamammiin** [comment]
@Piterden   
i want search in post title and content . but now just search in post title
 what append post content ??

**Comment by Piterden** [comment]
```twig
{{ entries('posts') }}
```
Returns the EntryCriteria which allows you to use any methods of Eloquent API.

**Comment by RyanThompson** [comment]
@aminmohammadmazreali `{{ entries('posts').search('term')... }}` will engage the Scout based search engine as well.
