### ISSUE TITLE
[multiple-field_type] When using Tags config and key_name you can't add records to pivot table

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#4642]
I was hoping to change the related if in the pivot table to be a `slug` instead of `id`.

Used the `tags` config option and set `key_name` to be my `slug` field.

This looked like it was working fine, except when trying to add the form, even though it was using the right entry and the slug to enter, it kept spitting out duplicate entry, when looking at the table in the db, I was getting `entry_id = id,  realted_id = null, sort_order = null`

The passed values were correct of `id,slug,sort_order`.

Removing the `key_name` and just let it be the default ID and reinstalling the module fixes it, and saves just fine.

**Comment by Piterden** [comment]
This happens because the `related_id` column of the pivot is type of `INT(11)`.

**Comment by edster** [comment]
so if key_name == NULL then leave it as is

Else maybe varchar?

**Comment by Piterden** [comment]
Fixed
https://github.com/anomalylabs/multiple-field_type/pull/32

**Comment by Piterden** [comment]
![image](https://user-images.githubusercontent.com/5930429/31526809-de4d62a2-afd1-11e7-8f9f-5f52b3f8a647.png)

**Comment by RyanThompson** [comment]
This was fixed a while ago. Multiple FT is working as it should.
