### ISSUE TITLE
[upload-field_type] required fields always fail on validation when a file is already uploaded

### ISSUE THREAD

**Issue by basv** [pyrocms/pyrocms#4643]
I have 2 streams, each has an upload ft field. The one which is not required works fine. The one which is set as required works fine for the initial upload. But as soon as there already is a file uploaded the validation always fails (using formbuilders).

The field config:
<img width="453" alt="screen shot 2017-10-12 at 20 20 25" src="https://user-images.githubusercontent.com/946871/31512341-d5d638a2-af8a-11e7-83f6-bef72486ee9a.png">

The streams config:
<img width="247" alt="screen shot 2017-10-12 at 20 23 35" src="https://user-images.githubusercontent.com/946871/31512450-4a6fac98-af8b-11e7-8de5-1ebfe94f3e0d.png">

The field in the builder with a file already there (which meets the requirements):
<img width="1176" alt="screen shot 2017-10-12 at 20 12 49" src="https://user-images.githubusercontent.com/946871/31512321-bfa58d94-af8a-11e7-87fb-83cc70cca1da.png">

The validation is triggered:
<img width="528" alt="screen shot 2017-10-12 at 20 12 43" src="https://user-images.githubusercontent.com/946871/31512320-bf84d02c-af8a-11e7-891d-4fa535a9c942.png">

**Comment by Piterden** [comment]
Why don't you use the file/files-ft for it?
Also, why do you need the `photo_` prefix in each field name?

**Comment by basv** [comment]
Because I want a simple upload button in my frontend form for the users, the upload ft gives me that :)

I don't need the prefix, it's just a personal preference.

**Comment by Piterden** [comment]
Thought it is CP

<img width="1176" alt="screen shot 2017-10-12 at 20 12 49" src="https://user-images.githubusercontent.com/946871/31512321-bfa58d94-af8a-11e7-87fb-83cc70cca1da.png">

**Comment by basv** [comment]
Ah yeah, the bug is in the CP, but this same field is also used in a form on my frontend. Somehow it works fine there.

**Comment by Piterden** [comment]
Maybe that field is for frontend? Never used it.

**Comment by RyanThompson** [comment]
@basv what version are you on? 

I have added it to a simple variables group for testing - made required - and it's working fine. This sounds slightly familiar I wonder if you're out of date?

**Comment by basv** [comment]
@RyanThompson I'm at ~1.0.0

**Comment by basv** [comment]
Upgraded to 1.1.0, still encounter the same issue

**Comment by basv** [comment]
@RyanThompson any news on this? :)
