### ISSUE TITLE
[posts-module] enhttps error

### ISSUE THREAD

**Issue by stockhausen** [pyrocms/pyrocms#4645]
Hello everyone, 

sitemap of post-module has de problem

`  <url>
    <loc>https://www.languedoc-wines.com/posts/1-minute-1-vignoble</loc>
		<xhtml:link rel="alternate" hreflang="en" href="enhttps://www.languedoc-wines.com/posts/1-minute-1-vignoble" />
		<xhtml:link rel="alternate" hreflang="de" href="dehttps://www.languedoc-wines.com/posts/1-minute-1-vignoble" />
		<xhtml:link rel="alternate" hreflang="zh-cn" href="zh-cnhttps://www.languedoc-wines.com/posts/1-minute-1-vignoble" />
		<priority>0.5</priority>
		<lastmod>2017-09-25T11:50:46+00:00</lastmod>
		<changefreq>monthly</changefreq>
  </url>`

**Comment by Piterden** [comment]
Fixed
https://github.com/anomalylabs/posts-module/pull/45

**Comment by stockhausen** [comment]
thank you.
