### ISSUE TITLE
[multiple-field_type] When deleting a record from a stream, the records aren't removed/cleaned from the pivot tables when you have a withPivot()

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#4646]
When you use withPivot(), data is no longer cleaned up from the pivot table. Below is how I have configured it.

I have a buildings and sections stream.
A section is related to many buildings and a building can have many sections

Note the below works fine for updating/creating, just deleting is the issue.
The Sections Field
```
'sections'             => [
            'type'   => 'anomaly.field_type.multiple',
            "config" => [
                "mode"     => "tags",
                'related'  => 'Emange\StrataModule\Strata\Section\SectionModel'
            ]
        ],
```

The Building Stream
```
protected $stream = [
        'slug'         => 'buildings',
        'title_column' => 'plan'
    ];

    /**
     * The stream assignments.
     *
     * @var array
     */
    protected $assignments = [
        'name'      => [
            'required' => TRUE,
            'unique'   => TRUE
        ],
        'sections' => [
            'required' => TRUE
        ],
    ];

    public function up()
    {
        parent::up();

        $this->schema()->table('strata_buildings_sections', function (\Illuminate\Database\Schema\Blueprint $table) {
            $table->decimal('formb_price', 5,2)->default('35.00');
        });
    }
```

The building model contains
```
public function sections()
    {
        return $this->getFieldType('sections')->getRelation()->withPivot('formb_price');
    }
```

**Comment by Piterden** [comment]
What pivot table do you mean? I have the correct deleting of records of the pivot table in any multiple type field. I never use cascades for a multipleFT.

**Comment by edster** [comment]
The pivot table.....

The records are only deleting from the main tables, not the pivots.

**Comment by Piterden** [comment]
Can you record a video, then share it in Slack? I have the correct records deleting. I just have re-checked it again...

**Comment by edster** [comment]
I'll play with it on Monday and confirm.

Sent from my Windows 10 phone

________________________________

**Comment by edster** [comment]
So Piterden thinks this might have to do with the extra pivot table data related to the model.

I can pull and modify this data fine using laravel.
`return $this->getFieldType('sections')->getRelation()->withPivot('formb_price');`

I am adding it to the pivot table via
```
public function up()
    {
        parent::up();

        $this->schema()->table('strata_buildings_sections', function (\Illuminate\Database\Schema\Blueprint $table) {
            $table->decimal('formb_price', 5,2)->default('35.00');
        });
    }
```

If this is the cause of the break, its still a bug, shouldn't have anything to do with the records not being deleted.

**Comment by Piterden** [comment]
Well this is your error. It is strange, that you are using migration for adding data to the table. It is wrong from the beginning. You surely should use a seeder for that purpose. Look how I did it some time ago:
```php
$this->pages->create([
    'ru'           => [
        'title'            => $title,
        'meta_title'       => $title,
        'meta_description' => $summary,
    ],
    'en'           => [
        'title'            => $title,
        'meta_title'       => $title,
        'meta_description' => $summary,
    ],
    'slug'         => $slug,
    'entry'        => $entry,
    'type'         => $type,
    'enabled'      => true,
    'home'         => $home,
    'parent'       => $parent,
    'theme_layout' => 'theme::layouts/default.twig',
])->allowedRoles()->sync([]);
```
This code is from the seeder and it removes associated roles.

Then, in the same file I have the oldschool loop for collection ids.
```php
$i   = 1;
$ids = [];

foreach ($images as $image)
{
    $uploaded = new UploadedFile(
        $image,
        $slug . '_' . $i . '.jpg',
        'image/jpeg',
        filesize($image),
        null,
        true
    );

    $file = $this->uploader->upload($uploaded, $folder);

    $ids[] = $file->getId();

    ++$i;

    echo "\033[31;5;228mUploaded {$image}.\n";
}

echo "\033[36;5;228mAll images was uploaded!\n";

$entry->gallery()->sync($ids);
$entry->save();
```

**Comment by edster** [comment]
@Piterden I don't think you understand what I am doing. I'm going to update the details

**Comment by edster** [comment]
This is still an issue and should not be closed.

**Comment by Piterden** [comment]
Oh sorry. Just that was a week, I have thought you had solved it.

**Comment by edster** [comment]
No it is an issue with `withPivot` and multiple relation.

Talked to Ryan about it last week and he needs to enhance the FT he said.

**Comment by Piterden** [comment]
So what about the details? How to achieve that?

**Comment by RyanThompson** [comment]
it's OK this is indeed an issue and I have it on my  internal list for the addon.
