### ISSUE TITLE
Rename `--nested` parameter back to `--tree`!

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4647]
It is unclear not only for me!
https://github.com/anomalylabs/streams-platform/pull/498

**Comment by RyanThompson** [comment]
Why?

**Comment by Piterden** [comment]
Because what is nested? It is unclear! The really clear for making EntryTreeBuilder, is the `--tree` parameter.

Proof:
![image](https://user-images.githubusercontent.com/5930429/31676257-b1fe62cc-b36f-11e7-8dba-23ac7012b6fc.png)

**Comment by Piterden** [comment]
@squatto

**Comment by Piterden** [comment]
@RyanThompson  https://blog.carbonfive.com/2016/10/04/ubiquitous-language-the-joy-of-naming/
