### ISSUE TITLE
[user-module] No username field in admin login

### ISSUE THREAD

**Issue by kiltedup** [pyrocms/pyrocms#4648]
If you switch the login method in settings to username, there is no input field for the username.

core/pyrocms/accelerant-theme/resources/views/login.twig:31

`{{ form.fields.username.setPlaceholder(form.fields.username.label).input_name|raw }}`

should probably be

`{{ form.fields.username.setPlaceholder(form.fields.username.label).input|raw }}`

**Comment by Piterden** [comment]
So did you check it?

**Comment by Piterden** [comment]
https://github.com/pyrocms/accelerant-theme/pull/37

**Comment by RyanThompson** [comment]
This has been fixed - thanks @Piterden !
