### ISSUE TITLE
[relationship-field_type][multiple-field_type] Valuate option text instead of accessor / name approach.

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4655]

**Comment by Piterden** [comment]
What does it mean, sorry?

**Comment by Pixney-William** [comment]
Is this a feature you have "accepted" @RyanThompson , and in that case for what version?

**Comment by RyanThompson** [comment]
This is mostly done. Safer alternative with pluck. Valuate will come later.
