### ISSUE TITLE
[multiple-field_type] Reorganize views structure

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4656]
I had tried to: 
```php
        'forms'       => [
            'type'   => 'anomaly.field_type.multiple',
            'config' => [
                'related' => FormModel::class,
                'mode'    => 'filter', // I just look at views folder, and saw it
            ],
        ],
```
in migration, and I had thought in that moment

How about to use of such of structure for views in any addon? 
```yaml
/resources/views:
  /mode:
    - /checkboxes.twig
    - /lookup.twig
    - /tags.twig
  /table:
    /filter:
      - /index.twig
    /partials:
      - /body.twig
    - /table.twig
```
It promises to be more clear and intuitive.

or even
```yaml
/resources/views:
  /mode:
    - /checkboxes.twig
    - /lookup.twig
    - /tags.twig
  /table:
    /partials:
      - /body.twig
    - /table.twig
    - /filter.twig
```

**Comment by RyanThompson** [comment]
Seems like the same thing as I have minus a level doesn't it? If the addon was more complex there would be more directories

**Comment by Piterden** [comment]
If you would have the same thing, I would never confused with mode define.

I mean modes should be in the `mode` folder.

**Comment by Piterden** [comment]
https://github.com/pyrocms/pyrocms/issues/4652 @RyanThompson

**Comment by RyanThompson** [comment]
I'll likely revisit this when vanilla-izing the FT later.
