### ISSUE TITLE
[streams-core][files-module] Fallback missing images with placeholder.

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4657]
This would be nice and prevents the need to sync local images with remote when working.

**Comment by squatto** [comment]
Are you meaning that something from a place like [https://placeholder.com/](https://placeholder.com/) would show up if the image doesn't exist? My only concern would be if there's an issue on production with an image. A placeholder doesn't look very professional (nor does a broken image, but most browser don't show anything at all nowadays). Maybe make it a setting?

**Comment by Piterden** [comment]
I think each browser has a blank image for showing when image was not loaded

**Comment by squatto** [comment]
Or they typically show the alt text. Something like this:

 
<img width="1178" alt="screen shot 2017-10-19 at 9 47 07 pm" src="https://user-images.githubusercontent.com/748444/31836237-d2458bb8-b591-11e7-9009-7a057e377015.png">

The first, second, and fourth images are showing the alt text.

**Comment by Piterden** [comment]
Oh, alt text is enough professional

**Comment by ghost** [comment]
And don't show thumbnails for larger images.

**Comment by Piterden** [comment]
What you mean larger?

**Comment by Piterden** [comment]
Maybe it would be better to have an ability to enable that placeholder in the settings page of the files-module?

**Comment by ghost** [comment]
I agree with @Piterden , and maybe settings for different extensions as well. Maybe even settings for size/weight when to skip preview and not.

@Piterden i am having some issues with a client where i get errors when it tries to render the thumbnails because the images they upload are very large. And they have reason to upload such large images.

**Comment by squatto** [comment]
That's definitely the route I'd like to see this take. A setting would be ideal.

**Comment by timjai** [comment]
Although it's not strictly related we've created a pyro/twig plugin that allows us to add a placeholder filter that resolves problems on the front end when there's no source image.

General Usage: `<img src="{{ image(item.image|placeholder).fit(370, 250).quality(80).url }}">`

If it's of any interest I'll happily write up some docs and share it 

_tim@evoluted_

**Comment by Pixney-William** [comment]
Please do @timjai all docs and tips are very appreciated by the community!

**Comment by Pixney-William** [comment]
Did you ever share this @timjai ?
