### ISSUE TITLE
[image_field-type] Thumbnail is updated. Not crop area. When i select image

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4658]
After updating to 3.4 i have an error saying `General error: 5 database is locked` as soon as i select an image, using image field type within a grid.  It seems to happen whenever you use the image field type.

The console output gives a 500 error and points to `streams/image-field_type/view/134`

Whenever i have selected an image, the thumbnail of the image field type is updated. But the image within the cropped area is not.

Anyone else having this issue?

**Comment by ghost** [comment]
Setting `SCOUT_DRIVER="null"` in my .env file solves this. 

BUT, is that **really** the way to solve this issue?

**Comment by Pixney-William** [comment]
Is this something we still have an issue with? I have scout driver as null as standard since then so i have no idea.

**Comment by RyanThompson** [comment]
This has been fixed.
