### ISSUE TITLE
The process "composer dump-autoload" exceeded the timeout of 60 seconds.

### ISSUE THREAD

**Issue by joaocosta-azores** [pyrocms/pyrocms#4660]
Hello,

When i created a new theme and i get this message:

```
Addon [client.theme.mytheme] created.


  [Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process "composer dump-autoload" exceeded the timeout of 60 seconds.
```

I already tried running composer dump-autoload but keep getting this message.

What could be the solution?

**Comment by Piterden** [comment]
What OS and what HW do you use?

**Comment by joaocosta-azores** [comment]
I'm running Windows 10.

**Comment by Piterden** [comment]
I suppose it is your environment issue.

**Comment by C-137D** [comment]
i solve this by  running
$ composer dump-autoload
before
$ php artisan voyager:install --with-dummy
