### ISSUE TITLE
Access violation: 1059 Identifier name too long

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4661]
I know this has been issued before twice. Once also by @Piterden .

Question is, how to we handle this? In my case i have my own module with types and this is basically too long : `presentations_exhibitions_presentations_translations_locale_index`

How are others handling this issue? How should we handle it? How should we think regarding naming conventions?

**Comment by Piterden** [comment]
I will not tell you until you change your avatar in Slack! (Hope she don't read your GH)

**Comment by Pixney-William** [comment]
You mean your md5 solution?

**Comment by Pixney-William** [comment]
I changed my avatar @Piterden , now tell!

**Comment by Piterden** [comment]
I found something about it https://www.kerstner.at/2012/07/shortening-strings-using-base-62-encoding/

**Comment by Piterden** [comment]
Strict length limit on a slug-ft would solve this issue.
