### ISSUE TITLE
Add counter to slug field

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4662]
Because of my problem here: https://github.com/pyrocms/pyrocms/issues/4445 , i am using a MAX on my slug field. But i would like a counter too since it would be more obvious to my client to see something actually being counted down.

While we think of the original issue, could we throw in a counter on the slug ?

**Comment by Piterden** [comment]
Agree

**Comment by RyanThompson** [comment]
Counter on all that text stuff pry. And just have a config to toggle it on and off.

**Comment by Pixney-William** [comment]
For what version is this accepted @RyanThompson or is it already completed?
