### ISSUE TITLE
[BUG] [Translations]  : You should not be required to save twice

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4665]
@RyanThompson this one is kind of important.

There is a flaw to the fallback language.

If having two languages, and you have both written, then you go into the secondary language and delete all data from one field and press save, the page should default to the primary language. But it doesn't. It actually requires you to once again save the page to do that.

So we need to make sure, we don't have to save the page twice. As soon as you have deleted the secondary language and hit save, you should fallback to the primary language.

**Comment by RyanThompson** [comment]
After discussion we have two items to take action on:

- The form should not default values based on the default locale.
- The API should assume null as a fallback-able value to the default locale `$se->value ?: $default->value` basically.

**Comment by Pixney-William** [comment]
Agreed

**Comment by RyanThompson** [comment]
This is done partially. Working on the second half of it and spinning up a new issue.
