### ISSUE TITLE
[streams-platform] A clear cache button should exist

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4668]
Should we not have a clear cache button inside the admin as per default?

**Comment by RyanThompson** [comment]
I have thought about something like that in a 'system-module' or something but.. eh. 

I think my main concern is separation of concerns. This is a CLI command typically and very dev oriented. Write an Envoy task for it or something.

**Comment by RyanThompson** [comment]
On that note though not sure how necessary this is and if I would consider building it. Maybe a community member will!

**Comment by RyanThompson** [comment]
In fact.. nah. Need more compelling feature set. Put one together then come back lol. Gotta keep these issues down 🙃
