### ISSUE TITLE
[streams-platform] Fallback to default locale value if translated value is empty.

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4670]
$entry->foo would return $entry->translate(default)->foo if the former is empty

To avoid this behavior you can $entry->translate(locale)->foo 

In other words this only behaves like this on the base model.

**Comment by Pixney-William** [comment]
Are we far away on this ? @RyanThompson

**Comment by RyanThompson** [comment]
Newp

**Comment by Pixney-William** [comment]
Let me know if there is no time for this @RyanThompson and ill write something to handle this on my site temp because we have issues with it since no content shows up on pages if they forget writing content.

**Comment by Pixney-William** [comment]
If i am not mistaken. This is sorted @RyanThompson . Closing
