### ISSUE TITLE
[image-field_type] We must have a max height of the cropping area

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4671]
Thank you very much for the 1.3, @RyanThompson . It's great! Except for one thing. We have lost the max-height which means that images are hard to manage when cropping since the height of the image could be a lot taller than the screen size.

You want to be able to see all of the image/crop area within your screen. So would you be so kind, setting a max-height to calc(100vh - WHATEVERTHESIZEISOFTOPBARANDFOOTER) ?

**Comment by ghost** [comment]
https://github.com/anomalylabs/image-field_type/pull/16

**Comment by ghost** [comment]
Merged and fixed, close it

**Comment by ghost** [comment]
Fixed @Piterden

**Comment by ghost** [comment]
I was the one who did the pull request @Piterden , i think it might be smarter to assign it to dwains or someone to test:)

**Comment by Piterden** [comment]
I can't, sorry(
