### ISSUE TITLE
The window scrolls down which it shouldnt

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4672]
I have a presentations module, with a files fieldtype in it (and other fields). When i open it to edit, the window always scroll down to the files field type. It shouldn't. The scroll should always be at top when you open this.

**Comment by RyanThompson** [comment]
Note to myself/whomever. This needs to be smarter: https://github.com/anomalylabs/streams-platform/blob/1.3/resources/js/form/form.js#L6
