### ISSUE TITLE
Error rendering edit view after anomaly/streams-platform (v1.3.51 => v1.3.52)

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4674]
When i updated to streams platform 1.3.52 from 1.3.50 i got this error..

An exception has been thrown during the rendering of a template ("An exception has been thrown during the rendering of a template ("An exception has been thrown during the rendering of a template ("An exception has been thrown during the rendering of a template ("An exception has been thrown during the rendering of a template ("Array to string conversion").").").").").

**Comment by ghost** [comment]
```
{% for field in fields %}
    <div class="field-group {{ field }}">
        {% for field in form.fields.translations(field) %}
            {{ field.render({'form': form})|raw }}
        {% endfor %}
    </div>
{% endfor %}
```

**Comment by ghost** [comment]
in `resources/views/form/partials/fields.twig`

**Comment by Piterden** [comment]
Field type not defined, as I remember. Something brakes fields config.

**Comment by ghost** [comment]
Confirmed 1.3.50 works fine. But not 1.3.52 .

@Piterden are you saying you know what @RyanThompson did to make it fail?

**Comment by Piterden** [comment]
Git knows, check the diff

**Comment by ghost** [comment]
1.3.51 works not 1.3.52.

I will check..

**Comment by Piterden** [comment]
I took 1.3.50 vs 1.3.52
![image](https://user-images.githubusercontent.com/5930429/32142678-365c2752-bcad-11e7-853a-5a2bb63e716b.png)

And `streams-platform-1.3.50/resources/views/table/partials/body.twig`

**Comment by ghost** [comment]
you should take 1.3.51vs52.. the issue has to do with the getAttributes method added

**Comment by Piterden** [comment]
Fix you! I don't have time now

**Comment by ghost** [comment]
Neither do i.. i have to drive my snowmobile

**Comment by Piterden** [comment]
What will you give me for Christmas, Santa?

**Comment by Piterden** [comment]
I think, we need some global avoiding of Twig exceptions. How are you about it?

**Comment by Piterden** [comment]
Did you fix it? @designbywilliam

**Comment by ghost** [comment]
Its fixed now @Piterden
