### ISSUE TITLE
[Documentation] The pyrocms.com site throws 500 error's

### ISSUE THREAD

**Issue by MarGul** [pyrocms/pyrocms#4676]
Hey. 
Wasn't sure where to get in contact with you guys to I'm opening an issue for this instead. Almost everywhere on www.pyrocms.com I get 500 errors (videos, invite for slack,...).

Just wanted to see if the resources has been moved or there is any problem on my part. Best thing would be to get an invite to the slack channel so we can close this "issue".

**Comment by Piterden** [comment]
I have videos and invite working good. Check once more please.

Links are appreciated.

**Comment by MarGul** [comment]
Thanks for the reply. I have tried two computers, different browsers and everything and I still get this:

Maybe yours is cached?

![pyrocms](https://user-images.githubusercontent.com/11759765/32161250-1fe93dd6-bd55-11e7-902e-095715149e84.png)

**Comment by Piterden** [comment]
Maybe it is your cached?
![image](https://user-images.githubusercontent.com/5930429/32185589-a103703e-bdb0-11e7-858f-eec795843d28.png)

**Comment by Piterden** [comment]
Check the certificate you have, it seems I have another one.
