### ISSUE TITLE
[forum-module] Issue with pages and/or files type reported in the forum

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4681]
https://pyrocms.com/forum/channels/field-types/files-field-type-record-not-deleted-when-you-delete-the-related-stream

**Comment by Pixney-William** [comment]
Has this been fixed so we can close the issue @RyanThompson ?

**Comment by RyanThompson** [comment]
Working on it - GC in general needs work

**Comment by RyanThompson** [comment]
I have sep tasks for these as its more widespread. Closing.
