### ISSUE TITLE
Cache is not being invalidated when using pagination

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4683]
This does not work:

```
{% set newslist = entries('posts').recent().paginate() %}
{% cache newslist 100 %}
    {% include "theme::news/news-item" with {"newslist": newslist} %}
{% endcache %}
```

Ryans comment : "Spin up an issue for this I can add it. Should be pretty straight forward to get a cache key like this."

**Comment by RyanThompson** [comment]
Cache now treats paginators like collections but might wanna use a better strategy since entries on other pages are unable to be considered.
