### ISSUE TITLE
[streams-platform] Can't install addon with a simple folder copying

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4684]
Earlier that worked fine, and I could just move a folder with my addon to the right place.

Now I have error after moving, and I have to call `make:addon` command first, then replace all files in the created by the command folder.

**Comment by Pixney-William** [comment]
Is this still an issue/problem? @RyanThompson ?

**Comment by Eighke** [comment]
I think it was just the `composer dump-autoload`, I remember speaking about that on Slack

**Comment by Pixney-William** [comment]
thanks  @Eighke . Closing it.
