### ISSUE TITLE
Adding a grid without assigned fields throws an error

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4685]
In a migration i have created a new grid stream (this grid namespace is assigned to default_pages).

I go into the page, and it has no previous rows added.

I click on add new row, select the grid and hit save. `An error is thrown`

If i instead, add another grid to the page. And click save. And then add this grid and click save. It all works.

If i remove all the grids again. Click save. Then add this grid and click save. `Same error is thrown`.

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'entry_id' cannot be null 
(SQL: insert into `project_pages_default_pages_grid` 
(`related_id`, `entry_id`, `entry_type`, `sort_order`) values 
(35, , Anomaly\Streams\Platform\Model\Grid\GridPresentationsEntryModel, 0))

```

**Comment by Piterden** [comment]
Just tell us where to move that error? Where would be the best place for it?

**Comment by Pixney-William** [comment]
Are you asking me @Piterden

**Comment by Piterden** [comment]
How do you know it. Did I tell you?

**Comment by Pixney-William** [comment]
Reminder to myself to test to see if this has been fixed.
