### ISSUE TITLE
Setting a language problem

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4686]
When you have a website for/with people of different nationalities, the users should be able to set their preferred language under preferences.

* Logging in as a Swedish site admin , i would like my preference lang setting to be English.
* Logging in as a Chinese webmaster, i would like my preference lang setting to be Chinese.

Today, if i as a user change my preference settings for lang, it affects all users.

**Comment by keevitaja** [comment]
Admin locale switching is session based. So if you change your locale in admin, it kinda sticks with your session and takes precedence in frontend. Pretty ducked up!

**Comment by Pixney-William** [comment]
K, we need to fix this!

**Comment by RyanThompson** [comment]
This is all working as it should. Don't use session language picker if you desire your preferences language. The two items have to coexist for different reasons. Preferences is your preference. When you set it via the CP selector you are actively choosing otherwise.
