### ISSUE TITLE
Accelerant style issue for repeaters (within grids only?)

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4687]
https://imgur.com/a/GuIEA

**Comment by Piterden** [comment]
![image](https://user-images.githubusercontent.com/5930429/32689486-158a41ea-c6f7-11e7-80a0-f7d13cc9b012.png)
WTF, William? Do you forget about `ctrl+v`?

Do you mean big margins?

**Comment by Piterden** [comment]
You are the good in CSS! Fix it))

**Comment by Pixney-William** [comment]
I am not sure it should be fixed in a fieldtype.. I think this styling should be per theme. Otherwise it wont be fun creating themes.

I fixed in the hjortron theme, and have to do this to change it which is not good...

`.grid-container .repeater-field_type .repeater-container .repeater-item .repeater-body .form-group`
