### ISSUE TITLE
[country-field_type] Documentation incorrect or bug

### ISSUE THREAD

**Issue by emergingdzns** [pyrocms/pyrocms#4688]
The documentation for the Country field type (https://pyrocms.com/documentation/country-field-type/latest) states that there is a "text" mode and "text" is used in the default example. However, when using "text" it throws an error in the form builder like the one shown here: https://pyrocms.com/forum/channels/modules/error-in-twig-view-text-not-found-on-using-form-builder

Either there is no text mode or the text mode functionality is broken.

**Comment by Piterden** [comment]
Fixed. Thanx)
