### ISSUE TITLE
[redirects-module] Redirections not working for from URI starting with `posts`

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#4689]
Hello,

`some-slug` -> `some-new-slug` works perfectly fine, but

`posts/some-slug` -> `posts/some-new-slug` does not!

I guess all routes starting with `posts` are routed to some posts controller and it never hits the redirection.

**Comment by Piterden** [comment]
You are the lucky guy. Me was need to learn Nginx's redirects.

**Comment by keevitaja** [comment]
How me lucky? Me too did nginx redirect now!

**Comment by Pixney-William** [comment]
@RyanThompson i remember this one. If i remember correctly it was something didn't really wanna jump on. Is that the same now?
