### ISSUE TITLE
Problem with unit testing. Clean Pyro install on XAMPP and Homestead / Windows

### ISSUE THREAD

**Issue by vargvinter** [pyrocms/pyrocms#4697]
I am unable to run tests.

It returns:
```
ReflectionException: Class Anomaly\TestModule\TestModule does not exists
```

Problem occurs on XAMPP and Homestead as well. 
Thread on the official forum: https://pyrocms.com/forum/channels/general/how-to-configure-the-test-environment-in-pyrocms-vagranthomestead/

**Comment by Piterden** [comment]
Do you have the `anomaly/test-module` package?

**Comment by vargvinter** [comment]
`C:\xampp\htdocs\pyrocms> composer require anomaly/test-module --dev`

Throws:
```
  [InvalidArgumentException]
  Could not find package anomaly/test-module at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

**Comment by Piterden** [comment]
What about `php artisan make:addon anomaly.module.test`?

**Comment by vargvinter** [comment]
Done.
Then `php artisan addon:install anomaly.module.test`

After phpunit run bunch of:
```
ReflectionException: Class Anomaly\TestPlugin\TestPlugin does not exist
```

**Comment by Piterden** [comment]
`php artisan make:addon anomaly.plugin.test`

Did you have some logical test in school?

UPD ^

Only modules and extensions should be installed.

**Comment by vargvinter** [comment]
All done.
Tests work.
Thanks.

Shouldn't it be in docs?

**Comment by fryiee** [comment]
This isn't a fix btw, you just created a blank addon that had the same namespace in core that mimicks the test addon in vendor.
