### ISSUE TITLE
Forms in CP not return its page scroll position after save.

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4698]
Actually I don't want page to be reloaded during save, but it's pointless to talk about it.

It is very uncomfortable that page not returns scroll position. Could we fix it? @RyanThompson

**Comment by Piterden** [comment]
And it happens even in frontend.

**Comment by fryiee** [comment]
I think this is probably best handled in theme. It's not a universal and requires fixing the position of form messages.
