### ISSUE TITLE
Can't override validation messages.

### ISSUE THREAD

**Issue by vargvinter** [pyrocms/pyrocms#4699]
I do `php artisan streams:publish`

Changes in `/resources/lang/xx/validation.php` or in `/resources/default/streams/lang/xx/validation.php` don't take effect. 

Changes in `vendor/anomaly/streams-platform/resources/lang/xx/validation.php` take effect.

Of course I don't want to mess in core.

Solution?

**Comment by Piterden** [comment]
This is the bullshit man.

I have publish streams and edit `resources/default/streams/lang/en/validation.php`.

All works fine!

![image](https://user-images.githubusercontent.com/5930429/33468196-82e5072e-d66b-11e7-8742-ffeaf70b0d40.png)

**Comment by vargvinter** [comment]
Ok, I have new thoughts. Currently I am developing on XAMPP and my validation messages overrides don't work.

But I have also Vagrant/Homestead machine and it works fine.

No idea why. In both environments I have default pyro installation 
That's frustrating.

Do you need any more information?

**Comment by Piterden** [comment]
Why would me need it? It is your environments issues, which have not any relation to PyroCMS.
Try to work on linux.

**Comment by Pixney-William** [comment]
@RyanThompson do you have any comments to this one to help @vargvinter with the issue?
