### ISSUE TITLE
[country-field_type] top_options config not being used in drop down.

### ISSUE THREAD

**Issue by emergingdzns** [pyrocms/pyrocms#4702]
I've got a list of top options but they are not being added to the top of the dropdown.

Please see forum thread for more details: https://pyrocms.com/forum/channels/field-types/country-field-type-sorting-is-wrong-and-ignoring-top-options

**Comment by Piterden** [comment]
Forum is shitty!
I think, it should be only one select-FT, which could load a different data sets.

**Comment by Pixney-William** [comment]
@RyanThompson Is this still an issue? Seems like it was confirmed on the forum but i haven't had time to verify it. Maybe you know better if it is @emergingdzns ?

**Comment by RyanThompson** [comment]
Fixed this and also added `shouldSort: false,` to the other choices.js related FTs: https://github.com/anomalylabs/country-field_type/commit/c958a732053f8440c8a05cff7b5654b8fc807415
