### ISSUE TITLE
[translator-module] There is a BIG BUG in translate `field.php`

### ISSUE THREAD

**Issue by oimken** [pyrocms/pyrocms#4703]
Could not save translations in `field.php` and `notification.php`  and any translations has sub-array translations,  for example:

### translator module can handle 'addon.php' ( Flat array ? ) fine. 
```
return [
    'title'       => 'Comments',
    'name'        => 'Comments Module',
    'description' => 'A powerful commenting system.',
];

```
### But failure to save Multi-dimensional arrays such as `field.php` , it just empty my translations like below!!!
```
<?php
return [
                        'name' => [
                ],
                                'reference' => [
                ],
                                'domain' => [
                ],
                                'enabled' => [
                ],
                                'username' => [
                ],
                                'email' => [
                ],
                                'password' => [
                ],
                                'application' => [
                ],
            ];

```

**Comment by Piterden** [comment]
https://github.com/anomalylabs/translator-module/pull/25

**Comment by Eighke** [comment]
https://github.com/anomalylabs/translator-module/pull/25 isn't working, but https://github.com/anomalylabs/translator-module/pull/24 fixed the problem

**Comment by Piterden** [comment]
So make correct changes and PR

**Comment by Eighke** [comment]
I think you can merge the anomalylabs/translator-module#24 directly. I don't want to get his contribution. :)

**Comment by RyanThompson** [comment]
This has been resolved and twig2 versioned up in a new branch for streams platform 1.3
