### ISSUE TITLE
[datetime_field-type] Impossible to configure different time representation

### ISSUE THREAD

**Issue by pepijnolivier** [pyrocms/pyrocms#4705]
By default the datepicker represents time via AM / PM notation.

Seems like it doesn't support configuring a different representation (for example, European notation is 23:59 instead of 11:59 AM)

**Comment by Piterden** [comment]
Did you try to set
```php
'time_format' => 'H:i',
```
???

**Comment by pepijnolivier** [comment]
Yup,

Here's my field definition in the formbuilder

```
'end_date' => [
   'label' => 'End time,
   "type" => "anomaly.field_type.datetime",
   'required' => true,
   'config' => [
       "plugin_format" => "d/m/Y H:i",
       "date_format"   => "d/m/Y",
       "time_format"   => "H:i",
       'mode' => 'datetime'
   ]
],
```

**Comment by Piterden** [comment]
Mixing of `"` and `'` is the bad practice.
![image](https://user-images.githubusercontent.com/5930429/34048323-5d07c41a-e1c4-11e7-8f38-b854e061b0e3.png)

**Comment by pepijnolivier** [comment]
I agree, that's not really the issue though. Can you advise on the actual problem ?

**Comment by Piterden** [comment]
Don't you see your config is working for me?

**Comment by Piterden** [comment]
And the only one difference is quotes!

**Comment by pepijnolivier** [comment]
The quotes shouldn't matter, but thanks for running my code. Now I know it *should* work...
Just updated the datetime package to the latest version, still no dice...

**Comment by pepijnolivier** [comment]
@Piterden Just to be sure, you used this config in a FormBuilder field definition, right ?

**Comment by Piterden** [comment]
I have `"anomaly/datetime-field_type": "~3.0.0",`.

Yes, it is the `fields` array of a single form builder.

Quotes are important, believe me. I can't explain it, and I was surprised about it too. It's just the fact)

**Comment by pepijnolivier** [comment]
I ran composer update and the problem was solved.
I have a hunch this was a bug in the streams platform, but I'm just guessing.

@Piterden single quotes behave differently compared to double quotes, but in this case, it has no effect. [More info](https://stackoverflow.com/a/3446286/237739)
