### ISSUE TITLE
[datetime-field_type] Cannot set null value

### ISSUE THREAD

**Issue by mjlizard** [pyrocms/pyrocms#4706]
In Datetime FieldType there is no way to set null value.
For example, I have custom news module with datetime field: publicating news until date. When I change my mind and I want to reset this value, there is no way to do it, even if I manualy delete date from input.
There should be option to allow send via form null values and save it in database.

**Comment by fryiee** [comment]
Did https://github.com/anomalylabs/datetime-field_type/pull/30 this merge fix your issue?

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/datetime-field_type/commit/8d61288a1c3f995f356aa7a49698282368408d47
