### ISSUE TITLE
Overwrite streams-platform .twig files

### ISSUE THREAD

**Issue by mjlizard** [pyrocms/pyrocms#4707]
I can't overwrite default .twig files (from streams-platform). If I well understand a very modest project documentation, there should be option to overwrite:
**/vendor/anomaly/streams-platform/resources/views/form/form.twig**
using this file:
**/resources/default/streams/views/form/form.twig**
Unfortunately, PyroCMS ignoring second file and forcing first. This makes it impossible to overwrite streams-platform files.

**Comment by vargvinter** [comment]
I can confirm.

`php artisan streams:publish` is publishing views but changes made in published files are not reflected. Pyro always use core view files.

**Comment by Piterden** [comment]
I use it in my theme's SP
```php
    /**
     * The addon overrides.
     *
     * @type array|null
     */
    protected $overrides = [
        'streams::form/standard'        => 'theme::document/form',
        'streams::form/partials/layout' => 'theme::form/partials/layout',
        'anomaly.module.users::login'   => 'theme::login',
    ];
```

**Comment by Piterden** [comment]
So, @vargvinter @mjlizard, does it work now?

**Comment by vargvinter** [comment]
Yes, creating custom theme did the trick.
