### ISSUE TITLE
[streams-platform] Addon field translations not working properly with multidimensional arrays

### ISSUE THREAD

**Issue by Dinushasilva** [pyrocms/pyrocms#4710]
**Field Type = textarea**
**PyroCMS = v3.4.10**

This is not working, as the field is unable to show the instructions on all three fields (movies,series,topics), it will only show on the first field which is (movies).

```
return [
    'description' => [
        'name' => 'Description',
        'instructions' => [
            'movies' => 'Brief description about the Movies.',
            'series' => 'Brief description about the Series.',
            'topics' => 'Brief description about the Topics.',
        ]
    ],
];
```

But this will work

```
return [
    'description' => [
        'name' => 'Description',
        'instructions' => 'Brief description.'
    ],
];
```

**Comment by Piterden** [comment]
You set translations for only one field, which is description.

**Comment by Dinushasilva** [comment]
as in?

**Comment by Piterden** [comment]
Instructions property must be a string value

**Comment by Dinushasilva** [comment]
But it's working for name field, you mean Instructions can't be an array type?

**Comment by Piterden** [comment]
Yes, it must be string

**Comment by Dinushasilva** [comment]
But then how can we use it for multiple fields? let's say if we have **description** field on three different streams?.

How can we manage unique instructions for all three?.

**Comment by Piterden** [comment]
The thing is you have fields attached to the domain, which is the module in our case. Streams have assignments, not fields. And assignment item can override fields settings.

**Comment by RyanThompson** [comment]
This should indeed be working and I see it working elsewhere.. might be a compiler issue. I'll look into it though.

**Comment by RyanThompson** [comment]
@Dinushasilva does re-compiling the streams fix this?

**Comment by Dinushasilva** [comment]
@RyanThompson , Sorry i couldn't mention that, yup recompiling the streams would do the fix,

if anyone needs a temporary fix,

```
php artisan streams:cleanup
php artisan streams:compile
```

**Comment by Pixney-William** [comment]
@RyanThompson did you fix this?
