### ISSUE TITLE
[image-field_type][settings-module] Image value not saving at settings

### ISSUE THREAD

**Issue by girvydas** [pyrocms/pyrocms#4714]
If ‘anomaly.field_type.image’ field type is added to form, this value is not saving at settings module. After save, value in database table is null.

But everything works fine with "anomaly.field_type.file".

Bug appears on:
"anomaly/streams-platform": "~1.3.0",
"anomaly/settings-module": "~2.1.0",
"anomaly/image-field_type": "^1.2",

**Comment by Piterden** [comment]
So use file

**Comment by RyanThompson** [comment]
Settings does not support fields that require more than one column OR a pivot table currently.
