### ISSUE TITLE
Translatable field_type-text is repopulated for languages that have null value in DB with default translation on form edit

### ISSUE THREAD

**Issue by vargvinter** [pyrocms/pyrocms#4715]
Hello,

So this is the case:

- I have three languages on the page (`EN`, `DE`, `PL`), where `EN` is default,

- In the form I have translatable and required text input and I want to provide value only for `EN` translation (because it is required) - it works fine for creating the record (translations for `DE` and `PL` languages are set to `null` in DB),

- When I edit this record the **text input is populated for `DE` and `PL` translations with `EN` text**,

This is undesirable behaviour because translations for `DE` and `PL` languages are in fact `null`.
If the user does not clear the text input from `DE` and `PL` translations manually they will be persisted in DB on update. 
Moreover, the user **may not be aware** that other translations where populated with text in default translation and persisted to the DB!

**Comment by Piterden** [comment]
Are you talking about frontend, or CP?

**Comment by vargvinter** [comment]
I am talking about CP.

It's nice for listings. When I browse panel in `DE` locale, `null` values take default translation.

But for form editing it is very confusing and undesirable.

**Comment by Piterden** [comment]
Can you please describe what behavior for required and translatable fields you are waiting?

**Comment by vargvinter** [comment]
Given we have table with translations:

![screen](https://user-images.githubusercontent.com/6939116/34627622-99e5e396-f261-11e7-8dda-659db2a592a2.png)

When I go to this record edit page I should see text `Foobar` for `EN` translation **only**. For translations `DE` and `PL` (when I toggle dropdown with locales next to a label) this field should be blank because there is `null` in DB table.

Now all translations have `Foobar` value in this text field which in my opinion is wrong.

I hope I am clear enough.

**Comment by Piterden** [comment]
It was clear enough. Tell me next thing, please.
What is your opinion about having `null` in the DB for required fields?

**Comment by Piterden** [comment]
The behavior of using a fallback locale works correctly there. It shouldn't allow you to save item before all locales wouldn't be filled.

It is my official opinion about this situation!

**Comment by Piterden** [comment]
```php
protected $stream = [
    'slug' => 'slugs',
    'translatable' => true,
];

protected $fields = [
    'name' => [
        'type' => 'anomaly.field_type.text',
    ],
];

protected $assignments = [
    'name' => [
        'required' => [
            'en',
        ],
    ],
];
```

**Comment by vargvinter** [comment]
@Piterden 
> What is your opinion about having `null` in the DB for required fields?

Not `null` for default translation. `null` for other translations. 

@Piterden 
> The behavior of using a fallback locale works correctly there. It shouldn't allow you to save item before all locales wouldn't be filled.

So, it does not work as you described it. 

- For record creation: Pyro does not force you to fill all translations for required and translatable field. It **only requires default translation** (`EN` in our example - if not filled form validation will fail and redirect back with form errors). Other translations may be left blank.
- For record update: Pyro does not force you to fill all translations for required and translatable field too **but** it populates others than default translations with default translation field value. I can manually clear them (besides `EN` translation because form validation will fail) and update will pass.
But I don't want translations fields (`DE` and `PL`) to be populated because they were blank upon record creation and should still stay blank.

I made a little test:
I have created **not** required and translatable field. Unfortunately, on record edit not filled translations upon record creation are populated with default translation value. :(

**Comment by vargvinter** [comment]
Is there a solution for the time being? Am I able to control field population in controller's edit method manually?

**Comment by RyanThompson** [comment]
I am taking a look at this now.

**Comment by RyanThompson** [comment]
Should take care of this! Thanks for the information guys.

https://github.com/anomalylabs/streams-platform/commit/2c3db2f499b3c5a99059591f793addfa670cd1ef
