### ISSUE TITLE
[repeater-field_type] erase field from repeater not working

### ISSUE THREAD

**Issue by michvh-dev** [pyrocms/pyrocms#4717]
When a filled in repeater field you want to erase is it not working. When clicking update the value is filled back in. (version streams ~1.3.0 & repeater ~1.3.0)

**Comment by Piterden** [comment]
Sorry, what? Try to use GTranslate...
And screenshots would be nice, too.

**Comment by michvh-dev** [comment]
After further research it is not the repeater but the datetimefield. When you want to change a datetime field value it is not changing. It is the latest version of the datetimefield

**Comment by Pixney-William** [comment]
This is not longer an issue, however there is a new one : https://github.com/pyrocms/pyrocms/issues/4805
