### ISSUE TITLE
[country-field_type@2.3.2] - Countries options list issue

### ISSUE THREAD

**Issue by vargvinter** [pyrocms/pyrocms#4719]
After update to v2.3.2 a value of option in dropdown has number instead of country code. Storing number instead of country code in database breaks other things like displaying country for given record.

Is:
`<option value="0" selected="">Andorra</option>`

Should be:
`<option value="AD">Andorra</option>`

**Comment by fryiee** [comment]
This is absolutely a bug, and should be fixed ASAP. Broke a production site pretty badly.

**Comment by fryiee** [comment]
Fixed in https://github.com/anomalylabs/country-field_type/pull/13

**Comment by vargvinter** [comment]
https://github.com/anomalylabs/country-field_type/pull/14
