### ISSUE TITLE
[repeater-field_type] Rows/Column Layouting Doesn't work

### ISSUE THREAD

**Issue by dakshhmehta** [pyrocms/pyrocms#4720]
The scenario: Trying to generate invoice layout, which has purchase details, vendor name etc as common.
However, PurchaseItem stream is repeater powered and would like to align it with 4/4/4 name/qty/amount respectively in the design.

The problem: Section grid alignment as per rows/columns within section doesn't render properly. However, the same form being used directly from the controller can render.

The problem as I found:
In repeater/form.twig, we use 	{{ form.render_fields|raw }}
which is wrong.

To replace this, we should actually use streams::form/partials/layout as form_view option.

I tried for same, however, when done, It render the grid but not the field itself.
So, the root cause found in streams::form/partials/fields.twig, as the following loop is not getting executed.

```php
{% for field in form.fields.translations(field) %}
    {{ field.render({'form': form})|raw }}
{% endfor %}
```

Hope we can resolve it in upcoming repeater updates.

Feel free to ask any doubt/query if above explanation has any confusion.

**Comment by Piterden** [comment]
What if you replace `form.render_fields` to just `form.render`?

```twig
<div class="form">
    {{ form.render|raw }}
</div>
```

**Comment by Pixney-William** [comment]
@RyanThompson & @dakshhmehta is this still an issue or can we close it?

**Comment by dakshhmehta** [comment]
Hi, sorry not been much active as PyroCMS project was completed. I'll check it next week and update you. Starting new project again.
