### ISSUE TITLE
[streams-platform] Additional locales problem - throws 404

### ISSUE THREAD

**Issue by vargvinter** [pyrocms/pyrocms#4721]
- `php artisan streams:publish`

- in `resources/default/streams/config/locales.php` I add new language (Czech in this case because I need it) to the `supported` array:

```
...
        'cz'    => [
            'direction' => 'ltr'
        ],
...
```

- Then in Control Panel in Settings I check Czech language.

- Select dropdown next to the translatable fields has Czech language - great.

- When I go to my-site.org/cz/some-url **it throws 404.**

- Works if I overwrite the core `vendor/anomaly/streams-platform/resources/config/locales.php`

I don't want to overwrite the core. What to do?

**Comment by keribend** [comment]
I have this problem also, the published config files are only loaded after the request has already been modified by `Anomaly\Streams\Platform\Http\Kernel::defineLocale`.

**Comment by Pixney-William** [comment]
@keribend and @vargvinter is this still an issue?

**Comment by keribend** [comment]
@Pixney-William last update on my project is about three months ago and yes, it was still an issue. Don't know if at the moment of writing there are new updates with fixes.

**Comment by Eighke** [comment]
It is "normal", the `supported` locales are checked in the Kernel before the config to be set. You can override it in '/resources/core/config/streams/locales.php'.

So to add new locales you need to override both files.

**Comment by Pixney-William** [comment]
@RyanThompson Could you have a look at this and see if you feel this might still be an issue or if your fix really fixed it? I get the feeling maybe @Eighke was after something else?

![discussion](https://user-images.githubusercontent.com/31292231/42029875-3d3b9700-7ad1-11e8-9c9b-f370c28865f5.jpg)

**Comment by RyanThompson** [comment]
I think the "proper" fix to this would be to submit a PR adding the locale. We can't test overrides at the kernel level cause it's too early and we need the matching there to decipher if the fisrt segment / subdomain is indeed a locale OR a 2 letter segment for whatever reason.

**Comment by RyanThompson** [comment]
Also we have CS as the hint for that locale which I've found to be generally accepted.
