### ISSUE TITLE
[ streams-platform ] Exception when on login with fresh install

### ISSUE THREAD

**Issue by ddnetters** [pyrocms/pyrocms#4722]
Streams-platform throws an exception when trying to log into the admin panel on a fresh install.

# Exception
```
Call to a member function setActive() on array
```
## File
https://github.com/anomalylabs/streams-platform/blob/1.3/src/Addon/Module/Listener/DetectActiveModule.php#L107

# Steps to reproduce
1. `pyro new mysite`
2. `php artisan install`
3. Fill in login form at `mysite.localhost/admin`

**Comment by ddnetters** [comment]
Same goes for the other code in the handle function. `$module->getVendor()` gets called on an array.

**Comment by bbrala** [comment]
Hmm, just saw the same in a fresh install...

**Comment by ddnetters** [comment]
Temp fix is to add
```
        if (is_null($key)) {
            return null;
        }
```

To the `AddonCollection`s `get()` function

Ryan is pushing a fix as we speak

**Comment by Piterden** [comment]
I use only `composer create-project`

**Comment by ddnetters** [comment]
Issue fixed see:
https://github.com/anomalylabs/streams-platform/commit/fa5f60c88e435be82d3847c6abab98bf7f0aa49d
