### ISSUE TITLE
php artisan make:addon my-addon.module.news fails

### ISSUE THREAD

**Issue by bbrala** [pyrocms/pyrocms#4723]
When using dash in the addon name, creation fails. 

```
In ConfigureCreator.php line 69:

  Addon could not be found.
```

When not using a dash, all is fine. Perhaps the input should be checked?

**Comment by Piterden** [comment]
`php artisan make:addon b_brala.module.news`

**Comment by bbrala** [comment]
Yeah, i understand the fix, but if the input is invalid, shouldn't that be checked by the command?

**Comment by Piterden** [comment]
It would be nice. Make a PR )))

**Comment by bbrala** [comment]
@ddnetters Ah, just made a PR, it uses preg_match to check for valid charactes. I see in your PR that it just checks for dashes, which would still mean other characters would pass right?

**Comment by RyanThompson** [comment]
Thanks @bbrala
