### ISSUE TITLE
[users-module] Users must have access to users module to access back-end

### ISSUE THREAD

**Issue by ddnetters** [pyrocms/pyrocms#4724]
When you login to the backend at `/admin`, the `/admin` page tries to redirect you to `/admin/dashboard`. However the `AuthorizeModuleAccess` middleware prevents this redirect and throws a 403 if the user's not allowed to atleast read the users stream.

## Steps to replicate
1. Create a user role that only has access to pages
2. Try to login with a user which has only that role

**Comment by okaufmann** [comment]
I had the same problem and solved it by giving access to the Dashboard by ticking the following Permission:

![image](https://user-images.githubusercontent.com/4414498/35290522-caed5ebc-006a-11e8-801f-bd3a8cf984f2.png)

**Comment by okaufmann** [comment]
I can confirm this behaviour...

**Comment by Pixney-William** [comment]
Confirmed also on 

![image](https://user-images.githubusercontent.com/31292231/42027842-f6a0396e-7aca-11e8-924c-aef5fbc6128d.png)

**Comment by RyanThompson** [comment]
This should be fixed now - it tries to redirect to you the first addon you have access to at all.
