### ISSUE TITLE
[streams-platform] Class 'TestCase' not found immediately after install

### ISSUE THREAD

**Issue by mattdillon100** [pyrocms/pyrocms#4725]
Following the installation instructions and immediately running `phpunit` results in the following error:
```
Fatal error: Class 'TestCase' not found in [...]/vendor/anomaly/streams-platform/tests/Unit/Addon/AddonCollectionTest.php on line 3
```
I have tried installing using the web interface and the CLI but get the same result.

My phpunit.xml is unchanged.

PHPUnit version is **6.6.5**

**Comment by mattdillon100** [comment]
After looking into this a little more, it seems that namespacing isn't set up correctly for the test classes. Pyro installed Laravel 5.5 but the `TestCase` class (tests/TestCase.php) doesn't have any namespacing. Adding `namespace Tests;` changes the error to
```
ReflectionException : Class Anomaly\TestModule\TestModule does not exist
```
when PHPUnit is ran.

Can we please get some feedback on this?

**Comment by Piterden** [comment]
You should develop only inside  your own addon, using Pyro. So, tests should be there too.

**Comment by mattdillon100** [comment]
How are we to run application-wide tests? this being part of our deployment procedure.

By adding `"tests/TestCase.php"` to the autoload classmap in `composer.json` I have got tests running, but all fail with:
```
ReflectionException : Class Anomaly\TestAdminTheme\TestAdminTheme does not exist
```

**Comment by vargvinter** [comment]
@wildcard27 Try this: https://github.com/pyrocms/pyrocms/issues/4697

**Comment by mattdillon100** [comment]
@vargvinter Already tried. All tests still fail. You will see by the error I have referenced that the suggestions in that thread would not fix the issues.

@Piterden presumably you would have had all tests passing prior to release(?). Can you please explain how?

**Comment by mattdillon100** [comment]
The open pull request (https://github.com/pyrocms/pyrocms/pull/4727) seems to fix all. Can we get an ETA as to when this will be implemented please?

**Comment by RyanThompson** [comment]
Merged
