### ISSUE TITLE
[files-module] Prevent nasty file names cause it breaks downloads.

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4726]

**Comment by fryiee** [comment]
@RyanThompson I'll look into this. Is this in the FileDownloader class itself?

**Comment by Pixney-William** [comment]
Did you ever look at this @fryiee ?

**Comment by fryiee** [comment]
@Pixney-William no, I haven't had a chance.

**Comment by Pixney-William** [comment]
@RyanThompson Could you please define a nasty file name for anyone wanna try to look at / understand the issue?

**Comment by fryiee** [comment]
Paging doctor @RyanThompson

**Comment by Pixney-William** [comment]
@RyanThompson could we fix this?

**Comment by fryiee** [comment]
@RyanThompson any update on this?

**Comment by fryiee** [comment]
This really needs to be fixed ASAP, it's not practical for us to run minute to minute commands just to fix filenames.

**Comment by RyanThompson** [comment]
This has been fixed.
