### ISSUE TITLE
[ relationship-field_type && accelerant-theme && repeater-field_type  ]  Variable use crashes assetic

### ISSUE THREAD

**Issue by ddnetters** [pyrocms/pyrocms#4734]
When you've got a repeater which contains a relationship field type it crashes assetic in the backend. The cause being the fact that the repeater loads css on the fly when adding a new row ('add row'). The generation of css happens after everything has been loaded. This mean any newly generated css files don't have access to the theme's variables.

The relationship field type needs those variables in `choices.scss` but doesn't get them since the themes css has already been generated/compiled. This results in Assetic throwing `[2018-02-01 09:15:26] local.ERROR: Leafo\ScssPhp\Exception\CompilerException: Undefined variable $input-border-radius: line: 10`

So `core/anomaly/relationship-field_type/resources/scss/choices.scss` is trying to use variables from `core/pyrocms/accelerant-theme/resources/scss/theme/_variables.scss` but it can't because it's being compiled after the scss files containing the variables have been compiled.

**Steps to replicate**

1. Create a repeater containing a relationship field type to some stream
2. Assign the repeater to a page or whatever
3. Try to click `add row`

It's probably a good idea to generate the css for repeaters and their assignments when the css for the theme is being generated. It'd remove this issue and prevent unnecessary css files from being generated and loaded.

**Comment by RyanThompson** [comment]
Every field type needs to have the variables ripped out of it and use the equivalent value used instead from the Accelerant theme - wanna tackle a few of these and send in PRs? Would be greatly appreciated!

**Comment by edster** [comment]
Alot of these got patched up today ^.^
