### ISSUE TITLE
[datetime-field_type] Allowed to enter time, but data not stored.

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4737]
When using the datepicker (time) you have a field when clicking shows a time selector. However, you are also able to enter a time manually.

If you do that, and hit save. It's not stored.

Now, if you are not able to do that, you shouldn't be allowed to enter a value without the selector if it can't be saved.

**Comment by RyanThompson** [comment]
This has been fixed prior by not allowing custom/manual input!
