### ISSUE TITLE
Accelerante Theme ; Tables missing pagination

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4739]
Main problem is that we are missing pagination.

Second problem is that the select box, always jumps back to 5 results. See last image even though i have selected 10 results (query string).

## Here you see 6 results

![image](https://user-images.githubusercontent.com/31292231/36029219-9b5c4f42-0da2-11e8-9b82-448118feaeca.png)

## Here you have 5 results, but without pagination

![image](https://user-images.githubusercontent.com/31292231/36029252-bccec8a8-0da2-11e8-972c-e614d5c4e627.png)

## Select box issue

![image](https://user-images.githubusercontent.com/31292231/36029314-ffd5363c-0da2-11e8-8556-4a38a6df1173.png)

**Comment by vargvinter** [comment]
Yup, pagination is broken.

**Comment by Pixney-William** [comment]
Thank you for confirming @vargvinter

**Comment by vargvinter** [comment]
No problem.
Just saw it minutes ago in my app, but you were faster with posting this issue. :)

**Comment by Pixney-William** [comment]
This is now done
