### ISSUE TITLE
[file-field_type] Upload/Select modal does not work with multiple locales

### ISSUE THREAD

**Issue by adrianfalleiro** [pyrocms/pyrocms#4740]
Hi there, I have noticed an issue with the File Field Type when working across multiple locales in the admin.

The issue occurs in the entry edit/creation screen and affects the ability to select/upload files for multiple locales.

The Field Field Type modal only appears for the first locale, and not any of the others. So, for example, if I have two locales (in this order): `en` and `fr` - the modal will only appear when the en locale is active. If I switch to the `fr` locale and click Select or Upload the modal will not appear (although the dark overlay will).

After an investigation, this appears to be the case since the data-target value of the Select and Upload buttons are the same across each locale, and the modal div ID is the same across multiple locales.

In accordance with the contributing guidelines I have opened a PR with a fix over here https://github.com/anomalylabs/file-field_type/pull/28

**Comment by RyanThompson** [comment]
Merged

**Comment by RyanThompson** [comment]
Thank you!

**Comment by adrianfalleiro** [comment]
Thanks @RyanThompson
