### ISSUE TITLE
[streams-platform] Buttons only allow href and not route name.

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#4744]
We should add support either through the HrefGuesser or add a separate attribute for buttons where you can specify `route` and point to a route name.

**Comment by RyanThompson** [comment]
Ya I say a route parameter could be checked for and made into href?

Or we could use the `hasRoute` method I added (cause it fails in Laravel I think).

Has route could collide with simple routes/urls like `login` is my only concern that route. Pun not intended. 

Thoughts?

**Comment by Pixney-William** [comment]
Any further comment on Ryans comment here @fryiee ?

**Comment by fryiee** [comment]
I would think it's safer to use a separate parameter to prevent URL collisions using href.
