### ISSUE TITLE
[api-module] API Module is broken

### ISSUE THREAD

**Issue by emergingdzns** [pyrocms/pyrocms#4745]
Ok so I've installed the API module 2.0.2.

I can't authenticate ANYTHING at all. It simply won't work. I'm able to use the admin panel and created a new client.

I then went in and did try adding the callback route as shown in the documentation. When I try to call it I get the same error I get when I run php artisan tinker...
```
$ php artisan tinker
Psy Shell v0.8.17 (PHP 7.1.6-1~ubuntu16.04.1+deb.sury.org+1 — cli) by Justin Hileman
>>> app(\Anomaly\ApiModule\User\UserModel::class)->find(300)->createToken('TokenName')->accessToken;
TypeError: Argument 1 passed to League\OAuth2\Server\AuthorizationServer::__construct() 
must be an instance of League\OAuth2\Server\Repositories\ClientRepositoryInterface, 
instance of Laravel\Passport\ClientRepository given, called in 
/path/to/site/core/anomaly/api-module/src/Passport/PassportServiceProvider.php on line 41
```
I know that user 300 exists and works (it's even an admin user).

The error seems to be that the api module PassportServiceProvider.php file is not referring to the right stuff.

I'm completely stuck and I've screwed around with this for 24 hours and I think the API module is broken because I have raw passport on a flat laravel 5.5 installation and it works fine there.

**Comment by Piterden** [comment]
Try next way:
```php
$users = new \Anomaly\UsersModule\User\UserRepository(
    new \Anomaly\ApiModule\User\UserModel()
);

$user = $users->find(300);
.....
```

**Comment by emergingdzns** [comment]
Actually, @RyanThompson fixed it. There were a couple bugs in the module.
