### ISSUE TITLE
[variables-module] PgSQL has `Not null Violation Error` while creating variable group

### ISSUE THREAD

**Issue by narayandhoj** [pyrocms/pyrocms#4750]
I am using pgsql 10 and I have freshly installed pyro with Pgsql. But when I tried creating new variable group it shows :

SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "config" violates not-null constraint DETAIL: Failing row contains (29, variables, site, variables_, id, id, f, f, f, f, f, null, f, null). (SQL: insert into "default_streams_streams" ("prefix", "namespace", "slug", "translatable") values (variables_, variables, site, 0) returning "id")

**Comment by Piterden** [comment]
Try 9th version. PHP v7.2 doesn't work fully too.

**Comment by Piterden** [comment]
@narayandhoj Any updates?

**Comment by narayandhoj** [comment]
@Piterden I tried both 9.2 and 9.6 version error still there. For now I have altered the streams table and working.

**Comment by Piterden** [comment]
Make a PR for those changes

**Comment by Piterden** [comment]
Either, could you please describe to me what I need to do to repeat it? Step by step...

**Comment by RyanThompson** [comment]
@Piterden are you able to replicate this at all?

**Comment by RyanThompson** [comment]
Closing for now but keep me posted if there is something we can do!
