### ISSUE TITLE
Pages with not enabled language should throw a 404

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4753]
## Filing this issue since it hasn't been done

jeroendewaele [Today at 10:44 AM]
in #support
What’s the point of ‘enabling’ languages, for ex. only dutch & english, if you still can visit all the pages in other languages?
As an example: https://pyrocms.com/de/documentation or https://pyrocms.com/it/documentation etc
Result: you get the same page (bad for google indexing because duplicate content)
Expected result: language is not activated -> so a 404 or redirect to the default language url (edited)

5 replies
jeroendewaele [7 hours ago]
Once you follow these url’s, you can navigate through the whole pyrocms website on that language segment... Doesn’t this result in a penalisation by Google for duplicate content? @ryanthompson (edited)

ryanthompson [7 hours ago]
It probably should throw a 404.. Why would you end up on these pages? They’re not linked anywhere and not in your sitemap. Or are they not? Anyways.. ya 404 is pry in order :stuck_out_tongue:

rienmoeyaert [7 hours ago]
Probably somebody changed the url in their browser, so that triggers a crawl.

ryanthompson [5 hours ago]
Spin up an issue for this if you would - I am afk

**Comment by Piterden** [comment]
You took out the dirty linen :joy:

**Comment by ddnetters** [comment]
Yes, please

**Comment by RyanThompson** [comment]
Ill show YOU my dirty linens..

https://github.com/anomalylabs/streams-platform/commit/bb5d97e55fff81041fdc0c2031e49b1636afbb41
