### ISSUE TITLE
Feature request: multiple polymorphic-field_type

### ISSUE THREAD

**Issue by girvydas** [pyrocms/pyrocms#4754]
Field type similar to grid-field_type with option to select (assign) related entries, but not create new ones.

Grid is strictly create only.. but it could be starter.
And between that and the multiple FT code should be able to cobble something together.

**Comment by RyanThompson** [comment]
Depending on what kinda content you need or if it's not non-content objects.. partials module might be something to look at. But yes, an FT like this would be nice. Poly needs a lookup mode too to begin with.

**Comment by Piterden** [comment]
Multiple polimorphic is just a pivot with polymorphic

**Comment by RyanThompson** [comment]
Array of objects in LS: https://streams.dev/docs/core/array
