### ISSUE TITLE
login 

### ISSUE THREAD

**Issue by saintsatplay2015** [pyrocms/pyrocms#4756]
When testing local installation of PyroCMS and attempting to reset the admin login password I get the following error thrown in the browser (after entering and submitting the admin e-mail address): 

mb_strtoupper() expects parameter 1 to be string, array given

Above error exception is thrown at vendor/laravel/framework/src/Illuminate/Support/Str.php381.

Any guidance or suggestions for how to resolve this?

**Comment by Piterden** [comment]
It's strange, but I have a success changing admin's password on my local installation.

Could you give some more info about what you did exactly?
