### ISSUE TITLE
[multiple-field_type] multiple tags mode fields have the last field's data.

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#4757]
As title.

You can replicate by putting two multiple FTs in one form with different data. The first field will have the second field's values.

I haven't tested on tags FT to see if issue exists there also.

**Comment by RyanThompson** [comment]
<img width="450" alt="screen shot 2018-05-23 at 10 45 23 pm" src="https://user-images.githubusercontent.com/1099967/40463435-0173696c-5edb-11e8-9cfe-d65285b3c7c5.png">

Not getting this. Variable with two repeaters - tried same related model and different ones. No bleeding over. Perhaps this was fixed?

**Comment by RyanThompson** [comment]
Kinda old so Ima close - please reopen if it persists!

**Comment by fryiee** [comment]
@RyanThompson was this tested on the multiple FT itself, from a form builder (not GUI?)
