### ISSUE TITLE
[select-field_type] Select and checkboxes fields created using FieldRepositoryInterface render correctly when used but cannot be edited in FieldsController

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#4758]
As title. To replicate, use for example, Pages Module, and create a select field from the admin UI. This will save the configuration using line breaks between values, and not arrays. Create the same select via FieldRepositoryInterface and although the field is visible in the FieldsTableBuilder output, clicking error results in a `Array to string conversion` error. This is due to the edit page's field attempting to explode via \n .

Example configs:
Select field created via admin UI:
```
a:3:{s:4:"mode";s:8:"dropdown";s:7:"options";s:27:"Full
Associate
Non-member";s:13:"default_value";N;}
```

Select field created via FieldRepositoryInterface:
```
a:2:{s:4:"mode";s:8:"dropdown";s:7:"options";a:3:{i:0;s:4:"Full";i:1;s:9:"Associate";i:2;s:10:"Non-Member";}}
```

Both fields render correctly when assigned and used.

**Comment by fryiee** [comment]
On investigation this is in the ParseOptions section of the FT.

**Comment by fryiee** [comment]
L101 of Anomaly\Streams\Platform\Form\Command\GetConfigFields:
```php
            /*
             * Set the configuration value.
             */
            $field['value'] = array_get($this->fieldType->getConfig(), $slug);
```

I believe this is responsible. This is just doing a basic array set on the value without doing any parsing to / from.

**Comment by fryiee** [comment]
Doing this to convert the option handler to a string so it can be parsed directly in the value works, but it seems quite smelly (not just the awkward array uses). What are your thoughts on this @RyanThompson ?

In SelectFieldType:

```php
public function getConfig()
    {
        if (isset($this->config['options'])) {
            if (is_array($this->config['options'])) {
                $options = [];
                if ($this->config['options'] !== array_values($this->config['options'])) {
                    foreach ($this->config['options'] as $key => $value) {
                        $options[] = $key . ':' . $value;
                    }
                } else {
                    $options = array_values($this->config['options']);
                }
                $this->config['options'] = implode(PHP_EOL, $options);
            }
        }

        return $this->config;
    }
```

**Comment by fryiee** [comment]
@RyanThompson what are your thoughts on this guy?

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/checkboxes-field_type/commit/d726c99713bdf022cea686196045a7c10197ec95
