### ISSUE TITLE
[files-module] Better metadata and organisation of files

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#4760]
As title. The files module should support nested folder structures.

**Comment by dwainscheeren** [comment]
I really would like to have this!

**Comment by Pixney-William** [comment]
I really would like to have this !

**Comment by RyanThompson** [comment]
There will need to be some cleverness with the filesystem cause not all adapters support this. BUT.. we could use uniqueness to have virtual nested folders..

**Comment by dwainscheeren** [comment]
Thats a good idea.

**Comment by fryiee** [comment]
I think this is an important one to have, as it's a significant issue both in terms of infrastructure and useability on the admin UI.

**Comment by Pixney-William** [comment]
Agreed. And so does my cat application!

**Comment by RyanThompson** [comment]
This comes with a lot of consequences I don't think are worth the hefty payment for them.

FTs basically do this for us. Any nested or automatic functionality should be handled as a field type or extension.

**Comment by fryiee** [comment]
@RyanThompson can you please direct me to the issue related to the underlying problem that this card is intended to solve (if there is one)? If there isn't, I think this should be kept open and modified  to represent the core issue, which is files module organisation. I fail to see how FTs and or an extension solve this core issue. Whether this is solved through nested folders or through another method, I think this is a legitimate business requirement that should be discussed. One of our projects has hundreds of files across multiple folders and the files module UI is unwieldy for that.

**Comment by dwainscheeren** [comment]
What about creating all folders in root, but in the admin make them nested only for GUI?

**Comment by fryiee** [comment]
I have modified the title to better represent the intention of this issue, which is to solve the underlying organisation issue with the files module (and all files within Pyro). If you could please re-open it @RyanThompson so we could continue discussing potential options for solving this it would be greatly appreciated.

**Comment by fryiee** [comment]
With that in mind, I would suggest at a minimum, the following things which would go a long way to improving useability:
- Categories for files (additional to folder location)
- Tagging for files
- Filters for: MIME Type, size, categories, tags and any other data dimension that could make file delineation easier
