### ISSUE TITLE
[files-module] Disks created are not synced with Storage.

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#4761]
As title. To replicate, create a disk, such as `local_private` via admin UI. Then attempt to retrieve it using `Storage::disk('local_private')` . This is the output:
```php
$disks = app('Anomaly\FilesModule\Disk\DiskRepository')->findBySlug('local_private')->filesystem();
InvalidArgumentException with message 'Driver [] is not supported.'
```

The workaround to get it load properly requires you to set config/filesystems.php to have a new disk, with the following:
```php
'local_private' => [
            'driver' => 'local_private',
            'root' => storage_path('app'),
        ],
```

The driver must equal the slug of the disk, and root can be anything as once it is set here the files module correctly overrides the root to its proper location. This will enable the disk to work from Storage:
```php
>>> Storage::disk('local_private')->path('');
=> "/home/vagrant/git/cb-pyro/storage/streams/default/files-module/local_private/"
```

**Comment by RyanThompson** [comment]
So this needs to be in config earlier than we are adding it then?

**Comment by fryiee** [comment]
Seems that way.

**Comment by fryiee** [comment]
@RyanThompson any thoughts on fix here?

**Comment by RyanThompson** [comment]
I've not been able to dig into this yet but I feel like the storage manager service provider could yield some insight as to how to replace config properly so it's not required so early.

**Comment by RyanThompson** [comment]
This should do it: https://github.com/anomalylabs/local_storage_adapter-extension/commit/b24705e101e703b5db6ac5375760eaae8cf621be
