### ISSUE TITLE
[file-field_type] We should be able to view/download files that are upload to a field from the FT itself.

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#4762]
As title. There should be controls to view/download directly from the file/s FT screen once it has been uploaded and selected. For example, in below, either hyperlinking the preview / icon itself or adding another View / Download button would be most appropriate.

![image](https://user-images.githubusercontent.com/5254791/38072685-3d363166-3373-11e8-93cd-6b96ec9ea715.png)

This applies to files FT and (potentially) upload FT also.

**Comment by fryiee** [comment]
https://github.com/anomalylabs/files-field_type/pull/20
https://github.com/anomalylabs/file-field_type/pull/29

Example screenshot from PR:
![image](https://user-images.githubusercontent.com/5254791/38073784-2e16f8aa-3378-11e8-91ec-97f317a2cb91.png)

**Comment by RyanThompson** [comment]
I like it! Ima put those into a dropdown group on the edit and merge (aside from the brown.. lol)

**Comment by fryiee** [comment]
@RyanThompson the brown is just brand primary.

**Comment by RyanThompson** [comment]
Done and done
