### ISSUE TITLE
[repeater-field_type] We need some way of interacting/passing the parent form to the repeater form.

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#4763]
Currently there's no easy way to get the repeater form builder to know about its parent. This is important as it breaks the pattern that we often use for setting runtime specific information on a form. For example, specifying that the form is using a parent model via the use of a setSomething() / getSomething() approach in the form builder can't be achieved in the repeater form as we have no way of accessing it before runtime.

Using newRepeaterFormBuilder() also doesn't help as that is tied to the model, and doesn't receive any arguments. We should think about the best way to pass down the parent form to any repeaters. One issue I foresee is subsequent repeater rows not having access if the request changes. I'm open to ideas on how to solve this - currently I'm doing a really awkward method of utilising a session() variable to check for the existing of an entry when populating the repeater form builder.

**Comment by RyanThompson** [comment]
This is a feature in the 1.4 branch: https://github.com/anomalylabs/streams-platform/blob/1.4/src/Ui/Form/Multiple/MultipleFormBuilder.php#L168

**Comment by RyanThompson** [comment]
We might need to back port this... so FTs don't need to be arbitrarily versioned with improvements (they'll likely need to do this themselves)

**Comment by RyanThompson** [comment]
Backported.
