### ISSUE TITLE
[streams-platform] Streams config - register listeners

### ISSUE THREAD

**Issue by girvydas** [pyrocms/pyrocms#4765]
There is no additional array for listeners to register in "config/streams.php".

**Comment by Piterden** [comment]
Use the service provider for placing listeners inside.

**Comment by girvydas** [comment]
It is not always suitable. Ex.:
I need to bind listener on  "AddonsHaveRegistered" event while running installer. Non of module service providers are loaded yet. 
Only way to bind listener is to use "app/Providers/EventServiceProvider.php". But it would be nice to have Laravel independent solution.

**Comment by Piterden** [comment]
Can't imagine the Laravel independent listener. Events is the part of Laravel and not the part of PHP.

```php
app('events')->listen($event, $listener, $priority);
```

**Comment by girvydas** [comment]
I'm not talking about Laravel independent listeners or events.
It would be nice to have ability to register listeners not directly in Laravel "core" project ("app/Providers/EventServiceProvider.php"), but via "config/streams.php", just like commands, schedulers and etc. It would be more flexible.

**Comment by Piterden** [comment]
Developing under the `app` folder is the bad practice for Pyro. You should place all your code into your custom addons.

**Comment by girvydas** [comment]
What's what I'm talking about.
In file https://github.com/pyrocms/pyrocms/blob/3.4/config/streams.php could be added something like:
```
'listeners' => [
    'App\Events\OrderShipped' => [
        'App\Listeners\SendShipmentNotification',
    ],
]
```

**Comment by Piterden** [comment]
Man, you don't need it. You can include there the service provider and bind listeners inside. Anyway, no one listener from `/config/streams.php` never be init before service providers.

**Comment by girvydas** [comment]
As I mentioned before, my problem was when I needed to bind listener on "AddonsHaveRegistered" event while running installer. When Pyro runs installer, it skips modules and extensions service providers registering (vendor/anomaly/streams-platform/src/Addon/AddonProvider.php line 133 and 137) and there is no way to include/bind listeners in service providers.

**Comment by fryiee** [comment]
@girvydas what's the use case for it? I'm onboard with this one 👍 just need to know what to be testing any PR against.

Just to confirm:

* You're trying to hook into `php artisan install` but any SP from an addon isn't loaded;
* You don't want to add any code directly to `app/`;
* You want to have a way to bind to those events fired during installation;
* and whatever code you're calling is NOT coming from anything that requires the Addon Service Provider in the first place.

**Comment by girvydas** [comment]
1. yes
2. yes
3. yes
4. not sure

In my case, I'm binding listener for "AddonsHaveRegistered" event and on binded listener calling code from my module. Basically I run my command "SortRegisteredAddons" and sort order of addons they install.

**Comment by RyanThompson** [comment]
I've thought about this one too and have been meaning to do it for a bit. I'll get er done!

**Comment by RyanThompson** [comment]
For me.. it's just easy / early / clean. 3 things I like.

**Comment by RyanThompson** [comment]
This has been added: https://github.com/pyrocms/pyrocms/commit/d76a7149105519e9db4fcf526be71d0dea08be22

I've needed to do this before as well - for easy / quick EARLY listener registration.
