### ISSUE TITLE
[streams-platform] SetMetaInformation command overwrites own timestamps

### ISSUE THREAD

**Issue by mmodler** [pyrocms/pyrocms#4766]
Hi,

i tried to set updated_at of a model manually for seeding using the laravel feature $model->timestamps = false, which disables timestamp auto-update.

But on save the saving event dispatches the SetMetaInformation command:
```php
    /**
     * Handle the command.
     *
     * @param Guard $auth
     */
    public function handle(Guard $auth)
    {
        if ($this->entry->created_at) {
            $this->entry->updated_at    = time();
            $this->entry->updated_by_id = $auth->id();
        }

        if (!$this->entry->created_at) {
            $this->entry->created_at    = time();
            $this->entry->created_by_id = $auth->id();
        }

        if (!$this->entry->sort_order) {

            /* @var Builder $query */
            $query = $this->entry->newQuery();

            $this->entry->sort_order = $query->count('id') + 1;
        }
    }
```

This will overwrite my updated_at. I think:

- It might be a copy-and-paste bug (the code is a little pointless/redundant) and $this->entry->updated_at should only be set if $this->entry->updated_at is NOT set, not related to $this->entry->created_at

or

- The command should check $this->entry->timestamps and only update if not false, which is the original laravel behavior

Thanks!

**Comment by fryiee** [comment]
@mmodler your first point isn't correct - in your example, it would only ever get updated_at set once. The current code is correct: it's checking that it has 'created_at' set, which would mean that it has been created before and is now being updated.

It should just check the timestamps flag as you've suggested.

**Comment by fryiee** [comment]
https://github.com/anomalylabs/streams-platform/pull/552

**Comment by mmodler** [comment]
But why the double logic, laravel will update updated_at?

If it would set it only if updated_at is null, it would make more sense?

EDIT: The created_at part does this, only set if not set before...

**Comment by fryiee** [comment]
@mmodler it seems that EloquentModel doesn't automatically updating using Laravel timestamps, so it's manually set anyway - which explains why Laravel timestamps updates aren't used. See https://github.com/anomalylabs/streams-platform/blob/1.3/src/Model/EloquentModel.php#L31
 
This is because Laravel doesn't have created_at_id/updated_by_id by default. Meaning my PR will need to be adjusted.

The logic otherwise is sound.
For the updated_at check, if created_at = any save of the model that isn't the initial one (meaning updated_at will be updated every save after initial creation)
For the created_at check, if !created_at = only the initial save when it's null

It could be simplified to `if ($entry->created_at) { } else { }` however.

**Comment by fryiee** [comment]
I think the simple solution is to use SetMetaInformation for the updated_at_id and created_at_id, but remove the updated_at / created_at set completely and use the inbuilt Laravel timestamps setter for that - although I'm not sure what impact that may have on core and whether detaching the setters will cause any problems. @RyanThompson may need to weigh in on this.

**Comment by mmodler** [comment]
You're absolutely right, laravel timestamps are disabled by default. But this is a very unintuitive solution i think - and you definitely need a way to save custom timestamps (for example on data import).

**Comment by RyanThompson** [comment]
At the time Laravel didn't have auto timestamps. Let me see what I can do real quick.

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/50d8775596a47fb9542b6436e32df3fc19f26bdc
