### ISSUE TITLE
[streams-platform] Section tabs with views do not translate via trans().

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#4767]
As title. Can be replicated by creating a section in a form builder that has a tab with a custom view. This custom view should call `trans()`. The resulting string will not be properly translated (using a normal addon namespace string such as `anomaly.module.users::etc...`

**Comment by fryiee** [comment]
@Piterden this is a bug, not a feature.

**Comment by RyanThompson** [comment]
Can you give some example of code not working? If `section.view` is present it simply includes it so trans() inside there would be up to you as a normal view: `{% include section.view %}`

**Comment by fryiee** [comment]
Disregard, this is PEBKAC
