### ISSUE TITLE
[streams-platform] Password reset form broken due to form builder changes

### ISSUE THREAD

**Issue by RichardMBS** [pyrocms/pyrocms#4772]
When you request a password reset and click the link you will get the following error...

`Method Anomaly\UsersModule\User\Password\ResetPasswordFormCriteria::__toString() must not throw an exception, caught ErrorException: Array to string conversion`

When the password reset form is being built it adds fields using the 'FormBuilder::addFields()' method. Recent changes to this method have added a call to `array_unique()`. By default this method casts array values to strings which is causing the above error.

This can be easily fixed by adding the `SORT_REGULAR` flag to the method call. This will ensure arrays are compared as arrays.

**Pull Request:**
https://github.com/anomalylabs/streams-platform/pull/559

**Comment by edster** [comment]
Confirmed this is still a thing in 3.5 branch as well

**Comment by RyanThompson** [comment]
Merged - thanks @RichardMBS !
