### ISSUE TITLE
[Hosting Error] Cms taking up invalid path on shared hosting subfolder

### ISSUE THREAD

**Issue by abhishekyagnik** [pyrocms/pyrocms#4773]
Hi, I am getting following error because the path is invalid.
Somehow, cms is repeating names of the path

```sh
An exception has been thrown during the rendering of a template
("file_get_contents(/home/SOMEAPP/public_html/release/public/release/app/default/assets/public/theme.css): failed to open stream: No such file or directory").
```

Following is the structure:
Domain: SOMEAPP.com/release
The public folder contents are in release directory too

I have moved the public folder and have made necessary laravel changes in the public index.php for boostrap

Is there anything else we need to change for pyrocms to work?

**Comment by Piterden** [comment]
Changes should be exactly the same as for clean Laravel installation.

**Comment by RyanThompson** [comment]
I would hesitate to host Pyro out of a subdirectory. Laravel doesn't always pick up the base bath and append. Try using release.someapp.com if you can.
