### ISSUE TITLE
Cache (model) is not cleared correctly when editing the grid

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4774]
Chat me up @RyanThompson when you see this and let's go over it!

**Comment by RyanThompson** [comment]
Can you update and check this again. There was a couple issues in Grid cache that got sorted out yesterday.

**Comment by Pixney-William** [comment]
Well i did a composer update 2 hours ago and that didnt help.. ill check locally now though

**Comment by Pixney-William** [comment]
Im on grid 1.3.0 , updated now,  doesn't work @RyanThompson

**Comment by Pixney-William** [comment]
Do not forget this mr @RyanThompson

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/da57de1cf32ab777c6b317d2d73c502bdd31bf6d
