### ISSUE TITLE
[streams-platform] Installation error on eager loaded addons

### ISSUE THREAD

**Issue by girvydas** [pyrocms/pyrocms#4775]
Installation fails if "sitemap-extension" is not required in composer.json
This occured after streams-platform update.
At "version": "v1.3.132" had no errors.

But at streams version:
` "name": "anomaly/streams-platform",
            "version": "v1.3.198",` any artisan command fails.

Potential cause:
  `resources/streams/config/addons.php` eager/deferred addons are loaded in some paths collection which doesn't exists

**Comment by girvydas** [comment]
Test this one https://github.com/anomalylabs/streams-platform/commit/a260dba768480dedffdc2a3028db013a707cb2fd

**Comment by fryiee** [comment]
@girvydas submit a PR and we'll get it looked at.

**Comment by RyanThompson** [comment]
@girvydas that link you posted should have fixed this - Blocks module was showing this behavior and it's been resolved I can confirm. Closing for now - reopen if the issue persists for you.
