### ISSUE TITLE
[streams-platform] Replace uses of superglobals with Request object

### ISSUE THREAD

**Issue by adrianfalleiro** [pyrocms/pyrocms#4776]
In a few places, superglobals ($_SERVER, $_REQUEST, $_POST, $_GET) are used instead of the Request object.

Some of these places are:
- Anomaly\Streams\Platform\Http\Kernel
- Anomaly\Streams\Platform\Addon\FieldType\FieldType
- Anomaly\InstallerModule\Installer\Form\InstallerFormHandler

I think it is best to avoid using superglobals where possible, especially when we have a great abstraction in the Laravel Request class.

Additionally when using a stateful PHP server such as [PHP-PM](https://github.com/php-pm/php-pm) superglobals aren't available - so forms/login/admin don't work.

I've been having a look at this and changing to use the Request object doesn't seem to break anything.  

If I submit a PR will you be interested in looking at it and potentially merging?

**Comment by fryiee** [comment]
@adrianfalleiro no reason why not - submit PR and we'll get it looked at.

**Comment by RyanThompson** [comment]
Indeed - would love a PR for it. Might be instances across addons so if you queue up a PR make sure to scan the whole project ^_^

**Comment by adrianfalleiro** [comment]
Great, I will start lining up a PR for streams-platform and any other modules. I will keep this ticket updated as I go.

**Comment by adrianfalleiro** [comment]
@RyanThompson @fryiee How do you test the `streams-platform` repo? 

I think I need to clone the `pryocms/pyrocms` repo and add my local `streams-platform` path as a repository and run the tests from `pryocms/pyrocms`?

**Comment by fryiee** [comment]
@adrianfalleiro that's correct. I clone a workbench installation of the Pyro repo then swap out streams-platform with my fork

**Comment by adrianfalleiro** [comment]
PR for `streams-platform` submitted - https://github.com/anomalylabs/streams-platform/pull/568
PR for `installer-module` submitted - https://github.com/anomalylabs/installer-module/pull/29
PR for `files-module` submitted - https://github.com/anomalylabs/files-module/pull/57

**Comment by RyanThompson** [comment]
Closing this for now as we'll handling this in an on-going manner.
