### ISSUE TITLE
slider-field_type can not set the range with negative number？

### ISSUE THREAD

**Issue by oimken** [pyrocms/pyrocms#4778]
For example：

set `Minimum Value`  to `-50` and  `Maximum Value` to `50`,
default value `0`;

Slider field type dose not work..

**Comment by RyanThompson** [comment]
Looks like it was working fine less the default value did not set properly. Fixed: https://github.com/anomalylabs/slider-field_type/commit/f69d0b9dc9b4a67b10e419bf0e317f210eb9011b

**Comment by RyanThompson** [comment]
https://packages.pyrocms.com/ updates every 10 minutes so try updating in about 4-ish minutes
