### ISSUE TITLE
[streams-platform] Pyro v3.5 has a login error

### ISSUE THREAD

**Issue by Eighke** [pyrocms/pyrocms#4779]
Just tried pyro 3.5, I got an error on `http://localhost:8000/admin/login` using `php artisan serve`

```
ErrorException thrown with message "Undefined index: QUERY_STRING"

Stacktrace:
#102 ErrorException in /vendor/anomaly/streams-platform/src/Ui/Form/Component/Action/Guesser/RedirectGuesser.php:62
```

Didn't try on Apache, but `QUERY_STRING` doesn't exists if we haven't a query in the URL.

**Comment by Piterden** [comment]
I don't have it.

Streams Platform doesn't have a `QUERY_STRING` words inside its sources.

**Comment by Eighke** [comment]
Pyro 3.5 -> Streams Platform 1.4

https://github.com/anomalylabs/streams-platform/blob/e4e5d1c072aa60efbe94c7e3020d696d74009a44/src/Ui/Form/Component/Action/Guesser/RedirectGuesser.php#L62

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/da6ae0437307d8b7c86da234b692fd1aa612be80
