### ISSUE TITLE
[streams-platform] Need to dump composer autoload at the end of make addon command.

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4780]
On a clean Pyro install I have an Exception of class not found each time, when I use `make:addon` artisan command.

Manual dump composer solves this issue.

**Comment by RyanThompson** [comment]
Can you tell when / where exactly it's being thrown? We dump here: https://github.com/anomalylabs/streams-platform/blob/1.3/src/Addon/Console/MakeAddon.php#L98

**Comment by RyanThompson** [comment]
Open er up if need be but I think this is working correctly.
