### ISSUE TITLE
[decimal-field_type] 0 min/max values treated as null

### ISSUE THREAD

**Issue by mf16** [pyrocms/pyrocms#4782]
There was a previous fix for this merged in 2017, but it was only in the view. If the min/max config value for the decimal field type is set to 0, it is treated as null during validation.

I've created a pull request in the anomalylabs/decimal-field_type repository: https://github.com/anomalylabs/decimal-field_type/pull/19

**Comment by RyanThompson** [comment]
Merged! Thank you
