### ISSUE TITLE
[anomaly/markdown-field_type] version conflict

### ISSUE THREAD

**Issue by girvydas** [pyrocms/pyrocms#4783]
Composer require conflict at https://github.com/pyrocms/pyrocms/blob/3.5/composer.json

Streams-platform version "~1.4.0" requires "anomaly/markdown-field_type": "~3.0.0", but 
https://github.com/anomalylabs/markdown-field_type/tree/3.0, there is line "anomaly/streams-platform": "^1.3.0"

**Comment by girvydas** [comment]
"anomaly/files-module": "~2.5.0" as well

**Comment by RyanThompson** [comment]
Good catch! Fixed them both, thank you.

**Comment by RyanThompson** [comment]
Give satis a couple minutes to update is all.
