### ISSUE TITLE
[Streams-platform] performance issue with many files in resources folder of active template

### ISSUE THREAD

**Issue by sir-vince** [pyrocms/pyrocms#4785]
In streams-platform, commit 3be8f000a1320a71f283cd20171218d75266054e introduced some changes to the method lastModifiedAt which recursively iterates over every file in the resources folder of the activated theme. If someone stores a lot of files, eg. stores all the source files from a pre-bought template or a node_modules folder, this could potentially kill performance of an application.

**Comment by sir-vince** [comment]
The catalyst to this issue seem to be
`if ($this->request->isNoCache() && $this->lastModifiedAt('theme::') > filemtime($path)) {
            return true;
        }`
in Asset\Asset.php

**Comment by RyanThompson** [comment]
I was going to actually remove that clause in favor for the one on line 660

**Comment by RyanThompson** [comment]
Which would use this syntax: https://github.com/anomalylabs/streams-platform/blob/1.3/resources/stubs/addons/resources/views/partials/metadata.twig#L43

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/6c5a23d4c1f307f5570883c7201aa6e34750dba9
