### ISSUE TITLE
[Image-FT] -- You cannot use the image FT with the settings module

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#4786]
You are unable to use the image FT with the settings module, bombs out. Some fields rely on multiple columns / pivots so we need some way to virtualize them. to be saved.

**Comment by Piterden** [comment]
```php
<?php

return [
    'image' => 'anomaly.field_type.file',
];
```

**Comment by edster** [comment]
Piterden what on earth are you trying to say here.

One, you have file not image.

Two, if that is intentional that has no relation ok this bug
