### ISSUE TITLE
[Streams Platform 1.3/1.4] -- Unable to unset entry to clone

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#4787]
The below used to work as a cloning mechanism, however this now just makes the form blank with no values anymore.

To I managed to get around this by using `$form->setFormMode('create');` instead, but having issues with cloning grids which I wonder has something to do with the way they are being related here.
```php
 public function copy(
    EventFormBuilder $form,
    Request $request,
    EventRepository $events,
    $id
) {
        if (!$request->isMethod('post')) {
            $event = $events->find($id);

            $entry = clone($event);

            $entry->setAttribute('id', NULL);

            return $form->setEntry($entry)->render();
        }
        else {
            return $form->render();
        }
    }
```

**Comment by Pixney-William** [comment]
Your english is getting a lot better

**Comment by edster** [comment]
Did you even read the description? As I said above, cloning entries.

It is my own class, random swearing is not productive.

**Comment by Pixney-William** [comment]
Is this still an issue @edster or has it been resolved?

**Comment by edster** [comment]
The above code just no longer works, had to be more verbose and null out the grids and block ids to get it to work.

That being said it is possible to do it, just a lot more difficult
