### ISSUE TITLE
Select Field Type : Array to string conversion error on edit

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4788]
This error is shown when you try to edit the field from within the admin when the field has NOT been created by the GUI but through migrations.

## Expected Behavior
Normally when you create a select field type within the grid module, you are able to the options by `key:value` in a textarea.

When you are migrating, you use the options array.

I should be able to edit these options both when a select field type is  created through a migration and through GUI.

![screen shot 2018-05-29 at 14 18 19](https://user-images.githubusercontent.com/31292231/40658340-446e0e9c-634b-11e8-85ba-47b8a6c55b69.png)

## Current Behavior
You can not edit the select field type options since the textarea can't render the array data.

## Steps to Reproduce
1. Create a migration
2. Create a select field type within the grid namespace
3. Assign the field the field to a grid.
4 Migrate
5 Go to the admin panel within grid/fields and try edit the field.

![screen shot 2018-05-29 at 14 16 27](https://user-images.githubusercontent.com/31292231/40658254-ec788064-634a-11e8-86fe-304ed4809202.png)

**Comment by dwainscheeren** [comment]
Very annoying its a bug for months now.

**Comment by Pixney-William** [comment]
Did you file an issue @dwainscheeren ? So i know if this is a duplicate?

**Comment by dwainscheeren** [comment]
Nope this one is the first I guess

**Comment by Pixney-William** [comment]
Seems like its a duplicate of https://github.com/pyrocms/pyrocms/issues/4758

**Comment by RyanThompson** [comment]
Easy enough to fix - thanks for the heads up @Pixney-William

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/select-field_type/commit/ac7bc6f30ef28fd9f81358ab986ffafa57ab514b
