### ISSUE TITLE
Repeater and/or Markdown Bug - Duplicating markdown fields

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4789]
#### Issue description

The repeater has some kind of bug. When adding more rows, the markdown field on previous entries are duplicated

#### Steps to reproduce the issue

1.  Create a repeater
2. Create a text and markdown field
3. Assign those fields to a repeater.
4. Create a new page type.
5. Create a new field of repeater
6. Assign the pagetype the repeater
7. Go to the page using the repeater, enter the text field and markdown field.
8. Save
9. Now add a row and see how the above markdown field is duplicated.

#### What's the expected result?

I don't expect to see a duplicated markdown field when adding a new row

#### Additional details / screenshot

![duplicated_repeater](https://user-images.githubusercontent.com/31292231/40709711-16b9d2fe-63f7-11e8-8238-c1a883c66dbe.gif)

-

**Comment by fryiee** [comment]
@RyanThompson @Pixney-William is this similar to this one here?

https://github.com/pyrocms/pyrocms/issues/4757

**Comment by Pixney-William** [comment]
It looks similar @fryiee , but i guess i would need to have a deeper dig to know if it is for sure. And you know how busy i am with gdpr:) So ill let @RyanThompson decide:)

**Comment by RyanThompson** [comment]
woa

**Comment by Pixney-William** [comment]
Did you have a time to look at this @RyanThompson? The client is complaining so would like to help them:)

**Comment by Pixney-William** [comment]
This is happening on several sites. All sites, i have two languages if that might matter.

**Comment by Pixney-William** [comment]
Ok @RyanThompson , also tested on pages where i only have one language (en) set. And the same behavior.

**Comment by Pixney-William** [comment]
It doesnt happen to a textarea, so far ive only seen it on markdown

**Comment by Pixney-William** [comment]
Wonder if this isn't a js issue somewhere.. Can't really find where though...

**Comment by Pixney-William** [comment]
@RyanThompson is working on it @Piterden

**Comment by Pixney-William** [comment]
@RyanThompson i tried refactor today to use blocks instead for this screaming client. But its the same problem there unfortunately..

**Comment by Pixney-William** [comment]
Tested and confirming it works! Closing this now.
