### ISSUE TITLE
[forms-module] MultipleFormBuilder bug

### ISSUE THREAD

**Issue by nickstanko** [pyrocms/pyrocms#4790]
After latest updates on 3.4 and 3.5 getting error with the forms addon, please help.

Type error: Argument 1 passed to Anomaly\StandardFormExtension\StandardFormExtension::integrate() must be an instance of Anomaly\Streams\Platform\Ui\Form\Multiple\MultipleFormBuilder, instance of Anomaly\FormsModule\Form\Form\FormFormBuilder given, called in /home/forge/site.test/pyrocms/core/anomaly/forms-module/src/Http/Controller/Admin/FormsController.php on line 59

**Comment by Piterden** [comment]
Try to update your module too.

**Comment by Pixney-William** [comment]
Something you know anything about @fryiee ?
