### ISSUE TITLE
Translatable fields disappear when non-english languages are set for site

### ISSUE THREAD

**Issue by beije** [pyrocms/pyrocms#4791]
When configuring a site to have any combination of enabled languages, except English, the translatable fields will disappear from the admin forms.

The problem seems to be because of the localstorage variable `formTranslations` not being set properly, or rather, not falling back properly. (It seems to always default to `en`, even if `en` does not exist as a translatable option).

Note: If you've previously set the languages via the language dropdown, then `fromTranslations` will be set.

**Comment by Eighke** [comment]
I only have this problem when I set a Default Language that is not included in the Enabled Languages

**Comment by Pixney-William** [comment]
Thanks for your input @Eighke!

@beije Could you maybe do a step by step approach description for what i need to do to test this out? Would save some time testing it.

**Comment by RyanThompson** [comment]
This was remedied a bit ago. If there's a different set of steps to reproduce anything similar please open a report!
