### ISSUE TITLE
[files-module] Add all files after uploading

### ISSUE THREAD

**Issue by robinvoor** [pyrocms/pyrocms#4792]
As title. It should have a button that adds all files at once. When I upload 100+ images at once, I don't really have the time to click more than 100 times on the +Add button.

**Comment by Piterden** [comment]
This would be a very useful feature. Almost such useful, such it was the hoverable menu...

**Comment by Pixney-William** [comment]
@Piterden Not sure i understand what you mean here.

**Comment by dwainscheeren** [comment]
This needs to be implemented soon! :D

**Comment by RyanThompson** [comment]
Done. Update composer.json from 3.7 dev. Also did this feature on multiple FT.

**Comment by ikoniqoz** [comment]
YEA! I had wondered about this earlier today.

**Comment by dwainscheeren** [comment]
YESSSS PARTY OVER HERE!
