### ISSUE TITLE
[streams-platform] Can not switch language on dynamically added grid items.

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4794]
@Piterden you caused an issue here last year. When you add a grid item dynamically, you are not able to switch language on that item.

https://github.com/anomalylabs/streams-platform/blob/1.3/resources/js/form/translations.js#L35

**Comment by Piterden** [comment]
Also, three lines above, the comment about the construction below is the bullshit! It isn't a shorthand of a ready event))

Btw, I don't remember about that issue...

**Comment by Pixney-William** [comment]
So you are submitting a fix @Piterden ?

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/92dc2e70488ec4eb35f5de8165091c0ab0d6bccd
