### ISSUE TITLE
[checkboxes-field_type] can't save or display users/roles/permissions

### ISSUE THREAD

**Issue by aldf** [pyrocms/pyrocms#4795]
After updating anomaly/checkboxes-field_type to v2.3.12 [this commit](https://github.com/anomalylabs/checkboxes-field_type/commit/d726c99713bdf022cea686196045a7c10197ec95) then the streams can't render checkbox field type options in users/roles/permissions.
after I downgrade to anomaly/checkboxes-field_type to v2.3.11 then it's working fine.

**Comment by Piterden** [comment]
https://github.com/anomalylabs/checkboxes-field_type/pull/19

**Comment by Pixney-William** [comment]
Was this resolved yesterday @fryiee ?

**Comment by Pixney-William** [comment]
Resolved by @RyanThompson 2018-06-27
