### ISSUE TITLE
[wysiwyg-field_type] - Missing error border

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4796]
Should have a red border indication.

![image](https://user-images.githubusercontent.com/31292231/41590373-230b3d70-73b7-11e8-9738-51afc3dc6381.png)

**Comment by Piterden** [comment]
And why don't you fixed it?

**Comment by Pixney-William** [comment]
I haven't had time. Thought i would issue it at least. And then take it if i get the time

**Comment by RyanThompson** [comment]
Mmhmm

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/wysiwyg-field_type/commit/75aff95785dd5816208cf4b667f512aa2c95aefa
