### ISSUE TITLE
[Feature Request] - Improved File & Media manager

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4797]
This is one of the most requested features we have had from clients. A better way to manage their files.

**To be a solid CMS we do need an improvement to the file manager with (most importantly) the possibility to :**

* Rename files
* Copy files 
* Copy files from one directory to another
* Move files from one directory to another

**Comment by fryiee** [comment]
https://github.com/pyrocms/pyrocms/issues/4760 related

**Comment by dwainscheeren** [comment]
I WANT THIS

**Comment by Piterden** [comment]
https://github.com/iutbay/mm

**Comment by Pixney-William** [comment]
Why did you close this @Piterden ?

**Comment by Piterden** [comment]
Why did you remove my message?

**Comment by Pixney-William** [comment]
@Piterden You were simply referencing a link to a non-stable vue file manager. And as you know, @RyanThompson don't want to use vue for this anyway, so it was not relevant. Another underlying reason was that you had also commented on others issues with non-relevant information earlier.

**Comment by RyanThompson** [comment]
We'll need to seriously rethink and possibly hash folder names with external drivers to get nested folders. Not all drivers support them but if we have a folder/bucket by hash then we can only reference them by ID basically (string ID). Thoughts?

**Comment by RyanThompson** [comment]
JUST so it can be consistent across the board.

**Comment by Pixney-William** [comment]
Other related issue: https://github.com/pyrocms/pyrocms/issues/4131

**Comment by zymawy** [comment]
If You Look At October CMS You Find Their FIle Manager More Consistent Then Pyro CMS.

Another, Points Are To Reconsider Using Vue Blade Engine Instead Of Tiwg Since The Majority Of Laravel Develepors Are Using **Blade**. 

Just Thoughts 💯

**Comment by Eighke** [comment]
I disagree for `Twig`. Twig is really good for a CMS because it is sandboxed, so it can be used in a WYSIWYG, or in a 3rd party theme without to worry to much.

**Comment by RyanThompson** [comment]
Closing this as duplicate - will comment on others as progress develops around them. This is all in the works though now.
