### ISSUE TITLE
[repeater-field_type] - Error when having a required field in the repeater

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4798]
### Issue and Steps to Reproduce
* Create a repeater which has a couple of fields that are required.
* Attach the repeater to your default page type
* Add a new row, enter content on one area but leave one textarea.
* Click save
* After reload, you see an error message that you missed the field. Alla data you entered on the other fields are lost. In fact, the row is lost. 

### Screenshots

![doesntwork](https://user-images.githubusercontent.com/31292231/41623430-09744350-7413-11e8-8ca8-465ab94e4fa0.gif)

#### Expected
When you save, and have missed a required field. It should show the error message, and the row should still be there with all the fields and the data you entered. Allowing you to enter the data in the missing field.

**Comment by edster** [comment]
@Pixney-William Are you still having this issue. I do not encounter this on my 3.5 install.

**Comment by RyanThompson** [comment]
I've not encountered this for a while now on required rows. Closing. Please re-open if there is more information available around this. Thanks!
