### ISSUE TITLE
[streams-platform] htmlcompress slows down ttfb

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4799]
I just got a top from Zvineyard to remove the htmlcompress. Locally that cuts TTFB with 1000ms here. And in production with something like 100-250ms.

Not sure if we can so anything about this. Or if we should remove it from the theme scaffolding to make sure people don't use it if it slows down the sites this much.

**Comment by zvineyard** [comment]
Here's a link to a simple compressor I wrote to replace the default compressor in Pyro templates: https://github.com/zvineyard/pyrocms-html-compressor

One thing I could do is make an upgrade to the tags are the same in my plugin and the default tags. That way we'll have backward compatibility.

**Comment by RyanThompson** [comment]
@zvineyard I like that idea. Let me profile real quick so I don't waste your time and we'll take that approach if it makes sense. Thank you!

**Comment by zvineyard** [comment]
OK, I made the changes so that you can use the `{% htmlcompress %} {% endhtmlcompress %}` tags.

**Comment by Pixney-William** [comment]
Yei! Go @RyanThompson

**Comment by RyanThompson** [comment]
This has been fixed in 3.5/3.6
