### ISSUE TITLE
[streams-module] Preview image like files-field_type does for pages

### ISSUE THREAD

**Issue by robinvoor** [pyrocms/pyrocms#4801]
As title. Preview image(s) in streams module table (current display for image row: https://i.imgur.com/Pn7nBaC.png), the same way the files-field_type does for pages (https://i.imgur.com/wwYIOPy.png).

Maybe add an option to show preview in field option while assigning the field type (image_field-type, file_field-type, files_field-type).

**Comment by Piterden** [comment]
```php
'image'     => [
    'heading' => 'Image',
    'value'   => '<img src="{entry.image}" height="50px" />',
],
```
Just do it!

**Comment by RyanThompson** [comment]
This has been done and will be effective in 3.7
