### ISSUE TITLE
Swift_TransportException Connection could not be established with host smtp.qq.com

### ISSUE THREAD

**Issue by acjf** [pyrocms/pyrocms#4802]
MAIL_DRIVER=smtp
MAIL_HOST=smtp.qq.com
MAIL_PORT=587
MAIL_USERNAME=-
MAIL_PASSWORD= -
MAIL_ENCRYPTION=ssl

用户名密码被我隐藏，.env 我设置了正确的数值，但出现了 Connection could not be established with host smtp.qq.com 错误。我该如何操作？

**Comment by Piterden** [comment]
Ну я даже не знаю. Наверное, сперва нужно понимать, что никто не виноват в том, что вы не знаете английский язык. Я думаю, что это лично ваши проблемы и я не обязан пользоваться переводчиком, чтобы вас понимать. Представляете, если бы все говорили на родных языках? Был бы хаос!

**Comment by Piterden** [comment]
I suppose the is your server issue or either you have wrong password.

**Comment by Pixney-William** [comment]
As Piterden is saying, this is most likely an issue of wrong password, not supplying the correct details. I have personally a few sites up running with the latest version of pyrocms using mailgun and i have not experienced this problem. So check all the configs and make sure they are correct.

Best
