### ISSUE TITLE
[users-module] Set password should have better description 

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4804]
Since we have specific requirements when setting a users password. We need to specify those on the field to make sure an admin don't know about them. Saving causes waste of time having to correct errors and when using password managers you need to reenter email fields and names as well sometimes.

![image](https://user-images.githubusercontent.com/31292231/42027560-50e5c084-7aca-11e8-96a8-67a7d9ee1390.png)

**Comment by RyanThompson** [comment]
I usually write this for the public site manually but.. could see about something for admins.
