### ISSUE TITLE
[Datetime-field_type] Faulty display of selected date and time

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4805]
Seems like only the hour is displayed

![image](https://user-images.githubusercontent.com/31292231/42028915-0cfb52c2-7ace-11e8-9800-e1eaaa472107.png)

**Comment by RyanThompson** [comment]
@Pixney-William what does your field configuration look like?

**Comment by Pixney-William** [comment]
@RyanThompson time + date . I just added one datetime field time using gui, then assigned the page type, and then got that. All standard settings, didnt do anything.. others have posted about it too so it is a common issue happening a few days ago

**Comment by RyanThompson** [comment]
What are your settings for the time format?

**Comment by RyanThompson** [comment]
You on 3.0?

**Comment by Pixney-William** [comment]
Im on 3.0 when it comes to the field type and streams 1.4

**Comment by Pixney-William** [comment]
![image](https://user-images.githubusercontent.com/31292231/42047656-363400e8-7b01-11e8-8c81-c60a66384f72.png)
![image](https://user-images.githubusercontent.com/31292231/42047690-4c02c5c6-7b01-11e8-97a6-995ab28a5d4b.png)

**Comment by Pixney-William** [comment]
But i dont seem to get this on 1.3 and 3.0. However, since others have reported this in the support channel. it is an issue. I think @fryiee had it too?

**Comment by Pixney-William** [comment]
Come on now mr @RyanThompson we got one critical left! CRUSH IT!

**Comment by RyanThompson** [comment]
Why is it that your time format doesn't have a value?

**Comment by RyanThompson** [comment]
IT WASNT REQUIRED!!!!!

https://github.com/anomalylabs/datetime-field_type/commit/5db3a1bdcd70c9346a54fb067d2c22ac568866f5

**Comment by RyanThompson** [comment]
Should be fixed - but no default.. I'll add that now.

**Comment by Pixney-William** [comment]
Thats how you have made things by default, and not set it as required. So i guess it's ok to have it not selected?

![image](https://user-images.githubusercontent.com/31292231/42065687-90b0032e-7b3c-11e8-9a9b-3d3501908035.png)

**Comment by Pixney-William** [comment]
![image](https://user-images.githubusercontent.com/31292231/42065694-a3c4867e-7b3c-11e8-80d1-33aa0f2f7945.png)

**Comment by Pixney-William** [comment]
AARGH!!!! You beat me to me molesting you!

**Comment by RyanThompson** [comment]
I need you to DD this: \Anomaly\DatetimeFieldType@config L#132

The default value. So I can back port it.

**Comment by RyanThompson** [comment]
Some core setting must not be converting right

**Comment by Pixney-William** [comment]
What are you saying? That you still need be to dd that?

**Comment by Pixney-William** [comment]
dd($config['time_format']); == null

```
if (!$config['time_format']) {
            $config['time_format'] = $this->configuration->get('streams::datetime.time_format');
            dd($config['time_format']);
        }
```

=== g
