### ISSUE TITLE
[files-module] Created disks aren't retrievable using Storage::disk()

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#4806]
As above.

Files aren't retrievable using their disk slug location, and using Storage::disk('slug') always returns the 'local' disk.

To reproduce:
- Create "Local Private" disk (slug local_private) and set to private.
- Call `Storage::disk('local_private');`

You'll see the 'local' disk, not the local_private one.

Similarly:
- Create "Local Private" disk (slug local_private) and set to private.
- Upload a file to a folder on that disk
- Call `Storage::disk('local_private')->get($file->path());`

You will receive a `Illuminate \ Contracts \ Filesystem \ FileNotFoundException` error.

**Comment by fryiee** [comment]
https://github.com/anomalylabs/local_storage_adapter-extension/pull/5/files

**Comment by Pixney-William** [comment]
https://github.com/anomalylabs/local_storage_adapter-extension/pull/5

**Comment by RyanThompson** [comment]
Merged! Thanks a ton guys

**Comment by RyanThompson** [comment]
I also did something a bit ago that changed when it was all registered so should be good to go now entirely.
