### ISSUE TITLE
Guest role does not work to restrict the pages for registered users.

### ISSUE THREAD

**Issue by mkaanery** [pyrocms/pyrocms#4809]
### EDIT: There is no problem about the guest role, it was me who could not do it. There is a request down in the page from another user.

I wanted to create a register page which is not accessable by any user, but guests.
So I created a page from the panel and in the "Options" tab, I assigned "Guest" role in "Allowed Roles" section.

But this resulted in me being able to see the page when I am logged in only.

In the docs, it says

> You can authorize a route with \Anomaly\UsersModule\Http\Middleware\AuthorizeRouteRole by defining the anomaly.module.users::role route parameter;

So I went to ServiceProviders of Users Module and added the following,

'register'                           => [
            'as'   => 'anomaly.module.users::register',
            **'anomaly.module.users::role' => 'guest',**
            'uses' => 'Anomaly\UsersModule\Http\Controller\RegisterController@register',
        ],

which also did not work.

Could you guide me about this? I also read in github this solution is fixed in another issue but I can't make it work.

**Comment by Pixney-William** [comment]
What issue was that @mkaanery ?

**Comment by mkaanery** [comment]
@Pixney-William 

https://github.com/pyrocms/pyrocms/issues/4108
---
https://github.com/anomalylabs/users-module/commit/b68231eea8e0c312e65d57cfdc442b94da164928

**Comment by Eighke** [comment]
I just tried to add the `guest` role to `register`, it is working (I have a 404 when connected)

**Comment by Eighke** [comment]
Btw, why `register` is not limited to `guest` by default? Same question for `login` :)

**Comment by Pixney-William** [comment]
admin/login and you are redirected correctly. but /login you are not. 

Now question is, shouldn't the theme developer handle this middlewear? There is no way for @RyanThompson to know where to redirect your users. 

And i think maybe /register should be decided by theme developer too. It's not always you want to redirect either. You might want to show something on that screen if you are visiting them but being logged in.

So i don't think this is an issue - closing it (since you tried and successfully added the guest ole to register).

**Comment by Eighke** [comment]
@Pixney-William No way, it cannot be the theme developer. How can the theme interact with the app, maybe UserModule not installed (Is it possible?~). Themes should be app agnostic.

But usually CMS redirect to `/` or just 404.

**Comment by Pixney-William** [comment]
@Eighke Ok, i am thinking more from our company perspective. Where we do everything :) 

But whoever is giving the site to the client, could simply add a middleware?

Thoughts @RyanThompson ?

**Comment by Eighke** [comment]
Of course but that means it is not a Pyro feature and it needs to be done for every projects (and maintained).

Maybe we can add a Settings? "Guess access to login" [Allow, Redirect to HP, 404] ?

**Comment by mkaanery** [comment]
@Eighke Could you tell me how you did it? Where did you add it? I mean which file and how?
I am new to laravel, asking so many questions :))

**Comment by Pixney-William** [comment]
Yes, i think a setting would be perfect

**Comment by Pixney-William** [comment]
@Eighke Pull request maybe?:) 

Otherwise maybe i can chip in.. Small stuff like this is perfect for us in the community to do and have ryan focus on the important stuff we need done.

**Comment by RyanThompson** [comment]
I agree: https://github.com/anomalylabs/users-module/commit/e91e66e0c65eb84ca4a7b614225f46890826bc39
