### ISSUE TITLE
[pages-module] [posts-module] Translatable slugs

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4810]
A request a lot of people want. Heard it for two years now on slack. The other requests has been closed. I don't feel they should be. 

Even if you don't implement it today. I just feel this should be alive since it is highly desired.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/31292231/42086484-7d35103a-7b93-11e8-98fe-91f239611f0d.png)

**Comment by Pixney-William** [comment]
Seems like Fred has offered @RyanThompson something. At least have a look at it and see if it can be used/bought.

![image](https://user-images.githubusercontent.com/31292231/42086559-c2e092d0-7b93-11e8-8a0d-0ccfaf14bf86.png)

**Comment by Pixney-William** [comment]
@RyanThompson this is what we are discussing:

https://gitlab.com/newebtime/pyrocms/pages_extended-extension

**Comment by mmodler** [comment]
+100 from me :)

I think we need a solution working over single module borders?

**Comment by Eighke** [comment]
Well the last update of `pages-module` include major compatibility breaks

https://github.com/anomalylabs/pages-module/blob/f0c2c0ed9915ee4c479c56183d34a7227e9411fd/src/PagesModuleServiceProvider.php#L108

1. The page handle is "filtered", so I guess many custom handles are now broken.
2. `php artisan route:list` doesn't return any route anymore
3. `php artisan route:cache` doesn't work anymore

**Comment by RyanThompson** [comment]
@Eighke I can patch these in this latest release being they are performance based.

**Comment by Eighke** [comment]
@RyanThompson Yup I know, but it's a problem for the `artisan` commands to not be working. Especially the cache one (and it is a bit paradoxical for a performance commit to disable a better performance feature :D).

For the bullet 1, it is fine I guess, it just made the `handlers` useless (the route is now checked by the path before the handler, so custom routes are not possible anymore).

**Comment by RyanThompson** [comment]
Ya ya - getting this into 3.7 lol

**Comment by RyanThompson** [comment]
This is done: 

https://github.com/anomalylabs/pages-module/commit/ad4cfd32ac846a3b3626ef0a8d3cd3fe84490230

https://github.com/anomalylabs/posts-module/commit/767cb062ab6220d8e725b66d9d8639a0a2af8404
