### ISSUE TITLE
Class name not written when creating migrations

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4811]
**Describe the bug**
When creating a new migration, the class name is not written.

`"anomaly/streams-platform": "~1.3.0",` && `"anomaly/streams-platform": "~1.4.0",`

**To Reproduce**
1. Run `php artisan make:migration test --fields`
2. Look at : `/database/migrations/2018_XX_XX_XXXXXX_test.php`
3. Notice line number 5 : `class {class} extends Migration`

**Expected behavior**
The class name should not be {class}

**Screenshots**
![image](https://user-images.githubusercontent.com/31292231/42124893-f334c6bc-7c6b-11e8-95c3-69b2009ad59e.png)

**Comment by RyanThompson** [comment]
Fixed! https://github.com/anomalylabs/streams-platform/commit/ee1e9f01151f518896716d88de84386de5850347
