### ISSUE TITLE
[streams-platform] Read only fields in a non-readonly form are still editable.

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#4812]
**Describe the bug**
Setting a field to readonly doesn't work unless the form is readonly.

**To Reproduce**
1. Create a form builder
2. Set a field to `'readonly' => true`
3. Load the form

**Expected behavior**
Field should be readonly.

**Screenshots**
![image](https://user-images.githubusercontent.com/5254791/42272236-e34407a8-7fc8-11e8-9682-b28143638ffd.png)
![image](https://user-images.githubusercontent.com/5254791/42272333-2b502e1e-7fc9-11e8-99c6-7448a45d858a.png)

**Comment by edster** [comment]
Just asking for clarity, if you save the form do the changes to that field save or are they still rejected?

**Comment by RyanThompson** [comment]
This is just relationship then (and perhaps some others) cause I tested select and it seems to be working well.

**Comment by fryiee** [comment]
@RyanThompson were you able to push up fixes for the individual FTs?

**Comment by RyanThompson** [comment]
I'll push up FTs as I test and come across them. Other than that this issue really isn't helpful.

**Comment by fryiee** [comment]
@RyanThompson I'll be honest, this issue is so old that I ended up just overriding it myself to fix it.

**Comment by RyanThompson** [comment]
Would have been an easy few PRs.

**Comment by fryiee** [comment]
@RyanThompson probably.

**Comment by Pixney-William** [comment]
I totally get @RyanThompson that you would like people to make pull requests. However, not sure this is the best way of achieving this.

Instead, i propose we add a tag for it here on github called "PR Wanted". Then when you read an issue like this one that you don't want to jump on/don't prioritize you can simply use that tag and people will know that the issue wont likely be resolved in a near future unless someone from the community makes a pull requests. 

Also, that way people know that you welcome a PR on this issue, making sure our development time is not wasted.

What do you guys think of that idea?

**Comment by edster** [comment]
We have a volunteer needed tag  rename that if anything.
