### ISSUE TITLE
[tags-field_type] Options are ignored.

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#4813]
**Describe the bug**
`'options'` config setting is ignored on tags field type.

**To Reproduce**
1. Create a tag field type with `'options' => ['foo', 'bar']` in config
2. Load form builder
3. Attempt to add foo or bar

**Expected behavior**
Options are selectable ala multiple field type in tags mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/5254791/42318124-75f58202-8091-11e8-86ad-8390215de833.png)
![image](https://user-images.githubusercontent.com/5254791/42318165-9153ae3e-8091-11e8-8399-abe489e6ab14.png)

**Additional context**
This happens with fields set as tags in migration, and also on the fly in a form builder.

**Comment by edster** [comment]
Confirmed that handlers aren't working either, they are not even being fired.

**Comment by RyanThompson** [comment]
Update to 2.4 - both items here are fixed: https://github.com/anomalylabs/tags-field_type

**Comment by RyanThompson** [comment]
@edster first addon out there using new mix based assets too.
