### ISSUE TITLE
Buttons having name attribute redirects to the same page.

### ISSUE THREAD

**Issue by mkaanery** [pyrocms/pyrocms#4814]
In the admin panel, I have a stream table showing all the entries in the database and there are buttons attached to the end of each row. I want to pass data via button because I will use the data to fill a field of the form when it is accessed. My button definitions in my CompanyTableButtons file's handle function: 

```
$builder->setButtons([
            'edit',
            'add_worker' => [
                'attributes' => [
                    'href' => '/admin/crm/workers/create',
                    'value' => function(EntryInterface $entry) {
                        return $entry->getId();
                    },
                    'name' => 'add_worker',
                ],
                'text' => 'Çalışan ekle',
                'type' => 'success submit'
            ]
]);
```
When I click the button, it redirects to where I am.

**Comment by Eighke** [comment]
@mkaanery  The definitions is wrong, the href should be directly in `add_worker`.

```
            'add_worker' => [
                'href' => '/admin/crm/workers/create',
            ]
```
