### ISSUE TITLE
API Module - Can't issue a token 

### ISSUE THREAD

**Issue by DavidFortune** [pyrocms/pyrocms#4815]
I post my issue here because there is no support coming with the API Module that I purchased.

I followed the instructions here 
[https://pyrocms.com/documentation/api-module/2.0/usage/issuing-tokens]

when trying to access /oauth/request?client=CLIENT_ID
I get the following error
Call to undefined method Laravel\Passport\Bridge\ClientRepository::find()
[error](https://www.awesomescreenshot.com/image/3470181/e82482b7e789d91bc608fdc386295026)

Even when I try to create a client in the backend, I get an error related to the module
[admin](https://www.awesomescreenshot.com/image/3470186/1d81cd560e8801208cf2a806ebb71cb6)
Call to undefined method Laravel\Passport\Bridge\ClientRepository::create()
[error](https://www.awesomescreenshot.com/image/3470201/978dfa67ba16d621ae2463ef08b4abab)

It looks like something missing.

Thank for getting back to me.

**Comment by RyanThompson** [comment]
Let me pull this down real quick and check it out!

**Comment by RyanThompson** [comment]
Also, this and slack and the forum IS support for the addon :-)

So you are in the right place.

**Comment by RyanThompson** [comment]
Looks like there have been some changes in Passport - can you get ahold of me on Slack so I can PM you a package? Or email me (my email is under my profile here).

**Comment by RyanThompson** [comment]
Emailed you the updated version - should be good to go! Reopen if you are still experiencing issues!
