### ISSUE TITLE
UserAuthenticator doesn't check whether extensions are installed/enabled

### ISSUE THREAD

**Issue by twij** [pyrocms/pyrocms#4816]
Hey, just spent a few hours scratching my head on this one..

**Describe the bug**
UserAuthenticator.php (in Users module) doesn't check if the extension is installed or enabled so you can't replace the default authenticator unless you completely remove it.

**To Reproduce**
1. Make a new authenticator extension
2. Try and get it to work
3. Cry

**Expected behavior**
Extensions that aren't installed/enabled shouldn't be loaded.

Adding a 
~~~
if($authenticator->installed == true && $authenticator->enabled == true){ }
~~~
around the logic in the foreach loops seems to fix it! Thanks.

**Comment by RyanThompson** [comment]
This was fixed back in 3.5 I believe. Maybe 3.4  :-)
