### ISSUE TITLE
Being able to use tabs within grids,repeaters & blocks more easily

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4817]
I have one question about something and i wonder if there are any news (or i might have missed it):

I have a personal dislike, and have also heard it from clients, about how “long the pages get” when you stack fields upon each other. This is esp for blocks module, grids or repeaters.

I know i can go in there and manually do whatever i want. But obv this is time consuming and not cost-effective for the client.

Do you have any plans to make it easier for us to handle this? For example, being able to within a grid place fields into different tabs. Maybe you have one tab saying image, and then another saying settings. See images:

![image](https://user-images.githubusercontent.com/31292231/42398397-ff3d4f8a-8169-11e8-9b97-acfd384b9342.png)

![image](https://user-images.githubusercontent.com/31292231/42398411-0e348bac-816a-11e8-8b2a-ed141e474df3.png)

**Comment by RyanThompson** [comment]
Have you tried using the form builder callback to provide your own builder and layout?

**Comment by Pixney-William** [comment]
You are talking about this right?

https://pixney.com/news/customising-views-in-pyrocms

**Comment by RyanThompson** [comment]
Not reading it ATM but you can define the form builder to use there in the repeater I believe. Which should be able to control the layout.

**Comment by Pixney-William** [comment]
Ok ill gotta go try figure out what you mean i guess. And see if that is what i did earlier or if it means a better/faster way of achieving this.
