### ISSUE TITLE
[streams-platform] setTableEntries is overwritten on $table->render()

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#4818]
**Describe the bug**
Using setTableEntries() on a TableBuilder results in the table reverting to the original streams entry query on calling $table->render(). setTableEntries() is successfully called and a call to getTableEntries() after it but before rendering returns the correct collection, however after render the collection has reverted.

**To Reproduce**
1. Create a stream with table builder
2. In the controller method, set the table entries to a subset of the stream entries by way of `$builder->setTableEntries($entryCollection)`
3. After render, you'll see the full stream entries rather than the overwritten table entries.

**Expected behavior**
`setTableEntries($entries)` correctly sets the entries for the table to the collection (if stream table, assuming collection is same type).

**Screenshots**
![image](https://user-images.githubusercontent.com/5254791/42417004-bce7f25e-82c0-11e8-9ee5-20bec06cbd2d.png)
above should result in no results, but below shows all the stream entries:
![image](https://user-images.githubusercontent.com/5254791/42417009-d85d4098-82c0-11e8-8140-83d26e05af3f.png)

**Comment by Eighke** [comment]
Not sure if it is a bug, I'm currently doing that and it is working if you set something. But if you have `no results`... well it means you set nothing. And from my understanding you are in this case.

You can unset the model when you have no result to avoid that.

```php
$table->setTableEntries($items = $this->paymentBatches->findAll());

if ($items->count() == 0) {
    $table-->setModel(null);
}
```

I didn't find better solution. TableEntries is an empty collection by default, setting another empty collection will not change. Maybe it should be `null` by default? So an empty collection will be "no result"? But it is a B/C break.

**Comment by dwainscheeren** [comment]
Can this be fixed soon I have this bug too

**Comment by RyanThompson** [comment]
The issue I believe is that you're setting the table entries (on the target table) before even starting the build process. Maybe do some debugging around this though for some intel: https://github.com/anomalylabs/streams-platform/blob/1.5/src/Ui/Table/Command/GetTableEntries.php#L53

**Comment by Eighke** [comment]
@RyanThompson 

Yes, it is the problem. If you try to set entries before the build process:

```php
    public function onReady()
    {
        if (!$payrollId) {
            $employees = $this->employees->findAllActive($dateFrom, $dateTo);

            $this->setTableEntries($employees);
        }
    }
```

* Case 1: `findAllActive` return at least 1 employees: No problem
* Case 2: I don't have Active employee, so `setTableEntries` will set a empty collection.

If the Case 2 happen, `$entries->isEmpty()` is empty. So it will get all the employees.

The only way I found to avoid that is to unset the model.

```php
    public function onReady()
    {
        if (!$payrollId) {
            $employees = $this->employees->findAllActive($dateFrom, $dateTo);

            $this->setTableEntries($employees);

            if ($employees->count() == 0) {
                $this->setModel(null);
            }
        }
    }
```

I see only 2 ways to fix this problem.

* When we use `setTableEntries` we also flag some property to `true` and in the `GetTableEntries` we will check it.
* Change `table->entries` default value to `null`, and in `GetTableEntries` check if it's `! null`. So an empty collection will stop here (it will be a B/C break).

**Comment by dwainscheeren** [comment]
`$this->setModel(null);` does not always work, `$this->setModel(false);` is better to use

**Comment by RyanThompson** [comment]
Ok this should cover these kinds of issues from here forward. I do want the builder to carry the stuff though. Table itself should not be modified if it can be helped. Specially before build: https://github.com/anomalylabs/streams-platform/commit/5d8ec75b8fdbb07ce7db4bea007670bc45deb682

**Comment by RyanThompson** [comment]
Back ported this to 1.4 assuming that's what you are on in this case @fryiee
