### ISSUE TITLE
Blocks module function to use title + display checkbox

### ISSUE THREAD

**Issue by dwainscheeren** [pyrocms/pyrocms#4820]
I use blocks now a lot and created a lot of own blocks. But now everytime it places inside the admin the title and a checkbox "Yes, display the block title".

I always need to hide this with css code.

It would be great to have a build in function to enable/disable this functionality inside the BlockExtension file.

**Comment by RyanThompson** [comment]
The UI will improve for this but it'll always be there at the very least for organization purposes.
