### ISSUE TITLE
Pre-process Media Sizes (default macros)

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4821]
**Is your feature request related to a problem? Please describe.**
It would be nice to allow top level macros to be run programmatically for one but also have these sane defaults in place for rapidly consuming media and standardizing the common outputs.

**Describe the solution you'd like**
We have macros and I would like to propose being able to select which macros, per folder, are ran automatically when uploaded. This would also allow us to run them via CLI to ensure images are already all compiled as needed. 

**Describe alternatives you've considered**
I've thought about making this separate from macros but I don't think it makes any sense.. it's config based so that developers can easily publish/override config and define the macros they need.

This is a basic form that WP has implemented. We can certainly do better with our macro system:

![wordpress-media-settings](https://user-images.githubusercontent.com/1099967/42428537-b7b33ce2-82f9-11e8-9a91-5f4dc74ebc0b.png)

**Comment by oimken** [comment]
Yes，That will be great！ 

I will love to define the  marco's slug,  and set the description/size/quality/filter.....  base on folder (Is there will be sub-folder? :) . when I need image specify size I just add the marco slug as suffix, kinda like flicker:
```
s	small square 75x75
q	large square 150x150
t	thumbnail, 100 on longest side
m	small, 240 on longest side
n	small, 320 on longest side
-	medium, 500 on longest side
z	medium 640, 640 on longest side
c	medium 800, 800 on longest side†
b	large, 1024 on longest side*
h	large 1600, 1600 on longest side†
k	large 2048, 2048 on longest side†
o	original image, either a jpg, gif or png, depending on source format
```

I think marco is good. but how to get image easier is much important.
hope to see the image marco soon and thank you ryan!

**Comment by finnito** [comment]
I think this would be a great idea!
This would much better allow for using a srcset to responsively serve images to a user on their viewport size. I would be very behind it!

**Comment by dwainscheeren** [comment]
I really would love this!

**Comment by huglester** [comment]
Hello,
this is really needed.
we also need a possibility to create images with background.

for example I have image
100px X 50px

and want to fint it into 50x50 box.
so at the end I want to have 50x50 box. just for example left and right sides would have white background - so placeholder would took it's place

**Comment by RyanThompson** [comment]
So we've got image macros already - are you guys proposing more options out of the box?

I can get a small, small-square type pattern off the flickr examples into core as a default. But you can define macros already.

**Comment by RyanThompson** [comment]
Default ones: https://github.com/anomalylabs/streams-platform/commit/b14afe6ac6e0777b57e5cf0a6aee02e274a47b05

**Comment by RyanThompson** [comment]
Since this is per folder - are we better off just adding a "longest edge" setting to the folders?

**Comment by RyanThompson** [comment]
The idea here is to prevent dotes from uploading images that are 4000 pixels wide when we only need 800px or whatever for the media.

**Comment by edster** [comment]
@RyanThompson I would like to see settings per folder with the following optional settings
Quality
Max width (pixel)
Max height (pixel)

Realistically, the rest of the macros should most likely be done on the file/image instance like we are now per fetch.

The above just lets us take care of the numb-nuts who upload masssssive images without prep.

Love the idea of more out of the box macros for image instances though as above
