### ISSUE TITLE
[BUG?] Call to undefined method Anomaly\MultipleFieldType\MultipleFieldType::pluck()

### ISSUE THREAD

**Issue by mkaanery** [pyrocms/pyrocms#4822]
In a **form builder**, I wanted to pre-insert a field value, which is a multiple field type, as the following:
```
    public function onBuilt() {
        $this->getFormField('field-slug-here')->setValue($this->getFormData()->first());
   }

```
I tried to dump` $this->getFormData()->first()` and it returned a number which is an id. So, there is a method called `ids` in _core/anomaly/multiple-field_type/src/MultipleFieldType.php_, which uses pluck and causes the error.

**Comment by RyanThompson** [comment]
Value in that case should never be an instance of the MultipleFieldType. I would check the setup you have and correct.
