### ISSUE TITLE
[language-field_type] View [dropdown] not found.

### ISSUE THREAD

**Issue by girvydas** [pyrocms/pyrocms#4823]
Latest v2.2.5 language field type default input view mode set to "dropdown", but there is no dropdown.twig view at this version.

**Comment by fryiee** [comment]
@girvydas work around is to manually call 'mode' => 'search' in the config of the field where  you're using it.

**Comment by fryiee** [comment]
https://github.com/anomalylabs/language-field_type/pull/7

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/language-field_type/commit/c9da7450f4a0a975586ab5cf3f6ba2d30fe372d6
