### ISSUE TITLE
[streams-platform] Can't override core email template.

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#4824]
**Describe the bug**
View overrides don't work when called in a theme for `streams::notifications/email`

**To Reproduce**
1. Create a separate view for email e.g. `redtally.theme.awg_admin::mail/layout`
2. Add `'streams::notifications/email' => 'redtally.theme.awg_admin::mail/layout'` to your $overrides array in your service provider.
3. Send an email
4. See the original PyroCMS template.

**Expected behavior**
The view override works as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/5254791/42485136-a30bba76-8439-11e8-8133-559b4333166e.png)

**Additional Information**
I'm guessing this has to do with the way addons are loaded for dispatched jobs, or what addon service providers are loaded in that context.

**Comment by RyanThompson** [comment]
Publish or use otherwise standard view overriding.
