### ISSUE TITLE
[pages-module] Multiple WYSIWYG FTs - only one updated when editing.

### ISSUE THREAD

**Issue by kiltedup** [pyrocms/pyrocms#4827]
Added a new page type with two fields - both WYSIWYG FTs.

When editing a page with this type, only content one of the fields is updated. 

Video of the behaviour in action : https://pyrocms.slack.com/files/U08MK60A2/FBNQZBQTD/wysiwyg_editing.mov

This is on a fresh install (10 days ago) - composer updated.

**Comment by RyanThompson** [comment]
Fixed! Good find :-)

https://github.com/anomalylabs/editor-field_type/commit/54d828d0d77eaeeb7c9d9b6cdf64bd13b8a3d654

https://github.com/anomalylabs/wysiwyg-field_type/commit/50a0978a9b485a2b02035a5dfdac98a73525e0d8

https://github.com/anomalylabs/markdown-field_type/commit/53629239b560c204e70dd5beecda4c179a4533a0
