### ISSUE TITLE
Base table or view not found : default_streams_locks

### ISSUE THREAD

**Issue by stardothosting** [pyrocms/pyrocms#4828]
I have a brand new project that is generating an exception

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.default_streams_locks' doesn't exist (SQL: delete from `default_streams_locks` where `locked_at` <= 2018-07-16 16:42:28)`

**To Reproduce**
1. Create new pyro project
2. Add streams via composer
3. Create new post
4. Edit post

Am I missing something obvious?

**Comment by RyanThompson** [comment]
How did you create the project? Looks like it's a mixture of 3.4/3.5 branches since locks are in 3.5

**Comment by stardothosting** [comment]
Followed the instructions here : https://pyrocms.com/help/developer-tools/cheatsheets/installation

`composer create-project pyrocms/pyrocms myproject.dev`

**Comment by RyanThompson** [comment]
Can you paste the whole stack here so I can see the trace?

**Comment by GioValentin** [comment]
Hey was this ever resolved ?

**Comment by GioValentin** [comment]
123
Illuminate\Database\QueryException 
…/vendor/laravel/framework/src/Illuminate/Database/Connection.php664
122
Doctrine\DBAL\Driver\PDOException 
…/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php79
121
PDOException 
…/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php77
120
PDO prepare
…/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php77
119
Doctrine\DBAL\Driver\PDOConnection prepare
…/vendor/laravel/framework/src/Illuminate/Database/Connection.php479
118
Illuminate\Database\Connection Illuminate\Database\{closure}
…/vendor/laravel/framework/src/Illuminate/Database/Connection.php657
117
Illuminate\Database\Connection runQueryCallback
…/vendor/laravel/framework/src/Illuminate/Database/Connection.php624
116
Illuminate\Database\Connection run
…/vendor/laravel/framework/src/Illuminate/Database/Connection.php490
115
Illuminate\Database\Connection affectingStatement
…/vendor/laravel/framework/src/Illuminate/Database/Connection.php435
114
Illuminate\Database\Connection delete
…/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php2252
113
Illuminate\Database\Query\Builder delete
…/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php844
112
Illuminate\Database\Eloquent\Builder delete
…/vendor/anomaly/streams-platform/src/Model/EloquentQueryBuilder.php210
111
Anomaly\Streams\Platform\Model\EloquentQueryBuilder delete
…/vendor/anomaly/streams-platform/src/Lock/LockRepository.php87
110
Anomaly\Streams\Platform\Lock\LockRepository cleanup
…/vendor/anomaly/streams-platform/src/Ui/Form/Command/LockFormModel.php90
109
Anomaly\Streams\Platform\Ui\Form\Command\LockFormModel handle
…/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php29
108
 call_user_func_array
…/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php29
107
Illuminate\Container\BoundMethod Illuminate\Container\{closure}
…/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php87
106
Illuminate\Container\BoundMethod callBoundMethod
…/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php31
105
Illuminate\Container\BoundMethod call
…/vendor/laravel/framework/src/Illuminate/Container/Container.php549
104
Illuminate\Container\Container call
…/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php94
103
Illuminate\Bus\Dispatcher Illuminate\Bus\{closure}
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php114
102
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php102
101
Illuminate\Pipeline\Pipeline then
…/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php98
100
Illuminate\Bus\Dispatcher dispatchNow
…/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php76
99
Illuminate\Bus\Dispatcher dispatch
…/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesJobs.php17
98
Anomaly\Streams\Platform\Ui\Form\Command\BuildForm dispatch
…/vendor/anomaly/streams-platform/src/Ui/Form/Command/BuildForm.php77
97
Anomaly\Streams\Platform\Ui\Form\Command\BuildForm handle
…/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php29
96
 call_user_func_array
…/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php29
95
Illuminate\Container\BoundMethod Illuminate\Container\{closure}
…/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php87
94
Illuminate\Container\BoundMethod callBoundMethod
…/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php31
93
Illuminate\Container\BoundMethod call
…/vendor/laravel/framework/src/Illuminate/Container/Container.php549
92
Illuminate\Container\Container call
…/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php94
91
Illuminate\Bus\Dispatcher Illuminate\Bus\{closure}
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php114
90
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php102
89
Illuminate\Pipeline\Pipeline then
…/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php98
88
Illuminate\Bus\Dispatcher dispatchNow
…/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php76
87
Illuminate\Bus\Dispatcher dispatch
…/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesJobs.php17
86
Anomaly\Streams\Platform\Ui\Form\FormBuilder dispatch
…/vendor/anomaly/streams-platform/src/Ui/Form/FormBuilder.php217
85
Anomaly\Streams\Platform\Ui\Form\FormBuilder build
…/vendor/anomaly/streams-platform/src/Ui/Form/Multiple/Command/BuildForms.php40
84
Anomaly\Streams\Platform\Ui\Form\Multiple\Command\BuildForms handle
…/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php29
83
 call_user_func_array
…/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php29
82
Illuminate\Container\BoundMethod Illuminate\Container\{closure}
…/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php87
81
Illuminate\Container\BoundMethod callBoundMethod
…/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php31
80
Illuminate\Container\BoundMethod call
…/vendor/laravel/framework/src/Illuminate/Container/Container.php549
79
Illuminate\Container\Container call
…/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php94
78
Illuminate\Bus\Dispatcher Illuminate\Bus\{closure}
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php114
77
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php102
76
Illuminate\Pipeline\Pipeline then
…/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php98
75
Illuminate\Bus\Dispatcher dispatchNow
…/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php76
74
Illuminate\Bus\Dispatcher dispatch
…/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesJobs.php17
73
Anomaly\Streams\Platform\Ui\Form\FormBuilder dispatch
…/vendor/anomaly/streams-platform/src/Ui/Form/Multiple/MultipleFormBuilder.php59
72
Anomaly\Streams\Platform\Ui\Form\Multiple\MultipleFormBuilder build
…/vendor/anomaly/streams-platform/src/Ui/Form/FormBuilder.php232
71
Anomaly\Streams\Platform\Ui\Form\FormBuilder make
…/vendor/anomaly/streams-platform/src/Ui/Form/FormBuilder.php317
70
Anomaly\Streams\Platform\Ui\Form\FormBuilder render
…/core/anomaly/pages-module/src/Http/Controller/Admin/PagesController.php74
69
Anomaly\PagesModule\Http\Controller\Admin\PagesController edit
…/vendor/laravel/framework/src/Illuminate/Routing/Controller.php54
68
 call_user_func_array
…/vendor/laravel/framework/src/Illuminate/Routing/Controller.php54
67
Illuminate\Routing\Controller callAction
…/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php45
66
Illuminate\Routing\ControllerDispatcher dispatch
…/vendor/laravel/framework/src/Illuminate/Routing/Route.php212
65
Illuminate\Routing\Route runController
…/vendor/laravel/framework/src/Illuminate/Routing/Route.php169
64
Illuminate\Routing\Route run
…/vendor/laravel/framework/src/Illuminate/Routing/Router.php658
63
Illuminate\Routing\Router Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php30
62
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/core/anomaly/users-module/src/Http/Middleware/AuthorizeRoutePermission.php128
61
Anomaly\UsersModule\Http\Middleware\AuthorizeRoutePermission handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
60
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
59
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/core/anomaly/users-module/src/Http/Middleware/AuthorizeControlPanel.php51
58
Anomaly\UsersModule\Http\Middleware\AuthorizeControlPanel handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
57
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
56
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/core/anomaly/users-module/src/Http/Middleware/AuthorizeModuleAccess.php63
55
Anomaly\UsersModule\Http\Middleware\AuthorizeModuleAccess handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
54
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
53
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/core/anomaly/users-module/src/Http/Middleware/AuthorizeRouteRoles.php132
52
Anomaly\UsersModule\Http\Middleware\AuthorizeRouteRoles handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
51
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
50
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/core/anomaly/users-module/src/Http/Middleware/CheckSecurity.php86
49
Anomaly\UsersModule\Http\Middleware\CheckSecurity handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
48
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
47
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/core/anomaly/installer-module/src/Http/Middleware/CheckIfInstallerExists.php72
46
Anomaly\InstallerModule\Http\Middleware\CheckIfInstallerExists handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
45
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
44
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/anomaly/streams-platform/src/Http/Middleware/ApplicationReady.php49
43
Anomaly\Streams\Platform\Http\Middleware\ApplicationReady handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
42
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
41
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/anomaly/streams-platform/src/Http/Middleware/CheckLocale.php50
40
Anomaly\Streams\Platform\Http\Middleware\CheckLocale handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
39
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
38
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/anomaly/streams-platform/src/Http/Middleware/SetLocale.php125
37
Anomaly\Streams\Platform\Http\Middleware\SetLocale handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
36
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
35
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/anomaly/streams-platform/src/Http/Middleware/PoweredBy.php38
34
Anomaly\Streams\Platform\Http\Middleware\PoweredBy handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
33
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
32
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/anomaly/streams-platform/src/Http/Middleware/VerifyCsrfToken.php108
31
Anomaly\Streams\Platform\Http\Middleware\VerifyCsrfToken handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
30
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
29
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php43
28
Illuminate\Auth\Middleware\Authenticate handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
27
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
26
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php102
25
Illuminate\Pipeline\Pipeline then
…/vendor/laravel/framework/src/Illuminate/Routing/Router.php660
24
Illuminate\Routing\Router runRouteWithinStack
…/vendor/laravel/framework/src/Illuminate/Routing/Router.php635
23
Illuminate\Routing\Router runRoute
…/vendor/laravel/framework/src/Illuminate/Routing/Router.php601
22
Illuminate\Routing\Router dispatchToRoute
…/vendor/laravel/framework/src/Illuminate/Routing/Router.php590
21
Illuminate\Routing\Router dispatch
…/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php176
20
Illuminate\Foundation\Http\Kernel Illuminate\Foundation\Http\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php30
19
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/anomaly/streams-platform/src/Http/Middleware/SetLocale.php125
18
Anomaly\Streams\Platform\Http\Middleware\SetLocale handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
17
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
16
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php49
15
Illuminate\View\Middleware\ShareErrorsFromSession handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
14
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
13
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php63
12
Illuminate\Session\Middleware\StartSession handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
11
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
10
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php37
9
Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
8
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
7
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php59
6
Illuminate\Cookie\Middleware\EncryptCookies handle
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php149
5
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php53
4
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php102
3
Illuminate\Pipeline\Pipeline then
…/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php151
2
Illuminate\Foundation\Http\Kernel sendRequestThroughRouter
…/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php116
1
Illuminate\Foundation\Http\Kernel handle
…/public/index.php53
0
 require_once
…/server.php21

**Comment by GioValentin** [comment]
I am getting the same error.

**Comment by GioValentin** [comment]
Okay,

How I resolved. 

$ php artisan addon:reinstall anomaly.module.pages

But now, I keep getting the error when I create a new user and the email redirect gives me the same error and trying to reinstall the users table has done nothing more then lock me out

**Comment by RyanThompson** [comment]
Looks like you need to migrate your addons - this would only happen from an update that wasn't migrated or a reused DB or something.

Do the migrations listed here: https://pyrocms.com/help/developer-tools/cheatsheets/upgrading
