### ISSUE TITLE
[upload-field_type/files-module] String replace does not support G.

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#4829]
**Describe the bug**
Both upload field type and files module use str_replace('M', '' ...) to get the current upload max. This does not support gigabyte shorthand as set in nginx, for example.

**To Reproduce**
1. Set nginx / PHP max upload size to 2G or similar
2. Attempt to upload

**Expected behavior**
Gigabyte values are correctly converted.

**Comment by RyanThompson** [comment]
Ya we had this mentioned elsewhere.. lemme see what I can do.

**Comment by RyanThompson** [comment]
Fixed:

https://github.com/anomalylabs/upload-field_type/commit/2f0ccee400dc4322ec06b1b05f9dc9d3b9f92d10

https://github.com/anomalylabs/files-module/commit/3c5d796a287eaf9b572073b1991df9b43bac8355
