### ISSUE TITLE
Exception on brand new install after creating theme : Class MyClient\AwesomeTheme\AwesomeTheme does not exist

### ISSUE THREAD

**Issue by stardothosting** [pyrocms/pyrocms#4830]
**Description**
Brand new PyroCMS. Works fine out of the box until you create a theme. When a theme is created following the instructions at https://pyrocms.com/help/addon-development/themes/creating-a-theme , an exception is generated : 

`Class MyClient\AwesomeTheme\AwesomeTheme does not exist`

source file : /vendor/laravel/framework/src/Illuminate/Container/Container.php

**Steps to re-create**
1. composer create-project pyrocms/pyrocms myproject.dev
2. chmod -R 777 ./storage; chmod -R 777 ./public/app; chmod -R 777 ./bootstrap/cache
3. composer update
4. php artisan install (mysql database driver)
5. php artisan make:addon my_client.theme.awesome
6. View the website to see the exception

I'd be happy to post any additional information needed.

**Comment by RyanThompson** [comment]
Try running `composer dump-autoload`. 

Do you see that that class actually exists? Or is there a compiler error and the name/class doesn't match up for some reason?

**Comment by RyanThompson** [comment]
Any word on this?
