### ISSUE TITLE
[upload-field_type] ValidateFolder fails if field is inside a MultipleFormBuilder.

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#4834]
**Describe the bug**
ValidateFolder fails if inside a MultipleFormBuilder as it uses attribute (not prefixed) to return it. This is a problem when the field comes from assignments, and is not defined in a form builder. This is worrying in that there could be a bunch of validators in various FTs that are borked in MultipleFormBuilders.

**To Reproduce**
1. Create an upload field type
2. Assign it to something with an entry (e.g. post type or similar)
3. Try to submit
4. See "Call to member function getConfig() on null".

**Expected behavior**
Upload FT works

**Screenshots**
![image](https://user-images.githubusercontent.com/5254791/42930580-bca8b26a-8b80-11e8-86f8-3608b6f2fc06.png)

**Additional context**
Laravel validators don't prefix, therefore this causes the field to never be retrieved in the validator, see https://github.com/pyrocms/pyrocms/issues/4826

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/upload-field_type/commit/5e92ee69da13ec07138eceeb94ef5af02439f530
