### ISSUE TITLE
[upload-field_type] v1.2.6 broke all uploads

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#4835]
**Describe the bug**
As title. Due to change in method privacy from public to protected, all uploads are broken.

**To Reproduce**
1. Add an upload field type of version 1.2.6
2. Try to upload

**Expected behavior**
Upload FT works.

**Screenshots**
![image](https://user-images.githubusercontent.com/5254791/42930674-003a2c20-8b81-11e8-8c8c-a77dc8903f41.png)

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/upload-field_type/commit/552a7345e0d4f76be0f92d0339e75d366c4a9e30
