### ISSUE TITLE
[users-module] Unknow permission

### ISSUE THREAD

**Issue by Eighke** [pyrocms/pyrocms#4837]
I was trying to create a `Manager` role, but I notice it is not possible to access to /admin using anything else that "Admin". Because of the permission `anomaly.module.users::general.control_panel`.

https://github.com/anomalylabs/users-module/blob/218ea87396e89086468aa8ce036e39e8b626d12c/src/Http/Middleware/AuthorizeRoutePermission.php#L93

I'm not sure what it is for? Because we already have a permission `streams::control_panel.access`. Is it an old behaviour?

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/users-module/commit/07e2737ed4177759fb48294d23a28555e0b50c59
