### ISSUE TITLE
[language-field_type] Should support all language codes in the ISO-639-1 standard, not just the locales enabled in streams-platform.

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#4838]
**Describe the bug**
As title.

**To Reproduce**
1. Add language FT
2. Attempt to add an ISO-639-1 code that isn't in config/locales.php
3. It won't be there

**Expected behavior**
The language FT should pull the full ISO-639-1 list.

**Comment by RyanThompson** [comment]
Maybe let's just add the others to config? Looks like a lot of resources just list them out (no built in support in PHP for them?): https://github.com/datasets/language-codes/blob/master/data/language-codes.csv

There are a lot of things like that. Thoughts?

**Comment by Eighke** [comment]
I'm using https://github.com/antonioribeiro/countries (https://github.com/antonioribeiro/countries-laravel), allow to manage almost everything about countries

**Comment by RyanThompson** [comment]
I guess this won't hurt anything - I will add config to restrict supported locales only

**Comment by RyanThompson** [comment]
Done - and used tags / search for settings
