### ISSUE TITLE
[Documentation] - Navigation module error

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4839]
**Describe the bug**

![image](https://user-images.githubusercontent.com/1510338/43312092-92ea02c8-918c-11e8-8c08-b99e5f85cd9c.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/1510338/43312112-a1d2d9a4-918c-11e8-85bf-3b7004f5e1e7.png)

**Comment by RyanThompson** [comment]
The docs are correct allbeit a very minute detail. It was demonstrating `{{ menu.getLinks() }}` which means menu is an object not a plugin function. The `menu` FUNCTION looks like this: https://pyrocms.com/documentation/navigation-module/2.3/usage/plugin#menu

You're correct in using `links()` though being that you want the links and not a rendered menu.

To get the menu in the view you could do `{% set menu = entries('navigation', 'menus').whereSlug('foo').first() %}` for example.
