### ISSUE TITLE
[users-module] Several bugs

### ISSUE THREAD

**Issue by emergingdzns** [pyrocms/pyrocms#4842]
Two issues:
1. In the Fields section there's an untranslated string: `anomaly.module.users::stream.users.description`. Not a big deal but figured you'd want to know about it.

2. Adding a new field does not add it to the Profile tab of the user unless you add another field after it.

3. Clicking on section tabs triggers search drop-down.

**To Reproduce**
1. Go to Users -> Fields and then add a new field.
2. Click on Add Field. Choose any field type.
3. Fill in any required info and click Save.
4. Click Users section and edit a user.
5. Note that the search field become focused so the drop-down comes out. Very irritating.
6. Click Profile tab. Again search field becomes focused and drop down comes out.
7. Note that the new field is not there.
8. Repeat steps above and then you will see that only the first field you created is there.

Note: I did figure out that if you START to add a field but then cancel the last field added will then show up.

UPDATE: I went in an deleted the extra fields I made in testing this and they still appear in the Profile tab when editing a user. But a minute or so later they stopped appearing. It seems like maybe there's some kind of cache issue? Which may also explain why the new field didn't appear right away...

**Expected behavior**
1. Make it so that the Search field is only focused when clicked on.
2. Make it so that the new field is added immediately.

**Desktop (please complete the following information):**
 - OS: Mac High Sierra
 - Browser: Chrome
 - Version: 68.0.3440.106

**Comment by RyanThompson** [comment]
Can you update and verify the fields show up right away? I am looking into JS. Locale thing is fixed too.

**Comment by RyanThompson** [comment]
This should finish that one up: https://github.com/pyrocms/accelerant-theme/commit/3d3803a37be2439e73ece43702a1588e99c6bc8d
