### ISSUE TITLE
Background management delete operation, prompt box need to enter what is the content. Where can I find what I need to input?

### ISSUE THREAD

**Issue by acjf** [pyrocms/pyrocms#4843]
Background management delete operation, prompt box need to enter what is the content. Where can I find what I need to input?

**Comment by acjf** [comment]
no one?

**Comment by RyanThompson** [comment]
We really need more information to help. For example - "Yes" is displayed by default to confirm typing: 
<img width="512" alt="screen shot 2018-10-02 at 4 02 57 pm" src="https://user-images.githubusercontent.com/1099967/46376852-b291f180-c65c-11e8-8c7b-49bde163516d.png">

**Comment by RyanThompson** [comment]
Post some more information and I can reopen and investigate. Maybe note the locale you are using.
