### ISSUE TITLE
[users-module] Forgot Password link not including redirect url

### ISSUE THREAD

**Issue by emergingdzns** [pyrocms/pyrocms#4845]
**Describe the bug**
I discovered that the Forgot Password link on the login form is not adding the redirect url to the href when it is provided to the login page.

**To Reproduce**
1. Add the Comments module to any page or post
2. View that page or post while NOT logged in.
3. Click the text to "login or register to comment".
4. On the login page you get, notice the URL says ?redirect=http.....
5. Right click on the Forgot Password link and inspect the link. No "?redirect" is attached to that URL.

**Expected behavior**
When "?redirect=http......." is in the url to the login page that information should be added to the forgot password link. The password/forgot.twig file does include the `.redirect(request_get('redirect', '/'))` in the form open statement but it's pointless if the link doesn't include the redirect.

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser: All
 - Version: All

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/users-module/commit/307caa8e6191cea45b420e04d8c30a52ee30f195
