### ISSUE TITLE
[core: versioning]: Versions not deleted from streams_versions when addon uninstalled/reinstalled

### ISSUE THREAD

**Issue by finnito** [pyrocms/pyrocms#4846]
**Describe the bug**
When running `php artisan addon:uninstall` or `php artisan addon:reinstall` entries are not removed from the `streams_versions` table causing clutter to accumulate while developing.

**To Reproduce**
1. Add some versions to a versional model
2. Reinstall the addon
3. Model entries with the same ID should retain versions from previous installation

**Expected behavior**
I think that this is probably good behaviour when a system is in production, but if a system is in development then it is not ideal.

**Additional context**
Maybe the versioning could use ENV variables to determine whether in production/development and therefore whether entries should be deleted from the versions table when an addon is uninstalled.

**Composer**
[composer.txt](https://github.com/pyrocms/pyrocms/files/2407757/composer.txt)

**Comment by RyanThompson** [comment]
Done! https://github.com/anomalylabs/streams-platform/commit/96e1d20733a7f515684d2471cb964d61204f1ab4

**Comment by finnito** [comment]
Thanks Ryan! 🙌
