### ISSUE TITLE
[core: versioning]: Two version entries created when making a new model entry in a custom addon

### ISSUE THREAD

**Issue by finnito** [pyrocms/pyrocms#4847]
**Describe the bug**
I have written a custom addon to manage some rosters for a client and when I create a new entry into the rosters stream, two versions get created. In the screenshot below the seconds value in the timestamp is not displayed, but they are identical.

**To Reproduce**
1. Create a versionable model
2. Add a new entry
3. Inspect the versions table and see that there are two entries from the initial creation

**Expected behavior**
Should only expect a single version entry to be created.

**Screenshots**
Here I am iterating over entry.versions in Twig to produce a revisions table in the frontend. I would give a backend example but for some reason I'm having issues with the VersionsController.
![versioning-example](https://user-images.githubusercontent.com/6530078/45917171-94144500-be69-11e8-99ea-49660bececd5.png)

**Additional context**
[composer.txt](https://github.com/pyrocms/pyrocms/files/2407766/composer.txt)

**Comment by RyanThompson** [comment]
This should fix it - but it's not tagged just yet. Testing: https://github.com/anomalylabs/streams-platform/commit/5bf5479652bc0184206662fec53d1d0b63a9cd88

**Comment by finnito** [comment]
Thanks Ryan! That’s stellar!
