### ISSUE TITLE
[slug-field_type]: Input gets stuck on Safari

### ISSUE THREAD

**Issue by finnito** [pyrocms/pyrocms#4848]
**Describe the bug**
When navigating through a form on Safari 11.1.2 the input gets stuck in the slug field type and I am unable to tab or click into a different input. The page needs to be reloaded to fix the issue.

**To Reproduce**
1. Open a form in Safari 11.1.2
2. Select a slug field with a click or tab into it
3. See error

**Expected behavior**
User should be able to tab through to the next input or click to another input.

**Video**
https://youtu.be/NnSMdiNEUIQ

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra (10.13.6)
 - Safari 11.1.2

**Extra**
[composer.txt](https://github.com/pyrocms/pyrocms/files/2408895/composer.txt)

**Comment by Pixney-William** [comment]
Hello, is there something wrong with the video?

**Comment by finnito** [comment]
Hello! The video is supposed to show how I am trying to click another input box but am unable to

**Comment by RyanThompson** [comment]
Patched up: https://github.com/anomalylabs/slug-field_type/commit/876161f23fd7e4bd597130c755ac478ffc632ecb

**Comment by finnito** [comment]
Thanks Ryan! Looking forward to updating
