### ISSUE TITLE
Link to documentation results in 404

### ISSUE THREAD

**Issue by bochoven** [pyrocms/pyrocms#4849]
**Describe the bug**
The link on the Image Field Type page:
https://store.pyrocms.com/geocoder-field-type-1.html

points to 

http://pyrocms.com/documentation/image-field-type/v1.2

Which results in a 404

**Comment by RyanThompson** [comment]
Huh.. welp I don't see why that's happening. SEO is no good but it'll have to sit like that until I replace the listings. Magento is... a different kind of animal that's for sure. So disobedient. I updated the doc links though! Thank you ^_^
