### ISSUE TITLE
Error running artisan install with SQL Server database

### ISSUE THREAD

**Issue by dariusj18** [pyrocms/pyrocms#4851]
**Describe the bug**

When using a SQL Server database with PyroCMS and running the artisan installer There is an error

```
SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Column 'default_users_roles.sort_order' is i
  nvalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause. (SQL:
   select top 1 [default_users_roles].* from [default_users_roles] left join [default_users_roles_translations] on [d
  efault_users_roles].[id] = [default_users_roles_translations].[entry_id] where [slug] = guest and ([default_users_r
  oles_translations].[locale] = en or [default_users_roles_translations].[locale] = en or [default_users_roles_transl
  ations].[locale] is null) and [default_users_roles].[deleted_at] is null group by [default_users_roles].[id] order
  by [default_users_roles_translations].[name] asc)
```

The issue stems from the file \anomaly\streams-platform\src\Model\EloquentQueryBuilder.php:256
`->groupBy($model->getTableName() . '.id')` and commenting this out allows the installer to continue, but I don't know the larger ramifications this might have.

SQL Server does not allow you to select any field that you do not group by.

I am not even sure if PyroCMS is meant to run on SQL Server, I couldn't find any requirements in that regard.

**To Reproduce**
1. With a databse on SQL Server run php artisan install --ready with a sqlsv database configured in the config/database.php

```
 'sqlsrv' => [
            'driver'   => 'sqlsrv',
            'host'     => env('DB_HOST', 'localhost'),
            'port'     => env('DB_PORT', '1433'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset'  => 'utf8',
            'prefix'   => env('DB_PREFIX', ''),
        ],
```

**Expected behavior**
The installer work with SQL Server

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Command Line

**Comment by RyanThompson** [comment]
Ya this is required in the translation system.. However I had disabled this portion of the default ordering just north of your line for postgres so I added sqlsrvr to the list there as well.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/c387793b61a96452faff63f7e9266624a6051de3
