### ISSUE TITLE
[colorpicker-field_type]: Colour box not working on Safari (Mac & iOS)

### ISSUE THREAD

**Issue by finnito** [pyrocms/pyrocms#4859]
**Describe the bug**
When using the colourpicker-field_type the box that displays the colour does not display a colour, but instead displays the hex code.

**To Reproduce**
1. View a colour picker field on Safari on iOS or Mac

**Expected behavior**
The box should be coloured and not display a hex code.

**Screenshots**
![screen shot 2018-10-05 at 12 28 23 pm](https://user-images.githubusercontent.com/6530078/46532901-a1cebf00-c89a-11e8-9b9e-80427958d973.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14 (18A391)
 - Browser Safari 
 - Version 12.0 (14606.1.36.1.9)

**Smartphone (please complete the following information):**
 - Device: iPhone 6s Plus
 - OS: 12.0
 - Browser: Safari

[composer.txt](https://github.com/pyrocms/pyrocms/files/2450098/composer.txt)

**Comment by Pixney-William** [comment]
Ill try to verify this @RyanThompson unless you have already done it?

**Comment by RyanThompson** [comment]
It was working in 11 but ya 12 doesn't work.. We need a REALLY good native JS alternative. And I'll still pry use it only for fallback.

**Comment by RyanThompson** [comment]
I've got a new version coming in the next couple days that will remedy this and is BC

**Comment by RyanThompson** [comment]
Updating to `~2.3.0` will bring back a colorpicker that's cross browser consistent and also re-introduces alpha control if configured to do so. 100% BC update.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/colorpicker-field_type
