### ISSUE TITLE
Allow null for all stream fields

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4861]
I'm trying to accomplish a "Quick Save" functionality that allows users to bypass validation temporarily.  The context for this is the front end of the site  using the Form Builder class.  I can easily enough modify the Form Builder validator so that validation errors are bypassed, however i am running into an issue with database level constraints when trying to save the data to the database.

**Comment by RyanThompson** [comment]
Could a good alternative be to NOT make the field required but define that on the builder instead where applicable?

Anyone else with thoughts on required fields not actually being required at the low level of the database?

Is there a default you could implement? 

Just thinking about the options and any potential consequences.

**Comment by mattcdavis1** [comment]
I don't think NOT making the field required is a good solution.  It creates to much extra work and overhead to maintain and it creates confusion as one would expect to see fields configured in the CMS according to their expected behavior.  

There are already application level constraints on required fields so i don't see why database level constraints are needed as well.  However, if we must have database level constraints perhaps just add an event that provides an easy opt-out of this functionality and keep the database constraints as a default.

**Comment by edster** [comment]
I'm of the opinion that the database level should be required if you want the field required, thats the whole point.

I agree that if it isn't to be required everywhere, it should be flagged as such when creating the field, and overridden to be required where it needs to be.
