### ISSUE TITLE
Translator Module

### ISSUE THREAD

**Issue by tomrey13** [pyrocms/pyrocms#4862]
With the Frensh language activated, when saving new translations ( doesn't matter if they are for another language ) the page returns a error.

I believe it's because of the Frensh slashes of the translation:

Like this:

`return [    
                        'title' => [    
                        'name' => 'Titre',
                                'instructions' => 'Entrez une titre pour cette page.',
            ],
                                'slug' => [    
                        'name' => 'Slug',
                                'instructions' => [    
                        'types' => 'Le slug est utilisé pour nommer la table en base de données.',
                                'pages' => 'Le slug est utilisé pour l'URL de la page.',
            ],`

**Comment by Eighke** [comment]
I confirm single quote are broken. Didn't notice before but French translation is basicaly impossible (we have ' everywhere :)).

PR: https://github.com/anomalylabs/translator-module/pull/26 @Pixney-William
