### ISSUE TITLE
[streams-platform] 'Saving' event is not fired if nothing has changed when translations are used.

### ISSUE THREAD

**Issue by bubba169** [pyrocms/pyrocms#4864]
**Describe the bug**
When saving a model, the `saving` event is usually fired so observers can modify the data before committing to the database. If translated fields are used then saving is skipped if the data is not dirty meaning the event is not fired. Some apps will require the event to fire regardless of if the data has changed. Also this behaviour is inconsistent between models that have translations and models that don't.

**To Reproduce**
1. Create a model with a translated field
2. Add a saving method in the observer
3. Save in the CMS without changing anything
4. The saving handler has not been called

**Expected behavior**
The `saving` event should be fired whenever `save` is called on a model.

**Comment by RyanThompson** [comment]
Looks like I am handling this differently here and there. A quick fix for the time being would be to observe the translatable model as well. Or trigger these corresponding models to both trigger during the event yourself. 

I think, however, I will end up making sure to fire the meta even updates on the form models manually which will trigger these events regardless as well.

**Comment by RyanThompson** [comment]
This has been fixed in 3.7
