### ISSUE TITLE
[documentation-module] Multilingual support errors

### ISSUE THREAD

**Issue by myshoeshurt** [pyrocms/pyrocms#4866]
**Describe the bug**
The website is multilingual but the documentation is not. A person visiting, for example, the german version of the site visits the documentation, he gets a broken documentation, because [de] is a valid locale, but no german documentation exists.

**To Reproduce**
1. Create a multilingual site
2. Go through a link to the documentation section
3. See error

**Expected behavior**
Ability to turn off multilingual support for documentation. I understand that some sites would translate their documentation, but not all.

**Screenshots**
![cmkol59](https://user-images.githubusercontent.com/8910904/48432921-69b27a00-e77e-11e8-858e-b3abf5687dd7.png)

**Comment by RyanThompson** [comment]
Really it should fallback all the same..
