### ISSUE TITLE
Using view() in twig

### ISSUE THREAD

**Issue by Eighke** [pyrocms/pyrocms#4868]
Shouldn't we consider using `view()` instead of `include` everywhere in twig? Because `include` cannot be override using `$overrides`, as results we basically need to override all the parents.

e.g. currently if you want to override `anomaly.module.posts::posts/partials/posts` you will need to override:

* anomaly.module.posts::posts/archive/index
* anomaly.module.posts::posts/categories/index
* anomaly.module.posts::posts/posts/index
* anomaly.module.posts::posts/tags/index
* anomaly.module.posts::posts/types/index

:(

**Comment by dakshhmehta** [comment]
I support this feature. Have faced such situation while creating an Admin theme in past.

**Comment by RyanThompson** [comment]
I would leave it up to you guys to override as needed. I like native Twig performance but you can use view if you wish.
