### ISSUE TITLE
Merging package.json addon

### ISSUE THREAD

**Issue by Eighke** [pyrocms/pyrocms#4869]
**Is your feature request related to a problem? Please describe.**
Creating "reusable" themes is a mess because of the dependencies. We need to commit and ship all the dependencies, the compiled one **and** the sources.

We can provide a `package.json` for the sources, but unlike `composer` it is not read from the main `package.json`.

**Describe the solution you'd like**
Using a tools like [lerna](https://lernajs.io/), with allow to do the same the `composer-merge-plugin` for `composer` . I successfully tested https://github.com/heikomat/minstall 

```json
{
    "name": "pyrocms",
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "postinstall": "minstall addons/*/*"
    },
    "devDependencies": {
        "axios": "^0.17",
        "bootstrap": "^4.0.0",
        "popper.js": "^1.12",
        "cross-env": "^5.1",
        "jquery": "^3.2",
        "laravel-mix": "^2.0",
        "lodash": "^4.17.4",
        "vue": "^2.5.7",
        "minstall": "^3.3.0"
    }
}
```

-------------------

It will simplify the installation of themes, with that I just need  a simple `npm install` inside Pyro root folder after installing my theme. And I don't need to ship anymore the sources (and the compiled files).

```scss
@import "~bootstrap/scss/bootstrap";
```

And

```twig
{{ asset_add('theme.css', 'theme::scss/theme.scss']) }}
```

So it can resume the installation of a theme with 2 commands

```
composer require namepace/theme
npm install
```

It should also help using `mix`.

**Comment by Eighke** [comment]
To go a bit more far. We can add a `webpack.mix.js` at the root of each theme.

```js
// /addons/app/namespace/name-theme/webpack.mix.js

let mix = require('laravel-mix');

const dir = __dirname;

mix
  .sass(dir+'/resources/scss/theme.scss', 'css/theme.css')
  .setPublicPath(dir+'/resources')
  .options({
    processCssUrls: false
  });
```

And in Pyro `webpack.mix.js`

```js
let mix = require('laravel-mix');
let glob = require('glob');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

// Themes webpack
let webpacks = glob.sync('addons/*/*/*-theme/webpack.mix.js');

webpacks.forEach(function(path) {
  require(`./${path}`);
});

...
```

So `npm run dev` will run all themes webpack automaticaly.

**Comment by Eighke** [comment]
Well, for people looking for it, to enable multi mix compilation

Change the **`package.json`** to use a new webpack config

```
--config=node_modules/laravel-mix/setup/webpack.config.js
// to
--config=webpack.config.js
```

Then create a **`webpack.config.js`** inside Pyro root directory.

```js
/**
 * As our first step, we'll pull in the user's webpack.mix.js
 * file. Based on what the user requests in that file,
 * a generic config object will be constructed for us.
 */

let mix = require('laravel-mix');

let ComponentFactory = require('laravel-mix/src/components/ComponentFactory');

new ComponentFactory().installAll();

require(Mix.paths.mix());

/**
 * Just in case the user needs to hook into this point
 * in the build process, we'll make an announcement.
 */

Mix.dispatch('init', Mix);

/**
 * Now that we know which build tasks are required by the
 * user, we can dynamically create a configuration object
 * for Webpack. And that's all there is to it. Simple!
 */

let WebpackConfig = require('laravel-mix/src/builder/WebpackConfig');

let configs = [
  new WebpackConfig().build()
];

let glob = require('glob');
let paths = glob.sync('addons/*/*/*-theme/webpack.mix.js');

paths.forEach(function(path) {
  delete require.cache[require.resolve('laravel-mix')];
  delete require.cache[require.resolve('laravel-mix/src/components/ComponentFactory')];

  mix = require('laravel-mix');

  ComponentFactory = require('laravel-mix/src/components/ComponentFactory');

  new ComponentFactory().installAll();

  require(`./${path}`);

  Mix.dispatch('init', Mix);

  let config = new WebpackConfig().build();

  configs.push(config);
});

module.exports = configs;
```

**Comment by RyanThompson** [comment]
We're introducing webpack as the default compiler and dependency resolver for themes (and addons) starting with Pyro 3.7: https://github.com/anomalylabs/streams-platform/tree/1.6/resources/stubs/addons

We will likely have to actually remove assetic in 4.0 because it's just falling so far behind. So all compiling will need to go here and asset class will be left for piping collections to the designated areas. 

One thing that concerns me with style dependencies throughout everything is that it binds up your installation. I really like having addons all self-contained. That's not to say that themes cant (and people do this - @Pixney-William is probably a good one to talk to about this) customize the way blocks look even specific blocks it's designed to support. 

All for thoughts on how to improve things now that mix is coming into the ... mix :-P

**Comment by Pixney-William** [comment]
mm.. I personally never use assetics. I wrote a quick dirty thing to speed up the procedure to get a theme up and running using mix called avviare (https://github.com/pixney/avviare-extension).

It basically removed directories not needed from the standard theme, adds the mix stuff to the metadata and asset twig for using the compiled js and css files. With a console option to pull in the latest package.json file from Larvavels repository..

Will probably have to be updated once 4.0 is released.

For blocks, i customize it to use my own wrapper for all blocks, that i have placed within my theme to make sure its all easy to access (https://github.com/pixney/wysiwyg_image_block-extension/blob/master/src/WysiwygImageBlockExtension.php#L18)

**Comment by Pixney-William** [comment]
![image](https://user-images.githubusercontent.com/31292231/51215941-f0243d00-1922-11e9-98c1-a769a8d84cab.png)

![image](https://user-images.githubusercontent.com/31292231/51215957-fe725900-1922-11e9-9a23-01b6d5a07e49.png)

**Comment by RyanThompson** [comment]
Im gonna close this as we're using mix now and I don't think a clear path to merging is both realistic but also desired. Addons should be standalone as much as possible.

**Comment by Eighke** [comment]
Be careful moving to Mix, Assetics is really convenient for 3rd party themes (and modules). If we need to develop Pyro ecosystem we will need:

1. Being able to manage `one-click-install` reusable themes. 
2. But without having to commit all `npm` dependencies (like we are doing now using Assetics).
3. And also being able to override the files easily.

`1.` is needed for 3rd party themes, nobody will ever start trying to sell/provide themes without that.Themes are usually sell on "low budget" projects. And "low budget" projects usually don't has real developers (individual for their own website, SMEs without any developer on board, marketing agencies for simple website).

`2.`, well it is not needed but better for maintenance. Having to commit all dependencies is not the best thing.

 `3.` is needed for developers and more complex projects.

-------------------

* Using Assetics only, we can do the 1. and 3., but it is impossible to do the 2.
  * If we `asset_add()` a `.scss` we will need mandatory the dependencies committed.
  * If we `asset_add()` a compilated `.css` we will need a way to recompile it (so the 3. is not possible).
* Using Mix only, we can do the 2., the 3. is possible but not as easy as Assetics. And it impossible to do the 1.
  * For 1., how do we move files to `/public` without a command?
  * For 3., we will need `npm` mandatory to recompile the files, for each `themes` or `modules` using it. Not that convenient.

For `mix` only. The `3.` can be partially solved using https://github.com/pyrocms/pyrocms/issues/4869#issuecomment-441534719 I gave above. It still needs `npm` but at least everything is managed in a single place. No need to go in each `addon` to compile the resources. But the `1.` is just not manageable, `mix` cannot copy anything outside the `npm` command.

-----------------

So my only guess is to use both Assetics and Mix.

* We pre-complile a `.css` (committed or generated in a `build.xml` ?) and it will be served using `asset_add()`.
* We provider a `package.json` and `webpack.config.js` allowing to recompile the `.css` if needed.
* We implement something like https://github.com/pyrocms/pyrocms/issues/4869#issuecomment-441534719 to recompile everything easily.

That way:
* `1.`. The themes are `one-click-install` by default.
* `2.`. No dependencies need to be committed.
* `3.`. We can override the files easily (not as easily as Assetics because we need `npm` installed, but it should do).

**Comment by Eighke** [comment]
@RyanThompson

**Comment by RyanThompson** [comment]
@Eighke I completely agree (part of me does) however here are a couple points to consider and also some clarification that might help:

1.) We are NOT removing `asset_*` functions or the `Asset` class. 
    a.) We ARE however removing the compiling functionality of the class. It will be a pipeline manager now.
2.) There will be some time with 3.7 to change over to the preferred (soon documented) method.
3.) Themes and modules now come with an out of the box (in 3.7) setup all you do is `npm install` and `npm watch` when you develop. Much better experience (as someone who is very new to mix). I love the asset class but Mix is where it's at - use our asset class to continue managing asset pipelines. 

Basically you compile to css/js FROM / USING Mix and use assets to pipe them into pyro like you normally would. No dependencies are necessary as the output is published to the addon. I think this still covers ALL our bases but makes things more modern and shows a good example / holds the hand of newer folk like myself to get into Mix and still make cool things easily.

Check out this addon for some guidance:

Mix: https://github.com/anomalylabs/tags-field_type/blob/2.4/webpack.mix.js
Includes: https://github.com/anomalylabs/tags-field_type/blob/2.4/resources/views/input.twig#L1-L2
Default .gitignore: https://github.com/anomalylabs/tags-field_type/blob/2.4/.gitignore

Hope that clears some things up! Still a very easy system.
