### ISSUE TITLE
Missing default value for locked_at column in streams_locks

### ISSUE THREAD

**Issue by G3z** [pyrocms/pyrocms#4873]
**Describe the bug**
Application crashes when editing a page type on a fresh install

**To Reproduce**
install a fresh copy of Pyro with a Postgresql 9.6 database

**Expected behavior**
Locked at column is not set with a default CURRENT_TIMESTAMP value

**Screenshots**
![schermata 2018-11-30 alle 11 06 08](https://user-images.githubusercontent.com/875086/49282656-fb64fb80-f48f-11e8-8255-96bc4f2af300.png)
<img width="2032" alt="schermata 2018-11-30 alle 11 06 53" src="https://user-images.githubusercontent.com/875086/49282683-0fa8f880-f490-11e8-99a2-1a0ec6310cc6.png">

**Comment by G3z** [comment]
[2018_05_03_020251_create_locks_table.php#L28](https://github.com/anomalylabs/streams-platform/blob/1.5/migrations/application/2018_05_03_020251_create_locks_table.php#L28) 
```
$table->datetime('locked_at');
```
should be 
```
$table->datetime('locked_at')->useCurrent();
```

source:[Laravel 5.5 Docs](https://laravel.com/docs/5.5/migrations#column-modifiers)

**Comment by RyanThompson** [comment]
This is created in the model now.
