### ISSUE TITLE
[forum-module] Initial discussion mentions not notifying mentioned users

### ISSUE THREAD

**Issue by emergingdzns** [pyrocms/pyrocms#4876]
**Describe the bug**
So I have the forum module installed. It is not set to require admin approval on new discussions. It posts discussions just fine. HOWEVER, if I mention someone like @ryanthompson does NOT send the mentioned user an email saying they were mentioned in a discussion. It DOES do so if mentioned in a comment. Am I simply doing something wrong? I'm looking at the code and it doesn't appear to have been added.

**To Reproduce**
Go to the forum.
Start a new discussion.
Mention a user in the discussion (not a comment).

**Expected behavior**
Mentioned user should receive a notification but does not.

**Comment by emergingdzns** [comment]
Any hope for a fix for this @RyanThompson ?

**Comment by emergingdzns** [comment]
Any update guys? I'm getting crap from my client because the app is released.

**Comment by edster** [comment]
Hey @emergingdzns, @RyanThompson is aware of the issue and has an idea of how to fix it.

He has it on his radar to tackle it today or tomorrow.

**Comment by emergingdzns** [comment]
Sorry to pester. Just wondering if there's an update. Thanks!

**Comment by emergingdzns** [comment]
Guys, any updates?

**Comment by RyanThompson** [comment]
Sorry meant to update this when I fixed it in 2.0 - the mentions system isn’t made to handle discussion level mention notifications. 

I can take another look. Currently I am bouncing around a 1.x update or 2.0 with a clear migration path and am leaning hard towards the latter based on the amount of cleaning house. 2.0 also is just about done. I could help with a migration if you’re open to that.

**Comment by RyanThompson** [comment]
In fact mentions in general got kinda botched in 1.0.. you could potentially listen from the outside and make a custom notification too

**Comment by emergingdzns** [comment]
Hmm. I tried to recreate the mention notification function but had no luck and got a bit lost.

How soon do you see 2.0 being ready? I'd love to be able to upgrade but will that require also upgrading to P3.5? Are the forum views different too? I've customized them a bit so I'll have to republish and re-apply my changes I assume.

**Comment by RyanThompson** [comment]
I am updating 2.0 very shortly - It'll be very close to the 3.7 release which is this month.
