### ISSUE TITLE
Setting CSRF to be false on route not working in 3.6

### ISSUE THREAD

**Issue by kiltedup** [pyrocms/pyrocms#4879]
**Describe the bug**
Setting 'csrf' => false on a route is having no effect in v3.6 - the VerifyCSRFToken middleware is triggered. Worked fine on 3.5 and earlier.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/31fe1872c858c965cf49035d840aa995a0b2ee08
