### ISSUE TITLE
Updated to 3.6 issue

### ISSUE THREAD

**Issue by laxmeeshchipsy** [pyrocms/pyrocms#4887]
On update getting error in image processing ..

""An exception has been thrown during the rendering of a template ("substr() expects parameter 1 to be string, object given")."" 
Above i have added error message help me to resolve ...
Also i have updated screen shoot help me to resolve. 

![screenshot from 2019-01-11 17-21-21](https://user-images.githubusercontent.com/39458090/51032280-680e0280-15c5-11e9-9ee2-07937463c840.png)

**Comment by Pixney-William** [comment]
Change .path to .url and see if that solves it!

**Comment by laxmeeshchipsy** [comment]
No still the same ... 
Same  "("substr() expects parameter 1 to be string, object given")"

**Comment by Pixney-William** [comment]
Why do yo do image(image.image).url()? Why not image.image.url()?

**Comment by laxmeeshchipsy** [comment]
I need print image path it not working after update .
Getting image substr() errror ...

**Comment by Pixney-William** [comment]
I get that, however i think it is wrong to use image() in this situation since the image is derived from your block.

**Comment by laxmeeshchipsy** [comment]
Its used same in version 3.3, there its fine. when i update to 3.6 it giving the error...

**Comment by laxmeeshchipsy** [comment]
Anyone ?

**Comment by RyanThompson** [comment]
Can you post this entire stack from your log - that way we can follow it down further. Trying to figure out what's using the substr function.

**Comment by RyanThompson** [comment]
Open er back up if you're still getting an issue! I'll assume you've fixed this otherwise :-)
