### ISSUE TITLE
[Pages Module, Links Module, Posts Module] Change button label to swap types is not descriptive

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#4889]
**Is your feature request related to a problem? Please describe.**
The orange change button label to swap types on the bottom of the form builders in the above modules is bad UX, it does not properly describe what it does. I had no idea what it was until Ryan brought it up.

**Describe the solution you'd like**
The labels should be overriden in each of the builders to better describe what it is doing.

For instance, on pages->fields, the change button should say `Change Type`. This will enhance the UX.

**Describe alternatives you've considered**
Any better descriptive wording would be fine, as long as it makes it more clear what the button is doing, you don't have the space limitations you have in the tables.

**Comment by RyanThompson** [comment]
I am going to reform action groups for forms to help reduce the footprint in the UI instead of going this route. I'd like to be more descriptive overall and this will help me here.
