### ISSUE TITLE
[accelerant-theme] 4.0 Enhancements

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4892]
This is a discussion around enhancing the UI for the 4.0 release of PyroCMS. Feel free to suggest your own ideas or contribute to the existing ones via discussion / links / resources / etc.

- [ ] Move to latest BS 4
Let's keep an eye out for what can be removed entirely in leu of core BS components.

- [ ] Remove any and all jQuery dependencies
This should be done and has been going on for a while globally. Remove all jQuery. Everything should be as standalone as possible.

- [ ] Move all modals to tingle.js
This is open for discussion. In general I think it's more flexible then BS modal but this might be different in 4.0

- [ ] Freshen up the entire UI
This is obviously open for discussion. I don't want to redesign but I want to freshen things up and polish it all a bit. Soften it even so that it's easier to look at day in and day out. In _general_ I would like to soften and lighten up the UI and visual weight of the CP.

- [ ] Freshen up the login screen

- [ ] Add more customization to settings. 
Company logo, branding, (login art if any), etc. This will likely get pushed to a **PRO** extension with a lot of options available to change.

- [ ] Add "stage" UI.
Very similar to the way LARGE modals work in WP. Where it's a whole page in and of itself where you can isolate areas of work and collapse back down. Really this just needs a layout to inject forms / tables into using "staged" flag to automate it. Very similar to modals but it'll be on the screen already. No Ajax.

**Comment by Pixney-William** [comment]
I like the ideas of freshening up the admin ui. It has issues with font size, paddings and margins. Even though its better after the setting thing i added that allows you to downsize things and have a static sidebar.

**My main concern is blocks and grids however:**

* Better overall layout for it (work on margins, paddings and how fields work in combination with each other) 
* Go over all field types and it's html markup. I would be willing to help, if you just trust / let me. Because currently the html hasn't gotten a lot of love.
*  The title field. It should be places on the dark row, and be editable at the same place. Should not have the title on the row and then below the input field. If you wanna skip js, id suggest some css/html to allow the row to look as if it wasn't an input field but it is and shows if you hover/click/focus it.
* Better documentation and examples of how to place fields in columns. Maybe even look at improving the functionality behind it. Because we definitely have to make sure people can build more complexed blocks with more fields without having to scroll 20 vh's.

**Comment by edster** [comment]
To what William is saying with `grids,repeaters,blocks`. Form sections should have a way to group fields into a single row from the array, rather then having to do a custom view. This would solve the issues all over the place.

I'm using sections to limit the scroll length by grouping into tabs, thus not needing to really do any overrides for tables+js. The icing on the cake would be able to declare the fields in a row.

I'm envisioning something along the lines of the below, if its an array, put them side by side, if not an array stack as per normal.
```
        $sections = [
            'options' => [
                'stacked' => TRUE,
                'tabs'    => [
                    'config'  => [
                        'title'  => 'Configuration',
                        'fields' => [
                            [
                                'featured',
                                'fall_back',
                            ],
                            [
                                'icon',
                                'theme',
                                
                            ],
                            'background_image',
                            'anouther_background_image'
                        ],
                    ],
                    'content' => [
                        'title'  => 'Content',
                        'fields' => [
                            'title',
                            'price',
                            'features',
                        ],
                    ],
                    'link'    => [
                        'title'  => 'Link Options',
                        'fields' => [
                            'button_text',
                            'target'
                        ]
                    ]
                ]
            ]
        ];
```

**Comment by Pixney-William** [comment]
Agreed, i also would like to be able to manage this in the section array.

**Comment by RyanThompson** [comment]
> **My main concern is blocks and grids however:**
> 
> * Better overall layout for it (work on margins, paddings and how fields work in combination with each other)
> * Go over all field types and it's html markup. I would be willing to help, if you just trust / let me. Because currently the html hasn't gotten a lot of love.
> * The title field. It should be places on the dark row, and be editable at the same place. Should not have the title on the row and then below the input field. If you wanna skip js, id suggest some css/html to allow the row to look as if it wasn't an input field but it is and shows if you hover/click/focus it.
> * Better documentation and examples of how to place fields in columns. Maybe even look at improving the functionality behind it. Because we definitely have to make sure people can build more complexed blocks with more fields without having to scroll 20 vh's.

Blocks and the others will be providing their own UI/styling instead of using so much of the theme going forward. 

**I have half a mind to remove grid because it's essentially blocks.**

But blocks and repeater for sure will be getting separate UI improvements and that'll be pushed into their own repositories.

**Comment by RyanThompson** [comment]
> I'm envisioning something along the lines of the below, if its an array, put them side by side, if not an array stack as per normal.

Also agreed on that - we have layout control for columns n stuff but it needs to be more intuitive. Currently it takes some pretty hefty array configuration and if I recall it's limited to one row. So that could certainly be improved.

**Comment by Pixney-William** [comment]
Too many websites are out there using grid. So i would not drop support for it. However, not including it may be fine.

**Comment by RyanThompson** [comment]
Ya it would be a soft deprecation

**Comment by Pixney-William** [comment]
Fine with me!

**Comment by edster** [comment]
> Blocks and the others will be providing their own UI/styling instead of using so much of the theme going forward.
> But blocks and repeater for sure will be getting separate UI improvements and that'll be pushed into their own repositories.

I don't think this is necessary, the overall ui is fine, with the title being moved to the bar, be able to auto collapse the headers. And put x fields into a single row fixes almost all the issue with it except for maybe some of your layout blocks your thinkingof.

**Comment by Pixney-William** [comment]
Another thing i would like to see, is some thought into how to make it easier for people who might want to create their own ADMIN themes. Let's say i would like to create a theme based on VUE where we could have field validations and other things that would make the work faster.

Today, it's too many changes happening randomly to the current admin theme to be able to support it. Esp with not that many people buying themes, it wouldn't be worth it.

I will think about this myself. But would like to see if others have thoughts around this.

**Comment by RobinRadic** [comment]
@RyanThompson I spotted a few commits in which you where replacing twig by blade. But then it went back to twig.

Was there any reason to revert back to twig? I'd really like to see blade as default. Twig in laravel 
 decreases developer experience _a lot_, is completely unnecessary and undermines the statement "Pyro feels like a natural extension of Laravel. We do not try and hide it but embrace it everywhere."

**Comment by edster** [comment]
@RobinRadic  We are discussing moving to blade with an optional extension to keep all functionality currently existing via our twig implementation. We are concerned about the breakage and refactoring needed for all existing users modules /sites so trying to find a way to soften that blow if we are going to strip it.
________________________________

**Comment by RobinRadic** [comment]
@edster where is this discussion taking place? is it on slack?

**Comment by edster** [comment]
Yea

--------
Regards,
Edi Mange

**Comment by RyanThompson** [comment]
Laravel + AlpineJS + Streams + Tailwind

The LAST stack :-P
