### ISSUE TITLE
We need better upgrade guides - Httpcache directory does not exist

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4893]
**Describe the bug**
I updated from 3.4 to 3.6, and i have this exception thrown.

**Screenshots**
![image](https://user-images.githubusercontent.com/31292231/51374210-94b0a580-1b02-11e9-847e-4b11065bbfa0.png)

**Comment by webformatik-pyrocms-pro** [comment]
I think you forgot updating you pyro folder structure?

See: https://github.com/pyrocms/pyrocms/commit/2b7c4ed0eed8129097b371e808ed0d390fff779e

**Comment by Pixney-William** [comment]
Is that in the docs somewhere?

(to be clear, trying to figure out if docs need improvements or if i have just missed it, or if there should be logic creating it) @webformatik-pyrocms-pro

**Comment by mmodler** [comment]
(Now with right github account :) )

We definitely need upgrade guides like laravel has.

For upgrades i work through the commits to pyro repo:

https://github.com/pyrocms/pyrocms/commits/3.6

But its hard work atm ;)

**Comment by Pixney-William** [comment]
Right, this is an improvement we need to have ASAP. It's even more important than documentation since updates happen quite often.

**Comment by mmodler** [comment]
Yes, i often missed things especially composer package version updates and pyro config or folder changes.

@RyanThompson 3.7?

**Comment by Pixney-William** [comment]
![image](https://user-images.githubusercontent.com/31292231/51382933-5c1bc680-1b18-11e9-8d43-b242a6630ccd.png)

**Comment by RyanThompson** [comment]
I can certainly do this. I like the idea of a change-log too.

**Comment by RyanThompson** [comment]
Updated the post and will be more granular in the future for sure. Those the "table of versions".. it's called a composer.json file lol. I will pry start using a text comparator output to show better overview of what's changing though.
