### ISSUE TITLE
Addon-Module Undefined index versions

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4895]
**Describe the bug**
When clicking on addons to go to addons this exception is thrown. Seems like it always happen when you have your own modules installed.. What are my modules missing alternatively what is wrong in addons module?

![image](https://user-images.githubusercontent.com/31292231/51390874-d35d5480-1b30-11e9-89d2-90e50a848b4c.png)

**Comment by RyanThompson** [comment]
Odd.. I don't get that. But preventing it anyways.

Fixed: https://github.com/anomalylabs/addons-module/commit/ba159846347d3ea4a0ff767f8c0e69dfc137a33a
