### ISSUE TITLE
Can't install the CMS

### ISSUE THREAD

**Issue by bradsapp** [pyrocms/pyrocms#4898]
Downloaded via composer. 
```
composer create-project pyrocms/pyrocms
```

Go to pyrocms.test/installer and fill out the form. Click install...get the error below. It's happened on 2 different computers. I'm on MacOS in a homestead environment.

```
[2019-01-18 16:02:18] local.ERROR: compact(): Undefined variable: entry {"url":"http://pyrocms.test/installer/run/31","identifier":"de286137-017a-4f85-847b-555ea1fabad2","exception":"[object] (ErrorException(code: 0): compact(): Undefined variable: entry at /home/vagrant/sites/pyrocms/vendor/anomaly/streams-platform/src/Entry/EntryTranslationsModel.php:169)
```

**Comment by robinvoor** [comment]
Have you tried [automating the CLI installer](https://pyrocms.com/documentation/pyrocms/3.4/installation/installing-pyrocms#automating-the-cli-installer)? Scroll down to **Automating the CLI installer** if your browser won't do it automatically.

**Comment by bradsapp** [comment]
Yes both ways still causes an error for me.

**Comment by RyanThompson** [comment]
Can you give us the full stack? Are you still experiencing this issue?

**Comment by vagkaefer** [comment]
In my case:

```
33/57 Seeding: Dashboard Module
In EntryTranslationsModel.php line 169: compact(): Undefined variable: entry
```

The problem is the PHP 7.3, in this version the compact() function was changed. The people needs to downgrade the php, the version 7.3 is not compatible yet...

**Comment by ghost** [comment]
As @vagkaefer said, PHP 7.3 causes issue here; I got the same error. I could move on to finish installation by changing EntryTranslationsModel.php at line 169 to be: 
`if(isset($entry)){
            $fieldType->fire($trigger, array_merge(compact('fieldType', 'entry'), $payload));
            } else {
              $fieldType->fire($trigger, array_merge(compact('fieldType'), $payload));  
            }`

My environment: Antergos Linux, PHP 7.3.

**Comment by RyanThompson** [comment]
7.3 isn't supported until 3.7 releases here shortly on Laravel 5.3 and a load of updates.

**Comment by LeTranAnhVu** [comment]
Hi. 

> In my case:
> 
> ```
> 33/57 Seeding: Dashboard Module
> In EntryTranslationsModel.php line 169: compact(): Undefined variable: entry
> ```
> The problem is the PHP 7.3, in this version the compact() function was changed. The people needs to downgrade the php, the version 7.3 is not compatible yet...

Hi, Have you find the solution. I just got the same issue. how to deal with that thing.

**Comment by edster** [comment]
Downgrade to 7.2

**Comment by vagkaefer** [comment]
> Hi.
> 
> > In my case:
> > ```
> > 33/57 Seeding: Dashboard Module
> > In EntryTranslationsModel.php line 169: compact(): Undefined variable: entry
> > ```
> > The problem is the PHP 7.3, in this version the compact() function was changed. The people needs to downgrade the php, the version 7.3 is not compatible yet...
> 
> Hi, Have you find the solution. I just got the same issue. how to deal with that thing.

I edited some files, solved this problem, but then others started to emerge. In the end I returned to version 7.2.

**Comment by ngocsangyem** [comment]
I still have this issue

```
php -v
```
output

```
PHP 7.2.18 (cli) (built: May  2 2019 13:03:01) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.18, Copyright (c) 1999-2018, by Zend Technologies
```
I using Mamp on MacOs Mojave

Any way to fix this? Thanks
