### ISSUE TITLE
[Streams-Platform v1.5.50] - Fields assigned to streams will not be on db table if installed via GUI

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#4899]
**Describe the bug**
Fields are not being created when installing via the GUI. If you install via CLI they are.

Streams platform versions:
v1.5.50

**To Reproduce**
1. Install a module/addon with streams and fields 
2. Install via gui
3. Check the DB, non of the assigned fields will be there.
4. reinstall via CLI
5. Check the DB, all fields will exists.

**Expected behavior**
GUI and CLI installation should resolve the same.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/6d297f8c047b07361496213db86b167caf65813b

Good find!
