### ISSUE TITLE
[3.6][Pages-module] Security (kind of) issue with HTTPCache enabled

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4902]
**Describe the bug**
1) Http cache is on
2) You visit a page
3) You go into the admin and disable that page
4) You visit that page again
5) Its not unabled.
6) Clear http cache
7) Try visit the page - you cant.
So the problem is nr 5

**Expected behavior**
As soon as you set a page to not be enabled, you should not be able to visit that page. Question is why we don't clear the http cache right now when saving it after setting the enabled flag?

**Comment by RyanThompson** [comment]
Duplicate of the prior - you're logged in so you can preview pages. Disable. Logout. View the URL. 404.
