### ISSUE TITLE
[3.6][Pages-Module] HTTP Cache prevents pages to be updated if one is enabled

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4903]
**Describe the bug**
So this is very weird, and i am trying to get my head around it. See the image: 
![image](https://user-images.githubusercontent.com/31292231/51644328-1aec4200-1f70-11e9-86dd-f11b6038a6b8.png)

Here i have set About to enabled=false.

I clear my httpcache. Once i do that, if i edit the titlle for example on the pages below (gotta test and pyrocms) it doesnt show on their pages even though they are enabled and its cache should clear on save right?

However, if i do enable about, clear my cache, and then edit and save those two other pages, it works as expected.

**Comment by RyanThompson** [comment]
This looks to be working as desired. However being logged in as an admin you can preview pages at their URLs so to better test. Set to disabled. LOGOUT. Then try the page. You'll be greeted with a 404. Also the TTL is set to 0 when disabled to prevent cache from building back up.
