### ISSUE TITLE
[3.6]&[3.7][Pages-Module] Page urls as children is really getting messed up

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4904]
**Describe the bug**
(This happens only if its parent is set to enabled=false - see first image there and the about page)

Create a page (set it to enabled=false), then a child page and last a child of that. See image:

![image](https://user-images.githubusercontent.com/31292231/51644813-e7aab280-1f71-11e9-9559-f818581eaec7.png)

The last page there has a very strange URL - See image:
![image](https://user-images.githubusercontent.com/31292231/51644843-fb561900-1f71-11e9-8491-257a4c2d8996.png)

If you place it as a sibling to the other one, then the url is fine, see image:
![image](https://user-images.githubusercontent.com/31292231/51644873-145eca00-1f72-11e9-9309-5df33682045d.png)

If you then again place it as a child of the other.. Its messed up again. Move it to a sibling, its fine.. and so on..

**Comment by Pixney-William** [comment]
This happens only if its parent is set to `enabled=false` - see first image there and the about page

**Comment by edster** [comment]
Well the parent is false so I'm guessing it can't determine the url currently.

This looks like a display bug rather then a functionality bug.

**Comment by Pixney-William** [comment]
As for the display blug, it's not only that since i can't visit the actual url : `https://pixney.com/about/technology/cms` - that is 404.

Also `https://pixney.com/pages/preview/sEtzOaw8hypocGlyXf8CFETr/technology/cms` is a 404

**Now, i understand where the preview_id_string thing comes form. However, if it is placed on the childs child url and not the childs - isnt that strange?**

Also, what are we really trying to achieve here? To "disable" all urls beneath it? If so, why don't we loop through the children and set them to disabled too? 

**This is how it all looks**

![image](https://user-images.githubusercontent.com/31292231/51645890-82a58b80-1f76-11e9-91f0-aaa4a090999d.png)

![image](https://user-images.githubusercontent.com/31292231/51645902-93560180-1f76-11e9-9827-cc1698fe8917.png)

![image](https://user-images.githubusercontent.com/31292231/51645917-9d780000-1f76-11e9-8e74-67e87a4b2e35.png)

![image](https://user-images.githubusercontent.com/31292231/51645929-a8cb2b80-1f76-11e9-9bb3-52946cd31861.png)

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/pages-module/commit/fb9b17b185f7821cc76c463614e10539f7d66f27
