### ISSUE TITLE
Maintenance Mode error

### ISSUE THREAD

**Issue by ikoniqoz** [pyrocms/pyrocms#4915]
**Describe the bug**
When setting Maintenance Mode to ON I get error on fresh install of pyrocms v3.6.4

**To Reproduce**
1. Go to 'Admin -> Settings -> System -> Maintenance and set to ON
2. Update to save the setting then Log out to check front-end
3. View Front-end Home page and observe error Refer included screenshot.

**Expected behavior**
Site Closed for Maintenance notice as in pyrocms 2.x.

**Screenshots**
![screen shot 2019-02-09 at 4 45 25 pm](https://user-images.githubusercontent.com/3609155/52517143-7f0a4800-2c8a-11e9-9ee7-4f34ae989b40.png)

**Desktop (please complete the following information):**
 - OS: [Mac OS X Mojave 10.14.1]
 - Browser [Chrome]
 - Version [Version 72.0.3626.96 (Official Build) (64-bit)]

**Comment by RyanThompson** [comment]
This will happen when you have debugging enabled. To see the pretty version of it disabled debug mode :-)
