### ISSUE TITLE
[stream-platform] Move to cartalyst/assetic

### ISSUE THREAD

**Issue by Eighke** [pyrocms/pyrocms#4921]
Assetics is blocking to move to Laravel 5.7. Currently the plan is to remove it on `stream-platform` 1.7 (Pyro 4.0). Instead we can just move to `cartalyst/assetic`. Cartalyst forked the repository and fixed the Symfony deps. I think using Cartalyst should be safe enough.

It will allow to have Assetics and Laravel 5.7 in the same time (good for people that need Laravel 5.7 but has no time to convert every addons). And we can also move to Laravel 5.7 right away (it is the last package blocking it).

**Comment by Eighke** [comment]
PS: I tried to change the deps and it is working: https://github.com/Eighke/streams-platform/commit/b7ba2c11b3617f32bba15415474c5e3c66cdbad8

**Comment by Eighke** [comment]
`$bindings` and `$singletons` in `StreamsServiceProvider` are now already registered in the `Application`. So it can be removed from the `register()`, but they need to be public.

**Comment by Eighke** [comment]
https://github.com/Eighke/streams-platform/tree/laravel57

**Comment by edster** [comment]
@Eighke are you intending to do a PR for this? If so please submit one and link to it here.

**Comment by Eighke** [comment]
@edster I am, but I need to be sure everything is functional before that. :)

**Comment by edster** [comment]
Just checking 😉

**Comment by Eighke** [comment]
So, it looks good. I didn't test all modules on all versions, but I converted my website without problem.

The only package I found that failed is the sitemap-extension (it is using an old version of `laravelium/sitemap`, so it need to be updated)

**Comment by RyanThompson** [comment]
Done - SP 1.6
