### ISSUE TITLE
Generated Files - Public Directory Permissions

### ISSUE THREAD

**Issue by omniwired** [pyrocms/pyrocms#4927]
I'm working in an environment where we are required to have dynamically generated files to a minimum.

Is it possible to run this CMS without public/app being 777?

Is there a reliable, stable, consistent way to "pre-generate" all the necessary files in this folder before putting the site live?

**Comment by RyanThompson** [comment]
You only need to allow for writable by the application. 755 or whatever would work fine as well. 

Currently there isn't though 3.7 coming out here in a little less than a month has a cache warmer we might be able to use. It crawls your sitemap to warm HTTP cache. We could do the same to hit/trigger compiling by touching pages. But the markup / stylings dictate images so there's no other good way to do it but trigger those things to generate.

**Comment by omniwired** [comment]
Thanks Ryan.

That is along the lines what I been doing, visiting the pages to generate locally the files.
Then committing those files and pushing.

**Comment by RyanThompson** [comment]
Here is the cache warming if you want to implement something like it on your end: https://github.com/anomalylabs/streams-platform/blob/1.6/src/Http/Console/Warm.php

Pretty simple crawler.

**Comment by RyanThompson** [comment]
Are you running behind a load balancer or something? Curious as to why you need to pre-process this stuff.

**Comment by omniwired** [comment]
yes is running behind a load balancer and the deploys have to be similar to each other.

send me a DM in twitter (@omniwired ) and I can tell you more about it.
