### ISSUE TITLE
Laravel Telescope preventing composer update

### ISSUE THREAD

**Issue by JorodriguezNA** [pyrocms/pyrocms#4934]
**Describe the bug**
Updating composer and running composer update runs into a problem.

installing an application using the original composer config file, then applying the changes to update.

Then I ran composer update.

Got this error in console:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - anomaly/system-module v1.0.0 requires laravel/telescope ^1.0 -> satisfiable by laravel/telescope[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9, v1.1].
    - anomaly/system-module v1.0.1 requires laravel/telescope ^1.0 -> satisfiable by laravel/telescope[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9, v1.1].
    - anomaly/system-module v1.0.10 requires laravel/telescope ^1.0 -> satisfiable by laravel/telescope[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9, v1.1].
    - anomaly/system-module v1.0.11 requires laravel/telescope ^1.0 -> satisfiable by laravel/telescope[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9, v1.1].
    - anomaly/system-module v1.0.12 requires laravel/telescope ^1.0 -> satisfiable by laravel/telescope[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9, v1.1].
    - anomaly/system-module v1.0.13 requires laravel/telescope ^1.0 -> satisfiable by laravel/telescope[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9, v1.1].
    - anomaly/system-module v1.0.14 requires laravel/telescope ^1.0 -> satisfiable by laravel/telescope[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9, v1.1].
    - anomaly/system-module v1.0.15 requires laravel/telescope ^1.0 -> satisfiable by laravel/telescope[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9, v1.1].
    - anomaly/system-module v1.0.2 requires laravel/telescope ^1.0 -> satisfiable by laravel/telescope[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9, v1.1].
    - anomaly/system-module v1.0.3 requires laravel/telescope ^1.0 -> satisfiable by laravel/telescope[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9, v1.1].
    - anomaly/system-module v1.0.4 requires laravel/telescope ^1.0 -> satisfiable by laravel/telescope[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9, v1.1].
    - anomaly/system-module v1.0.5 requires laravel/telescope ^1.0 -> satisfiable by laravel/telescope[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9, v1.1].
    - anomaly/system-module v1.0.6 requires laravel/telescope ^1.0 -> satisfiable by laravel/telescope[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9, v1.1].
    - anomaly/system-module v1.0.7 requires laravel/telescope ^1.0 -> satisfiable by laravel/telescope[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9, v1.1].
    - anomaly/system-module v1.0.8 requires laravel/telescope ^1.0 -> satisfiable by laravel/telescope[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9, v1.1].
    - anomaly/system-module v1.0.9 requires laravel/telescope ^1.0 -> satisfiable by laravel/telescope[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9, v1.1].
    - laravel/telescope v1.1 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement.
    - laravel/telescope v1.0.9 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement.
    - laravel/telescope v1.0.8 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement.
    - laravel/telescope v1.0.7 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement.
    - laravel/telescope v1.0.6 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement.
    - laravel/telescope v1.0.5 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement.
    - laravel/telescope v1.0.4 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement.
    - laravel/telescope v1.0.3 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement.
    - laravel/telescope v1.0.2 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement.
    - laravel/telescope v1.0.13 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement.
    - laravel/telescope v1.0.12 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement.
    - laravel/telescope v1.0.11 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement.
    - laravel/telescope v1.0.10 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement.
    - laravel/telescope v1.0.1 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement.
    - laravel/telescope v1.0.0 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement.
    - Installation request for anomaly/system-module ~1.0.0 -> satisfiable by anomaly/system-module[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.14, v1.0.15, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9].

[config_original.txt](https://github.com/pyrocms/pyrocms/files/2937168/config_original.txt)
[config_updated.txt](https://github.com/pyrocms/pyrocms/files/2937169/config_updated.txt)

**Comment by RyanThompson** [comment]
> laravel/telescope v1.1 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement
