### ISSUE TITLE
[streams-platform] Messages broken on 1.6

### ISSUE THREAD

**Issue by Eighke** [pyrocms/pyrocms#4941]
**Describe the bug**
Twig message_* are broken.

**To Reproduce**
Just save anything, not message

**Additional context**
The Twig plugin is using `config()` ^^;

**Comment by edster** [comment]
@eighke, please follow the issue templates and provide some code.

**Comment by Eighke** [comment]
What code? The messages are not working.That all.

**Comment by Eighke** [comment]
@RyanThompson I cannot open it back :(

**Comment by edster** [comment]
What do you mean by `messages_*`
Is this on a page? a form builder? A view file?

I'm getting messages on forms in 1.6

**Comment by Eighke** [comment]
https://github.com/anomalylabs/streams-platform/blob/9d3da4cc11a5a30d18e43eaf1ca520924e787025/src/StreamsPlugin.php#L601

As I pointed out, it is now using the `config()`, I guess it is a mistake. But I'm not sure, I'll let Ryan check that out. But switching back to `session()` is working.

If it is working for you, check with 1.6 you got, it was changed in the` v1.6.61`.

**Comment by RyanThompson** [comment]
Fixed
