### ISSUE TITLE
Streams delete property should default to false.

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4943]
When appending streams information, you need to set the delete property to false to make sure it's not deleted. 

**Describe the solution you'd like**
This value should default to false instead, and you should set it to true if you would like it to be deleted.

**Comment by RyanThompson** [comment]
Done: https://github.com/anomalylabs/streams-platform/commit/8c1854e004f8ffa84c8a91fb8850708be8ec71c0
