### ISSUE TITLE
[navigation-module] - Can't edit link

### ISSUE THREAD

**Issue by vargvinter** [pyrocms/pyrocms#4944]
Hello,

After creating link in menu I can't edit it. It's unclickable.

When change this https://github.com/anomalylabs/navigation-module/blob/2.4/src/Link/Tree/LinkTreeSegments.php#L25
into
`entry.edit_link`

it works again.

**Comment by stockhausen** [comment]
Helllo, Same probleme here @RyanThompson

**Comment by RyanThompson** [comment]
This was the culprit.. Patched back to 1.7: https://github.com/laravel-streams/streams-core/commit/180a69f62ca36396f3b15826b7ce0b946a253896
