### ISSUE TITLE
[Streams v1.6 (3.7) - Grid 1.4] Versions not working.

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4949]
**Describe the bug**
Versions are not working on content within the grid.

**To Reproduce**
Add a grid to your page with a wysiwyg editor. Within the editor, write: "Trump".

Then click save.

Change the content in the wysiwyg editor to say: "Putin.".

Click save.

Then go into versioning and try to load the first version.. Nothing happens for the grid..

**Expected behavior**
After reload i should see : "Trump" in the grid wysiwyg editor.

**Comment by RyanThompson** [comment]
Update - added note to docs too

**Comment by Pixney-William** [comment]
I will let you close this since you didn't like the title. But to be clear, this had nothing to do with the grid field v.1.4. This was meant to be the other issue, which if you read the description you'd figured:)
