### ISSUE TITLE
[streams-platform] [urgent] Duplicate entry in CP table builder

### ISSUE THREAD

**Issue by oimken** [pyrocms/pyrocms#4955]
**Describe the bug**
Upgrade to PyroCMS 3.7 beta with No error,  but..
If default language is not english, create a entry for a module(such as `admin/navigation`),
in list view will show duplicate entries.

**To Reproduce**
1. Go to `admin/settings#tab-localization` enable more than one language and set default language to the non-english one.
2. Go to `admin/navigation/create` and create a menu.
3. Go to `admin/navigation`, you will see a duplicate entries

**Desktop (please complete the following information):**
 - OS: OSX valet  php7.1
 - Browser chrome
 - Version [3.7 beta]
# #

**Comment by oimken** [comment]
Btw:
Set default language to `en`,  table display collect.

**Comment by RyanThompson** [comment]
Ill check it out - it undoubtedly has to do with https://github.com/anomalylabs/streams-platform/blob/1.7/src/Model/EloquentQueryBuilder.php#L351

**Comment by oimken** [comment]
@RyanThompson I don't think so.
https://github.com/anomalylabs/streams-platform/blob/1.6/src/Model/EloquentQueryBuilder.php
they are same...

**Comment by RyanThompson** [comment]
Indeed the issue was related to: https://github.com/laravel-streams/streams-core/commit/180a69f62ca36396f3b15826b7ce0b946a253896
