### ISSUE TITLE
[streams-platform] Unable to create configured logger

### ISSUE THREAD

**Issue by oimken** [pyrocms/pyrocms#4956]
**Describe the bug**
Upgrade from 3.6 to 3.7beta with no error,   got `logger.php` in `config` folder already.
but:
```
 Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at ............/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:168)
```

**To Reproduce**
1. Upgrade to 3.7 beta and check `storage/logs/laravel.log` 

**Expected behavior**
no error.

**Comment by Pixney-William** [comment]
And the logger looks at the following? https://github.com/pyrocms/pyrocms/blob/3.7/config/logger.php

**Comment by oimken** [comment]
yes. I download and put it into `config`

But I fixed this just now....

### Rename `logger.php` to `logging.php`, Log comes alive again!!!

**Comment by Pixney-William** [comment]
Correct, that is the right name for it

**Comment by mmodler** [comment]
+1

Ryan, fix it :)
