### ISSUE TITLE
Override table/ajax.twig

### ISSUE THREAD

**Issue by Fellner96** [pyrocms/pyrocms#4959]
Hi. I have an issue to override table/ajax.twig. I want to replace the file uploader table but i cant override table/ajax. Working in the admin theme, all works correctly except this. Any idea?

I tried override in serviceprovider, resource/streams/table/ajax in theme, all the other way..

When i debug the twig loader, all the files land in the public function findTemplate($name) with the name like: anomaly.module.example::folder/view but the table/ajax return with the full path and return the file in the findTemplate:

if ($this->files->exists($name)) {
            return $name;
        }

Then override after this if statement.

**Comment by Eighke** [comment]
Hi @Fellner96 

See https://github.com/pyrocms/pyrocms/issues/4868

**Comment by Fellner96** [comment]
> Hi @Fellner96
> 
> See #4868

I saw this issue but my problem is with view and not the include.

**Comment by Eighke** [comment]
If you are using view(), it should has no problem. I already overrided many file w/o problem. Just remember than only the one using view() can be overrided.
