### ISSUE TITLE
[files-module] [pyrocms 3.7 beta]Move file failure

### ISSUE THREAD

**Issue by oimken** [pyrocms/pyrocms#4963]
**Describe the bug**
Move file will failure if the folder has  custom fields assigned.
Error:
```
Exception thrown with message "The [type] parameter of [link] is required and should be string."
```
 
**To Reproduce**
1. Go to 'admin/files/folders', create two test folder and assign some different fields to each folder
2. Go to ''admin/files', upload a file in one folder, and edit it ,input something into fields 
3. Try move this file to the other folder

**Expected behavior**
Clear out the old value if target folder did not have that field

**Comment by oimken** [comment]
I check the Database found that:
`folder_id` is changed , but it seems @RyanThompson you miss the `entry_type`

**Comment by RyanThompson** [comment]
On it.
