### ISSUE TITLE
Duplicating translateble fields in pyro 3.7

### ISSUE THREAD

**Issue by fatihalp** [pyrocms/pyrocms#4965]
**Describe the bug**
After upgrading to pyrocms 3.7 translatable fields duplicates data if 2 languages activated. 

**To Reproduce**
1- Create new module and steream. 
2- Activate 2 language.
3- Change language to Turkish
4- Try to get data like: 
```
        $data = new PostModel();
        dd($data->get()->toArray());
```
5- You will see data is duplicated. 

**Screenshots**
https://i.imgur.com/9ymVymw.png
https://i.imgur.com/F4hlc86.png
https://i.imgur.com/6g4tvtC.png

**Desktop & Smartphone**
All

**Comment by Pixney-William** [comment]
Is this the same issue that Oimken had @RyanThompson ?

**Comment by fatihalp** [comment]
I dig into issue and duplicated with Posts module. Create multi language post. Change language to other then English. (Change to Turkish) Make this query : 

```
        $data = new PostModel();
        dd($data->get()->toArray());
```
It's duplicating post: 

https://i.imgur.com/Cri4azX.png
![image](https://user-images.githubusercontent.com/219454/56741022-c036d200-677a-11e9-8cd5-d683e2c7a5d7.png)

**Comment by RyanThompson** [comment]
@fatihalp thanks a ton for the bug report - well done! I've fixed this here if you would like to confirm: https://github.com/anomalylabs/streams-platform/commit/b998fcecfab378c9feccd01f914898d54b62eadc
