### ISSUE TITLE
Installation doesn't activate other languages then English in pyrocms 3.7

### ISSUE THREAD

**Issue by fatihalp** [pyrocms/pyrocms#4966]
**Describe the bug**
I'm making fresh new installation with pyro 3.7  

**To Reproduce**
1- Install pyrocms 3.7 other then English (like Turkish)
2- You will see it will only activate English. 
3- Also it doesn't care default language. Site is in English.

**Screenshots**

![image](https://user-images.githubusercontent.com/219454/56737569-67177000-6773-11e9-8556-aba4979bdae4.png)

**Desktop & Smartphone**
All

**Comment by Eighke** [comment]
But in Enabled Languages on your screen, Turkish is not available. So it cannot enable it, and it will fallback on Laravel configuration (so `en`).

**Comment by fatihalp** [comment]
Enabled language should be only Turkish

**Comment by Eighke** [comment]
No it doesn't work like that. Currently it is misleading because of the fields order. Enabled languages should be first.

What should not be possible is to select a Default language which is not in the Enabled languages.

**Comment by ozcan-durak** [comment]
I think he's trying to say, That while installation he had selected preferred language suppose "Turkish". Then after he runs says enabled languages still keeps English rather than Turkish.

**Comment by RyanThompson** [comment]
Ah the default value for enabled locales does not account for the current (installed data) locale.

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/settings-module/commit/1ed5b73b6ed1e466ea510ad962c3aab115c0346c
