### ISSUE TITLE
[documentation] Implementing Versioning: Use different VersionRouter class

### ISSUE THREAD

**Issue by finnito** [pyrocms/pyrocms#4968]
**What are you trying to do?**
When following the [Implementing Versioning](https://pyrocms.com/help/addon-development/modules/implementing-versioning) guide it is describing how to implement versioning for a model. However, the route is not properly registered when following the guide and a 404 is given.

**Problem**
It tells you to use this class as the `VersionRouter`:
```
use Anomaly\Streams\Platform\Assignment\VersionRouter;
``` 

But if you do so, the route is not registered properly.

**Solution**
I looked in `VariablesModuleServiceProvider` to see how it was done there and it uses this class instead:
```
use Anomaly\Streams\Platform\Version\VersionRouter;
```
By using this class instead, the route is properly registered and all is well!

**Documentation**
[https://pyrocms.com/help/addon-development/modules/implementing-versioning](https://pyrocms.com/help/addon-development/modules/implementing-versioning)

**Comment by RyanThompson** [comment]
Whoops! Good catch, thanks! Fixing now.
