### ISSUE TITLE
Pyro 3.7 installation gives error if you select any other language then English

### ISSUE THREAD

**Issue by fatihalp** [pyrocms/pyrocms#4973]
**Describe the bug**
Can't install any other language then English.

**To Reproduce**
1. Install Pyro 3.7 in Turkish.
2. You will get an error. 
3. message: "SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'menu_id' cannot be null (SQL: insert into `default_navigation_links` (`menu_id`, `target`, `entry_id`, `entry_type`, `type`, `updated_by_id`, `created_by_id`, `sort_order`, `updated_at`, `created_at`) values (, _blank, 1, Anomaly\UrlLinkTypeExtension\UrlLinkTypeModel, anomaly.extension.url_link_type, , , 1, 2019-05-15 03:40:40, 2019-05-15 03:40:40))"

**Screenshots**

![image](https://user-images.githubusercontent.com/219454/57755581-edcbc700-76f9-11e9-9072-5c7daf07a3af.png)

**Comment by Eighke** [comment]
Same for User module.

The seeders only seed `en`, so if you set the locale to something else than `en`, it will not find any translation. And LinkSeeder will not be able to find the menu. For the User it is the Role that will not be found.

Setting the locale to `en` during install and switch after is not better, most of the seeded entries in the admin will not be accessible for the same reason.

@RyanThompson

**Comment by fatihalp** [comment]
It still gives and error :( @RyanThompson

**Comment by RyanThompson** [comment]
This has been resolved:

https://github.com/anomalylabs/streams-platform/commit/21daf3817257fa79628f9a8fea0f8d0e450ad330 Fixed in 1.6+

https://github.com/anomalylabs/users-module/commit/d183bb459fc00e133b1535a16b49bf67086799d3

https://github.com/anomalylabs/navigation-module/commit/5855f854bf9b92fc311b83e9fcc99ffc7dd9d113
