### ISSUE TITLE
Pyro 3.7 can't load old versions of page

### ISSUE THREAD

**Issue by fatihalp** [pyrocms/pyrocms#4974]
**Describe the bug**

http://pyro.test/admin/pages/edit/1?version=4&versionable=Anomaly\PagesModule\Page\PageModel

**To Reproduce**
1- Create fresh pyro 3.7
2- Go to pages 
3- Update a page.
4- Go to versions of page.
5- Click load page see:  get_class() expects parameter 1 to be object, null given

**Expected behavior**
Load old version of page.

**Screenshots**

![image](https://user-images.githubusercontent.com/219454/57832504-7e6cda80-77c0-11e9-888d-e33ab7556ffb.png)

**Comment by RyanThompson** [comment]
This has been resolved.
