### ISSUE TITLE
Heroku clean installation

### ISSUE THREAD

**Issue by Realsnowyman** [pyrocms/pyrocms#4976]
I'm trying to install PyroCMS 3.7 on Heroku:
First i'm forked clean install of PyroCMS to my repositorie on git, changed some files for attaching the database (such as a composer.json and database.php), then i attached ClearDB addon with empty database on it. I executed php artisan install on heroku console with positive result, and i see that database fill up with data after that. But for now i got same errors from app

> In Connection.php line 664:

> SQLSTATE[42S02]: Base table or view not found: 1146 Table
> 'heroku_7e721028496403d.streams_streams' doesn't exist (SQL: select * from `streams_streams`)                                                                            

> In PDOConnection.php line 63:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'heroku_7e721028496403d.streams_streams' doesn't exist                                        

> In PDOConnection.php line 61:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'heroku_7e721028496403d.streams_streams' doesn't exist            

> heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=pyrocmstest.herokuapp.com request_id=51ea4d26-e070-4114-a161-265ac128dba7 fwd="95.141.237.28" dyno= connect= service= status=503 bytes= protocol=https

> heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=pyrocmstest.herokuapp.com request_id=bdd19752-91af-421c-9974-7d5466e51e97 fwd="95.141.237.28" dyno= connect= service= status=503 bytes= protocol=https                            

This is my database connection params:
`'mysql' => [

            'driver' => 'mysql',

            'host' => env('DB_HOST', $host),

            'port' => env('DB_PORT', '3306'),

            'database' => env('DB_DATABASE', $database),

            'username' => env('DB_USERNAME', $username),

            'password' => env('DB_PASSWORD', $password),

            'unix_socket' => env('DB_SOCKET', ''),

            'charset' => 'utf8',

            'collation' => 'utf8_unicode_ci',

            'prefix' => '',

            'strict' => false,

            'engine' => null,

            'modes' => [

            'STRICT_TRANS_TABLES',

            'NO_ZERO_IN_DATE',

            'NO_ZERO_DATE',

            'ERROR_FOR_DIVISION_BY_ZERO',

            'NO_AUTO_CREATE_USER',

            'NO_ENGINE_SUBSTITUTION'],
        ],
`
What i'm doing wrong?

**Comment by RyanThompson** [comment]
What is your `.env` contents at this time? If you're able to share or desensitize it and share.

**Comment by Realsnowyman** [comment]
> What is your `.env` contents at this time? If you're able to share or desensitize it and share.

Well as i understeand you don't need .env file for heroku. Config variables is for that. So in my config variables i have APP_KEY, APP_URL and CLEARDB_DATABASE_URL. 
In database.php i get database connection params from CLEARDB_DATABASE_URL:
>$url = parse_url(getenv("CLEARDB_DATABASE_URL"));
>$host = $url["host"];
>$username = $url["user"];
>$password = $url["pass"];
>$database = substr($url["path"], 1);

Also i tried to place DB params to database.php directly.

**Comment by Realsnowyman** [comment]
@RyanThompson i've added .env file with this params

>APP_ENV=production
>APP_DEBUG=false
>APP_KEY=*key*
>DB_CONNECTION=mysql
>DB_HOST=eu-cdbr-west-02.cleardb.net
>DB_DATABASE=heroku_616f80dbbf058a7
>DB_USERNAME=b863864bd5a908
>DB_PASSWORD=*dbpassword*
>APPLICATION_NAME=pyrocmstest
>APPLICATION_REFERENCE=default
>APPLICATION_DOMAIN=mypyro.herokuapp.com
>ADMIN_EMAIL=admin@pyrotest.com
>ADMIN_USERNAME=admin
>ADMIN_PASSWORD=*mypasword*
>LAZY_TRANSLATIONS=true
>DB_CACHE=true
>LOCALE=en
>TIMEZONE=UTC

Then i make artisan install without any errors.
If i try open the app, i see this errors in logs:

`PHP Fatal error:  Class 'Anomaly\Streams\Platform\Model\Users\UsersRolesEntryModel' not found in /app/core/anomaly/users-module/src/Role/RoleModel.php on line 14`

`10.91.195.42 - - [28/May/2019:13:23:07 +0000] "GET /favicon.ico HTTP/1.1" 500 12684 "https://mypyro.herokuapp.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36`

**Comment by edster** [comment]
Run `php artisan streams compile`, if you run into the same issue make a new line in .env of  `installed=false` then run it again.

**Comment by Realsnowyman** [comment]
> Run `php artisan streams compile`, if you run into the same issue make a new line in .env of `installed=false` then run it again.

Done without errors. But i still get same errors.
![image](https://user-images.githubusercontent.com/49273831/58537427-8a628e80-81fb-11e9-84a6-da23e7a472cd.png)

**Comment by edster** [comment]
Go into the storage folder and look for the models for your app reference. Make sure they are actually generated
