### ISSUE TITLE
Intermittent login issue where CSRF token mismatch error is thrown

### ISSUE THREAD

**Issue by drmonkeyninja** [pyrocms/pyrocms#4977]
**Describe the bug**
Admin is occasionally logging out users or preventing users from logging in and throwing the `csrf_token_mismatch` error.

**To Reproduce**
This is difficult to recreate as it happens intermittently, but when it does it tends to consistently fail to let the user login for a while. It tends to happen on first login (it fails to login and returns the message 'Your security token has expired. Please submit the form again.').

**Expected behavior**
User successfully logs in and the session is maintained.

**Additional context**
We're using database sessions as the site is load balanced.

We're using PyroCMS v3.5 on PHP 7.2 using MySQL.

**Comment by drmonkeyninja** [comment]
This is continuing to be an issue for us (the client is reporting that this is happening a lot to them making the CMS unusable).

It reoccurred for me earlier today and I found that once the `csrf_token_mismatch` error was triggered it consistently kept me logged out for about an hour. I was able to login from a fresh browser during this time, but after a couple of minutes that too logged out with the expired security token error.

It looks like it is the `tokensMatch` method in the `VerifyCsrfToken` class that is failing.

Any chance this has been looked into yet?

**Comment by vargvinter** [comment]
Same here. We have got same symptoms like @drmonkeyninja.
I have noticed that `Shift + F5` combination also logouts the user on the very next request.

**Comment by RyanThompson** [comment]
Are you guys still getting this with the double session issue fixed and some other updates that have happened? Can you confirm this is still a thing or is it resolved?

**Comment by drmonkeyninja** [comment]
Sorry @RyanThompson I forgot to comment on this one. I believe this PR resolved it: https://github.com/anomalylabs/streams-platform/pull/640. When I originally opened that PR I had no idea that it would be related, it was just an attempt to tidy the code. 🤷‍♂️

We're no longer getting the issue. 😀
