### ISSUE TITLE
[streams-platform] Schedule config name

### ISSUE THREAD

**Issue by Eighke** [pyrocms/pyrocms#4979]
**Describe the bug**
https://github.com/pyrocms/pyrocms/blob/8d30fabbb28adbe36b812f679137ae98279ca6cb/config/streams.php#L69

Use `schedules` but

https://github.com/anomalylabs/streams-platform/blob/00f41ab2b1ed193a44cc2a32173a790658af7e6c/src/StreamsServiceProvider.php#L235

Use `schedule`

I'm not sure which one you wanna keeps, so I just report it. :)

**Comment by RyanThompson** [comment]
Plural `schedules` is correct. Thanks! I've fixed and patched.
