### ISSUE TITLE
Ambiguous sort_order column when joining two sortable models

### ISSUE THREAD

**Issue by drmonkeyninja** [pyrocms/pyrocms#4981]
**Describe the bug**
When joining a sortable table onto another sortable model the generated SQL contains an ambiguous order clause due to the `sort_order` columns on both tables.

> SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'sort_order' in order clause is ambiguous

**To Reproduce**
Use the `join` method on a sortable Eloquent model to join another sortable table.

**Expected behavior**
I would expect a valid SQL query to be generated with the columns in the order clause aliased to the relevant table.

**Comment by RyanThompson** [comment]
CURRENTLY this is up to you - however I have field type query criteria.. I might be able to squeak in but it'll automate more of the join logic needed. Checkout the `translate` method I just added in the meanwhile to get an idea of what's needed.. I might sneak in a join version of this but I am unsure: https://github.com/anomalylabs/streams-platform/blob/1.7/src/Model/EloquentQueryBuilder.php#L351

**Comment by RyanThompson** [comment]
Added this after all: https://github.com/anomalylabs/streams-platform/commit/4ea724449885031e5a0531a1075dfc144dbd9449
