### ISSUE TITLE
Installer - Add an option to set the DB port

### ISSUE THREAD

**Issue by rickmills** [pyrocms/pyrocms#4983]
Just been setting a fresh copy of 3.7.x-dev and I've got a bit of an odd home setup where I use a synology running MySQL on a non-standard port. However both the web and CLI installers look to be missing the option to set your own port.

Workaround for now is to just fill out the `.env` file manually but would be nice if at some point this was added into the gui/cli.

Probably wouldn't hurt to also add in support for `DB_PREFIX` at the same time.

**Comment by RyanThompson** [comment]
DB prefix is dictated by application reference - but added the port in! 

https://github.com/anomalylabs/installer-module/commit/57daec328454a22661573d5a80b2581c98f15f95

https://github.com/anomalylabs/installer-module/commit/272774bf97c4de14fbd5e17115b4a8f829e5c5b8
