### ISSUE TITLE
Improve documentation on best practice for publishing streams

### ISSUE THREAD

**Issue by drmonkeyninja** [pyrocms/pyrocms#4984]
The existing documentation isn't clear on how best to handle the view and config files generated when publishing the streams platform or one of the addons.

On the [cheatsheet for Upgrading](https://pyrocms.com/help/developer-tools/cheatsheets/upgrading) it states that:

> When you run addon:publish to override the addon it's always a good idea to remove / delete EVERYTHING you do not need to override. This will help prevent subtle breaking changes to configs or views that should not, but may occur.

This is a really important point, but this should be clearly stated at any point in the documentation that explains how to publish either streams or addons. This currently appears to be missing from the [streams documentation](https://pyrocms.com/help/developer-tools/extending-pyrocms/overriding-configuration) and only alluded to on the [addons documentation](https://pyrocms.com/help/developer-tools/extending-pyrocms/overriding-views). The upgrade guide is unlikely to be seen until this is a little too late in the process.

We were recently tripped up by this when upgrading to a newer version of PyroCMS as we were not aware that another developer had published the streams platform and this resulted in a config file in the wrong format that broke the system settings UI. It turned out that the file in question hadn't been modified from the original, so really should have been deleted after the streams platform had been published.

It would also be hugely beneficial if the upgrade guides clearly indicated which config files will have changed structure between versions so that issues like this can be quickly resolved.

**Comment by RyanThompson** [comment]
Done: https://github.com/anomalylabs/streams-platform/commit/84ea5bc70aa29f718ebade6b1fab21ac83d533a7
