### ISSUE TITLE
[Field Type] Code - issue with second locale

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4986]
**Describe the bug**
Field type is messed up.

![codeerror](https://user-images.githubusercontent.com/31292231/59627940-b6f53080-913f-11e9-98b7-866a30ce4bf8.gif)

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/markdown-field_type/commit/01e9dce28dd70dc7e02647a04040600ff004b36f
