### ISSUE TITLE
[Field Type] Markdown - Error init second locale

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4987]
**Describe the bug**
On page load, the primary language is visible in the markdown field. When selecting the secondary language the text/markdownarea is empty until you click inside it.

![markdownerror](https://user-images.githubusercontent.com/31292231/59628378-d3459d00-9140-11e9-9840-22adcc6c5558.gif)

**Comment by RyanThompson** [comment]
Fixed bruh: https://github.com/anomalylabs/markdown-field_type/commit/01e9dce28dd70dc7e02647a04040600ff004b36f
