### ISSUE TITLE
Logout notification persists after re-login

### ISSUE THREAD

**Issue by TheBeems** [pyrocms/pyrocms#4988]
**Describe the bug**
The website I am making is behind a login. When trying to reach a page while logged out, it will redirect to the login page and produce a message you need to be logged in  (as intended). But after re-login, the notification will not get removed. 
The same happens when you are logged in on the website and then logout. You will get a notification that you are logged out (as intended). But if you login again, that notification will remain.
Also when you click the notification away with the closing button, after page refresh or going to another page, will get the notification messages back.

**To Reproduce**
Logout from the website. The notification that you are logged out appears. Then without removing the notification, re-login and the notification remains while logged in.

**Expected behavior**
The notification message stays away after removing it or if not applicable.

**Additional context**
I am using PyroCMS v3.7 on PHP 7.2 using MariaDB.

**Comment by TheBeems** [comment]
Anyone have an idea where the problem resides? It happens with all the session messages. They persist for a couple of minutes while browsing the site, even when going to the admin dashboard page. But clicking on any page within the admin area, the message gets removed.

**Comment by RyanThompson** [comment]
Check that your `messages.php` file uses the correct session method: https://github.com/anomalylabs/streams-platform/blob/1.7/resources/stubs/addons/resources/views/partials/messages.twig#L10

Old bug that was deprecated out without updating the view respectively :-/

**Comment by edster** [comment]
I am also having session persists periodically on 3.7
________________________________
