### ISSUE TITLE
[Forms Module] Not sending emails from different locales

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4989]
**Describe the bug**
Forms module is implemented. Notification is created and added. When i go to williamastrom.se and submit the form, an email notification is sent to me.

When i go to the swedish version: williamastrom.se/sv and submit the form, nothing is sent.

Form is stored however.

**Comment by Pixney-William** [comment]
@RyanThompson have you looked at it or should i dig it down?

**Comment by Pixney-William** [comment]
The issue is found here : 
https://github.com/anomalylabs/forms-module/blob/1.3/src/Form/FormMailer.php#L87

If you have a website with multiple locales, but only have entered the send to email in english, the other locales returns an empty array here.

I suggest you make it so it defaults to the standard locale (ie English setting that exist) and then only use other value if it is set.

@RyanThompson

**Comment by Pixney-William** [comment]
![image](https://user-images.githubusercontent.com/31292231/62969337-561b6900-be0d-11e9-91b9-5a24226f3b4b.png)

This field isn't required. Does it use another value if it's not filled in? If so, then maybe that value should be used if another locale email is not filled in instead of using the one that is filled for the standard locale? 

Not sure what the best way is here?

**Comment by RyanThompson** [comment]
Interesting. So it needs a default to the default locale's value.

**Comment by Pixney-William** [comment]
Question is, if it's not a required field. And you don't fill it out in any language. What does it default to? @RyanThompson
