### ISSUE TITLE
[3.7][Pages-Module] - Home Page not updating properly.

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#4990]
**Describe the bug**
If you change the home page between different pages, it does not update.

**To Reproduce**
1. Go to Page module
2. Update the home page to a different page
3. The site home page will not update, however the DB record will indicate that the home page has changed.

**Expected behavior**
The home page will update on the site to showcase the new page.

**Additional context**
"name": "anomaly/pages-module",
            "version": "v2.6.21",

**Comment by RyanThompson** [comment]
I can confirm this works too.. which is kinda a duplicate to your other. Can you tell me if you have route cache, http cache, and or DB caching toggled on?

**Comment by edster** [comment]
It's all stock, itlf it is on by default then it's on
________________________________
