### ISSUE TITLE
[3.7][Pages-Module] - Updating a page types layout does not work

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#4991]
**Describe the bug**
If you change the layout of a page type to a new layout, the published page does not refresh.

**To Reproduce**
1. Go to Page module
2. Update page type to a different theme layout
3. Navigating back to a page that uses this layout will not update, however the DB record will indicate that the layout has changed.

**Expected behavior**
The page layout will reflect the newly selected page layout.

**Additional context**
"name": "anomaly/pages-module",
            "version": "v2.6.21",

**Comment by RyanThompson** [comment]
This seems odd.. I have been doing this all week on a bleeding edge install and others - no issues. Just tried with a local tests on two installs and it appears fine. HTTP cache also appears to bust appropriately. Can you gather me more deets to reproduce and poke me if this is still a thing?
