### ISSUE TITLE
[3.7][Addons Module] - Does not show modules in the addons directly

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#4992]
**Describe the bug**
The addons module is not showing any modules sitting in the addons directory.

**To Reproduce**
1. Place a module in the addons directory
2. Look for the addon in any of the navigational items.
4. It will not be listed to be installed/uninstalled.

**Expected behavior**
Addons in the addons directory should be listed.

**Additional context**
"name": "anomaly/streams-platform",
            "version": "v1.6.155",
"name": "anomaly/addons-module",
            "version": "v2.3.39",

**Comment by RyanThompson** [comment]
Fixed this as well.
