### ISSUE TITLE
[3.7][Addons-Module] - Cannot install an addon via GUI

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#4993]
**Describe the bug**
When you try to install a module via the gui you get the following error.
`The provided cwd "anomaly.module.dashboard --seed" does not exist.`

You get this regardless if you have checked off seed or not.
**To Reproduce**
1. Go to addon module
2. Click on the install button for a module
3. Select Seed

**Expected behavior**
Module installs and seeds.

**Additional context**
"name": "anomaly/streams-platform",
"version": "v1.6.155",
"name": "anomaly/addons-module",
"version": "v2.3.39",

**Comment by RyanThompson** [comment]
This has been resolved.
