### ISSUE TITLE
[3.x][accelerant-theme] Page breaks on failed login attempt

### ISSUE THREAD

**Issue by rickmills** [pyrocms/pyrocms#4997]
**Describe the bug**
When attempting to log in to any pyrocms admin area running accelerant, if you enter an incorrect username/password and press submit, the page 'slides' the background open, filling the screen which then scrolls horizontally.

**To Reproduce**
1. Go to any pyro admin area (e.g http://pyrocms.com/admin)
2. Enter junk in the email and password field, press submit
4. See error - page splits

**Expected behavior**
The page shouldn't split apart, instead you should get a validation error.

**Screenshots**
https://imgur.com/a/UX3PBI8

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome & Firefox
 - Version: Latest

**Comment by RyanThompson** [comment]
Fixed - thanks! https://github.com/pyrocms/accelerant-theme/releases/tag/v1.2.13
