### ISSUE TITLE
[3.7] New language adding causing error in Pyro 3.7

### ISSUE THREAD

**Issue by fatihalp** [pyrocms/pyrocms#4999]
**Describe the bug**
If there isn't language's data in database (let's says title in posts module) it gives error when you change language. 

**To Reproduce**
1. Install new Pyrocms 3.7 
2. Add new post. 
3. Activate new language (like Turkish) other than English. 
4. Change language to Turkish and open the post. You will see error. 

**Screenshots**

Pyro 3.6 is working when there isn't that language related (_translation) record.

Current Lang= TR-Turkish
![image](https://user-images.githubusercontent.com/219454/61281068-a88f4880-a7c1-11e9-87b5-f326ebd0846d.png)

![image](https://user-images.githubusercontent.com/219454/61281075-ae852980-a7c1-11e9-9e8b-4538e808ddc3.png)

**Same code, same database pyro 3.7 is not working**

Current Lang= TR-Turkish
![image](https://user-images.githubusercontent.com/219454/61281103-c066cc80-a7c1-11e9-8f83-f75cf77066ee.png)

![image](https://user-images.githubusercontent.com/219454/61281110-c5c41700-a7c1-11e9-8e4a-bc2a39edb257.png)

**Desktop & Smartphone:**
All

**Comment by RyanThompson** [comment]
I believe this commit should fix this: https://github.com/anomalylabs/streams-platform/commit/44398d79e5c912c010fd68187ba2c174c26f4ee9

**Comment by fatihalp** [comment]
It still consist in 3.7 Beta 2 @RyanThompson 

https://www.youtube.com/watch?v=nfJockEWEsg
