### ISSUE TITLE
[3.6] Duplicate folder path causes Error 500 during installation

### ISSUE THREAD

**Issue by quangdo** [pyrocms/pyrocms#5000]
**Describe the bug**
**Log:** [laravel-2019-07-26.log](https://github.com/pyrocms/pyrocms/files/3437550/laravel-2019-07-26.log)

When attempting to install PyroCMS locally using MAMP (free version), I get a Error 500 message when I visit the installer page (.../installer). The log that PyroCMS generates says it "failed to open stream: No such file or directory".

The file that it's attempting to open is located at the following path which is wrong: 
/Applications/MAMP/htdocs/pyrocms/public/pyrocms/public/app/default/assets/admin/theme.css
This

PyroCMS, for some reason, is printing the path "**_pyrocms/public_**" twice during install phase.

Performing the install via **_"php artisan install_**" yields same error.

**Exact line I'm referring to:**
> [2019-07-26 22:15:51] production.ERROR: An exception has been thrown during the rendering of a template ("file_get_contents(/Applications/MAMP/htdocs/pyrocms/public/pyrocms/public/app/default/assets/admin/theme.css): failed to open stream: No such file or directory").

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Browser: Chrome
 - Version: 75.0.3770.142 (Official Build) (64-bit)

Thank you for looking! Can't wait to get it up and running!

**Comment by RyanThompson** [comment]
Can you confirm, is the public root of your MAMP host the `public` folder of your PyroCMS installation? That is a must to continue: https://pyrocms.com/documentation/pyrocms/3.7/getting-started/installation#host-configuration

**Comment by quangdo** [comment]
D'oh! Yes I skipped over that bit. Thanks for looking.
