### ISSUE TITLE
PyroCMS installer broken

### ISSUE THREAD

**Issue by monicaelenastefan** [pyrocms/pyrocms#5001]
I am trying to install PyroCMS on CentOS and the installer seems broken. It stops at 33/57 with no error log. The users table in the database is empty and the public folder does not contain the default pages ( welcome or control panel). 
I have followed the steps from https://pyrocms.com/documentation/pyrocms/3.5/installation/installing-pyrocms 
![image](https://user-images.githubusercontent.com/22777096/62530006-6dc08380-b848-11e9-874f-36705b478e80.png)
My php version is 7.1.30. I had this problem for some days now and I can not understand what I am doing wrong. Please help.

**Comment by RyanThompson** [comment]
Can you try again? I've made some changes to the installation processes recently.

Does it give you an error on the console at all? Does it just stop to never continue? No feedback whatsoever? Any more information would help tremendously.

**Comment by RyanThompson** [comment]
I think I was hitting a few things too but those have all been resolved on 3.7.

You might try `ulimit -n 1024` before installation if you're on a mac.
