### ISSUE TITLE
Authy Authenticator

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#5005]
**What are you trying to do?**
Add two factor authentication for admins logging into the admin as well as for users logging in for protected pages.

**Comment by edster** [comment]
What is the issue @Pixney-William?

There are docs for the module here: https://github.com/anomalylabs/authy_authenticator-extension/tree/1.0/docs/en

Or are you asking that they get pushed to the website? It is there under Extensions

**Comment by RyanThompson** [comment]
It's listed here: https://pyrocms.com/documentation

And here: https://pyrocms.com/documentation?q=authy

And here: https://pyrocms.com/documentation/authy-authenticator-extension

:-P

**Comment by Pixney-William** [comment]
It wasn't available this morning. Or there was cache or something. @edster

**Comment by Pixney-William** [comment]
Homepage that is... Where i normally look for docs.
