### ISSUE TITLE
Error making migrations (php artisan make:migrate)

### ISSUE THREAD

**Issue by stickeegreg** [pyrocms/pyrocms#5007]
**Describe the bug**
Error `The "fullpath" option does not exist.`

**To Reproduce**
1. Run `php artisan make:migration test` on a fresh install (`composer create-project pyrocms/pyrocms:3.7.x-dev`)

Pyrocms 3.7.x-dev 7be2ef3dc44c8a70840ceb599fb67a796abacbc7
Laravel 5.8.32

**Fix**
Change `Anomaly\Streams\Platform\Database\Migration\Console\MigrateMakeCommand` to:

```
    protected $signature = 'make:migration {name : The name of the migration.}
        {--table= : The table to migrate.}
        {--create= : The table to be created.}
        {--fields : Create a fields migration.}
        {--addon= : The addon to create a migration for.}
        {--stream= : The stream to create a migration for.}
        {--path= : The location where the migration file should be created.}
        {--realpath : Indicate any provided migration file paths are pre-resolved absolute paths.}
        {--fullpath : Output the full path of the migration.}';
```

**Comment by StarfallProjects** [comment]
I also got this error on Laravel 6.0.4
Fresh project created with `laravel new`
Using the renthinkDB plugin (added with composer require "duxet/laravel-rethinkdb:dev-master")
