### ISSUE TITLE
Error when trying to install 3.7 beta2 from CLI

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#5011]
**Describe the bug**
`Target [Anomaly\AddonsModule\Repository\Contract\RepositoryRepositoryInterface] is not instantiable.`

**To Reproduce**
1. `composer create-project pyrocms/pyrocms:3.7.x-dev `
2. `php artisan install`
3. During install it throws above error 

![image](https://user-images.githubusercontent.com/31292231/63623030-be7dfd80-c5f8-11e9-8923-0c9c80cdcc10.png)

**Comment by Pixney-William** [comment]
If i run composer update and then php artisan install - it works. 

We should find this issue since i am not the only one having it.

**Comment by mmodler** [comment]
+1

It now happens with stable v3.7 (platform 1.7) - weird!

**Comment by ghost** [comment]
@mmodler have you found any workaround for this issue? i have same problem now...

**Comment by mmodler** [comment]
I use platform 1.6 - no other solution found.

**Comment by mmodler** [comment]
Sould be fixed, will test soon. 

https://github.com/anomalylabs/streams-platform/commit/2caef91037e621bdd1af47d9b1e8a24aede67edf
