### ISSUE TITLE
Duplicating post records in 2 language with Pyro 3.7 Beta 2

### ISSUE THREAD

**Issue by fatihalp** [pyrocms/pyrocms#5012]
Describe the bug
After upgrading to pyrocms 3.7 translatable fields duplicates data if 2 languages activated.

To Reproduce
1- Create new module and steream.
2- Activate 2 language.
3- Change language to Turkish
4- Try to get data like:

```
        $data = new PostModel();
        dd($data->get()->toArray());
```
5- You will see data is duplicated.

https://www.youtube.com/watch?v=nfJockEWEsg

#4965 bug continue.

**Comment by RyanThompson** [comment]
Is Turkish one of the 2 languages activated? And what is the DEFAULT language for the system then? And also what are the 2 locales you have enabled?

**Comment by fatihalp** [comment]
Default is English. Turkish and English is activated. 

I believe all answers in 1 min. video : https://www.youtube.com/watch?v=nfJockEWEsg

**Comment by RyanThompson** [comment]
Thanks!

**Comment by Eighke** [comment]
@RyanThompson It is currently a critical issue for non English people, if the `app.locale` is in a different language than the fallback, everything is duplicated.

I had to lock my SP before the B/C break change on some project :(

------------------

![Screenshot](https://user-images.githubusercontent.com/2734125/65309002-6fa29400-dbb5-11e9-90d0-302affe4125b.png)

Basically

```
        $this->query->groupBy([$model->getTableName() . '.id', $model->getTranslationsTableName() . '.id']);
```

Cannot work with 

```
                $query->orWhere(
                    $model->getTranslationsTableName() . '.locale',
                    config('app.fallback_locale')
                );
```

**Comment by RyanThompson** [comment]
Welp.. I don't see any other way but then to do this and I THINK that is just fine.. Covering any erroneous entries as well that could exist: https://github.com/anomalylabs/streams-platform/commit/72ec4f13ae8bd84e27b827cbedbf7e4404147885#diff-4e632746ca6f1b960073c327959452b7L364-L374
