### ISSUE TITLE
Website redirecting issues

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#5013]
If i am here : 
https://pyrocms.com/documentation/pyrocms/3.7/prologue/upgrade-guide

I change the select box to 3.6 , i then arrive here : 
https://pyrocms.com/documentation/pyrocms/3.6/prologue/upgrade-guide

If i then change back to 3.7, i come to:
https://pyrocms.com/documentation/pyrocms/3.7/getting-started/installation

I should come back to : 
https://pyrocms.com/documentation/pyrocms/3.7/prologue/upgrade-guide

**Comment by RyanThompson** [comment]
Good catch! Agreed.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/documentation-module/commit/1d645e3aabbad2c704a883fd0d5cc7add877d001 (also duplicate: https://github.com/pyrocms/pyrocms/issues/5017)
