### ISSUE TITLE
Documentation how to create a form and store it using formbuilders

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#5016]
So i was working on an ajax contact form for a module i have. And i have been googling to try to solve it but i ended up just working with native Laravel functionality instead. I think we would need documentation regarding this if it doesn't exist:

1) Create an addon/module with migration (basic fields for a contact form, name, email)
2) How to use a formbuilder to render the form in html including an extra tmp field "honeypot" which is a text field that you later can check in 3 and also skip after that since it doesn't need to be stored.
3) How to manipulate the submitted data before being stored.
4) How to store it.

I have always used form() for creating these contact forms but it only uses the fields you have migrated.

**Comment by fryiee** [comment]
@Pixney-William digging this up - is this what you're talking about?

- https://pyrocms.com/documentation/streams-platform/1.7/ui/forms
- https://pyrocms.com/help/developer-tools/form-builders/defining-custom-ajax-forms-in-twig
