### ISSUE TITLE
Homepage documentation redirect error

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#5017]
This is similar to the other error. If you visit: https://pyrocms.com/documentation/streams-platform/1.5/the-basics/httpcache and then chang from 1.5 to 1.7 you are not staying on the httpcache page any longer.

**Comment by RyanThompson** [comment]
This has been vastly improved. It'll try harder to preserve position now. Exact if possible.

https://github.com/anomalylabs/documentation-module/commit/1d645e3aabbad2c704a883fd0d5cc7add877d001
