### ISSUE TITLE
Custom Status

### ISSUE THREAD

**Issue by nazminnasya** [pyrocms/pyrocms#5025]
I am creating a custom filter status in my posts-module. So I need to bind PostTableBuilder with the one in the core and modify the filter status. 

I create a new file in my App/Bindings folder named PostTableBuilder and I try to bind it in config/streams.php with

`'Anomaly\PostsModule\Post\Table\PostTableBuilder' => 'App\Bindings\PostTableBuilder',`

Then when I try to reload the table in the control panel, 

it says Type error: Argument 1 passed to Anomaly\PostsModule\Http\Controller\Admin\PostsController::index() must be an instance of Anomaly\PostsModule\Post\Table\PostTableBuilder, instance of App\Bindings\PostTableBuilder given.

Then when I tried to replace the file PostTableBuilder in my PostsController with the new one that I binded (in App/Bindings), then it says Call to a member function getField() on null on the file {app-name}/vendor/anomaly/streams-platform/src/Ui/Table/Component/Filter/Type/FieldFilter.php

![Post](https://user-images.githubusercontent.com/36849456/65105673-4264b300-da08-11e9-9957-fb4fc16347b3.png)

Can someone point out to me what I am doing wrong? I had created my custom StatusFilterQuery and also binded it and it worked. But when I tried to bind PostTableBuilder to my App/Bindings folder, somehow it doesn't work...I am still learning Pyrocms, so any help/guide would be appreciated.

**Comment by edster** [comment]
You need to set the stream on your table builder since it is outside the auto detection area
________________________________

**Comment by nazminnasya** [comment]
> You need to set the stream on your table builder since it is outside the auto detection area
> […](#)
> ________________________________ From: NazminNasya <notifications@github.com> Sent: Tuesday, September 17, 2019 8:38:39 PM To: pyrocms/pyrocms <pyrocms@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [pyrocms/pyrocms] Custom Status (#5025) I am creating a custom filter status in my posts-module. So I need to bind PostTableBuilder with the one in the core and modify the filter status. I create a new file in my App/Bindings folder named PostTableBuilder and I try to bind it in config/streams.php with 'Anomaly\PostsModule\Post\Table\PostTableBuilder' => 'App\Bindings\PostTableBuilder', Then when I try to reload the table in the control panel, it says Type error: Argument 1 passed to Anomaly\PostsModule\Http\Controller\Admin\PostsController::index() must be an instance of Anomaly\PostsModule\Post\Table\PostTableBuilder, instance of App\Bindings\PostTableBuilder given. Then when I tried to replace the file PostTableBuilder in my PostsController with the new one that I binded (in App/Bindings), then it says Call to a member function getField() on null on the file {app-name}/vendor/anomaly/streams-platform/src/Ui/Table/Component/Filter/Type/FieldFilter.php [Post]<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F36849456%2F65105673-4264b300-da08-11e9-9957-fb4fc16347b3.png&data=02%7C01%7C%7Cbef9d6c007cd4dc2bc1008d73be9b256%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637043747214898794&sdata=i%2Fu3agbMinGxgdc4xmqGu50tVV4EpSIYeXP%2FQj1ueQM%3D&reserved=0> Can someone point out to me what I am doing wrong? I had created my custom StatusFilterQuery and also binded it and it worked. But when I tried to bind PostTableBuilder to my App/Bindings folder, somehow it doesn't work...I am still learning Pyrocms, so any help/guide would be appreciated. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpyrocms%2Fpyrocms%2Fissues%2F5025%3Femail_source%3Dnotifications%26email_token%3DAAFAHOJ6INS2DCTPUM5E4PLQKGPD7A5CNFSM4IXYVJZ2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HMAUA5A&data=02%7C01%7C%7Cbef9d6c007cd4dc2bc1008d73be9b256%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637043747214898794&sdata=7KbdRccV37Nj9GvNZFuZ5AosgUq6CogVQOdcz1aTRv0%3D&reserved=0>, or mute the thread<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAFAHOMKFUNIYY4SSWZZ6LLQKGPD7ANCNFSM4IXYVJZQ&data=02%7C01%7C%7Cbef9d6c007cd4dc2bc1008d73be9b256%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637043747214908803&sdata=xkH1D6owT4wdD5CHTFpUdyMdjiQ%2BKBza%2FjHuzzYSDjY%3D&reserved=0>.

okay...how do I do that? Is there any guide somewhere that I could read? I'm sorry I'm still learning Pyrocms, so bear with me...

**Comment by nazminnasya** [comment]
How do I extend it?

Here is my PostTableBuilder in App\Bindings for your reference
```

<?php namespace App\Bindings;

//use Anomaly\PostsModule\Post\Table\Filter\StatusFilterQuery;
use Anomaly\Streams\Platform\Ui\Table\TableBuilder;
use Anomaly\PostsModule\Post\Table;
use App\Bindings\StatusFilterQuery;
/**
 * Class PostTableBuilder
 *
 * @link          http://pyrocms.com/
 * @author        PyroCMS, Inc. <support@pyrocms.com>
 * @author        Ryan Thompson <ryan@pyrocms.com>
 */
class PostTableBuilder extends TableBuilder
{

    /**
     * The table filters.
     *
     * @var array
     */
    protected $filters = [
        'search' => [
            'fields' => [
                'tags',
                'title',
                'summary',
                'meta_title',
                'meta_description',
            ],
        ],
        'author',
        'category',
        'status' => [
            'filter'  => 'select',
            'query'   => StatusFilterQuery::class,
            'options' => [
                'live'      => 'anomaly.module.posts::field.status.option.live',
                'draft'     => 'anomaly.module.posts::field.status.option.draft',
                'scheduled' => 'anomaly.module.posts::field.status.option.scheduled',
                'archived' => 'anomaly.module.posts::field.status.option.archived',
            ],
        ],
    ];

    /**
     * The table columns.
     *
     * @var array
     */
    protected $columns = [
        'title',
        'author',
        'category',
        'status' => [
            'heading' => 'anomaly.module.posts::message.status',
            'value'   => 'entry.status_label',
        ],
    ];

    /**
     * The tree buttons.
     *
     * @var array
     */
    protected $buttons = [
        'edit',
        'view' => [
            'target' => '_blank',
        ],
    ];

    /**
     * The table actions.
     *
     * @var array
     */
    protected $actions = [
        'delete',
    ];

    /**
     * The table options.
     *
     * @var array
     */
    protected $options = [
        'order_by' => [
            'publish_at' => 'DESC',
        ],
    ];
}
```
