### ISSUE TITLE
ProxySession Class withCookie 

### ISSUE THREAD

**Issue by babatundestickee** [pyrocms/pyrocms#5027]
**Bug**
I have integrated cors using the Barryvdh package, the CORS requests only works when withCookie is commented out, looks like with Cookie is no longer in Laravel as of 5.0 based on my little research

**Reproduce**
1. ```$ composer require barryvdh/laravel-cors```
2. add ``` 'middleware' => [
        \Barryvdh\Cors\HandleCors::class,
    ],``` in config/streams.php
3. add ``` Barryvdh\Cors\ServiceProvider::class ``` to providers array in app.php
4. See error: local.ERROR: Call to undefined method Symfony\Component\HttpFoundation\Response::withCookie()

**Comment by RyanThompson** [comment]
Got this taken care of - thank you! https://github.com/anomalylabs/streams-platform/commit/7e55cb85b4143b743260b86d99130c34914b3584
