### ISSUE TITLE
asset_inline('...', ['parse']) breaks with production build - "Unclosed comment"

### ISSUE THREAD

**Issue by stickeegreg** [pyrocms/pyrocms#5028]
**Describe the bug**

**To Reproduce**
1. Create a foo.css file with a media block that starts with an id, e.g.
```
@media(print) {
  #foo { color: red; }
}
```
2. Run `yarn run prod`
3. In your layout, add
```
asset_add('bar.css', 'theme::foo.css');
asset_inline('bar.css', ['parse']);
```
4. Load the page
5. See error "Unclosed comment"

This is caused by `yarn run prod` minifying the CSS.
The output CSS file looks like
`@media(print){#foo{color:red}}`
This contains `{#`, which is interpreted as a twig comment (the `}}` at the end would probably break things as well).

**Workaround**
Compile themes with `yarn run dev`

This might be difficult to fix as it would be difficult to tell minified CSS from a legitimate twig comment... if it proves too difficult to fix then improving the error message that tells the developer to run `dev` instead of `prod` would help at least.

**Comment by edster** [comment]
This sounds like an instigation issue between yarn and twig. How is this pyro related?
________________________________

**Comment by stickeegreg** [comment]
Pyro is passing yarn output and pretending it's a twig template. Yarn has no requirement to output something twig-compatible, so if Pyro wants to pretend that a CSS file is a twig template, it needs to fix up the CSS before it passes it to twig

**Comment by Pixney-William** [comment]
What if you use mix/webpack instead?

William Åström, Pixney AB

**Comment by fryiee** [comment]
@stickeegreg re-approving that this is a genuine bug and we are looking at it.
