### ISSUE TITLE
[forms-module] Export entries throws 'withCookie()' error

### ISSUE THREAD

**Issue by kiltedup** [pyrocms/pyrocms#5032]
**Describe the bug**
Using Forms Module in v3.7 ( module version 1.3 )
If you try to export entries in admin, following error is generated.

`Call to undefined method Symfony\Component\HttpFoundation\StreamedResponse::withCookie()`

Issue is in `vendor/anomaly/streams-platform/src/Http/Middleware/ProxySession.php`

**Additional context**
Issue not just impacting Forms Module - anywhere you try to use `response()->download()` will result in same error.

**Comment by kiltedup** [comment]
![image](https://user-images.githubusercontent.com/14813121/65878227-6cfa2880-e385-11e9-84ef-9ae6747339d0.png)

**Comment by RyanThompson** [comment]
I just fixed something else similar - on it. Thanks for the report!

**Comment by RyanThompson** [comment]
This should do it: https://github.com/anomalylabs/streams-platform/commit/7e55cb85b4143b743260b86d99130c34914b3584
