### ISSUE TITLE
Pyro 3.7 fresh composer install needs github token

### ISSUE THREAD

**Issue by fatihalp** [pyrocms/pyrocms#5034]
- Installing anomaly/geocoder-field_type (v1.2.5): Cloning 524de1d007
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+alp-lenovo+2019-10-03+1203
to retrieve a token. It will be stored in "C:/Users/alp/AppData/Roaming/Composer/auth.json" for future use by Composer.
Token (hidden):

![image](https://user-images.githubusercontent.com/219454/66126941-46d9c000-e5f3-11e9-8f5a-8008ec0e0022.png)

**Comment by Pixney-William** [comment]
Are you pro subscriber? If so, look in the pro documentation how to set
your token in composer.

William Åström, Pixney AB

**Comment by fatihalp** [comment]
Yes I'm but I don't need this field type and want to install only open source modules.

**Comment by edster** [comment]
Then simply remove it from the composer.json.
