### ISSUE TITLE
<input type="text"> character counter

### ISSUE THREAD

**Issue by ericleversen** [pyrocms/pyrocms#5037]
**Describe the bug**
The character counter is not working on <input type="text">
The initial "characters remaining" text is displayed but the counter is not nor does it inc/decrement.

** Fix ** 
`/core/anomaly/text-field_type/resources/js/input.js` does not initialize the counter.
commenting out  `let initialize = function () { }` and `load(initialize);` provides the correct behavior. See attached file [input.js.zip](https://github.com/pyrocms/pyrocms/files/3719834/input.js.zip)

Note that none of the other field type (eg: textarea)'s input.js files employ `let initialize = function 
() { }` and `load(initialize);` 

**To Reproduce**
View any form with a text field with `'show_counter' => TRUE` as an option.

**Expected behavior**
A dynamic counter with the number of characters in the test field should appear
![Screen Shot 2019-10-11 at 5 40 04 PM](https://user-images.githubusercontent.com/1933891/66688880-38705180-ec4e-11e9-9abb-8095abe05802.png)

**Screenshots**
See attached

**Comment by edster** [comment]
I would assume this is a race condition with the custom view your using. The stock views seem to work fine.
