### ISSUE TITLE
make:addon anomaly.module.videos

### ISSUE THREAD

**Issue by mostadev** [pyrocms/pyrocms#5041]
When Following your tutorials to how to build modules and scaffold it with streams the command
"artisan make:addon anomaly.module.videos"
doesn't create migration file for the module like the tutorial and then i searched for many things in your documentation isn't clear and too short to discuss any thing like other products.

**Comment by mmodler** [comment]
Your should use your own proejct/vendor name:
foo.module.video

Perhaps this helps:
https://github.com/pixney/pyrocms-cheatsheet#moduleextension

**Comment by edster** [comment]
That is an old video, migrations are created with the `make:stream` cmd after you have created a module
