### ISSUE TITLE
[blocks-module] Delete doesn't cascade and leaves trash data

### ISSUE THREAD

**Issue by mmodler** [pyrocms/pyrocms#5042]
**Describe the bug**

If i remove a block in admin, its data is deleted from the blocks table, but not from blocks transalations and not from block-extension tables.

If i remove a block programmatically via $blockModel->delete(),  its data is not deleted from block-extension tables.

**Expected behavior**
In both cases, all block data should be deleted from all tables.

**Additional context**
Over the time much garbage data will bloat the database.

**Comment by edster** [comment]
How is this block created? Is this an extension or a virtual block?

**Comment by mmodler** [comment]
Adding $cascades to parent BlockModel seems to do nothing... Looks like cascading is broken for blocks as transaltions are not delteted as well...

**Comment by mmodler** [comment]
@RyanThompson Do you have an eta for a fix so i can decide if it makes sence to write workaround code? Thanks!

**Comment by mmodler** [comment]
Hm, bombing @RyanThompson with slack messages might have more effect than opening issues here? :smiling_imp:

**Comment by Pixney-William** [comment]
Mmm unforunatelu

William Åström, Pixney AB

**Comment by mmodler** [comment]
@RyanThompson 

Any way to encourage you to take a look at this issue? Buying a :beer:, :coffee: or :doughnut: for you?

**Comment by Pixney-William** [comment]
yah, i would like this one sorted too

**Comment by mmodler** [comment]
News on this?

**Comment by mmodler** [comment]
One month later...

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/blocks-module/commit/0d6dde510683615cb417156fc504700679dc8a4c

**Comment by mmodler** [comment]
Thank you very very much!
