### ISSUE TITLE
Registering bindings/singletons doesn't work as expected

### ISSUE THREAD

**Issue by stickeegreg** [pyrocms/pyrocms#5044]
**Describe the bug**
Overriding a binding or singleton doesn't work as expected - the class specified in StreamsServiceProvider is always used

**To Reproduce**
1. In `config/streams.php` add the following binding
```
$bindings => [
    'Illuminate\Routing\UrlGenerator' => 'TESTING',
],
```
2. In your controller, `dd($this->app->getBindings()`

**Expected behavior**
The UrlGenerator binding should be set to 'TESTING' but is in fact set to 'Anomaly\Streams\Platform\Routing\UrlGenerator'

The code in [StreamsServiceProvider.php](https://github.com/anomalylabs/streams-platform/blob/1.7/src/StreamsServiceProvider.php#L359) merges `config('streams.bindings')` in to `$this->bindings`, which looks like it will allow you to override bindings, but in fact Laravel re-registers all the bindings using the property after the `register` method completes (see [Application.php](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Foundation/Application.php#L609)), thus overwriting changes from the config

**Suggested fix**
In StreamsServiceProvider.php replace
```
        // Register bindings.
        foreach (array_merge($this->bindings, config('streams.bindings', [])) as $abstract => $concrete) {
            $this->app->bind($abstract, $concrete);
        }

        // Register singletons.
        foreach (array_merge($this->singletons, config('streams.singletons', [])) as $abstract => $concrete) {
            $this->app->singleton($abstract, $concrete);
        }
```

with

```
        $this->bindings = array_merge($this->bindings, config('streams.bindings', []));
        $this->singletons = array_merge($this->singletons, config('streams.singletons', []));
```

If the bindings are required to be registered before the end of this function, then a combination of both would do it:
```
        // Register bindings.
        $this->bindings = array_merge($this->bindings, config('streams.bindings', []));

        foreach ($this->bindings as $abstract => $concrete) {
            $this->app->bind($abstract, $concrete);
        }

        // Register singletons.
        $this->singletons = array_merge($this->singletons, config('streams.singletons', []));

        foreach ($this->singletons as $abstract => $concrete) {
            $this->app->singleton($abstract, $concrete);
        }
```

**Workaround**
As a workaround, create a new ServiceProvider and register it in `config/app.php` *after* StreamsServiceProvider, and add your bindings/singletons there.

**Comment by RyanThompson** [comment]
Good call on the workaround. There is no documented timing that this could step on so I would assume bring it inline with laravel with your suggestion.

**Comment by RyanThompson** [comment]
Works perfectly - thank you!

https://github.com/anomalylabs/streams-platform/commit/4bc752b8f2853f34d24620c088f916e1e5216afa
