### ISSUE TITLE
Restoring Deleted (Post) Types Error

### ISSUE THREAD

**Issue by JoshuaBedford** [pyrocms/pyrocms#5045]
On a fresh install of Pyro CMS, I've created several post types then trashed them. When clicking 'restore' beside one of the trashed post types, an error occurs:

`Call to a member function getEntryStream() on null`

**To Reproduce**
1. Install fresh Pyro.
2. Create Post Type.
3. Trash Post Type.
4. Restore Post Type.

**Expected behavior**
I expected the Type in the trash to be undeleted and begin showing as a live / available type.

**Screenshots**
<img width="1504" alt="Screen Shot 2019-11-11 at 5 22 54 PM" src="https://user-images.githubusercontent.com/13459258/68629022-f08c5680-04a7-11ea-9fcc-ab9d5a25ac45.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS 10.14.6
 - Browser [e.g. chrome, safari] Chrome v78.0.3904.97

**Comment by RyanThompson** [comment]
Thank you! Good catch: https://github.com/anomalylabs/posts-module/commit/ae45ba1990ca3effd3df64c96ef2a2864be9abfd

`composer update` will bring in necessary updates.
