### ISSUE TITLE
Date field type doesn't work with repeaters and validation fails

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#5049]
**Describe the bug**
If you place a date field type within a repeater and set it to be text and not datepicker. It only instantiate on the first repeater, not the others. So it's a javascript thing there.

Then see images on how i set my dates. Please let me know if there are other ways to set the timezone than these and ill try. But basically if i use the datepicker, and have the values set according to the timezone and rules in the images it fails validation..

<img width="574" alt="Screenshot 2019-11-28 at 21 04 55" src="https://user-images.githubusercontent.com/31292231/69835253-66cae000-1240-11ea-9e88-5f31f9e32d39.png">
<img width="386" alt="Screenshot 2019-11-28 at 21 05 11" src="https://user-images.githubusercontent.com/31292231/69835254-66cae000-1240-11ea-8f99-1ee115adf51c.png">
<img width="400" alt="Screenshot 2019-11-28 at 21 05 59" src="https://user-images.githubusercontent.com/31292231/69835255-66cae000-1240-11ea-892e-0a97deac77b6.png">

**Comment by Pixney-William** [comment]
Ive also set it hard in the .env file : 
![image](https://user-images.githubusercontent.com/31292231/69835433-f4f39600-1241-11ea-9c21-22441cbfeac7.png)


Cant get this to work. Do you have the time to look at this?

**Comment by Pixney-William** [comment]
Doesn't matter if i choose date or date/time either.. 

![image](https://user-images.githubusercontent.com/31292231/69835620-43556480-1243-11ea-9fb1-014cf7b57ba7.png)

**Comment by Pixney-William** [comment]
Choosing only TIME works fine..

![image](https://user-images.githubusercontent.com/31292231/69835655-857ea600-1243-11ea-9490-f42f33183ceb.png)

**Comment by Pixney-William** [comment]
$this->configuration->get('streams::datetime.date_format'); =

![image](https://user-images.githubusercontent.com/31292231/69836268-e314f180-1247-11ea-9f6b-9836d0a430f7.png)

**Comment by Pixney-William** [comment]
It works perfectly fine if i create a date field , attach it to a page time and then saves it 👍 

![image](https://user-images.githubusercontent.com/31292231/69836379-a4cc0200-1248-11ea-94ee-77ae4ca3c548.png)

**Comment by Pixney-William** [comment]
So can this have anything to do with it being inside a repeater?

**Comment by Pixney-William** [comment]
Confirmed,, if i place a datetime field type in a repeater and attach it to a page it fails validation. But the other datetimefield above validates fine..

![image](https://user-images.githubusercontent.com/31292231/69836484-55d29c80-1249-11ea-904b-11e8a138c49f.png)

**Comment by RyanThompson** [comment]
This was fixed in core - prefixes were not passing into child forms properly
