### ISSUE TITLE
Pyro PRO subscribe error?

### ISSUE THREAD

**Issue by longmajs** [pyrocms/pyrocms#5050]
Two days ago, I purchased the pro service at pyrocms.com, Unlimited licensing. After payment, there is a page prompting me to submit a Github handle. How does pyrocms pro purchase succeed?

**Comment by RyanThompson** [comment]
I've contacted you via email @thimper - so sorry for the delay and inconvenience!

**Comment by RyanThompson** [comment]
Also you're now active. You can auth your server(s) and start using PRO addons now: https://pyrocms.com/documentation/pyrocms/3.7/getting-started/managing-addons

**Comment by longmajs** [comment]
Thank you for your reply. Best wishes
