### ISSUE TITLE
php artisan down --message='xxx'，message does not show.

### ISSUE THREAD

**Issue by longmajs** [pyrocms/pyrocms#5051]
**Describe the bug**
run:
`php artisan down --message="XXXX"`

No custom information is displayed; 

streams/views/error/error.twig:
![image](https://user-images.githubusercontent.com/3387095/70069093-2ac2c100-162c-11ea-8aaa-70ad847a1f3d.png)

message is lang/err.php content;

![image](https://user-images.githubusercontent.com/3387095/70069158-48902600-162c-11ea-8ca8-a68294299b4b.png)

![image](https://user-images.githubusercontent.com/3387095/70068967-ee8f6080-162b-11ea-85a5-5f00cc95f929.png)

**Comment by longmajs** [comment]
I know what you mean, you deliberately left out this definition and expressed it by defining 503 localization

**Comment by RyanThompson** [comment]
It should display more information though.. fixed: https://github.com/anomalylabs/streams-platform/commit/ca8955ec64151d662dcaf84c26363b3cac87a858
