### ISSUE TITLE
[users-module] Language Fallback for roles doesn't work

### ISSUE THREAD

**Issue by schmidex** [pyrocms/pyrocms#5052]
Pyro 3.7

Steps to reproduce:
Change the CP language to anything else than English and visit the roles-table at `admin/users/roles`.
-> `admin`,`guest` and `user` are gone.
Same happens when trying to attach roles to a user. If the CP ist that to anything else than english you can't attach admin,user or guest role because they're missing in the dropdown.

Update:
Seems like you can't even edit a user anymore because of this problem. Saving a usersprofile in the control panel results in a `Call to a member function getId() on null` error.

**Comment by RyanThompson** [comment]
This has been resolved. But the roles will need to be re-saved so data for the fallback exists. This stems from an installation issue where everything was seeded in `en` regardless of configuration.
