### ISSUE TITLE
Creating page with 'nn' as slug gives 404 in site

### ISSUE THREAD

**Issue by ericleversen** [pyrocms/pyrocms#5053]
**Describe the bug**
A Page with slug=`nn` will cause a 404 error when trying to access from the site

**To Reproduce**
1. Login to Admin
2. Create a page
3. Use NN for name, thus giving it nn for slug
4. Save
5. Go to site and hit the page's link.
6. See 404 error

**Expected behavior**
The page shows be rendered properly.

**Screenshots**
Attached shots of Create Page, Site's nav with link in it; 404 after hitting link.

**Additional context**
-slugs= `nnn` and `nn-n` work properly

![Screen Shot 2019-12-31 at 1 49 32 PM](https://user-images.githubusercontent.com/1933891/71632580-bd776100-2bd4-11ea-8925-89a8168e84f3.png)
![Screen Shot 2019-12-31 at 1 46 13 PM](https://user-images.githubusercontent.com/1933891/71632581-bd776100-2bd4-11ea-9c1e-38d02a0df548.png)
![Screen Shot 2019-12-31 at 1 45 56 PM](https://user-images.githubusercontent.com/1933891/71632582-bd776100-2bd4-11ea-9f74-86a2b87a0838.png)

**Comment by RyanThompson** [comment]
Lol how did you come across this? Turns out `nn` and `aa` (my test) are both qualified locale abbreviations. We should validate against those but they are not supported because of URI / path hinting for locales.

**Comment by ericleversen** [comment]
> Lol how did you come across this?

Don't ya just love weird edge cases like this?

I was doing a quick test of a new install and I entered N for the first one.
Then entered NN for the second one and voila.

Thx for the fix.
