### ISSUE TITLE
Character counter not working; JS code at fault

### ISSUE THREAD

**Issue by ericleversen** [pyrocms/pyrocms#5054]
**Describe the bug**
The character counter does not work

**To Reproduce**
-Go to a field with character counter.
-The count is blank but the words are there. See attached
![Screen Shot 2020-01-03 at 11 48 41 AM](https://user-images.githubusercontent.com/1933891/71739427-0589c400-2e1f-11ea-8d45-23d6e5021109.png)
-Type in field and the counter remains blank

**Expected behavior**
Characters are counted

**System**
-Pyro v3.7

**Additional context**
I altered the attached `input.js` to get it to work. See lines 10 and 54.
I  removed the code from the Initialize function so it runs on load. I'm not a JS expert so I would assume there's a better way to do it.
[input.js.zip](https://github.com/pyrocms/pyrocms/files/4020225/input.js.zip)

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/text-field_type/commit/cd41becc5f7fb43fb1f717570044c7eab427c498

**Comment by RyanThompson** [comment]
Thank you for the report :-)
