### ISSUE TITLE
[Tag Field-Type] Causing Error saving a post (getConfig() on null) 

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#5055]
On posts ~2.6.0 and streams-platform 1.7, "anomaly/tags-field_type": "~2.4.0", , trying to save a post i get a complaint like this. No matter if i enter or don't enter a tag.

So right now it seems like posts is not functioning at all. Anyone who can verify this?

![bild](https://user-images.githubusercontent.com/31292231/71815606-4f251980-3080-11ea-9fa6-3db1c7a2bc8d.png)

**Comment by Pixney-William** [comment]
Obv works with a conditional there for !field , but not sure that is the correct solution for this @RyanThompson

**Comment by Pixney-William** [comment]
Does it have anything to do with:
https://github.com/anomalylabs/upload-field_type/commit/5e92ee69da13ec07138eceeb94ef5af02439f530

@RyanThompson

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/tags-field_type/commit/0c0474ca97565e16d6bf422ece88a872c771177f
