### ISSUE TITLE
Can't properly use jQuery: Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by protectedfor** [pyrocms/pyrocms#5056]
**Describe the bug**
I'm trying to use jQuery in my project.
Getting error:
`Uncaught ReferenceError: $ is not defined`

**To Reproduce**
1. In theme's `webpack.min.js` add `jquery` and `initialize.js`
2. Try to use `$` in `initialize.js` file
3. Reload page

**Expected behavior**
Proper work of jquery

**Additional context**
Here is my `webpack.min.js`

```
mix
  .js('node_modules/jquery/dist/jquery.min.js', 'resources/js/vendor')
  .js('resources/js/theme/initialize.js', 'resources/js/vendor')
  .sass('resources/scss/theme/theme.scss', 'resources/css')
  .options({
    processCssUrls: false
  });
```
in `package.json` I use `"jquery": "^3.2"`

What am I missing?

Thanks.

**Comment by protectedfor** [comment]
Hm......seems I've got tired.....it's a really stupid issue from me.

I have fixed it.

I've just replaces method `.js` to `.copy` in my `webpack.min.js` :)

Sorry.

**Comment by Pixney-William** [comment]
Then ill close it :)
