### ISSUE TITLE
Sitemap and httpcache problems when posts does not exist.

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#5057]
Delete all posts on the site. Turn httpcache on. Run httpcache:warm

You will get this error:

![image](https://user-images.githubusercontent.com/31292231/72975271-cd97f000-3dd0-11ea-82f0-fdf6022d4737.png)

Visiting that url you see that the `$repository` is null in the sitemapcontroller line 65 
![image](https://user-images.githubusercontent.com/31292231/72975346-f15b3600-3dd0-11ea-8365-aceb1eec4cc6.png)

If you create a post. DO NOT publish it. You get this error when running httpcache:warm

![image](https://user-images.githubusercontent.com/31292231/72975450-1e0f4d80-3dd1-11ea-9733-ed86840132cd.png)

But it is now possible to visit the sitemap.xml url without errors.

If you now PUBLISH the post. Everything works fine!

**Comment by fryiee** [comment]
@Pixney-William fixed in sitemap-extension v2.2.14. Was happening irrespective of HTTP cache, just whenever the sitemap would generate at the index with a repository that was empty.
