### ISSUE TITLE
Post edit error if you changed system language in 3.7

### ISSUE THREAD

**Issue by fatihalp** [pyrocms/pyrocms#5058]
1- Install fresh pyrocms 3.7 in English
2- Change system language to Turkish and activate only that language. 
3- Use admin panel language in English.
4- When you edit post it will give this error:

![image](https://user-images.githubusercontent.com/219454/73177819-06153200-4121-11ea-9f61-6ab31f34f39b.png)

```
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Argument 2 passed to Anomaly\PostsModule\Post\Form\Command\AddEntryFormFromPost::__construct() must implement interface Anomaly\PostsModule\Post\Contract\PostInterface, null given, called in C:\wamp64\www\pyrocms\core\anomaly\posts-module\src\Http\Controller\Admin\PostsController.php on line 87
```

**Comment by fatihalp** [comment]
we tested it fixed with https://github.com/anomalylabs/streams-platform/pull/690


@RyanThompson

**Comment by RyanThompson** [comment]
@fatihalp has this been resolved? I know we had a number of off-thread chats about it in Slack. Just want to make sure you're good before closing. IIRC we fixed the bug and corrected your data that was corrupted from it prior.

**Comment by fatihalp** [comment]
We needed to fork stream platform add whereOR to make it work with all conditions @RyanThompson

**Comment by fryiee** [comment]
@RyanThompson and @fatihalp - is this still an issue?

**Comment by fatihalp** [comment]
beacuase of this problem we're always installing pyro in English. Didn't check lately.
