### ISSUE TITLE
Ion_auth =& sign with php 7.2

### ISSUE THREAD

**Issue by szabogtamas** [pyrocms/pyrocms#5059]
**Cannot use result of built-in function in write context error**
Pyro CMS won't start because of a fatal error caused by line 704 of Ion_auth.php

**To Reproduce**
Install Pyro CMS on a remote server running php 7.2 (I did it with the autoinstall function of hostinger)

**Expected behavior**
Just go on to the homepage

**Temporary fix**
Changing =& to = solves the issue for now.

**Comment by RyanThompson** [comment]
We're not supporting v2 anymore :-/ 

That said I am glad it was a simple fix!
