### ISSUE TITLE
[Multiple field types] Stop using Cache for config keys and change to crypt.

### ISSUE THREAD

**Issue by edster** [pyrocms/pyrocms#5061]
**Describe the bug**
Cache for config keys in `field_types` keeps breaking due to expirations.

**To Reproduce**
1. Open a ft using cached config keys
2. Leave the page open for a short period of time
3. Can no longer use the AJAX as the config cache busts.

**Expected behavior**
Config is always available.

**Additional context**
Multiple FT: https://github.com/anomalylabs/multiple-field_type/pull/40
Relationship FT: https://github.com/anomalylabs/relationship-field_type/pull/25
File FT: https://github.com/anomalylabs/file-field_type/pull/33
Files FT: https://github.com/anomalylabs/files-field_type/pull/26
Image FT: https://github.com/anomalylabs/image-field_type/pull/21

**Comment by edster** [comment]
Added Files FT

**Comment by edster** [comment]
Added File FT

**Comment by edster** [comment]
Added image FT

**Comment by RyanThompson** [comment]
Killed it! Many many thanks 💯
