### ISSUE TITLE
[textarea_fieldType] - Default value not populating textarea

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#5062]
Steps to rep:
1) Create a migration for a page where you want to add a textarea to it.
2) Enter a default value for the textarea
3) Migrate and go checkout the page. Default value not filled. But if you look under fields, the value is there as default. 

I will fill it out more..

**Comment by RyanThompson** [comment]
Resolved at some point. but tested and works (field_type.config.default_value). Share migration maybe.
