### ISSUE TITLE
Pyrocms upgrade from 3.5 to 3.7

### ISSUE THREAD

**Issue by chrisjk123** [pyrocms/pyrocms#5063]
As I was going through the [docs](https://pyrocms.com/documentation/pyrocms/3.7/prologue/upgrade-guide), to update my composer dependencies I was missing one being: [anomaly/streams-platform](https://github.com/pyrocms/pyrocms/blob/3.7/composer.json#L26).

Unfortunately, it appears I can't include this and the repo's `twig` views rely on it. Had left my mac on all night and it was still stuck on this in my terminal windows:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
```

**Comment by edster** [comment]
This can happen with big jump in versions.

Delete the anomaly folder in vendor directory and composer update.
