### ISSUE TITLE
All links are broken after private_storage_adapter 1.0.2 update

### ISSUE THREAD

**Issue by fatihalp** [pyrocms/pyrocms#5064]
We use like this and our image links are broken:

`file(setting_value('.....logo_web')).url `

I think this commit broke: 

https://github.com/anomalylabs/private_storage_adapter-extension/commit/a89f62b479fbaf17bc7fc11813bc6919513c5d5c

**Comment by RyanThompson** [comment]
Fixed! And bumped minor versions for that root correction.
