### ISSUE TITLE
Page types and files field sort order

### ISSUE THREAD

**Issue by lauraevoluted** [pyrocms/pyrocms#5067]
**Describe the bug**
When a page type has a [files field](https://pyrocms.com/documentation/files-field-type/2.2) it creates a table (prefix_pages_pagetype_field_name) to store each linked entry, with a sort column.

When displaying the files on the frontend, the order is correct. The files are not shown in the correct order in the admin.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a page type and a file_s_ field type
1. Assign that field to the page type
1. Create a page and select the type you just created
1. Upload multiple files to the field
1. Drag and drop to reorder them
1. Save
1. The files will be in a different order in the admin, but if you view on the frontend (you may need to setup a twig to see it!) it will be in the order you set.

**Expected behaviour**
Files displayed in the same order in the admin and frontend.

**Screenshots**

Field and query shown in admin:
![Screenshot_2020-04-14_at_10_23_10](https://user-images.githubusercontent.com/47743931/79208680-463fa300-7e3a-11ea-9e52-80ab85898223.png)

Result of query in database, I've just put the sort order at the beginning to make it easier to see:
![Screenshot 2020-04-14 at 10 24 50](https://user-images.githubusercontent.com/47743931/79208700-50fa3800-7e3a-11ea-8faa-eb906e873b58.png)

Same query on frontend, files are in the correct order. This is just `pages.downloads` looped through in the twig file, no core code has changed:
![Screenshot_2020-04-14_at_10_26_39](https://user-images.githubusercontent.com/47743931/79208875-928ae300-7e3a-11ea-811f-f1912bc1da2f.png)

The queries are the same but something is changing between the query executing and the files being shown on the page.

**Desktop (please complete the following information):**
Not sure this is relevant in this case, seems to happen wherever.

**Comment by RyanThompson** [comment]
This may have been resolved with https://github.com/anomalylabs/files-field_type/commit/6de3762895c2e421eb3700344e09dd548ed88d41 and https://github.com/anomalylabs/files-field_type/commit/3207995ff2e5a19b2748318bbd4d632c800e990e. 

Please reopen if this issue persists. My apologies for not following up.
