### ISSUE TITLE
[Posts Module] Cannot adjust base URL in permalink

### ISSUE THREAD

**Issue by mallardduck** [pyrocms/pyrocms#5069]
**Is your feature request related to a problem? Please describe.**
I'd love to be able to have more robust configuration control over the posts module's Permalinks. The date format can be controlled - however it'd be even cooler if we could control the URL/Permalink structure of the 'root area' for Posts as well ad categories and tags.
(Think similar to WP's settings for posts - what exists is really close, just slightly less configurable)

**Describe the solution you'd like**
At a minimum it would be great if ENV settings could control the base URL structure for all posts. Even better would be if it's possible to set Posts via a Settings Module integration.

**Describe alternatives you've considered**
_Directly modifying the routes defined in the post modules service provider._
**CON:** Is not intended to be user editable. Would require a composer hook/plugin to do it 'clean' (automatic patch) so updates don't change URL structures.

_Using Server based rewrite rules to transparently rewrite `/post/` to `blog` - or which ever base URL._
**CON:** Server dependent, makes working in different types of Dev and Prod environments harder. Creates a server dependent config process for desired URL structures. And - more important - won't work with URLs generated by other areas of site.

**Additional context**
By default the post_module only supports URLs like:

- /posts
- /posts/my-cool-post
- /posts/tags/cool
- /posts/categories/software-dev

The requested changes would allow people to set the `/posts/` part to any string they wish. So they could do:

- /blog
- /blog/my-cool-post
- /blog/tags/cool
- /blog/categories/software-dev

**Comment by mallardduck** [comment]
First pass at addressing this here - https://github.com/anomalylabs/posts-module/pull/54

Initially I tried to implement with Settings Module but am not familiar enough with Pyro's execution path/order to understand how to make that work out. Either way this PR would allow simple access to adjusting the posts permalinks and could be expanded on later.

Hope this helps as it'd be a great feature to have. Let me know in the PR if there's any feedback on how to improve the current implementation.

**Comment by RyanThompson** [comment]
Thank you for the PR!
