### ISSUE TITLE
Composer v2.0

### ISSUE THREAD

**Issue by mmodler** [pyrocms/pyrocms#5070]
Platform 1.7

There are some issues with psd-0 autoloading which will cause troube with composer 2.0:

> Deprecation Notice: Class Anomaly\Streams\Platform\Cache\Command\CacheConfig located in /vendor/anomaly/streams-platform/src\Config\Command\CacheConfig.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Anomaly\Streams\Platform\Ui\Form\Command\GetTableCriteria located in /vendor/anomaly/streams-platform/src\Ui\Table\Command\GetTableCriteria.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by fryiee** [comment]
@mmodler @RyanThompson fixed (finally) in 1.7.33 and 1.6.192

**Comment by mmodler** [comment]
Now with composer 2:

The "anomaly/streams-composer-plugin" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
