### ISSUE TITLE
[Install] Call to a member function getId() of null

### ISSUE THREAD

**Issue by lprocx** [pyrocms/pyrocms#5071]
Hi all,

I'm trying to run pyrocms on Ubunto 18.04 with nginx. I found a page that helped me with it [(](https://websiteforstudents.com/setup-pyrocms-on-ubuntu-16-04-17-10-18-04-with-nginx-mariadb-and-php-7-1-support/) and I got far enough that I have the installer on screen. 

After filling in all required information i start the installation, but it get's an 500 error with the following logging:

> [2020-05-29 00:43:49] local.ERROR: Call to a member function getId() on null {"url":"http://www.****.com/installer/run/46","identifier":"2d23743d-4df9-468e-ae0c-148ecb07876a","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getId() on null at /var/www/html/pyrocms/core/anomaly/users-module/src/User/UserSeeder.php:95)
[stacktrace]
#0 [internal function]: Anomaly\\UsersModule\\User\\UserSeeder->run()
#1 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#2 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#4 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#5 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(124): Illuminate\\Container\\Container->call(Array)
#6 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(44): Illuminate\\Database\\Seeder->__invoke()
#7 /var/www/html/pyrocms/core/anomaly/users-module/src/UsersModuleSeeder.php(23): Illuminate\\Database\\Seeder->call('Anomaly\\\\UsersMo...')
#8 [internal function]: Anomaly\\UsersModule\\UsersModuleSeeder->run()
#9 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#10 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(124): Illuminate\\Container\\Container->call(Array)
#14 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(63): Illuminate\\Database\\Seeder->__invoke()
#15 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php(122): Illuminate\\Database\\Console\\Seeds\\SeedCommand->Illuminate\\Database\\Console\\Seeds\\{closure}()
#16 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(64): Illuminate\\Database\\Eloquent\\Model::unguarded(Object(Closure))
#17 /var/www/html/pyrocms/vendor/anomaly/streams-platform/src/Database/Seeder/Console/SeedCommand.php(40): Illuminate\\Database\\Console\\Seeds\\SeedCommand->handle()
#18 [internal function]: Anomaly\\Streams\\Platform\\Database\\Seeder\\Console\\SeedCommand->handle()
#19 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#20 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#21 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#22 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#23 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#24 /var/www/html/pyrocms/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#25 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#26 /var/www/html/pyrocms/vendor/symfony/console/Application.php(1001): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#27 /var/www/html/pyrocms/vendor/symfony/console/Application.php(271): Symfony\\Component\\Console\\Application->doRunCommand(Object(Anomaly\\Streams\\Platform\\Database\\Seeder\\Console\\SeedCommand), Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#28 /var/www/html/pyrocms/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#29 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#30 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Console/Application.php(182): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#31 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(275): Illuminate\\Console\\Application->call('db:seed', Array, NULL)
#32 /var/www/html/pyrocms/vendor/anomaly/streams-platform/src/Installer/Console/Command/LoadModuleSeeders.php(56): Illuminate\\Foundation\\Console\\Kernel->call('db:seed', Array)
#33 [internal function]: Anomaly\\Streams\\Platform\\Installer\\Console\\Command\\LoadModuleSeeders->Anomaly\\Streams\\Platform\\Installer\\Console\\Command\\{closure}(Object(Anomaly\\Streams\\Platform\\Console\\Kernel))
#34 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Object(Closure), Array)
#35 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(78): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#36 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#37 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#38 /var/www/html/pyrocms/core/anomaly/installer-module/src/Http/Controller/InstallerController.php(145): Illuminate\\Container\\Container->call(Object(Closure))
#39 [internal function]: Anomaly\\InstallerModule\\Http\\Controller\\InstallerController->run(Object(Illuminate\\Foundation\\Application), '46')
#40 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#41 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('run', Array)
#42 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Anomaly\\InstallerModule\\Http\\Controller\\InstallerController), 'run')
#43 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#44 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#45 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/html/pyrocms/vendor/anomaly/streams-platform/src/Http/Middleware/CheckForMaintenanceMode.php(91): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Anomaly\\Streams\\Platform\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /var/www/html/pyrocms/vendor/anomaly/streams-platform/src/Http/Middleware/HttpCache.php(88): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Anomaly\\Streams\\Platform\\Http\\Middleware\\HttpCache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /var/www/html/pyrocms/core/anomaly/redirects-module/src/Http/Middleware/RedirectDomains.php(32): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Anomaly\\RedirectsModule\\Http\\Middleware\\RedirectDomains->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /var/www/html/pyrocms/core/anomaly/users-module/src/Http/Middleware/AuthorizeRoutePermission.php(149): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#56 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Anomaly\\UsersModule\\Http\\Middleware\\AuthorizeRoutePermission->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /var/www/html/pyrocms/core/anomaly/users-module/src/Http/Middleware/AuthorizeControlPanel.php(44): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Anomaly\\UsersModule\\Http\\Middleware\\AuthorizeControlPanel->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /var/www/html/pyrocms/core/anomaly/users-module/src/Http/Middleware/AuthorizeModuleAccess.php(54): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#62 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Anomaly\\UsersModule\\Http\\Middleware\\AuthorizeModuleAccess->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /var/www/html/pyrocms/core/anomaly/users-module/src/Http/Middleware/AuthorizeRouteRoles.php(139): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#65 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Anomaly\\UsersModule\\Http\\Middleware\\AuthorizeRouteRoles->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /var/www/html/pyrocms/core/anomaly/users-module/src/Http/Middleware/CheckSecurity.php(47): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#68 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Anomaly\\UsersModule\\Http\\Middleware\\CheckSecurity->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /var/www/html/pyrocms/core/anomaly/installer-module/src/Http/Middleware/CheckIfInstallerExists.php(72): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#71 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Anomaly\\InstallerModule\\Http\\Middleware\\CheckIfInstallerExists->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /var/www/html/pyrocms/vendor/anomaly/streams-platform/src/Http/Middleware/ApplicationReady.php(34): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#74 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Anomaly\\Streams\\Platform\\Http\\Middleware\\ApplicationReady->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /var/www/html/pyrocms/vendor/anomaly/streams-platform/src/Http/Middleware/CheckLocale.php(32): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#77 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Anomaly\\Streams\\Platform\\Http\\Middleware\\CheckLocale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 /var/www/html/pyrocms/vendor/anomaly/streams-platform/src/Http/Middleware/SetLocale.php(114): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#80 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Anomaly\\Streams\\Platform\\Http\\Middleware\\SetLocale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#81 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#82 /var/www/html/pyrocms/vendor/anomaly/streams-platform/src/Http/Middleware/PrefixDomain.php(71): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#83 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Anomaly\\Streams\\Platform\\Http\\Middleware\\PrefixDomain->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#84 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#85 /var/www/html/pyrocms/vendor/anomaly/streams-platform/src/Http/Middleware/ForceSsl.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#86 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Anomaly\\Streams\\Platform\\Http\\Middleware\\ForceSsl->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#87 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#88 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#89 /var/www/html/pyrocms/vendor/anomaly/streams-platform/src/Http/Middleware/VerifyCsrfToken.php(80): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#90 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Anomaly\\Streams\\Platform\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#91 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#92 /var/www/html/pyrocms/vendor/anomaly/streams-platform/src/Http/Middleware/PoweredBy.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#93 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Anomaly\\Streams\\Platform\\Http\\Middleware\\PoweredBy->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#94 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#95 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#96 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#97 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#98 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#99 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#100 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#101 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#102 /var/www/html/pyrocms/vendor/anomaly/streams-platform/src/Http/Middleware/ProxySession.php(32): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#103 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Anomaly\\Streams\\Platform\\Http\\Middleware\\ProxySession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#104 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#105 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#106 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#107 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#108 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#109 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#110 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#111 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#112 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#113 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#114 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#115 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#116 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#117 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#118 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#119 /var/www/html/pyrocms/vendor/anomaly/streams-platform/src/Http/Kernel.php(119): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#120 /var/www/html/pyrocms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Anomaly\\Streams\\Platform\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#121 /var/www/html/pyrocms/vendor/barryvdh/laravel-httpcache/src/CacheKernel.php(27): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#122 /var/www/html/pyrocms/vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(85): Barryvdh\\HttpCache\\CacheKernel->handle(Object(Illuminate\\Http\\Request), 1, true)
#123 /var/www/html/pyrocms/vendor/symfony/http-kernel/HttpCache/HttpCache.php(477): Symfony\\Component\\HttpKernel\\HttpCache\\SubRequestHandler::handle(Object(Anomaly\\Streams\\Platform\\Http\\CacheKernel), Object(Illuminate\\Http\\Request), 1, true)
#124 /var/www/html/pyrocms/vendor/symfony/http-kernel/HttpCache/HttpCache.php(450): Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache->forward(Object(Illuminate\\Http\\Request), true)
#125 /var/www/html/pyrocms/vendor/symfony/http-kernel/HttpCache/HttpCache.php(344): Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache->fetch(Object(Illuminate\\Http\\Request), true)
#126 /var/www/html/pyrocms/vendor/symfony/http-kernel/HttpCache/HttpCache.php(222): Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache->lookup(Object(Illuminate\\Http\\Request), true)
#127 /var/www/html/pyrocms/public/index.php(55): Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache->handle(Object(Illuminate\\Http\\Request))
#128 {main}
"} 

**To Reproduce**
1. Follow tutorial on provided link with OS Ubuntu 18.04 ( i used Mysql instead of MariaDB)
2. Installation crashing

**Expected behavior**
Expected to install pyrocms according to plan

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser (installer opened in) Chrome
 - Version 83.0.4103.61

Anybody an idea on how to fix this? The OS is installed freshly this tuesday. Only some nginx , java and random packages are installed. Nothing special

**Comment by spartokos99** [comment]
I have the same issue on Xampp (Windows) with php 7.4.

I fixed the folder permissions and installed all extensions. Still doesn't work.
Help pls

**Comment by tobiit** [comment]
I have the same issue on Ubuntu 18.04 and Ubuntu 20.04 - all folder permissions are set. Still doesn't work.
Help pls.

**Comment by RyanThompson** [comment]
PHP 7.4 was not supported with `anomaly/streams-platform@1.7` but 1.8 which is included in PyroCMS v3.8 does support it: https://pyrocms.com/posts/pyrocms-v3-8

I believe that was the cause of this issue. Please reopen if the issue persists on `anomaly/streams-platform@1.8`, but it appears to be resolved.
