### ISSUE TITLE
[streams-platform] Running phpunit breaks commented env lines and doesn't clean up after itself.

### ISSUE THREAD

**Issue by fryiee** [pyrocms/pyrocms#5073]
**Describe the bug**

**To Reproduce**
1. Run PHPUnit on a project that has more than one commented env line, e.g.
```
#TEST=TEST
#TEST2=TEST2
#TEST3=TEST3
```
2 See the following
```
#TEST=TEST
1=#TEST2=TEST2
2=#TEST3=TEST3
```
3. In addition, the test env variable `DUMMY_TEST` is present.

**Expected behavior**
PHPUnit tests clean up after themselves in setUp/tearDown, and don't mess with existing commented lines when running Read/Write/ReloadEnvironmentFile tests.

**Comment by RyanThompson** [comment]
Skipping for now: https://github.com/laravel-streams/streams-core/commit/8b2bc765b74358fadb2b2ee25ebf6f1b5942b4f4
