### ISSUE TITLE
Sitemap extension is issuing a 500 error

### ISSUE THREAD

**Issue by JorodriguezNA** [pyrocms/pyrocms#5074]
Viewing the sitemap at /sitemap.xml gives a 500 error:

"Cannot use object of type Closure as array"

At line 59: 

`if (isset($configuration['repository'])) {`

You can replicate by going to https://pyrocms.com/sitemap.xml

Or just viewing the sitemap yourself on your site if you have the most stable version installed.

**Comment by RyanThompson** [comment]
Weird! Quick patch: https://github.com/anomalylabs/sitemap-extension/commit/f4d0dbc76bb3b7401749e4ff8f3a1bbf95dd0aff

Thanks for the heads up!
