### ISSUE TITLE
Error installing pyrocms

### ISSUE THREAD

**Issue by ShuKTan** [pyrocms/pyrocms#5076]
getting error while installing (xampp & Windwos)

php artisan install command gives out below error.

In MigrateCommand.php line 58:

  Too few arguments to function Illuminate\Database\Console\Migrations\MigrateCommand::__construct(), 1 passed in C:\xampp\htdocs\pyro\vendor\anomaly\streams-platform\src\Database\Migration\MigrationServiceProvider.php on line 88 and exactly 2 expected

**Comment by alancolant** [comment]
Same error here

**Comment by RyanThompson** [comment]
This issue was resolved: https://github.com/laravel-streams/streams-core/commit/9e3e35c5a3ecbd078a6baf214510979c8ce2cc68#diff-ae0c55256b98cb19b118cfb9e70de6396933e1aaed29153f8115ec7a9b8b6302
