### ISSUE TITLE
[Blocks Module] Error on create a page with faqs block

### ISSUE THREAD

**Issue by vajihemrp** [pyrocms/pyrocms#5079]
Hi all,
After installing faqs_block extension when  I want to create a new default page. This error is appeared:

Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Method Anomaly\BlocksModule\Block\BlockCollection::__toString() must not throw an exception, caught ErrorException: Unexpected token "operator" of value ">".

Symfony\Component\Debug\Exception\FatalErrorException 
…\vendor\anomaly\streams-platform\src\Addon\FieldType\FieldType.php 

Anybody an idea on how to fix this?

**Comment by RyanThompson** [comment]
How exactly are you getting this? I doubt this is the block itself. Perhaps something in the template or theme? 

I have a local v3.7/v3.8 and faqs_block-extension works as intended out of the box. 

Can you see what you can dig up?
