### ISSUE TITLE
[files-module] [pyrocms 3.8]Force delete folder error

### ISSUE THREAD

**Issue by aidanwatt** [pyrocms/pyrocms#5081]
**Describe the bug**

When force deleting a folder from trash an error is thrown and the operation doesn't fully complete.

`League \ Flysystem \ FileNotFoundException
File not found at path: folder_name`

**To Reproduce**
1. Create a new folder
2. Delete the folder
3. Goto trash and force delete folder

**Expected behavior**
No error thrown, operation completes

**Additional context**
I think this may be caused by this method on \Anomaly\FilesModule\Disk\Adapter\AdapterFilesystem getting itself into a loop:

```
public function deleteDir($dirname)
    {
        $result = parent::deleteDir($dirname);

        if ($result && $resource = $this->get($dirname)) {
            return $this->dispatch(new DeleteFolder($resource));
        }

        return $result;
    }
```

**Comment by RyanThompson** [comment]
This has been resolved: https://github.com/anomalylabs/files-module/commit/a31e5c62d70e24e7ad3437cc8d8bc34ac83e1485

Thanks for the report!
