### ISSUE TITLE
[Blocks Module] Missing style and functions from Block field type

### ISSUE THREAD

**Issue by BubeCPH** [pyrocms/pyrocms#5086]
**Describe the bug**
Block field type doesn't load the style and script correctly

**To Reproduce**
1. Run composer create-project pyrocms/pyrocms pyro38-test
2. Complete install
3. Don't install any custom themes, modules or extensions
4. Login to CP
5. Navigate to Pages Module
6. Add new field type "Blocks"
7. Assign the newly created field to Page type "Default"
8. Edit the page "Welcome"
9. Add a new block to the page 
10. The block's heading isn't styled and the functions "Collaps", "Add above" etc.  aren't working
Screendump from PyroCMS 3.8.3 with anomaly/blocks-module v1.3.20:
![image](https://user-images.githubusercontent.com/63174222/100667232-836d8c80-335a-11eb-9d90-d9e536faeebd.png)

**Expected behavior**
This is what I expected to see, screendump from PyroCMS 3.7 with anomaly/blocks-module v1.3.20:
![image](https://user-images.githubusercontent.com/63174222/100667009-4d300d00-335a-11eb-8491-265c59dae277.png)

**Desktop (please complete the following information):**
 - OS: macOS 11
 - Browser: Chrome

**Comment by RyanThompson** [comment]
Thank you! Fixed: https://github.com/anomalylabs/blocks-module/commit/0054229faf29f4128d604a4c909cbcab3a79516b
