### ISSUE TITLE
Uprade an older version of the package that was developed mainly on top of CodeIgniter

### ISSUE THREAD

**Issue by moroccan-webdev** [pyrocms/pyrocms#5087]
Hello @RyanThompson I have a project built developed from the early versions which was built on the top of CodeIgniter and I would like to Upgrade the whole project to the latest version which is built on the top of the framework Laravel. 

Please If there is any kind of information that that can help me out fix some bugs and build newer functionalities, It would be very helpful.

Thanks in advance.

**Comment by RyanThompson** [comment]
Hello! It really depends on the details of the project. Please feel free to DM me on Discord: https://discord.gg/RjywDG2 @RyanThePyro
