### ISSUE TITLE
[Addon Module] Can't view addons - Missing required parameters for route

### ISSUE THREAD

**Issue by BubeCPH** [pyrocms/pyrocms#5091]
**Describe the bug**
It isn't possible to access an addon in "Addons Module / Addons".
Pyro is throwing the ErrorException _An exception has been thrown during the rendering of a template ("Missing required parameters for [Route: anomaly.module.addons::composer.download] [URI: admin/addons/download/{addon}].")._

**To Reproduce**
1. Create a fresh PyroCMS 3.8 project
2. Navigate to "Addons Module / Addons" (/admin/addons)
3. Click on ![image](https://user-images.githubusercontent.com/63174222/102468024-4a6b3280-4051-11eb-8751-84325343148d.png)

**Expected behavior**
I expect to se the addon details.

**Screenshots**
![image](https://user-images.githubusercontent.com/63174222/102468119-6c64b500-4051-11eb-9f9b-78dd0e2b0bb3.png)

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/addons-module/commit/662ca66fdf7921072719260c5da8776185140150

Thank you for the report!
