### ISSUE TITLE
3.8 first installation error (before create .env)

### ISSUE THREAD

**Issue by spektra2147** [pyrocms/pyrocms#5094]
With php artisan install the first installation gets an error. I think it is because it cannot find the .env file.

Installing with php artisan install --ready.

![Ekran Resmi 2021-02-03 11 32 56](https://user-images.githubusercontent.com/39536659/106719970-f70a6f00-6613-11eb-8c67-7c4a544cd0eb.png)

**Comment by ryanlholt** [comment]
@spektra2147 I'm also experiencing this issue. Second run is successful.

**Comment by gnovaro** [comment]
Duplicated issue #5098
