### ISSUE TITLE
[streams-composer-plugin] Composer 2 Upgrade Error

### ISSUE THREAD

**Issue by spektra2147** [pyrocms/pyrocms#5097]
I want to migrate composer 2.0. I fork the required package and changed the fixed composer versions in the composer.json file. But I am getting this error.

Can you create version 2.0 of the required package?

------------------

Package operations: 1 install, 0 updates, 0 removals
  - Installing visiosoft/streams-composer-plugin (v2.0): Extracting archive

Fatal error: Class Anomaly\StreamsComposerPlugin\Plugin contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Composer\Plugin\PluginInterface::deactivate, Composer\Plugin\PluginInterface::uninstall) in /Users/vedatakdogan/Desktop/vedat/oc0902/vendor/visiosoft/streams-composer-plugin/src/Plugin.php on line 14

**Comment by spektra2147** [comment]
@fatihalp

**Comment by spektra2147** [comment]
@RyanThompson

**Comment by RyanThompson** [comment]
This has been resolved in 3.9
