### ISSUE TITLE
Installation migration problem

### ISSUE THREAD

**Issue by gnovaro** [pyrocms/pyrocms#5100]
Before run composer and run the command php artisan install

**Expected behavior**

**Screenshots**
![imagen](https://user-images.githubusercontent.com/270990/114267397-a04a5880-99fb-11eb-8e6b-4812454c9ae0.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu Linux
 - Browser [e.g. chrome, safari] ---
 - Version [e.g. 22] --
 - Database Engine: **MariaDB**

**Comment by RyanThompson** [comment]
It looks like there is no application prefix specified. Closing this as 3.9 fixed a lot of these old issues. Most of the focus is on 4.0 right now which eliminates almost all of these weird issues. It's a simpler system :-/
