### ISSUE TITLE
db:seed not seeding all seeder file

### ISSUE THREAD

**Issue by spektra2147** [pyrocms/pyrocms#5101]
Laravel 8.x seeder not working without specifying class name

- Project seed does not work in the first installation

@fatihalp @RyanThompson

**Comment by edster** [comment]
Run db:seed all-addons
________________________________
From: spektra2147 ***@***.***>
Sent: Monday, April 12, 2021 9:28:46 PM
To: pyrocms/pyrocms ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pyrocms/pyrocms] db:seed not seeding all seeder file (#5101)


Laravel 8.x seeder not working without specifying class name
@fatihalp<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffatihalp&data=04%7C01%7C%7C1a2a9d6de14348914f9208d8fe34a167%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637538849277055917%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=y27ZoVhjdT7ELgK%2Bz05CCksJjo8idvQKAqu6pLmqucY%3D&reserved=0> @RyanThompson<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRyanThompson&data=04%7C01%7C%7C1a2a9d6de14348914f9208d8fe34a167%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637538849277065910%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9CxycyLKTpd3LBaZ96aPNfLkKPrwFzb3Zz14x9m4WtQ%3D&reserved=0>

**Comment by spektra2147** [comment]
Project seed does not work in the first installation. @edster

**Comment by RyanThompson** [comment]
If installed = false and there is nothing installed yet - you should be able to use `--addon=the_addon` to specify an addon path by ref
