### ISSUE TITLE
pyrocms installation error (3.9)

### ISSUE THREAD

**Issue by spektra2147** [pyrocms/pyrocms#5102]
![Ekran Resmi 2021-04-14 08 57 37](https://user-images.githubusercontent.com/39536659/114661368-8bbdd700-9cff-11eb-913a-5616b19cc022.png)

**Comment by spektra2147** [comment]
@RyanThompson @fatihalp

**Comment by spektra2147** [comment]
@RyanThompson I fixed the problem when I fixed the laravel / framework version.("laravel/framework": "v8.36.2")

`"laravel/framework": "v8.36.2"`

Please add this line to your composer.json file.

**Comment by finnito** [comment]
I just saw this problem, too and can verify that @spektra2147's solution works.

**Comment by Eighke** [comment]
Probably due to https://laravel-news.com/laravel-anonymous-migrations if you wanna dig inside @RyanThompson

**Comment by RyanThompson** [comment]
Ya locking this isn't really a solution - digging in now

**Comment by RyanThompson** [comment]
This should be resolved here: https://github.com/laravel-streams/streams-core/commit/9b9104d8d8600f44d5152d56d7c3e975951076be

**Comment by spektra2147** [comment]
@RyanThompson https://prnt.sc/11qqib9

Can't find migration files
