### ISSUE TITLE
Installed via composer in subdirectory; apparent routing issues

### ISSUE THREAD

**Issue by jasonday** [pyrocms/pyrocms#5104]
Seeing the below at install location. I'm attempting to run pyroCMS in a subdirectory. 

![image](https://user-images.githubusercontent.com/748011/114961861-a5fad080-9e37-11eb-9eff-26205ceee30e.png)

- installed to apps/myapps/html/test/pyrocms
- screenshot is url mydomain.com/test/pyrocms/public/
- Ubuntu 18.04 server

**Comment by edster** [comment]
This is a k own issue, you need to point a vhost to the public directory and use that
________________________________
From: Jason Day ***@***.***>
Sent: Thursday, April 15, 2021 7:20:37 PM
To: pyrocms/pyrocms ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pyrocms/pyrocms] Installed via composer in subdirectory; apparent routing issues (#5104)


Seeing the below at install location. I'm attempting to run pyroCMS in a subdirectory.

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F748011%2F114961861-a5fad080-9e37-11eb-9eff-26205ceee30e.png&data=04%7C01%7C%7Cb4ce66025f814bca264908d9007e3960%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637541364386675256%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nr%2FwTunNNofGLVBS%2FVEVBo2OD3IafioKUlWl27FBDpE%3D&reserved=0>

  *   installed to apps/myapps/html/test/pyrocms
  *   screenshot is url mydomain.com/test/pyrocms/public/
  *   Ubuntu 18.04 server
