### ISSUE TITLE
Addon for SASS compilers/filters

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#5109]
Add in legacy compilers via addon if it makes sense. What is the temperature on this?

**Comment by edster** [comment]
This would be great, I don't have the time or resources to update some older sites due to this change.

Being able to get some of the improvements from the new code base without having to redo a bunch of themes would be extremely valuable.

**Comment by finnito** [comment]
Keen! I have some old sites too, and because it removes a step in building/deploying I think.
