### ISSUE TITLE
Abandoned packages

### ISSUE THREAD

**Issue by finnito** [pyrocms/pyrocms#5111]
**Describe the bug**
When running `composer install` I get the following warnings:

```
Package asm89/twig-cache-extension is abandoned, you should avoid using it. Use twig/cache-extension instead.
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
```

I've attached my `composer.json` for reference. Thanks :)

[composer.txt](https://github.com/pyrocms/pyrocms/files/7037223/composer.txt)

**Comment by BubeCPH** [comment]
Replace `fzaninotto/faker` with `fakerphp/faker`
