### ISSUE TITLE
[Files-Module]: Install/Uninstall Migration Errors

### ISSUE THREAD

**Issue by finnito** [pyrocms/pyrocms#5112]
**Describe the bug**
I'm unable to uninstall the files module with artisan.

**To Reproduce**
```
php artisan addon:uninstall anomaly.module.files
In 2016_10_05_221741_anomaly.module.files__make_disks_sortable.php line 25:

  Call to a member function setAttribute() on null
```

```
php artisan migrate --addon=anomaly.module.files
Migrating: 2019_08_02_010559_anomaly.module.files__add_str_id_to_files

In ForwardsCalls.php line 50:

  Call to undefined method Anomaly\FilesModule\File\FileModel::withTrashed()
```

This is using `"anomaly/files-module": "~2.6.0"` in my `composer.json`

**Comment by RyanThompson** [comment]
There was an issue with migrations in the past through our extending Laravel - this should be resolved now on latest: https://github.com/laravel-streams/streams-core/blob/1.9/docs/en/01.prologue/02.change-log.md#191---2021-03-18

**Comment by RyanThompson** [comment]
Anyways, cannot reproduce on latest.
