### ISSUE TITLE
[search-module]: FULLTEXT not supported on sqlite

### ISSUE THREAD

**Issue by finnito** [pyrocms/pyrocms#5113]
**Describe the bug**
 `SQLSTATE[HY000]: General error: 1 near "(": syntax error (SQL: ALTER TABLE fitlytics_search_items ADD FULLTEXT(title,description);)`

**To Reproduce**
`php artisan install --ready` (I've attached my composer.json).

the error occurs in these lines of the `search__create_items_stream` migration of the search module.
```php
{
        app('db')->statement('ALTER TABLE ' . app('db')->getTablePrefix() . 'search_items ADD FULLTEXT(title,description);');
        app('db')->statement('ALTER TABLE ' . app('db')->getTablePrefix() . 'search_items ADD FULLTEXT(searchable);');
    }
```

https://github.com/anomalylabs/search-module/blob/dab96e75616f743ca06c4acf8b88de889257e16b/migrations/2019_06_10_214712_anomaly.module.search__create_items_stream.php#L64

[composer.json.txt](https://github.com/pyrocms/pyrocms/files/7095927/composer.json.txt)

**Comment by RyanThompson** [comment]
If using the search module - SQLite is not an option. Unless maybe using this option: https://www.sqlite.org/fts5.html#:~:text=FTS5%20is%20an%20SQLite%20virtual,instances%20of%20a%20search%20term.

Full-text search is required for the DB search engine though.
