### ISSUE TITLE
Docs, Forums

### ISSUE THREAD

**Issue by KeygenOld** [pyrocms/pyrocms#5115]
Not so much a feature request as pointing out the obvious.

The docs for Pyro are lacking and could use a serious update. I've been testing out a bunch of CMSs this past week and having good docs is crucial, especially for those of us who've never used Twig and are used to templating in systems like WordPress. The worst systems also had the worst docs.

Your control panel is pretty solid and feature-rich compared to others, but once it got to templating, the docs left me hanging. Some parts were completely empty. Consequently, I jumped over to try CraftCMS, and you should take a look at their docs for inspiration. Granted, they have almost a complete lack of documentation about extending the admin/cp unless it relates to making custom plugins and they've had paid versions for some time so probably more resources to focus on the docs.

Your forums seem to have been flooded by bots, to the point where browsing is basically pointless. I'd suggest giving those a good purge. The icons in your forum design also failed to load in my browser and just produced those weird empty rectangles with unicode-like text in them.

Anyway, not trying to be too critical because Pyro is one of the best CMSs I've tried recently. A big positive about Pyro is it's feature-rich control panel and ease of installation (don't get me started on things that require npm and are full of errors and deprecations). The docs might be fine for serious programmers, but for someone like myself who's never used a system like this and isn't a programmer for a day job, it was prohibitive to learning how to work with the system and get up-and-running quickly with the front-end, so figured I'd share my experience. I'm still going to try and build out a site with it and hope this gives you a different perspective from a non-typical user of the software.

Thanks

**Comment by RyanThompson** [comment]
First, thank you for evaluating the software! I am all too aware of the shortcomings, unfortunately. Though, fortunately, I am working to correct them! However, the path is not an easy one nor super quick.

Maintaining forums is not something we are keen on doing, so we will be leaning on our Discord (or Slack in the future, idk, Discord integrations are somewhat lacking) community and StackOverflow integration to increase the visibility within the community. I am going to clean out and end up uninstalling the forum. Made it read-only for now.

I think you nailed it on docs - they are very much written for developers, as this CMS is built for developers to build with and then hand over to their clients. It is NOT designed for non-developers to create things (though it can lend itself do that group, but as you've discovered, has a learning curve). The next iteration of docs will be more aligned with non-developers, as it will be a product in an ecosystem that is already focused on developers (Laravel Streams). The next iteration will also be much more simple in concept (no installer, no compiling, straightforward concepts). 

This post (not live yet, scheduled to for the morning of the 24th of January) explains more of the expectations and roadmap for the future: https://pyrocms.com/posts/laravel-streams-pyrocms-4
