### ISSUE TITLE
BUG: php artisan install does not install properly

### ISSUE THREAD

**Issue by snailcatcher** [pyrocms/pyrocms#5116]
**Describe the bug**
When I try to install pyrocms from scratch with `php artisan install --ready` I get the following error.

```sh
...
31/63 Installing: Sitemap Extension
32/63 Reloading application.
33/63 Seeding: Streams Module
34/63 Seeding: Preferences Module
35/63 Seeding: Pages Module

In Container.php line 1049:

  Target [Anomaly\PagesModule\Type\Contract\TypeRepositoryInterface] is not instantiable while building [Anomaly\PagesModule\Type\TypeSeeder].  
```

**To Reproduce**
1. write a .env which contain your database connection
2. run `php artisan install --ready`
3. wait until error occurs

**Expected behavior**
I expect that I can install pyrocms from scratch

**Environment:**
 - PyroCms Version: v3.9.0
 - OS: Ubuntu Focal

**Comment by snailcatcher** [comment]
I found the same problem in #5106 but this issue isn't solved as mentioned in this issue.

**Comment by RyanThompson** [comment]
I've installed a number of these recently both on PHP 7.4 and 8.0 with no issues.

This was the last fix that cleared up installer issues: https://github.com/anomalylabs/installer-module/commit/4adb3c895babf8d385ebcec17415fcaa2e003ad4#diff-d37edcba5b726cc47c012099e109813c39f9ec3a68fdbfdd1e546d4a4dc4bff8

Did your composer dependencies completely install? Does this occur without the `--ready` flag too? That error would indicate that the dependency was not fully downloaded or the autoloader failed in some way. 

If you are using PHP 7.4, you have to use something like this `php -d memory_limit=-1 /usr/local/bin/composer update` where Composer is v1. If you are using PHP 8 and composer 2 you can simply `composer update` and be done. 

I just confirmed with the below `.env` example.

```
APP_ENV=local
INSTALLED="false"
APP_KEY=WS0bbyMzqTsTqB1zJuwpuOniUsT8Zu7L
APP_DEBUG=true
DEBUG_BAR=false
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=pyrocms-latest
DB_USERNAME=root
DB_PASSWORD="root"
APPLICATION_NAME="Default"
APPLICATION_DOMAIN=127.0.0.1:8000
APPLICATION_REFERENCE=default
DEFAULT_LOCALE=en
APP_TIMEZONE=America/Chicago
APP_URL=http://127.0.0.1:8000
ADMIN_USERNAME=admin
ADMIN_EMAIL=ryan@pyrocms.com
ADMIN_PASSWORD=password
```
