### ISSUE TITLE
Class encrypter does not exist

### ISSUE THREAD

**Issue by iamshulz** [pyrocms/pyrocms#5120]
**Describe the bug**
I am using Laragon for local development environment. Upon trying to access the `http://localhost/_WORK/****/****/public/` to see the website I get this error. `Class encrypter does not exist`

Side question
In Laravel we can do -php artisan serve I am not sure whats the similar command for pyrocms 

**To Reproduce**
1. Go to `http://localhost/_WORK/****/****/public/`

**Expected behavior**
I would be able to see the Website

**Screenshots**
![image](https://user-images.githubusercontent.com/20100579/185110636-7759225b-5c8c-4c4e-abdf-0bf9489216fd.png)

**Additional context**
php version 7.4.19
composer 2

**Comment by RyanThompson** [comment]
Did you first run ‘composer install’ ?

‘php artisan serve’ works all the same with Pyro.

You might need a host name locally to run properly but sounds like you’ve got dependencies missing perhaps

**Comment by RyanThompson** [comment]
Did you first run ‘composer install’ ?

‘php artisan serve’ works all the same with Pyro.

You might need a host name locally to run properly but sounds like you’ve got dependencies missing perhaps

**Comment by iamshulz** [comment]
@RyanThompson not sure what version I am using pyro so I could tell you what version I have but I am using composer 2 and used `composer install --ignore-platform-reqs` then `composer update --no-plugins` 

I noticed that there are skipped installations such as 
`The "anomaly/streams-composer-plugin" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.`
`The "wikimedia/composer-merge-plugin" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.`

![image](https://user-images.githubusercontent.com/20100579/185413256-a965b888-8119-4579-a235-1a83072d4af0.png)

There are some on the few issues I've picked upon running installation on composer 2. Btw Laragon also hosts the project automatically if you're quire familiar with Laragon



On my composer.json
I have these 
```
require: {
        "pyrocms/starter-theme": "~1.0.0",
        "pyrocms/accelerant-theme": "~1.0.0",
}
```

-- UPDATE--
Found pyrocms version its at distribution.php 
```
return [
    'name'        => 'PyroCMS',
    'description' => 'Build better Laravel websites and applications faster with Pyro.',
    'version'     => 'v3.4',
];
```
Guess if I have no other way to fix this I will have to change to `composer 1` and use `PHP 7.2.X`

**Comment by iamshulz** [comment]
So I've used `composer 1` and `PHP 7.2.X`
I am able to install the packages smoothly 
I encountered error in model `Class 'Anomaly\Streams\Platform\Model\Users\UsersRolesEntryModel' not found` and found a solution but the solution gives me a different error
![image](https://user-images.githubusercontent.com/20100579/185439035-bddb2cd7-cfcd-4046-b7ec-a15a9644a485.png)

**Comment by RyanThompson** [comment]
Ahh, so a little older install. PHP 7.4 is what you want, then run composer update again because Symfony has a bunch of polyfills that will adjust to that PHP version.
