### ISSUE TITLE
Some news about PyroCMS?

### ISSUE THREAD

**Issue by Grazouillis** [pyrocms/pyrocms#5121]
Hello,

What a pity, PyroCMS is the best CMS I ever see and it seems it is no longer pampered ?
I see your project is into Laravel 5, and templates and plugins (http://store.pyrocms.com/) are unavailable.
Is PyroCMS abandoned? Do you plan to upgrade it? No developer offers you help to update it?

**Comment by RyanThompson** [comment]
@Grazouillis it's being replaced by it's predecessor: Laravel Streams which is a CMF more than out of the box CMS. 

Still in development but nearing an alpha release on core/api with a preview of UI wrapping up in the next few weeks: https://streams.dev/

It can do everything Pyro can do, but tends to do it ~300% faster and with less effort and resources necessary to use it. And it's 1000% nicer to maintain :-)

**Comment by RyanThompson** [comment]
That said, PyroCMS will continue to see 3.10, 3.11, etc. in order to maintain support with Laravel and continue improving the 3.x branch.
