### ISSUE TITLE
MS Sql database installation error 

### ISSUE THREAD

**Issue by MegaMindVisionary** [pyrocms/pyrocms#5125]
when i try install pyrocms with microsoft sql database i get error as below:
  SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The definition for column 'FULLTEXT' must in
  clude a data type. (SQL: ALTER TABLE default_search_items ADD FULLTEXT(title,description);)

  SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The definition for column 'FULLTEXT' must in
  clude a data type.

  SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The definition for column 'FULLTEXT' must in
  clude a data type.

i found same error using web installation as well. how fix this??

**Comment by RyanThompson** [comment]
Hmm, I am not very familiar with MS Sql DBs. This just uses the Laravel schema utilities. How is this done in Laravel typically?
